### ISSUE TITLE
Connection to Azure SQL DB's shaky 

### ISSUE THREAD

**Issue by akshay-pande** [microsoft/azuredatastudio#16619] opened 2021-08-09 09:41 UTC
Issue Type: <b>Bug</b>

The connection to Azure SQL Server/DB's is extremely shaky. The tool sometimes disconnects 2 min after being connected. And it needs to be reconnected 5-10 times through one single sitting due to expired connections. Is it not possible to create a persistent connection for 8 hours at least?

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-prompt|Red|0.2.7
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-08-09 16:38
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8965 since this seems to be an issue with our retry logic as well. Let us know if you think there's anything else going on here we should know about.

**Closed by Charles-Gagnon** 2021-08-09 16:38 UTC
