### ISSUE TITLE
Unable to connect to SQL Server using Windows Authentication

### ISSUE THREAD

**Issue by Palsternakka** [microsoft/azuredatastudio#20225] opened 2022-08-02 15:38 UTC
- Azure Data Studio Version: 1.38.0
- OS Version: Xubuntu 22.04.1 LTS

**Steps to Reproduce:**

1. Run `kinit` in a terminal, enter credentials
2. Click New Connection in Azure Data Studio
3. Enter Server, select Windows Authentication as Authentication Type
4. Click Connect

After a few seconds this error appears:

![image](https://user-images.githubusercontent.com/41788480/182412594-9ec85a95-0f03-4419-9209-a7b989dc6075.png)

And this appears in `renderer1.log`:

```
[2022-08-02 16:28:35.740] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:10.1.3.7|user:|group:C777F06B-202E-4480-B475-FA416154D458
[2022-08-02 16:28:35.741] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:10.1.3.7|user:|group:C777F06B-202E-4480-B475-FA416154D458
[2022-08-02 16:28:35.742] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:10.1.3.7|user:|group:C777F06B-202E-4480-B475-FA416154D458
```

5. It appears to load forever, however upon clicking Cancel the following lines then appear in `renderer1.log`:

```
[2022-08-02 16:29:23.693] [renderer1] [info] Cancelling connection for URI connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:10.1.3.7|user:|group:C777F06B-202E-4480-B475-FA416154D458
[2022-08-02 16:29:23.693] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:10.1.3.7|user:|group:C777F06B-202E-4480-B475-FA416154D458 (connecting)
[2022-08-02 16:29:23.702] [renderer1] [error] Unfound provider 3: Error: Unfound provider 3
	at P._resolveProvider (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:27806)
	at P.$cancelConnect (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:32068)
	at i._doInvokeHandler (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:13841)
	at i._invokeHandler (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:13525)
	at i._receiveRequest (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:12149)
	at i._receiveOneMessage (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:10827)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:8923
	at n.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at g.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15997)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:110:30556
	at n.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at g.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15997)
	at v._receiveMessage (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21267)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18145
	at n.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at m.acceptChunk (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13358)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12706
	at Socket.w (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:110:13580)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Additional Information:**

Output of `klist`:

```
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: oliver.dalton@DOMAIN.LOCAL

Valid starting     Expires            Service principal
02/08/22 14:59:37  03/08/22 00:59:37  krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL
	renew until 03/08/22 00:59:37
```

Contents of `/etc/krb5.conf`:

```
[libdefaults]
        default_realm = DOMAIN.LOCAL

[realms]
        DOMAIN.LOCAL = {
                kdc = 10.1.0.12
        }
```

Other .NET Core apps running on the same PC using Integrated Security (connection string - `Data Source=SERVER;Integrated Security=true;TrustServerCertificate=true`) are working as expected - I have tried entering this connection string to connect and the same result occurs

~~Also having an issue with other .NET Core apps on the PC - when using Integrated Security a Segmentation Fault is thrown - guessing this could be related to [this](https://github.com/dotnet/SqlClient/issues/1390)?~~

I am able to connect to the same server using SQL Authentication

Does this issue occur when all extensions are disabled?: Yes - no extensions installed

**Comment by cheenamalhotra** [comment] 2022-08-23 05:26
Hi @Palsternakka 

This seems duplicate of #18844 
Closing the issue as it will be fixed with upcoming Aug release (v1.39) this week.

Thanks!

**Closed by cheenamalhotra** 2022-08-23 05:26 UTC
Labels: Bug, Area - Connection, Triage: Done
