### ISSUE TITLE
Unable to open new or existing sql files on v1.18

### ISSUE THREAD

**Issue by splady** [microsoft/azuredatastudio#10537] opened 2020-05-21 15:10 UTC
Issue Type: <b>Bug</b>

When trying to make a new tab with ctrl + n I get the error 
`Unable to open 'SQLQuery_1 - disconnected': Horizontal scrolling and dynamic heights not supported simultaneously.`

If I open a sql file in Azure Data Studio, I get the error
 `Unable to open 'Untitled-2.sql - disconnected': Cannot set property 'input' of undefined.`

Currently, I am only able to open jupytr notebooks in Data Studio. I'll be going back to 1.17.1 for now. I have uninstalled/reinstalled via chocolatey, which puts me back to 1.17.1, the Data Studio auto-updater then upgrades me to v1.18 where this all breaks. I have tried this a few times, with the same results.

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (17.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
sqldm-performance-insights|IDE|0.4.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
import|Mic|0.15.0
profiler|Mic|0.11.0
server-report|Mic|0.2.2
whoisactive|Mic|0.1.4
azdata-sanddance|msr|1.3.9
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment] 2020-05-21 20:39
@splady I haven't been able to reproduce this locally, but we'll try to investigate based on the error messages provided.  In the meantime, you can disable auto-update to 1.18.0 by setting the `Update: Mode` to none.

![image](https://user-images.githubusercontent.com/599935/82604012-74668000-9b68-11ea-9e00-d926087021b9.png)

**Comment by kburtram** [comment] 2020-05-21 20:52
@splady it looks related to the Horizontal Scrolling setting.  Could you please try to disable the below setting while we prepare a fix?

![image](https://user-images.githubusercontent.com/599935/82605178-5c8ffb80-9b6a-11ea-90a4-58eb25cfcec1.png)

**Comment by splady** [comment] 2020-05-21 23:08
I upgraded from 1.17.1 -> 18.0 and when I tried to open the settings UI I got the error message `Unable to open 'Settings': Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node..`

I then uninstalled/reinstalled via chocolatey to get back to 1.17.1, turned off Horizontal Scrolling, upgraded within Azure Data Studio to version 18.0, and it works! I can now open new tabs, existing files, and the settings UI.

Thanks for your help!!

**Comment by peterlukerow** [comment] 2020-05-26 15:25
I get the same issue - see @kburtram linked to it #10549.
I've closed it since this one task was created first. May be worth checking out the diagnostics created from my task in case that points to anything.

**Comment by kburtram** [comment] 2020-05-26 17:53
One note is that to remove the HorizontalScrolling setting you can delete this value `"workbench.list.horizontalScrolling": true` from the settings.json file directly.  That file is at %USERPROFILE%\AppData\Roaming\azuredatastudio\User\settings.json.  This should allow you avoid a downgrade to edit the setting.

**Comment by Charles-Gagnon** [comment] 2020-05-26 20:36
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/10378 - we're working on getting a hotfix out for this but in the meantime the above workaround should fix the issue for now.

**Closed by Charles-Gagnon** 2020-05-26 20:36 UTC
Labels: Approved, Area - Query Editor, Bug, Triage: Done
