### ISSUE TITLE
Constant problems with inaccessible database objects

### ISSUE THREAD

**Issue by bwyatt-mcr** [microsoft/azuredatastudio#21558] opened 2023-01-10 16:14 UTC
I have 5 servers on Azure SQL that I connect to via Azure site-to-site VPN (i.e. my corporate network is connected to Azure), but I have to restart ADS constantly because I fail to find and select database objects. Errors are usually around an exception executing TSQL statement or batch, failed to generate select script, etc.

![Screenshot 2023-01-10 at 16 14 14](https://user-images.githubusercontent.com/122385470/211603929-dde989eb-3f2e-4584-8ab9-f7213a05d4a1.png)

![Screenshot 2023-01-10 at 16 15 09](https://user-images.githubusercontent.com/122385470/211604115-0d3a67c4-33b4-422f-a6b5-838c4fd4e4ce.png)
![Screenshot 2023-01-10 at 16 14 59](https://user-images.githubusercontent.com/122385470/211604116-b03377b4-f23d-459c-8829-a196e100344b.png)

**Comment by bwyatt-mcr** [comment] 2023-01-11 16:58
Hi @kburtram - yes I suppose it does, but I do not have the same problem with SSMS. 

Is there something we can do to stabilise this? Perhaps some kind of keep-alive or resiliency to latency/packet drops?

**Comment by cheenamalhotra** [comment] 2023-01-11 18:07
@bwyatt-mcr 

Could you try out the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know if you continue to see this behavior? 
I suspect this is related to expiring access token issue and the fix for refreshing the same in Object Explorer hasn't made the stable release yet.

**Comment by bwyatt-mcr** [comment] 2023-01-12 12:30
Thanks @cheenamalhotra - can you advise where I can refresh the token? I refreshed the server but it doesn't resolve.

`Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server xxxxx.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'. Token is expired.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
ClientConnectionId:5fafb402-09a5-4675-a8a6-2d591f54fda0
Error Number:18456,State:233,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at Microsoft.SqlTools.ServiceLayer.Scripting.ScriptAsScriptingOperation.Execute() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Scripting\ScriptAsScriptingOperation.cs:line 84`

**Comment by cheenamalhotra** [comment] 2023-01-12 16:57
I think you need to drop the connection, using Disconnect or simply delete the connection in the tree view, and create a new connection.

**Comment by bwyatt-mcr** [comment] 2023-01-16 10:13
@cheenamalhotra - that did work, but it's not something I should really be having to do in my opinion. The connections and tokens should be stable enough. If MS can do this in SSMS, they can surely do this in ADS? I'd be surprised if this wasn't something other people suffer with.

**Comment by cheenamalhotra** [comment] 2023-01-16 16:41
Yes, the fix has been and is available in the insiders build, its on it's way to the next stable release.

**Comment by Dvnoten** [comment] 2023-01-31 14:02
@cheenamalhotra, I'm running version 1.41.1 on Windows platform. The issue is still there.

**Comment by cheenamalhotra** [comment] 2023-03-07 03:19
@Dvnoten 

The solution to solve this should be similar to: https://github.com/microsoft/azuredatastudio/issues/21774#issuecomment-1457276049 and I'm hopeful this to resolve multiple access token refresh issues with this setting enabled:

```json
    "mssql.enableSqlAuthenticationProvider": true
```

Support is available in the latest insiders build, please give it a try and let me know how it goes :)

**Comment by cheenamalhotra** [comment] 2023-04-26 01:49
Closing as "mssql.enableSqlAuthenticationProvider" is now enabled by default in the latest insiders.
This will be available in the next May release.

**Closed by cheenamalhotra** 2023-04-26 01:49 UTC
Labels: Bug, Area - Object Explorer, Area - Connection, Triage: Done
