### ISSUE TITLE
Schema compare include "Delete" even after uncheck option "Drop object not in source" 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#21055] opened 2022-11-01 17:27 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a db with one table
2. Create another db
3. Compare those dbs (1 as source, 2 as target) and verify  Delete table
4. Open options and un check "Drop objects not in source"
5. Compare again
Expected: Result should not include "Delete table"
Actual: Still see "Delete" in the result

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment] 2022-11-01 17:37
closing as duplicate of #19730

**Closed by kisantia** 2022-11-01 17:37 UTC
Labels: Area - Schema Compare, Triage: Needed
