### ISSUE TITLE
The icon pinned to the start is so big...

### ISSUE THREAD

**Issue by NagiaME** [microsoft/azuredatastudio#13545] opened 2020-11-25 02:42 UTC
Issue Type: <b>Bug</b>

The icon pinned to the start is too big, it was never liked this before, please fix it.

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by NagiaME** [comment] 2020-11-25 02:44
![image](https://user-images.githubusercontent.com/11983319/100176357-19448a00-2f0b-11eb-926e-3aa2a02f40f6.png)

**Comment by Charles-Gagnon** [comment] 2020-11-25 19:09
Thanks for the report! This looks to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/13452 so I'll close this one for now.

**Closed by Charles-Gagnon** 2020-11-25 19:09 UTC
