### ISSUE TITLE
Unable to connect to SQL Server 2017 using SQL Login (mac OS)

### ISSUE THREAD

**Issue by sarantoo** [microsoft/azuredatastudio#4591] opened 2019-03-19 04:14 UTC
Issue Type: <b>Bug</b>

When connection is provided with a wrong username/password, the Login failed for user 'xxx' is instantly displayed. This proved that the communication to the server was successfully established.

However, with the correct user name and password. There will be an indefinitely spinning icon appear without any timeout. I need to cancel the connection attempt.

Note:

* Connection to local SQL Server 2008 R2 with Windows Authentication is working fine but SQL Login face the same problem.
* Azure Data Studio for Windows has no such problem

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_426088|
|Screen Reader|no|
|VM|29%|

</details>Extensions: none

**Comment by BrentOzar** [comment] 2019-03-23 11:22
I'm able to log in fine with SQL Server authentication to SQL Server 2017 on the v1.6 insider build - can you try with that? The download link is on the home page of this project (click Code at the top of Github, and scroll down.) Not saying it didn't work with v1.5.1 - I don't have that handy to test with.

![Screen Shot 2019-03-23 at 4 20 22 AM](https://user-images.githubusercontent.com/245462/54865451-13080e80-4d23-11e9-9812-77bb66a92802.png)

**Comment by sarantoo** [comment] 2019-04-02 04:04
> I'm able to log in fine with SQL Server authentication to SQL Server 2017 on the v1.6 insider build - can you try with that? The download link is on the home page of this project (click Code at the top of Github, and scroll down.) Not saying it didn't work with v1.5.1 - I don't have that handy to test with.
> 
> ![Screen Shot 2019-03-23 at 4 20 22 AM](https://user-images.githubusercontent.com/245462/54865451-13080e80-4d23-11e9-9812-77bb66a92802.png)

Hi Brent,

I've tried both insider version 1.6.0 and the standard 1.5.2 version. And after trying it for several days, I found that with SQL Login, it's kind of hit-and-miss. Sometime it connect just fine, but can't connect again after disconnected. The only thing that always works is Windows Authentication with server on the local network.

Servers I can sometime connect:

- Remote SQL Server 2017 (SQL  Login)
- Local SQL Server 2008 R2 (SQL Login)

Server that is unable to connect to:

- Remote SQL Server 2005 (SQL Login)

As usual, incorrect password was detected immediately but got indefinite response with a correct password.

**Comment by Charles-Gagnon** [comment] 2020-01-07 00:35
Closing this as a dupe of #1727 - there's a lot of general timeout issues and for cleanup purposes I'm going to bucket them all in one place.

**Closed by Charles-Gagnon** 2020-01-07 00:35 UTC
Labels: Area - Connection, Bug
