### ISSUE TITLE
Save Password Bug

### ISSUE THREAD

**Issue by chess92** [microsoft/azuredatastudio#17723] opened 2021-11-20 15:31 UTC
Issue Type: <b>Bug</b>

The "save password" checkbox does not seem to be working correctly.

It saves it the first time, but when I re-open the app, the checkbox is no longer checked. From this point, the only way to keep my password saved is to keep checking the box every time I open the app.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:43:30.222Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (37.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2021-11-20 23:47
Duplicate of https://github.com/microsoft/azuredatastudio/issues/17594

**Closed by Charles-Gagnon** 2021-11-20 23:47 UTC
