### ISSUE TITLE
In "Manage" window, after filtering DB table list and right-clicking a DB table and choosing 'Select...' context menu item, a new SELECT clause window opens, but DB table list becomes empty in "Manage" window

### ISSUE THREAD

**Issue by BurstX** [microsoft/azuredatastudio#10599] opened 2020-05-28 07:47 UTC
Issue Type: <b>Bug</b>

1. Open Azure Data Studio
1. Open "Connections" pane (Ctrl+B), right click a database (better - with a lot of tables, say, 100) and choose "Manage" in the context menu
1. The database "Manage" pane is opened
1. Filter the database list by typing a substring existing in a table name (so that there are tables to choose from the filtered list)
1. right-click a table in the filtered list
1. choose "Select..." form the context menu
1. A new window opens with the SELECT clause for the chosen DB table, and this window becomes active
1. switch back to "manage" window
1. the filtered table list is empty

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|1.3.9

</details>

**Comment by BurstX** [comment] 2020-05-28 13:55
In fact, the filtered list contains items, which are revealed as soon as the scrollbar (assuming that the filtered list is big enough for the scroll bar to appear) is moved. Perhaps, the list has to be redrawn.

**Comment by alanrenmsft** [comment] 2020-06-01 22:41
> In fact, the filtered list contains items, which are revealed as soon as the scrollbar (assuming that the filtered list is big enough for the scroll bar to appear) is moved. Perhaps, the list has to be redrawn.

@BurstX this comment helps 😄 , now I can repro it.

**Comment by kburtram** [comment] 2021-08-17 18:26
Thanks for filing this issue!  This appears to be a duplicate of #5178, though with alternate repro steps.  Closing to consolidate bug reports.

**Closed by kburtram** 2021-08-17 18:26 UTC
Labels: Bug, Area - Dashboard, Triage: Done
