### ISSUE TITLE
Markdown relative links on edit mode are not working correctly

### ISSUE THREAD

**Issue by mikelawell** [microsoft/azuredatastudio#10896] opened 2020-06-12 15:32 UTC
We have written the needed d
Issue Type: <b>Bug</b>

When I use the link syntax its not opening the notebook. If I use an <a> tag (i.e. <a href="FABParameters.ipyn">FAB Parameters</a>) it is getting the relative link locations as "Unable to open 'FABParameters.ipynb': Unable to read file 'c:\C:\Users\mml63\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\code\electron-browser\workbench\FABParameters.ipynb' (Error: Unable to resolve non-existing file 'c:\C:\Users\mml63\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\code\electron-browser\workbench\FABParameters.ipynb')."

This is not the relative link to the project files.

This started last update. 

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (3.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2020.4.0

</details>
ata into your clipboard because it was too large to send. Please paste.

**Comment by chlafreniere** [comment] 2020-06-12 22:04
@barbaravaldez can you work with @mikelawell to repro this issue?

**Comment by barbaravaldez** [comment] 2020-07-27 17:35
Hi @mikelawell, are you trying to use markdown links?

**Comment by mikelawell** [comment] 2020-07-27 17:47
Sorry, been awhile... this is using markdown links... I converted to an A tag to work around this. I need to try to repro to see if it got fixed in the past couple of releases.

**Comment by mikelawell** [comment] 2020-07-27 18:00
![Links](https://user-images.githubusercontent.com/39015075/88575087-efd12b80-d008-11ea-98d9-91804061ef81.jpg)
There is still some weirdness. It looks like it is still adding a front slash to the link. I'm now using 1.20.1

**Comment by barbaravaldez** [comment] 2020-07-27 18:14
Thank you for the screenshot 😄 Yeah, it seems that something weird is happening when it's trying to convert the relative link into an absolute path. I'll take a look at this. Thank you!! 😄

**Comment by barbaravaldez** [comment] 2020-08-05 18:20
Hi @mikelawell, I tried to repro this issue using markdown relative links in Notebooks but it seems to be working fine. So, I just wanted to clarify does this issue happens on Notebooks or Books?

**Comment by Charles-Gagnon** [comment] 2020-08-05 21:00
Closing this one as a duplicate of #11657

**Comment by chlafreniere** [comment] 2020-08-05 21:07
I was incorrect here; this affects text cells instead of markdown files, which use slightly different code paths. Reopening.

**Comment by MsSQLGirl** [comment] 2020-12-14 22:40
@mikelawell @barbaravaldez  - I'm using v1.25.1 right now and am unable to repro. Perhaps we can close this if it's no longer an issue? 

I do notice that there is "\/" in front of the beginning of the relative link. But this seems to be harmless on Windows. @barbaravaldez - what's the behavior on Mac or LInux? 

A friendly reminder:  link sometimes does not work is that if a user forgets to mark their notebook as Trusted.

**Comment by barbaravaldez** [comment] 2020-12-15 19:24
> @mikelawell @barbaravaldez - I'm using v1.25.1 right now and am unable to repro. Perhaps we can close this if it's no longer an issue?
> 
> I do notice that there is "/" in front of the beginning of the relative link. But this seems to be harmless on Windows. @barbaravaldez - what's the behavior on Mac or LInux?
> 
> A friendly reminder: link sometimes does not work is that if a user forgets to mark their notebook as Trusted.

@MsSQLGirl - I was not able to repro on Mac, as well.

**Comment by chlafreniere** [comment] 2021-02-02 05:04
Given that we have some folks unable to repro, closing this issue. Feel free to reactivate if we have a consistent repro.

**Closed by chlafreniere** 2021-02-02 05:04 UTC
Labels: Area - Notebooks, Bug, Triage: Done, Triage: Postponed
