### ISSUE TITLE
Let users sort and filter results sets by clicking on column heades (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#4933] opened 2019-04-09 17:07 UTC
Issue Type: <b>Feature Request</b>

Provide the ability to sort result sets by select the column header.

Additionally, filtering of result sets could be added to these commands.  This would make result sets behave close to Excel tables.

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

**Comment by Charles-Gagnon** [comment] 2019-04-11 04:21
Closing this as a duplicate of #4934

**Closed by Charles-Gagnon** 2019-04-11 04:21 UTC
