### ISSUE TITLE
Queries Never Finish

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#22044] opened 2023-02-27 17:19 UTC
Issue Type: <b>Bug</b>

Executing a simple query never finishes. Even after returning a result grid, the timer keeps ticking, and the "Run" button never re-activates. 

I noticed this after running a query, doing something else, then coming back 2 hours later and seeing the timer ticking away.

Cancel button does not stop query. Have to exit ADS to stop.

![image](https://user-images.githubusercontent.com/13488/221634530-cb55dd44-f053-4219-9338-709d190b972e.png)
![image](https://user-images.githubusercontent.com/13488/221634684-c18de1c6-c782-4b7f-90d9-a520da520a85.png)

Azure Data Studio version: azuredatastudio-insiders 1.42.0-insider (1e8519d54a6507504bfdbec4faa3082648609455, 2023-02-27T06:50:07.267Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (14.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dacpac|Mic|1.13.0
import|Mic|1.5.4
schema-compare|Mic|1.18.0
sql-database-projects|Mic|0.22.0
sql-search|Red|0.4.0
ADS-add-columns|sof|0.0.12
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by alanrenmsft** [comment] 2023-02-27 22:14
Thanks for reporting. this looks to be a dupe of #7440

**Comment by jtsom** [comment] 2023-02-27 22:58
I'm not so sure it's the same. It just started down by this with the latest insiders. And the query completes (complete results are shown) but the timer keeps running and the Run button never reactivates.

**Comment by alanrenmsft** [comment] 2023-02-27 23:38
I can reproduce the issue now. Thanks, Will investigate.

**Comment by alanrenmsft** [comment] 2023-02-28 00:50
@corivera , this issue is introduced by https://github.com/microsoft/azuredatastudio/pull/21995, the onQueryComplete notification is now being processed by the new controller you added
![image](https://user-images.githubusercontent.com/13777222/221723419-0faf0027-0931-4e8a-9949-922533ded2a1.png)

please treat this as high priority as the query editor feature is broken now.

Thanks
Alan

**Comment by Charles-Gagnon** [comment] 2023-02-28 18:47
Sigh, yeah this looks like it's related to this long-standing issue with provider callbacks. 

https://github.com/microsoft/sqlops-dataprotocolclient/issues/62

Fixing that would be great since this is something that very much limits the usefulness of the providers in general (and making it easy for extensions to completely break core behavior is pretty bad in general)

**Comment by corivera** [comment] 2023-02-28 19:13
@Charles-Gagnon For query providers, wouldn't it be a problem if any extension can register a listener and get all the query outputs from the MSSQL provider? Or do we assume that an extension is trusted if the user installs it?

**Comment by Charles-Gagnon** [comment] 2023-02-28 19:19
That's definitely a discussion we'll have to have - but that's something an extension can do currently anyways (it just breaks everything else) so something to keep in mind. But yeah, overall the general idea VS Code seems to go with is that if you install an extension you trust it so they have a lot of capabilities - for example reading any file in the workspace.

**Comment by corivera** [comment] 2023-02-28 19:25
Yeah, it would make more sense if it behaves like other events where you can register multiple callbacks. Extensions could then route the outputs correctly using the editor URI.

**Closed** 2023-02-28 20:18 UTC
Labels: Bug, Area - Query Editor, Pri: 1, Triage: Done, Size: S

**Comment by chris-larsen** [comment] 2023-03-02 23:43
dont want to pollute this but in the interim is there a version prior to this controller addition i can use in the interim? SSMS makes me wanna find a ledge it's been hard to live without ADS lol

**Comment by alanrenmsft** [comment] 2023-03-02 23:49
@chris-larsen the fix is already in the latest insider build.
