### ISSUE TITLE
Images not rendering in markdowns

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#4747] opened 2019-03-28 18:51 UTC
Issue Type: <b>Bug</b>

Images are not rendering on notebooks.

<img src="https://github.com/Microsoft/sqlworkshops/blob/master/graphics/solutions-microsoft-logo-small.png" alt="Microsoft">

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.390
azuredatastudio-postgresql|Mic|0.1.0
import|Mic|0.7.0
sql-vnext|Mic|0.11.0

</details>

**Comment by anthonydresser** [comment] 2019-03-28 19:15
without context; it looks like in your issue comment you are using the img html tag. Doesn't the actual markdown version of images work? `![alt-text](image link)`

**Comment by chlafreniere** [comment] 2019-04-05 23:14
Dupe of #3069.

**Closed by chlafreniere** 2019-04-05 23:14 UTC
Labels: Area: Notebooks
