### ISSUE TITLE
Execute Query on Multiple Instances

### ISSUE THREAD

**Issue by marshallquick** [microsoft/azuredatastudio#7093] opened 2019-09-05 21:57 UTC
- Azure Data Studio Version:
Version: 1.10.0 (system setup)
Commit: 5fdb967ffcea41df0335ec17cfa396a694bb174e
Date: 2019-08-14T18:28:10.311Z
VS Code 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce: [none: new functionality]
Research and Docs reviewed.  I came up with no current functionality like I'm requesting. 
Ref: [Server groups in Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/server-groups?view=sql-server-2017)

Request: 
Please allow user to execute a query on all instances of a Server Group or multiple selected instance. SSMS can execute a query on multiple instance by using the 'Local Server Groups'. We really need the ability to easily execute a query on multiple instances. 

This feature is a little restrictive in SSMS. Idealy

Feature Visualization:
SSMS approach:

1. Add 'New Query' to the right click menu of the Server Group
2. Clicking this option opens a query window
3. Execution results are displayed like multiple result sets or a union-ed set with the first column containing the instance name.

Flexible approach:
1. Add 'New Query' to the right click menu of the Server Group
2. Clicking this option opens a query window
3. KEY Feature: The connection drop down is a multi select UI control that allow the select of multiple server connections. ()
4. Execution results are displayed like multiple result sets or a union-ed set with the first column containing the instance name.

**Comment by Charles-Gagnon** [comment] 2019-09-09 16:12
Thanks for the report @marshallquick - this appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/28 so I'm going to close this one for now. Feel free to reopen it if you think the issue is separate enough - otherwise follow that one for any updates!

**Closed by Charles-Gagnon** 2019-09-09 16:12 UTC
Labels: Area: Query Editor, Enhancement, Triage: Needed
