### ISSUE TITLE
VSCode release notes shown on update of Insiders app

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#7291] opened 2019-09-19 20:39 UTC
Issue Type: <b>Bug</b>

- Open Azure Data Studio Insiders
- Check for updates and choose "Restart to update"
- Note that the VSCode Insiders release notes are shown unexpectedly (see image below)

![image](https://user-images.githubusercontent.com/10819925/65279324-d014d100-dae2-11e9-87b2-30bc0061c46b.png)

@anthonydresser any idea if a recent VSCode merge cause this?

Azure Data Studio version: Azure Data Studio 1.12.0-insider (a584aca96997a18ecedee73a575536332e542718, 2019-09-19T07:26:08.307Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_864467|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
nbopener|kc|0.0.1
ads-language-pack-es|Mic|1.9.0
azuredatastudio-postgresql|Mic|0.2.1
sql-vnext|Mic|0.14.1

</details>

**Comment by Charles-Gagnon** [comment] 2019-09-19 20:43
Duplicate of #7242 so closing this one

**Closed by Charles-Gagnon** 2019-09-19 20:43 UTC
Labels: Bug
