### ISSUE TITLE
Double click to select text with '@'

### ISSUE THREAD

**Issue by VictorBalbo** [microsoft/azuredatastudio#6523] opened 2019-07-29 18:28 UTC
Issue Type: <b>Feature Request</b>

On double click a text (to select the word) with '@' on it, the selected text does not stops at the '@', like every text editor does.
Example: clicking on name in the string 'name@domain', selects the entire string, instead of only the name.

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.16299

**Comment by anthonydresser** [comment] 2019-07-30 02:13
This is being caused by this edit https://github.com/microsoft/azuredatastudio/blob/master/src/vs/editor/common/model/wordHelper.ts#L9 in this commit which was created to solve https://github.com/microsoft/azuredatastudio/issues/143 

Can you clarify if you are experiencing this issue when editing sql queries or other types of files. based on #143 is sounds like it is preferable for sql to not use @ as a break for highlighting words.

**Comment by kburtram** [comment] 2019-08-05 22:00
@anthonydresser `@` is used at the beginning of SQL variable names and in that situation we would want to not use it as a word separator.  In this bug repo since the `@` is not at the beginning of a word we would want to use it as a word separator.

Since the VS Code logic isn't smart enough to handle this distinction we would want to keep the current behavior since it is more common to be highlighting SQL variable names than strings with embedded `@` in SQL scripts.  I'll close this as "by design limitation of upstream."  If VS Code adds ability to be smarter about word separator exceptions we can revisit.

**Closed by kburtram** 2019-08-05 22:00 UTC
Labels: Area: Query Editor, Bug, Triage: Needed

**Comment by anthonydresser** [comment] 2019-08-05 23:05
I think we can be smarter about it with current implementation according to https://github.com/microsoft/vscode/issues/39218#issuecomment-347448993 we can design a regex to do this parsing correctly https://code.visualstudio.com/api/language-extensions/language-configuration-guide
