### ISSUE TITLE
"New Query" doesn't auto-connect to previous database connection

### ISSUE THREAD

**Issue by leonardofel** [microsoft/azuredatastudio#8865] opened 2020-01-12 15:56 UTC
I remember update ~10/2019 when you open a new query tab, if the previous windows had a connection, the new tab connect to the same one, now this feature doesn't work anymore...

![image](https://user-images.githubusercontent.com/34713362/72221571-f56a9680-353a-11ea-9406-c8f79cf3b608.png)

settings.json in attachment
[azure_no_query.json.txt](https://github.com/microsoft/azuredatastudio/files/4050802/azure_no_query.json.txt)

**Comment by Charles-Gagnon** [comment] 2020-01-14 18:43
@leonardofel I went back and checked the Sept 2019 version and wasn't able to repro the behavior you mentioned, so I'm not sure if we had a regression there or not.

Regardless I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8668. I agree that we should have some sort of default connection that is populated when a new query tab is open - although we'll have to discuss what approach would be preferable (the linked issue has a different solution than your suggestion) - but in order to consolidate the discussion let's keep it all in one issue thread.

Thanks for the feedback!

**Closed by Charles-Gagnon** 2020-01-14 18:43 UTC
Labels: Area - Connection, Bug, Triage: Done

**Comment by Charles-Gagnon** [comment] 2020-01-15 15:55
@leonardofel I looked into this a bit more and think I found an issue with some recent changes we made that probably broke this. I'm going to keep this closed but you can follow https://github.com/microsoft/azuredatastudio/issues/8883 for more information. 

The other linked item, #8668 is for a slightly different ask and so while in the similar vein isn't exactly the problem you're hitting here.
