### ISSUE TITLE
Kusto: getting access denied after a day on same connection, also repros on *new connection* unless you use *add account*

### ISSUE THREAD

**Issue by baselsalam** [microsoft/azuredatastudio#12642] opened 2020-09-25 23:36 UTC
- Azure Data Studio Version: 1.22.0

Steps to Reproduce:
1. Create a new notebook,
2. Create a new Kusto connection
3. Run a query.
4. Come back after a day (ADS is still open all this time)
5. Try to rerun the same query.
   You get error: `Query failed: Unauthorized (): Authorization has been denied for this request.`

I figured there might be an issue with the bearer token expiring, and its not refreshing it.
So I tried even creating a new connection:
6. Create a new connection, with the same details *but using the same account*.
7. This also fails, with the following error details stack posted below.
   However, if under 'Account', I choose "Add Account", then the issue goes away! 

It might be the same underlying token refresh issue that's being encountered in both scenarios.

**Error Details when trying to create a new connection, but using the same Account:**
`System.ArgumentException: Unable to connect. ClusterName = ..., DatabaseName = ...
   at Microsoft.Kusto.ServiceLayer.Utility.ValidationUtils.IsTrue[T](Boolean condition, String message) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Utility\ValidationUtils.cs:line 143
   at Microsoft.Kusto.ServiceLayer.DataSource.KustoDataSource..ctor(String connectionString, String azureAccountToken) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\KustoDataSource.cs:line 97
   at Microsoft.Kusto.ServiceLayer.DataSource.DataSourceFactory.Create(DataSourceType dataSourceType, String connectionString, String azureAccountToken) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\DataSourceFactory.cs:line 25
   at Microsoft.Kusto.ServiceLayer.Connection.ReliableDataSourceConnection..ctor(String connectionString, RetryPolicy connectionRetryPolicy, RetryPolicy commandRetryPolicy, String azureAccountToken, IDataSourceFactory dataSourceFactory) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\ReliableDataSourceConnection.cs:line 64
   at Microsoft.Kusto.ServiceLayer.Connection.DataSourceConnectionFactory.CreateDataSourceConnection(String connectionString, String azureAccountToken) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\DataSourceConnectionFactory.cs:line 35
   at Microsoft.Kusto.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\ConnectionService.cs:line 438`

**Comment by JustinMDotNet** [comment] 2020-10-29 23:25
This issue is a duplicate of this issue: #11830 and should have been resolved in the September release.

**Closed by JustinMDotNet** 2020-10-29 23:25 UTC
Labels: Area - Connection, Area - Kusto, Bug, Triage: Done
