### ISSUE TITLE
Query results slows down whole application

### ISSUE THREAD

**Issue by panuoksala** [microsoft/azuredatastudio#2690] opened 2018-09-25 05:12 UTC
Issue Type: <b>Bug</b>

If query returns lots of columns (over 20) and rows (over 20), whole applications becomes very slow. Result grid has approx. 1-2 second of lag in scrolling and also the query editor has similiar lag when trying to type something.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (2.64GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by panuoksala** [comment] 2018-09-25 05:14
I have been having this bug for last two versions.

**Comment by panuoksala** [comment] 2019-02-14 08:17
Still valid with new version. Returning over 50 rows will slow down the application a lot. Even typing into query window lags ~1-2 seconds for every character.

**Comment by pnhughes** [comment] 2019-08-06 19:43
I experience performance issues and typing lag in the application when my notebook grows to a reasonable size. For example, I have 6 text blocks with markdown and 7 code blocks, with all output cleared.  Typing in existing or new text blocks in this notebook is subject to ~1 sec lag per keystroke, but cursor manipulation with arrow keys within the same blocks is fast and experiences no lag. 

The experience of a notebook performing steadily worse the larger it gets is consistent with my experience on current & prior versions, since Notebook support was added.

**Comment by panuoksala** [comment] 2019-08-07 05:16
My issue was resolved by computer change. I think this might be caused by some of the Windows UI settings.

**Comment by kburtram** [comment] 2021-04-23 18:03
Closing this issue as the original issue was mitigated through work around.  @aasimkhan30 is planning some perf improvements in query editor so hopefully we can root cause any underlying problems remaining in this use case.  Thanks!

**Closed by kburtram** 2021-04-23 18:03 UTC
Labels: Area - Query Editor, Bug
