### ISSUE TITLE
Jupyter Lab / Notebook

### ISSUE THREAD

**Issue by KT12** [Microsoft/azuredatastudio#4681] opened 2019-03-24 12:58 UTC
Issue Type: <b>Bug</b>

Hi,

I'm running Azure Data Studio in Ubuntu 18.04.  Unfortunately, when I try to open a Jupyter Notebook or Lab, it opens in ADS and not my default browser.
I'm running Ubuntu 18.04.
Thank you,
Ken

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:04:39.718Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2786)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|15.36GB (8.14GB free)|
|Process Argv|/usr/share/azuredatastudio/azuredatastudio --unity-launch /run/user/1000/jupyter/nbserver-7346-open.html|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by corivera** [comment] 2019-03-25 22:30
Issue does not repro for me on ADS 1.5.2 on Ubuntu 18.04. Closing.

**Closed by corivera** 2019-03-25 22:30 UTC
Labels: bug, notebooks

**Comment by sgornick** [comment] 2019-04-06 21:02
This is likely a duplicate of issue #3108

**Comment by KT12** [comment] 2019-04-07 23:32
Changing the file `~/.config/mimeapps.list` default to:
`text/html=firefox.desktop`
fixed the issue.  @sgornick  thanks for pointing me in the right direction.
