### ISSUE TITLE
Report Issue UI doesnt work in Azure Data Studio

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/azuredatastudio#2674] opened 2018-09-24 14:30 UTC
Open Help menu
Choose Report Issue
Complete the Issue Reporter UI
Click the Preview on GitHub

**********************
Expectation is to arrive at GitHub in the New Issue UI
**********************
What actually happens is a 404 error from GitHub

the browser opens a url starting https://github.com/Microsoft/azuredatastudio/issues/new

but none of that exists beyond https://github.com/Microsoft

**Comment by HugoKornelis** [comment] 2018-09-24 14:50
I have the exact same issue.

**Comment by yualan** [comment] 2018-09-24 15:50
This seems to be working now, let us know if this problem persists.

**Comment by kburtram** [comment] 2018-09-24 16:53
This was caused by the gap in docs publishing and repo rename.  Closing since the issue is now resolved.

**Closed by kburtram** 2018-09-24 16:53 UTC

**Comment by fatherjack** [comment] 2018-09-24 17:42
yep, agreed, working now. Thanks
