### ISSUE TITLE
Welcome page text color issue in dark theme

### ISSUE THREAD

**Issue by radentonev** [microsoft/azuredatastudio#14945] opened 2021-04-01 16:48 UTC
Issue Type: <b>Bug</b>

The SQL Admin Pack title and body text turn black in dark theme, which is wrong. The text should remain white instead, b/c its background is rather dark.

<img width="1680" alt="Screen Shot 2021-04-01 at 9 44 50 AM" src="https://user-images.githubusercontent.com/71295692/113326905-23b6cc00-92cf-11eb-9fa8-74180ca94e74.png">

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:18:54.187Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
adslivesite|Mic|0.0.46
azuredatastudio-postgresql|Mic|0.2.7
datavirtualization|Mic|1.12.0
machine-learning|Mic|0.8.0
schema-compare|Mic|1.9.1
sql-database-projects|Mic|0.7.1
azdata-sanddance|msr|3.1.0

</details>

**Comment by kisantia** [comment] 2023-09-05 23:50
duplicate of https://github.com/microsoft/azuredatastudio/issues/16978

**Closed by kisantia** 2023-09-05 23:50 UTC
Labels: Bug, Area - Shell, Area - UX
