### ISSUE TITLE
Running a Select returns Query Failed : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by peperami97** [microsoft/azuredatastudio#20292] opened 2022-08-10 15:46 UTC
Issue Type: <b>Bug</b>

I have run a simple select statement of the form 

select * 
from table1 e
inner join table2 eph on e.field1 = eph.field1
inner join table3 eh on eh.field1 = e.field1
left join table4 el on e.field1 = el.field1

This causes the following message

16:39:52Started executing query at Line 1
(169 rows affected)
Total execution time: 00:00:00.157

The results grid is available but contains 166 rows.

When run in managment studio 2018 I get no error message and 169 rows returned.

I have tried restarting azure data studio

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (13.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
demo-mode|dre|1.1.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.48.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0
query-history|Mic|0.2.1
schema-compare|Mic|1.15.0
schema-visualization|R0t|0.8.2
sql-prompt|Red|0.2.11
simple-data-scripter|sea|0.1.6
vscodeintellicode|Vis|1.2.1

(2 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment] 2022-09-07 22:03
@peperami97 could you please share a screenshot of the results grid with it scrolled all the way to the bottom, also include the xxx rows in the status bar. 

![image](https://user-images.githubusercontent.com/13777222/188991677-4f6faaae-1857-44cc-87a8-f194a50dd222.png)

**Comment by alanrenmsft** [comment] 2022-12-06 19:19
dupe of #18714

**Closed by alanrenmsft** 2022-12-06 19:19 UTC
Labels: Bug, Area - Query Editor, Needs More Info, Triage: Done
