### ISSUE TITLE
Data doesn't show up

### ISSUE THREAD

**Issue by GearTheWorld** [microsoft/azuredatastudio#24821] opened 2023-10-30 19:17 UTC
Type: <b>Bug</b>

The data doesn't show up.  I have to click on Messages and come back to Results to see the data

![image](https://github.com/microsoft/azuredatastudio/assets/8614008/83890f4f-caea-4feb-b228-9e5e6136077a)

After transitionning between Messages and Results

![image](https://github.com/microsoft/azuredatastudio/assets/8614008/9cdd88b8-47b4-4385-bd6a-9c5274be9d96)

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.1.3
import|Mic|1.5.5
profiler|Mic|0.14.0
schema-compare|Mic|1.21.0
azdata-sanddance|msr|4.1.1

</details>

**Comment by GearTheWorld** [comment] 2023-10-30 19:46
![image](https://github.com/microsoft/azuredatastudio/assets/8614008/8c53e6b1-784f-484b-abe9-df1284882708)

**Comment by cheenamalhotra** [comment] 2023-10-30 21:23
Hi @GearTheWorld 

Does your repro steps looks similar to what is mentioned here: https://github.com/microsoft/azuredatastudio/issues/24713#issuecomment-1770215491?
Otherwise, can you provide steps you used to repro the issue?

**Comment by GearTheWorld** [comment] 2023-10-30 23:02
Maybe 😊

**Comment by cheenamalhotra** [comment] 2023-10-31 02:32
In that case I'll close this as duplicate of #24713 - please follow this issue for further updates.
Thanks!

**Closed by cheenamalhotra** 2023-10-31 02:32 UTC
Labels: Bug, Area - Query Editor, Needs More Info, Triage: Needed
