### ISSUE TITLE
Inconsistent display of record data when query executed multiple times

### ISSUE THREAD

**Issue by rmacfadyen** [microsoft/azuredatastudio#25469] opened 2024-03-04 03:19 UTC
Type: <b>Bug</b>

I have a query that returns an integer Id field and a Geometry field. The geometry field is return in it's binary/native format and in a string representation. The underlying data is not being changed, it is completely static throughout the steps taken in this bug report. 

Remote server @@Version: The SQL Server is remote, an Azure SQL instance: Microsoft SQL Server 2016 (SP3-CU1-GDR) (KB5029187) - 13.0.7029.3 (X64)  	Aug 16 2023 19:44:44  	Copyright (c) Microsoft Corporation 	Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

Here's the query:

select 
    id,
    GeoSpatial,
    GeoSpatial.STAsText()
from MyTableName
where Id = 8610085

The GeoSpatial column contains the WKT. Here's a setup script to help repro the issue https://pastebin.com/BMzggXBJ

Sometimes it displays the correct data, sometimes it display completely incorrect data. Usually incorrect. But if I execute the query over and over eventually it will display the data correctly. Might take 1 try, might take a dozen tries.

Here's the correct data: https://imgur.com/a/8YnnhF6
Note that the unnamed column, the one that contains WKT formatted text, is jumbled and displays chinese characters. Very odd because WKT is always plain ascii.

Here's the incorrect data: https://imgur.com/a/ft5XDsk
If I copy/paste the incorrect data (with headers) the paste buffer contains the correct data correctly formatted. Though this is also inconsitent (tried copy of just the unnamed column's cell and paste buffer did not change; copyied whole row with headers and paste buffer populated correctly.

Late breaking... so in setting up my repro script I could NOT reproduce the problem using my local SQL database. Locally I have SQL2019, remotely the server is 2016. I'd have tried my repro script remotely... but insufficient permissions. 

Local server @@Version: Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)  	Apr 29 2022 18:00:13  	Copyright (C) 2019 Microsoft Corporation 	Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19043: ) (Hypervisor) 

Azure Data Studio version: azuredatastudio-insiders 1.49.0-insider (34cbc32d322c5dbdda5571a9b800d1f8b782ff7a, 2024-03-01T15:46:13.960Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.76GB (21.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kisantia** [comment] 2024-03-04 21:32
please update this issue when you have a repro that can be shared

**Comment by cheenamalhotra** [comment] 2024-03-04 22:30
Likely a duplicate of https://github.com/microsoft/azuredatastudio/issues/25177

**Comment by cheenamalhotra** [comment] 2024-03-08 21:51
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/25177

**Closed by cheenamalhotra** 2024-03-08 21:51 UTC
Labels: Bug, Area - Query Editor, Triage: Done
