### ISSUE TITLE
Feedback on the migration experience

### ISSUE THREAD

**Issue by treytro** [microsoft/azuredatastudio#20298] opened 2022-08-10 21:01 UTC
Issue Type: <b>Bug</b>

If you try to run more than one assessment per day, it throws the error below because the json file already exists.  The work around is to rename or delete the json file.

The file 'c:\Users\Trey.JINTECH\AppData\Roaming\azuredatastudio\logs\20220810T151012\exthost1\Microsoft.mssql\SqlAssessmentReport-20220810.json' already exists.

Extension version: 1.0.4
Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<!-- generated by issue reporter --
![SqlAssessment_issue](https://user-images.githubusercontent.com/35743905/184019150-b3a98575-73ea-49d2-8ca5-6609ed7eaeb6.PNG)
[SqlAssessment_callstack.txt](https://github.com/microsoft/azuredatastudio/files/9304027/SqlAssessment_callstack.txt)
>

**Comment by treytro** [comment] 2022-08-10 21:07
Callstack...

An error occurred while assessing the server 'nnn'.
========================
message: Microsoft.SqlServer.DataCollection.Common.Contracts.Exceptions.FailedToSaveResultsException: Saving the report file 'c:\Users\Trey.JINTECH\AppData\Roaming\azuredatastudio\logs\20220810T151012\exthost1\Microsoft.mssql\SqlAssessmentReport-20220810.json' failed.
 ---> System.IO.IOException: The file 'c:\Users\Trey.JINTECH\AppData\Roaming\azuredatastudio\logs\20220810T151012\exthost1\Microsoft.mssql\SqlAssessmentReport-20220810.json' already exists.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.SqlServer.Migration.Assessment.Common.TargetAssessment.Utils.ExportAssessmentResultsAction.OpenFile(String fileName, Boolean overwriteResult)
   at Microsoft.SqlServer.Migration.Assessment.Common.TargetAssessment.Utils.ExportAssessmentResultsAction.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Migration.Assessment.Common.TargetAssessment.Utils.ExportAssessmentResultsAction.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   at Microsoft.SqlServer.Migration.Assessment.Common.Workflows.MigrationAssessmentWorkflow.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   at Microsoft.SqlServer.Migration.Assessment.Common.Engine.DmaEngine.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   at Microsoft.SqlTools.ServiceLayer.Migration.MigrationService.GetAssessmentItems(String[] connectionStrings) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Migration\MigrationService.cs:line 438
   at Microsoft.SqlTools.ServiceLayer.Migration.MigrationService.HandleMigrationAssessmentsRequest(MigrationAssessmentsParams parameters, RequestContext`1 requestContext) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Migration\MigrationService.cs:line 156
stack: Error: Microsoft.SqlServer.DataCollection.Common.Contracts.Exceptions.FailedToSaveResultsException: Saving the report file 'c:\Users\Trey.JINTECH\AppData\Roaming\azuredatastudio\logs\20220810T151012\exthost1\Microsoft.mssql\SqlAssessmentReport-20220810.json' failed.
 ---> System.IO.IOException: The file 'c:\Users\Trey.JINTECH\AppData\Roaming\azuredatastudio\logs\20220810T151012\exthost1\Microsoft.mssql\SqlAssessmentReport-20220810.json' already exists.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.SqlServer.Migration.Assessment.Common.TargetAssessment.Utils.ExportAssessmentResultsAction.OpenFile(String fileName, Boolean overwriteResult)
   at Microsoft.SqlServer.Migration.Assessment.Common.TargetAssessment.Utils.ExportAssessmentResultsAction.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Migration.Assessment.Common.TargetAssessment.Utils.ExportAssessmentResultsAction.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   at Microsoft.SqlServer.Migration.Assessment.Common.Workflows.MigrationAssessmentWorkflow.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   at Microsoft.SqlServer.Migration.Assessment.Common.Engine.DmaEngine.SaveAssessmentResultsToJson(ISqlMigrationAssessmentModel assessmentModel, Boolean overwrite, String fileName)
   at Microsoft.SqlTools.ServiceLayer.Migration.MigrationService.GetAssessmentItems(String[] connectionStrings) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Migration\MigrationService.cs:line 438
   at Microsoft.SqlTools.ServiceLayer.Migration.MigrationService.HandleMigrationAssessmentsRequest(MigrationAssessmentsParams parameters, RequestContext`1 requestContext) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Migration\MigrationService.cs:line 156
	at c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1344425
	at c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1344719
	at Immediate.<anonymous> (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1345080)
	at processImmediate (internal/timers.js:461:21)

**Comment by raymondtruong** [comment] 2023-03-27 19:52
This is a duplicate of https://github.com/microsoft/azuredatastudio/issues/19617

**Comment by raymondtruong** [comment] 2023-03-28 16:56
This issue has been identified and has been fixed in the latest release.

**Closed by raymondtruong** 2023-03-28 16:56 UTC
Labels: Bug, Triage: Done, Area - SQL Migration
