### ISSUE TITLE
Logon to Azure timeout way too early on windows

### ISSUE THREAD

**Issue by ralphke** [microsoft/azuredatastudio#10790] opened 2020-06-08 15:48 UTC
Issue Type: <b>Bug</b>

With the current Data Studio Build I am unable to login to Azure and access my MS internal subscription. The issue might be related to the fact  that I have multiple subscriptions in other domains, outside of Microsoft. There is no way to specify which domain to logon first.  This behaviour breakes Data Studio, so I cannot use it with the data services I have provisioned on Azure.

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
datavirtualization|Mic|1.4.0
import|Mic|0.15.0
machine-learning|Mic|0.1.0
managed-instance-dashboard|Mic|0.4.1
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
schema-compare|Mic|1.4.0
server-report|Mic|0.2.2
sql-dw|Mic|0.0.1
azdata-sanddance|msr|1.3.9
vscodeintellicode|Vis|1.2.1

</details>

**Comment by ralphke** [comment] 2020-06-08 16:06
The error I am getting is: Retrieving the Azure token failed. Please sign in again.

**Comment by ralphke** [comment] 2020-06-08 20:39
[20200608T222844.zip](https://github.com/microsoft/azuredatastudio/files/4748495/20200608T222844.zip)
Here is the logfile from the Logs Folder.

**Comment by aaomidi** [comment] 2020-06-08 20:46
The log file seems to be missing the bug you reported. Can you open azure data studio (not insiders), press Help -> Toggle Developer Dialog and press console and see what information is getting printed there?

**Comment by aaomidi** [comment] 2020-07-25 23:03
Closing this issue. Please feel free to reopen a new one if the issue is still there on the latest insiders build.

**Closed by aaomidi** 2020-07-25 23:03 UTC
Labels: Area - Azure, Bug, Needs Logs, Triage: Done
