### ISSUE TITLE
Azure AD Auth : Error not found in cache

### ISSUE THREAD

**Issue by AlejoSQL** [microsoft/azuredatastudio#7074] opened 2019-09-05 15:29 UTC
Issue Type: <b>Bug</b>

Trying to add a credential to connect to Azure SQL DB, triggers the Azure Data Studio link and code to authenticate in browser, and then throws the above error. 

Azure Data Studio version: azuredatastudio-insiders 1.11.0-insider (b8518f5795ce15a5a524cbc0f9e531b8e02d8456, 2019-09-04T09:15:54.332Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by simongottipalli** [comment] 2019-09-16 12:33
Similar issue on Mac OSX: 10.14.6
Login Type: Microsoft MFA

**Comment by AlejoSQL** [comment] 2019-11-22 16:38
seems to be similar to #7619 .

**Comment by kburtram** [comment] 2019-11-27 20:06
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/7619.  We're looking into this area for Dec release.  Please leave any additional related comments on https://github.com/microsoft/azuredatastudio/issues/7619.  Thanks!

**Closed by kburtram** 2019-11-27 20:06 UTC
Labels: Area - Azure, Bug
