### ISSUE TITLE
Name Tabs Without Saving

### ISSUE THREAD

**Issue by sputnik-adam** [microsoft/azuredatastudio#19282] opened 2022-05-04 10:50 UTC
Issue Type: <b>Feature Request</b>

It would be good if we could name tabs without needing to save the contents as a file.

Oftentimes when working in a database we find ourselves working across multiple queries, especially when investigating issues. We can often find ourselves working with the same query investigating multiple instances of the same issue. In these circumstances, having SQLQuery_12, SQLQuery_13, SQLQuery_15, etc. is not helpful, but neither is littering files just to have names for tabs.

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:24:29.469Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by alanrenmsft** [comment] 2022-05-05 17:28
dupe of #9278

**Closed by alanrenmsft** 2022-05-05 17:28 UTC
Labels: Area - Query Editor, Enhancement, Triage: Done
