### ISSUE TITLE
select button is enabled even before azadata installtion completes

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#8734] opened 2019-12-18 22:15 UTC
Issue Type: <b>Bug</b>

It is observed on Mac using 'resource-deployment' extension.
Pre-condition: None of the kubectl, azure-cli, and azdata-cli tools needed for BDC is installed on the box.
1. Start 'New Deployment' -> select new 'BDC deployment' card.
2. Invoke the install tools button.

Observed: After kubectl and azure-cli are installed before the azdata-cli installation completes the 'select' button to allow the user to continue to the next screen becomes enabled.

Expected: Select button is enabled only after azdata installation completes.

Azure Data Studio version: azuredatastudio Dev 1.15.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.11.0

</details>

**Comment by ranasaria** [comment] 2020-01-22 02:34
fit and finish issue that we will tackle in next milestone.

**Comment by chlafreniere** [comment] 2020-03-09 20:58
Moving to April since this isn't a new regression.

**Comment by kburtram** [comment] 2021-09-10 22:36
Closing older issues without recent repro reports.  Please let us know if you're still impacted by this issue.

**Closed by kburtram** 2021-09-10 22:36 UTC
Labels: Area - Resource Deployment, Triage: Done
