### ISSUE TITLE
Server dashboard actions not working on database table

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11282] opened 2020-07-10 00:59 UTC
1. Open server dashboard
1. Go to databases
1. Click on ...

The `New Notebook` action fails with this :

```
[9512:0709/175826.006:INFO:CONSOLE(2280)] "%c  ERR color: #f33 An unknown error occurred. Please consult the log for more details.", source: C:\src\AzureDataStudio\node_modules\zone.js\dist\zone-node.js (2280)
[9512:0709/175826.008:INFO:CONSOLE(2280)] "%c  ERR color: #f33 Converting circular structure to JSON
    --> starting at object with constructor 'Node'
    |     property 'next' -> object with constructor 'Node'
    --- property 'prev' closes the circle: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Node'
    |     property 'next' -> object with constructor 'Node'
    --- property 'prev' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (file:///C:/src/AzureDataStudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:18:21)
    at Function.serializeRequestArguments (file:///C:/src/AzureDataStudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:570:23)
    at RPCProtocol._remoteCall (file:///C:/src/AzureDataStudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:349:58)
    at Proxy.target.<computed> (file:///C:/src/AzureDataStudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:140:41)
```

The `Script as Create` fails with this :

```
[9512:0709/175543.990:INFO:CONSOLE(2280)] "%c  ERR color: #f33 Cannot read property 'metadataTypeName' of undefined: TypeError: Cannot read property 'metadataTypeName' of undefined
        at Object.asScriptingParams (c:\src\AzureDataStudio\extensions\mssql\node_modules\dataprotocol-client\lib\codeConverter.js:20:24)
        at Object.scriptAsOperation (c:\src\AzureDataStudio\extensions\mssql\node_modules\dataprotocol-client\lib\main.js:801:85)
```

**Comment by alanrenmsft** [comment] 2020-07-16 05:29
dupe of #10765

**Closed by alanrenmsft** 2020-07-16 05:29 UTC
Labels: Area - Dashboard, Bug, Triage: Needed
