### ISSUE TITLE
List of Tables for Azure SQL DB Times out within 45 seconds

### ISSUE THREAD

**Issue by LRomano72** [microsoft/azuredatastudio#19170] opened 2022-04-21 16:16 UTC
Issue Type: <b>Bug</b>

1. Install or update to 1.36
2. Disconnect to an Azure SQL database
3. Click on the Tables Folder
4. Error: Object Explorer task didn't complete within 45 seconds

Azure Data Studio version: azuredatastudio 1.36.0 (0704471e6b4a79f0c2c2425b22dc6bee60a1c2a8, 2022-04-19T18:20:54.197Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (46.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.6.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.13.1
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.16.1

</details>

**Comment by Charles-Gagnon** [comment] 2022-04-21 16:30
Duplicate of https://github.com/microsoft/azuredatastudio/issues/19166

**Closed by Charles-Gagnon** 2022-04-21 16:30 UTC

**Comment by kburtram** [comment] 2022-04-21 16:39
@LRomano72 could you please add error logs to https://github.com/microsoft/azuredatastudio/issues/19166 following instructions on that issue, if possible?  Thanks!
