### ISSUE TITLE
Tab color does not change on connection change

### ISSUE THREAD

**Issue by matteovannucchi-lu** [microsoft/azuredatastudio#23992] opened 2023-07-27 07:46 UTC
Type: <b>Bug</b>

- Set tab color mode for query editor to fill
- Prepare two connection groups with different colors
- Add a connection to each group
- Start a query for one of the connections
- Change connection for the tab using the change button above the query editor and set to the one that belongs to the group with a different color
- The tab color does not change to the one of the selected group

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-data-inspector|ern|0.6.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.13.0
import|Mic|1.5.5
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.19.0
sql-database-projects|Mic|1.1.1
extra-sql-script-as|pac|0.5.0
sqlops-spexecutesql-to-sql|pej|1.0.2
sql-prompt|Red|0.2.12
sql-search|Red|0.4.1
simple-data-scripter|sea|0.1.6
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment] 2023-07-27 19:38
Duplicate of #23996

**Closed by cheenamalhotra** 2023-07-27 19:38 UTC
