### ISSUE TITLE
Export to SQL Opens Two Query Windows

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#15631] opened 2021-06-07 21:22 UTC
- Create a notebook (SQL kernel)
- Click "Export Notebook as SQL" action

2 query windows are opened:

![image](https://user-images.githubusercontent.com/40371649/121089251-bb3b0e00-c79b-11eb-8ad0-3d8c913ab79e.png)

**Comment by chlafreniere** [comment] 2021-06-07 21:22
@Charles-Gagnon have you heard about this issue before? (also, can you repro?)

**Comment by Charles-Gagnon** [comment] 2021-06-07 21:26
Duplicate of https://github.com/microsoft/azuredatastudio/issues/13250 - this is something we've had intermittent reports of for a while now. It doesn't happen to just the Notebook convert stuff either - it's a general issue we see with the extensibility API to open an editor.

**Closed by Charles-Gagnon** 2021-06-07 21:26 UTC
Labels: Area - Notebooks, Bug

**Comment by Charles-Gagnon** [comment] 2021-06-07 21:27
I can actually repro it now though with the RC1 build (never could before), is that where you're seeing it too?

**Comment by chlafreniere** [comment] 2021-06-07 21:29
@Charles-Gagnon yup I'm seeing it too in RC1

**Comment by Charles-Gagnon** [comment] 2021-06-07 21:31
Alrighty, I'll try to take a look sometime this week to see if I can repro it in main or at least add some logging to help figure out what's going on here.
