### ISSUE TITLE
Error while adding a firewall rule 

### ISSUE THREAD

**Issue by vijaypandeyy** [microsoft/azuredatastudio#16068] opened 2021-07-12 14:51 UTC
Issue Type: <b>Bug</b>

faced an issue when i was trying to connect to a sqlserver. 
I was shown a window to add a firewall rule in the sqlserver, to allow my ip for accsing the db.

error:
" firewall rule error.
Error: token retrieval failed with an error. open developer tools to view the error."

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

**Comment by abist** [comment] 2021-07-14 20:08
Do you always see this issue or was it a one time thing? Can you repro this issue again?

**Comment by vijaypandeyy** [comment] 2021-07-15 03:17
It can be reproduced.
I was trying to connect mssql server instance on azure, my ip address was not whitelisted under the "firewall and virtual network" for the sqlserver instance.

When I was trying to connect it through the azure data studio I was getting a popup for creating a firewall  rule.

![IMG_20210715_083229](https://user-images.githubusercontent.com/59576197/125721311-8468910f-13e5-4035-96f3-8d0b91fe63e2.jpg)
![IMG_20210715_083310](https://user-images.githubusercontent.com/59576197/125723474-f286d0ca-269e-480c-abf5-bab277a4d808.jpg)


I was able to connect successfully to the mssql server db instance by adding a firewall rule through azure portal.

**Comment by kburtram** [comment] 2021-08-23 18:41
This looks related to other AAD token bugs, just surfacing in a different part of the UX.  I'll close as a duplicate of https://github.com/microsoft/azuredatastudio/issues/12637 and we will verify the fix for that also addresses this use case.  Thanks!

**Closed by kburtram** 2021-08-23 18:41 UTC
Labels: Bug, Area - Azure, Triage: Done, Needs Logs
