### ISSUE TITLE
Conversion Overflow Error

### ISSUE THREAD

**Issue by tomwells2** [microsoft/azuredatastudio#13458] opened 2020-11-17 13:38 UTC
Issue Type: <b>Bug</b>

Run -
select 264.432016 * (0.0037816903274887487 / 0.900886)
Results in a Conversion Overflow Error.

Run the same in SSMS and it is fine. 

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.78GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0
whoisactive|Mic|0.1.4
poor-mans-tsql-formatter|Tao|1.7.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by alanrenmsft** [comment] 2020-11-18 19:46
dupe of #275, btw, that is a really old bug. 😨 I will take a look at it.

**Closed by alanrenmsft** 2020-11-18 19:46 UTC
Labels: Area - Query Editor, Bug, Triage: Needed
