### ISSUE TITLE
VS2019 is publishing but AzDataStudio is falling with the same scripts and profile file

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/azuredatastudio#13157] opened 2020-10-30 19:38 UTC
- Azure Data Studio Version:

>Version: 1.23.0 (user setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134

- Visual Studio Version:

![devenv_QV94XveCgA](https://user-images.githubusercontent.com/33104726/97754957-99ff9a00-1ab5-11eb-972b-6d9af02ea2ee.png)

- Steps to Reproduce:

1. Create a project from a small Az Synapse DB in Visual Studio 2019 build and publish.
2. Sync with AzDS using previous project and profile file to build and publish.

- Issue:

Build and Publish successful in VS2019

![devenv_YTGmcvd96n](https://user-images.githubusercontent.com/33104726/97754755-4d1bc380-1ab5-11eb-9fc4-5f9ac069a222.png)

Error logs in Az Data Studio:

```
Deploy dacpac: Could not deploy package.
Warning SQL0: Your permissions to see all objects in the server or database could not be verified. The original error was:
The SELECT permission has not been granted on 'sys.sql_logins' for the 'master' database. You must be a member of the 'loginmanager' role to access this system view.
Reverse Engineer will continue the import process, and logins will not be imported.
The reverse engineering operation will attempt to continue anyway, but the resulting model might be incomplete, malformed, or incorrect.
Warning SQL72015: The table [schema].[table_name] is being dropped, data loss could occur.
Warning SQL72015: The table ... other tables same message ...
Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 50000, Level 16, State 127, Line 1 Rows were detected. The schema update is terminating because data loss might occur.
Error SQL72045: Script execution error. The executed script:
IF EXISTS (SELECT TOP 1 1
FROM [schema].[another_table])
RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127)
WITH NOWAIT;
```

```
** Highlights
     Tables that will be rebuilt
       None
     Clustered indexes that will be dropped
       None
     Clustered indexes that will be created
       None
     Possible data issues
       None

** User actions

** Supporting actions

Your permissions to see all objects in the server or database could not be verified.  The original error was:
The SELECT permission has not been granted on 'sys.sql_logins' for the 'master' database. You must be a member of the 'loginmanager' role to access this system view. 
Reverse Engineer will continue the import process, and logins will not be imported.
The reverse engineering operation will attempt to continue anyway, but the resulting model might be incomplete, malformed, or incorrect.
```

**Comment by udeeshagautam** [comment] 2020-11-03 00:26
@virtualdvid thanks for reprorting the issue. Can you please help with following question to repro the issue on our end
1. Can you please share the profile file or let us know if there is any setting specifically added in the profile or it was just using the default settings?
2. The error seems like there was data loss possibility on the target database, Can you please confirm if you are deployng to a new database or existing database. By default ADS has Block on possible data loss set to true, Can you please try to add the followin the profle file and try to deploy

**Comment by udeeshagautam** [comment] 2020-11-03 00:29
@Benjin can you please take a look

**Comment by virtualdvid** [comment] 2020-11-03 21:01
> thanks for reprorting the issue. Can you please help with following question to repro the issue on our end
> 
> 1. Can you please share the profile file or let us know if there is any setting specifically added in the profile or it was just using the default settings?
> 2. The error seems like there was data loss possibility on the target database, Can you please confirm if you are deploying to a new database or existing database.
> 
> By default ADS has Block on possible data loss set to true, Can you please try to add the following in the profle file and try to publish using the profile file.

Hi @udeeshagautam 

Sure, here what I have:

1. I used the default settings. There were a pop-up asking to sync AzDF and VS2019. Got this file:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <Name>my_project_name</Name>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectVersion>4.1</ProjectVersion>
    <ProjectGuid>{...}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.my_table.my_table.SqlDwDatabaseSchemaProvider</DSP>
    <OutputType>Database</OutputType>
    <RootPath>
    </RootPath>
    <RootNamespace>my_project_name</RootNamespace>
    <AssemblyName>my_project_name</AssemblyName>
    <ModelCollation>1033,CI</ModelCollation>
    <DefaultFileStructure>BySchemaAndSchemaType</DefaultFileStructure>
    <DeployToDatabase>True</DeployToDatabase>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetLanguage>CS</TargetLanguage>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <SqlServerVerification>False</SqlServerVerification>
    <IncludeCompositeObjects>True</IncludeCompositeObjects>
    <TargetDatabaseSet>True</TargetDatabaseSet>
    <DefaultCollation>SQL_Latin1_General_CP1_CI_AS</DefaultCollation>
    <QueryStoreCaptureMode>None</QueryStoreCaptureMode>
    <QueryStoreDesiredState>Off</QueryStoreDesiredState>
    <QueryStoreFlushInterval>0</QueryStoreFlushInterval>
    <QueryStoreStatsInterval>0</QueryStoreStatsInterval>
    <QueryStoreMaxPlansPerQuery>0</QueryStoreMaxPlansPerQuery>
    <QueryStoreStaleQueryThreshold>0</QueryStoreStaleQueryThreshold>
    <QueryStoreMaxStorageSize>0</QueryStoreMaxStorageSize>
    <DbScopedConfigLegacyCardinalityEstimation>Off</DbScopedConfigLegacyCardinalityEstimation>
    <DbScopedConfigLegacyCardinalityEstimationSecondary>Off</DbScopedConfigLegacyCardinalityEstimationSecondary>
    <DbScopedConfigMaxDOP>0</DbScopedConfigMaxDOP>
    <DbScopedConfigMaxDOPSecondary>0</DbScopedConfigMaxDOPSecondary>
    <DbScopedConfigParameterSniffing>Off</DbScopedConfigParameterSniffing>
    <DbScopedConfigParameterSniffingSecondary>Off</DbScopedConfigParameterSniffingSecondary>
    <DbScopedConfigOptimizerHotfixes>Off</DbScopedConfigOptimizerHotfixes>
    <DbScopedConfigOptimizerHotfixesSecondary>Off</DbScopedConfigOptimizerHotfixesSecondary>
    <DelayedDurability>DISABLED</DelayedDurability>
    <AutoCreateStatisticsIncremental>False</AutoCreateStatisticsIncremental>
    <MemoryOptimizedElevateToSnapshot>False</MemoryOptimizedElevateToSnapshot>
    <Containment>None</Containment>
    <IsNestedTriggersOn>True</IsNestedTriggersOn>
    <IsTransformNoiseWordsOn>False</IsTransformNoiseWordsOn>
    <TwoDigitYearCutoff>2049</TwoDigitYearCutoff>
    <NonTransactedFileStreamAccess>OFF</NonTransactedFileStreamAccess>
    <TargetRecoveryTimePeriod>60</TargetRecoveryTimePeriod>
    <TargetRecoveryTimeUnit>SECONDS</TargetRecoveryTimeUnit>
    <IsChangeTrackingOn>False</IsChangeTrackingOn>
    <IsChangeTrackingAutoCleanupOn>False</IsChangeTrackingAutoCleanupOn>
    <ChangeTrackingRetentionPeriod>0</ChangeTrackingRetentionPeriod>
    <IsEncryptionOn>False</IsEncryptionOn>
    <IsBrokerPriorityHonored>False</IsBrokerPriorityHonored>
    <Trustworthy>False</Trustworthy>
    <AutoUpdateStatisticsAsynchronously>False</AutoUpdateStatisticsAsynchronously>
    <PageVerify>NONE</PageVerify>
    <ServiceBrokerOption>DisableBroker</ServiceBrokerOption>
    <DateCorrelationOptimizationOn>False</DateCorrelationOptimizationOn>
    <Parameterization>SIMPLE</Parameterization>
    <AllowSnapshotIsolation>False</AllowSnapshotIsolation>
    <ReadCommittedSnapshot>False</ReadCommittedSnapshot>
    <VardecimalStorageFormatOn>False</VardecimalStorageFormatOn>
    <SupplementalLoggingOn>False</SupplementalLoggingOn>
    <CompatibilityMode>130</CompatibilityMode>
    <AnsiNullDefault>True</AnsiNullDefault>
    <AnsiNulls>True</AnsiNulls>
    <AnsiPadding>True</AnsiPadding>
    <AnsiWarnings>True</AnsiWarnings>
    <ArithAbort>True</ArithAbort>
    <ConcatNullYieldsNull>True</ConcatNullYieldsNull>
    <QuotedIdentifier>True</QuotedIdentifier>
    <NumericRoundAbort>True</NumericRoundAbort>
    <RecursiveTriggersEnabled>False</RecursiveTriggersEnabled>
    <DatabaseChaining>False</DatabaseChaining>
    <DatabaseState>ONLINE</DatabaseState>
    <CloseCursorOnCommitEnabled>False</CloseCursorOnCommitEnabled>
    <DefaultCursor>GLOBAL</DefaultCursor>
    <AutoClose>False</AutoClose>
    <AutoCreateStatistics>True</AutoCreateStatistics>
    <AutoShrink>False</AutoShrink>
    <AutoUpdateStatistics>False</AutoUpdateStatistics>
    <TornPageDetection>False</TornPageDetection>
    <DatabaseAccess>MULTI_USER</DatabaseAccess>
    <Recovery>SIMPLE</Recovery>
    <EnableFullTextSearch>False</EnableFullTextSearch>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>bin\Release\</OutputPath>
    <BuildScriptName>$(MSBuildProjectNamemy_table.sql</BuildScriptName>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Debug\</OutputPath>
    <BuildScriptName>$(MSBuildProjectNamemy_table.sql</BuildScriptName>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">11.0</VisualStudioVersion>
    <!-- Default to the v11.0 targets path if the targets file for the current VS version is not found -->
    <SSDTExists Condition="Exists('$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\SSDT\Microsoft.Data.Tools.my_table.SqlTasks.targets')">True</SSDTExists>
    <VisualStudioVersion Condition="'$(SSDTExists)' == ''">11.0</VisualStudioVersion>
  </PropertyGroup>
  <Import Condition="'$(NetCoreBuild)' != 'true' AND '$(SQLDBExtensionsRefPath)' != ''" Project="$(SQLDBExtensionsRefPath)\Microsoft.Data.Tools.my_table.SqlTasks.targets" />
  <Import Condition="'$(NetCoreBuild)' != 'true' AND '$(SQLDBExtensionsRefPath)' == ''" Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\SSDT\Microsoft.Data.Tools.my_table.SqlTasks.targets" />
  <ItemGroup>
    <Folder Include="Properties" />
    <Folder Include="my_schema\" />
    <Folder Include="my_schema\Tables\" />
    <Folder Include="Security\" />
    <Folder Include="my_schema\StoredProcedures" />
  </ItemGroup>
  <ItemGroup>
    <Build Include="my_schema\Tables\my_table.sql" />
    <Build Include="Security\my_setting.sql" />
    <Build Include="my_schema\StoredProcedures\my_sp.sql" />
  </ItemGroup>
  <Import Condition="'$(NetCoreBuild)' == 'true'" Project="$(NETCoreTargetsPath)\Microsoft.Data.Tools.my_table.SqlTasks.targets" />
  <ItemGroup>
    <PackageReference Condition="'$(NetCoreBuild)' == 'true'" Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="All" />
  </ItemGroup>
  <Target Name="AfterClean">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
</Project>
```

2. There is already three tables with data. Wondering why in VS2019 doesn't raise the data issue and AzDF does it.

I'm going to test `<BlockOnPossibleDataLoss>False</BlockOnPossibleDataLoss>` and let you know how it goes. Thanks!

**Comment by virtualdvid** [comment] 2020-11-09 23:08
Update.

I keep getting errors with properties from VS2019 (working fine `publish` in VS2019). 

![image](https://user-images.githubusercontent.com/33104726/98606362-02136480-229c-11eb-8a2b-18decc8f6e00.png)

Even if I change that property to `false` another property fails.

Also another minor thing is, I can exclude scripts but there is not way to include them like in VS19:

![image](https://user-images.githubusercontent.com/33104726/98606889-e6f52480-229c-11eb-9163-c1ca3770d9c9.png)

VS19:

![image](https://user-images.githubusercontent.com/33104726/98607024-2754a280-229d-11eb-86af-0ef1edd54999.png)

**Comment by udeeshagautam** [comment] 2020-11-10 21:48
Thanks for the details - will debug on our side and update further.

**Comment by udeeshagautam** [comment] 2020-11-10 21:59
>Also another minor thing is, I can exclude scripts but there is not way to include them like in VS19

for this part opened a seperate tracking task https://github.com/microsoft/azuredatastudio/issues/13344 for granularity

**Comment by Benjin** [comment] 2020-11-13 01:26
Hey @virtualdvid, with my small Azure Synapse (table with some data and a stored procedure, I haven't been able to reproduce this failure - the project created in VS 2019 was able to be published successfully from Azure Data Studio.

Could you email me either a dacpac or a complete setup script at benjind@microsoft.com?  Thanks!

**Comment by virtualdvid** [comment] 2020-11-16 15:36
Hi @Benjin, Unfortunately I can't share the dacpac because it contains information of the company I'm currently working on.

**Comment by Benjin** [comment] 2020-11-16 17:19
@virtualdvid Perhaps an isolated repro in the form of either a dacpac without data but with different table/column names, or a TSQL script I can execute on a clean database, maybe?

**Comment by virtualdvid** [comment] 2020-11-18 17:28
Hi @Benjin,

I found the root of the issue.

What is happening is in VS2019 when I'm setting the properties `DoNotDrop...` there are some that are by default unselected. This ones are not getting updated in the profile file. Once I put them explicit in the file the error message disappears.

![image](https://user-images.githubusercontent.com/33104726/99564706-a1f97e00-297f-11eb-90db-cc708ea54062.png)

![azuredatastudio_QDg23Wfgb9](https://user-images.githubusercontent.com/33104726/99565151-2cda7880-2980-11eb-9324-e20697f69fbb.png)

Wondering how to setup this settings in Az Data Studio.

**Comment by Benjin** [comment] 2020-11-20 20:53
Good find!  Based on that, it looks like it may be related to https://github.com/microsoft/azuredatastudio/issues/12847.  Schema Compare uses different set of defaults from Publish in SSDT, but we reused them over in ADS.  Looks like the Schema Compare defaults `DropRoleMembersNotInSource` and `DropPermissionsNotInSource` to _true_ if they aren't explicitly listed in the publish profile: https://github.com/microsoft/sqltoolsservice/blob/fd843670084ab814f6bb56abb523e3a4abdfa4e9/src/Microsoft.SqlTools.ServiceLayer/SchemaCompare/Contracts/DeploymentOptions.cs#L266

I'm guessing that my repro attempt didn't encounter the same error because I didn't have those objects in the project.  Let's see if preserving the same defaults works for you, otherwise I may still need an explicit repro script.

**Comment by virtualdvid** [comment] 2020-11-20 22:48
@Benjin, Putting the parameters explicitly in the `publish.xml` file worked. I was able to publish without issues. Those settings are by default in SSDT but AzDS doesn't have them.

**Comment by kisantia** [comment] 2020-12-15 00:51
@Benjin were you able to update ADS to use the new default options?

**Comment by kisantia** [comment] 2022-08-15 16:40
closing now that the Dac Deploy Options are now exposed in the publish dialog, added in https://github.com/microsoft/azuredatastudio/pull/19789. This is now available in insiders and will be in the next release.

**Closed by kisantia** 2022-08-15 16:40 UTC
Labels: Bug, Pri: 1, Triage: Done, Area - SQL Project
