### ISSUE TITLE
Double results grids

### ISSUE THREAD

**Issue by timg83** [Microsoft/azuredatastudio#4041] opened 2019-02-14 10:08 UTC
Issue Type: <b>Bug</b>

Sometimes when executing a query the result grid shows twice. Executing the query again fixes this. Two grid are confusing when you execute one select statement and expect only one grid.

![afbeelding](https://user-images.githubusercontent.com/2979347/52779532-a70df880-3048-11e9-91fb-ab99ae59e472.png)

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|11.37GB (2.87GB free)|
|Process Argv|C:\Users\tim.xxxx\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by gregveres** [comment] 2019-02-14 15:11
I have seen this many times too. I have not been able to figure out a reproducible test case.

Unlike the original poster, once this happens it seems the only way to get everything stable is to close this query tab and start again with a fresh query.

**Comment by jsh121988** [comment] 2019-02-14 16:33
Have you tried updating to the latest version. I'm running 1.4.5, and the latest release notes state that this was resolved. I was running into this issue as well previously.

**Comment by gregveres** [comment] 2019-02-14 16:42
Ah, I am still on 1.3.9. I will update right now. Thanks!

**Comment by kburtram** [comment] 2019-02-14 18:53
As @jsh121988 mentioned, we think this issue should be resolved in 1.4.5.  Sorry for the inconvenience.  

I'll close as a duplicate of https://github.com/Microsoft/azuredatastudio/issues/3759.  Please let me know if the issue still occurs after upgrade.  Thanks!

**Closed by kburtram** 2019-02-14 18:53 UTC

**Comment by timg83** [comment] 2019-02-19 12:06
Update resolved the issue 👍
