### ISSUE TITLE
Application hangs when click on show compare

### ISSUE THREAD

**Issue by desmonddongxu** [microsoft/azuredatastudio#15426] opened 2021-05-12 13:40 UTC
Right click on one file select Select for Compare
Right click on another file and select Compare with Selected
Application hang and Error popup: The Window is no longer responding
![image](https://user-images.githubusercontent.com/56276382/117984698-0c272600-b306-11eb-93c5-508225714027.png)
if keep waiting, get this
![image](https://user-images.githubusercontent.com/56276382/118000557-eacd3680-b313-11eb-8d4a-ac2e15e94e93.png)

**Comment by Charles-Gagnon** [comment] 2021-05-12 16:06
Duplicate of #15180 - see that issue for instructions to revert to a working version until a build with the fix is released.

**Closed by Charles-Gagnon** 2021-05-12 16:06 UTC
