### ISSUE TITLE
ADS ui got truncated suddenly while duplicating to a screen

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7644] opened 2019-10-10 22:20 UTC
![ads-truncated-ui](https://user-images.githubusercontent.com/10999577/66610763-764b7800-eb71-11e9-8c9b-9f6c04c8ef4b.png)
Issue Type: <b>Bug</b>

See attached picture & the empty bar on the right. I couldn't see the File & other menu options, OE disappeared a bit & so on. This is bit crazy & happened during a demo. Had to close & reopen everything.

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (f475c04ce33cebe739cad383410a1f4a48f041b0, 2019-10-09T08:22:13.771Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (14.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by ellbosch** [comment] 2019-10-14 22:13
Thanks @uc-msft for bringing this to light. I'm so sorry this happened during a demo!

**Comment by aaomidi** [comment] 2019-10-14 22:15
This is likely an electron issue.

**Comment by chlafreniere** [comment] 2019-10-24 06:59
Dupe of #7613

**Closed by chlafreniere** 2019-10-24 06:59 UTC
Labels: Area - Notebooks, Area - Shell, Bug, Triage: Needed
