### ISSUE TITLE
new feature filter file like ms sql server management stdio

### ISSUE THREAD

**Issue by amitsinghrawat1994** [Microsoft/azuredatastudio#3365] opened 2018-11-30 04:18 UTC
- Azure Data Studio Version:
it will be best if there is a filter option to search files (tables views, stored procedures etc)

**Comment by kburtram** [comment] 2018-12-04 21:00
This looks like a duplicate of https://github.com/Microsoft/azuredatastudio/issues/3331.  Please add any comments there if anything is missing.

**Closed by kburtram** 2018-12-04 21:00 UTC
