### ISSUE TITLE
option to not run query by default with Select Top 1000

### ISSUE THREAD

**Issue by gregveres** [microsoft/azuredatastudio#9336] opened 2020-02-25 23:55 UTC
Issue Type: <b>Feature Request</b>

I use "Select Top 1000" and "Edit Data" a lot in ADS.  However, the amount of times that I want the results of the default query that ADS gives me is about 1% of the time. 

This means that the database has been queried needlessly 99% of the time I am using ADS. if there was an option in the configuration to not send the default query command when I select these options, I would definitely enable that option. 

I would like to request some configuration option (because I know not everybody will want to enable it) to turn off the sending of these default queries. If this configuration option is enabled, then I would be able to "Select Top 1000" or "Edit Data" and the query editor would come up with the query, but the query would not have been sent to the server yet. This gives me a chance to edit the query the way that I need to and then run the query when I am ready. 

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

**Comment by cssuh** [comment] 2023-08-09 23:40
Closing - duplicate of #4043

**Closed by cssuh** 2023-08-09 23:40 UTC
Labels: Area - Query Editor, Enhancement, Triage: Done
