### ISSUE TITLE
Executing same SQL notebook against multiple databases is cumbersome...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7687] opened 2019-10-11 16:31 UTC
Issue Type: <b>Bug</b>

I have to either edit a cell & change the database name or have a separate connection altogether. In the TSQL editor, you can just switch the database on top without mucking around with anything else.

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (93c9426f25e632e8e3dd6e572d48d559ae07a7bf, 2019-10-10T18:18:16.586Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by kevcunnane** [comment] 2019-10-11 19:34
@chlafreniere - it looks like this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/4722. Action I'm taking:
- Move the related bug out of backlog and into planning, since we really need to revisit this in the upcoming months. It's one of the few gaps vs query editor (but does require toolbar refactor)
- Closing this bug since we prefer to use the original issue where possible. Thanks UC for bringing this issue back up the priority queue.

**Closed by kevcunnane** 2019-10-11 19:34 UTC
