### ISSUE TITLE
Lower case 'i' does not work when typing

### ISSUE THREAD

**Issue by kspittler** [microsoft/azuredatastudio#24797] opened 2023-10-27 13:44 UTC
Type: <b>Bug</b>

lower case 'i' does not show when pressed on either of my keyboards. it does work on all other applications but azure data studio. It also works if I shift-'i' to uppercase. Not sure how this happend or how to fix it. thank you - kevin

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-oracle|Mic|0.1.5
import|Mic|1.5.5
net-6-runtime|Mic|1.1.0
azdata-sanddance|msr|4.1.1

</details>

**Comment by smartguest** [comment] 2023-10-27 18:08
Can you tell me which areas have you encountered this bug? Such as in settings or in Query Editor?

**Comment by kspittler** [comment] 2023-10-27 18:09
Query editor

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kburtram** [comment] 2023-10-27 20:29
@kspittler I wasn't able to reproduce this issue in my environment.  It's possible that `i` was somehow mapped as a Keyboard Shortcut to a command that is not doing some noticeable action.  You may check the "Keyboard Shortcuts" configuration page available from the Preferences menu.

Otherwise, you could try resetting the application state under [userhomedir]\AppData\Roaming\azuredatastudio, though deleting that cached content would clear out saved connections and other preferences.

**Comment by kspittler** [comment] 2023-10-30 12:49
Wow! Thank you that worked. It was created to refresh intelisense.

Cheers,

Kevin Spittler, MBA-HCA | Strategic Data Analyst | Institute for H.O.P.E™
***@***.******@***.***>

**Comment by SakshiS-harma** [comment] 2023-10-30 17:46
Thanks for the confirmation Kevin. 
Closing this issue since it is resolved.

**Closed by SakshiS-harma** 2023-10-30 17:46 UTC
Labels: Bug, Area - Shell, Triage: Needed
