### ISSUE TITLE
Syntax Highlighting Error with Block Comments

### ISSUE THREAD

**Issue by Kellett** [microsoft/azuredatastudio#14045] opened 2021-01-25 14:08 UTC
- Azure Data Studio Version: 
Version: 1.25.2 (system setup)
Commit: 4d4917d328ab7a7526817a0f0ef03237a79aa54d
Date: 2021-01-20T22:52:13.492Z (4 days ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

---

- Steps to Reproduce:

1. Open a window with an active connection to a MS SQL database
2. Enter the following 
```
/*
PRINT 1
/*
PRINT 2
*/
PRINT 3
*/
PRINT 4
```

3. The syntax highlighting will assume the block comment stops above the PRINT 3 line
4. Run the query and you will see only the final line will execute as the rest are commented out.

---

- Screenshot of issue:
![image](https://user-images.githubusercontent.com/1553850/105716199-68606880-5f16-11eb-9c94-7d5cda8b9411.png)

**Comment by Charles-Gagnon** [comment] 2021-01-25 17:05
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/848

**Closed by Charles-Gagnon** 2021-01-25 17:05 UTC
