### ISSUE TITLE
Can't read matching text when filtering in quickpick because of color

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#17095] opened 2021-09-17 00:19 UTC
Version: insiders

The matching text is the same or very similar color to the selected item background, making it very hard to read.

![image](https://user-images.githubusercontent.com/31145923/133704424-337bea0a-8562-4b67-bb5e-464272d764a9.png)

**Comment by chlafreniere** [comment] 2021-09-22 20:37
I'm running into this both with command palette and Intellisense completion lists:

![image](https://user-images.githubusercontent.com/40371649/134418053-6276cdcf-c9bb-4b5c-984c-086eab9fd826.png)

@kburtram any chance that we could get someone from your team to take a look for October?

**Comment by kburtram** [comment] 2021-09-22 20:51
@chlafreniere this looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/17001.  @smartguest is looking into this.

**Closed by kburtram** 2021-09-22 20:51 UTC
Labels: Bug, Area - Shell, Triage: Needed, Impact: UI
