### ISSUE TITLE
Saving Query Editor disconnects session for that editor

### ISSUE THREAD

**Issue by haydnlj** [microsoft/azuredatastudio#11474] opened 2020-07-22 04:20 UTC
Issue Type: <b>Bug</b>

Start adhoc query, save query as .sql file to filesystem. Upon save, the current SQL connection is closed for that editor.

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
import|Mic|0.18.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0

(2 theme extensions excluded)

</details>

**Comment by kburtram** [comment] 2021-09-03 18:13
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/1876.  Thanks for reporting this issue!

**Closed by kburtram** 2021-09-03 18:13 UTC
Labels: Bug, Area - Query Editor, Triage: Done, Triage: Postponed
