### ISSUE TITLE
Korean Language Broken

### ISSUE THREAD

**Issue by Zerglrisk** [microsoft/azuredatastudio#17853] opened 2021-12-08 04:50 UTC
- Azure Data Studio Version:
Version: 1.33.1 (system setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19044

- OS Version:
Microsoft Windows 10
Version 21H2 (OS Build 19044.1387)

Steps to Reproduce:

1. Launch ADS.
2. Click Account in Side Menu
3. Check Accounts what include my name as korean
![image](https://user-images.githubusercontent.com/8271831/145149779-3fee01c1-5047-457d-9fe0-5a91153ce188.png)

Script, Table Column Name with korean is all fine :)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Zerglrisk** [comment] 2021-12-08 04:52
is this problem relate with azrue data studio ?

after install 'Korean Language Pack for Azure Data Studio' Extension
![image](https://user-images.githubusercontent.com/8271831/145150229-94879149-2017-4acf-8f32-a6fb50467925.png)

cannot find link account right side, but left below azure tab exist accounts. 
![image](https://user-images.githubusercontent.com/8271831/145150197-63066d44-fc12-4c56-92d1-14cf449885ec.png)

**Comment by Charles-Gagnon** [comment] 2021-12-08 17:20
@smartguest

**Comment by smartguest** [comment] 2021-12-08 17:40
This is not an issue with the Language Pack as those use pre generated text @Zerglrisk @Charles-Gagnon . This has something to do with Azure Data Studio retrieving the name from Azure services and not rendering it correctly, a lot of languages have this issue not just Korean, I am still investigating how to solve this issue as it appears that copying the name directly into Azure Data Studio works fine but whatever is passed from Azure has no proper encoding that is handled by ADS.

**Comment by smartguest** [comment] 2021-12-08 17:42
This is a duplicate of https://github.com/microsoft/azuredatastudio/issues/15598
and https://github.com/microsoft/azuredatastudio/issues/17754

**Comment by Charles-Gagnon** [comment] 2021-12-08 17:47
@cssuh What about the second issue that @Zerglrisk mentioned - it appears that their accounts aren't showing up correctly in the Add Account dialog (even though you can see them listed in the Azure pane in the bottom left). (@Zerglrisk let me know if I got that correct...)

**Comment by cssuh** [comment] 2021-12-08 19:39
@Charles-Gagnon yes that seems odd, let me take a look and see if I can repro anything like that

**Comment by Zerglrisk** [comment] 2021-12-09 06:46
> is this problem relate with azrue data studio ?
> 
> after install 'Korean Language Pack for Azure Data Studio' Extension ![image](https://user-images.githubusercontent.com/8271831/145150229-94879149-2017-4acf-8f32-a6fb50467925.png)
> 
> cannot find link account right side, but left below azure tab exist accounts. ![image](https://user-images.githubusercontent.com/8271831/145150197-63066d44-fc12-4c56-92d1-14cf449885ec.png)

I Testeid why it happend that right after launch ads, click the account button in side menu while load Azure pane in bottom left tab. than can't see the accounts

![image](https://user-images.githubusercontent.com/8271831/145346969-0f4ffee1-3a40-4e95-8aa3-6ac2f1802fb5.png)

![image](https://user-images.githubusercontent.com/8271831/145347302-cb095fe4-b0fb-40ea-a0c4-062d7264b7c6.png)

keep can't get account list -> have to restart ADS
![image](https://user-images.githubusercontent.com/8271831/145347442-7c0829de-8fb6-4605-ae41-6d4415a94c70.png)

**Comment by kburtram** [comment] 2022-02-28 20:52
@smartguest could you please take a look @Zerglrisk's previous comment and confirm if you can repro, and if so determine the cause?  thanks!

**Comment by smartguest** [comment] 2022-02-28 22:55
@kburtram the second issue is not caused by the language pack, it's basically a general issue with ADS where if you try to add a new account before the azure accounts list has been fully loaded, the list of accounts is blank and will remain that way until ADS is restarted and the azure account list has been loaded. This issue only happens if you rush to try to create a new account without letting the azure accounts load first (which takes about a couple of seconds on my side) and isn't generally something most users would encounter. I should file this as a separate bug for ADS, while the other bug involving the Korean name not displaying correctly is an existing bug with Azure account usernames with special characters in general. Then I can close this issue, as these are two separate problems.

**Comment by smartguest** [comment] 2022-03-15 19:24
Closing issue as the account loading issue has been fixed, the Korean characters not displaying issue is already a duplicate of an existing issue.

**Closed by smartguest** 2022-03-15 19:24 UTC
Labels: Bug, Area - Localization, Triage: Done
