### ISSUE TITLE
Incorrect syntax near 'or'.

### ISSUE THREAD

**Issue by immortalxxx** [microsoft/azuredatastudio#13329] opened 2020-11-10 07:38 UTC
We have written the needed data into your clipboard because it was 
Issue Type: <b>Bug</b>

Hi guys,
Please paste the following in a new query window and you will see that ADS doesn't recognise a valid statements and throws 2 errors "Incorrect syntax near 'or'." and "Incorrect syntax: 'ALTER PROCEDURE' must be the only statement in the batch.":

create or alter procedure di.usp_dupa
as 
BEGIN
    select * from di.GlobalVariables
end
go

Thanks
Daniel

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0
azdata-sanddance|msr|3.1.0

</details>
too large to send. Please paste.

**Comment by santivarm** [comment] 2020-11-12 20:52
This looks to be a duplicate of #7745 which was closed due to inactivity. In there it was mentioned that this was occurring when connected to an Azure SQL DB.

I can reproduce this when testing on the simplified script mentioned in that issue when pointing to an Azure SQL DB:

```
create or alter procedure procTest
as
begin
 print (1)
end
go
```

![create_or_alter_issue](https://user-images.githubusercontent.com/14864189/98995205-ff647980-24fe-11eb-95e7-df49c22d3db3.png)

**Comment by immortalxxx** [comment] 2020-11-17 07:32
Hi santivarm I confirm we use Azure SQL databases.

**Comment by Charles-Gagnon** [comment] 2021-06-09 00:30
This should be fixed in the next release of ADS - if you are able to verify this on the latest version of our insiders builds that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Closed by Charles-Gagnon** 2021-06-09 00:30 UTC
Labels: Area - Language Service, Bug, Triage: Done
