### ISSUE TITLE
Cannot type ">" character with Hungarian keyboard layout

### ISSUE THREAD

**Issue by karolygere** [Microsoft/azuredatastudio#3622] opened 2018-12-13 10:30 UTC
Issue Type: <b>Bug</b>

Steps to produce bug:

1. Set your keyboard layout to Hungarian
2. Start Azure Data Studio
3. Open new Query tab
4. On your keyboard press and hold AltGr (right Alt) key and press Y key

Expected result: ">" character produced in editor
Actual result: nothing is typed

This makes writing  conditions like "<>", ">", ">=" very difficult, as the ">" character must be copy-pasted from outside Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.63GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.3.0
server-report|Mic|0.1.3

</details>

**Comment by vickyharp** [comment] 2018-12-18 19:41
Interesting. Do you see different behavior in VSCode or in Google Chrome? Does Ctrl+Alt+Y work in your setup?

**Comment by kburtram** [comment] 2019-01-23 00:09
This looks like a duplicate of https://github.com/Microsoft/azuredatastudio/issues/1605.  Basically we need to remove the Ctrl-Alt shortcuts.  I think the old up was determining which shortcuts to use instead.

**Closed by kburtram** 2019-01-23 00:09 UTC
