### ISSUE TITLE
Error when execute select

### ISSUE THREAD

**Issue by chkumar10** [microsoft/azuredatastudio#10173] opened 2020-04-27 17:45 UTC
Issue Type: <b>Bug</b>

Query failed: The connection does not support MultipleActiveResultSets.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:06:16.901Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment] 2020-05-07 19:54
Looks like a likely duplicate of https://github.com/microsoft/azuredatastudio/issues/3594.  Please add any additional related comments to that issue.  Thanks for reporting!

**Closed by kburtram** 2020-05-07 19:54 UTC
Labels: Area - Connection, Bug, Triage: Needed
