### ISSUE TITLE
Notebooks experience error on machine without Python

### ISSUE THREAD

**Issue by jeroenterheerdt** [Microsoft/azuredatastudio#4557] opened 2019-03-15 22:44 UTC
Issue Type: <b>Bug</b>

With the latest version on a machine without Python there is no set up started and it gives me a ‘could not display contents: Notebook provider does not exist’. Should a user install Python on their own? Then we need a better error message 😊

Reproduce: open a notebook on a machine that has no Python installed. I am on Windows using the latest ADS Insider build (2019-03-15T07:13:26...)

Azure Data Studio version: azuredatastudio 1.5.1-insider (4014c1d0abcae1a621480dcfbea278497343d647, 2019-03-15T07:31:53.929Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (21.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment] 2019-03-25 20:55
Probably related to #4580.

**Comment by chlafreniere** [comment] 2019-03-26 18:33
Closing this as a dupe of #4580

**Closed by chlafreniere** 2019-03-26 18:33 UTC
Labels: bug, notebooks
