### ISSUE TITLE
Broken layout after using scrollbar in notebook

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#7613] opened 2019-10-09 18:06 UTC
Issue Type: <b>Bug</b>

The layout in ADS was broken after using the notebook and I think the last thing was using the scrollbar. The viewlet and menus were hidden:

![ads](https://user-images.githubusercontent.com/17187348/66507825-c26cbe80-ea84-11e9-8bd5-2b227ba7e3ab.png)

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (8e1a2248e47925eb825b0ce037b96b6c87798a8a, 2019-10-04T07:52:03.973Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (12.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ellbosch** [comment] 2019-10-14 18:37
Thanks @llali, have you been able to repro this since this post?

**Comment by chlafreniere** [comment] 2021-01-29 21:34
Chatted with @llali offline and confirmed that she hasn't seen this recently. Therefore, closing this issue.

**Closed by chlafreniere** 2021-01-29 21:34 UTC
Labels: Area - Notebooks, Bug, Triage: Done
