### ISSUE TITLE
Refreshing AAD Credentials Never Works

### ISSUE THREAD

**Issue by OliverRC** [microsoft/azuredatastudio#17082] opened 2021-09-15 10:27 UTC
Issue Type: <b>Bug</b>

If my token or credentials expire or get stale there is no way update them.

Sure I can try use the "Re-authenticate" button but it does absolultey nothing. 
You go through the process but try refresh the Azure blade for subsriptions and databases and it just pops it open again.

It's never worked... not even once.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (14.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment] 2021-09-15 21:04
@cssuh do you know if this is a duplicate of the other access token refresh bugs we're looking at?  Or is this something else?

**Comment by cssuh** [comment] 2021-09-15 22:24
yes I believe this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/12637 which @caohai is working on now.

**Comment by cssuh** [comment] 2021-09-15 22:28
closing as this is a duplicate item

**Closed by cssuh** 2021-09-15 22:28 UTC
Labels: Bug, Area - Azure, Triage: Needed

**Comment by cssuh** [comment] 2021-09-15 22:29
@OliverRC you can try the steps listed in the duplicate issue #12637 I have linked above (removing/re-adding your azure account) as a temporary workaround, we are currently working to resolve this issue
