### ISSUE TITLE
Schema Intellisense does not appear

### ISSUE THREAD

**Issue by chrisbennell** [microsoft/azuredatastudio#17923] opened 2021-12-15 09:39 UTC
Issue Type: <b>Bug</b>

Probably 80% of the time, intellisense does not appear for tables and column names when writing SQL queries. When it does appear it can easily suddenly not show again

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (11.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment] 2021-12-21 18:21
@aasimkhan30 I believe you've added logging to troubleshoot this kind of issues, right? what do we need from the user?

**Comment by aasimkhan30** [comment] 2021-12-21 18:30
Unfortunately, I have not added logging yet.

**Comment by kburtram** [comment] 2022-02-17 17:24
Pushing to April milestone

**Comment by aasimkhan30** [comment] 2022-04-11 19:05
Pushing to June milestone

**Comment by cssuh** [comment] 2022-04-11 19:11
closing because it is a duplicate of https://github.com/microsoft/azuredatastudio/issues/17179

**Closed by cssuh** 2022-04-11 19:11 UTC
Labels: Bug, Area - Language Service, Triage: Done, Triage: Postponed
