### ISSUE TITLE
Unsaved tabs restore as empty

### ISSUE THREAD

**Issue by Ravatsaas** [microsoft/azuredatastudio#3304] opened 2018-11-26 13:24 UTC
- Azure Data Studio Version: 1.2.4

Steps to Reproduce:

1. Do important work
2. Go home for the weekend
3. Come back Monday to find IT rebooted your computer just because
4. Azure Data Studio restores all of your unsaved tabs, but they are all empty

**Comment by Ravatsaas** [comment] 2018-11-26 19:17
An additional observation: When I closed the tabs and clicked Ctrl+N to get new tabs, the new tabs were populated with the missing content from the old tabs with the same names. 

For example, the new SQLQuery_1 was populated with the lost content from the old, unsaved SqlQuery_1, and so on.

Closing SQLQuery_1 and reopening it again yields an empty tab.

This might help troubleshoot and could be a good workaround for anyone dealing with the same issue.

**Comment by kburtram** [comment] 2018-11-26 22:00
@Ravatsaas I haven't been able to reproduce this issue doing something like the below steps (unfortunately I can follow the provided repro literally myself 😄).  It sounds like something went wrong in the auto-save recovery logic from symptoms.

1. Open Azure Data Studio
2. Open some query editors and type some content
3. Close ADS without saving files
4. Reopen ADS

Result: Files are restore with unsaved content.

Please let me know if you're able to narrow down the repro to a more self-contained set of steps.  Thanks!

**Comment by Ravatsaas** [comment] 2018-11-27 13:36
@kburtram, unfortunately, it doesn't reproduce consistently on my computer either. 

Since the content was restored later, after closing the empty tabs and creating new ones with the same name, I can speculate that the restore functionality is written in such a way that when you open a new tab by whatever means, it checks for a restoreable tab by that name. So my thought is, because I started ADS right as I was rebooting my computer and a lot was going on at the same time, the sequence of events could have been thrown off so that the restored file content provider was not yet properly initialized when the tabs were recreated.

If I wanted to poke around in the source code to look for an explanation, would you happen to know off the top of your head what would be a good place to start looking?

**Comment by Tarig0** [comment] 2018-12-26 14:14
Can confirm this issue in 1.3.7-insider. Not able to consistently get this behavior but does seem to do with a restart while the application is running.

**Comment by yualan** [comment] 2019-03-06 00:21
Repro: Process Explorer -> Kill Process Tree

**Comment by granttrevor** [comment] 2019-03-19 00:24
Am experiencing this issue - and yes seems to be related to shutting down the PC without closing ADS first.

On startup of ADS any open tabs now display as disconnected/empty.
Interestingly if you close all of these tabs and then start openning new ones with 'Ctrl'+'N' the newly opened tabs contain the content that was present prior to shutdown.

**Comment by Charles-Gagnon** [comment] 2019-07-02 18:00
I'm not able to repro this at all in 1.8 or insiders so I'm going to close this - we've made some changes to how query editor state is handled so that or a VSCode merge might have fixed the issue. If anyone is still experiencing the issue in 1.8+ let me know and we can reopen this to investigate further.

**Closed by Charles-Gagnon** 2019-07-02 18:00 UTC
Labels: Area: Query Editor, Bug
