### ISSUE TITLE
Saving a query with a new file name causes results to disappear

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1876] opened 2018-07-09 19:58 UTC
- SQL Operations Studio Version: fbd5e81

Steps to Reproduce:
1. Open an untitled query editor and write a new query (or run a script operation to get a new query editor with a query)
2. Run the query and get results
3. Save the editor. If the editor wasn't already untitled, use "save as" with a new filename 

Actual behavior: The open query results disappear
Expected behavior: The query results stay open

**Comment by alanrenmsft** [comment] 2019-08-05 18:47
please reconsider the milestone for this issue.

**Comment by KyleStay** [comment] 2019-09-25 21:19
@Charles-Gagnon this is show stopping. I have rolled back to the [August release](https://github.com/microsoft/azuredatastudio/releases/tag/1.10.0) which doesn't have this issue and set updating to manual because I cannot work without IntelliSense.

**Comment by KyleStay** [comment] 2019-09-25 21:31
Also, I think it's a stretch to call this a duplicate. This issue doesn't begin to describe the full severity of the issue referenced in the now closed #7366 and #6585 issues.

With whatever changes were made in the September release, when a file is saved as a .sql or a .sql file is opened, the following issues occur.
* IntelliSense is broken for all MSSQL database engine changes and custom database objects
* The user's potentially non-reproducible results are wiped out → completely unacceptable for a database product.
* The user must redo their connection string again.

**Comment by KyleStay** [comment] 2019-09-25 21:39
And it looks like #7366 was reopened for the time being...

**Comment by Charles-Gagnon** [comment] 2019-09-25 22:42
It sounds like part of the problem you're having is Intellisense being broken for saved files. This is currently fixed in the insiders builds (original issue for that: https://github.com/microsoft/azuredatastudio/issues/7161)

The rest of the issues around editors being disconnected after being saved are separate but that's not a recent regression and is something we're tracking for a fix at some point. When you reconnect after saving things should continue to function as normal otherwise.

**Comment by heneds** [comment] 2020-01-16 09:06
As stated above: when saving a new file the connection is lost. See also #4717. Regardless of Intellisense or any other  underlying reason this is too severe a bug to have for this long. It encourages the user not to save. Or use another tool...

**Comment by kburtram** [comment] 2021-09-03 18:14
This should be fixed with PR https://github.com/microsoft/azuredatastudio/pull/16883.

**Closed by kburtram** 2021-09-03 18:14 UTC
Labels: Bug, Area - Query Editor, Triage: Done, Triage: Postponed
