### ISSUE TITLE
Cannot toggle code styling off in a text cell by pressing toolbar button again.

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#18114] opened 2022-01-18 23:07 UTC
Steps to Reproduce:
1. Open a new notebook and add a text cell.
2. Add some text and then convert the text to a Code block with the toolbar button.
3. When pressing the toolbar button again over the same text, the Code block styling doesn't get removed.

**Comment by chlafreniere** [comment] 2022-01-20 06:11
Closing as dupe of #13639

**Closed by chlafreniere** 2022-01-20 06:11 UTC
Labels: Bug, Area - Notebooks, Triage: Needed
