### ISSUE TITLE
Failed to change kernel 

### ISSUE THREAD

**Issue by Vinayak1812** [microsoft/azuredatastudio#23954] opened 2023-07-21 09:13 UTC
Type: <b>Bug</b>

Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. Std Err Output: Traceback (most recent call last): File "c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\resources\python Scripts\startNotebook.py", line 1, in <module> import notebook.notebookapp ModuleNotFoundError: No module named 'notebook.notebookapp'

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.22623
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|1.0.0
azuredatastudio-postgresql|Mic|0.4.2
dacpac|Mic|1.13.0
datavirtualization|Mic|1.13.2
import|Mic|1.5.5
machine-learning|Mic|0.12.0
powershell|ms-|2023.6.0
profiler|Mic|0.12.2
schema-compare|Mic|1.19.0
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|1.1.1

</details>

**Comment by jrmclennan** [comment] 2023-07-26 22:51
I have the same issue. Exact same error.

**Comment by olliescase** [comment] 2023-07-27 07:52
Same issue on:
MacBook Pro M2 13" 2022 (MacOS 13.4.1 (c))

Ran setup for python using /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11

I have additionally tried installing manually this notebook package via pip to no success. Here is the log, sanitised:

```
... Ensuring /Users/{name}/Library/Jupyter/instances/{uuid} exists
... Ensuring /Users/{name}/Library/Jupyter/instances/{uuid}/config exists
... Ensuring /Users/{name}/Library/Jupyter/instances/{uuid}/data exists
... Ensuring /Users/{name}/Library/Jupyter/instances/{uuid}/config/custom exists
... Ensuring /Users/{name}/Library/Jupyter/kernels exists
... Starting Notebook server
    > "/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/bin/python3" "/Applications/Azure Data Studio.app/Contents/Resources/app/extensions/notebook/resources/pythonScripts/startNotebook.py" --no-browser --ip=127.0.0.1  --no-mathjax --notebook-dir "/Users/{name}" --NotebookApp.token={token}
```

And this produces the following error:

```
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last): File "/Applications/Azure Data Studio.app/Contents/Resources/app/extensions/notebook/resources/pythonScripts/startNotebook.py", line 1, in <module> import notebook.notebookapp ModuleNotFoundError: No module named 'notebook.notebookapp'
```

**Comment by gitadeb** [comment] 2023-07-27 13:37
I have exactly the same issue & error - running ADS on Win10.

**Comment by Vinayak1812** [comment] 2023-07-29 09:50
Actually I solved that problem 

The best way is to delete all python version from your computer after that verify by typing in cmd

code: python --version

go to advance environment setting and delete the path of python after that uninstall your azure data studio and download the latest version of azure data studio

after download anaconda environment and by that you can use jupyter in your any IDE like vs code and after change the kernel in azure data studio you can get the python3

**Comment by olliescase** [comment] 2023-08-02 09:00
Really think this should be closed as its a duplicate of #23945 (and diagnostics/workarounds are being made in both)

> The best way is to delete all python version from your computer after that verify by typing in cmd

Without uninstalling/removing python at all, if notebook is installed via pip, you can just do:

```sh
pip3 install notebook==6.5.5
```

**Comment by Vinayak1812** [comment] 2023-08-03 06:24
thanks for giving me this  another way @olliescase  I will definitely try this .

**Comment by AmmarSahyoun** [comment] 2023-08-06 20:30
Solved! By downgrading the version of notebook from 7.0.1 to 6.5.5  Many thanks @olliescase.

**Comment by lucyzhang929** [comment] 2023-09-08 19:06
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/23945.

**Closed by lucyzhang929** 2023-09-08 19:06 UTC
Labels: Bug, Area - Notebooks, Triage: Needed
