### ISSUE TITLE
Error, Requires "PolyBase to be enabled..." even If already enabled

### ISSUE THREAD

**Issue by SQLBigEyesDad** [microsoft/azuredatastudio#8742] opened 2019-12-19 11:27 UTC
Issue Type: <b>Bug</b>

No problem When I implement Data Virtualization by TSQL with SSMS
But When I run "Create External Table" menu, It shows error message, requires "PolyBase to be enabled..."

Windows 10
Azure Data Studio 1.13.1
Data Virtualization 1.1.0

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (12.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment] 2020-03-24 19:59
@SQLBigEyesDad Apologies for not getting back to you on this - are you still seeing this issue? If so could you run these queries on the server you're trying to create the External Tables on and let me know what the results are?

```
SELECT SERVERPROPERTY('IsPolybaseInstalled');
SELECT value_in_use FROM sys.configurations WHERE name='polybase enabled';
```

I'm going to close this out now since it's been open for a long time without any updates, but if you're still having this issue I'll reopen it and we can investigate further.

**Comment by minma898** [comment] 2021-04-02 23:22
I have exact same issue with latest version of Azure Data Studio. PolyBase is installed and enabled on the target server and I verified result returns 1 for those two queries
SELECT SERVERPROPERTY('IsPolybaseInstalled');
SELECT value_in_use FROM sys.configurations WHERE name='polybase enabled';

I can run CREATE EXTERNAL TABLE successfully on the target server using SQL Server Management Studio. However when I try to run Data Visualization on target database using Azure Data Studio, I am getting error "This operation requires PolyBase to be enabled in the target server. "

Here is version information for Azure Data Studio
Version: 1.27.0 (system setup)
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:24:59.168Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Please help to resolve this issue!!!

I have attached screenshots for your reference
![ErrorDV](https://user-images.githubusercontent.com/81834992/113460912-344e6b80-93cf-11eb-8adc-8b0099711015.PNG)
![PolyBaseChecker](https://user-images.githubusercontent.com/81834992/113460914-34e70200-93cf-11eb-8d95-3e4fec6ebc4b.PNG)

**Comment by Charles-Gagnon** [comment] 2021-04-05 16:35
@minma898 

Can you try running this query? And make sure you're running this as the same login you're trying to use the virtualize data wizard for and is against the `master` DB.

```
SELECT DB_NAME()
SELECT COUNT(*) FROM sys.dm_exec_compute_nodes
SELECT SERVERPROPERTY('IsPolybaseInstalled')
SELECT value_in_use FROM sys.configurations WHERE name='polybase enabled'
```

**Comment by minma898** [comment] 2021-04-05 16:59
Ok, The query result is attached, I used the same login that I try to use virtualize data wizard
![Query](https://user-images.githubusercontent.com/81834992/113600994-a56f6800-95f5-11eb-8eab-15b5338f3337.PNG)

**Comment by Charles-Gagnon** [comment] 2021-04-05 17:03
And this happens 100% of the time for you? (or at least consistently enough to be a problem)

**Comment by minma898** [comment] 2021-04-05 17:09
Yes, It happens 100%. I have never been able to run virtualize data (v1.12.0)

**Comment by minma898** [comment] 2021-04-05 19:26
Hi, Attached are log files requested (no private data in the files). Thanks for the help.

**Comment by Charles-Gagnon** [comment] 2021-04-05 19:41
@minma898 It looks like the attachments weren't included - could you try uploading them again? You can also e-mail them to me directly if you wish and I'll take a look.

**Comment by minma898** [comment] 2021-04-05 20:00
Log files are attached

[Console.log](https://github.com/microsoft/azuredatastudio/files/6260355/Console.log)
[20210405T114231.zip](https://github.com/microsoft/azuredatastudio/files/6260361/20210405T114231.zip)

**Comment by Charles-Gagnon** [comment] 2021-04-05 20:09
It looks like you might not have the logging setting enabled, could you see if you have the following setting checked? If you don't then : 

1. Check the setting
2. Restart ADS
3. Follow the steps above to generate the logs again

![image](https://user-images.githubusercontent.com/28519865/113620978-e8d6d000-960f-11eb-990e-8d373103ab38.png)

**Comment by minma898** [comment] 2021-04-05 20:46
Enabled logging setting and generated logs again

[Console.log](https://github.com/microsoft/azuredatastudio/files/6260511/Console.log)
[20210402T151835.zip](https://github.com/microsoft/azuredatastudio/files/6260526/20210402T151835.zip)

**Comment by Charles-Gagnon** [comment] 2021-04-05 22:06
Unfortunately it looks like something happened and the logs I'm expecting aren't there. Could you try the following to help try and figure out what's going on?

1. Close all instances of ADS 
2. Start ADS
3. Verify setting from above is still checked
4. Open up Data Virtualization dialog
5. Run the `Developer: Open Extension Logs Folder` command (note this is slightly different than the one above)

Do you see a folder named `Microsoft.datavirtualization` there? And if so does it contain anything?

6. Run this command in a powershell window `Get-WmiObject Win32_Process -Filter "name = 'MicrosoftSqlToolsScaleOutData.exe'" | Select-Object CommandLine | Out-String -Width 10000`

Paste the output from that command here (you can strip out any PII in the path names, I just want to see that the parameters are being set correctly)
7. Keeping the log folder open, close ADS

Check the log folder again for a subfolder named `Microsoft.datavirtualization`

**Comment by minma898** [comment] 2021-04-06 00:22
After run Developer: Open Extension Logs Folder, I see folder named Micrisoft.datavirtualization there and it contains a log file which is not empty

Here is result from command in powershell window

CommandLine
-----------
c:\Users\xxxxx\.azuredatastudio\extensions\microsoft.datavirtualization-1.12.0\scaleoutdataservice\Windows\1.10.0\MicrosoftSqlToolsScaleOutData.exe --log-dir c:\Users\xxxxx\AppData\Roaming\azuredatastudio\logs\20210405T163609\exthost1\Microsoft.datavirtualization --enable-logging

After close ADS, the log file is still there under Microsoft.datavirtualization folder. The log file is attached

[MicrosoftSqlToolsScaleOutData_20210405163612264.log](https://github.com/microsoft/azuredatastudio/files/6261203/MicrosoftSqlToolsScaleOutData_20210405163612264.log)

**Comment by Charles-Gagnon** [comment] 2021-04-06 20:24
Thanks. although I'm not seeing why this is failing still. So if you have time to try these two things that would be great :

1. Run this query using the same login against the master DB : 

```
SELECT SERVERPROPERTY('ProductMajorVersion') as server_major_version, SERVERPROPERTY('ProductMinorVersion') AS server_minor_version, SERVERPROPERTY('ProductBuild') AS server_build_version; 

DECLARE @Cond1 INT = CONVERT(INT, (SELECT SERVERPROPERTY('IsPolybaseInstalled'))); 
DECLARE @Cond2 INT = CONVERT(INT, (SELECT value_in_use FROM sys.configurations WHERE name='polybase enabled')); 
DECLARE @Cond3 INT = 2; 
BEGIN TRY 
SET @Cond3 = CONVERT(INT, (SELECT COUNT(*) FROM sys.dm_exec_compute_nodes)); 
END TRY 
BEGIN CATCH 
END CATCH; 
IF @Cond1 = 1 AND @Cond2 = 1 AND @Cond3 >= 2 
SELECT 1 AS is_polybase_enabled; 
ELSE 
SELECT 0 AS is_polybase_enabled; 

DECLARE @dbListWithMk AS TABLE (name NVARCHAR(4000), hasMasterKey BIT); 
DECLARE @tempDbName NVARCHAR(4000); 
DECLARE @SQL NVARCHAR(4000); 
DECLARE DbListCursor CURSOR FOR SELECT name FROM [sys].[sysdatabases]; 
OPEN DbListCursor; 
FETCH NEXT FROM DbListCursor INTO @tempDbName; 
WHILE @@FETCH_STATUS = 0 
BEGIN 
SET @SQL = N'SELECT N''' + REPLACE(@tempDbName,'''','''''') + ''', (CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END) FROM ' + QUOTENAME(@tempDbName) + '.[sys].[symmetric_keys] WHERE name = ''##MS_DatabaseMasterKey##'''; 
BEGIN TRY 
INSERT INTO @dbListWithMk EXEC(@SQL); 
END TRY 
BEGIN CATCH 
INSERT INTO @dbListWithMk VALUES (@tempDbName, 0); 
END CATCH; 
FETCH NEXT FROM DbListCursor INTO @tempDbName; 
END; 
CLOSE DbListCursor; 
DEALLOCATE DbListCursor; 
SELECT * FROM @dbListWithMk; 
SELECT SERVERPROPERTY('ProductLevel') as product_level;
```

2. 
- Download this zip [Microsoft.SqlTools.ScaleOutData.Services.dll.zip](https://github.com/microsoft/azuredatastudio/files/6267330/Microsoft.SqlTools.ScaleOutData.Services.dll.zip)
- Extract the DLL
- Shut down all running instances of ADS
- Find the extension and copy the DLL there - replacing the version that's there currently (It should be in `%USERPROFILE%\.azuredatastudio\extensions\microsoft.datavirtualization-1.12.0\scaleoutdataservice\Windows\1.10.0)
- Start ADS and launch the wizard
- Get the Data Virtualization logs as above


I added some additional logging to this to try and figure out where this might be failing. The additional logs will look something like this : 

```
4/6/2021 11:01:27 AM [VERBOSE] - Method "GetServerInfo" at line 49 of Microsoft.SqlTools.ScaleOutData.Services\SqlOperation\SqlServer\SqlServerInformationLookUp.cs

    ServerInfo Connection String = <CONNECTION STRING HERE>

4/6/2021 11:01:27 AM [VERBOSE] - Method "GetServerInfo" at line 53 of Microsoft.SqlTools.ScaleOutData.Services\SqlOperation\SqlServer\SqlServerInformationLookUp.cs

    Get ServerInfo was successful

4/6/2021 11:01:27 AM [VERBOSE] - Method "GetServerInfo" at line 59 of Microsoft.SqlTools.ScaleOutData.Services\SqlOperation\SqlServer\SqlServerInformationLookUp.cs

    Polybase Val = 1
  ```
  
  For the first one with the connection string you can either strip out any personal information you want or just delete it entirely but first if you could look at that and see whether the connection string seems correct to you.
  
  Then the second 2 messages are what I'm interested in currently to verify what the query is returning is what I'm expecting.

**Comment by minma898** [comment] 2021-04-07 16:57
1) Run the query with same login against the target DB, attached the query result.
2) Here are what I see in the log file. I see value is 0 for Polybase enabled, but the query returns 1.
![2021-04-07 09_31_03-● SQLQuery_1 - SPCPDWHOUSE01 master (Integrated) - Azure Data Studio](https://user-images.githubusercontent.com/81834992/113905011-8c96bc00-9787-11eb-8323-6d6d3fd7293f.png)

4/7/2021 9:41:23 AM [VERBOSE] - Method "GetServerInfo" at line 49 of C:\src\SqlOpsStudioExtensions\services\src\Microsoft.SqlTools.ScaleOutData.Services\SqlOperation\SqlServer\SqlServerInformationLookUp.cs

    ServerInfo Connection String = Data Source=xxxxxx;Initial Catalog=xxxx;Integrated Security=True;Persist Security Info=True;User ID=;Password=;Pooling=True;Multiple Active Result Sets=True

4/7/2021 9:41:23 AM [VERBOSE] - Method "GetServerInfo" at line 53 of C:\src\SqlOpsStudioExtensions\services\src\Microsoft.SqlTools.ScaleOutData.Services\SqlOperation\SqlServer\SqlServerInformationLookUp.cs

    Get ServerInfo was successful

4/7/2021 9:41:23 AM [VERBOSE] - Method "GetServerInfo" at line 59 of C:\src\SqlOpsStudioExtensions\services\src\Microsoft.SqlTools.ScaleOutData.Services\SqlOperation\SqlServer\SqlServerInformationLookUp.cs

    Polybase Val = 0

**Comment by Charles-Gagnon** [comment] 2021-04-07 17:26
And in the connection string from the logs is the database set to master? And the data source looks correct - no weirdness going on there?

**Comment by Charles-Gagnon** [comment] 2021-04-07 17:30
Actually - looks like the connection string will still list the original database (we set a different property on the SqlConnection). But it might be relevant if that database is different than master so I'd still like to know if this is for another database.

Are you able to connect directly to master? If so could you try making another connection for that and seeing if the wizard works there?

**Comment by minma898** [comment] 2021-04-07 23:16
Yes, I am able to connect directly to master without any issue, same as connecting to my working database, Regardless which databases connected, the wizard stops working with the same error

**Comment by Charles-Gagnon** [comment] 2021-04-08 18:11
Here's another version of the DLL with some additional logging - if you get a chance could you follow the same steps above to install it and then get the logs?


[Microsoft.SqlTools.ScaleOutData.Services.zip](https://github.com/microsoft/azuredatastudio/files/6280626/Microsoft.SqlTools.ScaleOutData.Services.zip)

**Comment by Charles-Gagnon** [comment] 2021-04-12 19:55
@minma898 Were you able to get a chance to try that out?

**Comment by minma898** [comment] 2021-04-12 23:56
I just tried and noticed the issue is fixed by itself!!! I am able to run Virtualize Data wizard using exact same connection, target database that I used before. Now the error is gone!

**Comment by minma898** [comment] 2021-04-13 00:18
Just let you know that Cumulative Update 10 for SQL Server 2019 KB5001090 was applied on the server two days ago. Not sure if the update installation fixes the Virtualize Data wizard in ADS

**Comment by Charles-Gagnon** [comment] 2021-04-13 16:18
Interesting, there may have been something there that wasn't working correctly. Shame we couldn't figure out what the issue was - if it happens again let me know! I'll close this issue for the time being though.

**Closed by Charles-Gagnon** 2021-04-13 16:18 UTC
Labels: Area - External Table, Bug, Needs Logs, Triage: Needed

**Comment by minma898** [comment] 2021-04-13 19:56
Ok, sounds good. Thank you for the helps with troubleshooting.
