### ISSUE TITLE
SQL Agent History - Job Step Duration

### ISSUE THREAD

**Issue by mrlife** [microsoft/azuredatastudio#10240] opened 2020-05-01 14:56 UTC
Please add the duration a step ran.

**Comment by kburtram** [comment] 2020-05-07 19:58
@mrlife thanks for the suggestion!  This looks like mostly a duplicate of https://github.com/microsoft/azuredatastudio/issues/7005.  Please add any additional comments to that issue so we can track the request.

**Closed by kburtram** 2020-05-07 19:58 UTC
Labels: Area - SQL Agent, Enhancement, Triage: Needed

**Comment by mrlife** [comment] 2020-05-08 00:45
Hi @kburtram This one is for duration of each step, which may be different than what is tracked by the other ticket... looks like it’s for the duration of an entire job.

**Comment by abist** [comment] 2020-05-08 16:12
@mrlife I'll change the title to reflect that the duration is needed for step and job both.

**Comment by mrlife** [comment] 2021-04-01 13:40
> @mrlife I'll change the title to reflect that the duration is needed for step and job both.

@abist Please make this update. Thanks.
