### ISSUE TITLE
the content of the hover over tooltip is truncated

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#18378] opened 2022-02-15 18:35 UTC
if there are not enough vertical space, the content of the hover over tooltip is truncated. ideally, it should scroll.
![image](https://user-images.githubusercontent.com/13777222/154126654-e4aeef2c-76d0-46b6-a8e7-ed3c1b275705.png)

**Comment by aasimkhan30** [comment] 2022-11-03 00:19
duplicate of #20796

**Closed by aasimkhan30** 2022-11-03 00:19 UTC
Labels: Bug, Triage: Done, Area - Execution Plan
