### ISSUE TITLE
Save As Excel, now saves numbers as text

### ISSUE THREAD

**Issue by davegedny** [microsoft/azuredatastudio#18703] opened 2022-03-11 10:32 UTC
Issue Type: <b>Bug</b>

Hi,
This has only recently just started happening so assuming a new issue with v1.35 that came out 2 weeks ago.

Use the 'Save as Excel' feature to export data. Open in Excel. All the numbers are stored as text and you have to highlight the cells and convert to number before using. THis didn't used to happen.

Hope this helps. Kind regards, Dave

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:24:29.469Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2022-03-11 16:59
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/18615

**Closed by Charles-Gagnon** 2022-03-11 16:59 UTC
