### ISSUE TITLE
Add / Edit Table or Sp from GUI

### ISSUE THREAD

**Issue by dvanurag1308** [microsoft/azuredatastudio#89] opened 2017-11-16 17:38 UTC
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
Right Click on Tables.

Add new menu item to add/edit table and store procedures from GUI.

**Comment by kburtram** [comment] 2019-06-06 20:25
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/282 since that issue has a bit more context.  Please add any related comments in that issue.  Thanks!

**Closed by kburtram** 2019-06-06 20:25 UTC
Labels: Enhancement
