### ISSUE TITLE
Connection disconnects - random time-out / connection failures

### ISSUE THREAD

**Issue by albegouws** [microsoft/azuredatastudio#21321] opened 2022-11-29 12:59 UTC
- Azure Data Studio Version: 1.40.1
- OS Version: Windows 11 21H2

Steps to Reproduce:

1. Connect to any database and run a query
2. Switch between tabls

Does this issue occur when all extensions are disabled?: Yes

I have an issue that seems to be related to token refreshes.  I am seeing connecting to both Azure or on site SQL servers.  A query may run and then end with an error such as "Query failed: Invalid operation. The connection is closed."

Opening Developer mode and watching the console, this message keeps showing until the error happens :  INFO Found pending reconnect promise for uri untitled:SQLQuery_7, waiting. workbench.dekstop.main.js:877

Switching open tabs for one second then going back to the same window reports 
INFO Access token expired for connection 67cef55a-4f0b-4965-91e5-7f4635f1abd6 with uri untitled:SQLQuery_7
Successfully refreshed token for connection 67cef55a-4f0b-4965-91e5-7f4635f1abd6 with uri untitled:SQLQuery_7, result: true [object Object], isConnected: true, [object Object]

then immediately reports this again 
 INFO Access token expired for connection 67cef55a-4f0b-4965-91e5-7f4635f1abd6 with uri untitled:SQLQuery_7

The same does not happen when running 1.41.0-insiders

**Comment by cheenamalhotra** [comment] 2022-12-13 02:58
Duplicate of #21320

**Closed by cheenamalhotra** 2022-12-13 02:58 UTC
Labels: Bug, Area - Connection, Triage: Done
