### ISSUE TITLE
Notebook Find dialog position can sometimes obscure the keyword on a text cell

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#14017] opened 2021-01-21 22:49 UTC
- Azure Data Studio Version:
Version: 1.26.0-insider (user setup)
Commit: 94b697340dd23eb8f59708275a460a769f80fc30
Date: 2021-01-18T06:34:21.629Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a notebook. 
> do Ctrl + O and paste this path: `https://raw.githubusercontent.com/MsSQLGirl/jubilant-data-wizards/main/Simple%20Demo/Sample%20Notebooks%20-%20Data%20Analysis/ADSNotebooksDemo.ipynb`

Resize your window to something like this:
![image](https://user-images.githubusercontent.com/6405919/105421907-b6fcc280-5bf7-11eb-9006-c06b02581716.png)

2. Do search on "Studio" with Ctrl + F. 
You'll see that "Azure Data Studio" is obscured. 
![image](https://user-images.githubusercontent.com/6405919/105421697-5ff6ed80-5bf7-11eb-988c-788eacfd7f51.png)

**Comment by MsSQLGirl** [comment] 2021-01-21 22:50
@MaddyDev : FYI this is the one we discussed earlier.

**Comment by radentonev** [comment] 2021-01-22 19:15
Seems to be very similar behavior in VSCode. I am not really convinced that I want to change the behavior, as there are implications.

Potential solutions:
- Move box to be over the toolbar. Downside is that we then hide the toolbar. No idea how many people want to use the toolbar when search is on.
- Make the box background semi-transparent or something 
- Decrease the size of the box to minimum in order to mitigate issue

**Comment by chlafreniere** [comment] 2021-02-01 20:27
There's a scenario where we really can't do anything about here; at the very top of the document, if there is text behind the search box, there is nowhere to scroll to.

**Comment by MsSQLGirl** [comment] 2021-02-27 03:47
We might be able to lower the priority on this and look into it as part of the longer term / run Search design. (Understood that this is a Find, but the spirit of ability to find things applies)

**Comment by MsSQLGirl** [comment] 2021-03-01 16:49
Bumping down to P2 after consulting with the team.

**Comment by JustinMDotNet** [comment] 2021-08-12 23:23
This is no longer reproduceable. Closing issue.

**Closed by JustinMDotNet** 2021-08-12 23:23 UTC
Labels: Bug, Area - Notebooks, Pri: 3, Impact: Live site
