### ISSUE TITLE
Query Plan loses details

### ISSUE THREAD

**Issue by peterox** [microsoft/azuredatastudio#16173] opened 2021-07-15 11:34 UTC
Issue Type: <b>Bug</b>

If I run a query plan it displays correctly, but if I switch to a different tab and then back to the plan all the arrows disappear.

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment] 2021-07-15 17:06
@peterox could please add some screenshots?

**Comment by peterox** [comment] 2021-07-15 22:25
![Screenshot 2021-07-16 082522](https://user-images.githubusercontent.com/804375/125865593-53ee51e7-9865-40c6-a26a-07c74ba7b579.png)
![Screenshot 2021-07-16 082501](https://user-images.githubusercontent.com/804375/125865596-7d325fe8-57e3-42b0-90ac-349bce2986b0.png)

**Comment by alanrenmsft** [comment] 2021-07-16 00:03
I am able to reproduce this with 1.30 release, but don't see such issue with the latest insider release and the 1.31 release candidate. Assuming it has been fixed, I will verify this on the 1.31 final build when it is available.

**Comment by alanrenmsft** [comment] 2021-07-21 17:54
I can repro the issue in 1.31 stable build, will take a look.

**Comment by kburtram** [comment] 2021-08-19 00:48
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/4755.  Thanks for reporting this issue!

**Closed by kburtram** 2021-08-19 00:48 UTC
Labels: Bug, Area - Query Plan, Triage: Done
