### ISSUE TITLE
Cannot copy

### ISSUE THREAD

**Issue by bhartman353** [microsoft/azuredatastudio#15334] opened 2021-05-05 14:16 UTC
Issue Type: <b>Bug</b>

run "sp_help 'randomtable'" to get a table definition.

Try and copy various "Column_name" values from the 2nd table.
Sometimes it will update the clipboard, but most times it won't.
Copying values from the first table works.

It looks like it's related to leaving the query window open for more than 1 day.
Opening a new query (in the same session) does not have exhibit the same issue; but the old query tab still cannot copy values from the 2nd table.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0

</details>

**Comment by kburtram** [comment] 2021-08-23 18:38
Closing as a duplicate of #10123. We'll investigate the various related copy from results grid issues when investigating that bug. Thanks!

**Closed by kburtram** 2021-08-23 18:38 UTC
Labels: Bug, Area - Query Editor, Triage: Done
