### ISSUE TITLE
Export data from results in notebook

### ISSUE THREAD

**Issue by ejosowitz** [microsoft/azuredatastudio#5803] opened 2019-05-31 21:15 UTC
Issue Type: <b>Feature Request</b>

Perhaps I'm just not seeing it, but it doesn't seem like I can export the results from a code query run in a notebook in Azure Data Studio. This means I need to interactively debug my query in notebook, then copy and paste it into a new query document, then export the results from there. 

I'd like to be able to export results cleanly within the notebook without requiring the additional steps. Would be just as useful for other kernels -- if I display a data frame from Python/Pandas it would also be great to export to Excel directly from there.

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17134

**Comment by chlafreniere** [comment] 2019-06-19 18:28
Dupe of #4633

**Closed by chlafreniere** 2019-06-19 18:28 UTC
Labels: Area: Notebooks, Enhancement
