### ISSUE TITLE
Node labels can extend into the region of other nodes

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#18389] opened 2022-02-15 19:19 UTC
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run an execution plan that generates a node with a longer label.  I'm using `[wideworldimporters].[Warehouse].[StockItemStockGroups]`

Expected: Labels should be constrained to below the node.

Actual: Label extend into regions of other nodes.  Compare with SSMS for example.

ADS

![image](https://user-images.githubusercontent.com/599935/154133182-487b3579-9c11-4539-99f8-a896971a3bac.png)

SSMS

![image](https://user-images.githubusercontent.com/599935/154133162-4b2832b5-01f5-4929-b389-a737a1591218.png)
 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment] 2022-02-15 20:52
This can actually be pretty annoying if several such nodes are side-by-side.  For example, the WWI Suppliers view.

![image](https://user-images.githubusercontent.com/599935/154147143-9d848d7e-21c9-48b0-ae49-5251df765a81.png)

**Comment by lewis-sanchez** [comment] 2022-02-17 21:23
The fix for this issue was made in the azdataGraph repo, and the PR for that is here:
https://github.com/microsoft/azdataGraph/pull/44

**Comment by lewis-sanchez** [comment] 2022-02-18 06:31
Closing this issue because the fix for this issue was merged into release 1.35 here: https://github.com/microsoft/azuredatastudio/pull/18463

The fix for this issue has also been confirmed in Azure Data Studio RC. As seen in the image the bottom 2 vertices have their labels truncated:
![image](https://user-images.githubusercontent.com/87730006/154629732-aac2414f-b5ea-4964-be8d-184931fa536c.png)

**Closed by lewis-sanchez** 2022-02-18 06:31 UTC
Labels: Bug, Approved, Area - Execution Plan
