### ISSUE TITLE
Brackets are added to SQL function names upon auto-complete

### ISSUE THREAD

**Issue by jconrey** [microsoft/azuredatastudio#8427] opened 2019-11-21 21:18 UTC
Issue Type: <b>Bug</b>

if I type "select count_bi", autocomplete will prompt me to select count_big, and when I do it prints completes count_big, but it also surrounds it with brackets, which renders the command useless until I manually remove the brackets, which in turn renders the autocomplete useless. I've not found a way to customize this setting, but could we just remove the brackets from the autocomplete for SQL functions?

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2019-11-22 17:10
Thanks for the report @jconrey - I'm going to close this as a duplicate of #7570 so follow that for any updates! I haven't been able to dig into what's causing this but I am able to repro it myself so I should be able to figure something out. I'll let you know if I need any more information!

**Closed by Charles-Gagnon** 2019-11-22 17:10 UTC
Labels: Area - Language Service, Bug, Triage: Done

**Comment by jconrey** [comment] 2019-11-22 17:26
Awesome! Thanks, Charles. Have a great weekend.
