### ISSUE TITLE
Unexpected error while connecting

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7897] opened 2019-10-22 18:29 UTC
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/3757758/renderer1.log)
Issue Type: <b>Bug</b>

See attached file.

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (65fb77ef5ce93fa1090033fe31606138b8059bbc, 2019-10-22T10:25:42.157Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7-8890 v2 @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|24.00GB (19.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.16.0

</details>

```
[2019-10-22 11:26:15.274] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:bdc-sqlmaster,31533|user:|group:C777F06B-202E-4480-B475-FA416154D458
[2019-10-22 11:26:15.275] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:bdc-sqlmaster,31533|user:|group:C777F06B-202E-4480-B475-FA416154D458
[2019-10-22 11:26:15.277] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:bdc-sqlmaster,31533|user:|group:C777F06B-202E-4480-B475-FA416154D458
[2019-10-22 11:26:18.826] [renderer1] [info] Creating new connection untitled:SQLQuery_1
[2019-10-22 11:26:18.826] [renderer1] [info] Adding connection untitled:SQLQuery_1
[2019-10-22 11:26:18.827] [renderer1] [info] Successfully added connection untitled:SQLQuery_1
[2019-10-22 11:26:25.472] [renderer1] [error] OnConnectionComplete but no connection found 'file:///null' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:bdc-sqlmaster,31533|user:|group:C777F06B-202E-4480-B475-FA416154D458,untitled:SQLQuery_1]
[2019-10-22 11:26:25.617] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at ConnectionStatusManager.onConnectionComplete (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:170954:23)
    at ConnectionManagementService.onConnectionComplete (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:225488:60)
    at MainThreadDataProtocol.$onConnectionComplete (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:236864:47)
    at RPCProtocol._doInvokeHandler (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:241762:27)
    at RPCProtocol._invokeHandler (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:241747:45)
    at RPCProtocol._receiveRequest (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:241674:32)
    at RPCProtocol._receiveOneMessage (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:241602:26)
    at file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:241492:52
    at Emitter.fire (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:10651:38)
    at BufferedEmitter.fire (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:34000:35)
    at PersistentProtocol._receiveMessage (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:34219:37)
    at file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:34093:83
    at Emitter.fire (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:10651:38)
    at ProtocolReader.acceptChunk (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:33826:37)
    at file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:33795:61
    at Socket.listener (file:///C:/azuredatastudio-insiders/azuredatastudio-windows/resources/app/out/vs/workbench/workbench.desktop.main.js:34456:40)
    at ZoneDelegate.invokeTask (c:\azuredatastudio-insiders\azuredatastudio-windows\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\azuredatastudio-insiders\azuredatastudio-windows\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (c:\azuredatastudio-insiders\azuredatastudio-windows\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (c:\azuredatastudio-insiders\azuredatastudio-windows\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[2019-10-22 11:26:25.848] [renderer1] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:master|server:bdc-sqlmaster,31533|user:|group:C777F06B-202E-4480-B475-FA416154D458

```

**Comment by MaddyDev** [comment] 2019-10-22 18:31
This is intentional : https://github.com/microsoft/azuredatastudio/pull/7857

**Comment by uc-msft** [comment] 2019-10-22 18:41
Why is this closed? this has nothing to do with the green icon.

**Comment by aaomidi** [comment] 2019-10-22 18:43
Are you able to reproduce this or is it a one off thing that happened?

**Comment by MaddyDev** [comment] 2019-10-22 18:51
@uc-msft  Is this a new connection or an existing one?

**Comment by uc-msft** [comment] 2019-10-22 19:03
Hit this couple of times when i tried to expand a server after opening ADS fresh (so existing server connection)

**Comment by aaomidi** [comment] 2019-10-22 19:29
This is potentially an issue with the specific server - although we've done a large pull from vscode recently which might be the cause of this. 

I'll keep my eye on this issue, please do update it if you notice it in another BDC server.

**Comment by MaddyDev** [comment] 2019-10-22 19:33
As Amir said, it might be possible that the issue is with the specific server since I tested couple of times and it worked as expected.

**Comment by MaddyDev** [comment] 2019-10-22 19:35
Closed this by mistake. What is it with this issue and me :|

**Comment by CGamboa96** [comment] 2019-11-11 14:24
Any update on this? Everyone in my company is experiencing this problem when trying to connect to our Azure SQL server. From what I have found the stable version for me is 1.10.0 and any newer version results to this issue. 

In addition, we are able to connect to one of our sql servers and discovered that the connection string password does **NOT** contain any special characters.

**Comment by aaomidi** [comment] 2019-11-11 20:05
Do you have any logs of when this issue happened @CGamboa96?

**Comment by CGamboa96** [comment] 2019-11-12 10:47
For us it happened it only occurred after downloading the update to 1.11.0. However, I tried out each version between 1.9.0 to 1.13.0 and found that 1.9.0 and 1.10.0 was the only ones that allowed me to connect to our SQL servers. From the logs this is what I can see: 

```
--- 1.13.0 ---

[2019-11-12 08:46:15.156] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'NA'|group:undefined
[2019-11-12 08:46:15.156] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'NA'|group:undefined
[2019-11-12 08:46:15.156] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'CORRECT USER'|group:undefined
[2019-11-12 08:46:16.430] [renderer1] [error] OnConnectionComplete but no connection found 'connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'INCORRECT USER'|group:undefined' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'CORRECT USER'|group:undefined]
[2019-11-12 08:46:16.471] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at ConnectionStatusManager.onConnectionComplete (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:169807:23)
    at ConnectionManagementService.onConnectionComplete (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:224786:60)
    at MainThreadDataProtocol.$onConnectionComplete (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:236203:47)
    at RPCProtocol._doInvokeHandler (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:241119:27)
    at RPCProtocol._invokeHandler (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:241104:45)
    at RPCProtocol._receiveRequest (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:241031:32)
    at RPCProtocol._receiveOneMessage (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:240959:26)
    at RPCProtocol._protocol.onMessage (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:240849:52)
    at Emitter.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at BufferedEmitter.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:33784:35)
    at PersistentProtocol._receiveMessage (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:34003:37)
    at PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:33877:83)
    at Emitter.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at ProtocolReader.acceptChunk (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:33610:37)
    at ProtocolReader._register._socket.onData.data (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:33579:61)
    at Socket.listener (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:34240:40)
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:496:34)
    at Socket.ZoneTask.invoke (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)


--- 1.13.0 ---

[2019-11-12 08:48:28.098] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'NA'|group:undefined
[2019-11-12 08:48:28.098] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'NA'|group:undefined
[2019-11-12 08:48:28.098] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:'NA'|user:'NA'|group:undefined
[2019-11-12 08:48:28.118] [renderer1] [error] URI malformed: URIError: URI malformed
	at decodeURIComponent (<anonymous>)
	at Function.parse (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10332:89)
	at ExtHostDataProtocol.$connect (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38229:96)
	at RPCProtocol._doInvokeHandler (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47947:27)
	at RPCProtocol._invokeHandler (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47932:45)
	at RPCProtocol._receiveRequest (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47859:32)
	at RPCProtocol._receiveOneMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47787:26)
	at define.constructor._protocol.onMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47677:52)
	at Emitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:4099:38)
	at BufferedEmitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15788:35)
	at define.constructor.protocol.onMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:56029:41)
	at Emitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:4099:38)
	at BufferedEmitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15788:35)
	at PersistentProtocol._receiveMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:16007:37)
	at define.constructor._socketDisposables.push._socketReader.onMessage.msg (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15881:83)
	at Emitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:4099:38)
	at ProtocolReader.acceptChunk (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15614:37)
	at define.constructor._register._socket.onData.data (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15583:61)
	at Socket.listener (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:16112:40)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-11-12 08:48:32.345] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:'database'|server:'NA'|user:'NA'|databaseDisplayName:'database'|group:C777F06B-202E-4480-B475-FA416154****
[2019-11-12 08:48:32.345] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:'database'|server:'NA'|user:'NA'|databaseDisplayName:'database'|group:C777F06B-202E-4480-B475-FA416154****
[2019-11-12 08:48:32.345] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:'database'|server:'NA'|user:'NA'|databaseDisplayName:'database'|group:C777F06B-202E-4480-B475-FA41615****
[2019-11-12 08:48:32.354] [renderer1] [error] URI malformed: URIError: URI malformed
	at decodeURIComponent (<anonymous>)
	at Function.parse (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10332:89)
	at ExtHostDataProtocol.$connect (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38229:96)
	at RPCProtocol._doInvokeHandler (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47947:27)
	at RPCProtocol._invokeHandler (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47932:45)
	at RPCProtocol._receiveRequest (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47859:32)
	at RPCProtocol._receiveOneMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47787:26)
	at define.constructor._protocol.onMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47677:52)
	at Emitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:4099:38)
	at BufferedEmitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15788:35)
	at define.constructor.protocol.onMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:56029:41)
	at Emitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:4099:38)
	at BufferedEmitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15788:35)
	at PersistentProtocol._receiveMessage (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:16007:37)
	at define.constructor._socketDisposables.push._socketReader.onMessage.msg (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15881:83)
	at Emitter.fire (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:4099:38)
	at ProtocolReader.acceptChunk (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:15614:37)
	at define.constructor._register._socket.onData.data (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.j
s:15583:61)
	at Socket.listener (/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:16112:40)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by aveuud** [comment] 2020-04-14 11:57
I have the same issue: get an error message "An unexpected error occurred while connecting." 

Azure Data Studio
Version: 1.16.1
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:06:16.901Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

This used to work, but now I have to maintain two versions of my code in order to execute the scripts. One in plain file and one in Git. Please fix this!

**Comment by aveuud** [comment] 2020-07-06 08:48
My problem has now been solved. The issue was a space in the repository name cloned from DevOps. When Azure data studio tried to connect to the database it also tried to find a working folder, but failed due to the space in the name. Committing, pushing and pulling worked just fine, but the database connection failed until I renamed the repository folder.

**Comment by fzafeiriou** [comment] 2020-09-18 20:58
https://slack.github.com/github/oauth/callback
An unexpected error occurred. ref: 346abaea66ec4330a1bd546fb420fbae

**Comment by ricardogerbaudo** [comment] 2020-10-20 18:44
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/5410884/renderer1.log)

**Comment by Charles-Gagnon** [comment] 2022-12-06 22:54
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.

**Closed by Charles-Gagnon** 2022-12-06 22:54 UTC
Labels: Bug, Area - Connection, Triage: Done
