### ISSUE TITLE
Insider builds do not recognize source control

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#17045] opened 2021-09-10 19:12 UTC
- Azure Data Studio Version: Insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a workspace or git folder using Insider builds
2.
![image](https://user-images.githubusercontent.com/29285871/132905186-931262a8-80b5-4154-b740-fbf6535d3195.png)

Release version 1.32 does not have this problem

**Comment by kburtram** [comment] 2021-09-10 19:40
Duplicate of https://github.com/microsoft/azuredatastudio/issues/17033

**Closed by kburtram** 2021-09-10 19:40 UTC
