### ISSUE TITLE
Selecting file on Source Control panel disconnects connection on opened file

### ISSUE THREAD

**Issue by GrzegorzLyp** [microsoft/azuredatastudio#6137] opened 2019-06-23 16:12 UTC
Issue Type: <b>Bug</b>

Open sql file in ADS. Connect to database. Modify file. Open Source Control panel. File will occur on list of changes.  Click file in the Source Control panel. The opened tab with file will be disconnected.

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (83410565da1992e6d96ebf61b112fe0a13c44f9a, 2019-06-21T20:31:32.778Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (7.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.40.0
import|Mic|0.8.0
profiler|Mic|0.8.0

</details>

**Comment by GrzegorzLyp** [comment] 2019-08-21 19:59
Fixing this problem is really important. It seems that disconnecting happens in the other situations but I cannot repeat the exact moment.

**Comment by kburtram** [comment] 2021-08-17 19:26
This issue appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/4656.  @smartguest is currently looking into this general issue (specifically when a untitled file is saved).  We'll verify that fixes also addresses these two other bugs.

**Closed by kburtram** 2021-08-17 19:26 UTC
Labels: Bug, Area - Query Editor
