### ISSUE TITLE
Warnings are not getting displayed in the tasks pane while trying to Export/Import DB.

### ISSUE THREAD

**Issue by HarshiniCoder** [microsoft/azuredatastudio#10479] opened 2020-05-18 20:28 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to the server 
2. Right click on the server - select Data tier Application Wizard
3.  Select 3rd option - Create a database from a .bacpac file [Import Bacpac]
4. While processing the import - if there are warnings don't see them on UI. 
The import will be successful without displaying warnings. 
Expected - Warnings should be displayed in the tasks pane.

**Comment by udeeshagautam** [comment] 2020-05-18 20:33
This is a core issue - Tagging DacFx since thats where the repro comes from

**Comment by kisantia** [comment] 2022-12-06 22:07
Closing as by design. Error messages from DacFx only get shown if the task failed, which is why warnings aren't showing. For warnings to show, all the output would have to be displayed, like what's being requested in https://github.com/microsoft/azuredatastudio/issues/21332

**Closed by kisantia** 2022-12-06 22:07 UTC
Labels: Bug, Area - DacFX, Triage: Done
