### ISSUE TITLE
Error output on first cell execution after loading kernel.

### ISSUE THREAD

**Issue by lerchdude** [microsoft/azuredatastudio#9381] opened 2020-02-28 01:25 UTC
Issue Type: <b>Bug</b>

Occasionally, after toggling the kernel in a notebook (FWIW I am typically using PowerShell), I will get an error that is unrelated to the code in the cell during its first execution. For example:

```
At line:58 char:37
+ %set_env VSCODE_NLS_CONFIG={"locale":"en-us","availableLanguages":{}, ...
+                                     ~~~~~~~~
Unexpected token ':"en-us"' in expression or statement.
At line:58 char:45
+ %set_env VSCODE_NLS_CONFIG={"locale":"en-us","availableLanguages":{}, ...
+                                             ~
Missing argument in parameter list.
At line:1 char:3
+ . {
+   ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
}
At line:1 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 

. {
>> Start-Sleep -Seconds 2
>> 
````

I also noticed a brief pop-up saying  "Kernel is dead".

Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (d6b5d3c6b1c717a02e791175417b5d31c5b017b3, 2020-02-27T18:07:15.223Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (48 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|159.90GB (36.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lerchdude** [comment] 2020-02-28 01:37
Closing as duplicate. Apologies!

**Comment by lerchdude** [comment] 2020-03-06 19:41
Reopening since the duplicate was closed and I can't reopen that one.

**Comment by amthomas46** [comment] 2020-03-17 17:16
@chlafreniere I think part of this issue is when you install the latest version of ADS, powershell-kernel 1.3 isn't installed

**Comment by joshfria** [comment] 2020-05-06 13:50
I'm getting this same behavior. It wont even stay functional for a whole day.

**Comment by DiHo78** [comment] 2020-05-14 10:41
I have a similar issue on 2 different Win10 machines with german localization.

In Zeile:61 Zeichen:37
+ %set_env VSCODE_NLS_CONFIG={"locale":"de","availableLanguages":{},"_l ...
+                                     ~~~~~
Unerwartetes Token ":"de"" in Ausdruck oder Anweisung.
In Zeile:61 Zeichen:42
+ %set_env VSCODE_NLS_CONFIG={"locale":"de","availableLanguages":{},"_l ...
+                                          ~
Argument in der Parameterliste fehlt.
In Zeile:1 Zeichen:3
+ . {
+   ~
Die schlie■nde "}" fehlt im Anweisungsblock oder der Typdefinition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
}
In Zeile:1 Zeichen:1
+ }
+ ~
Unerwartetes Token "}" in Ausdruck oder Anweisung.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by DiHo78** [comment] 2020-05-14 10:58
I'm getting simliar errors on 2 different Win10 machines with german localization
```
In Zeile:61 Zeichen:37
+ %set_env VSCODE_NLS_CONFIG={"locale":"de","availableLanguages":{},"_l ...
+                                     ~~~~~
Unerwartetes Token ":"de"" in Ausdruck oder Anweisung.
In Zeile:61 Zeichen:42
+ %set_env VSCODE_NLS_CONFIG={"locale":"de","availableLanguages":{},"_l ...
+                                          ~
Argument in der Parameterliste fehlt.
In Zeile:1 Zeichen:3
+ . {
+   ~
Die schlie■nde "}" fehlt im Anweisungsblock oder der Typdefinition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
}
In Zeile:1 Zeichen:1
+ }
+ ~
Unerwartetes Token "}" in Ausdruck oder Anweisung.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

Installed powershell kernel is  0.1.3

The weird thing is: I have also an adminVM, which is also Win10 but just with english display language. 
Same powershell kernel (0.1.3) but here the same notebook is working like a charm. 
If I can provide further information jsut let me know.

**Comment by MsSQLGirl** [comment] 2020-05-14 17:29
@chlafreniere - a few folks in the community seem to be able to repro this as well. This has also happened to me a few times including in the latest ADS. 

Version: 1.17.1 (user setup)
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-30T00:16:35.943Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by SQLThomas** [comment] 2020-05-14 17:30
I can confirm getting that same error Dirk posted, on a German Win 10 machine.

**Comment by DiHo78** [comment] 2020-05-14 17:33
You can follow my repro here:
[https://github.com/DiHo78/ADSNotebooks/tree/master/notebooks/adsNotebookError](url)

I did put it in Notebooks instead of making screenshots though...

**Comment by DiHo78** [comment] 2020-05-18 16:38
Just as a flollow up since my response was only via twitter yet:
When the cells are cleared first and notebook gets saved then the cells in the notebooks work fine.

**Comment by chlafreniere** [comment] 2020-06-25 18:27
In our insiders builds, this should no longer repro for the PowerShell kernel any more; we aren't running these set environment variable commands in the background for the powershell kernel.

**Comment by amthomas46** [comment] 2020-06-25 18:29
Confirmed - i have not been able to repro on Insiders! Thank you Chris!

**Comment by chlafreniere** [comment] 2020-06-25 18:31
Very happy to hear that! I'll close this issue then 😄

**Closed by chlafreniere** 2020-06-25 18:31 UTC
Labels: Area - Notebooks, Bug, Impact: Live site, Triage: Done
