### ISSUE TITLE
Query Charts are not being displayed

### ISSUE THREAD

**Issue by mpkarlo** [microsoft/azuredatastudio#7976] opened 2019-10-24 12:22 UTC
Issue Type: <b>Bug</b>

Write a query that returns a decent result set, in my testing I just used the WideWorldImporters sample database. After the query executes and I press the Chart button in the results, nothing is shown on the new Chart tab.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7- 4860  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|16.00GB (6.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
dacpac|Mic|0.6.0
import|Mic|0.11.0
profiler|Mic|0.9.0

</details>

**Comment by abist** [comment] 2019-10-24 22:05
@mpkarlo I can't seem to repro this on WorldWideImporters. Was it a specific kind of chart this failed for?

**Comment by mpkarlo** [comment] 2019-10-24 22:31
@abist No... I can't use any chart since a few updates ago. Charts embedded in Dashboards continue to work just fine, though. 

All I pressed was the chart button on the results pane, a chart isn't displayed even then. Is there some kind of debug info I can provide, maybe?

**Comment by abist** [comment] 2019-10-24 22:36
@mpkarlo Thanks for the details! One way you can help us out to figure out the issue is by opening the Developer Console (`Ctrl`/`Cmd` + `Shift` + `I`) then click on the `Console` tab and see if there are any errors there.

**Comment by mpkarlo** [comment] 2019-10-24 22:48
@abist No problem! I do get an error from the Console, I've included it here.

<details>
<summary>
Console Output
</summary>
Unhandled Promise rejection: Cannot read property 'rows' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'rows' of undefined
    at _queryRunner.getQueryRows.then.d (workbench.desktop.main.js:313085)
    at ZoneDelegate.invoke (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388)
    at Zone.run (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138)
    at c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421)
    at Zone.runTask (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595)
    at ZoneTask.invokeTask (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500)
    at Socket.ZoneTask.invoke (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:283)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94) TypeError: Cannot read property 'rows' of undefined
    at _queryRunner.getQueryRows.then.d (file:///C:/Users/kmelendez/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:313085:54)
    at ZoneDelegate.invoke (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (c:\Users\kmelendez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
</details>

**Comment by anthonydresser** [comment] 2019-12-13 23:29
I couldn't repro this myself, but I've added some defensive programming around this in #8680 so I'll close this when that goes in. If you continue to see this error, feel free to reopen.

**Closed** 2019-12-17 20:26 UTC
Labels: Area - Charting, Bug, Triage: Done
