### ISSUE TITLE
Analyze in notebook listed twice when right click on file

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4532] opened 2019-03-15 15:34 UTC
- Azure Data Studio Version: 1.5.1-insider

Steps to Reproduce:

Connect to BDC and try to preview a file. Then, I noticed that Analyze in notebook is listed twice.
<img width="520" alt="Screen Shot 2019-03-15 at 8 33 27 AM" src="https://user-images.githubusercontent.com/28786161/54443016-040ad600-46fd-11e9-88b9-bf62d0ecd971.png">

**Comment by chlafreniere** [comment] 2019-03-16 00:44
This appears to happen only when using the SQL Server big data cluster connection type, and not with the SQL Server connection type. Closing this as by design for now.

**Closed by chlafreniere** 2019-03-16 00:44 UTC
Labels: bug, notebooks
