### ISSUE TITLE
Color Themes not setting all properties correctly

### ISSUE THREAD

**Issue by mcneo1972** [Microsoft/azuredatastudio#5248] opened 2019-04-29 10:32 UTC
Issue Type: <b>Feature Request</b>

Color themes don't set the database connection dropdown selectors correctly. In Dark modes they are always dark text on a dark background making it hard to see.

![image](https://user-images.githubusercontent.com/8267765/56890754-46e8f900-6a72-11e9-8547-dcd096cf0288.png)

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kburtram** [comment] 2019-04-29 16:38
This looks like a duplicate of #4741.  We will fix in the next release.

**Closed by kburtram** 2019-04-29 16:38 UTC
