### ISSUE TITLE
Add possibility to work with Azure Cosmos DB Account Document API

### ISSUE THREAD

**Issue by mdanylyuk** [microsoft/azuredatastudio#23266] opened 2023-05-31 12:01 UTC
Hello guys,
Could you please add the possibility to work with different Azure Cosmos DB Account APIs from the Azure Data Studio, not only MongoDB API.
At least will be great to have Document (SQL) API

**Comment by alanrenmsft** [comment] 2023-05-31 15:34
@languy Is this something you are working on?

**Comment by languy** [comment] 2023-05-31 15:58
That is correct, we are working on [it](https://github.com/Azure/azure-cosmosdb-ads-extension/issues/36) right now.

**Comment by alanrenmsft** [comment] 2023-05-31 16:09
@mdanylyuk closing as a dupe of https://github.com/Azure/azure-cosmosdb-ads-extension/issues/36

**Closed by alanrenmsft** 2023-05-31 16:09 UTC
