### ISSUE TITLE
Results Pane to Right Side

### ISSUE THREAD

**Issue by mjninc** [microsoft/azuredatastudio#24620] opened 2023-10-09 17:08 UTC
Would you please make it possible to put the results pane on the right (or left) side of the code editor please?

Typically my monitors are wide rather than long and I can spare the space horizontically, but for my code, I want as much vertical space as I can get.  

This is already possible in Visual Studio Code.  

See [this ](https://www.google.com/search?q=visual+studio+code+results+on+right&sca_esv=571940854&rlz=1C1GCEJ_enUS905US905&ei=DjIkZbGmO7avqtsPib-F2A8&ved=0ahUKEwix5dPmuOmBAxW2l2oFHYlfAfsQ4dUDCBA&uact=5&oq=visual+studio+code+results+on+right&gs_lp=Egxnd3Mtd2l6LXNlcnAiI3Zpc3VhbCBzdHVkaW8gY29kZSByZXN1bHRzIG9uIHJpZ2h0MgUQABiiBDIIEAAYiQUYogQyBRAAGKIEMgUQABiiBEjXEFAAWPsPcAB4AZABAJgBmwGgAfkNqgEEMTEuN7gBA8gBAPgBAcICBBAhGAriAwQYACBBiAYB&sclient=gws-wiz-serp#fpstate=ive&vld=cid:303c3b78,vid:HKiAfsPOdh0,st:0)video:

**Comment by cheenamalhotra** [comment] 2023-10-10 22:27
Duplicate of https://github.com/microsoft/azuredatastudio/issues/20134, please upvote the same instead.

**Closed by cheenamalhotra** 2023-10-10 22:27 UTC
Labels: Area - Query Editor, Enhancement, Triage: Needed
