### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by sunmicosun** [microsoft/azuredatastudio#4320] opened 2019-03-07 01:18 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sunmicosun** [comment] 2019-03-07 01:20
how to upload the picture

**Comment by kburtram** [comment] 2019-03-07 01:29
@sunmicosun you can add pictures to the issue by clicking the "Attach file by dragging & dropping, selecting them, or pasting from the clipboard." note at the bottom of a comment input area then selecting the file.

<img width="637" alt="screen shot 2019-03-06 at 5 28 35 pm" src="https://user-images.githubusercontent.com/599935/53925579-49f8d780-4035-11e9-87bc-7baac96378dd.png">

**Comment by sunmicosun** [comment] 2019-03-07 01:42
![snipaste_2019-03-07_09-16-28](https://user-images.githubusercontent.com/43307883/53926061-16fa2680-40bd-11e9-9d3c-d8af197261d2.png)
![snipaste_2019-03-07_09-16-01](https://user-images.githubusercontent.com/43307883/53926068-195c8080-40bd-11e9-80b7-146009eec0c1.png)
when I open ads, I don't know what to do, so I reinstall the ADS , but  it doesn't work, Thank you!

**Comment by kburtram** [comment] 2019-03-07 01:48
It looks like all the child service processes aren't launching for some reason.  From the screenshot it looks like ADS was working at one point (since there are saved servers)?

Which OS are you using?  If this is Linux, it appears the .Net Core applications may not be running for some reason.  Can you open the "Help->Developer Tools" and see if there are any exception details in the Console pane?

**Comment by sunmicosun** [comment] 2019-03-07 01:51
win 10 pro 1809update

CPUs | Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 11.95GB (6.26GB free)
Process Argv | C:\Users\sunmi\Downloads\azuredatastudio-windows\azuredatastudio.exe
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
sqlops-combine-scripts | Bat | 1.3.0
firstresponderkit | dre | 0.4.0
pastetheplan | dre | 0.2.0
sqldm-performance-insights | IDE | 0.4.0
newdatabase | kev | 0.0.3
alwayson-insights | mat | 0.2.1
mssql-db-insights | mat | 0.2.2
mssql-instance-insights | mat | 0.2.1
admin-pack | Mic | 0.0.1
agent | Mic | 0.36.1
import | Mic | 0.5.0
profiler | Mic | 0.6.0
server-report | Mic | 0.1.5
sql-dw | Mic | 0.0.1
whoisactive | Mic | 0.1.1
sqlops-spexecutesql-to-sql | pej | 0.0.1
sql-search | Red | 0.3.0
poor-sql-formatter | WSR | 0.1.0

this is consolo

 INFO no standard startup: not the explorer viewlet
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Microsoft.sql-dw]: No description specified to show.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 extensionHost process id is 3544
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 SqlTools Log file is: C:/Users/sunmi/AppData/Roaming/azuredatastudio/mssql/sqltools_3544.log
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for MicrosoftSqlToolsServiceLayer.exe is C:\Users\sunmi\AppData\Roaming\azuredatastudio\mssql\sqltools_3544.log
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 3544
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {}
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 9:50:10 AM] Starting client failed
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Launching server using command c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsServiceLayer.exe failed.
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Couldn't start client SqlToolsService
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR spawn c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsServiceLayer.exe ENOENT: Error: spawn c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsServiceLayer.exe ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for SqlToolsResourceProviderService.exe is C:\Users\sunmi\AppData\Roaming\azuredatastudio\mssql\resourceprovider_3544.log
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 3544
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {}
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Couldn't start client AzureResourceProvider
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR spawn c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\SqlToolsResourceProviderService.exe ENOENT: Error: spawn c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\SqlToolsResourceProviderService.exe ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for MicrosoftSqlToolsCredentials.exe is C:\Users\sunmi\AppData\Roaming\azuredatastudio\mssql\credentialstore_3544.log
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Couldn't start client Flat File Import Service
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR spawn c:\Users\sunmi\.azuredatastudio\extensions\microsoft.import-0.5.0\flatfileimportservice\Windows\0.0.2\MicrosoftSqlToolsFlatFileImport.exe ENOENT: Error: spawn c:\Users\sunmi\.azuredatastudio\extensions\microsoft.import-0.5.0\flatfileimportservice\Windows\0.0.2\MicrosoftSqlToolsFlatFileImport.exe ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Couldn't start client SerilizationProvider
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR spawn c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsCredentials.exe ENOENT: Error: spawn c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsCredentials.exe ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 3544
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {}
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] rejected promise not handled within 1 second
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR Launching server using command c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsServiceLayer.exe failed.
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] rejected promise not handled within 1 second
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR Launching server using command c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\SqlToolsResourceProviderService.exe failed.
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] rejected promise not handled within 1 second
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR Launching server using command c:\Users\sunmi\.azuredatastudio\extensions\microsoft.import-0.5.0\flatfileimportservice\Windows\0.0.2\MicrosoftSqlToolsFlatFileImport.exe failed.
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] rejected promise not handled within 1 second
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR Launching server using command c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsCredentials.exe failed.

**Comment by sunmicosun** [comment] 2019-03-07 01:52
I used a user install ADS, then I use zip, it still does't work

**Comment by kburtram** [comment] 2019-03-07 02:08
Hmm, it looks like all the .Net Core child processes are failing for some reason.  The log doesn't seem to say why.  


Could you please try running `c:\Users\sunmi\Downloads\azuredatastudio-windows\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsServiceLayer.exe` from the command-line and see if there is an error message?

**Comment by sunmicosun** [comment] 2019-03-07 02:46
![snipaste_2019-03-07_10-45-54](https://user-images.githubusercontent.com/43307883/53928753-36e21800-40c6-11e9-8f4f-057a2f356263.png)
it doesn't work and no error both direct running and in cmd

**Comment by jacobrillema** [comment] 2019-06-07 05:31
Any updates on this? ADS is no longer an option at this point until this gets resolved for me. No connections are working. I have tried insider build and stable builds and the same issue.

**Comment by jacobrillema** [comment] 2019-06-07 05:48
Ok, I found something here. So I had a bunch of saved local servers in a saved server group. None of them were connecting, turned out the database files were on a BitLocker drive and had yet to be unlocked. Once I unlocked the BitLocker drive, restarted the MSSQL Window services I was able to connect to them through ADS. I then went back and try to add a new connection to Azure SQL Server instance and no issues at all. So it appears to have some hiccups on either accessing the drives for the saved server group. Maybe this will help another person or help find the root cause.

**Comment by Charles-Gagnon** [comment] 2019-06-07 06:51
Interesting - were you getting the same behavior as @sunmicosun where none of the child processes were starting up? I would expect general connection errors given your description of the issue but I wouldn't expect the child processes themselves to actually have issues starting up.

**Comment by jacobrillema** [comment] 2019-06-07 16:27
Yeah, I was seeing the exact same errors as @sunmicosun pointed out. I did try to run the exe manually but it never came back, it just was hung with no errors. Probably trying to open a connection from my saved groups. Perhaps ADS is just reporting an error after the exe doesn't return back after a while. It would have been a whole lot easier to debug if it reported back saying unable to open database. SSMS balked at the drive not accessible something like unable to login into the database.

**Comment by cheenamalhotra** [comment] 2022-12-14 21:12
Closing this issue as resolved based on [comment](https://github.com/microsoft/azuredatastudio/issues/4320#issuecomment-499765131) above.

**Closed by cheenamalhotra** 2022-12-14 21:12 UTC
Labels: Bug, Area - Connection
