### ISSUE TITLE
Creating sql proj from yaml file fails

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17239] opened 2021-10-04 21:58 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

 using the following yaml create a sql proj: https://github.com/AmericanAirlines/AA-Mock-Engine/blob/master/api/swagger/swagger.yaml
Expected: either a sql project is created or it should show an error which helps user understand the problem
Actual: the error is not clear:

"    > autorest --use:autorest-sql-testing@latest --input-file="e:\tests\aa_sample.yaml" --output-folder="e:\tests\aa_sample" --clear-output-folder
    stdout: AutoRest code generation utility [cli version: 3.4.0; node: v14.17.0]
    stdout: 
    stdout: (C) 2018 Microsoft Corporation.
    stdout: https://aka.ms/autorest
    stdout: 
    stdout: info    |    Loading AutoRest core      'C:\Users\llali\.autorest\@autorestcore@3.6.3\nodemodules\@autorest\core\dist' (3.6.3)
    stdout: 
    stdout: info    |    Loading AutoRest extension 'autorest-sql-testing' (latest->0.0.3)
    stdout: 
    stdout: info    |    Loading AutoRest extension '@autorest/modelerfour' (4.20.0->4.20.0)
    stdout: 
    stdout: fatal   | Process() cancelled due to failure 
    stdout: 
    stderr:   Error: Server url '/' cannot be resolved to an absolute url. Update to be an absolute url or load OpenAPI document from host to automatically resolve the url relative to it.
    stderr: 
    >>> autorest --use:autorest-sql-testing@latest --input-file="e:\tests\aa_sample.yaml" --output-folder="e:\tests\aa_sample" --clear-output-folder    … exited with code: 1
"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Benjin** [comment] 2021-10-05 20:25
I'll check with the autorest team; this appears to be in the core modeler

**Comment by kisantia** [comment] 2022-12-08 21:45
closing as by design, as explained above :)

**Closed by kisantia** 2022-12-08 21:45 UTC
Labels: Upstream, Triage: Done, Area - SQL Project
