### ISSUE TITLE
Provide a way to view tables by schema and/or to search for a table

### ISSUE THREAD

**Issue by stephajn** [microsoft/azuredatastudio#17881] opened 2021-12-09 18:09 UTC
**Is your feature request related to a problem? Please describe.**
For larger databases, the list of tables gets incredibly long and it can be incredibly onerous to scroll through such a long list to find the one I'm interested in.

**Describe the solution or feature you'd like**
It would be great if the Tables node could group tables by the Schema they belong to rather than just being an entirely flat list.
Additionally, a search box at the top of the explorer window to search for an object name would be very helpful.

**Comment by Charles-Gagnon** [comment] 2021-12-09 18:17
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/7 - thanks for the feedback!

**Closed by Charles-Gagnon** 2021-12-09 18:17 UTC
