### ISSUE TITLE
SQL Query file (tab) becomes empty

### ISSUE THREAD

**Issue by nilact** [microsoft/azuredatastudio#13498] opened 2020-11-20 10:49 UTC
Issue Type: <b>Bug</b>

When we compare the content of the files in ADS and close the comaprison window, one of the query files (tab) becomes empty and the content within that tab goes missing. Sometimes both the files become empty.

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
profiler|Mic|0.11.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kburtram** [comment] 2021-08-18 05:36
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/12293.  Thanks for reporting!

**Closed by kburtram** 2021-08-18 05:36 UTC
Labels: Bug, Area - Query Editor, Area - Shell, Triage: Done, Triage: Postponed
