### ISSUE TITLE
ADS can be shrinked to strange looking level

### ISSUE THREAD

**Issue by geleems** [Microsoft/azuredatastudio#4467] opened 2019-03-13 23:19 UTC
ADS can be shrinked like this.
Should this be fixed? or Do we allow this?

![image](https://user-images.githubusercontent.com/19577035/54320838-9f8c3180-45ab-11e9-8186-cda6db26786b.png)

**Comment by kburtram** [comment] 2019-03-14 18:30
@geleems what is the behavior you expected in this scenario?

**Comment by kburtram** [comment] 2019-04-17 00:58
Closing as "by design" since we don't have plans to make ADS display content in highly constrained resolutions.  We'd ask the user to workaround the issue by resizing the window a bit larger.

**Closed by kburtram** 2019-04-17 00:58 UTC
Labels: Area: Shell, Enhancement
