### ISSUE TITLE
Open existing has an option to open workspace, but New doesn't have the option for creating new workspace

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#13449] opened 2020-11-16 20:14 UTC
![image](https://user-images.githubusercontent.com/57200045/99303777-4f488680-2806-11eb-95bd-a37ec3b4c872.png)

![image](https://user-images.githubusercontent.com/57200045/99303807-5c657580-2806-11eb-9810-d73c1a04a7cc.png)

**Comment by kisantia** [comment] 2020-12-11 22:41
closing as this is by design after discussing with Raden

**Closed by kisantia** 2020-12-11 22:41 UTC
Labels: Area - SQL Project, Enhancement
