### ISSUE TITLE
Syntax highlighting breaks after backslash char

### ISSUE THREAD

**Issue by fykcz** [microsoft/azuredatastudio#11244] opened 2020-07-08 13:51 UTC
- Azure Data Studio Version: 1.19.0 (user setup)
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:06:05.429Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Use this code:
    DECLARE @X VARCHAR(100);
    DECLARE @L VARCHAR(100);
    SET @L = 'DOMAIN\USER';
    SET @X = REPLACE(@L, 'DOMAIN\\', '');
    SELECT @X

2. Problem is with the backslash character.
![image](https://user-images.githubusercontent.com/6848471/86926782-c5d7c800-c132-11ea-9008-633e24f35a73.png)

**Comment by Charles-Gagnon** [comment] 2020-07-08 15:14
Duplicate of https://github.com/microsoft/azuredatastudio/issues/11150 - this issue is currently fixed in insiders and will be included in the upcoming stable release. Thanks for the report!

**Closed by Charles-Gagnon** 2020-07-08 15:14 UTC
Labels: Area - Query Editor, Bug, Triage: Needed

**Comment by fykcz** [comment] 2020-07-08 16:18
Oops, i didn't find this related issue. I'm sorry, my mistake. Thank you for solving the problem and for closing my duplicate issue.
