### ISSUE TITLE
Unable To Script Table Data through Azure Data Studio

### ISSUE THREAD

**Issue by dheerajm31** [microsoft/azuredatastudio#8919] opened 2020-01-21 19:17 UTC
Hi ,

I need to refresh specific Table from Prod To Stg Environment as We cannot filter the rows in the Generate Script wizard of SSMS. So i thought to choose Azure Data Studio through Script Table Data.

When i run the command in Query Panel Window , I got the result but while performing scripting with same query it fails with error : Query has no result to return

Environment :- SQL Azure Data Warehouse Server

Please let me know how we can resolve this.

**Comment by Charles-Gagnon** [comment] 2020-01-21 20:01
@dheerajm31 This seems likely to be a dupe of https://github.com/microsoft/azuredatastudio/issues/7260. I'm going to close this now and work on finishing up the port to update ADS with the fix - after which it should be available in the insiders build to try out. Please follow the linked issue for updates and let me know if that doesn't resolve the problem!

**Closed by Charles-Gagnon** 2020-01-21 20:01 UTC
Labels: Area - Query Editor, Enhancement, Triage: Needed

**Comment by dheerajm31** [comment] 2020-01-22 05:23
@Charles-Gagnon Is the issue has been resolved ? As I am still facing this error

**Comment by dheerajm31** [comment] 2020-01-22 06:44
@Charles-Gagnon May i know when we are expecting updated release

**Comment by Charles-Gagnon** [comment] 2020-01-22 15:45
The fix is now available in our [insiders builds](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master). Otherwise it'll be available in the next stable release - currently targeted for early February.
