### ISSUE TITLE
Authentication Error Failed to add account

### ISSUE THREAD

**Issue by ajnixon** [microsoft/azuredatastudio#9548] opened 2020-03-11 17:57 UTC
Issue Type: <b>Bug</b>

It appears that the connection to Azure servers from ADS has changed.  I tried to connect to the server as normal.  I was taken to the Azure Portal login page.  When I succesfully logged into the Azure Portal, I received two Azure (Core) Extension errors: 
1. Failed to add account.  No Azure tenants.
2. Your authentication to the tenant ... failed: {1}
![authentication failure](https://user-images.githubusercontent.com/40508494/76448122-10b12100-6387-11ea-829b-d92fc84cd6ba.jpg)

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment] 2020-03-23 18:05
@aaomidi does this look related to recent Azure Auth changes?

**Comment by aaomidi** [comment] 2020-03-23 18:34
@ajnixon Can you open the console and try to authenticate? It might show more context on what's happening here.

**Comment by aaomidi** [comment] 2020-04-02 18:17
Thanks for reporting this bug, @ajnixon. Unfortunately, since I can't reproduce this bug I'm going to close this issue. If you can get me more context/logs, I'll happily look into it again.

Thanks!

**Comment by dharmeshkakadia** [comment] 2020-04-15 22:46
I have the same issue. Happy to give you any details that might help.

**Comment by aaomidi** [comment] 2020-04-15 22:47
@dg

**Comment by dharmeshkakadia** [comment] 2020-04-15 22:56
Let me give it a try

**Comment by dharmeshkakadia** [comment] 2020-04-15 22:58
@ajnixon Its just stuck there instead of erroring out at all. Tried a few times.

**Comment by aaomidi** [comment] 2020-04-15 22:59
Can you give more context? What's just stuck there? Is it logging in? Are you able to see your account on the azure pane on the left side?

**Comment by dharmeshkakadia** [comment] 2020-04-15 23:01
![image](https://user-images.githubusercontent.com/2123078/79397157-4de27300-7f32-11ea-8096-e38141d1c433.png)

I have removed the account and server from the image

**Comment by aaomidi** [comment] 2020-04-15 23:01
Ah so its the process of logging into the server. Are you an active directory admin on this server?

You can check by going to Azure Portal

**Comment by dharmeshkakadia** [comment] 2020-04-15 23:02
No, I am not admin.
The Azure portal login works perfectly fine. Even Data Studio was working a few weeks ago before updates.

**Comment by aaomidi** [comment] 2020-05-06 20:47
Hmm, I've been unable to repro this on my side. Just for a sanity check is this still happening?

**Comment by dharmeshkakadia** [comment] 2020-05-06 22:08
Yes. Its been broken for almost a month now. :(

**Comment by aaomidi** [comment] 2020-05-06 22:13
Thanks! I hope we can root cause this issue as well.

**Comment by aaomidi** [comment] 2020-05-13 20:55
I'm going to be tracking this under #10314

**Comment by aaomidi** [comment] 2020-05-13 20:56
https://github.com/microsoft/azuredatastudio/issues/10314#issuecomment-627722312

**Closed by aaomidi** 2020-05-13 20:55 UTC
Labels: Area - Connection, Bug, Triage: Done
