### ISSUE TITLE
GO {N} reported as Problem

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/azuredatastudio#7842] opened 2019-10-19 17:09 UTC
Issue Type: <b>Bug</b>

Using the syntax `GO {N}` (where `N` is an integer) wrongly causes the below to be reported in the Problems pane:

> ⦻ Count not find stored procedure ''.
> ⦻ Incorrect syntax near '10'.

`GO {N}` is perfectly valid syntax in ADS (as it is in SSMS and `sqlcmd`) and causes the batch to be executed `N` number of times. It should not be reported as a "problem".

Azure Data Studio version: azuredatastudio 1.12.1 (cccb9327c707fe71de24d5ce655acb29cc8946d1, 2019-10-07T19:16:03.172Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (0.69GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.43.0
cms|Mic|0.5.0
dacpac|Mic|0.6.0
managed-instance-dashboard|Mic|0.3.8
profiler|Mic|0.9.0
schema-compare|Mic|0.6.0
server-report|Mic|0.2.0
whoisactive|Mic|0.1.2
material-icon-theme|PKi|3.9.0
sql-search|Red|0.3.4

</details>

**Comment by Charles-Gagnon** [comment] 2019-10-19 19:08
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/6974, thanks for the report though!

**Closed by Charles-Gagnon** 2019-10-19 19:08 UTC
Labels: Area - Language Service, Bug
