### ISSUE TITLE
Select Top 1000 tab taking very long time to open with LocalDB

### ISSUE THREAD

**Issue by gregveres** [microsoft/azuredatastudio#10584] opened 2020-05-27 12:28 UTC
Issue Type: <b>Bug</b>

I have a localDB database and I am selecting Select Top 1000 query on that database and the tab with the query is not opening. 

And because of the poor design where the tab doesn't open until some operation with the database completes, I have no idea if the operation is being ignored or if some database operation is taking forever to complete.

BTW, I clicked on Select Top 1000 twice on my table, waited 30 seconds, then started to write up this issue and the two tabs have still not opened. 

Something similar happened yesterday with other databases but at least there it eventually came back after 30-ish seconds.

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz (8 x 2834)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|12.00GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
server-report|Mic|0.2.2

</details>

**Comment by glolsh** [comment] 2020-10-26 20:27
I've encountered this bug as well. For some reason this bug disappeared after I changed FilesAutoSave option off (it was set on FocusChange) and on.

**Comment by drizztdourden08** [comment] 2021-02-09 19:06
Why is this still not resolved? I'm using an Azure database so there is no local setup reason for this. ADS is ignoring every single command I throw at it in the right click menu way too often. I have to restart it for it to work again and it's doomed to fail again at some point. It's not just laggy, it does nothing or at least it seems to.

This literally make ADS unusable from a productivity standpoint. The software is light and fast but stuff like this make it unusable daily. I can't start writing every single select query from scratch. Those are precious seconds in a work day. 

Back to SSMS I guess.

**Comment by gregveres** [comment] 2021-02-09 19:37
If you look at the release notes of every version put out, it seems they are too focused on Notebooks rather than on the core functionality of the product. 

I think SSMS is a better choice for the core functionality as ADS's usability is so poor.

**Comment by drizztdourden08** [comment] 2021-02-09 19:43
I've been trying it in and out in the hope to have this fixed as well as Table Design functionality since it was called something else (I can't remember what it was called before ADS). It's at least 2 years ago and still nothing.

I agree we should stop pushing for functionality a minority uses and focus on making this the default tool for MS SQL.

**Comment by gregveres** [comment] 2021-02-09 20:02
Yea, you are probably right that it has been about 2 years since they did anything with the core use case of the product. I have filed a number of usability improvement requests that just go ignored. 
For instance, as soon as you issue a query, the tool should open the window and put a spinner in to give us feedback that it took our command and is running with it. How hard can that be?
I asked for the ability to delete more than one row at a time like you can in SMSS. Again, how hard can that be?

Nothing.

**Comment by drizztdourden08** [comment] 2021-02-09 20:06
Who manage this project? Is it microsoft or is that open-source? Wonder who prioritize everything. It's definitely not done with user in mind.

**Comment by dicedpeppa** [comment] 2021-04-23 09:19
Still very much an issue. Looked like a good tool at first glance, then it's inner ugliness quickly became apparent :) Will not be using anymore. Back to SSMS.

**Comment by kburtram** [comment] 2021-04-23 17:01
@aasimkhan30 I think this is a good candidate to look at with the performance work you're planning.  The problem isn't scoped to local DB.

@gregveres I agree the UX you've suggested with first opening the window and showing a busy spinner makes sense.  Due to how vscode editor is implemented and the customizations we've made to add query editing with the composite view (editor & results in same document) that change would be a major refactoring of the query editing code base.  It may still be worth doing, but we'll likely try to (1) speed up the actually task of generating the SELECT 1000 command and (2) showing some sort of progress indicator short the having the document opened.

For item 1, the cost is typically dominated by (1) the first time the command is run a new connection to the DB is established for scripting purposes, the time here is related to how responsive the server is.  it may be possible to reuse one of the other connections (without running into MARS issues) and (2) generating the column list to add to the SELECT statement.  This is dependent on how fast the server responds with this metadata, as getting the column list requires a DMV query.  We could potentially add an option to just generate "SELECT *" if that turns out to be the bottleneck.  Of course, if SSMS is fast on the same client/server than this is not likely the bottleneck as it executes the same code.

**Comment by gregveres** [comment] 2021-04-23 18:39
@kburtram I just a test with SSMS and DataStudio. I opened the same azure database and did the select top 1000 with both of the tools and they were about the same 5-6 seconds. But the SSMS felt a little more responsive because it opened the window immediately. But then again, 5-6 seconds is just about best case scenerio to an azure database, so it is hard to judge when it comes back so quickly. 

Other places, I have suggested that the query not even be sent. Just populate the window with the query because I never want the stock query results. I always start with the Top 1000 just to give me a query window with a query that is close to what I want. 

Think about how often the top 1000 records contains the record you are looking for... And even when it does, I don't want to visually search through 1000 records to find the record I am looking for. I think the best UX would be:

- open the window immediately
- display a spinner while querying for the fields to generate the sql query
- show the sql query and stop (or at a minimum, have a config setting that controls if the query is automatically sent)

**Comment by cheenamalhotra** [comment] 2023-09-21 22:53
Hi @gregveres @drizztdourden08 @glolsh ,

Would request you to please try the same in the latest release v1.46 and let us know if this is still a concern? We've made various improvements in the way connections are made and how backend metadata queries work which should provide benefit here and give expected experience.

Let us know if you continue to have any concerns!

**Comment by gregveres** [comment] 2023-09-22 08:12
@cheenamalhotra It seems faster. ADS has been getting faster over the last few versions so it is harder to tell. But 1.46 seems pretty quick.

The feedback is still lacking when I make a change to the query and re-issue it. But at least there is feedback now when I right click on the table and say select or edit. 
I just tried re-issuing an edit query and I "think" the run greys out for a bit, but the query was pretty quick that it was very difficult to tell. This too is problematic. If you guys have made the query so quick (especially to a local database) and you don't give feedback that the query was actually executed and the display is now the updated display, then I am still sitting there "waiting" for the query to be done but it is done - I just got no feedback that it was done. This situation is just as bad or worse than the original "it's slow" situation. 

Ah, this is just a problem on the Edit query. The Select query flashes the result set so you know that the query is done. In that case the speed is really good. I click the button and the result set flashes instantly (when local).  No you just need to change the behaviour of the Edit to do the same thing - flash the result set so that I know the query has been executed and what I am looking at is the most up to date data.

**Comment by cheenamalhotra** [comment] 2023-10-23 21:37
> No you just need to change the behaviour of the Edit to do the same thing - flash the result set so that I know the query has been executed and what I am looking at is the most up to date data.

We do the same thing for Edit Data so I'm not sure what is missing. Below is what I see:

![editData](https://github.com/microsoft/azuredatastudio/assets/13396919/6b78d885-59f8-4603-ad6f-5d7ff4c4ca26)

I would recommend you to open a new issue for any experience issues with Edit Data with steps to reproduce/GIF that demonstrates the issue if you experience something. For Selection queries and performance concerns that are now resolved as above, I will close this issue.

**Closed by cheenamalhotra** 2023-10-23 21:37 UTC
Labels: Bug, Impact: Performance, Area - Query Editor, Triage: Done

**Comment by gregveres** [comment] 2023-10-23 21:49
@cheenamalhotra Ok, I will open another issue.
What you are showing isn't what i was saying. Go ahead and edit a table, then click the run button in the upper left corner of the results button. There is no feedback that the query ran and returned. 
Now do the same thing on a Select query and you will see that the results window gets repainted when the query returns, resulting in a visual flash of the data that can be used to tell that the query has finished running.

**Comment by cheenamalhotra** [comment] 2023-10-24 01:31
Ok, I think we have the same experience for Run in Query Editor and Edit Data both where notification is not provided for long running queries. It certainly makes sense to provide feedback if operation is time consuming.

We have an open enhancement request, which should take care of this ask: https://github.com/microsoft/azuredatastudio/issues/24394

**Comment by cbrandsma-cs** [comment] 2024-08-13 18:24
I'm running everything locally, SQL Server database, I used the option on a single table with 10 columns and 5 records.  5 minutes and counting it still hasn't returned any results...hasn't even opened a new tab yet. I have to do "New Query" and type the statement to get anywhere.  Might as well not have this option if it takes this long.
