### ISSUE TITLE
Remote Server Intellisense

### ISSUE THREAD

**Issue by rudiv** [microsoft/azuredatastudio#1373] opened 2018-05-09 11:55 UTC
Issue Type: <b>Bug</b>

When working locally on a (localdb)\MSSQLLocalDB instance, intellisense is available (we can get table / column hints specifically).

However, when connected to a remote server, the Intellisense is not available until after a long wait. There's no hint that an operation (loading in the metadata for the database / connection?) is taking place, and so this behaviour is confusing especially while keyword hints are still available through intellisense.

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|Memory (System)|31.93GB (16.14GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by arc95** [comment] 2018-05-09 11:59
Same issue here. I can't get Intellisense on remote SQL Server db,

`select * from Table t where t.`

`t.` does not produce any column names. I can manually type the name and it'll run the query though.

**Comment by aharpervc** [comment] 2018-05-11 18:27
I'm also seeing this, including when the "remote" server is literally running on localhost or in a locally in docker.

**Comment by ThisNoName** [comment] 2018-10-23 14:30
I was on 1.0.0 and intellisense was fine.  But just updated to 1.1.3, now it only works on local, not remote servers.

**Comment by kburtram** [comment] 2021-08-18 00:06
Closing older issues.  We've made many intellisense improvements since this issue was opened.  Please let us know if the issue is still impacting your scenario.

**Closed by kburtram** 2021-08-18 00:06 UTC
Labels: Area - Performance, Area - Language Service
