### ISSUE TITLE
Create external table wizard against Oracle fails with - Cannot read property 'contributes' of undefined

### ISSUE THREAD

**Issue by rl-msft** [microsoft/azuredatastudio#7284] opened 2019-09-19 13:17 UTC
### Issue
ADS wizard to create external table against Oracle is failing with this error 

 **Cannot read property 'contributes' of undefined** 

### ADS build:
Version: 1.12.0-insider (user setup)
Commit: 6af544afde27852343d403e2e11de7e104183a27
Date: 2019-09-18T07:50:32.629Z
VS Code 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

SQL server 2019 extension  0.16.0

here is the call stack from Developer tools Console

ERR Cannot read property 'error' of undefined: TypeError: Cannot read property 'error' of undefined
    at Promise.resolve._proxy.$getChildren.then.err (file:///C:/Users/rafidl/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:242131:42)
    at ZoneDelegate.invoke (c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (c:\Users\rafidl\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

please note that able create the external table using TSQL and successfully querying it , the below example is to  create external table to a sample table that comes out of the box with Oracle XE express edition.

create master key encryption by PASSWORD = 'XXXXXXXX'

CREATE DATABASE SCOPED CREDENTIAL [OracleCredential] WITH IDENTITY = 'SYSTEM', SECRET = 'XXXXXXXX';

CREATE EXTERNAL DATA SOURCE [OracleSalesSrvr] WITH (LOCATION = 'oracle://199.168.2.10',CREDENTIAL = [OracleCredential]);

CREATE EXTERNAL TABLE [Oracle_ext_REGIONS]
  (    
    "REGION_ID" FLOAT(53) NOT NULL, 
       "REGION_NAME" NVARCHAR(25) COLLATE Latin1_General_BIN
   ) 
WITH (DATA_SOURCE=[OracleSalesSrvr], LOCATION='XE.HR.REGIONS');

select * from [Oracle_ext_REGIONS]

**Comment by kevcunnane** [comment] 2019-09-19 16:50
@corivera can you take a look and see if there's a regression in Insiders?

**Comment by corivera** [comment] 2019-09-19 20:52
Duplicate of https://github.com/microsoft/azuredatastudio/issues/7233

**Closed by corivera** 2019-09-19 20:53 UTC
Labels: Area: SQL 2019, Bug, Impact: SQL 2019
