### ISSUE TITLE
Save as csv/excel or copy/paste don't include headers in Notebooks

### ISSUE THREAD

**Issue by RicardoNoerr** [microsoft/azuredatastudio#11246] opened 2020-07-08 14:53 UTC
Issue Type: <b>Bug</b>

Save as csv/excel or copy/paste don't include headers when saving or copying from a SQL result cell in Notebooks.

Settings are ok:

![image](https://user-images.githubusercontent.com/49344920/86934021-3669ef00-c109-11ea-9a78-93359d1be28b.png)

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
import|Mic|0.15.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by chlafreniere** [comment] 2020-07-08 20:26
This is a dupe of #11068. Let's track this work there.

**Closed by chlafreniere** 2020-07-08 20:26 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
