### ISSUE TITLE
SQL Tools Service component exited unexpectedly

### ISSUE THREAD

**Issue by ewinterrms** [Microsoft/azuredatastudio#5172] opened 2019-04-24 03:48 UTC
- Azure Data Studio Version: 1.6.0

Steps to Reproduce:

1. Open

I've just upgraded to Ubuntu 19.04

**Comment by abist** [comment] 2019-04-24 04:46
Hi @ewinterrms, thanks for reporting the issue. Could you Toggle the Developer Tools (Ctrl + Shift + I) and paste the error on the console?

**Comment by Forage** [comment] 2019-04-24 09:36
I just ran into the same problem. I'm also on Ubuntu 19.04.

![Capture d’écran de 2019-04-24 11-32-04](https://user-images.githubusercontent.com/550915/56649076-baf75b80-6684-11e9-89a1-c4425ed359f2.png)

From Ubuntu 18.10 to Ubuntu 19.04 libssl1.0 has been replaced by libssl1.1 and it is nicely installed, so there should be no reason for this error.

**Comment by Forage** [comment] 2019-04-24 09:46
Which makes this issue a duplicate of #5134

**Comment by ewinterrms** [comment] 2019-04-24 18:30
Thanks, Forage, I missed those dups, and installing libssl1.0.0 solved the problem for me:

wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb

**Comment by kburtram** [comment] 2019-04-26 17:27
Closing as a duplicate.  We'll look into the missing Ubuntu 19.04 dependencies using one of the other issues.

**Closed by kburtram** 2019-04-26 17:27 UTC
Labels: Bug
