### ISSUE TITLE
Database tables not loading in the window pain popout on the left

### ISSUE THREAD

**Issue by dspencer-hpg** [microsoft/azuredatastudio#21013] opened 2022-10-27 14:29 UTC
Issue Type: <b>Bug</b>

Add a connection to a database
click on the servers icon
click the drop down arrow

database objects don't load and timeout after 45 seconds.
it should load the server/database objects in the pop out panel

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (19.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment] 2022-11-02 06:31
@dspencer-hpg 

Do you know how many tables you have in the database? Can you find out from `sys.tables`? 
I would appreciate any more details you can provide to help reproduce the issue at our end.

**Comment by cheenamalhotra** [comment] 2022-12-08 22:23
Duplicate of #5173

**Closed by cheenamalhotra** 2022-12-08 22:23 UTC
Labels: Area - Object Explorer, Area - Connection, Needs More Info, Triage: Done
