### ISSUE TITLE
A11y_SQLAzureDataStudio_NewDeployment_SQLServerBigDataCluster_Keyboard: When selected any option from Deployment target combo box, focus moves to ‘I accept…License terms’ Checkbox

### ISSUE THREAD

**Issue by shweta255** [microsoft/azuredatastudio#9226] opened 2020-02-20 10:42 UTC
“[Check out Accessibility Insights!](https://accessibilityinsights.io/
) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”
#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#DesktopWeb;#Win10;#MAS2.4.3;#Benchmark;#A11y_SQLAzureDataStudio;#A11ySev2;

**Environment Details:**
Version: 1.16.0-insider
Commit: 506c6a5
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
Additional Details:
MAS reference: MAS2.4.3

**Repro Steps:**
1. Launch Azure Data Studio.
2. Select the Connections icon (if not already selected) from left bar.
3. Click on the ellipses '...' and select "New Deployment".
4. Select "SQL Server Big Data Cluster" card under deployment options.
5. Navigate to Deployment Target combo box using tab key and select any option.

**Actual:**
When selected any option from Deployment target combo box using Enter key, focus moves to ‘I accept…License terms’ Checkbox

**Expected:**
When selected any option from Deployment Target combo box, focus should remain at Deployment Combo box.

**User Impact:**
Keyboard only users will face difficulty to trace the current focus.

**Attachment link reference:**
[9226_A11y_SQLAzureDataStudio_NewDeployment_SQLServerBigDataCluster_Keyboard.zip](https://github.com/microsoft/azuredatastudio/files/4274910/9226_A11y_SQLAzureDataStudio_NewDeployment_SQLServerBigDataCluster_Keyboard.zip)

**Comment by alanrenmsft** [comment] 2020-03-05 07:12
dupe of https://github.com/microsoft/azuredatastudio/issues/9227

**Closed by alanrenmsft** 2020-03-05 07:12 UTC
Labels: A11y_AzureDataStudio, Area - Resource Deployment, Bug, Triage: Done

**Comment by sspatil123** [comment] 2023-02-06 10:58
**GithubTags**:#Closed;

**Comment by mstechie** [comment] 2023-03-05 19:50
GitHubTags:#SQLADS-Win32-Feb2020;
