### ISSUE TITLE
Table design changes

### ISSUE THREAD

**Issue by acohenOT** [microsoft/azuredatastudio#13782] opened 2020-12-11 15:32 UTC
**Is your feature request related to a problem? Please describe.**
I am unable to do basic table design changes

**Describe the solution or feature you'd like**
Add columns to a table
Delete columns from a table
Rename columns
Change column data types
Change column widths

**Describe alternatives you've considered**
Install SQL Server Management Studio to perform these tasks

**Comment by thecesrom** [comment] 2020-12-11 17:06
Hello, @acohenOT.

While Azure Data Studio does not provide a GUI for modifying table design, this can be achieved using T-SQL.

Here I share some options for the scenarios you've listed:
Add columns to a table: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15#a-adding-a-new-column
Delete columns from a table: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15#a-dropping-a-column-or-columns
Rename columns: https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql?view=sql-server-ver15
Change column data types/widths: https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15#alter_column

Usually I skip the *Design* GUI and write T-SQL, since the GUI not always allows "destructive" changes which can easily be done via T-SQL.

Hope this is what you were looking for.

- A fellow SQL enthusiast

**Comment by acohenOT** [comment] 2020-12-11 17:51
Perhaps Azure Data Studio can generate the T-SQL for some common commands such as these? Even through an extension would be sufficient, I think.

**Comment by drizztdourden08** [comment] 2021-02-09 19:13
Why would Azure Data Studio not provide a GUI for Table design. I know plenty of people to which I've suggestion ADS for work and they all gone back to SSMS because of this single function.

Designing table should not be relying on T-SQL. This is frequent work that people have to do and this breaks the flow. When you have a lot of design change, you got to write every single query by hand.

You have a "GUI" for editing data... Why would that be different in any way? there are ways to do this. SSMS handle it perfectly already.

I would make this a priority or at least develop an extension for this particular function as it makes ADS a no go for a lot of people.

**Comment by Geekimo** [comment] 2021-03-22 11:08
This feature is really missing since I'm developing on a Mac M1 and I can't run SSMS using parallels for example, thus I'm not really familiar with T-SQL.

**Comment by PureKrome** [comment] 2021-05-05 03:50
Further to what @drizztdourden08 said, there are already some _existing_ GUI's for things like NEW CONNECTION etc. Even REPORT BUG/ISSUE is a GUI window.

This should come as a big priority IMO. You would be surprised by the number of people who do these simple chores day in, day out. We don't really need to drop down to T-SQL for this boring stuff, especially when a GUI is a great experience for this type of work/requirements, IMO.

Please reconsider moving this up the list of priorities.

You want faster traction by users - then tackle this one.

**Comment by kburtram** [comment] 2021-09-10 22:20
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/282.  We are starting work on this feature currently and it should be available in the next several months.  Thanks!

**Closed by kburtram** 2021-09-10 22:20 UTC
Labels: Enhancement, Triage: Done, Area - Designer
