### ISSUE TITLE
Studio doesn't remember scrolling position when switching between tabs

### ISSUE THREAD

**Issue by JohnyL** [microsoft/azuredatastudio#6186] opened 2019-06-27 17:06 UTC
Issue Type: <b>Bug</b>

Studio doesn't remember scrolling position when switching between tabs. Say, the the first line in tab1 is 15. When I switch to tab2 and then to tab1 back, the first line is 1, i.e. Studio moved to the beginning of the file.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3460 @ 3.50GHz (2 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.40.0
import|Mic|0.8.0
managed-instance-dashboard|Mic|0.3.6
profiler|Mic|0.8.0

</details>

**Comment by Charles-Gagnon** [comment] 2019-06-27 17:33
Dupe of #6012 - this will be fixed in the next release

**Closed by Charles-Gagnon** 2019-06-27 17:33 UTC
