### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Recompare pop up_Screenreader: After activating the popup "Recompare" NVDA announces "Option button first".

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6663] opened 2019-08-09 12:09 UTC
“[Check out Accessibility Insights](https://accessibilityinsights.io/)! - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS; #A11yTCS; #A11y_ADS_Schema_Dacpac_Backup; #Azure Data Studio; #DesktopApp; #Win10; #MAS2.4.2; #MAS1.3.2; #NVDA; #Jaws;

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Additional Details:**
Screen reader  : NVDA 2019.2.rc2, Jaws
MAS reference: MAS2.4.2 MAS1.3.2

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Options menu from Schema compare Menu bar & hit enter.
12. Check or uncheck some options & hit Ok.
13. Validate Re compare pop will open
14. Start NVDA and check how it read the information.

**Actual:**
After activating the popup "Re-compare" NVDA reads the information as "Button Options warning Option has changed..." which is not correct.

Same issue is observed with Jaws

**Expected:**
After activating the popup nvda should read the information as "Options has changed ….. Dialog/Alert/Popup "

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screen reader user will not know the information about the dialog.

**MAS Reference:**
MAS2.4.2:[https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={c74ff881-82b6-4401-92cf-8919f9bffaf2}](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={c74ff881-82b6-4401-92cf-8919f9bffaf2})

 MAS1.3.2:[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4})

**Attachment for Reference:**
![6663_ Accessibility A11y_AzureDataStudio(Schema,Dacpac,Backup)_Recompare pop up_Screenreader](https://user-images.githubusercontent.com/24580570/62777993-c607b780-bacc-11e9-9118-f0b595198d75.png)

**Comment by udeeshagautam** [comment] 2019-08-19 20:07
This is caused by the fact that focus of vscode goes to main window even after toast notif opens- https://github.com/microsoft/azuredatastudio/issues/6661

**Comment by hannahqin** [comment] 2019-09-13 17:42
Reopening and reassigning to @fsteffi as per the [Accessibility External Bug Process](https://microsoft.sharepoint.com/teams/ceacc/SitePages/External-Bug-process.aspx). @fsteffi, this is an upstream issue from VS Code. Per the instructions in the External Bug Process, can you file this bug with vscode and track it there? https://github.com/microsoft/vscode/issues

This issue is related to #6661. The same fix would likely solve both issues.

**Comment by hannahqin** [comment] 2019-09-13 17:43
Reopening and reassigning to @fsteffi as per the [Accessibility External Bug Process](https://microsoft.sharepoint.com/teams/ceacc/SitePages/External-Bug-process.aspx). @fsteffi, this is an upstream issue from VS Code. Per the instructions in the External Bug Process, can you file this bug with vscode and track it there? https://github.com/microsoft/vscode/issues

This issue is related to #6661. The same fix would likely solve both issues.

**Comment by hannahqin** [comment] 2019-09-23 22:21
Marking this for Exclusion. @fsteffi, please work with a SME to review.
https://microsoft.sharepoint.com/teams/ceacc/SitePages/External-Bug-process.aspx

**Importance of Experience:** minimal
Schema compare feature is an extension, not part of ADS core, thus does not affect all users. The re-compare pop-up is also not a critical experience for schema compares; it provides a convenient way to execute a Compare after modifying options, but the same could be achieved by directly selecting "Compare" without the need for the pop-up.

**Quality of Experience:** manageable
Screen reader users may be slightly confused about the state of the screen when the re-compare popup appears. However, the popup is not necessary to the scenario. Simple workaround: After modifying options, instead of accessing the pop-up, users can directly select "Compare" to recompare.

**AAT Conformance Doc:** https://cela-ra-aat-prod.azurewebsites.net/#/workflow/ee5c9007-47f4-4fcb-a4d7-a998a617edde?tab=default
**External Remark:** For users who have installed and are using the Schema Compare extension, when the user executes a Compare and then modifies Options, a toast notification element is displayed, which is not read in the correct order by screen readers. The screen reader will first re-read the Options button before reading information in the notification, which is unrepresentative of the true state of the screen.

**Comment by fsteffi** [comment] 2019-09-26 11:39
@hannahqin we have logged external bug : https://github.com/microsoft/vscode/issues/81484

**Comment by hannahqin** [comment] 2019-10-21 21:32
This was re-filed with vscode as microsoft/vscode#81787

**Comment by kenvanhyning** [comment] 2019-11-07 17:52
Closing as upstream

**Closed by kenvanhyning** 2019-11-07 17:52 UTC
Labels: A11yExclusion, A11yMAS, A11y_ADS_Schema_Dacpac_Backup, Area - Schema Compare, Bug, External: VSCode, Impact: Accessibility, Triage: Done, Upstream

**Comment by Alexandria-R** [comment] 2019-11-21 20:12
Not approved, as this is an improper use of toast and was not acknowledged by the external party.

**Comment by hannahqin** [comment] 2019-11-21 21:58
@Alexandria-R The VSCode (external) team is saying that they do not think toast notifications should steal focus, and that we should use a large modal dialog if we want focus to shift immediately. 

We are using toast notifications as expected according to VSCode's documentation and believe that it's the best user experience to use a toast notification in these cases instead of a modal dialog. However, we don't have control over where focus moves when the toast notification pops up, as described in this issue filed by @fsteffi. 

Assuming that we are using toast notifications as VSCode intends, which we are, and you believe that the current behavior of screenreader focus is an accessibility issue, then this needs to be taken up with the VSCode team. We unfortunately do not have control over this.

Same comment left in https://github.com/microsoft/azuredatastudio/issues/6661
