### ISSUE TITLE
Messages pane steals focus from query editor

### ISSUE THREAD

**Issue by SledgeHammer01** [microsoft/azuredatastudio#6247] opened 2019-07-02 20:12 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. Execute query such as: DELETE * FROM myTable
2. Observe Messages pane stole focus from the query editor
3. Results pane does not steal focus

Expected Behavior:

Messages pane should not steal focus.

**Comment by Charles-Gagnon** [comment] 2019-07-02 20:59
Dupe of #5926 - this was unfortunately a bug that made it into the last release. The next release will have a fix - in the meantime you can use the Insiders Builds if this is a blocking issue for you.

**Closed by Charles-Gagnon** 2019-07-02 20:59 UTC
Labels: Bug
