### ISSUE TITLE
Feature Request: Make saving query result to Excel/JSON/text directly

### ISSUE THREAD

**Issue by JohnyL** [microsoft/azuredatastudio#234] opened 2017-11-28 18:49 UTC
Feature Request: Make saving query result to Excel/JSON/text directly, i.e. without showing them in "Results" pane - by selecting the text of the query and using the context menu.

**Comment by alanrenmsft** [comment] 2020-11-03 18:26
dupe of https://github.com/microsoft/azuredatastudio/issues/86, I added a upvote over there

**Closed by alanrenmsft** 2020-11-03 18:26 UTC
Labels: Area - Query Editor, Enhancement
