### ISSUE TITLE
App folder for MacOs has incorrect created date: Currently 12/31/1979

### ISSUE THREAD

**Issue by ptc-cjm** [microsoft/azuredatastudio#14818] opened 2021-03-22 16:02 UTC
- Azure Data Studio Version: 1.27

Steps to Reproduce:

1. Unzip deliverable package.
2. Examine Date Created property of parent App folder.

**Comment by abist** [comment] 2021-03-22 16:13
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/12787

**Closed by abist** 2021-03-22 16:13 UTC
