### ISSUE TITLE
Can not connect after changing Microsoft password

### ISSUE THREAD

**Issue by lioras** [microsoft/azuredatastudio#17836] opened 2021-12-07 17:58 UTC
Issue Type: <b>Bug</b>

Keep getting a token retrieval error even though I have reauthenticated. 

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:25:54.683Z)
OS version: Darwin x64 18.7.0

Extensions: none

**Comment by cssuh** [comment] 2021-12-07 19:35
Hi @lioras, is this for an Azure SQL DB?  Have you tried removing your Microsoft account and then re-adding it?

**Comment by cssuh** [comment] 2022-02-01 19:12
this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/12637

**Closed by cssuh** 2022-02-01 19:12 UTC
Labels: Bug, Area - Azure, Triage: Needed
