### ISSUE TITLE
SSMS Integration with SQL Auth Connections

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#13108] opened 2020-10-28 16:21 UTC
- Azure Data Studio Version:
Version: 1.23.0 (system setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

- SSMS version 18.7.1

Steps to Reproduce:

1. Connect to a SQL server or Azure SQL DB with SQL authentication in SSMS
2. Use the Azure Data Studio integration option for new query or new notebook
3. get error message on connection in Azure Data Studio 

"Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass45_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 549
ClientConnectionId:8db86d2b-fb2c-428e-960a-2333b08fbe15
Error Number:18452,State:1,Class:14"

**Comment by dzsquared** [comment] 2020-10-28 16:43
previously broken and fixed - https://github.com/microsoft/azuredatastudio/issues/11230

**Comment by Charles-Gagnon** [comment] 2020-10-28 18:26
@dzsquared Could you attach a gif/video of this? I'm not able to repro this with SSMS 18.7.1 and ADS 1.23

**Comment by dzsquared** [comment] 2020-10-28 20:36
@Charles-Gagnon 
![integration-login](https://user-images.githubusercontent.com/12227241/97493630-7e17bf00-1922-11eb-834c-0cc1cef4fc23.gif)

**Comment by Charles-Gagnon** [comment] 2020-10-28 21:03
Just to check - is ADS closed when you launch the command or was it previously opened? If it was open can you try closing it and then launching the command to see if it works? Can you use process explorer and get the command line parameters passed to ADS? https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer Should look something like this

![image](https://user-images.githubusercontent.com/28519865/97496446-2e3af700-1926-11eb-9984-ed911a7a39a0.png)

**Comment by dzsquared** [comment] 2020-10-29 02:25
![image](https://user-images.githubusercontent.com/12227241/97517679-e4b4d100-1952-11eb-956b-36405c8c8f58.png)

![image](https://user-images.githubusercontent.com/12227241/97517871-4bd28580-1953-11eb-8d08-87e753577ec3.png)

**Closed** 2020-10-30 15:19 UTC
Labels: Area - SSMS Integration, Bug, Triage: Needed

**Comment by Charles-Gagnon** [comment] 2020-10-30 20:24
@dzsquared Can you try again with the latest insiders to see if the issue is resolved with Amir's fix?

**Comment by dzsquared** [comment] 2020-11-02 20:29
@Charles-Gagnon  and @aaomidi - works great, thanks!

Version: 1.24.0-insider (system setup)
Commit: 338beaff29228fd1b1fd177a6bc270f37d53d69c
Date: 2020-11-02T06:36:02.847Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
