### ISSUE TITLE
column names reapeated in  exported csv data in row 500

### ISSUE THREAD

**Issue by cristobalsarome** [microsoft/azuredatastudio#13563] opened 2020-11-27 13:58 UTC
Issue Type: <b>Bug</b>

when I export a query result with more than 500 rows as csv, the column names appear at the begining (which is fine) but also appear repeated in row 500 wich is very annoying. It took me a lot of time to understand why my process was failing

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (11.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by katjakoka** [comment] 2020-11-29 15:18
The same problem here. I extracted 1600 rows and the column names appeared in six lines!

**Comment by katjakoka** [comment] 2020-11-29 16:05
As fyi btw, I though initially that those lines with column names are added extra BUT those lines with columns names SUBSTITUTE the real records actually. This leads to a data loss.

**Comment by lucyzhang929** [comment] 2020-11-30 14:51
Hi @cristobalsarome @katjakoka, is this issue being run into in notebooks? If so, I will close this issue as a duplicate of this one https://github.com/microsoft/azuredatastudio/issues/13562

**Closed** 2020-11-30 15:22 UTC
