### ISSUE TITLE
SQL 2019 Book Shouldn't Be Opened as Provided Book

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#13256] opened 2020-11-05 20:14 UTC
SQL 2019 book is broken when it's opened in the Provided Books view due to pathing issues. Have heard strong feedback that we need to make the experience much more seamless, as users are running into this problem daily.

**Comment by barbaravaldez** [comment] 2020-11-10 21:14
This issue is caused by #12357

**Comment by Charles-Gagnon** [comment] 2022-12-06 23:22
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.

**Closed by Charles-Gagnon** 2022-12-06 23:22 UTC
Labels: Bug, Area - Notebooks, Triage: Done, Subarea - BDC/Spark
