### ISSUE TITLE
It is impossible to create backup

### ISSUE THREAD

**Issue by IgorGutsaev** [Microsoft/azuredatastudio#4572] opened 2019-03-17 21:38 UTC
Issue Type: <b>Bug</b>

It is impossible to create backup- 'Backup type' combo box is empty. Backup button doing nothing.

Steps to reproduce:
1. Start backup task
2. Fill 'Backup name'
3. Set 'Backup type'
4. Add 'Backup files'
5. Press 'Backup'

Expested: created backup
Reality: no activity

![export](https://user-images.githubusercontent.com/13364181/54498255-14e26400-4916-11e9-8a1e-2b2f7724bcaf.png)

Azure Data Studio version: **azuredatastudio 1.4.5** (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2120 @ 3.10GHz (2 x 3116)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.95GB (7.77GB free)|
|Process Argv|C:\Users\igor.gutsaev\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MattIrv** [comment] 2019-03-18 18:25
I think this is a duplicate of #4471. Backup for Azure SQL DB isn't supported inside of Azure Data Studio right now but a bug made it possible to open the backup dialog. It should be fixed in version 1.5.1 that we just released.

If you want to backup your Azure SQL DB instance we recommend using the Azure Portal.

**Closed** 2019-03-18 18:25 UTC
Labels: backup, bug, duplicate
