### ISSUE TITLE
Error to create new firewall rule

### ISSUE THREAD

**Issue by eternalbard** [microsoft/azuredatastudio#4182] opened 2019-02-26 01:06 UTC
Issue Type: <b>Bug</b>

Sometimes when I need to create a new firewall rule due to dynamic IP changes, and sometimes I get the message "An error occurred while creating a new firewall rule."

The only way it passes (but I'm not sure if always) is to restart Azure Data Studio.

On old Sql Operations this error was more common to happen.

Thanks.

Azure Data Studio version: Azure Data Studio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:09:15.672Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|19, 11, 8|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.5.0

</details>

**Comment by aaomidi** [comment] 2020-05-06 20:51
I'll close out this issue for now. Please comment back if you've seen this behavior recently and I'll reopen the issue.

**Comment by EkimoCode** [comment] 2021-06-01 09:43
@aaomidi the issue is not solved as today

**Comment by Charles-Gagnon** [comment] 2021-06-02 21:17
@cssuh @kburtram FYI

@EkimoCode Could you verify the version of ADS that you're seeing this with?

**Comment by martinleo666** [comment] 2021-07-04 06:55
This Bug still exists. Very annoying. Most often occurs when the studio wasn't used for a while. An app restart always helps. If I had to guess, I'd say some kind of token has expired.

Date: 2021-06-16T18:57:01.467Z (2 wks ago)
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.5.0

**Comment by kburtram** [comment] 2021-10-15 19:13
@caohai could you please investigate if this is related to an expired token?  If it is, could you please include this use case in the various token refresh bugs you're fixing?  Thanks!

**Comment by cheenamalhotra** [comment] 2023-05-08 17:53
Closing as when making a request to create firewall rule, an active token is ensured.
If issue occurs again, please open a new issue to investigate.

**Closed by cheenamalhotra** 2023-05-08 17:53 UTC
Labels: Bug, Area - Azure, Pri: 2, Triage: Done, Size: M
