### ISSUE TITLE
Memory Leak - MicrosoftSqlToolsServiceLayer

### ISSUE THREAD

**Issue by nige6** [microsoft/azuredatastudio#5101] opened 2019-04-18 10:46 UTC
Opening ADS and then opening a sql file [of a SP] containing 1400 lines (51 kb file size), results in memory usage of MicrosoftSqlToolsServiceLayer growing from a few Mb to over 5Gb  - just from opening the file !

Alternatively open the file in notepad++ and copy and paste the sql into a new tab results in the same.

Eventually after several (5+) minutes memory returns to normal (a few Mb)
Even closing the file does not restore the memory for several minutes

so some kind of parsing of the sql ? 
SSMS and VS2019 also experience high memory usage but not to the extreme of ADS

is there some way to disable whatever this is using e.g. a parser until needed ?

**Comment by cheenamalhotra** [comment] 2023-08-24 22:15
It seems related with database metadata that is loaded by language service.
Have you tried disabling intellisense?

<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/f7442f93-794d-40ef-ad4b-715a87c0ebd4" width=500 />

**Comment by cheenamalhotra** [comment] 2023-08-24 22:19
Either way I will close it as duplicate of https://github.com/microsoft/azuredatastudio/issues/5101 - please track the same for more updates on the same.

**Closed by cheenamalhotra** 2023-08-24 22:19 UTC
Labels: Bug, Area - Language Service, Needs More Info, Impact: Reliability
