### ISSUE TITLE
Designer to create tables

### ISSUE THREAD

**Issue by michaelnemtsev** [Microsoft/azuredatastudio#1712] opened 2018-06-22 02:21 UTC
Issue Type: <b>Feature Request</b>

Hello,

it would be great to have a designed extension to create tables. Otherwise only Visual Studio provides this capability

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

**Comment by ScottRFrost** [comment] 2018-06-22 14:35
At least a copy of the Right click table > Design UI from SSMS would be nice.

Same for right click table Keys > New Foreign Key, right click table Indexes > New Index, etc.

**Comment by webprofusion-chrisc** [comment] 2018-06-27 02:57
This would really make the different between being a query tool and being a database development IDE. The feature is very complex though as it's really many features under one concept.

Based on similar tools in the past, you need;
- A layout engine for overall table layout in a diagram, based on table key relationships. The layout needs to be printable, zoomable and likely needs a thumbnail view for navigation.
- Drag/drop relationship creation, relationship property design UI
- Table design UI (add/remove fields, data type options, data type specific UI, metadata editor)
- Scripting and application of resulting changes

I'd estimate one developer could reasonably expect to spend about 6-9 months building a good v1 of this type of feature.

**Comment by kburtram** [comment] 2018-11-14 01:15
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/282.  Thanks!

**Closed by kburtram** 2018-11-14 01:15 UTC
Labels: suggestion
