### ISSUE TITLE
Unable to close tab after connection deletion

### ISSUE THREAD

**Issue by martindlarsson** [microsoft/azuredatastudio#14495] opened 2021-03-02 13:42 UTC
- Azure Data Studio Version: 1.26.1

Steps to Reproduce:

1. Created a new connection to a database and saved it with a name under connections
2. Right clicked on it and clicked Manage. A new tab appears with objects
3. Right click on the connection and delete it
4. I am now unable to close the "Manage"-tab. Needed to restart the client to get rid of the tab.

**Comment by alanrenmsft** [comment] 2021-04-01 18:19
not able to reproduce the issue.

**Comment by kburtram** [comment] 2021-08-18 23:15
Closing based on previous comment and lack of current repro.  Please let us know if you're still impacted by this issue.

**Closed by kburtram** 2021-08-18 23:15 UTC
Labels: Bug, Area - Dashboard, Triage: Done, Needs Logs
