### ISSUE TITLE
Files don't open properly

### ISSUE THREAD

**Issue by mpb9980** [microsoft/azuredatastudio#16463] opened 2021-07-28 15:23 UTC
Issue Type: <b>Bug</b>

Since I upgraded to this version, files that I open or save do not render properly.  When I create a new notebook or SQL file it looks and works properly.  

If I save a SQL file then it the button bar that allows me to connect the file to a database and execute it.  Otherwise it displays the SQL text and I can continue to edit and save.  

If I save a new notebook then it changes to JSON text.  

Opening a saved file behaves the same as saving a new one.  

Azure Data Studio version: azuredatastudio 1.31.0 (a430fd2592763ef4c4a406821967e4b7b2b3d876, 2021-07-20T19:43:31.605Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2021-07-28 15:38
Duplicate of https://github.com/microsoft/azuredatastudio/issues/16436, see that for instructions on getting a fixed version while we work on getting a hotfix out for this.

**Closed by Charles-Gagnon** 2021-07-28 15:38 UTC

**Comment by mpb9980** [comment] 2021-07-28 16:49
Thank you Charles!


Mike Bunce
Software Engineer
(585) 354-2901
