### ISSUE TITLE
More assets - App icon looks like Winforms app

### ISSUE THREAD

**Issue by Ryukote** [microsoft/azuredatastudio#857] opened 2018-03-07 07:37 UTC
Can you bring more assets to SQL Ops Studio? For example, app icon looks like it is about some Windows Forms app and I would like to see options to chose like something that looks like VS Code app icon. I know this is something based on personal opinion, but I am in believe I am not the only one who would like this.

**Comment by kburtram** [comment] 2018-03-07 15:44
@Ryukote  Just checking if you're seeing the below icon in the application title bar?  Sometimes the default Windows app icon is shown instead and you'd need to clear the Windows icon cache to get the actual app icon.  If you don't see the below app icon please follow the `Rebuilding the Icon Cache Database Manually` steps at http://www.winhelponline.com/blog/how-to-rebuild-the-icon-cache-in-windows, for example.

If you are seeing the below app icon then I'll pass this feedback on to our UX designer.  Thanks!

<img width="46" alt="screen shot 2018-03-07 at 7 39 43 am" src="https://user-images.githubusercontent.com/599935/37101582-c70f6f4c-21da-11e8-8cb9-636334e3ad92.png">

**Comment by Ryukote** [comment] 2018-03-07 20:41
Yes I am seeing this icon. Thank you.

**Comment by kburtram** [comment] 2018-03-08 05:18
@Ryukote thanks for confirming.  We'll discuss this icon in our next weekly bug triage meeting.  The icon came from our branding team to align with the current generation of SQL Server marketing materials.

**Comment by philoushka** [comment] 2018-03-25 00:47
Further on the icon, its misaligned or off-centre when compared to others in the Dock.

1. The bottom of the icon sits too low. It droops down further than any other Dock icon. See the white line drawn.

2. It's not centered - it is too far to the left, or _appears_ too far to the left. See the Dock's open dot indicator.

![image](https://user-images.githubusercontent.com/930731/37870448-492d1728-2f8b-11e8-899c-d5fe0f64b6d0.png)

**Comment by kburtram** [comment] 2020-02-21 02:12
Closing as "by design"  Our UX and marketing teams have provided our current icon set and control our branding.  Thanks for opening this suggestion!

**Closed by kburtram** 2020-02-21 02:12 UTC
Labels: Enhancement
