### ISSUE TITLE
Filter in database hierarchy

### ISSUE THREAD

**Issue by RobinDelage** [microsoft/azuredatastudio#16510] opened 2021-07-31 09:20 UTC
**Is your feature request related to a problem? Please describe.**
There is no possibility to filter in the database hierarchy.
So if you have a lot of objects you can not find it with a filtering.

**Describe the solution or feature you'd like**
It could be great to add Filter capabilities like in SSMS

**Comment by Charles-Gagnon** [comment] 2021-08-01 00:00
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12932

**Closed by Charles-Gagnon** 2021-08-01 00:00 UTC

**Comment by Charles-Gagnon** [comment] 2021-08-01 00:02
While the sidebar list doesn't support filtering currently you can use the dashboard (right click on server -> Manage) to search for databases

![image](https://user-images.githubusercontent.com/28519865/127755047-9459fe79-f586-4d4a-a8ba-b81dd48d2812.png)
