### ISSUE TITLE
Missing index recommendation script is incorrect

### ISSUE THREAD

**Issue by AaronBertrand** [microsoft/azuredatastudio#19273] opened 2022-05-03 20:01 UTC
- Azure Data Studio Version: 1.35.1
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. Run this SQL:

```
USE tempdb;
GO
SET SHOWPLAN_XML OFF;
GO
SET NOCOUNT ON;
DROP TABLE IF EXISTS dbo.tablename;
GO
CREATE TABLE dbo.tablename
(
  name     varchar(128),
  division varchar(128),
  source   varchar(128)
);
GO 

INSERT dbo.tablename(name, source, division) VALUES
('host1', 'comp',   'abc'), ('host2', 'manual', 'xy'),
('host3', 'comp',   'zyx'), ('host3', 'manual', 'zyx'),
('host2', 'manual', 'xy');
GO
INSERT dbo.tablename SELECT * FROM dbo.tablename;
GO 20
SET SHOWPLAN_XML ON;
GO

SELECT name, division  
FROM dbo.tablename
WHERE source in ('comp', 'manual')
GROUP BY name, division
HAVING COUNT(DISTINCT source) > 1;
```

2. Click on the Missing Index text in the query plan produced under the Query Plan (Preview) tab. The resulting script looks like this:

```
...
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[tablename] ([source])
INCLUDE ([source],[division])
GO
```

This is incorrect, as it includes `source` instead of `name`. Here is what the (correct) XML shows (also I don't see the same symptom in SSMS):

```
    <MissingIndex Database="[tempdb]" Schema="[dbo]" Table="[tablename]">
      <ColumnGroup Usage="INEQUALITY">
	<Column Name="[source]" ColumnId="3">
	</Column>
      </ColumnGroup>
      <ColumnGroup Usage="INCLUDE">
        <Column Name="[name]" ColumnId="1">
        </Column>
        <Column Name="[division]" ColumnId="2">
        </Column>
      </ColumnGroup>
    </MissingIndex>
```

**Comment by erinstellato-ms** [comment] 2023-08-30 21:36
@AaronBertrand FYI that I'm closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/20249.  Your issue was entered first :) but there's a bit more info on the other issue.  Will link to this issue from the other so your demo code is available if needed.

**Closed by erinstellato-ms** 2023-08-30 21:36 UTC
Labels: Bug, Area - Query Editor, Triage: Done, Subarea - Execution Plan, Duplicate
