### ISSUE TITLE
Incorrect login user is remembered and cannot be removed

### ISSUE THREAD

**Issue by IanKemp** [microsoft/azuredatastudio#8331] opened 2019-11-14 11:24 UTC
Issue Type: <b>Bug</b>

My employer has an Azure SQL DB. Originally, all devs connected to this DB using a shared SQL login named "Developer". Later policies were improved and each dev was assigned their own SQL login (mine is called "ian") and the Developer login's password was changed.

When I first connected to Azure SQL using ADS, I used the Developer login and ticked the "Remember password" box. But since I now have to use my own account, I login with ian and my own password, again choosing to have my credentials remembered.

The bug: ADS only remembers the Developer login, not ian. Which means that **every time** I try to connect to the DB, I am told "login failed for user Developer" and have to type in my ian login.

Second part of the bug: When I type ian in the login box, the password that was supposedly remembered is not filled in.

This is... **extremely** annoying, to say the least.

SQL Server Management Studio gets this right:

1. It actually remembers all login/password combinations and allows you to select a login via a dropdown, which auto-fills the saved password for that login.
2. It allows logins to be updated or removed via the login dialog, as well as via Windows Credential Manager.

Login functionality is really the absolute most basic feature of any app that you need to have 100% working before you even consider shipping an alpha, and the fact that it doesn't Just Work in ADS is incredibly disappointing. This sort of lack of quality is something I'd expect from a startup, not a multibillion-dollar company like Microsoft. I don't mind testing your software for you, I do mind when it doesn't work any better than the software that already exists (SSMS).

Simplest fix: tell me where/how I can delete saved credentials from ADS. I'd prefer to only delete the Developer login, but if the only option is getting rid of all of them, I can handle it.

Better fix: make the damn login functionality work like it should.

Best fix/feature request: some sort of UI to view all credentials grouped by DB server, with the option to add, remove and set a specific login as default.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
profiler|Mic|0.9.0

</details>

**Comment by IanKemp** [comment] 2019-11-14 11:28
I didn't know about the linked issues so this one could be considered a dupe, but seriously - those issues have been sitting around for literally **months** without any work being done on them.

I'll say it again, login functionality is a basic thing that needs to work 100% before you ship a product. And if it doesn't work, you need to fix it fast. That's not happening, which leads me to question whether there is any reason to use ADS.

**Comment by Charles-Gagnon** [comment] 2019-11-15 19:21
@IanKemp We don't support modifying existing connections at this time. If you delete the connection and then reconnect with the new username does it still not save correctly?

**Comment by kburtram** [comment] 2019-11-18 21:28
@IanKemp the Connection metadata is in the User Setting, which can be reached from the `Open Settings (JSON)` command in the Command Palette (available from F1).  In the JSON file you should be able to directly modify the username for the connection.  Thanks for reporting this bug.

**Comment by IanKemp** [comment] 2019-11-20 11:24
> @IanKemp the Connection metadata is in the User Setting, which can be reached from the `Open Settings (JSON)` command in the Command Palette (available from F1). In the JSON file you should be able to directly modify the username for the connection. Thanks for reporting this bug.

The connection metadata under the "Servers" section, yes. But connections under "Azure" are the problem here, and I can't figure out where *that* metadata is living.

**Comment by ransagy** [comment] 2019-12-16 11:43
I've been suffering from this quite a while; Even uninstalling, cleaning up everything and reinstalling doesn't seem to make this go away completely.

**Comment by drjwelch** [comment] 2020-10-06 08:27
This is still a problem and as the OP mentioned is VERY annoying!

Steps to reproduce
-Open ADS, login to your Azure SQL db with admin username/password, check "save password"
-Login using AD auth
-Change the admin password on the db
-Delete all connections and user information in the JSON described above; remove the cached token file for AD auth
-Uninstall and reinstall ADS
-Open ADS, connect to Azure SQL db with AD auth again
-Expand another db object
Expected: the object explorer expands the object
Actual: login error for username of db admin account

Where are those creds stored so we can remove them?

**Comment by ImrePyhvel** [comment] 2020-10-30 13:20
Just tried to give the product a second try and spent an hour trying to force it to remember that I want to authenticate with Azure AD with MFA. **I could not.** I removed everything from GUI, cleared connections and recent connections, cleaned the settings.json, restarted the app, used auto-discover to connect to Azure databases without  explicit connectionstrings ... and STILL **it magically tries to connect with ancient and no longer valid sql user**. And fails. Every time I start the client I have to go click around to change auth type. For every DB. Every time.

**Get a grip and wipe the magic cache!**
Or overwrite the cache on successful connection. 
Or clear auth cache on auth fail. 
Or offer a magic "reset cache" button. 
Or .. Everything is better than the current state..

**Comment by IanKemp** [comment] 2020-10-30 13:27
> Just tried to give the product a second try and spent an hour trying to force it to remember that I want to authenticate with Azure AD with MFA. **I could not.** I removed everything from GUI, cleared connections and recent connections, cleaned the settings.json, restarted the app, used auto-discover to connect to Azure databases without explicit connectionstrings ... and STILL **it magically tries to connect with ancient and no longer valid sql user**. And fails. Every time I start the client I have to go click around to change auth type. For every DB. Every time.
> 
> **Get a grip and wipe the magic cache!**
> Or overwrite the cache on successful connection.
> Or clear auth cache on auth fail.
> Or offer a magic "reset cache" button.
> Or .. Everything is better than the current state..

It's pretty obvious that the current Azure Data Studio dev team is clueless and should not be allowed anywhere near code, but someone high up at Microsoft has ADS as a pet project and they don't care about its quality, they're merely concerned with foisting it on as many customers as possible (the latest version of SSMS bundles ADS with it with no option to avoid installing it).

All we can do is avoid this broken piece of trash and continue to use SSMS - until, of course, the powers that be at MS decide to make its features stop working in the name of "deprecation" or "unsupported" to force people to use this rubbish called ADS.

**Comment by gitdrk** [comment] 2020-11-05 20:54
I had a similar issue after a password reset and found this work around. I am on the latest version as of this post.\

- Hit F1 
- Select "Azure: Sign in"
- Removed the linked account.
- Add the account back.

It looks like ADS was caching the token and even thought my PW had changed and I had tried to refresh the token it would fail to use the new info.

**Comment by ESTOCKY** [comment] 2020-11-27 19:10
I'm having the same issue as @IanKemp and others with Azure SQL connections.  Under CONNECTIONS / SERVERS, I am able to manually add an Azure SQL connection to a server/database.  However, under CONNECTIONS / AZURE, when I attempt to connect to server/databases (that I have access to with my Azure AD account), I get 'Connection Error Login failed for user '<sqladmin account>'.  To be clear <sqladmin account> is the Server admin account for the Azure SQL Server, and I have used that account before, but we have a need to use Azure AD accounts now and not SQL logins.

I am using ADS 1.24.0 and have uninstalled and reinstalled twice, manually removing my Roaming user data.  Any ideas how to remove the cached user logins?

**Comment by drizztdourden08** [comment] 2021-03-08 18:46
@gitdrk Only your solution actually brought some light to this.

It is incredible the number of issue this app have that they just don't care to fix. I have been on multiple post for different issues and it's always the same answer and months old stuff in backlog. In the meantime, they add functionality that nobody cares about except them.

If only they'd give the same attention to ADS that VsCode have, it would be awesome by now. But no... basic stuff and functionality are ignored. It made me laugh to read "We don't support modifying existing connections at this time."... How the hell do you not support such basics stuff. I think it's been added since then but still... managing login IS BASICS.

**Comment by JoshPorterFKH** [comment] 2021-04-07 12:47
+1 for this being a ridiculous defect.  I can reproduce and it causes me to close ADS in frustration every few months when I attempt to use it again.  Come on MS.

**Comment by mcetkovsky** [comment] 2021-04-16 06:41
I've found a partially workaround - instead of using the Connections tree to open tabs for querying or editing tables, use the list of tables shown after you right click the database and choose Manage. That way you need to go through trigger the "login failed" prompt just unce - after clicking on Manage while opening tabs for tables goes without prompts.

**Comment by adriennn** [comment] 2021-05-05 07:07
th still doesn't work, the issues reappears after MFA login needs to be update (e.g. after 14 days period has ended for mfa credentials). My setup is several AAD in different tenants.

I have now found the actual fix for this bug: Even if you delete an AAD account from the "Accounts" view, **it doesn't actual remove the account**, you need to remove the account from this view as well:

![image](https://user-images.githubusercontent.com/7082644/117106970-7cbfc700-ad89-11eb-89e8-9d2a243f0a1f.png)

**Comment by ImrePyhvel** [comment] 2021-06-22 10:53
Problem still reproducible in 1.130. ADS still not usable.

It pops the error with the ghost sql failed login every time I try to connect to db + every time I open a query window + every time I try to edit a table, etc. When I change to Azure AD+MFA, that one operation succeeds, except "edit table" which keeps on failing.

Is there anyone actually supporting this App? 

**Dear ADS dev, I know it may be hard to fit ton of bugs into a release, but at the very least DO provide a manual workaround how to clear the cache!**

**Comment by Lintonen** [comment] 2021-08-20 15:17
The issue appears to be with Credential Manager. A coworker had to use my machine and it caused this issue even though he didn't use ADS at any point. Despite that, I did a full Revo uninstall of ADS and it didn't resolve the issue. After I cleared all traces of his creds from the Credential Manager though, ADS is now logging in under my account again.

**Comment by ImrePyhvel** [comment] 2021-09-03 11:58
No fix for me. My ever-returning SQL credential is not found in Credential Manager.

**Comment by JoshPorterFKH** [comment] 2021-09-03 12:54
Same.  This product is unusable and we're not rolling it out here.  SSMS forever (I guess)...

**Comment by drizztdourden08** [comment] 2021-09-03 13:04
How is this not a priority by now?! ADS could be so much better for daily if only the basics stuff was resolved.

**Comment by Lintonen** [comment] 2021-09-03 13:18
What type of authentication are all of you using? It sounds like all three have had this issue at this point.

**Comment by kburtram** [comment] 2021-09-03 16:41
I'd like to investigate this issue today.  Reading through the discussion I see several different bugs being discussed, in the Servers view and in the Azure view (which have different default credential behavior).  And using Azure Accounts with AAD and with changing SqlLogins.  I'll run through some of use cases and try to repro what is discussed.

Could someone who is currently impacted by this issue please provide summary repo steps of the specific bug they are facing?  Thanks!

**Comment by JoshPorterFKH** [comment] 2021-09-03 17:24
1. Log into a PaaS db using SQL authentication
2. SQL auth credentials are the default for all new SQL connections.  When clicking on an object in the Azure explorer, you get an authentication failed.  

This has been happening to me for months now.  I have done everything short of blowing away my profile.

Here is the output from copy details on the error:

Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user ''.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass47_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 312
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 557
ClientConnectionId:4f0e1097-6200-473a-87f4-f9b482b10f26
Error Number:18456,State:1,Class:14

**Comment by kburtram** [comment] 2021-09-03 17:53
@JoshPorterFKH thanks for the details.  I believe the problem with the Azure view was we don't know the credentials for each of the databases in a user's subscription.  We defaulted to SqlLogin auth since it's still much more common than AAD.  It sounds like the logic to cache database passwords isn't working correctly.  I'll take a look.

**Comment by mcetkovsky** [comment] 2021-09-03 18:05
I am logged in via AAD. In Connections - Azure, I expand the account, the subscription, SQL database. After I try to expand a database or right click and choose Manage, I get login failed mentioning an SQL Login user name (see the stack trace below). I need to change Authentication type from SQL Login to AAD to proceed.

If I manage to get into a Manage page, I am free to right click the tables and choose either Select or Edit without needing to go through the login failed process. However, doing the same through the Connections pane, results in the login failed messages.

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user ''.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass47_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 312
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 555
ClientConnectionId:9033356d-8573-4949-a549-c2b24b64766c
Error Number:18456,State:1,Class:14
```

**Comment by kburtram** [comment] 2021-09-03 18:56
@mcetkovsky thanks adding that context.  It sounds likely to be a different bug than what is observed in the Azure view, though it does match up with the issue title.  I'll investigate that a bit too, but may move that bug into a separate issue.

**Comment by kburtram** [comment] 2021-09-04 03:29
@JoshPorterFKH this PR https://github.com/microsoft/azuredatastudio/pull/16999 changes the default auth type to AzureMFA for Azure connections, and makes the default configurable.  If MFA fails the connection dialog will pop-up and you can specify a SqlLogin.

@mcetkovsky I'll move your comment to a new issue since it's not related to the Azure viewlet.

For a little more context on the Azure viewlet and the credential issues there, the main issue is that the Azure account will not necessarily (and often won't) have permissions to login into all the databases in subscriptions their account is a part of.  We choose SqlLogin as the default option for Azure connections since that was much more common login type for SQL DBs.  The problem is that we don't retain connection credentials for connections from the Azure viewlet, that is what the Servers viewlet is for, so those SqlLogins would need to be reentered every time.  The thinking being if the database was accessed often it would be saved into the Servers viewlet using the little "Connect" icon next to the database node.

There is an "optimization" that if there happens to be a saved connection credential for the database then it would be used.  The save credentials are identified by the combination of server/database/user/authtype/etc. So if the database had been connected to in Servers view the credentials would be saved and then reused when expanding the node in Azure view.  I think this is what some people are seeing.  The PR #16999 should avoid this problem since it will default auth to AAD-MFA and the code path to find an existing sql login won't be hit (unless the default configuration option is changed to sqllogin).

The saved Sql Logins are saved in the Credential Manager using the `Microsoft.SqlTools|itemtype:Profile|` prefix and can safely be deleted.  You'll be prompted to reenter the password when reconnecting.

![image](https://user-images.githubusercontent.com/599935/132080759-4a014703-6643-4a5b-8b01-64139d496371.png)

Finally, we've added the "Browse" feature in the Connection dialog to allow going through your subscription and adding a saved connection to the Servers view.  Using this mechanism will persists the connection details to settings and Credential Manager, and would hopefully avoid a lot of these bugs.  We've been thinking about removing the Azure view and introducing some different UX for managing Azure resources.  The inline expansion of the nodes in the Azure tree is problematic since all the nodes can have different authentication settings and we'd need to cache a bunch of credential information to make that experience more seamless.  Using Connection Dialog Browse and Servers view makes the credential persistence more explicit.  If you do wish to persist credentials while using Azure view please trying using the Connect icon on the Database/Server node.

![image](https://user-images.githubusercontent.com/599935/132080888-d1e74832-3f5f-44ad-9350-d5ebc009ebb6.png)

I'm going to continue to investigate/improve the behavior in this area.  More so in the Servers view and core connectivity, as we'll likely be removing the Azure view in a future release once we have a better long-term experience designed.  And close this issue based on #16999.  Since there are several distinct bugs discussed in the comments thread please log new issues for those specific bugs.  Thanks!

**Comment by mcetkovsky** [comment] 2021-09-06 14:10
@kburtram Feel free to split this issue / move my comments as you find suitable. Thanks.

**Comment by kburtram** [comment] 2021-09-09 20:08
@mcetkovsky I moved the issue you reported to https://github.com/microsoft/azuredatastudio/issues/17036.  I'll take a look and try to repro and leave any follow-ups there.

I also opened https://github.com/microsoft/azuredatastudio/issues/17037 for a bug in the Azure view interaction with Connection dialog that may be confusing.

I merged this PR https://github.com/microsoft/azuredatastudio/pull/16999 which changes the default auth mode in Azure viewlet to AAD.  This will prevent the logic to try to guess a SqlLogin from running when expanding DB nodes.  

Though as discussed in the above comment, for servers/databases accessed frequently I'd recommend using the Connection Dialog Browse pane to add a saved connection to the resource.  This should persist the credentials properly and avoid some of the bugs discussed above.  The design with Azure view was to not persist credentials (but to try to use existing persisted credentials), which is somewhat confusing.  If don't end up replacing the Azure view with a different Azure Management experience we'll look into whether it makes sense to change the existing design to persist credentials from the Azure view.

Please log a new issue for any existing related bugs not covered by previously mentioned fix, workarounds, and bugs.  Thanks!

**Closed by kburtram** 2021-09-09 20:08 UTC
Labels: Bug, Area - Connection, Area - Azure, Triage: Done
