### ISSUE TITLE
Intellisense stall on second tab causes ADS UI to stop updating

### ISSUE THREAD

**Issue by mtaylorfsmb** [microsoft/azuredatastudio#18915] opened 2022-04-04 14:17 UTC
Issue Type: <b>Bug</b>

I have a tab open, connected to a DB and results loaded into the results window. I then open a second tab, change to a different database on the same server and start typing my select query. As soon as I enter a schema intellisense shows the schema/DBs and then it stops providing responses for a while as I assume it is trying to discover what is available. But at this point the UI has effectively stopped working properly.

![image](https://user-images.githubusercontent.com/38144840/161563483-f34dc269-e9aa-4923-b549-083c3d4379fb.png)

- I can continue typing in my query just fine.
- Going back to the first tab the Results window is empty except for the row numbers. I can scroll up and down but there are no results anymore.
  ![image](https://user-images.githubusercontent.com/38144840/161563237-dc63b75e-83f7-4bf9-8327-cca66e1fc0c5.png)

- Attempting to run my query again results in the tab not doing anything. The query seems to start but doesn't actually do so. The execution time in the status bar doesn't change from 00:00:00.
  
![image](https://user-images.githubusercontent.com/38144840/161563582-93f86448-e7e6-4fdd-9e0f-e217c588c830.png)

The only workaround I've found is to restart ADS.

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by alanrenmsft** [comment] 2022-04-08 17:57
@mtaylorfsmb what is the network latency between you machine and the server? and how powerful is the server? this seems to be related to an issue that we are not properly handling concurrent requests.

**Comment by alanrenmsft** [comment] 2022-04-08 17:58
dupe of #7440

**Comment by CoolDadTx** [comment] 2022-04-08 17:59
@alanrenmsft The network latency is normally not noticeable (aka SSMS). The server the DB runs on is a data center server and is way more powerful than the DB actually needs.

**Closed by alanrenmsft** 2022-04-08 17:58 UTC
Labels: Bug, Area - Query Editor
