### ISSUE TITLE
Chars not show correctly

### ISSUE THREAD

**Issue by ramons03** [microsoft/azuredatastudio#3134] opened 2018-11-06 15:28 UTC
Issue Type: <b>Bug</b>

1. Open a file with this word as example -> a�oacademico
2. character ? should be the letter ñ

Previous version was working ok.

Azure Data Studio version: azuredatastudio 1.1.4 (5d6390505643df3edd6f734c80082006efbeff5e, 2018-10-29T20:34:47.838Z)
OS version: Windows_NT x64 6.3.9600

Extensions: none

**Comment by ramons03** [comment] 2018-11-06 15:35
[chars sqlop.txt](https://github.com/Microsoft/azuredatastudio/files/2553815/chars.sqlop.txt)

**Comment by kburtram** [comment] 2018-11-08 19:36
I wasn't able to repro using the provided txt file.  Do I need to be in specific locale or keyboard layout?  

In general, this type of editor functionality comes from VS Code, so unless the issue is only in Azure Data Studio (and not VS Code), we'd likely recommend getting the issue fixed upstream.

![image](https://user-images.githubusercontent.com/599935/48222765-3f118d00-e34a-11e8-8291-8adfb3fd6a82.png)

**Comment by ramons03** [comment] 2018-11-08 20:17
Same issue vscode, i was not aware of that.
I have Español Argentina as main and English United States second.
When i open the file with other editors like notepad it works ok.

![vscode open](https://user-images.githubusercontent.com/295830/48224686-56b43a00-e379-11e8-9490-a00f7c8c8ee5.gif)

**Comment by ramons03** [comment] 2018-11-08 20:34
Encoding of the file (chars sqlop.txt) that vscode can't open is ANSI
Encoding of the file that vscode opens is UTF-8

**Comment by kburtram** [comment] 2018-11-14 00:35
@ramons03 thanks for the additional info.  This could be related to encoding settings we override in Azure Data Studio, though I'm not aware of any modifications we've made in this area vis-à-vis VS Code.  I'll take a closer look.

**Comment by ramons03** [comment] 2019-02-20 13:16
I think is fixed, version 1.4.5

**Comment by ramons03** [comment] 2019-02-20 13:29
Added this to fix.

![fix sqlop](https://user-images.githubusercontent.com/295830/53094962-4bd17f80-34fa-11e9-8454-63a7c9331403.JPG)

**Comment by kburtram** [comment] 2021-08-16 20:51
@ramons03 thanks for publishing the workaround!  I'll close this older issue as resolved by adding the `autoGuessEncoding` setting.

**Closed by kburtram** 2021-08-16 20:51 UTC
Labels: Bug, Upstream, Area - Query Editor, Area - Localization
