### ISSUE TITLE
Unable to delete last Null Row in Edit Data

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#19327] opened 2022-05-10 18:52 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. In object explorer, open the TutorialDB dropdown and right-click on dbo.Customers 
2. Select "Edit Data"
3. Right click on the last row (all columns in this row are NULL)

Expected:

Upon right-clicking, option to delete rows should be seen, just like in other rows

Actual:

Nothing happens upon right-clicking 

![image](https://user-images.githubusercontent.com/72947001/167701097-22979b45-31a5-4daf-94c8-66703a476456.png)

Does this issue occur when all extensions are disabled?: Yes/No 

N/A

**Comment by Charles-Gagnon** [comment] 2022-05-10 19:08
@tdoshin Is this row actually added to the table? I thought that the bottom row was just a proxy one and wasn't actually inserted until the user typed something in (so not being able to delete it is expected)

@smartguest Can you confirm?

**Comment by tdoshin** [comment] 2022-05-10 19:13
Ok. thanks. I guess I should have rephrased my question as "is this expected behavior". Bottom row is proxy.

**Comment by smartguest** [comment] 2022-05-10 19:30
That is correct @Charles-Gagnon it's always added at the end to allow for users to add stuff to it, if we could delete it, there would be no way for users to add more rows.

**Comment by Charles-Gagnon** [comment] 2022-05-10 19:35
Is there still something you think is wrong @tdoshin or can we close this then?

**Comment by kburtram** [comment] 2022-06-06 22:12
The "New Record" row isn't committed until focus leaves the row, so it's expected to not have options to delete the row yet since it hasn't been created.  To revert changes prior to adding the row the user can press the ESC key for example.  I'll close this is by design.

**Closed by kburtram** 2022-06-06 22:12 UTC
Labels: Bug, Area - Edit Data, Triage: Needed
