### ISSUE TITLE
Authentication times out and does not refresh (Kusto connection)

### ISSUE THREAD

**Issue by stevenhurwitt** [microsoft/azuredatastudio#12724] opened 2020-10-03 16:52 UTC
- Azure Data Studio Version: 1.22.1

Steps to Reproduce:

1. Let session sit idle for awhile (I'm guessing 3600s)
2. Run a kusto query - get an error.

I'm guessing the bearer token is expiring and it's not using the refresh token to get a new one.

**Comment by SQLvariant** [comment] 2020-10-21 21:01
I'm having the exact same issue.  I have to create a completely new connection in order to get a successful connection which will allow me to query.

**Comment by SQLvariant** [comment] 2020-10-22 16:14
For me, it seems to take a few hours before the connection times out.  Maybe it re-starts the timer each time I run a query?

**Comment by MsSQLGirl** [comment] 2020-10-22 18:32
@SQLvariant  - can you please add your ADS version and Kusto extension version where you can repro this?

**Comment by SQLvariant** [comment] 2020-10-22 18:56
Using Kusto extension v0.2.0

Here are my ADS details:
Version: 1.24.0-insider (user setup)
Commit: de7cc8ea53790cdb4fc034e885036924ba61f066
Date: 2020-10-22T05:37:15.111Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by JustinMDotNet** [comment] 2020-10-29 23:20
This issue is a duplicate of this issue: https://github.com/microsoft/azuredatastudio/issues/11830 and should have been resolved in the September release.

**Comment by MsSQLGirl** [comment] 2020-10-30 01:07
@JustinMDotNet - it seems that @SQLvariant can still repro this in the latest release i.e. v1.24.0-insider. So, I'm reopening this issue.

**Comment by JustinMDotNet** [comment] 2020-11-23 21:19
@SQLvariant @stevenhurwitt Are you still experiencing this issue in the latest Kusto Extension version 0.3.2? We're having trouble duplicating this internally. Are you using a non-default tenant?

**Comment by SQLvariant** [comment] 2020-11-23 21:23
Thankfully, I have not been able to repro that since a day or two after I posted my last comment.  I hope it stays that :-)

**Comment by JustinMDotNet** [comment] 2021-09-23 23:49
Issue has been resolved. Closing.

**Closed by JustinMDotNet** 2021-09-23 23:49 UTC
Labels: Bug, Triage: Done, Area - Kusto
