### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by SinisterChinaPenguin** [microsoft/azuredatastudio#23456] opened 2023-06-23 08:36 UTC
Type: <b>Bug</b>

Sometime when I start Data Studio I just get a blank Window - maybe one in 10 times I open Data Studio.

![image](https://github.com/microsoft/azuredatastudio/assets/18634517/3b0a3f85-35fa-4238-9428-66935d94c92c)

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.13.0
import|Mic|1.5.5
powershell|ms-|2023.2.1
profiler|Mic|0.12.2

</details>

**Comment by kisantia** [comment] 2023-07-10 18:57
@SinisterChinaPenguin did you start noticing this with the 1.44.1 release or also with previous versions of ADS?

**Comment by SinisterChinaPenguin** [comment] 2023-07-11 10:33
Hi. I started noticing this with the 1.44.1 release. It wasn’t an issue on previous versions.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cheenamalhotra** [comment] 2023-08-24 21:55
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/22022

**Closed by cheenamalhotra** 2023-08-24 21:55 UTC
Labels: Bug, Area - Shell, Pri: 2, Triage: Done
