### ISSUE TITLE
Windows Authentication can't log in as a different user

### ISSUE THREAD

**Issue by aabelnetline** [microsoft/azuredatastudio#14301] opened 2021-02-15 15:55 UTC
I am logged in to Windows on my home laptop but want to be able to connect to a SQL Server instance using a work domain user. But in Azure Data Studio when I select Windows Authentication the username and password are grayed out so I can't choose to log in as a different user.

**Comment by kburtram** [comment] 2021-02-18 01:52
@aabelnetline this is a long standing request we've had with azuredatastudio https://github.com/microsoft/azuredatastudio/issues/112.  The blocking issue has been the SqlClient driver doesn't easily support this scenario and would require updates for this.  The suggested workaround is to use the "runas" command to launch the ADS process as a different user.  I'll close this as a duplicate of the linked issue.  Thanks!

**Closed by kburtram** 2021-02-18 01:52 UTC
Labels: Area - Azure, Bug, Needs Logs, Triage: Needed
