### ISSUE TITLE
Profiler error

### ISSUE THREAD

**Issue by bbuic** [microsoft/azuredatastudio#10333] opened 2020-05-11 06:38 UTC
Issue Type: <b>Bug</b>

Hello,

when try to open azure data studio profiler a got error:

cannot set property "actionbarcontext" of undefined.

Call stack:

INFO Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:go2bike-db_test_azure|server:go2bike-sqlserver-test.database.windows.net|user:Go2BikeTest|databaseDisplayName:go2bike-db_test_azure|group:C777F06B-202E-4480-B475-FA416154D458
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:go2bike-db_test_azure|server:go2bike-sqlserver-test.database.windows.net|user:Go2BikeTest|databaseDisplayName:go2bike-db_test_azure|group:C777F06B-202E-4480-B475-FA416154D458
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:go2bike-db_test_azure|server:go2bike-sqlserver-test.database.windows.net|user:Go2BikeTest|databaseDisplayName:go2bike-db_test_azure|group:C777F06B-202E-4480-B475-FA416154D458
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Creating new connection connection:a8b43ea5-bb65-4e58-8d13-98114ca505e2
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Adding connection connection:a8b43ea5-bb65-4e58-8d13-98114ca505e2
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Successfully added connection connection:a8b43ea5-bb65-4e58-8d13-98114ca505e2
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 Unable to open 'Profiler: go2bike-sqlserver-te': Cannot set property 'actionBarContext' of undefined.
console.<computed> @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
onDidChangeNotification @ workbench.desktop.main.js:3738
(anonymous) @ workbench.desktop.main.js:3738
fire @ workbench.desktop.main.js:194
addNotification @ workbench.desktop.main.js:3773
notify @ workbench.desktop.main.js:5270
doHandleOpenEditorError @ workbench.desktop.main.js:7620
(anonymous) @ workbench.desktop.main.js:7620
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
(anonymous) @ workbench.desktop.main.js:7619
doShowEditor @ workbench.desktop.main.js:7620
doOpenEditor @ workbench.desktop.main.js:7619
openEditor @ workbench.desktop.main.js:7618
openEditor @ workbench.desktop.main.js:7412
(anonymous) @ workbench.desktop.main.js:7295
ZoneDelegate.invoke @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388
Zone.run @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138
(anonymous) @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872
ZoneDelegate.invokeTask @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421
Zone.runTask @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188
drainMicroTaskQueue @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
scheduleMicroTask @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:578
ZoneDelegate.scheduleTask @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:410
Zone.scheduleTask @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:232
Zone.scheduleMicroTask @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:252
scheduleResolveOrReject @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:862
resolvePromise @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:808
(anonymous) @ c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:724
handleDefaultOnConnect @ workbench.desktop.main.js:7815
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
handleDefaultOnConnect @ workbench.desktop.main.js:7815
handleOnConnect @ workbench.desktop.main.js:7813
(anonymous) @ workbench.desktop.main.js:7819
fire @ workbench.desktop.main.js:194
connect @ workbench.desktop.main.js:5672
(anonymous) @ workbench.desktop.main.js:5671
(anonymous) @ workbench.desktop.main.js:2775
fire @ workbench.desktop.main.js:194
(anonymous) @ workbench.desktop.main.js:647
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
    at e._showStatus (file:///C:/Users/Bojan/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5469:656)
    at e._updateStatus (file:///C:/Users/Bojan/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5469:545)
    at e._onFlavorChanged (file:///C:/Users/Bojan/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5469:452)
    at file:///C:/Users/Bojan/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5468:680
    at e.fire (file:///C:/Users/Bojan/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:67)
    at e.doChangeLanguageFlavor (file:///C:/Users/Bojan/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5652:346)
    at file:///C:/Users/Bojan/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5654:40
    at ZoneDelegate.invoke (c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 15:12:30] Request profiler/disconnect failed.
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: Value cannot be null.
Parameter name: key  Code: -2147467261 
c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Value cannot be null.
Parameter name: key: Error: Value cannot be null.
Parameter name: key
	at c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:68553
	at c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:68847
	at Immediate.<anonymous> (c:\Users\Bojan\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:69208)
	at processImmediate (internal/timers.js:439:21)

Did someone know what happened?

Bojan

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.47.0
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment] 2020-05-11 14:27
@bbuic thanks for reporting this issue.  This appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/10282.  There is a fix in the latest insider build, or a workaround is to close all the broken editor windows the profiler is leaving behind.  The easiest way to do this is to either open a folder or close the currently open folder, which will reset the hotexit editor windows list to prevent these broken editors from appearing on startup.  

The fix will be in the May release next.  Sorry for the inconvenience.

**Closed by kburtram** 2020-05-11 14:27 UTC
Labels: Bug, Triage: Needed
