### ISSUE TITLE
Failed to start session 

### ISSUE THREAD

**Issue by nnnax** [microsoft/azuredatastudio#6353] opened 2019-07-11 08:51 UTC
Issue Type: Bug
Area: SQL Profiler 

I'm not able to start a new session.
I've the message :
Failed to start session: An exception occurred while executing a Transact-SQL statement or batch.
Tested on windows and mac OS with the same error.

It was working fine 2 days ago with the same version of the extension.

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 6.1.7601

**Comment by Charles-Gagnon** [comment] 2019-07-11 15:28
Are there any further error messages in the Developer Console? (Help -> Toggle Developer Tools -> Console tab)

**Comment by nnnax** [comment] 2019-07-11 17:15
> Are there any further error messages in the Developer Console? (Help -> Toggle Developer Tools -> Console tab)

Please find the Screenshot below

![screen](https://user-images.githubusercontent.com/2895717/61071007-44126900-a410-11e9-96e5-1e44eb60b1e9.png)

**Comment by alanrenmsft** [comment] 2019-07-12 07:30
@nnnax  what is your target server, is it an Azure SQL Server or standalone SQL Server, also what template did you pick?

**Comment by nnnax** [comment] 2019-07-12 07:43
> @nnnax what is your target server, is it an Azure SQL Server or standalone SQL Server, also what template did you pick?

I target an Azure SQL server. I picked up ADS STANDARD AZURE.

I've tried with 2 different azure subscriptions.

**Comment by js-cubed** [comment] 2019-07-12 14:38
Same issue here. Used the profiler extension successfully for a few hours and then it stopped receiving events (the "Stop" button was disabled, and the "Start" button was clickable, but triggered the message "Failed to start session: An exception occurred while executing a Transact-SQL statement or batch."

Restarting Azure Data Studio did not fix it. I'm currently uninstall ADS, which requires a reboot apparently. I will return to update this thread shortly.

**Comment by js-cubed** [comment] 2019-07-12 15:07
This did *not* work:

 - Uninstalled ADS fully
 - Deleted `%APPDATA%\azuredatastudio`
 - Downloaded ZIP'd version of ADS (not installer)
 - Ran azuredatastudio.exe
 - Enabled "preview features"
 - Clicked the Gear in the bottom left
 - Picked "Extensions"
 - Searched for "SQL Server Profiler"
 - Clicked "Install"
 - Struck `Alt` + `P`
 - Entered connection info, let database selection auto-populate to confirm it was connecting to the server properly.
 - Picked session template: "Standard Azure" (nothing else available in drop down)
 - Clicked "Start", received error "Failed to create session: An exception occurred while executing a Transact-SQL statement or batch." with "Source: SQL Server Profiler (Extension)"

![2019-07-12_11-04-13](https://user-images.githubusercontent.com/52829535/61138208-06a3ef00-a495-11e9-8d48-c55d098f3097.png)
![2019-07-12_11-05-54](https://user-images.githubusercontent.com/52829535/61138220-0efc2a00-a495-11e9-80cd-63e8f0820ccf.png)

**Comment by alanrenmsft** [comment] 2019-07-12 17:57
Can you try running the following T-SQL directly against your Azure Database? 

CREATE EVENT SESSION [ADS_Standard_Azure_test] ON DATABASE
					ADD EVENT sqlserver.attention(
						ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)
						WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))),
					ADD EVENT sqlserver.existing_connection(SET collect_options_text=(1)
						ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)),
					ADD EVENT sqlserver.login(SET collect_options_text=(1)
						ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)),
					ADD EVENT sqlserver.logout(
						ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)),
					ADD EVENT sqlserver.rpc_completed(
						ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)
						WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))),
					ADD EVENT sqlserver.sql_batch_completed(
						ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)
						WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))),
					ADD EVENT sqlserver.sql_batch_starting(
						ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)
						WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0))))
					ADD TARGET package0.ring_buffer(SET max_events_limit=(1000),max_memory=(51200))
					WITH (MAX_MEMORY=8192 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=5 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=ON,STARTUP_STATE=OFF)

**Comment by js-cubed** [comment] 2019-07-12 18:07
Hi @alanrenmsft 

I got this error in ADS, so I put it in SMSS to get the live feedback on syntax.

![image](https://user-images.githubusercontent.com/52829535/61148849-b2593900-a4ad-11e9-88a8-36783913c799.png)

Thanks.

The plugin began working on another pool in my organisation (another *.database.windows.net URL). The main difference I can tell is that the one it stopped working on is part of "Elastic pool" and the one that it is working on is not part of an elastic pool.

**Comment by js-cubed** [comment] 2019-07-12 18:12
I created a ticket with MSFT support for the pool/server in question asking if it can be "restarted" just to check, since everything worked fine yesterday with this setup and I don't think it's anything to do with my PC as I tested it on another server in my corporate network as well as a PC outside of my corporate network.

**Comment by alanrenmsft** [comment] 2019-07-12 22:54
@nnnax, are you having similar issue (elastic pool related) as @js-cubed ? 
From Azure Data Studio side, I will expose the original error message thrown by SQL Server when trying to create  XEvent session to make it easier to identify the problem.

**Comment by nnnax** [comment] 2019-07-13 11:31
> @nnnax, are you having similar issue (elastic pool related) as @js-cubed ?
> From Azure Data Studio side, I will expose the original error message thrown by SQL Server when trying to create  XEvent session to make it easier to identify the problem.

I'am using Basic databases without Elastic Pool.
I've created a new SQL Server and new database, and I can confirm that it's works with a new SQL server. But all my existing databases on my existing SQL server are not working.

**Comment by alanrenmsft** [comment] 2019-07-15 16:50
@nnnax what error are you getting when running the SQL statement I mentioned earlier in the thread?

**Comment by nnnax** [comment] 2019-07-16 06:55
> @nnnax what error are you getting when running the SQL statement I mentioned earlier in the thread?

@alanrenmsft I'am facing the same syntax error as @js-cubed

**Comment by sambathraj** [comment] 2019-07-17 19:46
I am also facing this issue and cannot use the profile any more. It was working fine 2 days ago. I turned on auditing. 
Following query fails with error. 
**The event 'sqlserver.logout' is not available for Azure SQL Database.** Any way we remove the event from the template?

`CREATE EVENT SESSION [ADS_Standard_Azure] ON DATABASE      ADD EVENT sqlserver.attention(       ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)       WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))),      ADD EVENT sqlserver.existing_connection(SET collect_options_text=(1)       ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)),      ADD EVENT sqlserver.login(SET collect_options_text=(1)       ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)),      ADD EVENT sqlserver.logout(       ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)),      ADD EVENT sqlserver.rpc_completed(       ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)       WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))),      ADD EVENT sqlserver.sql_batch_completed(       ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)       WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))),      ADD EVENT sqlserver.sql_batch_starting(       ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id)       WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0))))      ADD TARGET package0.ring_buffer(SET max_events_limit=(1000),max_memory=(51200))      WITH (MAX_MEMORY=8192 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=5 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=ON,STARTUP_STATE=OFF)`

**Comment by matthewcastle** [comment] 2019-07-18 12:48
Just started to try and use profiling today for the first time, and have the same issue:

Msg 25743, Level 16, State 1, Line 1
The event 'sqlserver.logout' is not available for Azure SQL Database.

**Comment by Gebov** [comment] 2019-07-19 05:44
Same issue. Did not have it 12 hours ago .. This is my error:

  | console.(anonymous function) | @ | C:\Program Files\Azu…t\zone-node.js:2280
-- | -- | -- | --
  | onDidNotificationChange | @ | workbench.main.js:166520
  | _register.model.onDidNotificationChange.e | @ | workbench.main.js:166508
  | fire | @ | workbench.main.js:10027
  | notify | @ | workbench.main.js:170865
  | error | @ | workbench.main.js:251098
  | _runAction.then | @ | workbench.main.js:241836
  | ZoneDelegate.invoke | @ | C:\Program Files\Azu…st\zone-node.js:388
  | Zone.run | @ | C:\Program Files\Azu…st\zone-node.js:138
  | (anonymous) | @ | C:\Program Files\Azu…st\zone-node.js:872
  | ZoneDelegate.invokeTask | @ | C:\Program Files\Azu…st\zone-node.js:421
  | Zone.runTask | @ | C:\Program Files\Azu…st\zone-node.js:188
  | drainMicroTaskQueue | @ | C:\Program Files\Azu…st\zone-node.js:595
  | ZoneTask.invokeTask | @ | C:\Program Files\Azu…st\zone-node.js:500
  | ZoneTask.invoke | @ | C:\Program Files\Azu…st\zone-node.js:485
  | emit | @ | events.js:182
  | addChunk | @ | _stream_readable.js:279
  | readableAddChunk | @ | _stream_readable.js:264
  | Readable.push | @ | _stream_readable.js:219
  | onread | @ | net.js:636

**Comment by alexiordan** [comment] 2019-07-21 16:12
I managed to have it at least starting by removing the logout event from the provided script.
I ran the script against the database, then going back in Azure Data Studio and the starting the session.
```
CREATE EVENT SESSION [ADS_Standard_Azure] ON DATABASE ADD EVENT sqlserver.attention( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), ADD EVENT sqlserver.existing_connection(SET collect_options_text=(1) ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)), ADD EVENT sqlserver.login(SET collect_options_text=(1) ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)), ADD EVENT sqlserver.rpc_completed( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), ADD EVENT sqlserver.sql_batch_completed( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), ADD EVENT sqlserver.sql_batch_starting( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))) ADD TARGET package0.ring_buffer(SET max_events_limit=(1000),max_memory=(51200)) WITH (MAX_MEMORY=8192 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=5 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=ON,STARTUP_STATE=OFF)
```

**Comment by Chris-CBD** [comment] 2019-07-22 17:06
Same issue.  Super frustrating.

**Comment by matthewcastle** [comment] 2019-07-23 08:14
@yualan This issue seems to be a bit of attention, any chance of an ETA on a fix?  I am hoping this is earlier than the December 2020 Planning Milestone it has been added to!
Any info would be very much appreciated.

**Comment by VeritableHero** [comment] 2019-07-23 16:56
Is this tied to permissions/security at all? Users in our company with the "View Server State" permission receive this error. However, I'm able run the profiler through ADS 1.9 without receiving the error and I have elevated permissions.

**Comment by alanrenmsft** [comment] 2019-07-23 16:58
I am looking into this now

**Comment by jbutler94127** [comment] 2019-07-23 21:29
Same issue for me.  Just installed VS 2019 last week.  My (31) Azure databases have existed for over a year (all in an elastic pool on the same server).  I just began pointing the (.net) application to these databases.  

Installed Azure Data Studio and the SQL Server Profiler Extension (0.9.0) this morning.  When I select a database, View Command Palette, Profiler: Launch Profiler. Start New Profiler Session with only one session template: Standard_Azure, Enter session name: prefilled with ADS_Standard_Azure. Click Start.  Failed to create session: An exception occurred while executing a Transact-SQL statement or batch.

This must be really frustrating for people who have been relying on it.

**Comment by alanrenmsft** [comment] 2019-07-23 23:04
Confirmed with Azure SQL Database team, they have a regression recently, this will be fixed in the next Azure SQL Database update.

for now please follow @alexiordan ‘s comment to get yourself unblocked: https://github.com/microsoft/azuredatastudio/issues/6353#issuecomment-513567218

Thanks @alexiordan

**Comment by paschott** [comment] 2019-07-25 21:21
Oddly, _something_ I did is letting the Profiler work now. Last I tried was running the script Alex posted above - https://github.com/microsoft/azuredatastudio/issues/6353#issuecomment-513567218.  After that I started the profiler, created the session, and am getting results.

I have no idea why it's working, though.

**Comment by alanrenmsft** [comment] 2019-07-25 21:24
@paschott , Sorry, not sure I am following, are you asking why running the t-sql script Alex posted works?

**Comment by paschott** [comment] 2019-07-25 21:40
@alanrenmsft I think I was just confused about what the session was doing. I think I'd read the session name in the script differently. I thought it was creating a session name that wasn't the same one expected by the Profiler extension.  However, it _does_ work as a workaround until we get that next release.

**Comment by alanrenmsft** [comment] 2019-07-25 22:25
@paschott , I see, the profiler will try to create a new session if a session with the given name doesn’t exist. otherwise it will reuse the existing session. that’s Why Alex’s T-SQL script works. and that script only needs to be run once on your Azure SQL database. If SQL Azure Database is not getting the fix in before the next ADS release, I will make the change in ADS directly.

**Comment by spursrox** [comment] 2019-08-01 14:05
Confirming the work-around works. Run Alex's script, above, which manually creates a Session named "ADS_Standard_Azure". Then, in Azure Data Studio, attempt to profile, using a Session named exactly the same: "ADS_Standard_Azure".  This combination worked for me. Don't know if this makes a difference, or not, but I'm using Azure Data Studio version 1.10.0-insider

**Comment by alanrenmsft** [comment] 2019-08-13 17:57
it seem the Azure SQL DB has fixed the missing xevent name issue, Closing the issue.

**Closed by alanrenmsft** 2019-08-13 17:57 UTC
Labels: Area: SQL Profiler, Bug, Needs More Info, Triage: Done
