### ISSUE TITLE
Filter option for Tables, SP, etc.

### ISSUE THREAD

**Issue by cjcl007** [microsoft/azuredatastudio#13897] opened 2021-01-03 00:09 UTC
Issue Type: <b>Feature Request</b>

Please add a filter option for Tables and Stored procedures.
Is a headache always scroll down and up all the list of tables when I'm searching for a specific table.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19041

**Comment by liuwy1005** [comment] 2021-01-04 05:49
double click the database object , or right click the database select the "manage"
then you can see the search board .
type the table name or proc name.can filter it.

**Comment by Charles-Gagnon** [comment] 2021-01-05 17:40
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12932

The suggestion that @liuwy1005 had is a possible workaround as well.

**Closed by Charles-Gagnon** 2021-01-05 17:40 UTC

**Comment by hcc-donder** [comment] 2021-02-10 20:54
Neither of the workarounds actually solve the problems mentioned. If I am working on a query, I want to be able to see all the columns in a table. Right now, I scroll through the list of tables in the Connections pane to the table of interest and expand. Sometimes that can take a while given the number of tables and views I have. The manage options lets me filter the tables/views easily, but I cannot expand the table to view the columns and I cannot work on a query at the same time without splitting windows and taking up more screen space.

**Comment by mammadkoma** [comment] 2021-05-31 10:30
How we can filter tables like SSMS by right click on Tables folder?
