### ISSUE TITLE
Mouse horizontal scroll wheel does not work in SQL Ops Studio

### ISSUE THREAD

**Issue by nmyron** [microsoft/azuredatastudio#1735] opened 2018-06-26 20:19 UTC
- SQL Operations Studio Version:
Version 0.30.6
Commit df7e3ec7d52a82febee5b597a1019cabf021b883
Date 2018-06-19T21:45:43.589Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Personally I have a Logitech MX Master 2 mouse, but my suspicion would be that this would be the case on any mouse with a built in horizontal scroll input. Connect said mouse with horizontal scroll wheel, run a query, and attempt to scroll horizontally. The results pane will move a handful of pixels, then stop functioning entirely until a new query is ran.

This does not happen in any other application but SQL Ops Studio, and I have the latest drivers from Logitech. This issue has persisted through several updates. SHIFT+vertical scroll will still scroll horizontally as expected, but totally defeats the purpose of having a horizontal scroll wheel when using SQL Ops Studio.

**Comment by kevcunnane** [comment] 2018-06-27 18:38
Is this on Windows, Mac or Linux? I'm struggling to reproduce on macOS with my (Microsoft) mouse as horizontal scrolling works as expected. Would be interested in understanding if this is platform specific, or if we can get more details.

@anthonydresser any ideas on this one?

**Comment by nmyron** [comment] 2018-06-28 01:49
Should have specified. Windows 10. Apologies about that.

When it fails it's almost like thebold shift+scroll bug as well. It moves right a handful of pixels and won't work again until you pull your next result set.

**Comment by nmyron** [comment] 2018-06-28 01:54
Yes, it repros in VSCode. So it looks like the issue is above SQLOps right since it shares the VSCode codebase. Also repros in SQLOps editor.

**Comment by anthonydresser** [comment] 2018-06-28 17:37
Do you use chrome as a browser? does it repro in that?

**Comment by nmyron** [comment] 2018-06-28 18:14
Yes, I use Chrome and no, I have no other issues using my horizontal scroll wheel in any app. Only issues are in VSCode and SQLOps. I'll submit a similar bug report for VSCode shortly.

**Comment by anthonydresser** [comment] 2018-06-28 18:17
Do you use any other electron based apps that you could check if it repros in?

Here's a full list https://electronjs.org/apps but apps like Atom, Discord Desktop, Slack Desktop, WhatsApp Desktop.

**Comment by nmyron** [comment] 2018-12-21 17:08
I've not replied here in a while, honestly I forgot I opened this forever ago. But I wanted to try to provide some more information. I have upgraded to Azure Data Studio version 1.2.4, and it appears to work after using the scroll wheel within VSCode. For example, if I launch the application, it doens't work. If I then launch VSCode, and use my horizontal wheel in the editor window of VSCode, I can then use it successfully in both the editor and results pane of Azure Data Studio. Dunno if this helps to provide more information or not.

**Comment by slimbeck** [comment] 2019-10-30 13:01
@nmyron You're right. I have a Logitech MX Master 2S mouse and I could never get more than a few pixels of horizontal scroll movement out of the query results pane for each time I move my mouse out and then back into the pane (this is in SSMS 18.3.1). I tried what you said about launching VS Code and then trying again, and sure enough, it works.

**Comment by lewis-sanchez** [comment] 2023-05-16 17:55
Closing this issue since the bug seems to have been fixed already.

I attempted to repro the horizontal scrolling issue with my Logitech Master MX 2S mouse and scrolling is working in the results pane, and query editor.

**Closed by lewis-sanchez** 2023-05-16 17:55 UTC
Labels: Bug, Area - Query Editor, Pri: 3, Triage: Done

**Comment by Kevin-Havice-SOLV** [comment] 2024-09-09 18:52
Hello! I found this thread because even now, I have this issue in Azure Data Studio 1.49.1 ... I can't use horizontal scroll with my mouse in the results pane. For me right now, it's just like @nmyron said: "if I launch VSCode, and use my horizontal wheel in the editor window of VSCode, I can then use it successfully in both the editor and results pane of Azure Data Studio."

So maybe this bug isn't fully fixed?

**Comment by kevhav** [comment] 2024-09-09 18:57
Hello, I am having this exact same issue now in Azure Data Studio 1.49.1 ... horizontal scroll from my mouse won't work in the results pane. It works initially to scroll a tiny bit, but then stops. And I find the following workaround does work for me: "if I first use my horizontal wheel in the editor window of VSCode, I can then use it successfully in both the editor and results pane of Azure Data Studio."

So maybe this isn't totally fixed yet? Or am I missing something? Thanks!
