### ISSUE TITLE
SQL Server Import extension not loading - November 2022

### ISSUE THREAD

**Issue by VeroslavOlic** [microsoft/azuredatastudio#21304] opened 2022-11-24 10:03 UTC
Hi,
The extension SQL Server Import is not loading - after running Ctrl+I (Import wizard) the bottom status bar just says "Activating Extensions..." but nothing else happens then, no import wizard is shown. I've attached the main, renderer1 and sharedprocess logs.

Version: 1.40.1 (user setup)
Commit: 3a32679ab590c1023ab4de6f191769e7e127d25b
Date: 2022-11-22T18:30:25.850Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Windows_NT x64 10.0.19044

Please advise.
With regards
Veroslav

<img width="263" alt="Screenshot_1" src="https://user-images.githubusercontent.com/8067803/203754933-fac91e34-6029-4691-92c0-7d1b0605e9dc.png">
[main.log](https://github.com/microsoft/azuredatastudio/files/10083279/main.log)
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/10083284/renderer1.log)
[sharedprocess.log](https://github.com/microsoft/azuredatastudio/files/10083295/sharedprocess.log)

**Comment by Liriel** [comment] 2022-11-24 15:37
possible duplicate of https://github.com/microsoft/azuredatastudio/issues/21267

**Comment by aasimkhan30** [comment] 2022-12-10 01:15
dup of #21313

**Closed by aasimkhan30** 2022-12-10 01:15 UTC
Labels: Area - SQL Import, Triage: Needed
