### ISSUE TITLE
Notebooks: Collapse sections

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/azuredatastudio#7236] opened 2019-09-17 08:14 UTC
Issue Type: <b>Feature Request</b>

If I have several blocks in a notebook, I may not be interested in all of them at the same time. Being able to collapse sections that are not immediately relevant (and expand them when they become relevant again) will be a great improvement.

At the very least, one should be able to collapse the output, but collapsing the entire block (showing maybe the first three lines of text) will be best.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17763

**Comment by corivera** [comment] 2019-09-17 22:54
Duplicate of https://github.com/microsoft/azuredatastudio/issues/4641

**Closed by corivera** 2019-09-17 22:54 UTC
Labels: Area: Notebooks, Enhancement, Triage: Needed
