### ISSUE TITLE
Missing index suggestion error

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/azuredatastudio#24121] opened 2023-08-11 14:28 UTC
Type: <b>Bug</b>

I requisted a query plan for a query and got a missing index suggestion where the query is incorrect.

The suggested query defines the index column, which is also added to the include columns. This is not allowed in SQL and therefor I get the error "Cannot use duplicate column names in index. Column name 'GroupCode' listed more than once." upon running the query.

![image](https://github.com/microsoft/azuredatastudio/assets/10850600/a89924cb-c7cb-4ce4-9c3e-ae632aeb37cf)

```
CREATE NONCLUSTERED INDEX [IX_MyIndex]
ON [FE].[TableName] ([GroupCode])
INCLUDE ([GroupCode],[IsDeleted])
GO
```

Azure Data Studio version: azuredatastudio-insiders 1.46.0-insider (606d8086418046b0a13afbe49c2fd86c502f2288, 2023-08-09T06:08:08.496Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (10.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
batch-rename-extension|Jan|0.0.6
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.20.0
sql-database-projects|Mic|1.2.0
sql-prompt|Red|0.2.12

</details>

**Comment by erinstellato-ms** [comment] 2023-08-30 21:37
@nielsvdc Thank you for logging this issue.  FYI that I'm closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/20249.  I am linking to this issue from the other so your information is available if needed.  Feel free to upvote that issue (upvoting and comments help us determine priority), thanks!

**Closed by erinstellato-ms** 2023-08-30 21:37 UTC
Labels: Bug, Area - Query Editor, Triage: Needed, Subarea - Execution Plan, Duplicate
