### ISSUE TITLE
Add ability to alter table

### ISSUE THREAD

**Issue by devlern** [microsoft/azuredatastudio#7032] opened 2019-09-03 17:24 UTC
Issue Type: <b>Feature Request</b>

Please Add ability to alter table add column/ assigns table relashipnships/add view diagrams

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kburtram** [comment] 2021-09-10 19:46
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/282.  We are beginning work on this feature.

**Closed by kburtram** 2021-09-10 19:46 UTC
Labels: Area - Object Explorer, Enhancement, Triage: Done
