### ISSUE TITLE
Export To XLS fails

### ISSUE THREAD

**Issue by dgavrilov42** [microsoft/azuredatastudio#19277] opened 2022-05-03 21:36 UTC
Issue Type: <b>Bug</b>

Looks like unusual characters in string fields are causing XLS writer to fail. The error is "Failed to save results. Error: Failed to save Results.xlsx: The Writer is closed or in error state."

Export to CSV works ok.

Here's an example of a bad string value: 

Oaqï¿½ï¿½xï¿½=w]á²¿hï¿½aï¿½ï¿½_ï¿½'oMï¿½!sï¿½$ï¿½ï¿½&>ï¿½Rï¿½Kï¿½ï¿½gï¿½ï¿½eQï¿½ï¿½ï¿½k\ï¿½ï¿½ï¿½Ø!ï¿½.ï¿½ï¿½ï¿½]R~ï¿½Qcz*a5ï¿½hï¿½`]ï¿½ï¿½ï¿½Bï¿½9Xjï¿½.ï¿½}ï¿½ï¿½ï¿½lï¿½>qï¿½/Yï¿½cÎ¶ï¿½ï¿½Å¶ï¿½ï¿½dï¿½ï¿½9Gï¿½ï¿½ï¿½rï¿½ï¿½ï¿½o)Ä„ï¿½ï¿½ï¿½eï¿

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.22614
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (37.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment] 2022-05-05 17:26
dupe of #5202

**Closed by alanrenmsft** 2022-05-05 17:26 UTC
Labels: Bug, Area - Query Editor, Triage: Needed
