### ISSUE TITLE
CSV Field Values in the formatE### Cause Parser Hang

### ISSUE THREAD

**Issue by jlodom** [microsoft/azuredatastudio#3670] opened 2019-01-04 20:45 UTC
Issue Type: <b>Bug</b>

1. Create a fairly standard CSV file.
2. Create a field value in the format E### (where # is a number) such as E011 , E052, etc. For best results have this value as the first field.
3. Attempt to import the CSV file into a database. When it comes to the screen where the data is previewed there will be a hang.

I speculate that this bug is likely caused by the parser attempting to treat the field as a special character value or somesuch. 

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 18.2.0

**Comment by aasimkhan30** [comment] 2022-12-08 22:07
Closing this issue as I cannot reproduce this on the latest version of the extension. If it is still happening to you, can you please share a sample csv file for it. Thanks!

**Closed by aasimkhan30** 2022-12-08 22:07 UTC
Labels: Bug, Area - SQL Import
