### ISSUE TITLE
Copy and paste columns from results grid to Excel not behaving as expected

### ISSUE THREAD

**Issue by oakhousetom** [Microsoft/azuredatastudio#5201] opened 2019-04-25 08:52 UTC
Issue Type: <b>Bug</b>

Copying and pasting columns from the results grid to Excel seems to be a bit strange. If the whole result set or a drag-select is done, the structure copies OK, but if shift-selecting columns either together or spaced apart, the pasted result gets put all in one column - in the order the columns were selected.

Screenshot:
![11-00-51](https://user-images.githubusercontent.com/30407825/56722819-b93e9e00-673f-11e9-9bd5-af8c754971e4.png)

[Ref Twitter conversation here](https://twitter.com/vickyharp/status/1121089978019172352)

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (4.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.38.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1

</details>

**Comment by oakhousetom** [comment] 2019-04-25 08:53
Seems like it's been an issue since 2017? https://github.com/Microsoft/azuredatastudio/issues/26

**Comment by kburtram** [comment] 2019-04-29 16:58
I'll close as a duplicate of #26.  Please upvote that issue to help us prioritize.  Currently this bug has received relatively few reports relative to most the other bugs we're investigating.  Thanks for reporting!

**Closed by kburtram** 2019-04-29 16:58 UTC
