### ISSUE TITLE
Application hang when selecting a change in the source control view

### ISSUE THREAD

**Issue by nicolaslledo** [microsoft/azuredatastudio#15182] opened 2021-04-19 13:12 UTC
Issue Type: <b>Bug</b>

When clicking on a pending change in the source control view, azure data studio hangs, then a window asks keep waiting, reopen,....
The process view (from the help menu) shows that the main process use a whole cpu core (13% cpu) and memory reaches the roof.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
cms|Mic|0.8.0
import|Mic|1.3.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
server-report|Mic|0.2.3
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.1.0

</details>

**Comment by nicolaslledo** [comment] 2021-04-19 13:23
![2021-04-19 15_13_17-Process Explorer](https://user-images.githubusercontent.com/9571440/115243380-287add00-a123-11eb-9cfe-562b4872a570.png)
![2021-04-19 15_13_28-Azure Data Studio](https://user-images.githubusercontent.com/9571440/115243383-29ac0a00-a123-11eb-8a17-b0a9eeb11ce7.png)

**Comment by Charles-Gagnon** [comment] 2021-04-19 16:27
What kind of files are you trying to compare? Are they .sql files?

**Comment by nicolaslledo** [comment] 2021-04-19 18:06
Yes simple sql files. When opening the folder with VS Code instead of Azure Data Studio it works.

**Comment by Charles-Gagnon** [comment] 2021-04-19 18:08
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/15180

We'll be fixing this - but in the meantime you can revert to 1.27 if this is blocking your work until we have the fix released.

**Closed by Charles-Gagnon** 2021-04-19 18:08 UTC
Labels: Area - Shell, Bug, Triage: Needed
