### ISSUE TITLE
Auto-sizing columns in the results panel

### ISSUE THREAD

**Issue by Shawson** [Microsoft/azuredatastudio#172] opened 2017-11-21 13:44 UTC
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
Run any query

It would be great to have the results panel adjust the widths of the column based on the first few rows of data - I find after running a query I have to double click each column so I can view full dates etc.  I minor thing I know, but quite annoying having come from ssms which seemed to do this a little better.

**Comment by liamdo** [comment] 2017-11-24 19:31
Would love to have this too!

**Comment by JCKodel** [comment] 2017-11-27 20:29
+1

**Comment by simonsabin** [comment] 2018-05-12 09:32
I'll add that for E-n numbers this is super important as the E portion of the number is hidden, making you think number is wrong. Just run the following to see
`select 1/cast(11442.as float)`

**Comment by GrzegorzLyp** [comment] 2018-05-18 14:56
In 0.30.1 it does not work good.
![image](https://user-images.githubusercontent.com/29247982/40241905-6f7b3a3e-5abc-11e8-81c2-a7943062f32b.png)

**Comment by joshtoczko** [comment] 2018-05-25 12:16
Would be nice to have a user setting too where you could set a width value for the columns.

**Comment by salarcode** [comment] 2018-06-12 23:36
It would be great if there would be more options to control the behavior like:
'Limit shrinking to column name length'
'Limit growing to x characters'

**Comment by austinjordanFA** [comment] 2018-08-30 21:38
+1

**Comment by digish777** [comment] 2018-09-05 06:27
+1

**Comment by mmroczka** [comment] 2018-09-07 19:17
+1

**Comment by devtanna** [comment] 2018-09-27 11:58
+1

**Comment by real-napster** [comment] 2018-11-15 09:02
+1

**Comment by leemorton** [comment] 2018-12-04 07:53
+1

**Comment by ToyMakerGR** [comment] 2018-12-06 15:35
+1

**Comment by WhiteRabbit-BI** [comment] 2019-01-03 10:06
Is there any progress on this? It's annoying little things like this that keep sending me back to SSMS.

**Comment by devtanna** [comment] 2019-01-03 15:23
I don't think so :/ sadly for Mac users this (azure data studio) is the
only choice as far as I know

**Comment by Shawson** [comment] 2019-01-04 13:02
Same I've also switched back to ssms

**Comment by qJake** [comment] 2019-01-07 18:46
+1

How could anyone think that 120px as a constant default column width wouldn't be annoying? You can't even fit a date into that small of a column!

Please add the following options:

* `resultsGrid.defaultColumnWidth`
    * A value in px, or
    * `"sizeToColumnName"`, or
    * `"stretchToFit"`
* `resultsGrid.maximumStretchWidth`
    * A value in px, where if `resultsGrid.defaultColumnWidth` is `"stretchToFit"`, specifies the absolute maximum width in px that the colum will stretch

I think this would satisfy most people!

**Comment by kburtram** [comment] 2019-01-07 19:54
We're aware that this is an annoying issue that significantly impacts the SQL editing experience.  We'll target getting a fix for Feb. (Jan is already basically done).  The problem was we had a large performance regression with the initially implementation of this feature and need to come up with a different implementation approach.

**Comment by simonsabin** [comment] 2019-01-08 08:50
What is your implementation for this. Is it to size based on the visible rows, first X rows or all of the rows.

For me having the first is the critical one. Once you get into scrolling you are using the mouse and thus resizing a column isn't too bad. 

The secondary is for fixed data types like date time, there should just be a size that works all the time, because the length is static

**Comment by anthonydresser** [comment] 2019-01-09 21:55
This is merged in under a preferences flag

**Closed by anthonydresser** 2019-01-09 21:55 UTC
Labels: feature gap, feature request, query editor

**Comment by juliermecarvalho** [comment] 2019-01-11 16:37
+1

**Comment by kburtram** [comment] 2019-01-11 17:38
@simonsabin the implementation @anthonydresser merged (https://github.com/Microsoft/azuredatastudio/pull/2778) calculates the size based on using the HTML DOM to measure all the visible cells.  Apparently this works well most the time, but has some problems with particular types of values (I think large BLOBs and VARCHARS, IIRC).

I'll post an insiders build including that change to get some feedback.  If the perf degradation is noticeably hurting the experience we'll look into using heuristics such as fixed sizes for various data types, or guessing sizes based on the content of cells, etc.

**Comment by simonsabin** [comment] 2019-01-11 17:40
Biggest gripe is truncation of short columns.

Simon Sabin
Director Engineering Sabin.io
Founder SQLBits
Microsoft Regional Director & MVP

________________________________

**Comment by benjaminmiao** [comment] 2019-01-17 01:47
Why not use the same implementation as SSMS?

**Comment by qJake** [comment] 2019-01-17 17:51
@benjaminmiao Probably because SSMS uses a native Windows GridView control, while ADS uses an HTML-based frontend. 😉

**Comment by benjaminmiao** [comment] 2019-01-18 01:31
@qJake What I mean is to use the same logic behind SSMS to calculate the columns width. not the same width for all column regardless its content or type :smile:

**Comment by richardtallent** [comment] 2019-01-19 23:39
Is the grid aware of the datatype of the column being returned? If so, it should be childsplay to establish a reasonable default width for every data type other than varchar-ish columns, without having to look at the data. The biggest annoyances in my case have been with number, date, bit (too wide), and uniqueidentifier columns.

**Comment by touringsedan** [comment] 2019-02-06 15:43
+1
Also flipping back to SSMS.

**Comment by devtanna** [comment] 2019-02-06 15:44
Anyone has any idea when this feature will be released?

**Comment by kburtram** [comment] 2019-02-06 16:25
The feature is available in the latest insider build available under https://github.com/Microsoft/azuredatastudio/releases.  It can be enabled with the following setting `"resultsGrid.autoSizeColumns": true`.  This will also be included in the February stable release planned for next week.

**Comment by touringsedan** [comment] 2019-02-06 18:17
Awesome. Thank you. Installed 1.4.3, enabled setting and auto-width is working.

**Comment by rrgiles** [comment] 2019-02-17 23:12
Is the autoSizeColumns feature going to be carried into the Table object so it can be used when building a Dashboard that produces tables?
