### ISSUE TITLE
Edit properties of a server without recreating the connection

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#5158] opened 2019-04-23 17:52 UTC
PowerUser will modify server properties relatively often. Current experience is that user will need to reconnect and go to Advanced Properties. There is currently not a way to modify the properties of an existing connection like in SSMS.

Feature request is to have a way to modify advanced properties on an existing connection without having to reconnect, especially when managing many connections.

**Comment by westandy-dcp** [comment] 2019-09-10 19:00
Is there an ETA on this?  Seems like it'd be an easy feature to add.  But what do I know?

**Comment by kburtram** [comment] 2019-09-10 19:38
@westandy-dcp this should be a pretty easy feature to add.  I'll see if I can get someone to look into this in the next few weeks (we're all working on various other tasks most the time).

In the meantime, the two "workarounds" we've suggested are:

1. The connection metadata is stored in the User Settings file.  If you use the `Open Settings (JSON)` command you can edit directly there.

2, If you open the Connection Dialog and select the connection from the Recent Connections pane, then edit the connection properties, then connect to the server, the edited properties should be persisted back to the saved connection metadata.

Please let me know if either of these approaches doesn't work.

**Comment by kburtram** [comment] 2020-02-25 22:20
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/1339.

**Closed by kburtram** 2020-02-25 22:20 UTC
Labels: Area - Connection, Enhancement
