### ISSUE TITLE
when viewing index properties, the popup window reported an exception

### ISSUE THREAD

**Issue by MasterYoki** [microsoft/azuredatastudio#7590] opened 2019-10-09 06:18 UTC
TITLE: Microsoft SQL Server Management Studio
------------------------------

调用的目标发生了异常。 (mscorlib)

------------------------------
ADDITIONAL INFORMATION:

未能加载文件或程序集“Microsoft.SqlServer.MaintenancePlanTasks, Version=15.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040) (Microsoft.SqlServer.Management.RelationalEngineTasksExtended)

------------------------------

未能加载文件或程序集“Microsoft.SqlServer.MaintenancePlanTasks, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

------------------------------
BUTTONS:

OK
------------------------------

**Comment by Charles-Gagnon** [comment] 2019-10-09 14:29
Thank you for the report @MasterYoki! This appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/7258 so I'll close this one - you can follow that issue for any updates on our end.

**Closed by Charles-Gagnon** 2019-10-09 14:29 UTC
