### ISSUE TITLE
Add Booksmarks

### ISSUE THREAD

**Issue by MrAlex6204** [microsoft/azuredatastudio#2131] opened 2018-08-02 21:18 UTC
This feature will be awesome, because I have files with a bunch of queries and are very long
So is very tedious try to find a code scrolling up & down 

- SQL Operations Studio Version:
Version 0.32.2-insider
Commit 461a158ac32ac67f17158c931f0c84fc38478341
Date 2018-07-26T20:59:24.143Z
VS Code 1.23.1
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by MattIrv** [comment] 2018-08-02 23:34
We don't currently have plans for this but it might be a great idea for a community-contributed extension. Also it's possible to install extensions using the "Install from VSIX" command on the command palette so if you already use a VS Code extension that does this you might be able to download the vsix and install it yourself in SQL Ops Studio (though not all VS Code extensions work in Ops Studio)

**Comment by kburtram** [comment] 2021-09-10 18:41
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/13645

**Closed by kburtram** 2021-09-10 18:41 UTC
Labels: Enhancement
