### ISSUE TITLE
Login failed for user '<token-identified principal>' - connection lost after a period of time

### ISSUE THREAD

**Issue by philipnye** [microsoft/azuredatastudio#16970] opened 2021-09-02 16:33 UTC
Issue Type: <b>Bug</b>

1. Connect to database hosted on Azure SQL Database using Azure Active Directory - Universal with MFA Support. This works successfully - I'm able to query the database as expected. (Making this a different issue to https://github.com/microsoft/azuredatastudio/issues/10298, I think.)
2. Leave the Azure Data Studio tab for a certain amount of time (I'd struggle to say how long - at most ~an hour rather than days), then try running a query.
3. Query fails with the following message:

```
Msg 18456, Level 14, State 233, Line 1
Login failed for user '<token-identified principal>'. Token is expired.
```

I have to reconnect in order to run the query.

What I would have expected to happen: Azure Data Studio refreshes tokens when they expire, saving me from erroring and having to reconnect

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.3.1
azdata-sanddance|msr|3.3.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by Charles-Gagnon** [comment] 2021-09-02 16:48
Closing as a duplicate of #10352 - there's an open PR right now to fix this issue for query editors : #16936

**Closed by Charles-Gagnon** 2021-09-02 16:48 UTC
