### ISSUE TITLE
Query plan not displayed for Synapse query

### ISSUE THREAD

**Issue by Pedro-Martinez** [microsoft/azuredatastudio#10842] opened 2020-06-10 02:06 UTC
Version: 1.19.0-insider (user setup)
Commit: 22d7c9083eba69683a9e36ec1f1e74c7981a7626
Date: 2020-06-09T05:32:54.756Z
VS Code: 1.46.0
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click Explain
2. Query plan not displayed.. only Results and Message

**Comment by yualan** [comment] 2020-06-12 16:48
After following up with Pedro, it looks like query plans do not show up for Azure SQL DW (Synapse). Query plans work for other SQL connections.

**Comment by mwc360** [comment] 2021-03-02 18:11
Any update on this? I would love to move from SSMS to ADF for Synapse development but the lack of generating a graphical estimated plan is a deal breaker. This should work just like SSMS for est. query plans. After this, please implement graphical d-sql query plan. 

I hate the fact that for Synapse development i have to work in SSMS and then copy XML d-sql plans to visual studio so i can format the XML to understand how scripts need to be tuned.

**Comment by kburtram** [comment] 2021-08-18 02:43
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/2273.

**Closed by kburtram** 2021-08-18 02:43 UTC
Labels: Bug, Area - Query Plan, Triage: Done
