### ISSUE TITLE
Tables folder in the Connections tab won't load

### ISSUE THREAD

**Issue by Chewieez** [microsoft/azuredatastudio#19169] opened 2022-04-21 15:04 UTC
Issue Type: <b>Bug</b>

Connect to a database
Expand the database in the Connections sidebar tab
Expand the Tables folder

The tables folder inside the Connections sidebar tab times out and will not load the tables for a database. When I open the database details in a tab, all the tables load in the Search list. The sidebar times out. 

Azure Data Studio version: azuredatastudio 1.36.0 (0704471e6b4a79f0c2c2425b22dc6bee60a1c2a8, 2022-04-19T18:21:59.017Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-data-inspector|ern|0.5.0
azuredatastudio-select-top-n|jim|0.0.5
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.13.1
whoisactive|Mic|0.1.4
sqlops-spexecutesql-to-sql|pej|1.0.1
ADS-add-columns|sof|0.0.12
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(3 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment] 2022-04-21 16:30
Duplicate of https://github.com/microsoft/azuredatastudio/issues/19166

**Closed by Charles-Gagnon** 2022-04-21 16:30 UTC

**Comment by kburtram** [comment] 2022-04-21 16:39
@Chewieez  could you please add error logs to https://github.com/microsoft/azuredatastudio/issues/19166 following instructions on that issue, if possible?  Thanks!
