### ISSUE TITLE
OS X - cannot make connections: constantly loading, "cannot read property 'connection' of undefined"

### ISSUE THREAD

**Issue by deltaGPhys** [microsoft/azuredatastudio#17530] opened 2021-10-28 20:33 UTC
When I opened it today, all of the connections were stuck in a perpetual loading state, and the Locading contexts... bit is at the top of all notebooks. If I try to add a new connection, the connectiontype dialog doesn't open and I get a spinning wheel forever. Can't close the connection page. Updated to latest version, didn't help.

Error: 
```
  ERR Cannot read property 'connection' of undefined: TypeError: Cannot read property 'connection' of undefined
    at E.get uiController [as uiController] (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:68703)
    at E.handleShowUiComponent (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:69644)
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:72443
    at i.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:129:1835)
    at F.onProviderTypeSelected (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:57855)
    at F.render (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:56956)
    at E.doShowDialog (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:72731)
    at E.showDialogWithModel (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:71146)
    at E.showDialog (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2789:71700)
    at As.showConnectionDialog (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2554:16711)
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1633:50296
    at i.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:129:1835)
    at HTMLAnchorElement.<anonymous> (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:401:4374)
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:188:47)
    at ZoneTask.invokeTask [as invoke] (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:496:34)
    at invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1540:14)
    at HTMLAnchorElement.globalZoneAwareCallback (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1566:17)
```

**Comment by kburtram** [comment] 2021-11-01 21:33
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/17535.  Please leave any additional comments on that issue.  Thanks!

**Closed by kburtram** 2021-11-01 21:33 UTC
Labels: Bug, Area - Connection
