### ISSUE TITLE
"Go to/Peek definition" are broken

### ISSUE THREAD

**Issue by mshakurov** [microsoft/azuredatastudio#13434] opened 2020-11-16 17:15 UTC
Issue Type: <b>Bug</b>

The functions "go to definition" and "show definition" are broken!

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.6.0
db-snapshot-creator|sea|0.1.0

</details>

**Comment by kburtram** [comment] 2021-08-23 18:54
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/13867 since we use the same functions for peek and scripting.  Also could be related to https://github.com/microsoft/azuredatastudio/issues/13311 but it's unclear since the bug report is missing details regarding in what way the definition features are broken.  Please add context to #13867 if applicable.  Thanks!

**Closed by kburtram** 2021-08-23 18:54 UTC
Labels: Bug, Area - Language Service, Triage: Done
