### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by MahdiAckerman** [microsoft/azuredatastudio#19013] opened 2022-04-12 11:57 UTC
Issue Type: <b>Feature Request</b>

please add a feature to search between stored procedures and tables name . thanks

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by Charles-Gagnon** [comment] 2022-04-12 18:37
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12932

**Closed by Charles-Gagnon** 2022-04-12 18:37 UTC
