### ISSUE TITLE
SQL Server Profiler -- cannot set property 'actionBarContext' of undefined

### ISSUE THREAD

**Issue by JStanl** [microsoft/azuredatastudio#10394] opened 2020-05-14 13:52 UTC
- Azure Data Studio Version:Version: 1.17.1 (user setup)
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-30T00:16:35.943Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open Azure Data Studio
2. Connect to database
3. ALT+P

![Annotation 2020-05-14 095013](https://user-images.githubusercontent.com/65350726/81942636-5c22be00-95c8-11ea-9deb-c698e76077a4.jpg)

**Comment by JStanl** [comment] 2020-05-14 13:57
This extension worked fine for me yesterday. I have uninstalled/disabled the extension multiple times today trying to get it to work. Last resort I guess will be to uninstall Azure Data Studio and reinstall it.

**Comment by kburtram** [comment] 2020-05-14 15:32
@JStanl I think this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/10282.  To workaround the issue you can open a folder or close the currently open folder, which will reset the HotExit document list.  The issue is fixed in the latest insider build and the fix will ship in May release next week.  Sorry for the inconvenience.  Please let me know if the workaround doesn't work.

**Comment by alanrenmsft** [comment] 2020-05-14 19:06
@JStanl , please reactivate the issue if you are still seeing the issue after May release.

**Comment by Charles-Gagnon** [comment] 2020-08-11 16:59
Reopening this since @ymkumar is apparently running into this issue with the 1.20.1 build.

@alanrenmsft did we ever figure out what the issue was here?

@ymkumar Please include your ADS version info here for confirmation

**Comment by ymkumar** [comment] 2020-08-11 17:00
here is the ADS version
![image](https://user-images.githubusercontent.com/22806495/89926240-6ea59700-dbb9-11ea-8fec-a8c311336b79.png)

**Comment by alanrenmsft** [comment] 2020-08-11 17:03
@ymkumar Please follow what Karl pointed out in the other issue: https://github.com/microsoft/azuredatastudio/issues/10492#issuecomment-672090036

**Comment by kburtram** [comment] 2020-08-11 17:33
IIRC, the issue was bad state cached by an earlier version, so the problem can repro in any future ADS build if that bad state is still cached.  Open\closing a folder should reset the "open document" cache.  Worst case, the entire application cache can be removed but that would lose all application state and revert to a "first launch" state.

**Comment by alanrenmsft** [comment] 2020-08-11 18:12
worked with @ymkumar offline and the problem has been solved for him.

steps to resolve the issue for whoever run into this:
1. In the main menu, under "File", select 'Open Folder'
![image](https://user-images.githubusercontent.com/13777222/89932594-bd0b6380-dbc2-11ea-8928-65b0bbdc3f6a.png)
1. Pick a folder and press "Select Folder"
![image](https://user-images.githubusercontent.com/13777222/89933097-6a7e7700-dbc3-11ea-8280-ad00e65191ef.png)
1. close all editors and restart Azure Data Studio

**Closed by alanrenmsft** 2020-08-11 18:12 UTC
Labels: Area - SQL Profiler, Bug, Triage: Done
