### ISSUE TITLE
Copy Results mixing up column order

### ISSUE THREAD

**Issue by maracucho1997** [microsoft/azuredatastudio#8323] opened 2019-11-13 17:41 UTC
Issue Type: <b>Bug</b>

When copying Results, the columns are not getting put in the clipboard in the same order as the output in the Results. Using Copy With Headers brings the headers in the right order, but the data in the columns does not belong to the same header. This doesn't happen every time, but I can reproduce it with certain queries.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18363

For example, using this query and copying to excel or notepad the third field when pasting is a number field from the 11th column.

Query:
```
SELECT IdNum = 10701, CaseStatus = 'Closed', DateTimeField = '2019-03-20 16:23:00.000', DateField = '2019-03-28'
, DateField2 = '2019-04-01'
, DateFieldNULL = NULL, DateField3 = '2019-06-06'
, IntNull = NULL, Int1 = 1, Int2 = 2, Int3 = 3, IntNull2 = NULL; 
```

Results from Copy With Headers:
IdNum	CaseStatus	DateTimeField	DateField	DateField2	DateFieldNULL	DateField3	IntNull	Int1	Int2	Int3	IntNull2
10701	Closed	3	NULL	2019-03-20 16:23:00.000	2019-03-28	2019-04-01	NULL	2019-06-06	NULL	1	2

![image](https://user-images.githubusercontent.com/57723542/68789085-57298580-060a-11ea-8d0e-dca4cb03b7a4.png)

**Comment by Charles-Gagnon** [comment] 2019-11-13 17:44
Closing as a duplicate of #8210

This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release. Sorry about the inconvenience!

**Closed by Charles-Gagnon** 2019-11-13 17:44 UTC
Labels: Area - Query Editor, Bug
