### ISSUE TITLE
We need the default text cell size of the Notebooks to be the same as code cells.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3388] opened 2018-12-03 19:48 UTC
Issue Type: <b>Bug</b>

Make sure the default text cell size is the same as the code cells.

![image](https://user-images.githubusercontent.com/22312581/49397706-36199e80-f6f1-11e8-9ab6-72020f6f0c43.png)

Azure Data Studio version: azuredatastudio 1.3.5-insider (6912e3893ede7d13afb54acc4571764b8ad78469, 2018-11-30T03:22:16.978Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (23.92GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment] 2019-03-16 02:35
Dupe of many other bugs. Fixed for March.

**Closed by chlafreniere** 2019-03-16 02:35 UTC
Labels: notebooks
