### ISSUE TITLE
Connection dropped / is not maintained when saving / opening scripts o

### ISSUE THREAD

**Issue by stefanodcd** [microsoft/azuredatastudio#16435] opened 2021-07-26 04:05 UTC
Issue Type: <b>Bug</b>

When opening saved scripts with a current connection, there is no option to run the script. I have to open a new query window and then copy and past to that window to run the script. 

When saving a new script from a current connection window, the current connection drops. 

Azure Data Studio version: azuredatastudio 1.31.0 (a430fd2592763ef4c4a406821967e4b7b2b3d876, 2021-07-20T19:49:59.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-07-26 15:53
It's a little unclear what the scenario that you're describing is - could you please provide step-by-step instructions for what you're doing to open this file?

**Comment by Charles-Gagnon** [comment] 2021-07-26 18:35
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/16427 for now to consolidate the issues since this seems to be the same as that. Let me know if you think yours is a separate issue.

**Closed by Charles-Gagnon** 2021-07-26 18:35 UTC
Labels: Area - Query Editor, Bug, Triage: Needed
