### ISSUE TITLE
Problems pane for Notebook editors shows each editor as separate section

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11454] opened 2020-07-21 16:50 UTC
1. Open Notebook editor
1. Add a couple code cells
1. Type some invalid syntax in each of them

Expected : Problems pane shows one section for the Notebook with the problems listed

Actual : Separate section for each code editor - with names that are impossible to map back to the original Notebook. Clicking on these problems then opens a new query editor window with that text instead of opening the Notebook editor that had the problem in the first place

![image](https://user-images.githubusercontent.com/28519865/88083138-87310d00-cb37-11ea-8ad9-7c1d0a53d3ba.png)

**Comment by chlafreniere** [comment] 2021-02-11 04:45
Dupe of #7151

**Closed by chlafreniere** 2021-02-11 04:45 UTC
Labels: Area - Notebooks, Bug, Triage: Done
