### ISSUE TITLE
Linked Servers

### ISSUE THREAD

**Issue by AhsenBaig** [microsoft/azuredatastudio#1276] opened 2018-04-26 15:59 UTC
Issue Type: <b>Bug</b>

Linked Servers when you right click on one of the servers you can't expand the tables/view. Also when you right click on the linked server select new query it just opens a new blank SQL Query not like SSMS which opens up the. However we can still run the commands by manually entering in the syntax. 

SELECT *
  FROM [PROD_LinkServer]..[SCHEMA].[TABLE]
GO

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz (8 x 2300)|
|Memory (System)|16.00GB (10.20GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.28.1
server-report|Mic|0.1.1
whoisactive|Mic|0.1.0
sql-search|Red|0.1.1

</details>
Reproduces without extensions

**Comment by kburtram** [comment] 2021-04-23 17:45
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/2217 as that issue is encompasses this enhancement request.

**Closed by kburtram** 2021-04-23 17:45 UTC
Labels: Enhancement
