### ISSUE TITLE
Data-Tier Application Wizard menu item on CMS opens connection dialog even if connected

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6342] opened 2019-07-10 00:08 UTC
1. Connect to CMS and expand to registered server node
2. Right click on server and select Data-tier Application Wizard
3. Connection dialog pops up instead of using connection from node (the dialog is populated with correct information though)

Note this seems to work fine for OE (launches the wizard directly)

**Comment by abist** [comment] 2019-07-15 23:24
This issue is actually a DacFx issue and not Data Explorer. It's tracked here - https://github.com/microsoft/azuredatastudio/issues/3486.

**Comment by kburtram** [comment] 2021-08-17 19:42
Closing as duplicate of #3486 based on previous comment.

**Closed by kburtram** 2021-08-17 19:42 UTC
Labels: Bug, Area - DacFX, Triage: Done
