### ISSUE TITLE
Can't Connect to Azure Government

### ISSUE THREAD

**Issue by KevinDMack** [Microsoft/azuredatastudio#3342] opened 2018-11-29 15:48 UTC
Currently when I go to the Azure Tab within, I am only given the option to connect to Azure Commercial through the microsoft.com/devicelogin and does not allow using the deviceloginus version for the government sovereign cloud.

**Comment by kevcunnane** [comment] 2019-05-02 17:34
This is a duplicate of #3013 and I'll use that for tracking so we just have 1. That's being put in the June bucket and @kenvanhyning should be kicking off the approval process.

**Closed by kevcunnane** 2019-05-02 17:34 UTC
Labels: Area: Azure, Area: Connection
