### ISSUE TITLE
.SCMP files open as XML not a comparison

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#19227] opened 2022-04-27 11:35 UTC
Issue Type: <b>Bug</b>

When opening an .SCMP file using File > Open File (Ctrl+O) it open as XML file, not as a comparison.  This also occurs when using File > Open Recent > and then selecting an .SCMP file from the list.

The same file works fine when starting from Database Projects (icon on left-bar) > right-click project, choose Manage > click Schema Compare > click Open .scmp file > choose .scmp file from location.

Extension version: 0.16.1
Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment] 2022-04-27 20:39
closing as duplicate of #15880

**Closed by kisantia** 2022-04-27 20:39 UTC
Labels: Bug, Area - Schema Compare, Triage: Needed
