### ISSUE TITLE
Query doesn't show any results or has problems with display

### ISSUE THREAD

**Issue by CodingContinuum** [microsoft/azuredatastudio#25015] opened 2023-11-21 19:29 UTC
Type: <b>Bug</b>

Simple select query.
Result is 33 rows. Nothing is shown in the result pane.  Some rows have html in it.

Mssage is:
8:21:38 PMStarted executing query at Line 1
(33 rows affected)
Total execution time: 00:00:00.047

Happens to multiple computers / laptops!

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (21.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.21.0
sql-assessment|Mic|0.6.4
sql-migration|Mic|1.4.11
simple-data-scripter|sea|0.1.6

</details>

**Comment by cheenamalhotra** [comment] 2023-11-21 22:56
Duplicate of https://github.com/microsoft/azuredatastudio/issues/24903 https://github.com/microsoft/azuredatastudio/issues/24713, could you please upload logs for investigation on the related issues?
Please follow the same for further updates.

**Closed by cheenamalhotra** 2023-11-21 22:56 UTC
Labels: Bug, Area - Query Editor, Triage: Done
