### ISSUE TITLE
Database dropdown only shows current database

### ISSUE THREAD

**Issue by sandermvanvliet** [microsoft/azuredatastudio#10816] opened 2020-06-09 06:32 UTC
Issue Type: <b>Bug</b>

- Open a new query window
- Connect to a SQL Server with multiple databases leaving the `database` property empty in the connection tab
![image](https://user-images.githubusercontent.com/2393265/84113713-61d6bc80-aa2b-11ea-952e-b154870d6ff1.png)
- Query window opens on `master`
- Open database dropdown and select a different database
![image](https://user-images.githubusercontent.com/2393265/84113819-934f8800-aa2b-11ea-8b98-c4075ee4ad49.png)
- Database is now changed for the query window
- Open database dropdown

at this point only `master` and the selected database are visible. All other databases on the server are no longer displayed.
![image](https://user-images.githubusercontent.com/2393265/84113890-afebc000-aa2b-11ea-8ed9-3866ea6ec175.png)

As on Azure SQL you can't simply `USE [database]` this is  a bit suboptimal to change connections all the time...

Azure Data Studio version: azuredatastudio-insiders 1.19.0-insider (6e3d960d1db2a9544db18b20e0e0db5e22ccbc07, 2020-06-08T05:37:04.177Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (10.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-06-09 16:11
@aasimkhan30 Confirmed that this is a regression due to https://github.com/microsoft/sqltoolsservice/pull/957

We should consider trying to connect to master first - and if that fails then fall back to the current DB. Or at least having that be an option on listDatabases so that only callers that care about getting all the possible DBs can control it since we might not want the perf hit in other cases.

**Comment by kburtram** [comment] 2020-06-10 00:37
Fixed in release/1.19 branch

**Closed by kburtram** 2020-06-10 00:37 UTC
Labels: Approved, Area - Query Editor, Bug, Triage: Done
