### ISSUE TITLE
Notebooks: links in markdown are not functional

### ISSUE THREAD

**Issue by angdesign** [Microsoft/azuredatastudio#5184] opened 2019-04-24 19:16 UTC
- Azure Data Studio Version: 1.7.0-insider
- System: OSX Mojave 10.4.4

Steps to Reproduce:

1. start a new notebook
2. Create a text/markdown cell
3. enter an example link in markdown (bracket followed by parenthesis)
4. attempt to click on the resulting link - nothing happens

**Comment by kevcunnane** [comment] 2019-04-24 19:21
This is a dupe of #3440. Tracking this there. The workaround is Ctrl+Click (Windows/Linux) or Cmd+Click (macOS). @chlafreniere we should look at fixing this given it's a consistent piece of feedback.

**Closed by kevcunnane** 2019-04-24 19:21 UTC
Labels: Bug
