### ISSUE TITLE
Database selection when using dark theme nearly illegible

### ISSUE THREAD

**Issue by yellowstar** [Microsoft/azuredatastudio#5224] opened 2019-04-26 09:02 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Open Data Studio, select a dark theme, e.g.  Dark Azure Data Studio, connect to a Server, then open a new query, now open the list of available databases; the selected database is shown with white texxt on a dark grey background, but all the other available databases are shown with black foreground text and a dark grey background making them all but illegible.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (7.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
gitlens|eam|9.6.1
material-icon-theme|PKi|3.7.0
sql-search|Red|0.3.2
poor-sql-formatter|WSR|0.1.0

(2 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/1837790/56796385-56fe9f80-680a-11e9-9878-354f388df691.png)

**Comment by kburtram** [comment] 2019-04-26 21:15
Closing as a duplicate of #4741.  This will be fixed in next release.

**Closed by kburtram** 2019-04-26 21:15 UTC
