### ISSUE TITLE
Silent/Very Silent Install results in application opening after installation

### ISSUE THREAD

**Issue by stelawton** [microsoft/azuredatastudio#549] opened 2018-01-25 16:20 UTC
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:

Run the below command

`sqlops-windows-setup-0.25.4.exe /VERYSILENT`

After installation SQL OPs application opens on the users desktop automatically.

Looking in the log file you see the following final entry

2018-01-25 16:06:58.659   Run as: Original user
2018-01-25 16:06:58.659   Type: Exec
2018-01-25 16:06:58.659   Filename: C:\Program Files\SQL Operations Studio\sqlops.exe

Having looked at the Win32 installer at:

https://github.com/Microsoft/sqlopsstudio/blob/master/build/win32/code.iss

I believe adding the "skipifsilent" flag to the line:

```
[Run]
Filename: "{app}\{#ExeBasename}.exe"; Description: "{cm:LaunchProgram,{#NameLong}}"; Tasks: runcode; Flags: nowait postinstall; Check: WizardSilent
```

would resolve this issue and give a true silent install. Documentation entry for SkipIfSilent from http://www.jrsoftware.org/ishelp/index.php?topic=runsection 

```
skipifsilent
Valid only in a [Run] section. Instructs Setup to skip this entry if Setup is running (very) silent.
```

**Comment by kburtram** [comment] 2018-02-14 00:54
@corivera I've reactivated this issue because I think we reverted the change due to auto-update bug.  Please close again if I'm incorrectly reactivating.

**Comment by michalmiddleton** [comment] 2018-06-12 17:45
I can confirm on 0.30.4 with /silent

**Comment by kburtram** [comment] 2018-07-19 16:29
@Matteo-T I think this is related to the issue you saw with SQL Ops auto-starting after silent install.  There's a conflict with our auto-update mechanism and this switch that we'll need to resolve.

**Comment by Matteo-T** [comment] 2019-04-03 03:47
THanks @kburtram - I totally forgot about this one. Sorry for the dupe. :-(

**Comment by shikhy** [comment] 2020-08-14 13:29
Have you tried passing the response file along with the Silent/Very Silent switch?

**Comment by Charles-Gagnon** [comment] 2020-08-17 15:57
As mentioned in https://github.com/microsoft/azuredatastudio/issues/11652 `/MERGETASKS=!runcode` option. Let us know if that doesn't work.

**Comment by kburtram** [comment] 2021-04-23 17:30
Closing out this older issue with the workaround suggested in #11652.  Please let us know if you're still impacted by this bug.

**Closed by kburtram** 2021-04-23 17:30 UTC
Labels: Area - Acquisition, Bug
