### ISSUE TITLE
Modifying book toc.yml file causes a duplicate book entry to be opened in viewlet

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#9924] opened 2020-04-09 22:18 UTC
Currently we track changes to the book table of contents file (toc.yml) so that the book viewlet can be updated with the new book contents as needed. But when modifying the toc.yml file directly, one or more duplicate entries for that toc's book are opened in a viewlet, although the actual content changes are correct in each book entry. Closing any of these entries using Close Jupyter Book also causes all of them to be closed. Modifying the toc.yml file further causes the number of duplicates to increase and decrease randomly.

CC @MaddyDev

**Comment by MaddyDev** [comment] 2020-04-10 05:28
Duplicate of #9781

**Closed by MaddyDev** 2020-04-10 05:28 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
