### ISSUE TITLE
The "Database Size" widget in "Server dashboard" does not show the size value in the diagram on some localized systems 

### ISSUE THREAD

**Issue by SandroG** [microsoft/azuredatastudio#542] opened 2018-01-24 22:38 UTC
- SQL Operations Studio Version:
0.25.4

Steps to Reproduce:
Environment: Windows 10  localized in Italian (or the same should be reproducible by setting the system language to Italian or French or German, so that the decimal separator is ',' (comma)).
Open SqlOpsStudio, connect on a Sql Server instance and click on a database to see the "Server dashboard". The Database Size widget shows only a list of databases without the size value.

The same problem occurs if you try to see the chart for a generic query that produces a non-integer number.

**Comment by bigleka** [comment] 2018-04-23 19:51
On Brazilian Portuguese too

**Comment by kburtram** [comment] 2021-04-23 17:28
Closing out older issues that we won't be able to fix in an upcoming milestone.  We've made significant updates to the problem in this area so it is possible the issue is resolved in the latest release.  Thanks for reporting the bug!

**Closed by kburtram** 2021-04-23 17:28 UTC
Labels: Area - Charting, Bug
