### ISSUE TITLE
Update has stopped saved templates opening a query tab

### ISSUE THREAD

**Issue by TunnyF24** [microsoft/azuredatastudio#16451] opened 2021-07-27 16:09 UTC
I installed an update today that has stopped all my saved/existing queries opening in a query tab.

they're just opening as plain text

I then tried the below to re-save them as .sql file types

Open a new query 
![image](https://user-images.githubusercontent.com/88048134/127187051-092a03ec-64c4-478d-ab7f-418d13e04402.png)

then write my script into there
![image](https://user-images.githubusercontent.com/88048134/127187374-8d6af573-ebf7-4506-9cb6-d0ee5baeb726.png)

save this, and then reopen it, it's showing as the below, and won't allow me to run anything, the options aren't showing at the top
![image](https://user-images.githubusercontent.com/88048134/127187675-1c951620-164a-4767-a88d-ed5d3390d47e.png)

It's being saved as a .sql file type. my templates before were just files that I had sent to me from another user in our company and have been working fine up until today.

**Comment by Charles-Gagnon** [comment] 2021-07-27 16:29
Duplicate of https://github.com/microsoft/azuredatastudio/issues/16436 - see that thread for some things to try to fix this issue. Otherwise I'm working on a fix for this and we plan to release this as a hotfix once the issue is resolved.

In the meantime if none of the workarounds (including using the insiders builds) work for you then it may be best for you to go back to 1.30 until the hotfix is released.

**Closed by Charles-Gagnon** 2021-07-27 16:29 UTC
