### ISSUE TITLE
Missing index recommendation syntax

### ISSUE THREAD

**Issue by ParseBang** [microsoft/azuredatastudio#20110] opened 2022-07-20 16:38 UTC
Issue Type: <b>Bug</b>

When using "Estimated Plan" and there is a missing index recommendation, the generated create index syntax puts the same column name in the index column list and INCLUDE column list. This syntax is invalid and fails with:
Msg 1909, Level 16, State 2, Line 
Cannot use duplicate column names in index. Column name 'Column' listed more than once.

/*
Missing Index Details from untitled:SQLQuery
The Query Processor estimates that implementing the following index could improve the query cost by %.
*/

/*
USE [MyDatabase]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [schema].[Table] ([Column1])
INCLUDE ([Column1],[Column2])
GO
*/

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (16.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.48.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0

</details>

**Comment by aasimkhan30** [comment] 2022-10-05 18:28
duplicate of #20259

**Closed** 2022-10-05 18:28 UTC
Labels: Bug, Triage: Done, Area - Execution Plan
