### ISSUE TITLE
Wrong row order when copy result to clipboard

### ISSUE THREAD

**Issue by GrzegorzLyp** [microsoft/azuredatastudio#8211] opened 2019-11-04 19:53 UTC
Issue Type: <b>Bug</b>

Database WorldWideImporters

Query:
select top 100 OrderId from sales.orders order by OrderId

Copy whole Result column to clipboard (Ctrl+C)
Paste to notepad and the order is wrong

1
2
11
12
13
14
15
16
17
18
19
20
3
21
22
23
24
....

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (5.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
abs-ex|ABS|0.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.44.0
import|Mic|0.12.0
profiler|Mic|0.9.0
query-history|Mic|0.1.0
azdata-sanddance|msr|1.3.9
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by aaomidi** [comment] 2019-11-04 20:36
Duplicate of #8210

**Closed** 2019-11-04 21:40 UTC
