### ISSUE TITLE
Can't copy entire printed output in one go.

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#13774] opened 2020-12-11 10:02 UTC
Version: 1.25.1 (system setup)
Commit: e7eacc32c0d20bd4da843320c3bfac231b308c98
Date: 2020-12-11T01:59:24.271Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.Run a query that uses the print statement to output a lot of text, in my case a 400-odd line HTML file generate using bits of data from various tables in a database.
2.Using the mouse click and drag to highlight the entire output using the scroll wheel to move down. After selecting everything use the output scrollbar to move up and down to note that the entire output is highlighted.
3.Scroll to the bottom of the windows and press Ctrl+C to copy
4.In your favourite IDE open an empty file and paste into it. **WTH?!** It only pastes in the portion of printed output that was visible in the ADS windows at the time you pressed Ctrl+C! At present the only workaround to this bug is to change the split divider between query and output so that output section uses most of the available space, then copy/paste bit by bit - which is quite tedious as you may imagine.

**Comment by alanrenmsft** [comment] 2021-01-08 22:20
@peterlukerow I took a look at the code and I can confirm it is a design issue, we are using a tree component to render the messages pane, and the text selection is not being tracked, it might need some time to actually fix the issue of copy text from invisible rows.

But in your case, you want to select all text, fortunately, that is supported, you can use the 'Select All' context menu.
![image](https://user-images.githubusercontent.com/13777222/104070651-45b31d80-51bc-11eb-8803-a14513d83125.png)

hopefully this will save the time of going through multiple screens.

I will keep this issue open to track the issue copying text from the invisible rows

**Comment by peterlukerow** [comment] 2021-01-11 08:15
> @peterlukerow I took a look at the code and I can confirm it is a design issue, we are using a tree component to render the messages pane, and the text selection is not being tracked, it might take some time to actually fix the issue of copy text from invisible rows.
> 
> But in your case, you want to select all text, fortunately, that is supported, you can use the '**Copy All**' context menu.
> ![image](https://user-images.githubusercontent.com/13777222/104070651-45b31d80-51bc-11eb-8803-a14513d83125.png)
> 
> hopefully this will save the time of going through multiple screens.
> 
> I will keep this issue open to track the issue copying text from the invisible rows

Thanks for the update. You suggestion works, hurrah!

Now I just have to delete a couple of lines like "1 row(s) affected" before saving the file, but that's much quicker than what I was having to do before so big win.

**Comment by alanrenmsft** [comment] 2023-06-07 20:06
I am no longer able to reproduce the result inverted issue above with latest build. Please open a new issue if you still have problem with it.

**Comment by peterlukerow** [comment] 2023-06-08 08:32
@alanrenmsft You've closed the ticket because the extra problem of inversion of copy/paste is not reproducible.
However has the actual issue raised been fixed?

Yes there is the copy all option if that is what you want, but if you don't want everything then this bug not being fixed is still a problem.

**Comment by alanrenmsft** [comment] 2023-06-08 15:10
leave the issue open to track the issue of coping invisible messages

**Comment by alanrenmsft** [comment] 2023-06-09 21:03
close as dupe of https://github.com/microsoft/azuredatastudio/issues/2753

**Closed by alanrenmsft** 2023-06-09 21:03 UTC
Labels: Bug, Area - Query Editor, Triage: Done
