### ISSUE TITLE
OE sometimes shows spinning icon for server when I expand it...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#6228] opened 2019-07-01 16:32 UTC
Issue Type: <b>Bug</b>

No idea. It is random behavior.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.18922

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.40.0
azuredatastudio-postgresql|Mic|0.2.0
import|Mic|0.8.0
profiler|Mic|0.8.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.14.1

</details>

**Comment by Charles-Gagnon** [comment] 2019-07-01 16:50
Possibly dupe of #6128? @kburtram do you also only see that intermittently?

@uc-msft 

- What server are you connecting to? 
- Is it a specific server/servers or does it seem to happen to any server randomly? 
- Are you getting a pop up notification asking you to submit a bug when this happens? (there's another issue I'm tracking that I added this notification for, but if you're not seeing it then maybe this is another issue)
- Are there any errors in the dev console when this happens?
- Are you seeing this when connecting to multiple servers in quick succession or does it happen even when connecting to a single server?

**Comment by kburtram** [comment] 2019-07-01 19:06
@Charles-Gagnon I think the repro was pretty consistent.  But only occurred when connecting through a certain path.  It haven't seen this when expanding directly recently.

**Comment by Charles-Gagnon** [comment] 2019-07-02 14:13
I'm going to close this for now since we already have a couple other connecting issues. @uc-msft if you have more information to offer please add that here and I'll look into whether your issue is actually something new or just the similar issues we're seeing elsewhere.

**Closed by Charles-Gagnon** 2019-07-02 14:13 UTC
Labels: Area: Connection, Bug, Triage: Done
