### ISSUE TITLE
Unexpected Error Occurred while Connecting

### ISSUE THREAD

**Issue by stuartpa** [microsoft/azuredatastudio#8287] opened 2019-11-09 19:34 UTC
Issue Type: <b>Bug</b>

An unexpected error occurred while connecting. Please [file an issue](command:workbench.action.openIssueReporter) with the title 'Unexpected Error Occurred while Connecting' and include the log file [C:\Users\stuar\AppData\Roaming\azuredatastudio\logs\20191107T142237\renderer1.log](command:workbench.action.openLogsFolder)

[2019-11-07 14:22:37.502] [main] [info] update#setState idle
[2019-11-07 14:23:07.505] [main] [info] update#setState checking for updates
[2019-11-07 14:23:07.556] [main] [info] update#setState downloading
[2019-11-07 14:23:07.561] [main] [info] update#setState ready
[2019-11-09 11:32:43.215] [main] [error] webContents#will-navigate: Prevented webcontent navigation

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (86f8b3f9ecc15745be5e1bf8a531e94dfdf6cbbf, 2019-10-18T07:49:30.756Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.95GB free)|
|Process Argv|c:\temp\jupyter\books\bdc\draft |
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2019-11-10 19:40
Closing as a duplicate of #7897

**Closed by Charles-Gagnon** 2019-11-10 19:40 UTC
