### ISSUE TITLE
Can't connect without a password

### ISSUE THREAD

**Issue by mnavaor** [microsoft/azuredatastudio#22414] opened 2023-03-22 22:14 UTC
Issue Type: <b>Bug</b>

In the previous version, I was able to connect to a SQL Server Database that wasn't using password. But now, with the last update ADS is showing the error message: "Value cannot be null".

This is the error detail:

System.ArgumentNullException: Value cannot be null. (Parameter 'Password')
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.SetValue(String keyword, String value)
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.set_Password(String value)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.CreateConnectionStringBuilder(ConnectionDetails connectionDetails) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1418
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.BuildConnectionString(ConnectionDetails connectionDetails) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1374
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 674

Azure Data Studio version: azuredatastudio 1.42.0 (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:15:48.982Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|0.2.4
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.11.0
import|Mic|1.5.4
profiler|Mic|0.11.0
query-history|Mic|0.5.3
extra-sql-script-as|pac|0.5.0
sql-prompt|Red|0.2.12
sql-search|Red|0.4.0
simple-data-scripter|sea|0.1.6
code-settings-sync|Sha|3.4.3
poor-sql-formatter|WSR|0.1.0

(2 theme extensions excluded)

</details>

**Comment by cheenamalhotra** [comment] 2023-03-22 22:50
Hi @mnavaor 

When authenticating with 'SqlLogin', password is always needed. It seems your password is not read from credential store.. there's a known issue with passwords not read on update (#8918), that seems related here.

**Comment by cheenamalhotra** [comment] 2023-03-23 05:47
Closing as duplicate of #8918 
Let us know if you have additional info to share.

**Closed by cheenamalhotra** 2023-03-23 05:47 UTC
Labels: Bug, Area - Connection, Triage: Done
