### ISSUE TITLE
Issues working with tables in Synapse Databases

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#20709] opened 2022-10-03 16:59 UTC
- Azure Data Studio Version: 1.39.1 (also tested Insiders 1.40.1)
- OS Version: Windows 11

Steps to Reproduce:

#### When opening 'Table Designer'
1. Connect to a Azure Synapse server and navigate to a Database (e.g. master)
2. Create a new table using Table Designer
   - Notice the table designer fails to load and continues loading for a long time. It does load in the end, but takes many minutes to load.

#### When selecting 'Select Top 1000'
1. Navigate to any existing table or create a new table using Query.
2. Right click and select "SELECT TOP 1000".
   - Notice new tab doesn't open.
(noticed #20599 with same issue)

The same behaviors work fine with other databases and servers but fail for Azure Synapse.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment] 2022-10-11 19:02
select top 1000: dupe of https://github.com/microsoft/azuredatastudio/issues/20709, for table designer, it is not currently supported. I will hide the menu items for it.

**Comment by alanrenmsft** [comment] 2022-10-13 22:58
table designer is working now for Cheena, closing the issue.

**Closed by alanrenmsft** 2022-10-13 22:58 UTC
Labels: Area - Query Editor, Triage: Done, Area - Designer
