### ISSUE TITLE
I would like to be able to get my results as text like in SSMS

### ISSUE THREAD

**Issue by KyleStay** [microsoft/azuredatastudio#24386] opened 2023-09-12 20:03 UTC
Type: <b>Feature Request</b>

The results in the standard table view of Azure Data Studio can be pretty buggy. Having them as text like in SMSS would be helpful

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Disabled
Modes:

**Comment by cheenamalhotra** [comment] 2023-09-13 18:12
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/52
You may upvote the existing issue instead.

**Closed by cheenamalhotra** 2023-09-13 18:12 UTC
Labels: Area - Query Editor, Enhancement, Triage: Done
