### ISSUE TITLE
Script Database Trigger

### ISSUE THREAD

**Issue by ksoze84** [microsoft/azuredatastudio#16805] opened 2021-08-17 18:54 UTC
Version: 1.31.1
Commit: 65fb22cc7c36db9c53af1ed2fdbdf48f66c682be
Date: 2021-07-28T21:01:02.538Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.53-1-MANJARO

This is not about table triggers.

Currently there is not an easy way to Modify Database Triggers also known as DDL Triggers in Azure Data Studio. The only way i can update this type of trigger is using other machine running MSSQL

![image](https://user-images.githubusercontent.com/45209708/129782849-b057cf84-442a-429d-890d-b8c7e65f06f3.png)

An option to "Script as ..." is needed.

**Comment by kburtram** [comment] 2021-08-19 20:26
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/7980.  Please add any additional context to that issue if applicable.  I've moved #7980 to the committer triage board for prioritization review.  Thanks!

**Closed by kburtram** 2021-08-19 20:26 UTC
Labels: Area - Object Explorer, Enhancement, Triage: Done
