### ISSUE TITLE
query results empty (white page)  until I switch to Messages and back

### ISSUE THREAD

**Issue by r4ndom4is** [microsoft/azuredatastudio#8802] opened 2020-01-03 09:25 UTC
Issue Type: <b>Bug</b>

After a query completes I have to switch to Messages tab and then back to Resuts tab to see the resuts

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.2.0
azdata-sanddance|msr|1.3.9
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by ypedroo** [comment] 2020-01-03 11:41
This is happening with me too and now not only on the results tab but the whole screen.

Azure Data Studio version: azuredatastudio 1.14.1
OS version: Windows_NT x64 10.0.18363

**Comment by anthonydresser** [comment] 2020-01-03 19:24
Any repro steps? I haven't seen this or been able to repro the issue. Are there any errors in the log (F1 -> developer: show logs -> Window)

Could be related to #8795

**Comment by ypedroo** [comment] 2020-01-06 12:14
`[2020-01-06 08:21:35.716] [renderer1] [error] Error restoring editor grid widget: TypeError: Cannot read property 'getModel' of null (with state: {"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":1,"editors":[{"id":"workbench.editorInput.fileQueryInput","value":"{\"resource\":\"file:///c%3A/FonteDesenvolvimento/Scripts/ScriptsSelectResumoPedido.sql\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\FonteDesenvolvimento\\\\Scripts\\\\ScriptsSelectResumoPedido.sql\",\"_sep\":1,\"external\":\"file:///c%3A/FonteDesenvolvimento/Scripts/ScriptsSelectResumoPedido.sql\",\"path\":\"/c:/FonteDesenvolvimento/Scripts/ScriptsSelectResumoPedido.sql\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.fileQueryInput","value":"{\"resource\":\"file:///c%3A/FonteDesenvolvimento/Scripts/Script_fila_processamento.sql\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\FonteDesenvolvimento\\\\Scripts\\\\Script_fila_processamento.sql\",\"_sep\":1,\"external\":\"file:///c%3A/FonteDesenvolvimento/Scripts/Script_fila_processamento.sql\",\"path\":\"/C:/FonteDesenvolvimento/Scripts/Script_fila_processamento.sql\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"},{"id":"workbench.input.settings2","value":"{}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-userdata:/c%3A/Users/102608/AppData/Roaming/azuredatastudio/User/settings.json\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\Users\\\\102608\\\\AppData\\\\Roaming\\\\azuredatastudio\\\\User\\\\settings.json\",\"_sep\":1,\"external\":\"vscode-userdata:/c%3A/Users/102608/AppData/Roaming/azuredatastudio/User/settings.json\",\"path\":\"/C:/Users/102608/AppData/Roaming/azuredatastudio/User/settings.json\",\"scheme\":\"vscode-userdata\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.fileQueryInput","value":"{\"resource\":\"file:///c%3A/FonteDesenvolvimento/Scripts/script_movimento_estoque.sql\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\FonteDesenvolvimento\\\\Scripts\\\\script_movimento_estoque.sql\",\"_sep\":1,\"external\":\"file:///c%3A/FonteDesenvolvimento/Scripts/script_movimento_estoque.sql\",\"path\":\"/C:/FonteDesenvolvimento/Scripts/script_movimento_estoque.sql\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.untitledQueryInput","value":"{\"resource\":\"untitled:Untitled-5\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"Untitled-5\",\"_sep\":1,\"external\":\"untitled:Untitled-5\",\"path\":\"Untitled-5\",\"scheme\":\"untitled\"},\"modeId\":\"sql\",\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.untitledQueryInput","value":"{\"resource\":\"untitled:Untitled-3\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"Untitled-3\",\"_sep\":1,\"external\":\"untitled:Untitled-3\",\"path\":\"Untitled-3\",\"scheme\":\"untitled\"},\"modeId\":\"sql\",\"encoding\":\"utf8\"}"}],"mru":[3,2,1,0,4,6,5],"preview":2},"size":1874}],"size":990},"orientation":1,"width":1874,"height":990},"activeGroup":1,"mostRecentActiveGroups":[1]}): Error: Error restoring editor grid widget: TypeError: Cannot read property 'getModel' of null (with state: {"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":1,"editors":[{"id":"workbench.editorInput.fileQueryInput","value":"{\"resource\":\"file:///c%3A/FonteDesenvolvimento/Scripts/ScriptsSelectResumoPedido.sql\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\FonteDesenvolvimento\\\\Scripts\\\\ScriptsSelectResumoPedido.sql\",\"_sep\":1,\"external\":\"file:///c%3A/FonteDesenvolvimento/Scripts/ScriptsSelectResumoPedido.sql\",\"path\":\"/c:/FonteDesenvolvimento/Scripts/ScriptsSelectResumoPedido.sql\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.fileQueryInput","value":"{\"resource\":\"file:///c%3A/FonteDesenvolvimento/Scripts/Script_fila_processamento.sql\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\FonteDesenvolvimento\\\\Scripts\\\\Script_fila_processamento.sql\",\"_sep\":1,\"external\":\"file:///c%3A/FonteDesenvolvimento/Scripts/Script_fila_processamento.sql\",\"path\":\"/C:/FonteDesenvolvimento/Scripts/Script_fila_processamento.sql\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"},{"id":"workbench.input.settings2","value":"{}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-userdata:/c%3A/Users/102608/AppData/Roaming/azuredatastudio/User/settings.json\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\Users\\\\102608\\\\AppData\\\\Roaming\\\\azuredatastudio\\\\User\\\\settings.json\",\"_sep\":1,\"external\":\"vscode-userdata:/c%3A/Users/102608/AppData/Roaming/azuredatastudio/User/settings.json\",\"path\":\"/C:/Users/102608/AppData/Roaming/azuredatastudio/User/settings.json\",\"scheme\":\"vscode-userdata\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.fileQueryInput","value":"{\"resource\":\"file:///c%3A/FonteDesenvolvimento/Scripts/script_movimento_estoque.sql\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"c:\\\\FonteDesenvolvimento\\\\Scripts\\\\script_movimento_estoque.sql\",\"_sep\":1,\"external\":\"file:///c%3A/FonteDesenvolvimento/Scripts/script_movimento_estoque.sql\",\"path\":\"/C:/FonteDesenvolvimento/Scripts/script_movimento_estoque.sql\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.untitledQueryInput","value":"{\"resource\":\"untitled:Untitled-5\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"Untitled-5\",\"_sep\":1,\"external\":\"untitled:Untitled-5\",\"path\":\"Untitled-5\",\"scheme\":\"untitled\"},\"modeId\":\"sql\",\"encoding\":\"utf8\"}"},{"id":"workbench.editorInput.untitledQueryInput","value":"{\"resource\":\"untitled:Untitled-3\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"Untitled-3\",\"_sep\":1,\"external\":\"untitled:Untitled-3\",\"path\":\"Untitled-3\",\"scheme\":\"untitled\"},\"modeId\":\"sql\",\"encoding\":\"utf8\"}"}],"mru":[3,2,1,0,4,6,5],"preview":2},"size":1874}],"size":990},"orientation":1,"width":1874,"height":990},"activeGroup":1,"mostRecentActiveGroups":[1]})
    at e.doCreateGridControlWithPreviousState (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7052:349)
    at e.doCreateGridControl (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7051:678)
    at e.createContentArea (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7051:199)
    at e.create (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3590:914)
    at file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7103:651
    at Array.forEach (<anonymous>)
    at B.renderWorkbench (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7103:558)
    at file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7100:356
    at h.invokeFunction (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1938:149)
    at B.startup (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7100:94)
    at Y.open (file:///C:/Users/102608/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7673:929)`

**Comment by ypedroo** [comment] 2020-01-06 12:16
[renderer1] [error] Error restoring editor grid widget: TypeError: Cannot read property 'getModel' of null

**Comment by r4ndom4is** [comment] 2020-01-06 12:23
After uninstalling and wiping %APPDATA%\azuredatastudio folder clean, then re-installing, the issue went away.

**Comment by ypedroo** [comment] 2020-01-06 13:52
Seems to be working now thanks for the help

**Comment by ypedroo** [comment] 2020-01-08 12:29
between opens, actually the issue is back rn and basically the log shows the same error

**Comment by anthonydresser** [comment] 2020-01-08 22:07
I'll close as a dupe of #8795 I'm working on a fix currently.

**Closed by anthonydresser** 2020-01-08 22:07 UTC
Labels: Area - Query Editor, Bug, Triage: Needed
