### ISSUE TITLE
Profiler does not work. Throws error Failed to create session: An exception occurred while executing a Transact-SQL statement or batch.

### ISSUE THREAD

**Issue by spursrox** [microsoft/azuredatastudio#6457] opened 2019-07-22 22:43 UTC
- Azure Data Studio Version: 1.10.0 (Insiders build). 
- SQL Server Profiler Version :  0.9.0 

Note: Also happens in current release build.

Client is Mac OS.

Steps to Reproduce:

1. Launch Profiler against a SQL Server instance running in Azure. 
2. Session Template : "Standard_Azure" - this is the only available choice. 
3. Click Start. 

Result : Failed to create session: An exception occurred while executing a Transact-SQL statement or batch.

**Comment by Charles-Gagnon** [comment] 2019-07-22 22:53
Duplicate of #6353

**Closed by Charles-Gagnon** 2019-07-22 22:53 UTC
Labels: Bug
