### ISSUE TITLE
Error: Token retrieval failed with an error. Open developer tools to view the error

### ISSUE THREAD

**Issue by arnold-overby-SIM** [microsoft/azuredatastudio#17092] opened 2021-09-16 19:15 UTC
Issue Type: <b>Bug</b>

Attempt to create new firewall rule
-Add an Azure Account by successfully logging in to Azure/Microsoft Account 
-Select the appropriate Azure tentant from the drop-down
-Choose option for "Add my client IP (....)"
-Click on OK

Result:
"Error: Token retrieval failed with an error. Open developer tools to view the error"
-Close Azure Data Studio
-Open Azure Data Studio and try again.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:09:20.282Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
queryplan-show|phi|0.0.6

</details>

**Comment by cssuh** [comment] 2021-09-16 21:50
Hi @arnold-overby-SIM, if you open the Developer Tools (`Help` -> `Toggle Developer Tools`), do you see any error messages?

**Comment by arnold-overby-SIM** [comment] 2021-09-16 21:54
Hello,
No errors in the console.
The page itself says "Your account was added successfully. You may now
close this window."

Arnold Overby
Lead Developer
Salem Interactive Media
Salem Media Group
111 Virginia Street, Suite 500
Richmond, VA 23219
804.615.6882

**Comment by cssuh** [comment] 2022-02-01 21:35
closing for duplicate of https://github.com/microsoft/azuredatastudio/issues/14159

**Closed by cssuh** 2022-02-01 21:35 UTC
Labels: Bug, Area - Connection, Triage: Done
