### ISSUE TITLE
Messages appear out of order

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#10094] opened 2020-04-20 23:58 UTC
Issue Type: <b>Bug</b>

Messages will appear out of order when running with multiple batches.

![image](https://user-images.githubusercontent.com/4324725/79810524-1b68b980-8328-11ea-88e7-79689aa2f716.png)

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (10.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|azu|0.50.0

</details>

**Comment by Charles-Gagnon** [comment] 2020-04-21 16:30
@anthonydresser Isn't this a duplicate of https://github.com/microsoft/azuredatastudio/issues/9779 ?

**Closed** 2020-04-21 19:45 UTC
Labels: Area - Query Editor, Bug, Triage: Done
