### ISSUE TITLE
Azure Data Studio white hang

### ISSUE THREAD

**Issue by eminabdalian** [microsoft/azuredatastudio#8940] opened 2020-01-23 11:25 UTC
Hi,

I have a user who uses Azure Data Studio and it turns white and hangs, it helps to close/minimize Chrome and minimize maximize Data Studio, it starts to respond then.

Running on Windows 10

Uninstall/Reinstall dont help

**Comment by kburtram** [comment] 2020-01-23 22:14
@eminabdalian could you please verify if the issue repro with the latest insiders build (available at https://azuredatastudio-update.azurewebsites.net/latest/win32-x64-archive/insider for example)?

We've updated to Electron 7 in the latest insiders build and are planning to release that in Feb. It's possible we picked up an upstream fix. Thanks!

**Comment by aguerot** [comment] 2020-01-28 12:55
I have the exact same issue and I need to resize multiple times the window to get out of this "white hang"
Here is my diagnostic info:
```
Version: 1.14.1 (system setup)
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:42:26.303Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

CPUs | Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)
-- | --
GPU Status | 2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_renderer: disabled_off
surface_control: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off
webgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.93GB (0.75GB free)
Process Argv |  
Screen Reader | no
VM | 0%
```
There is also this error message in the Debug tool console:
```
(node:11836) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

I m going to try insider build to see if I can repro

**Comment by AndyWorral** [comment] 2020-01-31 18:12
I had the same issue as above and the Insiders preview is **not** having the issue.

Version: 1.15.0-insider
Commit: 56695be14ac0160e7a4d23b7af939b98fdaaea45
Date: 2020-01-30T05:35:45.707Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by kburtram** [comment] 2020-01-31 21:34
@AndyWorral thanks for confirming insiders isn't having the issue.  We are planning to ship a new stable build early next week which will include the changes in the insiders build.  Sorry for the inconvenience.

**Comment by kburtram** [comment] 2020-01-31 21:35
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8775.  We've had several reports of this and are trying to get an internal repro.  Hopefully it will be resolved by the changes in the Feb release.

**Closed by kburtram** 2020-01-31 21:35 UTC
Labels: Area - Shell, Bug, Triage: Done
