### ISSUE TITLE
spatial results

### ISSUE THREAD

**Issue by rpoche** [Microsoft/azuredatastudio#1377] opened 2018-05-09 18:24 UTC
- SQL Operations Studio Version: 0.28.6

Could you add a spatial results tab to preview spatial data?

Thanks,
Richard

**Comment by ChristopherTotty** [comment] 2018-09-01 03:35
Duplicate of #267

**Comment by kburtram** [comment] 2018-11-14 01:19
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/267.

**Closed by kburtram** 2018-11-14 01:19 UTC
Labels: new feature ask, suggestion
