### ISSUE TITLE
Azure Arc data controller doesnt display Arc resource names

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12333] opened 2020-09-16 01:46 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. Install the Azure Arc extension
2. Launch ADs
3. Connect to a data controller that has arc resources deployed, such as MIAA or PG
4. The dashboard doesnt display the name column for the arc resources.

![image](https://user-images.githubusercontent.com/43253513/93282665-c2406d00-f783-11ea-822b-cab32a73a282.png)

**Comment by chlafreniere** [comment] 2020-09-16 04:31
Dupe of #12304.

**Closed by chlafreniere** 2020-09-16 04:31 UTC
Labels: Impact: Azure Arc
