### ISSUE TITLE
Script file opened from command line does not allow DB connection

### ISSUE THREAD

**Issue by wthomp** [microsoft/azuredatastudio#16427] opened 2021-07-25 01:58 UTC
Issue Type: <b>Bug</b>

Using a shortcut that opens a script file and connects to a SQL Server successfully connects to the server and opens the file, but the file does not have any options for connecting to a server or executing.  This worked in the June release.

"azuredatastudio.exe" "<path to sql script file>" --new-window --server <SQL server name> --database <database name>

Azure Data Studio version: azuredatastudio 1.31.0 (a430fd2592763ef4c4a406821967e4b7b2b3d876, 2021-07-20T19:43:31.605Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.00GB free)|
|Process Argv|--new-window --server HQHBRFTSQL03\\PROD --database HBRFT_MDB|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.11.0
server-report|Mic|0.2.3
extra-sql-script-as|pac|0.3.0
sql-prompt|Red|0.2.7
sql-search|Red|0.4.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment] 2021-07-26 18:35
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/16427 - please provide any additional information there.

**Closed by Charles-Gagnon** 2021-07-26 18:35 UTC
