### ISSUE TITLE
Split Editor now opens the same file

### ISSUE THREAD

**Issue by oakhousetom** [microsoft/azuredatastudio#17021] opened 2021-09-08 09:35 UTC
Issue Type: <b>Bug</b>

Open any file or in-progress query
Click the split editor button or press CTRL+\

It used to create a new blank window but now it opens the same query again on the right.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.61GB (4.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0
query-history|Mic|0.1.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-09-08 16:00
This was a change VS Code made recently - see https://github.com/microsoft/azuredatastudio/issues/16430 for details and a workaround for setting up the keybinding for getting the old behavior.

Closing this as working as intended for now. Let us know if the above workarounds don't meet your needs!

**Closed by Charles-Gagnon** 2021-09-08 16:00 UTC
