### ISSUE TITLE
Right clicking on Triggers doesn't allow Script To

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/azuredatastudio#7980] opened 2019-10-24 16:42 UTC
Issue Type: <b>Bug</b>

Open a database and table with a trigger.

Double clicking does nothing.

Right clicking doesn't bring up the menu like all other types of things like Views, functions etc.

It should bring up the ability to script to with the same options as Views and functions.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18363

**Comment by kburtram** [comment] 2021-08-19 20:29
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/2093.  I'll use that issue to track since it has more upvotes.  Thanks!

**Closed by kburtram** 2021-08-19 20:29 UTC
Labels: Area - Object Explorer, Enhancement, Triage: Done
