### ISSUE TITLE
Clicking the refresh button of bdc dashboard will cause 2 refreshes

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#7918] opened 2019-10-22 23:05 UTC
![Oct-22-2019 16-02-15](https://user-images.githubusercontent.com/13777222/67341897-b56cb800-f4e5-11e9-8744-b4402135766c.gif)

**Comment by Charles-Gagnon** [comment] 2019-10-22 23:07
So that's not really an issue - we do the queries separately. The first one (endpoints) usually returns much more quickly than the second (BDC status) so you'll see the Endpoints refresh first and then later on the top status section will refresh. 

I'm closing this as by design for now but if you think that this behavior should be changed (for example to only refresh the UI once all queries complete) then re-open and we can discuss further.

**Closed by Charles-Gagnon** 2019-10-22 23:07 UTC
Labels: Area - Big Data Cluster, Bug, Triage: Needed
