### ISSUE TITLE
Edit Data on empty table shows error message

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/azuredatastudio#9918] opened 2020-04-09 13:28 UTC
Issue
![2020-04-09_09h25_38](https://user-images.githubusercontent.com/28546239/78900153-6d663100-7a44-11ea-9fb0-6ebb5b2f4861.png)
 Type: <b>Bug</b>

Table is empty but some columns are set Not Null.  Click Edit Data and an error message bottom left complains about "commit row failed".

Azure Data Studio version: azuredatastudio-insiders 1.17.0-insider (177a58c81d39446f9724d15cff037087246d32dc, 2020-04-03T16:57:24.010Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (8.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.46.0
dacpac|Mic|1.3.0
import|Mic|0.14.0
profiler|Mic|0.11.0
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kburtram** [comment] 2020-04-13 19:38
@smartguest could you please take a look to see if this is a regression?

**Comment by smartguest** [comment] 2020-04-14 00:26
@kburtram This is a regression, apparently when the first cell of the empty row is selected, its normally supposed to create a new null row (for rendering purposes), however since the columns have NOT NULL in them, it causes some issues as the code cannot handle that.

**Comment by abist** [comment] 2020-04-21 20:36
This should be fixed now.

**Closed by abist** 2020-04-21 20:36 UTC
Labels: Approved, Area - Edit Data, Bug, Triage: Done
