### ISSUE TITLE
Support for SSIS packages (dtsx) on Mac

### ISSUE THREAD

**Issue by saumyasuhagiya** [microsoft/azuredatastudio#16815] opened 2021-08-18 11:18 UTC
**Is your feature request related to a problem? Please describe.**
I have SSIS package but not able to open in current Azure Data Studio on Mac.

**Describe the solution or feature you'd like**
Open, analyze SSIS packages.
Edit and save capability will be added advantage
 
**Describe alternatives you've considered**
Alternative 1. Create VDI, install Visual Studio and get the packages.
Alternative 2. Ask person having windows and ask them to send it across as txt file.

**Additional context**
Tried with SQL Database projects but I think it doesn't support that.

**Comment by Charles-Gagnon** [comment] 2021-08-19 20:01
Closing this as a dupe of https://github.com/microsoft/azuredatastudio/issues/1080 - there are currently no plans for adding support for this but if we do then we'll update that issue. Thanks for the request!

**Closed by Charles-Gagnon** 2021-08-19 20:01 UTC
