### ISSUE TITLE
All columns from query not able to save to excel or be copied

### ISSUE THREAD

**Issue by codymullins** [microsoft/azuredatastudio#1810] opened 2018-06-30 14:33 UTC
Issue Type: <b>Bug</b>

1. Write a query with two left joins where only three columns of data are returned in the query
2. Export to excel with one column highlighted (middle column)
3. Only middle column exported
4. Re-highlight all columns, export to excel again
5. Only middle column exported
6. Right click --> Copy with headers
7. Only one column copied
8. Right click --> Copy
9. Only one column copied
10. I can copy the columns individually only

Expected:
Export to excel or copy with headers should copy/export all columns highlighted

Actual:
Only one column able to be highlighted

Other troubleshooting steps:
1. I restarted Excel
2. I restarted SQL Ops

Query:
select p.Name, c.CriteriaNumber, c.CriteriaTitle from TblPrograms p
left join XrefInstrumentCriteriaPrograms x on x.ProgramId = p.Id
left join TblMonitoringInstrumentCriterias c on c.CriteriaId = x.CriteriaId

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:34:32.192Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.75GB free)|
|Process Argv|/Applications/SQL Operations Studio 2.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details>Extensions: none

**Comment by alanrenmsft** [comment] 2023-06-09 20:39
I just tested and the issue is fixed now.

**Closed by alanrenmsft** 2023-06-09 20:39 UTC
Labels: Bug, Area - Query Editor
