### ISSUE TITLE
Caret Tracking Lost When Switching Tabs

### ISSUE THREAD

**Issue by nicknguyen** [microsoft/azuredatastudio#5935] opened 2019-06-07 13:10 UTC
Place caret on any line / column in any opened sql file / tab.
Navigate to another tab and switch back; caret position is reset to line 1, column 1.

**Comment by Charles-Gagnon** [comment] 2019-06-07 15:03
What version are you using? This doesn't repro for me on the latest release (1.8.0) so if you're not using that please try updating and let us know if you still see the issue.

![screen](https://user-images.githubusercontent.com/28519865/59113853-bcaa7500-88fa-11e9-8430-8c5aefa7c29b.gif)

**Comment by nicknguyen** [comment] 2019-06-10 14:56
@Charles-Gagnon 

Version 1.8.0.

Its happening in a multi-folder workspace on existing files when 1 or more of the files are very large (~12 MB). Breaking apart this monolithic new install script (which pre-dates my tenure) into many smaller files would be ideal but would require rework to the calling legacy db utility.

**Comment by anthonydresser** [comment] 2019-06-19 18:39
This is most likely a dupe of #6012

**Closed** 2019-06-26 19:02 UTC
Labels: Area: Query Editor, Bug, Needs More Info
