### ISSUE TITLE
Query Editor doesn't open

### ISSUE THREAD

**Issue by sdukes21** [microsoft/azuredatastudio#24058] opened 2023-08-02 16:00 UTC
Type: <b>Bug</b>

1. Click Explorer on left side of Data Studio window
2. Select any existing query (mine are all .sql) by double clicking the file name
3. Notice issue: Query Editor does not open (nothing happens)
4. Try again by clicking "File" in upper left and select either "New Query" or "Open File..."
5. Notice issue: neither option will open a query editor (nothing happens)
6. Try again by right clicking query name in explorer tab and choosing "open to side"
7. Notice issue: split window will appear, but file will still not appear (Close editor to return to single window view.)
8. Try again by right clicking file name and choosing "Open with..."
9. Choose "Query Editor"
10. Notice issue: nothing will open
11. Try again by right clicking file name and choosing "Open with.."
12. Choose "Text Editor"
13. Yay! File will open. Issue: in text editor we cannot run the code to test along the way (Close tab)
15. Try again: Choose "Connections" on left side of data studio window
16. Choose desired database and click small plug icon next to data base to connect
17. Once connected, a window will pop up to show details of the database.
18. In this window, choose "New Query"
19. Yay! A query editor opened. This is the ONLY place that will open a Query Editor, however it is a new file, not the ones I would like to work on. Once I save this new query, it becomes unopenable and I must create another new query (using same method) to copy and paste code from the text editor to test it.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sdukes21** [comment] 2023-08-02 23:18
[log for query editor issue.zip](https://github.com/microsoft/azuredatastudio/files/12245412/log.for.query.editor.issue.zip)
[Query Editor Not Opening Issue.txt](https://github.com/microsoft/azuredatastudio/files/12245419/Query.Editor.Not.Opening.Issue.txt)

**Comment by cheenamalhotra** [comment] 2023-08-03 01:19
Hi @sdukes21 

I couldn't reproduce the issues you're describing on Windows. Can you also share custom settings from your settings.json to see if they may be playing a role?

**Comment by sdukes21** [comment] 2023-08-03 03:17
Where can you find that so I can send it to you? Also, I have not changed any settings from the default until following the steps you sent me earlier

**Comment by cheenamalhotra** [comment] 2023-08-24 01:36
Hi @sdukes21 

Can you let us know if you still encounter this issue in 1.45.1?

**Comment by miguel-misstipsi** [comment] 2023-09-04 06:38
I have the same issue with this environment:

Version: 1.45.1 (user setup)
Commit: 88c21b1725a3e79440027bdb7b5a55fb036be0e2
Date: 2023-08-03T00:42:37.945Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by cheenamalhotra** [comment] 2023-10-26 21:01
@sdukes21 @miguel-misstipsi 

Could you please try the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know if that resolves the issue?

**Comment by miguel-misstipsi** [comment] 2023-10-27 07:35
@cheenamalhotra, the issue is fixed!
Thank you.

**Comment by cheenamalhotra** [comment] 2023-10-27 19:48
Closing as resolved.

**Closed by cheenamalhotra** 2023-10-27 19:48 UTC
Labels: Bug, Area - Query Editor, Area - Shell, Needs More Info, Triage: Needed
