### ISSUE TITLE
Synapse Serverless wrong classifaction and Connection

### ISSUE THREAD

**Issue by Carsten3000** [microsoft/azuredatastudio#20252] opened 2022-08-05 07:42 UTC
- Azure Data Studio Version:  1.38.0
- OS Version: Windows 10 21H2

![image](https://user-images.githubusercontent.com/43674046/183027961-430540de-4b6d-42c9-8293-9314101f2aea.png)

- Synapse Serverless is classified as SQL Server, i would propose an extra folder for Synapse Serverless
- The Servername in the connection panel is wrong. I suspect that it just takes the server name and adds ".database.windows.net"  For Synapse Serverless the endpoint is "<name>-ondemand.sql.azuresynapse.net". With this change the connection works.

**Comment by cheenamalhotra** [comment] 2022-08-25 06:37
Duplicate of https://github.com/microsoft/azuredatastudio/issues/20180, I will proceed to close this one.
@Carsten3000 please track the other issue for future updates.

**Closed by cheenamalhotra** 2022-08-25 06:37 UTC
Labels: Bug, Area - Connection, Triage: Done, Impact: Synapse
