### ISSUE TITLE
Problème de connexion à cause de la langue FR

### ISSUE THREAD

**Issue by Flagache** [microsoft/azuredatastudio#21487] opened 2022-12-29 18:23 UTC
Issue Type: <b>Bug</b>

Lorsque l'interface est en Français: il est impossible de se connecter à cause du paramètre Chiffrer qui prend la valeur Faux au lieu de "False" 

![image](https://user-images.githubusercontent.com/53898983/209993609-6449ddec-4064-40ad-978f-899dfe0d1347.png)

![image](https://user-images.githubusercontent.com/53898983/209993673-a52568d4-7de9-4904-8cbf-09c4509d29d7.png)

System.ArgumentException: Valeur non valide 'Faux' pour Chiffrer. Les valeurs valides sont 'Optional', 'Mandatory', 'Strict', 'True', 'False', 'Yes' et 'No'.
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.CreateConnectionStringBuilder(ConnectionDetails connectionDetails) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1311
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.BuildConnectionString(ConnectionDetails connectionDetails) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1204
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 645

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.37GB (29.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
ads-language-pack-fr|Mic|1.40.1
agent|Mic|0.49.0
dacpac|Mic|1.11.0
import|Mic|1.5.4
profiler|Mic|0.11.0
extra-sql-script-as|pac|0.5.0

</details>

**Comment by cheenamalhotra** [comment] 2022-12-30 00:28
Hi @Flagache 

This looks similar to https://github.com/microsoft/azuredatastudio/issues/21353 and has been fixed in the insiders build.

The fix will be released in the next stable release scheduled in January.

**Comment by cheenamalhotra** [comment] 2023-01-05 17:55
Closing as duplicate of #21353

**Closed by cheenamalhotra** 2023-01-05 17:55 UTC
Labels: Bug, Area - Connection, Triage: Done
