### ISSUE TITLE
new tab without sql suffix cant be used

### ISSUE THREAD

**Issue by DariusStank** [Microsoft/azuredatastudio#2964] opened 2018-10-22 06:03 UTC
- Azure Data Studio Version:
Version 0.32.9
Commit 8004776eff330e8980b473b6a2f6faf607164005
Date 2018-09-19T05:11:56.160Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:
Double click on empty space (near tabs) to get new tab/page

this new tab has no description about sql. Meaning that there is no connection possibility or run queries.

Maybe by default it should be sql as it is for sql purpose :)

![image](https://user-images.githubusercontent.com/42645070/47279243-5fb2b680-d5d8-11e8-9bee-61c1bc0c6c35.png)

**Comment by kevcunnane** [comment] 2018-10-22 17:48
Can you try this with the latest version? https://docs.microsoft.com/en-us/sql/azure-data-studio/download - I cannot reproduce this on the October build

**Comment by kburtram** [comment] 2018-10-22 19:37
This should be fixed in the latest build. Unfortunately we don't have an auto-update from SQL Ops to Azure Data Studio so this will require a 1-time manual upgrade.  Please reactive if you hit this on a version 1.1+ build.

**Closed by kburtram** 2018-10-22 19:37 UTC
Labels: needs repro
