### ISSUE TITLE
Failed to change kernel

### ISSUE THREAD

**Issue by RobbinsbkC** [microsoft/azuredatastudio#24080] opened 2023-08-04 19:06 UTC
Type: <b>Bug</b>

Can't run my notebook powershell code because it won't let me change kernels.   Defaults back to SQL displaying the error message below.

Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last): File "c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py", line 1, in <module> import notebook.notebookapp ModuleNotFoundError: No module named 'notebook.notebookapp'

Googled found several articles that suggested to reinstall python and jupyter which i tried and did not fix issue

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
cms|Mic|0.9.3
dacpac|Mic|1.14.0
datavirtualization|Mic|1.13.2
import|Mic|1.5.5
machine-learning|Mic|0.12.0
powershell|ms-|2023.6.0
profiler|Mic|0.14.0
whoisactive|Mic|0.1.5

</details>

**Comment by cheenamalhotra** [comment] 2023-08-04 19:22
Seems duplicate of https://github.com/microsoft/azuredatastudio/issues/23954 

@RobbinsbkC can you try recommendation from that issue and use same thread for follow up? 
I will close this as duplicate.

**Closed by cheenamalhotra** 2023-08-04 19:22 UTC

**Comment by RobbinsbkC** [comment] 2023-08-04 19:42
That recommendation didn't help.   Thanks for closing my case without any solution thought.

**Comment by cheenamalhotra** [comment] 2023-08-04 19:45
@RobbinsbkC the other issue will be used for investigation, so please upvote and post a comment there if none of the recommendations helped your case. Thanks!
