### ISSUE TITLE
Azure SQL Database objects no longer viewable in Connections pane

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/azuredatastudio#21735] opened 2023-01-26 09:50 UTC
Issue Type: <b>Bug</b>

After upgrading the 1.41 when connected to an Azure SQL Database you can no longer expand the database to see the objects inside it. Instead pressing the drop down returns nothing. 

This behaviour isn't replicated with on-premises instances. I don't have (at my current location) a Azure SQL Edge or Managed instance I can test against. You can see the attached screenshot, which demonstrates that the tables *can* be seen in the `sys.tables` object, however, ADS shows nothing in the Connections pane. For the Sandbox server I am also connected to, however, you can see both a Tables node, *and* all tables within the `AdventureWorks2019` database.

Both connections are using a `LOGIN` with `sysadmin` privileges, so this is not a permissions problem, and this behaviour did not occur in 1.40.

![image](https://user-images.githubusercontent.com/20837086/214806051-c8a57c87-aece-4616-92f3-38574ec544a4.png)

Azure Data Studio version: azuredatastudio 1.41.0 (cf5e0fe1a33709e2a82dc94f42dbe88487803d62, 2023-01-24T17:25:45.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.90GB (3.31GB free)|
|Process Argv|--enable-proposed-api ms-toolsai.jupyter|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.1
agent|Mic|0.49.0
cms|Mic|0.9.2
dacpac|Mic|1.12.0
import|Mic|1.5.4
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2022.7.2
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.18.0
server-report|Mic|0.2.3
sql-database-projects|Mic|0.21.0
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353
azdata-sanddance|msr|4.0.1
material-icon-theme|PKi|4.23.1
material-product-icons|PKi|1.4.1
sql-prompt|Red|0.2.12
sql-search|Red|0.4.0
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by LarnuUK** [comment] 2023-01-26 10:28
More confusing, if you right click the database and select "Manage" you can see the tables too. If you also click "Refresh" then the _classic_ error:
> Object reference not set to an instance an object.

![image](https://user-images.githubusercontent.com/20837086/214813608-cbbf5a7b-edcb-417c-b7a8-b90215ddc7ec.png)

**Comment by cheenamalhotra** [comment] 2023-01-26 17:30
I was able to reproduce it with a basic DTU5 database, doesn't seem to happen with all databases, that's why it got missed probably...

Pasting stacktrace for reference:

```
[Error - 8:10:05 a.m.] Request admin/getdatabaseinfo failed.
  Message: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabasePrototype.GetDatabaseDefaultInitFields(Server server) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabasePrototype.cs:line 1673
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabasePrototype..ctor(CDataContainer context) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabasePrototype.cs:line 1739
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabasePrototype80..ctor(CDataContainer context) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabasePrototype80.cs:line 186
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabasePrototype80SP3..ctor(CDataContainer context) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabasePrototype80SP3.cs:line 32
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabasePrototype90..ctor(CDataContainer context) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabasePrototype90.cs:line 218
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabasePrototype100..ctor(CDataContainer context) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabasePrototype100.cs:line 187
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabasePrototypeAzure..ctor(CDataContainer context, DatabaseEngineEdition editionToCreate) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabasePrototypeAzure.cs:line 37
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabaseTaskHelper.Initialize(CDataContainer context) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabaseTaskHelper.cs:line 61
   at Microsoft.SqlTools.ServiceLayer.Admin.DatabaseTaskHelper..ctor(CDataContainer context) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\Database\DatabaseTaskHelper.cs:line 45
   at Microsoft.SqlTools.ServiceLayer.Admin.AdminService.CreateDatabaseTaskHelper(ConnectionInfo connInfo, Boolean databaseExists) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\AdminService.cs:line 175
   at Microsoft.SqlTools.ServiceLayer.Admin.AdminService.GetDatabaseInfo(ConnectionInfo connInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\AdminService.cs:line 161
   at Microsoft.SqlTools.ServiceLayer.Admin.AdminService.<>c__DisplayClass12_0.<<HandleGetDatabaseInfoRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Admin\AdminService.cs:line 139
```

@shueybubbles is informed and issue is likely in the #dso query.

**Comment by cheenamalhotra** [comment] 2023-01-27 18:21
**Update:**

We've identified the root cause and are working on making the fix available soon. The hotfix to contain fix is planned to be released as soon as Monday.

Meanwhile, if you're hitting this issue, you may rollback to previous stable release [1.40.2](https://github.com/microsoft/azuredatastudio/releases/tag/1.40.2).
Thank you for your patience.

**Comment by kburtram** [comment] 2023-01-30 17:42
Fixed in insiders and in upcoming hotfix.

**Closed by kburtram** 2023-01-30 17:42 UTC
Labels: Bug, Area - Object Explorer, Triage: Done, Approved, Size: M, Pri: 0
