### ISSUE TITLE
Save results to Excel > Open File button tries to open the Excel file in ADS

### ISSUE THREAD

**Issue by oakhousetom** [microsoft/azuredatastudio#9054] opened 2020-02-05 11:47 UTC
Issue Type: <b>Bug</b>

To reproduce:
1. Run query
2. Click to save the results as an Excel file
3. Save the file on your computer
4. In the success box in the lower right, click Open File

Azure Data Studio displays the following message:
"The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?"

This used to work by opening the file externally which would launch Excel as expected.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.1.0
import|Mic|0.12.0
profiler|Mic|0.11.0
server-report|Mic|0.2.1
whoisactive|Mic|0.1.3

</details>

**Comment by chezy525** [comment] 2021-11-01 21:37
I just started experiencing this issue.  It was working as I would expect - the newly saved *.xlsx file would open in LibreOffice Calc when I clicked "Open File".  Now I get a popup warning that "An external application wants to open *.xlsx in azuredatastudio...", then when I click yes, the "The file is not displayed..." message appears.  This isn't a feature I use every day, so I'm not sure when it started.

Version: 1.33.0 (system setup)
Commit: 6783aa6967e8c6d086b6f04e5fbf527659981389
Date: 2021-10-26T17:28:15.782Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by bjones021595** [comment] 2021-11-06 19:54
Same! This just started for me after I updated my version of ADS. I do use this feature every day

**Comment by Thallerich** [comment] 2021-11-29 11:35
Same here, after clicking the "Open File" button, i get the following message:
**An extern application wants to open <filepath> in azuredatastudio. Do you want to open this file or folder?**

Clicking yes on this message opens the excel file in ADS, showing the message "This file is not displayed in the editor because it is either binary or uses an unsupported text encoding."

Opening excel files this way did work until i upgraded to version ADS version 1.33.

Version: 1.33.1 (system setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22504

**Comment by Charles-Gagnon** [comment] 2021-11-29 17:18
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/17618.

The original bug is extremely old though so not sure whether that was actually the same issue, but regardless with my fix there this should no longer be an issue going forward. For those using 1.33.1 you can use the insiders version if you want to make sure the fix works for you until the next stable release is out (sometime mid December is the target date)

**Comment by cheenamalhotra** [comment] 2023-10-11 18:38
Closing as issue doesn't occur anymore. Verified with latest release v1.46.1

**Closed by cheenamalhotra** 2023-10-11 18:38 UTC
Labels: Bug, Area - Query Editor, Triage: Done
