### ISSUE TITLE
Unable to copy and paste from Results

### ISSUE THREAD

**Issue by wiretiger** [microsoft/azuredatastudio#24285] opened 2023-09-05 01:02 UTC
Type: <b>Bug</b>

When I try to copy data from the Results window, it does not go into my system clipboard.

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:38:54.891Z)
OS version: Linux x64 6.2.0-31-generic
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 3848)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.34GB (9.04GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.5.0

</details>

**Comment by kisantia** [comment] 2023-09-05 17:22
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/24043

**Closed by kisantia** 2023-09-05 17:22 UTC
Labels: Bug, Area - Query Editor
