### ISSUE TITLE
Reopening ADS with User Settings opened errors out

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#15440] opened 2021-05-12 19:44 UTC
- Azure Data Studio Version: 1.29 RC

Steps to Reproduce:

1. Open User Settings on ADS and close ADS with the user settings opened.
2. Restart ADS

Expected - ADS just reopens without any issues with user settings tab open

Actual - User Settings tab is empty with the following error -

```
  ERR Cannot read property 'settingsGroups' of undefined: TypeError: Cannot read property 'settingsGroups' of undefined
    at Zt.onConfigUpdate (file:///private/var/folders/x_/t6mxvrys54z7qf8nt3_27cjw0000gn/T/AppTranslocation/D180FE11-6F47-4AA0-8B04-B4B11EC9D217/d/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:95383)
    at file:///private/var/folders/x_/t6mxvrys54z7qf8nt3_27cjw0000gn/T/AppTranslocation/D180FE11-6F47-4AA0-8B04-B4B11EC9D217/d/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:79138
    at s.fire (file:///private/var/folders/x_/t6mxvrys54z7qf8nt3_27cjw0000gn/T/AppTranslocation/D180FE11-6F47-4AA0-8B04-B4B11EC9D217/d/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:80:1835)
    at E.triggerConfigurationChange (file:///private/var/folders/x_/t6mxvrys54z7qf8nt3_27cjw0000gn/T/AppTranslocation/D180FE11-6F47-4AA0-8B04-B4B11EC9D217/d/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:40233)
    at E.onLocalUserConfigurationChanged (file:///private/var/folders/x_/t6mxvrys54z7qf8nt3_27cjw0000gn/T/AppTranslocation/D180FE11-6F47-4AA0-8B04-B4B11EC9D217/d/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:35414)
    at E.reloadLocalUserConfiguration (file:///private/var/folders/x_/t6mxvrys54z7qf8nt3_27cjw0000gn/T/AppTranslocation/D180FE11-6F47-4AA0-8B04-B4B11EC9D217/d/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:32680)
```

**Comment by Charles-Gagnon** [comment] 2021-05-12 19:56
For triaging purposes - this isn't a new issue. It's been around forever as far as I can tell (or at least since last year when I first noticed it). I briefly looked into it but wasn't able to track down the issue here (VS Code doesn't have this problem so I guess it's something that we've modified with the settings config? Seems weird though since we haven't really touched this stuff AFAIK)

**Comment by kburtram** [comment] 2021-05-12 20:19
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/13702.

**Closed by kburtram** 2021-05-12 20:19 UTC
Labels: Area - Shell, Bug, Triage: Needed
