### ISSUE TITLE
Ability to sort the result grid would be nice

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#2010] opened 2018-07-24 21:28 UTC
Issue Type: <b>Feature Request</b>

Alot of the time, we have to add the order by clause in our select statement, it would be nice to be able to sort the grid.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

**Comment by iant-travelopia** [comment] 2018-07-27 13:51
This is a duplicate of #569

It is (since June 2018) possible to filter and sort by clicking the show SQL Pane button and writing the appropriate SQL, but I'd call that a workaround given that this is a GUI application.

**Comment by datauduong** [comment] 2018-07-28 04:54
iant-travelopia, 

I am on version 0.31.4.

Right Click on the Table and Select Edit Data, I can see the Show SQL Pane, only show me the SQL Query, but you can't click on the Result Grid Column Header to Sort or Filter (When I click on the Column Header nothing Happen).

It defeat the purpose of quick data Browsing.

**Comment by iant-travelopia** [comment] 2018-07-30 08:41
@datauduong I agree it's a horrible solution for most use cases, but it's the solution Microsoft implemented in SQL Server Management Studio and it has been replicated here. It's not nice to use, but it does allow you to sort and filter the results.

#569 is open to add a nice way of sorting / filtering.

**Comment by MsSQLGirl** [comment] 2021-09-23 22:55
Hello, it is now possible to sort result set from the grid.
Please download the latest ADS (http://aka.ms/getAzureDataStudio)

![image](https://user-images.githubusercontent.com/6405919/134594375-a06772ca-20bc-4eac-9fa6-d8343e71263e.png)

**Closed by MsSQLGirl** 2021-09-23 22:55 UTC
Labels: Enhancement
