### ISSUE TITLE
Disable all option on schema compare

### ISSUE THREAD

**Issue by joelcampospi** [microsoft/azuredatastudio#24814] opened 2023-10-30 08:24 UTC
**Is your feature request related to a problem? Please describe.**
When comparing a schema, all "include" checkboxes are checked by default and we are forced to start unselecting all of them if we only want a few changes to be applied.

**Describe the solution or feature you'd like**
An option (for example, a button) that unselects all checkboxes.

**Describe alternatives you've considered**
The classical header that allows to enable/disable all.

**Comment by kisantia** [comment] 2023-10-30 16:31
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/10430

**Closed by kisantia** 2023-10-30 16:31 UTC
Labels: Area - Schema Compare
