### ISSUE TITLE
Query Failed: Conversion overflows

### ISSUE THREAD

**Issue by tgaudett** [microsoft/azuredatastudio#17578] opened 2021-11-03 14:10 UTC
Issue Type: <b>Bug</b>

I have a table of the IP2Location database that is purchased.  When I run the following command in Azure Data Studio I get an error.  But if I run the exact same SQL in MSSMS it does not error.  MSSMS returns 207 rows and Azure Data Studio returns 100 rows with the error message.  Connected to on-prem SQL Server instance. (I think SQL Server 13)

SELECT TOP (1000) [IP_FROM]
      ,[IP_TO]
      ,[COUNTRY_CODE]
      ,[COUNTRY_NAME]
      ,[STATE_NAME]
      ,[CITY_NAME]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[ZIP_CODE]
      ,[TIME_ZONE]
      ,[ISP_NAME]
      ,[DOMAIN_NAME]
      ,[LAST_LOAD_DATETM]
FROM [IP2Location].[dbo].[IP_ADDR_INFO]
WHERE DOMAIN_NAME LIKE ('%ga.us')

Azure Data Studio version: azuredatastudio 1.33.0 (6783aa6967e8c6d086b6f04e5fbf527659981389, 2021-10-26T17:28:15.782Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (18.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0

</details>

**Comment by tgaudett** [comment] 2021-11-03 14:24
I figured out that the error is happening on rows in the data that are big numbers.  The IP_FROM and IP_TO columns are of type decimal(38,0) and when we have a number like 42540986355731672318805982132698087424 in it then it errors.
[AzureError.xlsx](https://github.com/microsoft/azuredatastudio/files/7468229/AzureError.xlsx)

I am attaching a small section of the table so you can see which one errors.  Anything that is x10^36 errors.

**Comment by alanrenmsft** [comment] 2021-12-01 00:09
dupe of #275

**Closed** 2021-12-15 23:58 UTC
Labels: Bug, Area - Query Editor, Triage: Done
