### ISSUE TITLE
MacOS window.titleBarStyle not working like VsCode

### ISSUE THREAD

**Issue by Jonatthu** [Microsoft/azuredatastudio#1449] opened 2018-05-20 19:29 UTC
Version May Preview

{
    "workbench.colorTheme": "Default Dark SQL Operations Studio",
    "workbench.colorCustomizations": {
        "titleBar.activeBackground": "#b80a0a",
        "titleBar.activeForeground": "#ff0000"
    },
    "window.titleBarStyle": "custom"
}

The title bar should be red, using this configuration on vscode works fine but not on sqlopsstudio.

**Comment by Code-DJ** [comment] 2018-05-27 17:38
Looks like this is purposely disabled in window.ts

https://github.com/Microsoft/sqlopsstudio/blob/dafb7809875f49856b9b38e823a2f7dbd72733dd/src/vs/code/electron-main/window.ts

```
// {{SQL CARBON EDIT}}
// turn-off custom menus to avoid bug calculating size of SQL editor
//
// if (isMacintosh && (!windowConfig || !windowConfig.titleBarStyle || windowConfig.titleBarStyle === 'custom')) {
// 	const isDev = !this.environmentService.isBuilt || !!config.extensionDevelopmentPath;
// 	if (!isDev) {
// 		useCustomTitleStyle = true; // not enabled when developing due to https://github.com/electron/electron/issues/3647
// 	}
		// }
```

**Comment by anthonydresser** [comment] 2018-07-03 23:41
This was disabled do to other issues it was causing in our query editor window. Once we refactor the query editor code, we should be able to reenable this feature.

**Comment by KamasamaK** [comment] 2018-09-24 21:16
To be clear, this issue is not only affecting macOS.

**Comment by kianryan** [comment] 2018-10-18 15:44
This property is exposed in the user settings dialog (change between custom and native), but on restart hides the native toolbar but does not enable the custom toolbar (or the custom window chroming).

This is on Windows for ADS 1.1.3.

**Comment by anthonydresser** [comment] 2018-10-18 22:11
@kburtram Should we disable the custom bar setting, sounds like using it puts the user where they don't have either menu bar.

**Comment by dylmye** [comment] 2018-11-07 16:06
@anthonydresser I'd be happy to raise a PR removing this setting if you'd like

**Comment by anthonydresser** [comment] 2019-02-05 19:55
I'm going to close this as a dupe of #3300 as its a more general issue for this same problem.

**Closed by anthonydresser** 2019-02-05 19:55 UTC
Labels: bug, ux
