### ISSUE TITLE
Database connection toolbar missing for sql scripts

### ISSUE THREAD

**Issue by timgaunt** [microsoft/azuredatastudio#16436] opened 2021-07-26 05:09 UTC
- Azure Data Studio Version: Version: 1.31.0 Commit: a430fd2592763ef4c4a406821967e4b7b2b3d876
- OS Version: MacOS Big Sur 11.5

Steps to Reproduce:

1. Open a SQL script
2. Try to connect to a database using the toolbar

# Actual
<img width="754" alt="2021-07-26_06-05-31 (17)" src="https://user-images.githubusercontent.com/254564/126935899-775773eb-adbc-4a8c-b3d0-17b546107752.png">

# Expected
<img width="813" alt="2021-07-26_06-06-50" src="https://user-images.githubusercontent.com/254564/126935951-23db3f02-5144-487a-9ef4-ab85bbe1a291.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment] 2021-07-26 15:52
How are you opening the file? (command line, file -> open, other?)

If you aren't opening it via file -> open, does the issue still repro when closing it and re-opening with file -> open?

**Comment by timgaunt** [comment] 2021-07-26 15:57
> How are you opening the file? (command line, file -> open, other?)

⌘+O keyboard shortcut 
 
> If you aren't opening it via file -> open, does the issue still repro when closing it and re-opening with file -> open?

It does yes.

Interestingly, files which were open before the update are still showing the menu.

**Comment by Charles-Gagnon** [comment] 2021-07-26 16:05
Hm, well I was able to repro this behavior a couple times myself but now it seems to be working as expected....

Could you try :

1. Opening the .sql file
2. Closing ADS
3. Re-opening ADS

Does the editor still show without the toolbar?

**Comment by Charles-Gagnon** [comment] 2021-07-26 18:55
For anyone else hitting this issue, could you please provide the following information : 

1. Does this happen even after ADS has been opened for a while?
2. If you close the file and then close and re-open ADS does it still show without the toolbar?

**Comment by jesman3** [comment] 2021-07-26 19:04
To answer your 2 questions. Yes it happens even after ADS has been opened for while. I have had it opened for several hours and it is still happening.

Yes if i close the file and then close ADS and re-open it still shows without the toolbar.

**Comment by Charles-Gagnon** [comment] 2021-07-26 19:25
@jesman3 Could you try : 

1. Closing the file
2. Closing ADS
3. Deleting the `%APPDATA%\azuredatastudio\Cache` folder (this won't affect any saved connections or user settings)
4. Restarting ADS and re-opening the file

**Comment by timgaunt** [comment] 2021-07-26 19:26
@Charles-Gagnon same for me, it's the same even if I've restarted the Mac.

Where are the cache files stored on a Mac and I'll give that a go

**Comment by jesman3** [comment] 2021-07-26 19:34
@Charles-Gagnon
I followed steps 1 through 4 and the issue did not go away.

**Comment by Charles-Gagnon** [comment] 2021-07-26 20:05
@timgaunt You can get to this by running the `Developer: Open Logs Folder` command and then going up 2 directories

@jesman3 What type of installation do you have? (User, System, zip). And how are you opening the file? File -> Open (Ctrl+O) or something else?

**Comment by timgaunt** [comment] 2021-07-26 20:34
@Charles-Gagnon it seems happier now but I'll let you know if it continues to be an issue tomorrow

**Comment by jesman3** [comment] 2021-07-26 20:59
@Charles-Gagnon I believe it is a User installation but I am not sure. I can duplicate this by opening any .sql file as it will not have the connection toolbar and I cannot seem to figure out how to get the .sql file to connect to a database. 
I open it with File -> Open or even with File -> Open Recent. Either way duplicates the issue. Another way to duplicate the issue is to select File -> New Query which will open a new query WITH the toolbar visible then if you save that query via File -> Save the toolbar immediately disappears.

**Comment by jesman3** [comment] 2021-07-26 21:02
@Charles-Gagnon One other note is that I download a pre-release version of Azure Data Studio about a month ago to test for a bug fix regarding an array slice error and I noticed this same SQL toolbar behavior in the pre-release version but I didn't think too much of it as I was just testing the array slice error. I still have that pre-release version installed but I don't use it. Also, my co-workers who still have version 1.30 are not experiencing this issue.

**Comment by Charles-Gagnon** [comment] 2021-07-26 21:37
Thanks for the confirmation @timgaunt - my understanding of the issue is that as long as your cache isn't cleared this issue shouldn't happen for you anymore. But definitely let me know if that's not the case.

@jesman3 The Help -> About window will have that information 

![image](https://user-images.githubusercontent.com/28519865/127062306-d3bdf522-f638-4387-9fd8-79d88c8a1c3f.png)

Can you get me your logs per these instructions? It's unclear why your instance is behaving differently than mine during my testing and that might have something useful in it 

**Log Collection Instructions**

There are two types of logs to collect:

Console Logs

Open Developer Tools (Help -> Toggle Developer Tools)
Click the Console tab
Click in the log area and select all text (CTRL+A)
Save this text into a file named console.log and attach it to this issue.
Application Logs

Open command palette (Click View -> Command Palette)
Run the command: Developer: Open Logs Folder
This will open the log folder locally. Please zip up this folder and attach it to the issue.

**Comment by Charles-Gagnon** [comment] 2021-07-27 01:35
@jesman3 If you get a chance could you try out this private build to see if it resolves your issue?

https://sqltools.blob.core.windows.net/public/azuredatastudio-win32-x64.zip

Just unzip that and run the `azuredatastudio-insiders.exe` found inside the extracted folder.

**Comment by dot-fs** [comment] 2021-07-27 12:56
I have the exact same symptoms as @jesman3, I use the user setup version.
None of the suggestions helped for me, either.

The insider build you have provided does indeed fix the issue for me (the offending .sql files have to be reopened though)

**Comment by jesman3** [comment] 2021-07-27 15:00
@Charles-Gagnon I did not have the same luck as @dot-fs the insiders version did not resolve the issue. I have attached a gif showing the easiest flow to duplicate the issue. The only thing I notice is that the language on the status bar at the bottom changes from MSSQL when the toolbar is visible to SQL when the toolbar is not visible.
![ADS-SQLIssue](https://user-images.githubusercontent.com/12089698/127177681-3f52673d-c86c-40e7-a6df-d9d1c5ada0d7.gif)

**Comment by dot-fs** [comment] 2021-07-27 15:12
Interestingly, just using the insider build seems to have fixed the installed version for me.
Files saved while the issue was present have to be reopened (and maybe re-saved, i did that) but I can't reproduce the issue anymore (in any of the two builds).

**Comment by jesman3** [comment] 2021-07-27 16:39
FYI, I finally just did a full uninstall and re-install and everything is working fine in version 1.31. Sorry you have one less test subject now. Thanks for your help!!!

**Comment by Charles-Gagnon** [comment] 2021-07-27 16:47
Thanks for letting me know @jesman3! There definitely seems to be some sort of caching issue, if anyone else tries uninstalling/reinstalling and is still seeing this issue then please let me know.

We'll have a hotfix out for fixing some of the other issues that people are seeing with this, but the suggestions above in this thread should mostly resolve any problems people are running in to currently with my current understanding of the specific issues being hit here.

**Comment by TunnyF24** [comment] 2021-07-27 17:39
> @jesman3 If you get a chance could you try out this private build to see if it resolves your issue?
> 
> https://sqltools.blob.core.windows.net/public/azuredatastudio-win32-x64.zip
> 
> Just unzip that and run the `azuredatastudio-insiders.exe` found inside the extracted folder.

This has also fixed my issue.

The other problem that I experienced at the same time (and still with this fix) is any of my old saved templates stopped being recognised as queries and were opening as text pages. (they didn't have .sql as their file type but worked fine)

When you create 'new file' from within explorer it's creating a 'Plain Text' page, where as before this would open anew query.

after creating this, if you then change the language type to SQL from plain text, it then locks the page and you can't type anything.
![image](https://user-images.githubusercontent.com/88048134/127200900-3c28f114-3633-4b11-b526-fcac590d283b.png)
![image](https://user-images.githubusercontent.com/88048134/127200991-914f7b63-d1cc-450a-8189-703504ef2a42.png)

If you then rename the page to include the .sql file extension at the end, close it and re open it, it displays as it should
![image](https://user-images.githubusercontent.com/88048134/127201721-25a3b861-118e-467a-89ff-a6f06cc68ca8.png)

**Comment by Charles-Gagnon** [comment] 2021-07-27 17:56
@TunnyF24 That's expected behavior - we recognize things as queries based on their file extension and so if they don't have a .sql extension then they'll just open as plain text. So when creating a new file make sure to add the .sql extension to the end (or add it later and close/reopen as you found out)

Changing the language mode doesn't change the editor - so a text editor set to the SQL language will not be displayed as a query editor. It's something we'd like to fix at some point - but I believe this has always been the behavior for files originally opened as text files.

**Comment by emilhizer** [comment] 2021-07-28 14:27
Having this same issue on Mac. Tried uninstall / reinstall. SQL files open as plain text files (no connection toolbar available). I see the private build available for Windows, but any love for us Mac users? Quick fix is open .SQL file (has no connection toolbar), open new tab (has toolbar by default), copy/paste script from .SQL tab to new tab. Only started having this problem a couple of days ago - an issue with the new build/release on 7/21???

From About ADS:
Version: 1.31.0
Commit: a430fd2592763ef4c4a406821967e4b7b2b3d876
Date: 2021-07-20T19:49:59.277Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

**Comment by Charles-Gagnon** [comment] 2021-07-28 14:46
@emilhizer The latest [insiders build](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master) has the fix for this. Let us know if that still doesn't solve your issue.

We'll be releasing a hotfix for this in the next day or two for the stable version.

**Comment by emilhizer** [comment] 2021-07-28 20:45
Thanks @Charles-Gagnon - works perfectly. And thanks for the direct link to the insiders build.

**Comment by Charles-Gagnon** [comment] 2021-07-29 16:03
The stable hotfix for this issue has gone out - please update to 1.31.1 and if you're still seeing issues let me know!

**Closed by Charles-Gagnon** 2021-07-29 16:03 UTC
Labels: Approved, Area - Query Editor, Bug, Needs Logs, Triage: Done

**Comment by MangoZMR** [comment] 2021-08-03 15:41
i have upgraded to 1.31.1 but still have the same issue:
![image](https://user-images.githubusercontent.com/88392899/128044905-bdff976e-3697-456e-be26-ba491034d42c.png)
![image](https://user-images.githubusercontent.com/88392899/128045018-ca3ffb5a-3aaf-441c-a405-aea83183da56.png)

**Comment by Charles-Gagnon** [comment] 2021-08-03 15:49
Did you close and re-open the tabs?

If that still isn't working try this : 

1. Close all the tabs currently open
1. Run the `Developer: Open Logs Folder` command
2. Go up two directories to the `azuredatastudio` directory
3. Close ADS
4. Delete the `Cache` folder
5. Restart ADS and open up the editors again

**Comment by MangoZMR** [comment] 2021-08-03 15:58
> 2\. Developer: Open Logs Folder

I tried it but it doesn't work.

**Comment by Charles-Gagnon** [comment] 2021-08-03 16:01
Tried what? Both options? Some people also said that they had to uninstall and reinstall to get it to pick up the fix properly - so would be worth trying that if you're able. 

Otherwise could you list the exact steps you're taking to open this file?

**Comment by MangoZMR** [comment] 2021-08-03 17:42
I tried the steps that you show above to delete the Cache folder, and it does not work. Below is showing how I open the file:

![AzureGIF](https://user-images.githubusercontent.com/88392899/128061382-7c3a68ba-07f0-4147-bf99-a0d460f55ad9.gif)

**Comment by Charles-Gagnon** [comment] 2021-08-04 01:34
Could you 

1. Download https://sqltools.blob.core.windows.net/public/azuredatastudio-win32-x64.zip
2. Unzip the archive
3. Run azuredatastudio.exe from the extracted folder
4. Repro the issue (closing the file and then re-opening if it's already open)
5. Collect the two types of logs detailed below 

**Log Collection Instructions**

There are two types of logs to collect:

Console Logs

Open Developer Tools (Help -> Toggle Developer Tools)
Click the Console tab
Click in the log area and select all text (CTRL+A)
Save this text into a file named console.log
Application Logs

Open command palette (Click View -> Command Palette)
Run the command: Developer: Open Logs Folder
This will open the log folder locally. Please zip up this folder

Upload both sets of logs to this issue.

**Comment by MangoZMR** [comment] 2021-08-05 13:31
> Could you
> 
> 1. Download https://sqltools.blob.core.windows.net/public/azuredatastudio-win32-x64.zip
> 2. Unzip the archive
> 3. Run azuredatastudio.exe from the extracted folder
> 4. Repro the issue (closing the file and then re-opening if it's already open)
> 5. Collect the two types of logs detailed below
> 
> **Log Collection Instructions**
> 
> There are two types of logs to collect:
> 
> Console Logs
> 
> Open Developer Tools (Help -> Toggle Developer Tools)
> Click the Console tab
> Click in the log area and select all text (CTRL+A)
> Save this text into a file named console.log
> Application Logs
> 
> Open command palette (Click View -> Command Palette)
> Run the command: Developer: Open Logs Folder
> This will open the log folder locally. Please zip up this folder
> 
> Upload both sets of logs to this issue.

@Charles-Gagnon  Thank you, please see the files below:
[logfolderZip.zip](https://github.com/microsoft/azuredatastudio/files/6938986/logfolderZip.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/6938988/console.log)

**Comment by Charles-Gagnon** [comment] 2021-08-05 17:53
Thanks! Unfortunately that still wasn't enough to figure out what was going on here - I uploaded a new version with even more logging. So if you could download that and follow the same steps I'd appreciate that!

Link is the same : https://sqltools.blob.core.windows.net/public/azuredatastudio-win32-x64.zip

(also I removed the logs from your message since I no longer need them)

**Comment by MangoZMR** [comment] 2021-11-05 15:27
@Charles-Gagnon  Hi I have upgrade my ADS to version 1.33.1, but the issue is still there. Would you please help.
![image](https://user-images.githubusercontent.com/88392899/140535795-4620c583-9890-46eb-9881-db333f8b2eb0.png)

**Comment by Charles-Gagnon** [comment] 2021-11-05 17:54
@MangoZMR Does this continue to happen even if you close the query and open a new one?

**Comment by MangoZMR** [comment] 2021-11-05 19:14
@Charles-Gagnon There is no toolbar even I close the query and open a new one. Thank you.

**Comment by Charles-Gagnon** [comment] 2021-11-05 22:16
Alright, here's another private build with additional logging if you don't mind trying it out 

1. Download https://sqltools.blob.core.windows.net/public/editor-issue/azuredatastudio-win32-x64.zip
1. Unzip the archive
1. Run azuredatastudio.exe from the extracted folder
1. Repro the issue (closing the editor and then re-opening if it's already open)
1. Collect the two types of logs detailed below

### Log Collection Instructions

There are two types of logs to collect:

#### Console Logs

Open Developer Tools (Help -> Toggle Developer Tools)
Click the Console tab
Click in the log area and select all text (CTRL+A)
Save this text into a file named console.log

#### Application Logs

Open command palette (Click View -> Command Palette)
Run the command: Developer: Open Logs Folder
This will open the log folder locally. Please zip up this folder

E-mail me the logs (chgagnon@microsoft.com) or upload them to this issue

**Comment by cipinistor** [comment] 2023-03-23 12:07
I'll leave this here, maybe it will help somebody.
The only way to fix this for me was to delete the folder `~/Library/Application Support/azuredatastudio`
