### ISSUE TITLE
Start SQL Script over several SQL servers

### ISSUE THREAD

**Issue by OSch24** [microsoft/azuredatastudio#10915] opened 2020-06-15 14:51 UTC
Hello,

a question I haven't figured out yet. In SSMS I can run one SQL over several SQL servers or all SQL servers of a group.

How does this work with Azure Data Studio?
If this is not yet possible, I would like to see it. This function is extremely helpful.

**Comment by Charles-Gagnon** [comment] 2020-06-15 17:51
This functionality isn't currently implemented in ADS unfortunately. I'll be closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/28 - you can follow that for any updates in that area

**Closed by Charles-Gagnon** 2020-06-15 17:51 UTC
Labels: Enhancement, Triage: Needed
