### ISSUE TITLE
Running cell for Analyze in Notebook fails when Knox endpoint in BDC has a different password

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#5058] opened 2019-04-16 21:33 UTC
- Azure Data Studio Version: master

Steps to Reproduce:
1. Create a SQL Big Data Cluster that uses different passwords for the SQL and Knox endpoints.
2. Run Analyze in Notebook on a csv in the cluster's HDFS.
3. Run the generated cell. It throws the following 401 Unauthorized error.

Error:
The code failed because of a fatal error:
Invalid status code '401' from https:// X.X.X.X:30443/gateway/default/livy/v1/sessions with error payload: .

**Comment by alanrenmsft** [comment] 2019-04-16 22:15
@kevcunnane , IIUC, this is by design, the passwords has to match. right?

**Comment by kevcunnane** [comment] 2019-04-16 22:22
@alanrenmsft somewhat correct. We know this is a potential issue, so should handle it. In HDFS expansion scenario we prompt for password if authentication fails. That's the correct solution here, so let's keep it open.

**Comment by kevcunnane** [comment] 2019-05-28 17:54
Moving into June. On connecting with Spark kernels, we should be able to verify password (by pinging HDFS) and error / show connection dialog if fails.

@YurongHe this would be a great one to pick up this week if you can.

**Comment by YurongHe** [comment] 2019-05-31 18:24
Relate to  #5753

**Comment by Guillaume-Fourrat** [comment] 2019-08-22 09:50
Hi, confirming this is still active using ADS
 ```
Version: 1.10.0-insider (user setup)
Commit: 7f6839d38e24ebd637f2b7ae3b7a5995421c44b2
Date: 2019-08-18T14:37:30.357Z
```

Hitting following msg for any spark interactive payload as soon as SAPWD != KNOXPWD:

```

The code failed because of a fatal error:
	Invalid status code '401' from https://10.1.0.5:30443/gateway/default/livy/v1/sessions with error payload: .

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.
```

Could you confirm the following ?
>
> @kevcunnane , IIUC, this is by design, the passwords has to match. right?
>
The "somewhat correct" answer from @kevcunnane is a bit confusing =)

As it stands, this conflicts with ongoing [Doc](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-guidance?view=sqlallproducts-allversions#env) as follows

1. No mention of requirement of aligning SA PWD with KNOX PWD
2. Worse, the "SA PWD discoverable and to be changed after deployment" is likely to lead to a different password set in most situations.

So not sure if we have a doc bug where we need to mention that the pwd must be aligned, or a ADS bug where there's some invalid reuse of credentials ?

**Comment by chlafreniere** [comment] 2019-10-19 02:41
@kevcunnane does this still repro?

**Comment by kevcunnane** [comment] 2019-10-21 20:34
@chlafreniere yes it does.

**Comment by Charles-Gagnon** [comment] 2022-12-06 22:55
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.

**Closed by Charles-Gagnon** 2022-12-06 22:55 UTC
Labels: Bug, Area - Notebooks, Area - Data Virtualization, Triage: Done, Subarea - BDC/Spark
