### ISSUE TITLE
Filter capabilities

### ISSUE THREAD

**Issue by joseluisrod** [microsoft/azuredatastudio#7377] opened 2019-09-26 12:40 UTC
Issue Type: <b>Feature Request</b>

Hi All: could you add filtering by name for tables, programmability and views please?  Thanks for the great work!

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Charles-Gagnon** [comment] 2020-07-22 22:58
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as some cleanup

**Closed by Charles-Gagnon** 2020-07-22 22:58 UTC
Labels: Area - Data Explorer, Enhancement, Triage: Done
