### ISSUE TITLE
Sign in to Azure

### ISSUE THREAD

**Issue by alfeuduran** [microsoft/azuredatastudio#9104] opened 2020-02-10 14:22 UTC
Issue Type: <b>Bug</b>

In mac os when i try to "Sign in to Azure" the error "Entry not found in cache" appears. 

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:37:56.865Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.2

</details>

**Comment by alfeuduran** [comment] 2020-02-10 14:24
Yes, it is a duplicate #7619 .

**Comment by Charles-Gagnon** [comment] 2020-02-10 15:41
Have you tried the new sign in experience mentioned in that thread?

**Comment by DTronD** [comment] 2020-02-18 13:12
@Charles-Gagnon  - could you provide details on HOW to add the environment variable NEW_SIGN_IN_EXPERIENCE=true as mentioned in #7619 , please?

I couldn't figure out where to put that entry but I managed to clear the "entry not found in cache" error by deleting the token cache file:

C:\Users\JoeBlow\AppData\Roaming\azuredatastudio\Azure Accounts\azureTokenCache-azurePublicCloud

**Comment by Charles-Gagnon** [comment] 2020-02-18 16:22
Have you updated to the 1.15 release? That has the new sign in experience enabled by default.

**Comment by kburtram** [comment] 2020-03-23 17:55
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/9056.  Please add any additional comments to that issue.  I think this experience has been significantly updated since 1.14.1.

**Closed by kburtram** 2020-03-23 17:55 UTC
Labels: Area - Azure, Bug, Triage: Needed
