### ISSUE TITLE
Results to Text

### ISSUE THREAD

**Issue by shpsyte** [microsoft/azuredatastudio#12770] opened 2020-10-06 20:59 UTC
**Is your feature request related to a problem? Please describe.**
I know that this feature is present on SSMS, however, will be awesome to see here!

**Describe alternatives you've considered**
Saving the result as CSV I get the same result

**Comment by JediSQL** [comment] 2020-12-26 01:01
Since SQL 7, at least, SQL Server query windows have allowed the user to choose between results to grid (Ctrl-D) and results to text (Ctrl-T). Many T-SQL scripts have been written on the premise of outputting formatted results to a text results window. If ADS, Azure Data Studio, query windows do not support results to text, it will make it hard to migrate from SSMS (SQL Server Management studio) to ADS. Results to text is NOT the same thing as saving grid results to a text file. Results to text mixes text formatted query results with the output of PRINT statements, etc.

**Comment by xrayzwei** [comment] 2021-02-25 21:18
Wanted to add an additional comment to support this being integrated into ADS. Results and Messages together in the file was very useful in SMSS

**Comment by kburtram** [comment] 2021-09-10 22:12
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/52.  Thanks for opening this suggestion!

**Closed by kburtram** 2021-09-10 22:12 UTC
Labels: Area - Query Editor, Enhancement, Triage: Done
