### ISSUE TITLE
Copying results window (including headers) pastes in different order

### ISSUE THREAD

**Issue by BlackSneak** [microsoft/azuredatastudio#8329] opened 2019-11-14 03:13 UTC
Issue Type: <b>Bug</b>

I have SQL statements that populate a temporary table that has 50 columns, and a final select statement that returns the results (around 150 rows).

If I Ctrl + A in the results window to highlight all rows, then right-click -> Copy With Headers, then paste into Excel, the column headers are in the same order but some of the columns have been transposed.

I.e. the data in column 9 in the results window displays in column 49 in Excel. And vice-versa; column 9 in Excel is null.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (1.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.1

</details>

**Comment by Charles-Gagnon** [comment] 2019-11-14 03:19
Closing as a duplicate of #8210

This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release. Sorry about the inconvenience!

**Closed by Charles-Gagnon** 2019-11-14 03:19 UTC
Labels: Area - Query Editor, Bug
