### ISSUE TITLE
File save after running a query causes the result set to disappear

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12502] opened 2020-09-19 02:30 UTC
- Azure Data Studio Version:
Version: 1.22.0-rc1 (user setup)
Commit: 7f3d5bac0a64c64a16df025c69f549e390a2783f
Date: 2020-09-18T20:40:16.015Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a new KQL or SQL query.
2. Write a statement like `StormEvents | take 10` for Kusto
3. Run the query.
4. Save the file. 

Actual:
![FileSaveRemovesResultSet](https://user-images.githubusercontent.com/6405919/93657721-b3f38a80-f9e9-11ea-8830-e2815fb4b5eb.gif)

Expected:
resultset should not disappear

SSMS doesn't hide / remove result set after saving. See below -
![FileSaveRemovesResultSetSSMS](https://user-images.githubusercontent.com/6405919/93657405-7857c100-f9e7-11ea-9443-7f9a70509341.gif)

Why this is important?
Say I'm a data analyst, starting a new file, typing a query then running it which might take 20 minutes to run, returning 500 rows. The query looks good but I want to continue my analysis. So I'm saving this query before I lost it. Then upon saving the resultset somehow disappeared.

**Comment by MsSQLGirl** [comment] 2020-09-19 02:49
This seems to also happen in Aug 2020 release.
Version: 1.21.0 (user setup)
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:52:47.502Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by MsSQLGirl** [comment] 2020-09-19 02:57
Note: using the Toggle results on/off ( `Win` + `Shift` + `R`), I cannot bring the results back. (At first, I thought it was disappearing because it was toggled off) 
![image](https://user-images.githubusercontent.com/6405919/93657631-0a13fe00-f9e9-11ea-8a72-fcece6e907fe.png)

**Comment by kburtram** [comment] 2021-07-14 21:52
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/1876.

**Closed by kburtram** 2021-07-14 21:52 UTC
Labels: Area - Query Editor, Bug, Triage: Done
