### ISSUE TITLE
Copy does not work

### ISSUE THREAD

**Issue by Ravi5ingh** [microsoft/azuredatastudio#10335] opened 2020-05-11 12:32 UTC
Issue Type: <b>Bug</b>

1. Query any data with Azure Data Studio

2. Try and copy all of part of the results. For eg: a row, a cell, a colum, a subset of data (Ctrl + C or right-click and copy)

3. Sometimes it copies correct, sometimes, it doesn't copy at all, sometimes it copies the wrong field. The issue is not predictable.

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (6.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|1.3.9

</details>

**Comment by kburtram** [comment] 2020-05-11 15:08
This looks a lot like https://github.com/microsoft/azuredatastudio/issues/1388.  Which was recently closed as no repro.  I'll move this one into the next milestone for further investigation.

**Comment by bmallen1** [comment] 2020-05-22 19:25
I've also experienced this issue.

Ran a query, got results: a single integer Id for some record. 

Attempt to copy it from Results window--no dice. 
Right click => Copy, no dice, 
Right click => copy with headers, no dice.

Close and reopen Azure Data Studio => Re-run query => CTRL+C, success!

**Comment by don-binerd** [comment] 2020-06-16 00:08
Me Too!  have tried close and reopen..  still no luck
![copypaste](https://user-images.githubusercontent.com/63085169/84717448-26069e80-afb9-11ea-8d2d-e35fa5da3734.gif)

![image](https://user-images.githubusercontent.com/63085169/84717470-40d91300-afb9-11ea-9ebf-e7e3e88c447d.png)

**Comment by anthonydresser** [comment] 2020-06-16 00:13
@don-binerd looks like your issue is related to notebooks.

**Comment by don-binerd** [comment] 2020-06-16 00:42
The same behaviour (not copying results to clipboard) is happening with a query file too.  very weird

**Comment by don-binerd** [comment] 2020-07-15 21:59
Please close.  
The issue is now working with the latest version of data studio. 

For newbies you must right click the data and not the headers (behaves differently to ssms)

**Closed** 2020-07-15 22:11 UTC
Labels: Area - Query Editor, Bug, Needs Logs, Triage: Done, Triage: Postponed
