### ISSUE TITLE
Cannot drag and drop server connections to a Server Group

### ISSUE THREAD

**Issue by shishini** [microsoft/azuredatastudio#24250] opened 2023-08-30 13:56 UTC
- Azure Data Studio Version: 1.45.1
- OS Version: Windows 10 Pro 22H2

Steps to Reproduce:

1. Create a new server group
2. Drag and drop one server to it (first server or when group is empty it works)
3. Try to drag and drop a second server (doesn't work, i have to edit connections and change group from connection settings)
4. Try to drag and drop a connection out of a group, only work to empty group or default if default is empty 
5. Note that dragging to empty default area only work if you drag down until connection tab turns blue 

In general drag and drop between groups doesn't work as one would expect 

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment] 2023-08-30 15:56
@smartguest can you help investigate? Thanks!

**Comment by smartguest** [comment] 2023-08-30 20:50
If there is an exact duplicate of the connection in a group that you are trying to move the connection to, it won't let you do so, this is by design to prevent confusion.

**Comment by smartguest** [comment] 2023-08-30 20:52
Please hover over your mouse over the connection you are trying to add in the group and take a screenshot, along with the second one already in the group and do the same. If both of them are identical, then adding them won't work. If they are different, then that indicates an issue.

**Comment by smartguest** [comment] 2023-08-30 20:54
update, it looks like it appears that connections for same server, but different users are not working seemingly, this will be addressed

**Comment by Charles-Gagnon** [comment] 2023-08-30 20:55
@smartguest If we aren't currently, it would be good to display a toast notification when a conflicting connection exists to avoid confusion in the future.

**Comment by shishini** [comment] 2023-08-31 13:31
Here are screenshots of my bug
its different connection different names 

![AzureBug](https://github.com/microsoft/azuredatastudio/assets/2177439/2f0c3ecc-d9ae-485b-b0a6-c904f2ea25e7)

I cannot move connections between groups of from the default area to groups by dragging and dropping, is the default area or the group already have at least one connection 

But I can move them around fine from the connection detail 
![AzureBug 2](https://github.com/microsoft/azuredatastudio/assets/2177439/53377e58-86d3-449e-b3a0-3581dcd822c7)

**Closed** 2023-09-06 16:40 UTC
Labels: Bug, Area - Object Explorer, Triage: Done

**Comment by CKAnandP** [comment] 2024-03-06 05:10
My drag n drop is not working it seems.
