### ISSUE TITLE
Azure SQL Migration Extension in Disconnected Environment

### ISSUE THREAD

**Issue by pvandermaas-apriva** [microsoft/azuredatastudio#22558] opened 2023-03-31 00:48 UTC
Issue Type: <b>Bug</b>

Attempting to run the Azure SQL Migration Extension in Azure Data Studio on an Azure VM in a restricted environment (no internet access) and witnessing the following behavior:

Steps:
Connect to Source Server
Right-click -> Manage
General -> Azure SQL Migration

Error in notification popup:

Failed to start Sql Migration Service: Error: Request error: Error
	at ClientRequest.<anonymous> (c:\Users\<userfolder>\.azuredatastudio\extensions\microsoft.sql-migration-1.4.2\dist\main.js:2:7448)
	at ClientRequest.emit (node:events:538:35)
	at TLSSocket.socketErrorListener (node:_http_client:442:9)
	at TLSSocket.emit (node:events:526:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Close tab, repeat
Connect to Source Server
Right-click -> Manage
General -> Azure SQL Migration
Azure SQL Migration tab now has content
New Migration (or, "Migrate to Azure SQL" link in welcome screen)

Hangs with "Waiting for SqlMigrationProvider component to start." in the notification popup.  Never resolves or times-out.

Is this extension supported in a disconnected environment?  If not, is there an available list of hostnames/domains that I can request from my network team to allow access?  I am interested in the assessment information, including SKU recommendations.  TIA.

Extension version: 1.4.2
Azure Data Studio version: azuredatastudio 1.42.0 (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:15:48.982Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|32.00GB (11.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cap-dm** [comment] 2023-04-03 23:11
Just to add to the above, I'm seeing the same behaviour in my environment. 
We have:

- Dev VMs on premise
- SQL instances on premise
- Azure SQL MI
- Private routes from on prem into Azure.
- Proxy between the Dev VMs and the wider internet, but not between the Dev VMs and everything else mentioned. 

Default behaviour throws an exception (different to above) because I'm not authenticating to the proxy. If I fully disable the proxy in Settings > Proxy Support > Off, I get the above exception encountered by [pvandermaas-apriva](https://github.com/pvandermaas-apriva). I got it to load the Azure SQL Migration window once (Proxy Support off, but I think the main app was successfully communicating with the proxy), but then I hung on 'Waiting for SqlMigrationProvider component to start.'

Note: sorry for the brand new account. I made it specifically to comment on this.

**Comment by Charles-Gagnon** [comment] 2023-04-03 23:19
@alanrenmsft Have we tested the service downloader in a proxy environment? The comment from @cap-dm sounds like a separate issue where they have their proxy set up but it still doesn't download the service binaries. 

@cap-dm Can you confirm that other parts of ADS function with the proxy settings you have - a specific example would be the extension gallery loading and displaying the marketplace extensions.

**Comment by alanrenmsft** [comment] 2023-04-04 04:52
so just to confirm, the issue is resolved now, right?

**Comment by cap-dm** [comment] 2023-04-04 05:10
> @cap-dm Can you confirm that other parts of ADS function with the proxy settings you have - a specific example would be the extension gallery loading and displaying the marketplace extensions.

Oh I know I'm having proxy issues! It was more that I was seeing the same errors as [pvandermaas-apriva](https://github.com/pvandermaas-apriva) while experiencing them, so I was throwing some weight behind the SQL Migration Extension (SME) having issues when it was in a disconnected environment. 

Now I'm going to have to apologise because I can't quite remember the sequence of events before finding this ticket. 

- I know I was able to browse to and download the (SME). I don't think I changed any proxy settings prior to this
- Once it was down and I launched it I encountered the problems as described above
- I have tried many proxy settings, but I was finding either ADS or SME would work correctly not both. I finally managed to get both ADS and SME work by nuking all http.proxy* settings in settings.json and restarting the application. I'm actually astounded this works, but here we are. 

I would suggest that both ADS and SME get some more graceful handling of connectivity and proxy issues, it was a pain to debug as those traces don't really tell the end user much.

**Comment by Charles-Gagnon** [comment] 2023-04-04 16:59
We're working on making this experience better, but for the time being these steps should work for getting the extension functioning:

1. Open ADS and run the "Extensions: Open Extensions Folder" command
2. Look for the latest "microsoft.sql-migration-*" folder (e.g. `microsoft.sql-migration-1.4.2`)
3. In there look for a `config.json` file and open it
4. Get the version from the `"version": "*.*.*.*",` line (e.g. `"version": "4.5.0.37"`)
5. Download the zip/tar.gz that corresponds to your OS and replace the `*.*.*.*` in the links below with that version and copy it to the machine that ADS is installed on.

Windows: https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-win-x64-net7.0.zip
Windows (x86): https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-win-x86-net7.0.zip
OSX: https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-osx-x64-net7.0.tar.gz
Linux: https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-rhel-x64-net7.0.tar.gz

e.g. for Windows with version 4.5.0.37 it would be https://github.com/Microsoft/sqltoolsservice/releases/download/4.5.0.38/microsoft.sqltools.migration-win-x64-net7.0.zip
6. Unzip the contents
7. Back in the extension folder make sure the following path exists `<Path to Extension Folder>/migrationService/<Platform>/<Version>` (e.g. `%USERPROFILE%\.azuredatastudio\extensions\microsoft.sql-migration-1.4.2\migrationService\Windows\4.5.0.37`)
8. Copy the unzipped contents from above into this new folder. Verify the path is correct by checking that `<Path to Extension Folder>/migrationService/<Platform>/<Version>/MicrosoftSqlToolsMigration.exe` exists (e.g. `%USERPROFILE%\.azuredatastudio\extensions\microsoft.sql-migration-1.4.2\migrationService\Windows\4.5.0.37\MicrosoftSqlToolsMigration.exe`
9. Reload ADS - the Migration extension should start up correctly

Note that you'll need to do this each time a new version of the service is available - so if you hit the error again follow the instructions above (there will likely be a new version you have to download but the rest of the steps are the same)

**Comment by kburtram** [comment] 2023-05-08 18:19
@AkshayMata @alanrenmsft are we tracking any pending work for the May release with this issue?  Or should we move or close it?

**Comment by alanrenmsft** [comment] 2023-05-08 18:29
I have a follow up work item.

**Comment by sanjeevreddy22** [comment] 2023-06-26 10:51
> We're working on making this experience better, but for the time being these steps should work for getting the extension functioning:
> 
> 1. Open ADS and run the "Extensions: Open Extensions Folder" command
> 2. Look for the latest "microsoft.sql-migration-*" folder (e.g. `microsoft.sql-migration-1.4.2`)
> 3. In there look for a `config.json` file and open it
> 4. Get the version from the `"version": "*.*.*.*",` line (e.g. `"version": "4.5.0.37"`)
> 5. Download the zip/tar.gz that corresponds to your OS and replace the `*.*.*.*` in the links below with that version and copy it to the machine that ADS is installed on.
> 
> Windows: https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-win-x64-net7.0.zip Windows (x86): https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-win-x86-net7.0.zip OSX: https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-osx-x64-net7.0.tar.gz Linux: https://github.com/Microsoft/sqltoolsservice/releases/download/*.*.*.*/microsoft.sqltools.migration-rhel-x64-net7.0.tar.gz
> 
> e.g. for Windows with version 4.5.0.37 it would be https://github.com/Microsoft/sqltoolsservice/releases/download/4.5.0.38/microsoft.sqltools.migration-win-x64-net7.0.zip
> 
> 6. Unzip the contents
> 7. Back in the extension folder make sure the following path exists `<Path to Extension Folder>/migrationService/<Platform>/<Version>` (e.g. `%USERPROFILE%\.azuredatastudio\extensions\microsoft.sql-migration-1.4.2\migrationService\Windows\4.5.0.37`)
> 8. Copy the unzipped contents from above into this new folder. Verify the path is correct by checking that `<Path to Extension Folder>/migrationService/<Platform>/<Version>/MicrosoftSqlToolsMigration.exe` exists (e.g. `%USERPROFILE%\.azuredatastudio\extensions\microsoft.sql-migration-1.4.2\migrationService\Windows\4.5.0.37\MicrosoftSqlToolsMigration.exe`
> 9. Reload ADS - the Migration extension should start up correctly
> 
> Note that you'll need to do this each time a new version of the service is available - so if you hit the error again follow the instructions above (there will likely be a new version you have to download but the rest of the steps are the same)


Hi , I have tried the above method but , still i am not able to use the migration extension. i have internet on VM. Cloud you please help me.

**Comment by kisantia** [comment] 2023-07-10 22:57
@raymondtruong @brian-harris is this issue planned for the July release? Please move it out of the July milestone if it isn't. Thanks!

**Comment by kisantia** [comment] 2023-09-11 18:30
@raymondtruong @brian-harris any updates on this issue? I'll move it to the backlog if there aren't any plans to work on this

**Comment by brian-harris** [comment] 2023-09-11 19:26
is there anything that can be done on the SQL-Migration extension side? or is this all ADS?

**Comment by kisantia** [comment] 2023-09-11 20:26
@brian-harris the issue Alan linked above is completed. Is there anything else that needs to be done for this issue?

**Comment by brian-harris** [comment] 2023-09-11 21:05
I will assign to someone to verify it is fixed.

**Comment by kisantia** [comment] 2023-09-13 21:22
@Ramudaykumar I moved this issue to November. Please close if this is complete or add details on what else needs to be done

**Comment by Ramudaykumar** [comment] 2023-10-03 09:30
If source is in local/reachable from the machine ADS is running, we can do assessment and SKU recommendation without internet connection.

**Closed by Ramudaykumar** 2023-10-03 09:30 UTC
Labels: Bug, Area - SQL Migration
