### ISSUE TITLE
Image referencing in SQL Notebooks

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4454] opened 2019-03-13 21:58 UTC
- Azure Data Studio Version: 1.5.1-insider

Steps to Reproduce:

1. Try to reference an image
2. image must be in C drive
3. Sometimes one of these options works, sometimes not:

```
![Java in SQL](/images/java-r-python.png)  
![Java in SQL](C:/images/java-r-python.png)  
```

4. It'd be nice to be able to reference images where they are, similarly to how it work in VSCode markdown previewer today

**Comment by amthomas46** [comment] 2019-03-13 22:13
FYI @rgward

**Comment by chlafreniere** [comment] 2019-03-25 21:18
Dupe of #3069.

**Closed by chlafreniere** 2019-03-25 21:18 UTC
Labels: bug, notebooks
