### ISSUE TITLE
Schema Compare Plugin: Prefer alter table than re-create table

### ISSUE THREAD

**Issue by leokth** [microsoft/azuredatastudio#8142] opened 2019-10-31 09:52 UTC
Prefer alter table than re-create table

**Comment by udeeshagautam** [comment] 2019-11-04 18:29
@leokth thanks for submitting the issue. Can you please share some details on which scenario is causing the recreate in place of alter the table.

**Comment by leokth** [comment] 2019-11-06 05:31
> @leokth thanks for submitting the issue. Can you please share some details on which scenario is causing the recreate in place of alter the table.

For system upgrade, we would like to add or modify column to existing tables, instead of dropping tables and add again.

**Comment by kisantia** [comment] 2022-06-14 22:46
If column order doesn't matter, the "Ignore Column Order" option might help the update be an Alter table instead of drop and recreate.

**Comment by kisantia** [comment] 2022-12-06 22:33
closing as by design

**Closed by kisantia** 2022-12-06 22:33 UTC
Labels: Needs More Info, Enhancement, Area - Schema Compare, Triage: Done
