### ISSUE TITLE
Word wrap setting is being ignored by notebook text cells.

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#18113] opened 2022-01-18 23:04 UTC
Steps to Reproduce:
1. In the User Settings, set Editor: Word Wrap to "Off".
2. Open a new notebook and add a text cell.
3. Add enough text so that it clips beyond the border of the cell.
4. The cell text wraps around to the next line rather than continuing with a horizontal scroll bar.

**Comment by VasuBhog** [comment] 2022-02-09 19:59
Not a regression. Only see this issue in WYSIWYG. Split / Markdown mode work as expected.

**Comment by chlafreniere** [comment] 2022-02-09 21:46
Thanks @VasuBhog. Moving out, also validated.

**Comment by Charles-Gagnon** [comment] 2022-04-14 20:29
Adding some more information : 

For the markdown editor of text cells the default is "on" : https://github.com/microsoft/azuredatastudio/blob/main/extensions/markdown-language-features/package.json#L314

That means that it'll ignore the current "global" editor setting since it has its own language-specific setting. 

So to disable this you have to specifically set it to "off" for markdown. In settings.json : 

```
    "[markdown]": {
        "editor.wordWrap": "off",
    }
```

We should probably consider removing that default, I'm not sure it makes any sense for us and is definitely confusing for users.

(note this doesn't affect word wrap for the HTML rendered content, that still seems to also not be working correctly)

**Comment by VasuBhog** [comment] 2022-06-03 22:23
Does not seem we have any customer-reported issues in regards to this issue. Will try to target this for August if I get time.

**Comment by chlafreniere** [comment] 2022-06-29 19:49
Hey folks, I would love to not push this beyond August. Do we have clarity on how to fix this?

"Won't fix" is also an option, if this setting is just controlled by the md-specific word wrap setting.

Just don't want to keep punting this 😄 

@VasuBhog @Charles-Gagnon

**Comment by Charles-Gagnon** [comment] 2022-06-29 20:20
Do we actually need to fix this? Have any customers brought this up? This is currently expected behavior and is easy enough to change so not sure that there's anything we need to do here unless we think it's worth trying to change the default.

**Comment by chlafreniere** [comment] 2022-06-29 20:21
> Do we actually need to fix this? Have any customers brought this up? This is currently expected behavior and is easy enough to change so not sure that there's anything we need to do here unless we think it's worth trying to change the default.

No, we don't need to fix this. That's why I said that "won't fix" is also an option. I'm ok if that's what we decide 😄

**Comment by VasuBhog** [comment] 2022-06-29 20:44
Yeah this has not been reported as an issue from customers (specifically livesite as well) so I believe we can close this.

**Comment by chlafreniere** [comment] 2022-06-29 20:45
Closing as won't fix. Will reconsider if we get any customer feedback in this area.

**Closed by chlafreniere** 2022-06-29 20:45 UTC
Labels: Bug, Area - Notebooks, Triage: Done, Subarea - WYSIWYG
