### ISSUE TITLE
"DROP TABLE IF EXIST" statement detected as an error

### ISSUE THREAD

**Issue by drizztdourden08** [microsoft/azuredatastudio#14555] opened 2021-03-04 21:19 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. Using Azure Database here in an Elastic pool, if that information is even useful
2. When written the statement "DROP TABLE IF EXISTS dbo.#xxxxx". It is detected as an error even though the statement is correct and function as normal.

This was reported back in 2019 as well:
https://github.com/microsoft/azuredatastudio/issues/2712

Screenshot:
![image](https://user-images.githubusercontent.com/36481532/110031794-56d46280-7d05-11eb-9e50-1a9f8f6a3cb3.png)

**Comment by Charles-Gagnon** [comment] 2021-03-04 23:31
Duplicate of https://github.com/microsoft/azuredatastudio/issues/13431

**Closed by Charles-Gagnon** 2021-03-04 23:31 UTC
