### ISSUE TITLE
PC restarted for automatic updates: unsaved tabs were restored, empty, but creating new query windows they came back with their original contents

### ISSUE THREAD

**Issue by kierenj** [Microsoft/azuredatastudio#3618] opened 2018-12-12 21:28 UTC
Issue Type: <b>Bug</b>

Actually, I think the title says it all :)  Weird!

They came back blank when I re-opened the app.  I closed them, saying "no" to save changes.

Then I right-clicked a database, "New Query" - and the first one came back.  So I repeated for all 5 "lost" queries.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.53GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment] 2018-12-12 23:08
@kierenj thanks for reporting this bug.  It looks like the issue being tracked with https://github.com/Microsoft/azuredatastudio/issues/3304.  Please add any additional comments in that issue, though as you say, the title pretty much explains the problem 😄.  We just need to dig through the code a bit to find out what's happening here.  I'll close as a duplicate of #3304.

**Closed by kburtram** 2018-12-12 23:08 UTC
