### ISSUE TITLE
New query tabs either yield no result or become unresponsive 

### ISSUE THREAD

**Issue by RNBermudez** [microsoft/azuredatastudio#5550] opened 2019-05-20 21:06 UTC
New query tabs either does not yield a result (displaying empty rows) or they become irresponsible.

To reproduce:

1. Right click on the database and select _New Query_ or right click on a table and choose _Select Top 1000_
2. One of these two scenarios happens:
2.1 If the query successfully retrieves all the data and you attempt to re-run it, the tab will become irresponsive (see screen 1)
2.2 All the table's columns will be displayed with just empty rows (see screen 2)
3. If you attempt to run the same query or another query on the tab it won't respond (same as screen 1)
3.1 If you attempt to cancel the query (red square / _Cancel_) it won't respond.

This started to happen after the latest update for all my connections (local, dev, staging and production environment of ours).

This is my system and software information as reported by Azure Data Studio:
```
Version:            1.7.0 (user setup)
Commit:             e1280022d69b651cfff04b30e830904575c8acda
Date:               2019-05-08T00:55:40.928Z
VS Code             1.33.1
Electron:           3.1.8
Chrome:             66.0.3359.181
Node.js:            10.2.0
V8:                 6.6.346.32
OS:                 Windows_NT x64 10.0.17763

CPUs	            Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)
GPU Status	        2d_canvas: enabled
                    checker_imaging: disabled_off
                    flash_3d: enabled
                    flash_stage3d: enabled
                    flash_stage3d_baseline: enabled
                    gpu_compositing: enabled
                    multiple_raster_threads: enabled_on
                    native_gpu_memory_buffers: disabled_software
                    rasterization: enabled
                    surface_synchronization: enabled_on
                    video_decode: enabled
                    webgl: enabled
                    webgl2: enabled
Load (avg)	        undefined
Memory (System)	    11.85GB (1.71GB free)
Process Argv	
Screen Reader	    no
VM	                0%
```

I have the following extensions installed:
```
azuredatastudio-postgresql v0.1.0
```

![azure-1](https://user-images.githubusercontent.com/17709641/58051776-ee080000-7b07-11e9-9696-7ad9120fbd5b.png)

![azure-2](https://user-images.githubusercontent.com/17709641/58051778-f3654a80-7b07-11e9-9941-e195f768337a.png)

**Comment by kburtram** [comment] 2019-05-20 21:09
@RNBermudez is this happening all the time?  Or intermittently?  I am not able to reproduce locally in my test env.

**Comment by RNBermudez** [comment] 2019-05-20 22:03
@kburtram yes, all the time. 

I haven't re-installed yet because I thought that this may be a weird corner case that you may want to be aware of. I just checked with a college of mine and he is not experiencing any issue with the same databases and the same version of Azure Data Studio.

Needless to say, if there is anything I can do to help please let me know. 

PS: I don't a video recording software installed, but if you think it may be of any help I can fetch one and record what I'm experiencing.

**Comment by kburtram** [comment] 2019-05-20 22:13
@anthonydresser do you have any suggestions for how we could help diagnosis what's happening here?

@RNBermudez could you please check if there are any error in the "Help -> Developer Tools" Console?

**Comment by RNBermudez** [comment] 2019-05-20 22:41
@kburtram here's the Console output when the query returns an empty table:

```Unhandled Promise rejection: Cannot read property 'displayValue' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'displayValue' of undefined
    at response.resultSubset.rows.map.r (workbench.main.js:303611)
    at Array.map (<anonymous>)
    at runner.getQueryRows.then.response (workbench.main.js:303606)
    at ZoneDelegate.invoke (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388)
    at Zone.run (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138)
    at C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Zone.runTask (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595)
    at ZoneTask.invokeTask (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:500)
    at Socket.ZoneTask.invoke (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:279)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at Pipe.onread (net.js:636) TypeError: Cannot read property 'displayValue' of undefined
    at response.resultSubset.rows.map.r (file:///C:/Users/RBermudez/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:303611:52)
    at Array.map (<anonymous>)
    at runner.getQueryRows.then.response (file:///C:/Users/RBermudez/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:303606:51)
    at ZoneDelegate.invoke (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (C:\Users\RBermudez\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)```

So sorry I didn't include this before, totally missed it!

As for the other scenarios: 
- No errors when I try to cancel the -hang- query
- No errors when I try to re-run a successful query
- No errors on a successful query

**Comment by kburtram** [comment] 2021-08-17 18:52
Closing older issues.  We've made numerous improvements in query editor that hopefully helped this scenario.  And we are tracking several related active issues such as https://github.com/microsoft/azuredatastudio/issues/5477.  Please let us know if you're still impacted by this bug, or add additional repro details to one of the related issues if applicable.  Thanks!

**Closed by kburtram** 2021-08-17 18:52 UTC
Labels: Bug, Area - Query Editor
