### ISSUE TITLE
Generated binding for HttpTrigger doesn't include necessary System.Collections.Generic import.

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#17583] opened 2021-11-03 18:32 UTC
1. Create a new Azure Function (HttpTrigger)
2. Add sql binding to function

Expected: output is immediately compileable

Actual: missing `using` statement results in error for "unknown" reference for `IEnumerable<T>`

**Comment by Charles-Gagnon** [comment] 2021-11-03 18:46
Duplicate of https://github.com/microsoft/azuredatastudio/issues/17572

**Closed by Charles-Gagnon** 2021-11-03 18:46 UTC
Labels: Sql Binding
