### ISSUE TITLE
arguments to various az commands in aks cluster creation notebook need to be quoted

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#8075] opened 2019-10-28 23:53 UTC
- Azure Data Studio Version:
Version: 1.14.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.38.0
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Run the BDC Aks cluster creation wizard and script to notebook.
2. Run cells of the notebok that opens.
Actual: Got following error:
Executing: az group create --name arvran-aks-arg --location Australia East
 ERROR: az: error: unrecognized arguments: East
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {group} ...
 An exception has occurred, use %tb to see the full traceback.

SystemExit: Command execution failed with exit code: 2.
	az group create --name arvran-aks-arg --location Australia East

Expected: The notebook execution to succeed.

Workaround: edit the notebook to quote the --location parameter.
Notes: This problem also exists when we execute other aks command wehre the parameter values are allowed to have space.

**Comment by alanrenmsft** [comment] 2019-10-29 01:15
only the location code is supported, not the display name. closing as by design.

**Closed by alanrenmsft** 2019-10-29 01:15 UTC
Labels: Area - Big Data Cluster, Bug
