### ISSUE TITLE
git show changes hangs the UI

### ISSUE THREAD

**Issue by anand348** [microsoft/azuredatastudio#15241] opened 2021-04-26 21:53 UTC
Issue Type: <b>Bug</b>

Edit a save file
click on the filename under source control (configured to use git) extension
hangs the editor

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (17.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|3.3.1
gitlens|eam|10.2.3
ssmskeymap|kev|1.1.0
simple-data-scripter|sea|0.1.3
gitflow|vec|1.2.1

</details>

**Comment by Charles-Gagnon** [comment] 2021-04-26 22:22
Dupe of #15180 - see that issue for more context and how to get versions that don't have this issue until we publish a release with a fix.

**Closed by Charles-Gagnon** 2021-04-26 22:22 UTC
