### ISSUE TITLE
[ADS]-[Notebook]-[BDC Deployment]-Could not display contents: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#6544] opened 2019-07-31 12:45 UTC
Issue Type: <b>Bug</b>

Repro Steps
1.	Click on the connections and select [Deploy SQL Server Big Data Cluster…]
2.	Once you populate the required details and click on [Open Notebook] a new notebook gets opened.
3.	The notebook file is [deploy-bdc-aks] which gets opened
4.	This notebook is shipped as a part of ADS built-in notebook extension and is stored at [C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\resource-deployment\notebooks\bdc\2019]
5.	We can modify some default settings for BDC and AKS deployment in this notebook as per our requirement – changing number of nodes , changing VM Size etc.
6.	Post this we can save this notebook in a different location to make sure we are not disturbing the template notebook and have our own customized deployment copy.
7.	Once this is done we can close the template notebook and open our own saved copy.
8.	The moment we open the saved notebook we notice this error [Could not display contents: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}]
9.	If we notice the console logs in the developer tools window we see the following exceptions

Could not display contents: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
	ZoneDelegate.invoke	@	C:\Users\pradm\AppDa…st\zone-node.js:388
	Zone.run	@	C:\Users\pradm\AppDa…st\zone-node.js:138
	console.(anonymous function)	@	C:\Users\pradm\AppDa…t\zone-node.js:2283
	onDidNotificationChange	@	workbench.main.js:171459
	_register.model.onDidNotificationChange.e	@	workbench.main.js:171447
	fire	@	workbench.main.js:10435
	addNotification	@	workbench.main.js:175957
	error	@	workbench.main.js:249300
	setViewInErrorState	@	workbench.main.js:306387
	(anonymous)	@	workbench.main.js:306253
	rejected	@	workbench.main.js:5726
	ZoneDelegate.invoke	@	C:\Users\pradm\AppDa…st\zone-node.js:388
	onInvoke	@	c:\Users\pradm\AppDa…es\core.umd.js:4156
	ZoneDelegate.invoke	@	C:\Users\pradm\AppDa…st\zone-node.js:387
	Zone.run	@	C:\Users\pradm\AppDa…st\zone-node.js:138
	(anonymous)	@	C:\Users\pradm\AppDa…st\zone-node.js:872
	ZoneDelegate.invokeTask	@	C:\Users\pradm\AppDa…st\zone-node.js:421
	onInvokeTask	@	c:\Users\pradm\AppDa…es\core.umd.js:4147
	ZoneDelegate.invokeTask	@	C:\Users\pradm\AppDa…st\zone-node.js:420
	Zone.runTask	@	C:\Users\pradm\AppDa…st\zone-node.js:188
	drainMicroTaskQueue	@	C:\Users\pradm\AppDa…st\zone-node.js:595
	Promise.then (async)		
	scheduleMicroTask	@	C:\Users\pradm\AppDa…st\zone-node.js:578
	ZoneDelegate.scheduleTask	@	C:\Users\pradm\AppDa…st\zone-node.js:410
	onScheduleTask	@	C:\Users\pradm\AppDa…st\zone-node.js:297
	ZoneDelegate.scheduleTask	@	C:\Users\pradm\AppDa…st\zone-node.js:401
	Zone.scheduleTask	@	C:\Users\pradm\AppDa…st\zone-node.js:232
	Zone.scheduleMicroTask	@	C:\Users\pradm\AppDa…st\zone-node.js:252
	scheduleResolveOrReject	@	C:\Users\pradm\AppDa…st\zone-node.js:862
	resolvePromise	@	C:\Users\pradm\AppDa…st\zone-node.js:808
	(anonymous)	@	C:\Users\pradm\AppDa…st\zone-node.js:724
	original.call.values	@	internal/util.js:286
	(anonymous)	@	c:\Users\pradm\AppDa…fs\polyfills.js:287
	(anonymous)	@	original-fs.js:155

ERROR Error: Uncaught (in promise): Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
    at _validateUri (workbench.main.js:21287)
    at new URI (workbench.main.js:21404)
    at new _URI (workbench.main.js:21583)
    at Function.parse (workbench.main.js:21495)
    at Object.isLocal (workbench.main.js:22016)
    at Object.handleDefaults (workbench.main.js:22253)
    at Object.renderHTML (workbench.main.js:22078)
    at RenderedHTML.render (workbench.main.js:181049)
    at RenderedHTML.renderModel (workbench.main.js:181009)
    at MimeRendererComponent.createRenderedMimetype (workbench.main.js:86493)
    at MimeRendererComponent.renderOutput (workbench.main.js:86486)
    at MimeRendererComponent.layout (workbench.main.js:86482)
    at OutputComponent.layout (workbench.main.js:180736)
    at OutputComponent.ngOnInit (workbench.main.js:180705)
    at checkAndUpdateDirectiveInline (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10822)
    at checkAndUpdateNodeInline (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12245)
    at checkAndUpdateNode (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12184)
    at prodCheckAndUpdateNode (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12711)
    at Object.eval [as updateDirectives] (VM720 OutputAreaComponent.ngfactory.js:50)
    at Object.updateDirectives (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12625)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12151)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execComponentViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12446)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12157)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execComponentViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12446)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12157)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at Object.checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at ViewRef_.detectChanges (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10225)
    at NotebookComponent.detectChanges (workbench.main.js:306477)
    at NotebookComponent.setLoading (workbench.main.js:306264)
    at NotebookComponent.<anonymous> (workbench.main.js:306301)
    at Generator.next (<anonymous>)
    at fulfilled (workbench.main.js:5725)
    at ZoneDelegate.invoke (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:388)
    at Object.onInvoke (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156)
    at ZoneDelegate.invoke (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:387)
    at Zone.run (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:138)
    at C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Object.onInvokeTask (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147)
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:420)
    at Zone.runTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:595)
    at _validateUri (workbench.main.js:21287)
    at new URI (workbench.main.js:21404)
    at new _URI (workbench.main.js:21583)
    at Function.parse (workbench.main.js:21495)
    at Object.isLocal (workbench.main.js:22016)
    at Object.handleDefaults (workbench.main.js:22253)
    at Object.renderHTML (workbench.main.js:22078)
    at RenderedHTML.render (workbench.main.js:181049)
    at RenderedHTML.renderModel (workbench.main.js:181009)
    at MimeRendererComponent.createRenderedMimetype (workbench.main.js:86493)
    at MimeRendererComponent.renderOutput (workbench.main.js:86486)
    at MimeRendererComponent.layout (workbench.main.js:86482)
    at OutputComponent.layout (workbench.main.js:180736)
    at OutputComponent.ngOnInit (workbench.main.js:180705)
    at checkAndUpdateDirectiveInline (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10822)
    at checkAndUpdateNodeInline (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12245)
    at checkAndUpdateNode (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12184)
    at prodCheckAndUpdateNode (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12711)
    at Object.eval [as updateDirectives] (VM720 OutputAreaComponent.ngfactory.js:50)
    at Object.updateDirectives (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12625)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12151)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execComponentViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12446)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12157)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execComponentViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12446)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12157)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at callViewAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12472)
    at Object.checkAndUpdateView (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12152)
    at ViewRef_.detectChanges (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10225)
    at NotebookComponent.detectChanges (workbench.main.js:306477)
    at NotebookComponent.setLoading (workbench.main.js:306264)
    at NotebookComponent.<anonymous> (workbench.main.js:306301)
    at Generator.next (<anonymous>)
    at fulfilled (workbench.main.js:5725)
    at ZoneDelegate.invoke (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:388)
    at Object.onInvoke (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156)
    at ZoneDelegate.invoke (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:387)
    at Zone.run (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:138)
    at C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Object.onInvokeTask (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147)
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:420)
    at Zone.runTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:595)
    at resolvePromise (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:814)
    at resolvePromise (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:771)
    at C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:873
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Object.onInvokeTask (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147)
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:420)
    at Zone.runTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:595)

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (2c12b95e176e94f4e55b2a66774abfaf837c2dbb, 2019-07-30T18:50:20.139Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (12 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by corivera** [comment] 2019-08-07 22:30
Issue doesn't repro for me. Closing as fixed.

**Comment by alanrenmsft** [comment] 2019-08-07 22:33
@corivera Did you try it on Windows?

**Comment by corivera** [comment] 2019-08-07 23:10
Yes. Didn't see any issues after doing Save & Save As and reopening the resulting notebooks a couple of times.

**Comment by corivera** [comment] 2019-08-07 23:21
Reopening this. Issue is caused by the saved output having links in it, nothing about saving specifically.

**Comment by corivera** [comment] 2019-08-08 00:04
@alanrenmsft  Seems like it might be related to having a colon in the HTML. Here's an isolated repro for this issue:
```Python
from IPython.display import *
display(HTML('<a href="a:b">Test</a>'))
```

If you remove just the colon from "a:b", then the output renders fine.

**Comment by alanrenmsft** [comment] 2019-08-08 01:10
@corivera good to know, but I can't, it seems 'command' protocol is not recognized by the parser, we have to support it.

**Comment by alanrenmsft** [comment] 2019-08-08 01:11
command:commandName is the way you call Azure Data Studio command in notebooks

**Closed** 2019-08-23 21:51 UTC
Labels: Area: Notebooks, Area: SQL 2019, Bug, Triage: Done
