### ISSUE TITLE
Tree nodes do not open or close with arrow buttons

### ISSUE THREAD

**Issue by BEzGumpTion** [microsoft/azuredatastudio#14006] opened 2021-01-20 21:55 UTC
Issue Type: <b>Bug</b>

Case 1
1. Select a tree node with child elements.
2. Hit the right error key on the keyboard.

Expected: The selected tree node expands (so that the child elements are visible).
Actual: Nothing happens.

Case 2
1. Select a tree node with child elements.
2. Hit the left error key on the keyboard.

Expected: The selected tree node collapse (so that the child elements are hidden).
Actual: Nothing happens.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

Extensions: none

**Comment by abist** [comment] 2021-01-21 17:29
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/13749

**Closed by abist** 2021-01-21 17:29 UTC
