### ISSUE TITLE
In server view, search tables

### ISSUE THREAD

**Issue by tigerhawkvok** [Microsoft/azuredatastudio#4748] opened 2019-03-28 19:07 UTC
Issue Type: <b>Feature Request</b>

"Search Server Names" isn't crazy, but for people like me, much less helpful than "search tables". I only have 10 servers, but each server has a dozen databases and each database has a dozens of tables. 

Searching the expanded tables (or even just a view filter, like VSCode's Explorer filter) would be a huge improvement.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kburtram** [comment] 2019-04-24 01:13
@tigerhawkvok have you tried the Redgate Search extension?  It provides this functionality, but it is not integrated with the Servers pane.  In any case, I'll close as a duplicate of #860 since that is tracking the same request.

**Closed by kburtram** 2019-04-24 01:13 UTC
Labels: Area: Data Explorer, Enhancement
