### ISSUE TITLE
Copying data from the results table adds a newline to the copied text.

### ISSUE THREAD

**Issue by WillSullivan** [microsoft/azuredatastudio#6878] opened 2019-08-22 18:42 UTC
Issue Type: <b>Bug</b>

If you select a cell in the Results grid (entire cell is highlighted in blue) and right click and select Copy, you get the text you wanted to copy (yay!) but it's got a newline at the end of the copied text. It's annoying that when you want to paste something you just copied, in my case it's "SP_Text
" you get chunked on the next line.

I don't want to get chunked. Pls don't newline me, bro.

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aaomidi** [comment] 2019-09-04 21:38
Duplicate of #6803

**Closed by aaomidi** 2019-09-04 21:38 UTC
Labels: Area: Query Editor, Bug, Triage: Needed
