### ISSUE TITLE
Command Platte and Context menu disappear automatically while installing some extensions

### ISSUE THREAD

**Issue by AliBaghernejad** [microsoft/azuredatastudio#5149] opened 2019-04-23 13:00 UTC
During the installation process of some extensions we cannot use **command palette** and **drop-down menus** in Azure data studio. (command palette and menus goes away and disappear automatically after a period of time)

Here is an attachment file that describes the issue:
![scrn](https://user-images.githubusercontent.com/10639835/56581709-ceee7f00-65ea-11e9-9a6d-0daaff62db1f.gif)

- Azure Data Studio Version: 
Version: 1.6.0
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
1. Press Ctrl+Shift+X and navigate to the extension panel
2. Try to install "SQL Server import"  Extention
3. Azure data studio will try to download kinds of stuff that are required to the extension. One of this these stuff is:
https://sqlopsextensions.blob.core.windows.net/extensions/import/win-x64.zip
you can see the download process in **Flat File Import Service** in the **output windows**
4. during the download process, you can not use the command palette (Shift+Ctrl+P) and drop down menus.

**Expected Result:** We should work with the command palette and drop down menus normally.
**Observed Result:** Command palette and drop down menus disappear after a period of time.

**Comment by kburtram** [comment] 2019-04-23 23:52
The issue looks like the extension is downloading its platform-specific service component and the progress logging is stealing focus.  In our test environments this download\install is quick enough the issue isn't that impactful, but if the download is taking a longer time then this would be more annoying.

**Comment by Charles-Gagnon** [comment] 2019-07-09 16:37
This is currently in testing and should be fixed in the next stable release

**Closed by Charles-Gagnon** 2019-07-09 16:37 UTC
Labels: Area: Shell, Bug
