### ISSUE TITLE
Notification popup on copying results

### ISSUE THREAD

**Issue by jagdishrajan** [microsoft/azuredatastudio#24158] opened 2023-08-17 17:32 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Copy any cell data from the results output
2. A notification pops up stating 

This was never the case before and one of the recent updates has put this in place.  It is very annoying and if some people need this feature then there should be a setting to turn it off.  Nowhere else in the Windows system do messages keep popping up for just a simple copy.

![image](https://github.com/microsoft/azuredatastudio/assets/5642351/dc76d07f-88d9-4654-80ed-ec9d1efabfac)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by cheenamalhotra** [comment] 2023-08-17 17:47
Hi @jagdishrajan 

This has been addressed in the [insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and fix will be available in the next stable release (ref: https://github.com/microsoft/azuredatastudio/issues/24009#issuecomment-1660872076)
Duplicate of #24009 

Thanks!

**Closed by cheenamalhotra** 2023-08-17 17:47 UTC
