### ISSUE TITLE
False error in AZURE DATA STUDIO

### ISSUE THREAD

**Issue by afeslava** [microsoft/azuredatastudio#18714] opened 2022-03-13 00:56 UTC
I get this error in AZURE DATA STUDIO
'Query failed: Object reference not set to an instance of an object.'
BUT WORKS WELL IN SSMS-18

THE ERROR IS WHEN IS EXECUTED, But apparently AZURE DATA STUDIO affects the same number of rows than SSMS.

;WITH
    CT1
    AS
    (
        SELECT DISTINCT trim(upper(zz_presentationCode)) [zz_presentationCode]
						 ,trim(upper([zz_WorkCenter])) [zz_WorkCenter]
						 ,[zz_WorkC_Present_BDP] 
						 ,PR.F_ID [PR_F_ID]
						 ,CT.F_ID [CT_F_ID]
        FROM zzOeePlans
            INNER JOIN PRESENTATION PR ON PR.F_PRESENTATION_CODE = [zz_presentationCode]
            INNER JOIN CONTROLLER CT ON CT.F_NAME = [zz_WorkCenter]
        WHERE LEN(zz_presentationCode) > 0
    )
SELECT *
FROM CT1
    LEFT OUTER JOIN OEE_PLAN OP ON OP.F_PRESENTATION_ID = [PR_F_ID]
        AND OP.F_CONTROLLER_ID = [CT_F_ID]
ORDER BY [CT_F_ID], [PR_F_ID]

FAILS WITH AZURE DATA STUDIO BUT NOT WITH SSMS

**Comment by alanrenmsft** [comment] 2022-03-15 18:14
@afeslava could you please provide scripts to create the required tables and populate data? It will help if I can reproduce it easily. please make sure the sensitive data are removed from the script.

**Comment by alanrenmsft** [comment] 2022-03-29 03:34
@afeslava please reopen the issue with repro steps and we will look into it.

**Comment by raoulteeuwenPE** [comment] 2022-07-13 10:51
I'm running into this error pretty often as well. Per your request scripts to create the tables for an example where i'm running into this problem:

Table 1 of 2

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [crm].[TriggersExtracted](
	[TriggerProcessLogId] [uniqueidentifier] NOT NULL,
	[RetentieTriggersResponseId] [int] NOT NULL,
	[TriggerGroup] [uniqueidentifier] NOT NULL,
	[OrganizationId] [uniqueidentifier] NOT NULL,
	[ClusterReference] [nvarchar](50) NULL,
	[ConnectionId] [uniqueidentifier] NULL,
	[DateLogged] [datetimeoffset](7) NOT NULL,
	[TriggerType] [nvarchar](255) NOT NULL,
	[TriggerTypeLocalized] [nvarchar](255) NULL,
	[TriggerReason] [nvarchar](255) NULL,
	[TriggerReasonLocalized] [nvarchar](255) NULL,
	[Description] [nvarchar](1024) NULL,
	[Comment] [nvarchar](1024) NULL,
	[Event] [nvarchar](255) NULL,
	[EventLocalized] [nvarchar](255) NULL,
	[EventDate] [datetime] NULL,
	[TriggerEntityId] [uniqueidentifier] NULL,
	[TriggerEntityReference] [nvarchar](255) NULL,
	[AzureQueueId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_TriggersExtracted] PRIMARY KEY CLUSTERED 
(
	[TriggerProcessLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_TriggerType_INCLUDES] ON [crm].[TriggersExtracted]
(
	[TriggerType] ASC,
	[EventDate] ASC
)
INCLUDE([TriggerProcessLogId],[TriggerGroup],[OrganizationId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220406-144631] ON [crm].[TriggersExtracted]
(
	[AzureQueueId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [UX_VKO_EventDate_20181010] ON [crm].[TriggersExtracted]
(
	[EventDate] ASC
)
INCLUDE([TriggerProcessLogId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

Table 2 of 2 

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CRM].[OrganizationEvent](
	[OrganizationEventId] [uniqueidentifier] NOT NULL,
	[RowVersion] [timestamp] NOT NULL,
	[ModifiedBy] [nvarchar](50) NOT NULL,
	[LastModified] [datetimeoffset](7) NOT NULL,
	[DateCreated] [datetimeoffset](7) NOT NULL,
	[ExternalReference] [nvarchar](50) NULL,
	[EventType] [int] NOT NULL,
	[EventSource] [int] NOT NULL,
	[EventDate] [datetime] NOT NULL,
	[Comment] [nvarchar](1024) NULL,
	[OrganizationId] [uniqueidentifier] NOT NULL,
	[ClusterConnectionGroupId] [uniqueidentifier] NULL,
	[ConnectionId] [uniqueidentifier] NULL,
	[EscalationDate] [datetime] NULL,
	[FinalDate] [datetime] NULL,
	[ParentOrganizationEventId] [uniqueidentifier] NULL,
	[InvoiceConnectionGroupId] [uniqueidentifier] NULL,
	[TerminalDate] [datetime] NULL,
	[ParkUntilDate] [datetime] NULL,
	[EDSNDossierId] [nvarchar](50) NULL,
	[EventClassification] [int] NULL,
	[MeansOfProductionId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_CRM.OrganizationEvent] PRIMARY KEY CLUSTERED 
(
	[OrganizationEventId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ClusterConnectionGroupId] ON [CRM].[OrganizationEvent]
(
	[ClusterConnectionGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ConnectionId] ON [CRM].[OrganizationEvent]
(
	[ConnectionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_EventType] ON [CRM].[OrganizationEvent]
(
	[EventType] ASC
)
INCLUDE([OrganizationId],[ClusterConnectionGroupId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_InvoiceConnectionGroupId] ON [CRM].[OrganizationEvent]
(
	[InvoiceConnectionGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MeansOfProductionId] ON [CRM].[OrganizationEvent]
(
	[MeansOfProductionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_OrganizationId] ON [CRM].[OrganizationEvent]
(
	[OrganizationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ParentOrganizationEventId] ON [CRM].[OrganizationEvent]
(
	[ParentOrganizationEventId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [CRM].[OrganizationEvent] ADD  CONSTRAINT [dflt_CRM.OrganizationEvent$OrganizationEventId]  DEFAULT ([Utility].[GenerateNewGuid]()) FOR [OrganizationEventId]
GO
ALTER TABLE [CRM].[OrganizationEvent] ADD  CONSTRAINT [dflt_CRM.OrganizationEvent$ModifiedBy]  DEFAULT (suser_sname()) FOR [ModifiedBy]
GO
ALTER TABLE [CRM].[OrganizationEvent] ADD  CONSTRAINT [dflt_CRM.OrganizationEvent$LastModified]  DEFAULT (sysdatetimeoffset()) FOR [LastModified]
GO
ALTER TABLE [CRM].[OrganizationEvent]  WITH CHECK ADD  CONSTRAINT [FK_CRM.OrganizationEvent_CRM.Connection_ConnectionId] FOREIGN KEY([ConnectionId])
REFERENCES [CRM].[Connection] ([ConnectionId])
GO
ALTER TABLE [CRM].[OrganizationEvent] CHECK CONSTRAINT [FK_CRM.OrganizationEvent_CRM.Connection_ConnectionId]
GO
ALTER TABLE [CRM].[OrganizationEvent]  WITH CHECK ADD  CONSTRAINT [FK_CRM.OrganizationEvent_CRM.ConnectionGroup_ClusterConnectionGroupId] FOREIGN KEY([ClusterConnectionGroupId])
REFERENCES [CRM].[ConnectionGroup] ([ConnectionGroupId])
GO
ALTER TABLE [CRM].[OrganizationEvent] CHECK CONSTRAINT [FK_CRM.OrganizationEvent_CRM.ConnectionGroup_ClusterConnectionGroupId]
GO
ALTER TABLE [CRM].[OrganizationEvent]  WITH CHECK ADD  CONSTRAINT [FK_CRM.OrganizationEvent_CRM.ConnectionGroup_InvoiceConnectionGroupId] FOREIGN KEY([InvoiceConnectionGroupId])
REFERENCES [CRM].[ConnectionGroup] ([ConnectionGroupId])
GO
ALTER TABLE [CRM].[OrganizationEvent] CHECK CONSTRAINT [FK_CRM.OrganizationEvent_CRM.ConnectionGroup_InvoiceConnectionGroupId]
GO
ALTER TABLE [CRM].[OrganizationEvent]  WITH CHECK ADD  CONSTRAINT [FK_CRM.OrganizationEvent_CRM.MeansOfProduction_MeansOfProductionId] FOREIGN KEY([MeansOfProductionId])
REFERENCES [CRM].[MeansOfProduction] ([MeansOfProductionId])
GO
ALTER TABLE [CRM].[OrganizationEvent] CHECK CONSTRAINT [FK_CRM.OrganizationEvent_CRM.MeansOfProduction_MeansOfProductionId]
GO
ALTER TABLE [CRM].[OrganizationEvent]  WITH CHECK ADD  CONSTRAINT [FK_CRM.OrganizationEvent_CRM.Organization_OrganizationId] FOREIGN KEY([OrganizationId])
REFERENCES [CRM].[Organization] ([OrganizationId])
GO
ALTER TABLE [CRM].[OrganizationEvent] CHECK CONSTRAINT [FK_CRM.OrganizationEvent_CRM.Organization_OrganizationId]
GO
ALTER TABLE [CRM].[OrganizationEvent]  WITH CHECK ADD  CONSTRAINT [FK_CRM.OrganizationEvent_CRM.OrganizationEvent_ParentOrganizationEventId] FOREIGN KEY([ParentOrganizationEventId])
REFERENCES [CRM].[OrganizationEvent] ([OrganizationEventId])
GO
ALTER TABLE [CRM].[OrganizationEvent] CHECK CONSTRAINT [FK_CRM.OrganizationEvent_CRM.OrganizationEvent_ParentOrganizationEventId]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [CRM].[trg_CRM.OrganizationEvent$AfterDelete]
ON [CRM].[OrganizationEvent]
AFTER DELETE AS
BEGIN
	DECLARE @rowsAffected int --stores the number of rows affected

	SET @rowsAffected = @@ROWCOUNT

	--no need to continue on if no rows affected
	IF @rowsAffected = 0 RETURN

	SET ROWCOUNT 0 --in case the client has modified the rowcount
	SET NOCOUNT ON --to avoid the rowcount messages

	BEGIN TRY
		--[validation section]
		--[modification section]
		DECLARE @DeletedBy nvarchar(50)
		SELECT @DeletedBy = CONVERT(nvarchar(50), SESSION_CONTEXT(N'User'));


		INSERT INTO [CRM].[OrganizationEvent_past]([OrganizationEvent_pastId], [OrganizationEventId], [ModifiedBy], [DateCreated], [ExternalReference], [EventType], [EventSource], [EventDate], [Comment], [OrganizationId], [ClusterConnectionGroupId], [ConnectionId], [EscalationDate], [FinalDate], [ParentOrganizationEventId], [InvoiceConnectionGroupId], [TerminalDate], [ParkUntilDate], [EDSNDossierId], [EventClassification], [MeansOfProductionId], [TransStartDate], [TransEndDate], [DeletedBy], [RowVersion])
		SELECT [Utility].[GenerateNewGuid](), [OrganizationEventId], [ModifiedBy], [DateCreated], [ExternalReference], [EventType], [EventSource], [EventDate], [Comment], [OrganizationId], [ClusterConnectionGroupId], [ConnectionId], [EscalationDate], [FinalDate], [ParentOrganizationEventId], [InvoiceConnectionGroupId], [TerminalDate], [ParkUntilDate], [EDSNDossierId], [EventClassification], [MeansOfProductionId], [LastModified], SYSDATETIMEOFFSET(), @DeletedBy, [RowVersion]
		FROM [Deleted]
    
	END TRY --when the row was created, these values will be inserted
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION

		EXECUTE [Utility].[ErrorLog$Insert]
    
		DECLARE @errorMessage nvarchar(4000)
		SET @errorMessage = ERROR_MESSAGE()
		RAISERROR (@errorMessage, 16, 1)
	END CATCH
END
GO
ALTER TABLE [CRM].[OrganizationEvent] ENABLE TRIGGER [trg_CRM.OrganizationEvent$AfterDelete]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [CRM].[trg_CRM.OrganizationEvent$AfterUpdate]
ON [CRM].[OrganizationEvent]
AFTER UPDATE AS
BEGIN
	DECLARE @rowsAffected int --stores the number of rows affected

	SET @rowsAffected = @@ROWCOUNT

	--no need to continue on if no rows affected
	IF @rowsAffected = 0 RETURN

	SET ROWCOUNT 0 --in case the client has modified the rowcount
	SET NOCOUNT ON --to avoid the rowcount messages

	BEGIN TRY
		--[validation section]
		--[modification section]
        
		BEGIN TRANSACTION
        
		INSERT INTO [CRM].[OrganizationEvent_past]([OrganizationEvent_pastId], [OrganizationEventId], [ModifiedBy], [DateCreated], [ExternalReference], [EventType], [EventSource], [EventDate], [Comment], [OrganizationId], [ClusterConnectionGroupId], [ConnectionId], [EscalationDate], [FinalDate], [ParentOrganizationEventId], [InvoiceConnectionGroupId], [TerminalDate], [ParkUntilDate], [EDSNDossierId], [EventClassification], [MeansOfProductionId], [TransStartDate], [TransEndDate], [RowVersion])
		SELECT [Utility].[GenerateNewGuid](), [OrganizationEventId], [ModifiedBy], [DateCreated], [ExternalReference], [EventType], [EventSource], [EventDate], [Comment], [OrganizationId], [ClusterConnectionGroupId], [ConnectionId], [EscalationDate], [FinalDate], [ParentOrganizationEventId], [InvoiceConnectionGroupId], [TerminalDate], [ParkUntilDate], [EDSNDossierId], [EventClassification], [MeansOfProductionId], [LastModified], SYSDATETIMEOFFSET(), [RowVersion]
		FROM [Deleted]

		UPDATE [CRM].[OrganizationEvent] SET [LastModified] = SYSDATETIMEOFFSET() FROM [Deleted] WHERE [OrganizationEvent].[OrganizationEventId] IN (SELECT [OrganizationEventId] FROM [Deleted])
        
		COMMIT TRANSACTION
    
	END TRY --when the row was created, these values will be inserted
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION

		EXECUTE [Utility].[ErrorLog$Insert]
    
		DECLARE @errorMessage nvarchar(4000)
		SET @errorMessage = ERROR_MESSAGE()
		RAISERROR (@errorMessage, 16, 1)
	END CATCH
END
GO
ALTER TABLE [CRM].[OrganizationEvent] ENABLE TRIGGER [trg_CRM.OrganizationEvent$AfterUpdate]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [CRM].[trg_CRM.OrganizationEvent$InsteadOfInsert]
ON [CRM].[OrganizationEvent]
INSTEAD OF INSERT AS
BEGIN
	DECLARE @rowsAffected int --stores the number of rows affected

	SET @rowsAffected = @@ROWCOUNT

	--no need to continue on if no rows affected
	IF @rowsAffected = 0 RETURN

	SET ROWCOUNT 0 --in case the client has modified the rowcount
	SET NOCOUNT ON --to avoid the rowcount messages

	BEGIN TRY
		--[validation section]
		--[modification section]
    
		--[perform action]
		INSERT INTO [CRM].[OrganizationEvent]([OrganizationEventId], [ModifiedBy], [DateCreated], [ExternalReference], [EventType], [EventSource], [EventDate], [Comment], [OrganizationId], [ClusterConnectionGroupId], [ConnectionId], [EscalationDate], [FinalDate], [ParentOrganizationEventId], [InvoiceConnectionGroupId], [TerminalDate], [ParkUntilDate], [EDSNDossierId], [EventClassification], [MeansOfProductionId], [LastModified])
		OUTPUT [inserted].[OrganizationEventId], [inserted].[LastModified], [inserted].[RowVersion]
		SELECT [OrganizationEventId], [ModifiedBy], [DateCreated], [ExternalReference], [EventType], [EventSource], [EventDate], [Comment], [OrganizationId], [ClusterConnectionGroupId], [ConnectionId], [EscalationDate], [FinalDate], [ParentOrganizationEventId], [InvoiceConnectionGroupId], [TerminalDate], [ParkUntilDate], [EDSNDossierId], [EventClassification], [MeansOfProductionId], SYSDATETIMEOFFSET()
		FROM [inserted]
        
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION

		EXECUTE [Utility].[ErrorLog$Insert]
    
		DECLARE @errorMessage nvarchar(4000)
		SET @errorMessage = ERROR_MESSAGE()
		RAISERROR (@errorMessage, 16, 1)
	END CATCH
END
GO
ALTER TABLE [CRM].[OrganizationEvent] ENABLE TRIGGER [trg_CRM.OrganizationEvent$InsteadOfInsert]
GO


The following query currently throws me a "Started executing query at Line 1
(1 row affected)
Query failed: Object reference not set to an instance of an object.
Total execution time: 00:00:00.062":

SELECT
    te.*,
    parent_oe.*
FROM crm_addon.crm.TriggersExtracted te
    LEFT OUTER JOIN [Raedthuys.ERP].crm.OrganizationEvent parent_oe ON parent_oe.OrganizationEventId = te.TriggerEntityId
WHERE te.TriggerEntityId='c3d8e50f-c5b2-4f7f-b480-a4ce00e761e6'

**Comment by alanrenmsft** [comment] 2022-12-06 19:18
minimum repro:
```
drop TABLE [dbo].[ObjectErrorTable1];
drop TABLE [dbo].[ObjectErrorTable2];
GO


-- THIS IS TABLE 1
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ObjectErrorTable1](
    [SomeColumn] NVARCHAR(50) NOT NULL
) ON [PRIMARY]
GO


-- THIS IS TABLE 2
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ObjectErrorTable2](
[SomeOtherColumn] NVARCHAR(50) NOT NULL
    , [MeBeingEmptyAndATimeStampTypeThrowsAnError] [TIMESTAMP] NOT NULL -- THE EXISTENCE OF THIS TIMESTAMP COLUMN WITH NULL VALUES WITH CAUSES THE ERROR
) ON [PRIMARY]
GO


-- INSERT DATA
insert into [dbo].ObjectErrorTable1 (SomeColumn)
select 'theresavaluehereontable1'
    ;
GO

-- RUN QUERY TO THROW ERROR
SELECT t1.*, t2.*
FROM [dbo].[ObjectErrorTable1] t1
LEFT OUTER JOIN [dbo].[ObjectErrorTable2] t2 ON t1.SomeColumn = t2.SomeOtherColumn
WHERE t1.SomeColumn='theresavaluehereontable1';
go





-- -- INSERT A MATCHING ROW TO TABLE 2
-- insert into [dbo].[ObjectErrorTable2] (SomeOtherColumn)
-- select 'theresavaluehereontable1';
-- go

-- -- RUN QUERY AGAIN WITHOUT ERROR
-- SELECT t1.*, t2.*
-- FROM [dbo].[ObjectErrorTable1] t1
-- LEFT OUTER JOIN [dbo].[ObjectErrorTable2] t2 ON t1.SomeColumn = t2.SomeOtherColumn
-- WHERE t1.SomeColumn='theresavaluehereontable1';
-- go
```

**Comment by fehrinjt** [comment] 2022-12-09 17:50
Any updates on this? I'm running Version 1.40.1 on MacOS and I'm getting this same issue.
This error makes ADS pretty much unusable as a querying tool anytime running queries like this.

**Closed** 2022-12-16 17:20 UTC
Labels: Bug, Area - Query Editor, Pri: 1, Triage: Done, Size: S

**Comment by alanrenmsft** [comment] 2022-12-16 19:04
@fehrinjt @raoulteeuwenPE @afeslava 
The issue has been fixed in the latest [Insiders Build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and the upcoming release will include the fix. Please give it a try.

**Comment by raoulteeuwenPE** [comment] 2022-12-19 13:51
@alanrenmsft Thanks. Since updating to the Insider Build, i've lost the auto complete feature where i use ij for inner join, loj, st1, ssf etc. Any idea where i should look for how to get that back? Google-ing hasn't brought me a solution as of now...

**Comment by diddlys** [comment] 2023-01-18 16:53
I have the same error with a simple query with two LEFT JOINs. Results are returned, but this error:
![image](https://user-images.githubusercontent.com/98480984/213244397-81012f9f-b347-4838-88c9-3c2e588f208d.png)

If I change the second LEFT JOIN to regular JOIN, no error?

**Comment by alanrenmsft** [comment] 2023-01-18 18:12
@diddlys the fix is only in the insiders build right now, I suppose you are using the stable build. right?

**Comment by diddlys** [comment] 2023-01-18 21:36
Yes that’s right. I’ll try the insiders build 👍Sent from my iPhoneOn 18 Jan 2023, at 18:12, Alan Ren ***@***.***> wrote:﻿
@diddlys the fix is only in the insiders build right now, I suppose you are using the stable build. right?
