### ISSUE TITLE
SQL Database Projects fails to build in ADS but succeeded in VS. And then bringing project back into VS is broken

### ISSUE THREAD

**Issue by kevinvngo** [microsoft/azuredatastudio#11114] opened 2020-06-26 03:10 UTC
Version: 1.20.0-insider (user setup)
Commit: 710d0462d8d81373aa2bc0f36f88955c902cb173
Date: 2020-06-25T05:31:00.820Z
VS Code: 1.46.0
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
Steps to Reproduce:

Using Synapse SQL Pool (SQL DW).

1.	Create SSDT Database Project in VS and then run a successful build.
2.	Open the Database Project in ADS and then Build. Observe failure in ADS:
![image](https://user-images.githubusercontent.com/15145589/85816865-49e88380-b721-11ea-90f1-c6d440cf2717.png)

 
3.	Open VS and attempt to Build the project again. Observe following failure:
![image](https://user-images.githubusercontent.com/15145589/85816862-481ec000-b721-11ea-947e-fef2f196c7f0.png)

**Comment by kisantia** [comment] 2020-06-26 17:28
does doing Rebuild or Build after Clean in VS fail too? The build failing in VS should've been fixed by #10882

**Comment by kevinvngo** [comment] 2020-06-26 20:20
Thanks! After Rebuild, this is resolved. The first issue still occurs though.

**Comment by simonsabin** [comment] 2020-06-30 22:31
The issue is due to the project.assets.json in the obj folder.

I believe a solution is to change the .sqlproj file. data Studio adds this
```
 <Target Name="AfterClean">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json"/>
  </Target>
```
if you change it to the following it works for me.

```
 <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json"/>
  </Target>
```

**Comment by udeeshagautam** [comment] 2020-07-01 23:38
@kevinvngo for the first issue - can you please check what is the value of **QueryStoreMaxStorageSize** tag in sqlproj file that you have. Also, can you please explain how did you create the project in SSDT i.e. via new project flow or importing from a database?

**Comment by udeeshagautam** [comment] 2020-07-13 20:46
@kevinvngo can you please share the bove info on the property value. thanks for your help.

**Comment by udeeshagautam** [comment] 2020-09-09 20:28
This need a DacFx nnuget/ SqlToolsService refresh in ADS hence bringing to Sept

**Closed** 2020-09-10 21:21 UTC
Labels: Area - SQL Project, Bug, Pri: 1
