### ISSUE TITLE
Toggle Query Results shortcut doesn't work when Results have focus

### ISSUE THREAD

**Issue by barryseymour** [microsoft/azuredatastudio#23041] opened 2023-05-08 20:42 UTC
Issue Type: <b>Bug</b>

I mapped Ctrl+` to Toggle my query results window. However, it only works if the text editor window has the focus. 

If I go into the query results to sort, tag, copy, etc, the shortcut no longer works. I have to mouse-click back into the text editor before it will work.

This is the item I modified:
{
  "key": "ctrl+`",
  "command": "toggleQueryResultsKeyboardAction",
  "when": "queryEditorVisible"
}

Can we make this toggle also effective when the results window has the focus? Or maybe the 'when:' parameter might be useful? Not sure how that works.

Thanks,

Barry Seymour

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.20GB (48.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
import|Mic|1.5.4
query-history|Mic|0.5.3
azdata-sanddance|msr|4.0.3
extra-sql-script-as|pac|0.5.0
sql-prompt|Red|0.2.12
sql-search|Red|0.4.2

(1 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by cheenamalhotra** [comment] 2023-09-13 18:16
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/14612

**Closed by cheenamalhotra** 2023-09-13 18:16 UTC
Labels: Area - Query Editor, Enhancement, Triage: Done
