### ISSUE TITLE
Schema compare in source control pane freezes ADS

### ISSUE THREAD

**Issue by lmcconnell1665** [microsoft/azuredatastudio#15259] opened 2021-04-28 02:50 UTC
Issue Type: <b>Bug</b>

When I am connected to a git directory and editing files using the built-in source control features I go to the source control pane ( Ctrl + Shift + G ) and look at the files I have edited but not committed.

With I used to click on a file in this pane it would open a compare with unmodified window to show my changes compared to the last committed vesion of the file.

With the latest update, when I click a file to open this view Azure Data Studio freezes and stops responding to any clicks. Eventually a window opens that says the program has stopped responding and I restart. The problem does not go away after a restart.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.1.0
schema-compare|Mic|1.10.0
sql-database-projects|Mic|0.8.2

</details>

![image](https://user-images.githubusercontent.com/56060247/116339171-974eda80-a7a2-11eb-9c1c-7c1ba0a25174.png)

**Comment by JonathanWilkins** [comment] 2021-04-28 10:54
I'm getting the same issue.  As soon as I click on a file to compare, the memory usage starts climbing. I reopen the window at 3.5 GB.

Version: 1.28.0 (user setup)
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
Date: 2021-04-15T00:24:15.710Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment] 2021-04-28 16:41
Duplicate of https://github.com/microsoft/azuredatastudio/issues/15180 - see that issue for instructions to revert to a working version until a build with the fix is released.

**Closed by Charles-Gagnon** 2021-04-28 16:41 UTC
