### ISSUE TITLE
Cancel button doesnt work

### ISSUE THREAD

**Issue by subbaraonv** [microsoft/azuredatastudio#10187] opened 2020-04-28 13:29 UTC
Issue Type: <b>Bug</b>

cancel not working for any query ! it keeps on going

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by subbaraonv** [comment] 2020-04-28 13:35
> Query was canceled by user
> Total execution time: 00:15:59.245 
Duplicate of #8407

**Comment by kburtram** [comment] 2020-05-07 19:55
@subbaraonv thanks for reporting this bug.  I'll close it as a duplicate of #8407.  Please add any additional related comments to that issue.

**Closed by kburtram** 2020-05-07 19:55 UTC
Labels: Area - Query Editor, Bug, Triage: Needed
