### ISSUE TITLE
Include session id in the query tab header

### ISSUE THREAD

**Issue by mikedavem** [Microsoft/azuredatastudio#910] opened 2018-03-15 14:27 UTC
**SQL Operations Studio Version:** 
0.26.7

**Steps to Reproduce:** 
Just open a new Query Windows (ctrl+N). It could be good to display the SPID of the opened session in the query tab header (as SSMS). It helps to identify quickly your session to exlude it from a trace definition clause for instance. 

Regards

**Comment by kburtram** [comment] 2019-04-23 22:37
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/229.  Please add any related comments on that issue.

**Closed by kburtram** 2019-04-23 22:37 UTC
Labels: Area: Query Editor, Enhancement
