### ISSUE TITLE
Open recent menu shows full path making it impossible to identify files

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/azuredatastudio#591] opened 2018-01-31 15:56 UTC
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Create a couple of SQL files in a nested path over 100 chars long
2. Open each file so they appear in the Open Recent menu
3. Now try to figure out which entry goes with which file since only the first set of chars is shown

At a minimum the filename (or a subset thereof) should be shown so you have a chance at determining which file to open. Ideally a tooltip should show the full path in all cases. Right now there appears to be no tooltip.

**Comment by kburtram** [comment] 2019-07-17 22:49
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/330.  Thanks reporting!

**Closed by kburtram** 2019-07-17 22:49 UTC
Labels: Enhancement, Upstream
