### ISSUE TITLE
Unsaved tabs don't get recovered

### ISSUE THREAD

**Issue by jgodman** [microsoft/azuredatastudio#4964] opened 2019-04-10 08:43 UTC
Issue Type: <b>Bug</b>

Open a new tab and close the app unexpectedly (like when the PC goes off without shutting down or using Task manager for simulation). Open the app again. You would realise that some of the tabs would open but empty - without the contents in them.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.94GB (7.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by kburtram** [comment] 2019-06-12 17:30
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/3304.  Please add any additional context to that issue.  Thanks for reporting!

**Closed by kburtram** 2019-06-12 17:30 UTC
Labels: Area: Shell, Bug
