### ISSUE TITLE
Run button in Edit Data mode often doesn't work

### ISSUE THREAD

**Issue by Ben-CA** [microsoft/azuredatastudio#24733] opened 2023-10-19 21:34 UTC
Type: <b>Bug</b>

When I'm editing a table, and update the SQL query (to apply a filter for which rows to display), when I press "Run", 70% of the time it does nothing. (can wait 10+ seconds - nothing) I need to press it several times sometimes, and then finally it greys out and runs. Happens on older versions as well as the latest Insider version.

![image](https://github.com/microsoft/azuredatastudio/assets/47060874/4f4a0232-344a-4f1d-8db4-144fb800c59d)

Azure Data Studio version: azuredatastudio-insiders 1.47.0-insider (aee90f3fbc3c31972589f7c8ca3dbc5c07001e2c, 2023-10-19T06:08:46.451Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment] 2023-10-19 22:09
Duplicate of https://github.com/microsoft/azuredatastudio/issues/24367

**Closed by cheenamalhotra** 2023-10-19 22:09 UTC
Labels: Bug, Area - Edit Data, Triage: Done
