### ISSUE TITLE
createNewSession method of the ObjectExplorerProvider is called twice when a disconnected connection is clicked in OE

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#15922] opened 2021-06-26 00:31 UTC
I am working on a new objectExplorerProvider and noticed this behavior.

**Comment by alanrenmsft** [comment] 2021-06-26 00:34
if the provider is returning results instantly, the child nodes won't show up because of a race condition caused by this behavior

**Comment by lewis-sanchez** [comment] 2022-12-16 23:29
Duplicate of #21428

**Closed by lewis-sanchez** 2022-12-16 23:29 UTC
Labels: Bug, Area - Object Explorer, Pri: 2, Triage: Done, Size: L
