### ISSUE TITLE
Performance Issue: VSCode Extension: Microsoft Data Workspace for Azure Data Studio and VS Code

### ISSUE THREAD

**Issue by mansoor-omrani** [microsoft/azuredatastudio#22304] opened 2023-03-11 08:52 UTC
Type: <b>Bug</b>

The mssql-data:workspace  extension (Microsoft Data Workspace for Azure Data Studio and VS Code) consumes much CPU and causes the system reaching its knees.

Extension version: 0.4.0
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.74GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/sw2/source/repos/Projects/Tap.ERP.Front/tap --crash-reporter-id fbeeff25-07f5-4a8f-ba27-1b31c00a2db7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30677850
funwalk2cf:30682975

```

</details>

**Comment by kisantia** [comment] 2023-03-13 17:15
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/21978. A new version with a change to not * activate the extension will be released in the near future.

**Closed by kisantia** 2023-03-13 17:15 UTC
Labels: Bug, Triage: Done, Area - Data Workspace
