### ISSUE TITLE
Cannot select Azure subscription

### ISSUE THREAD

**Issue by jrmclennan** [microsoft/azuredatastudio#16495] opened 2021-07-30 14:25 UTC
Issue Type: <b>Bug</b>

After signing into Azure, authenticating successfully, then selecting a subscription,  I get the error message below.

[Extension Host] Account was stale. No tokens being fetched. - 
Error running command azure.resource.selectsubscriptions: Running the contributed command: 'azure.resource.selectsubscriptions' failed.. This is likely caused by the extension that contributes azure.resource.selectsubscriptions.
onDidChangeNotification @ workbench.desktop.main.js:1614
(anonymous) @ workbench.desktop.main.js:1614
fire @ workbench.desktop.main.js:129
addNotification @ workbench.desktop.main.js:1614
error @ workbench.desktop.main.js:2735
(anonymous) @ workbench.desktop.main.js:2892
fire @ workbench.desktop.main.js:129
run @ workbench.desktop.main.js:293
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
run @ workbench.desktop.main.js:293
onClick @ workbench.desktop.main.js:344
(anonymous) @ workbench.desktop.main.js:445
ZoneDelegate.invokeTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:421
Zone.runTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:188
ZoneTask.invokeTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:496
ZoneTask.invoke @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:485
timer @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:2054
setTimeout (async)
scheduleTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:2075
ZoneDelegate.scheduleTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:407
Zone.scheduleTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:232
Zone.scheduleMacroTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:255
scheduleMacroTaskWithCurrentZone @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1114
(anonymous) @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:2090
proto.<computed> @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1394
(anonymous) @ workbench.desktop.main.js:445
ZoneDelegate.invokeTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:421
Zone.runTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:188
ZoneTask.invokeTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:496
invokeTask @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1540
globalZoneAwareCallback @ C:\Users\jorussel\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1577

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment] 2021-07-30 18:38
@jrmclennan I haven't seen this particular error reported before.  Have you tried removing the account in the Account Management dialog and reauthenticating?

**Comment by jrmclennan** [comment] 2021-07-30 22:53
@kburtram, thank you for the reply. Yes, I have removed the account and added it back successfully. Then, errors after I attempt to select a subscription.

**Comment by cheenamalhotra** [comment] 2023-05-12 23:05
Closing as the issue is now resolved.

**Closed by cheenamalhotra** 2023-05-12 23:05 UTC
Labels: Bug, Area - Azure
