### ISSUE TITLE
Database Project do we need a project tree view

### ISSUE THREAD

**Issue by simonsabin** [microsoft/azuredatastudio#11349] opened 2020-07-15 00:16 UTC
This is really a discussion item about the approach to have a different project view for database projects. 

I don't really see the value as the project tree isn't a logical entity model, but just the same files that are in the files view and thus confusing. 

It feels like a confusing approach and one based on old VS approach to files and solutions.

**Comment by kisantia** [comment] 2020-12-11 23:17
Hi @simonsabin, in the December release, we moved Projects into its own viewlet. Does it still seem confusing to have the project tree even now that it's separate from the files view? 
![image](https://user-images.githubusercontent.com/31145923/101963601-f0d3b580-3bc3-11eb-980e-3bd8c758bd9d.png)

**Comment by simonsabin** [comment] 2020-12-11 23:22
I still question the value as it’s still just the files, except a thing for database references. It’s not the vs code way is it. 
If it was the logical object model fine but why value does this give over the files view

**Comment by udeeshagautam** [comment] 2022-04-22 18:32
This is by design as of now, hence closing.

**Closed by udeeshagautam** 2022-04-22 18:32 UTC
Labels: Enhancement, Triage: Done, Area - SQL Project
