### ISSUE TITLE
Bar at top of editor pane disappears if (kql) query is saved

### ISSUE THREAD

**Issue by IcyCooldrink** [microsoft/azuredatastudio#20834] opened 2022-10-13 07:38 UTC
Issue Type: <b>Bug</b>

I'll say up-front that this might just be a setting that I inadvertently changed and don't know how to change back.  Not that I move away from defaults usually, but it's not impossible I did a random command shortcut.

This relates to kql queries with the kusto(KQL) extension installed.

Actual behaviour
1. Right-click an open Kusto connection and click 'New Query'
2. Write a simple working query, click 'Run' from the tool bar at the top of the editor.
3. Look at results.
4. Click 'File' > 'Save' and save the file
5. The toolbar with 'Run', 'Cancel', etc at the top of the editor pane disappears.

Actual behaviour - Alt
1. 'File' > 'Open File' and select a .kql file
2. Editor panel opens with all file content, but without the toolbar with 'Run' 

Expected behaviour
The saved file should appear and behave the same as it does before the query is saved.

Extension version: 0.5.4
Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (20.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alanrenmsft** [comment] 2022-10-26 18:52
@IcyCooldrink I am able to reproduce the issue with 1.39.1 but not with the latest insider build, I will investigate it further.

in the meanwhile, I was able to open it with the query editor action bar after closing the other editors. you can use this as a workaround for now.

**Comment by alanrenmsft** [comment] 2022-10-26 21:42
I just produced a stable build with latest code and I am not able to reproduce the issue with it anymore, it has been fixed.

**Closed by alanrenmsft** 2022-10-26 21:42 UTC
Labels: Bug, Area - Query Editor, Triage: Done
