### ISSUE TITLE
Feature Request: Filter in "object explorer"

### ISSUE THREAD

**Issue by sroyvs** [microsoft/azuredatastudio#69] opened 2017-11-16 13:55 UTC
Like in SSMS have the ability to apply a filter/search in the object explorer, to find tables/SPs or functions

**Comment by luiznovaesneto** [comment] 2017-11-17 18:11
Unfortunately doesn't have the filter feature in the object explorer yet. However, you can display the explorer-widget and use it to search the objects. It is really usefull because allow you to search many kinds of objects like tables, views and Stored Procedures.

![image](https://user-images.githubusercontent.com/19173194/32962016-f54e58a2-cbb1-11e7-9575-c15b59c841ae.png)

**Comment by jakodev** [comment] 2018-03-15 16:03
It is one of my favorite features in ssms, I will really appreciate it

**Comment by sgf** [comment] 2018-09-06 06:13
Filter Table Name,Colume Name,Procedure Name....
its very important function

**Comment by qwefgh90** [comment] 2018-09-10 08:48
Filter or other features which provide same usability like SSMS would be necessary.

**Comment by pietie** [comment] 2018-09-19 06:34
Please consider making this an inline filter. So just a simple input box at the top of Object Explorer that I can type stuff into. I have always found the dialog in SSMS a pain to work with. Especially if you need to do a bunch of quick searches one after the other. 

And it should be smart. So if I type **dbo.MySproc** it knows to break it up into schema and routine name. You can go even further and allow expressions (think Wireshark) .. e.g. **schema != 'dbo' AND name like '%abc%' AND type='proc'** to filter on all sprocs that have a name containing 'abc' that are not in the dbo schema.

**Comment by wsmelton** [comment] 2019-03-22 18:15
This ability has been in VS Code Insiders for some time but it is for file view, not sure how you could port it over to the server explorer window....

https://twitter.com/wsmelton/status/1090017132757295106

**Comment by KamasamaK** [comment] 2019-04-06 01:47
@wsmelton This was deployed to stable in VS Code 1.31 and is actually part of the new tree widget which is not exclusive to the workspace file view. For example, the Outline and Breadcrumbs trees are also using the new widget and it should be usable for any existing tree.

**Comment by wsmelton** [comment] 2019-04-06 02:33
The server explorer doesn't support filtering object list by typing like the file list does.

**Comment by KamasamaK** [comment] 2019-04-06 03:09
@wsmelton Yes, that is clear. I was making a clarification that the feature you mentioned is not exclusive to Insiders and is not specific to the workspace file view, but is a new tree widget that should be able to be used for an existing tree like the Servers view and is already merged from the vscode `master`.

**Comment by KamasamaK** [comment] 2019-08-08 20:43
Starting with VS Code v1.37, all trees have the highlight and filter capability.

**Comment by bbeda** [comment] 2019-11-28 08:11
I would definetely want this feature as well. I am sometimes going to SSMS just because I want to have better filtering. 
Also, maybe I am missing something here but is there a way to resize the Search pane? Most of the time our names are longer than the pane and what I am searching for has multiple matches. I have to hover over each one of those to select what I am looking for.
Thank you

**Comment by Charles-Gagnon** [comment] 2020-07-22 23:01
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as cleanup

**Closed by Charles-Gagnon** 2020-07-22 23:01 UTC
Labels: Area - Data Explorer, Enhancement
