### ISSUE TITLE
Issues adding/linking my account to ADS

### ISSUE THREAD

**Issue by pragna-pasunuri** [microsoft/azuredatastudio#13969] opened 2021-01-15 01:15 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. I have ADS 1.25.1 installed
2. I tried to add my Microsoft account and I saw an error saying 'You have no clouds enabled' even though I have public cloud selected
![image](https://user-images.githubusercontent.com/77471135/104667879-e9ed0680-568b-11eb-8860-5906aebb2ab7.png)

3. Also, I am having trouble with Simplified PR's loading up, I am unable to see the 'Create pull request option' at the bottom of the page next to my branch

**Comment by MsSQLGirl** [comment] 2021-01-15 04:14
@pragna-pasunuri - can you please try removing KQL extension and restart ADS?

**Comment by Charles-Gagnon** [comment] 2021-01-15 18:10
@MsSQLGirl Do you think this has something to do with the Kusto extension? The issue described has nothing to do with that extension specifically.

It seems to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/11260 so I'm closing this one for now - let me know if there's any reason we should keep this one separate.

**Comment by MsSQLGirl** [comment] 2021-01-15 18:25
I'll follow up with @pragna-pasunuri later today and confirm. We'll reopen if the issue persists after reinstalling KQL extension. 

My assumption is that there are some background services that didn't finish running caused issues with logins.

**Comment by MsSQLGirl** [comment] 2021-01-15 21:31
@Charles-Gagnon 

We tried removing KQL extension but it didn't seem to solve the problem. 
When we start ADS, even the Azure viewlet shows "Loading..." and never finishes. 
![image](https://user-images.githubusercontent.com/6405919/104780578-e3b36480-5735-11eb-8a81-356501cec765.png)

The issue still persists.

**Comment by Charles-Gagnon** [comment] 2021-01-15 21:53
@pragna-pasunuri 

Could you please run this from the command line and paste the output here? 

`azuredatastudio --list-extensions`

**Comment by pragna-pasunuri** [comment] 2021-01-15 22:01
Here are the extensions i have

adslivesite.azure-devops-simplified-prs
ban.spellright
Microsoft.adslivesite
Microsoft.kusto
ms-vscode.powershell
nick-rudenko.back-n-forth

**Comment by MsSQLGirl** [comment] 2021-01-17 21:16
+ @rajeshka : FYI. Can we please triage this with the team?

**Comment by dhgrajeda** [comment] 2021-01-21 06:27
@pragna-pasunuri 

Does the error occur if you wait for a while? Could you try waiting a minute before attempting to log in?

If you continue to experience this issue, would you mind attaching the following logs?

**Console Logs**

Open Developer Tools (Help -> Toggle Developer Tools)
Click the Console tab
Click in the log area and select all text (CTRL+A)
Save this text into a file named console.log and attach it to this issue.

**Application Logs**

Open command palette (Click View -> Command Palette)
Run the command: Developer: Open Logs Folder
This will open the log folder locally. Please zip up this folder and attach it to the issue.

**Comment by MsSQLGirl** [comment] 2021-01-24 18:37
Removing Pri 1. It's tracked internally as part of Livesite work.

**Comment by Saancreed** [comment] 2021-01-29 14:36
I'm facing the same issue on my machine, complete with Azure viewlet staying at `Loading …`. Disabling all external extensions and waiting for up to 10 minutes does not help. Fwiw, system keychain integration is disabled.

My extensions:
```
$ azuredatastudio --list-extensions
Microsoft.admin-pack
Microsoft.agent
Microsoft.azuredatastudio-postgresql
Microsoft.dacpac
Microsoft.import
Microsoft.profiler
Microsoft.schema-compare
```

Some info from About dialog:
```
Version: 1.25.2
Commit: 4d4917d328ab7a7526817a0f0ef03237a79aa54d
Date: 2021-01-20T22:45:05.496Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.11-zen2-1-zen
```

Logs (`console.log` is included in the zip file): [20210129T151946.zip](https://github.com/microsoft/azuredatastudio/files/5894367/20210129T151946.zip)

**Comment by joberume** [comment] 2021-01-29 19:31
@MsSQLGirl , can we get this triaged again? It seems to be a broader issue

**Comment by MsSQLGirl** [comment] 2021-02-01 18:07
@Charles-Gagnon - As per Jorge mentioend above, seems to be a broader issue also. Saancreed can repro this above (not related to Livesite work). 
 https://github.com/microsoft/azuredatastudio/issues/13969#issuecomment-769841976 

Can you please help? Thanks!

**Comment by Charles-Gagnon** [comment] 2021-02-01 18:14
If this is a broader issue then we should close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/11260 I would think.

But I'll leave that up to @cssuh @kburtram as the owners of the Connection/Azure areas

**Comment by Saancreed** [comment] 2021-02-02 09:06
Good news: I can't reproduce this issue on Insiders build, so I guess whatever the cause was, 1.26 will have fixed it.

**Comment by jpsebasti** [comment] 2021-02-11 14:11
When will 1.26 be available.  All my databases are in Azure and right now, this software is useless to me until I can connect.

**Comment by glittle** [comment] 2021-02-21 03:01
I have a new install of Data Studio.  I was able to connect to my Azure account. I later removed the account.  Now, when I try to connect, I get "You have no clouds enabled."

I had, then uninstalled, the "SQL Server Profiler" extension. I've restarted the app a number of times. The "public cloud" is enabled.

The "Loading..." message does not go away:
![image](https://user-images.githubusercontent.com/85186/108614182-c9644a80-73b5-11eb-97f6-9b6ee4947d44.png)

This may help, from the DevTools console:

    Initializing stored accounts

    at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:694:94

![image](https://user-images.githubusercontent.com/85186/108614237-31b32c00-73b6-11eb-9105-40fba9d90c97.png)

**Comment by glittle** [comment] 2021-02-21 03:11
I deleted the folder at C:\Users\[My User Account]\AppData\Roaming\azuredatastudio

After that, Data Studio started up fresh and I was able to add my account and keep going.

**Comment by glittle** [comment] 2021-02-21 03:12
> When will 1.26 be available. All my databases are in Azure and right now, this software is useless to me until I can connect.

@jpsebasti Try resetting as I did.

**Comment by jpsebasti** [comment] 2021-02-21 15:11
Thank you glittle. I'm on a Mac so I'll have to see if I can figure out where equivalent (if one exists) folder is.

**Comment by kburtram** [comment] 2021-02-21 18:15
@jpsebasti I'm not on my mac now to get the exact path, but it's under something like ~/Library/Application Support/azuredatastudio.  Please let us know if deleting this directory helps resolve the issue.  The 1.26 release is planned for tomorrow morning (to answer a previous questions).

This issue was tracking a specific issue we saw when various extensions were enabled.  Since it's now discussing general AAD issues I'll close as a duplicate of a similar issue we've already been tracking.  Please add any additional related comments there.  Thanks!  https://github.com/microsoft/azuredatastudio/issues/11260

**Closed by kburtram** 2021-02-21 18:15 UTC
Labels: Area - Azure, Area - Live site, Impact: Live site
