### ISSUE TITLE
Selection undone when filling out Find/Replace

### ISSUE THREAD

**Issue by jimkilliansentinel** [microsoft/azuredatastudio#21666] opened 2023-01-19 22:30 UTC
**Is your feature request related to a problem? Please describe.**
If I want to search/replace text within a selection, I select the text, press Ctrl-F or Ctrl-H (first screenshot). If I start typing in the find box _before_ I click on the "Find in Selection" button (or Alt-L),  the selection is undone (second screenshot), and if I click on the "Find in Selection" button (or Alt-L), it just highlights the first instance found (third screenshot).

**Describe the solution or feature you'd like**
The text I have selected in the document _should not_ be deselected if I don't click on the "Find in Selection" button (or Alt-L) before typing in the text boxes. Ideally, if text is already selected when the dialog is opened, the "Find in Selection" button should default to enabled; this is how SSMS works (fourth screenshot). If I want it to be document-wide, I can turn it off.

Also, displaying the count of changes made afterward would be good (this is for all Find/Replace, not just for selection). SSMS does this (fifth screenshot), though a new popup isn't needed (just some text in the dialog would be enough).

**Describe alternatives you've considered**
I don't know of an alternative other than remembering to change the selection option before typing (***so hard!***).

**Additional context**
![SearchReplace_1](https://user-images.githubusercontent.com/85969574/213573594-70eba45d-750c-4457-9a15-fab6dfb1e854.png)
![image](https://user-images.githubusercontent.com/85969574/213573774-94b7da75-f975-4502-bfb4-5d82d36ca8d0.png)
![image](https://user-images.githubusercontent.com/85969574/213574026-314dacd8-87c6-4fb4-897e-23c5c7697416.png)
![image](https://user-images.githubusercontent.com/85969574/213575875-f7297e3e-c4e1-42a1-891a-9b6eeed84d4c.png)
![image](https://user-images.githubusercontent.com/85969574/213590297-b77c42ba-a12b-422a-883a-aaec86165d8c.png)

**Comment by cheenamalhotra** [comment] 2023-10-25 20:32
Hi @jimkilliansentinel 

I cannot reproduce this issue in the latest insiders build, and below is the behavior observed as expected:

![selection find](https://github.com/microsoft/azuredatastudio/assets/13396919/e94e1162-9bf4-4532-a84c-3f401d13c1a6)

I will close the issue as resolved, please feel free to reopen the issue and provide repro details if you continue to experience problems.

**Closed** 2023-10-25 20:32 UTC
Labels: Bug, Area - Query Editor, Triage: Done

**Comment by jimkilliansentinel** [comment] 2023-10-30 16:51
Hi @cheenamalhotra -

In your video, you're not following my description. Try this:

1. Select the text for doing the find/replace (this part is correct).
2. Press Ctrl-F or Ctrl-H.
3. Change the text to search for, which will undo your selection (this is what you did out of sequence).
4. Click on the button or Ctrl-L to work with the selection (now that your selection is undone, this doesn't work).
5. Try to make it work. It doesn't.

The problem is that when you open the find/replace window, you click the "selection" button before you change the text, so it works as expected. My contention is that changing the text you're searching for **shouldn't** undo your selection even if you haven't pressed the "selection" button or Ctrl-L yet. **If you're going to ignore the selection for the find/replace operation, what's the need to undo the selection if I don't click the button _first_?** Just leave the selection in-place and proceed with the operation in the usual way (either global or in the selection, depending on the "selection" button status when the action is applied).

**Comment by cheenamalhotra** [comment] 2023-10-30 17:45
Hi @jimkilliansentinel 

When Find/Replace is launched, irrespective of whether you have selected text, it doesn't limit your search into the selected content, unless you click the 'Selection' icon and that's why it starts searching in the whole file as soon as you start typing. If you want to retain your selection, you need to click on the 'Selection' icon or ALT+L to freeze your selection before you start typing.

This design comes from VS Code, which is upstream source. You may open an issue in [VS Code repository](https://github.com/microsoft/vscode) to raise your concern.

**Comment by jimkilliansentinel** [comment] 2023-10-30 20:30
Thanks! I'll raise it there. Especially since VS detects if you have a selection made when you open the find/replace and automatically selects "selection" mode. I think that's the right way to do it.
