### ISSUE TITLE
Import Wizard: Refresh when at Bottom of Results for Preview Data Shows Empty Grid

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5070] opened 2019-04-17 01:59 UTC
Go through the import wizard (choose a file, etc). On the Preview Data page, wait for data to be displayed.

Scroll to the bottom of the grid.

Click refresh.

Grid will appear empty until you scroll back up:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/40371649/56255398-921a0980-6079-11e9-8684-7d6d10208d0f.png">

**Comment by alanrenmsft** [comment] 2019-04-17 17:53
@yualan not a regression, and also not a block issue, please triage.

**Comment by aasimkhan30** [comment] 2020-09-21 21:17
Cannot reproduce this error. Closing the issue for now.

**Closed by aasimkhan30** 2020-09-21 21:17 UTC
Labels: Area - SQL Import, Bug
