### ISSUE TITLE
Can not connect to Python Kernel from Jupyter notebook.

### ISSUE THREAD

**Issue by gcapnias** [microsoft/azuredatastudio#24106] opened 2023-08-09 09:16 UTC
Type: <b>Bug</b>

I have a new Azure Data Studio installation (per machine installation) v1.45.1.

I open an empty folder and I create a Jupyter notebook. I select Python3 from Kernel dropdown. Azure Data Studio prompts to create a new Python installation. I accept the default settings and an installation starts. 

In Output window, in Notebooks I see that the installation of Jupiter Notebooks completed successfully. I receive a popup that installation was completed successfully. 
In the Output window, I can see that Azure Data Studio issues a command to start Jupyter Notebook. I receive an error:

```
Failed to change kernel. Kernel SQL will be used. Error was:
Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last): File "c:\Program Files\Azure Data Studio\resources\pythonScripts\startNotebook.py", line 1, in <module> import notebook.notebookapp'.
```

I issued the same command - from output window - in command prompt and I get the error:

```
C:\Users\gcapnias>"C:\Users\gcapnias\azuredatastudio-python\python.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --ip=127.0.0.1  --no-mathjax --notebook-dir "c:\Repository" --NotebookApp.token=9fa5a3bdf01d6d103b1746070804c8fcbb29fd4018fabd79
Traceback (most recent call last):
  File "c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py", line 1, in <module>
    import notebook.notebookapp
ModuleNotFoundError: No module named 'notebook.notebookapp'
```

I have issued the command 

```
C:\> "C:\Users\gcapnias>"C:\Users\gcapnias\azuredatastudio-python\python.exe" -m pip install jupyter
```

and I verified the installation of Jupyter Notebook

I can start Jupiter Notebook from command-line with the command:

```
C:\> "C:\Users\gcapnias\azuredatastudio-python\python.exe" -m notebook
```

How can I fix my installation in order to work Jupyter Notebooks with Azure Data Studio?

Thanks in advance,
George J.

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (2 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|4.00GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.5.0

</details>

**Comment by duanepfeiffer** [comment] 2023-08-10 22:09
I'm having the same issue.

**Comment by lucyzhang929** [comment] 2023-09-08 19:03
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/23945.
Please try downgrading the notebook package to v6.5.5 as a workaround.
```
pip3 install notebook==6.5.5
```

**Closed by lucyzhang929** 2023-09-08 19:03 UTC
Labels: Bug, Area - Notebooks, Triage: Needed
