### ISSUE TITLE
ADS doesn't find python libaries correctly when running Pyspark kernel on cluster

### ISSUE THREAD

**Issue by sfweller** [microsoft/azuredatastudio#6237] opened 2019-07-01 19:45 UTC
- Azure Data Studio Version:
  1.8.0
  Commit:  96e214593190071f0b520439929b218f9fa673de
  VS Code:  1.34.0
  Electron:  3.1.8
  Chrome:  66.0.3359.181
  Node.js:  10.2.0
  V8: 6.6.346.32
  OS:  Windows NT x64 10.00.18362

Steps to Reproduce:

1.  Install the 'bokeh' module using 'python -m pip install bokeh' both on the local machine running ADS and on a aris cluster you are connected to.

2.  Open a new notebook and select 'Pyspark3' as the kernel and connect to an aris cluster.

3. At the beginning of the notebook add the line 'import bokeh'.

4.  Attempt to run the notebook, you will get the following error message:
    
    No module named 'bokeh'
   ImportError: No module named 'bokeh'

5).  If you change the kernel to 'Python3', things will run successfully.

**Comment by kevcunnane** [comment] 2019-07-02 18:20
I'm closing this as by design. Pip is for local package management. Remote package management isn't supported in the cluster yet. Once that's done, we can start adding support for it in the UI but until then it's not supported. Thanks!

**Closed by kevcunnane** 2019-07-02 18:20 UTC
Labels: Area: Notebooks, Bug, Triage: Done
