### ISSUE TITLE
Unexpected

### ISSUE THREAD

**Issue by xaxdev** [microsoft/azuredatastudio#7215] opened 2019-09-16 03:48 UTC
Issue Type: <b>Feature Request</b>

Error

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Charles-Gagnon** [comment] 2019-09-16 05:32
I'm going to close this since it's not clear what the issue is - please reopen with more details on what problem you're running in to if there's an issue!

**Closed by Charles-Gagnon** 2019-09-16 05:32 UTC
