### ISSUE TITLE
Cannot download an older release.

### ISSUE THREAD

**Issue by KroneCorylus** [microsoft/azuredatastudio#22102] opened 2023-03-02 15:59 UTC
Steps to Reproduce:

1. [Go to releases page](https://github.com/microsoft/azuredatastudio/releases)
2. Try to download 1.41.1 or any older version

The link for all versions download the latest version.

**Comment by Charles-Gagnon** [comment] 2023-03-02 18:56
@KroneCorylus What versions are you seeing this for? The process we have is that links will always point to the latest for that major version - but each major version should have its own links. So 1.41.0, 1.41.1 and 1.41.2 all point to the same downloads (the 1.41.2) release. But 1.40.* and older major versions should each have their own.

We do this because we don't want people to use older versions that have known issues, so when a hotfix is released we want the link for the major version that hotfix is for to always point to the latest hotfix release for that major version.

So closing this as "working as intended" - although if you're seeing links that don't follow the above rules we have let us know, it's possible that some of the links on those pages are wrong!

**Closed by Charles-Gagnon** 2023-03-02 18:56 UTC
Labels: Bug, Triage: Needed

**Comment by KroneCorylus** [comment] 2023-03-02 20:16
Thank you for the excellent answer and sorry if I wasted your time.  I didn't know that it worked like that and indeed I was trying to download a version within the same major release (1.41.1 but getting 1.41.2).  Thanks again.
