### ISSUE TITLE
COMMAND LINE INTERFACE

### ISSUE THREAD

**Issue by robertvdmeijden** [microsoft/azuredatastudio#146] opened 2017-11-19 14:51 UTC
I would really appreciate a command line interface for SQLOPS.EXE I.e:
ssms.exe -nosplash -S ServerName -D DBName -E

All command line options as per ssms.exe 

Thanks in advance.

**Comment by qJake** [comment] 2018-08-21 04:03
+1 This is huge, and an absolute necessity for organizations using a password vault such as [Remote Desktop Manager](https://remotedesktopmanager.com/). Being able to pass in the data source, initial catalog, username, and password (or integrated mode switch) so that the application launches and automatically connects to the target server is critical for a lot of folks.

For reference, [here is the Ssms.exe command line argument list](https://docs.microsoft.com/en-us/sql/ssms/ssms-utility?view=sql-server-2017#arguments).

**Comment by kburtram** [comment] 2019-06-06 19:43
@shueybubbles do you know if the command-line arguments you add for SSMS Integration meet the requirements in this issue?  If so, could you please close this out.

**Comment by shueybubbles** [comment] 2019-06-06 19:52
we don't  allow password on the command line . Ssms puts it in credential manager before running ADS. Should we consider adding it, or at least reading it from standard input?

**Closed** 2019-06-09 08:47 UTC
Labels: Enhancement

**Comment by qJake** [comment] 2019-06-09 20:29
Hey, what was the resolution on this? Does `sqlops.exe` support command-line arguments now? Is there any documentation for it? (Google didn't turn up anything.) @kburtram Can you provide a status update and/or reopen if this is not yet released?

Also, #2039 exists and may be a duplicate and/or related to this?

**Comment by shueybubbles** [comment] 2019-06-11 14:28
azuredatastudio.exe/.cmd now supports similar command line parameters as ssms/sqlcmd, with the omission of passwords. 
#3059 is an issue tracking adding documentation of the switches.
#2039 is a duplicate of this one, pretty much. It's a bug that --help doesn't print anything useful. We inherit some of the same parameters as VS Code, like -r/--reuse-window
`azuredatastudio -S serverName -D databasename`
will open a new query editor window against the given database/server combination using Windows auth. To use sql auth, pass `-U username` 
If you have previously saved the connection and password in settings, ADS won't prompt you for the password.
