### ISSUE TITLE
Default plan should be Basic and not Standard

### ISSUE THREAD

**Issue by mdmoura** [microsoft/azuredatastudio#7442] opened 2019-10-01 16:35 UTC
When creating a database using the Data-Tier application wizard the new database gets the Standard General Purpose plan ... 

I think it should be the Basic plan or at least give the option to choose the plan.

A few times I ended up with extra costs with staging databases just because I forgot to go to Azure portal and change the plane from Standard to Basic.

**Comment by kisantia** [comment] 2022-12-06 22:04
closing as duplicate of #10301

**Closed by kisantia** 2022-12-06 22:04 UTC
Labels: Area - Azure, Area - DacFX, Enhancement, Pri: 3, Size: M
