### ISSUE TITLE
Installing R packages using ADS 1.29.0 & Machine Learning addin v0.9.0 - consistently fails

### ISSUE THREAD

**Issue by Stevew7777** [microsoft/azuredatastudio#15774] opened 2021-06-17 11:08 UTC
I can install Python packages to SQL 2019 MLS using ADS v1.29.0 with Machine Learning addin v0.9.0 with no issues. 

ADS Version: 1.29.0 (system setup)
Commit: 0f5cfdc2c8c2433028842e16dc5ac1a65da24292
Date: 2021-05-15T01:12:11.112Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.14393

But I cant install R packages, and any R package I try to install results in this error below :

----------------------------------------------------------------------------------
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> formals(quit)$save <- formals(q)$save <- "no"
> library(sqlmlutils)
> connection <- connectionInfo(driver=ODBC Driver 17 for SQL Server, database="master", server="SERVER01")
Error: unexpected symbol in "connection <- connectionInfo(driver=ODBC Driver"
Execution halted
---------------------------------------------------------------------------------------

It seems to me that ADS is creating malformed R code that is missing quotes , I think the ADS generated code should look like this :

> connection <- connectionInfo(driver="ODBC Driver 17 for SQL Server", database="master", server="SERVER01")

I have followed the instructions here carefully:
https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/machine-learning-extension?view=sql-server-ver15
and
https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/machine-learning-extension-manage-packages?view=sql-server-ver15
with no joy.

Can someone have a look please. Thanks.

**Comment by llali** [comment] 2021-07-06 20:46
this bug seems to be duplicate of https://github.com/microsoft/azuredatastudio/issues/15802

**Closed by llali** 2021-07-06 20:46 UTC
Labels: Area - Machine Learning, Bug, Triage: Needed
