### ISSUE TITLE
Please remove the "Selected data has been copied to the clipboard" notification.

### ISSUE THREAD

**Issue by bbuchanan** [microsoft/azuredatastudio#24128] opened 2023-08-14 17:27 UTC
Type: <b>Feature Request</b>

This new "feature" is extremely annoying. The fact that I have to click _Close_ on every one of these is a huge interruption to my workflow and they get in the way as they stack on top of each other.

At the bare minimum can you please make them auto dismiss after a few seconds?

Thank you.

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:36.656Z)
OS version: Darwin x64 22.5.0
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by cheenamalhotra** [comment] 2023-08-14 18:29
Duplicate of #24009

**Comment by smartguest** [comment] 2023-08-14 21:26
Closing as duplicate

**Closed by smartguest** 2023-08-14 21:26 UTC
Labels: Area - Query Editor
