### ISSUE TITLE
"TCP Provider, error: 35 - An internal exception was caught" when connecting to Managed Instances

### ISSUE THREAD

**Issue by sqlatspeed** [microsoft/azuredatastudio#20192] opened 2022-07-28 14:42 UTC
- Azure Data Studio Version: 1.37.0
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Open ADS
2. Log into VPN
3. Connect to any managed instance in our production subscription 
4. "TCP Provider, error: 35 - An internal exception was caught" displays after 60 seconds

Does this issue occur when all extensions are disabled?: Yes
![Screen Shot 2022-07-28 at 8 22 36 AM](https://user-images.githubusercontent.com/43384529/181562609-dd0d7688-56fb-423a-8fb0-760f4cfcc6a0.png)

**Comment by cheenamalhotra** [comment] 2022-08-05 00:20
Hi @sqlatspeed 

Could you please confirm you're able to connect to the target SQL Managed Instance from a Windows OS using SSMS/ADS, just to ensure connectivity is established? As SQL Managed Instances require clients to be in the same virtual network.

**Comment by sqlatspeed** [comment] 2022-08-07 02:20
Cheena,
I am fully able to connect to this managed instance (it is one of our production MIs) via SSMS from Windows PCs. Let me know what other information you need. Thanks for the help!
Matt Gordon
    On Thursday, August 4, 2022 at 07:20:53 PM CDT, Cheena Malhotra ***@***.***> wrote:  
 
 


Hi @sqlatspeed

Could you please confirm you're able to connect to the target SQL Managed Instance from a Windows OS using SSMS/ADS, just to ensure connectivity is established? As SQL Managed Instances require clients to be in the same virtual network.

**Comment by cheenamalhotra** [comment] 2022-08-15 20:15
The error you mentioned is thrown by the underlying driver when the hostname does not resolve to an IP address. Here is complete error information:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. 
The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. 
(provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known 
    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch) 
    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
```

You may want to check if DNS resolves to an IP address for this hostname in this environment.
Are you able to do a quick `nslookup` to confirm and modify /etc/hosts if needed?

**Comment by sqlatspeed** [comment] 2022-08-16 18:17
Cheena,
Thanks for the response. What's odd about this is that it doesn't happen to every user in our environment. Some ADS users seem to be able to connect to the managed instances just fine. DNS does resolve to a hostname for these MIs so that doesn't seem to be the issue here. How would it be inconsistent across users when they are all on our same network? Is it because of the nature of MIs themselves somehow?
Matt Gordon
    On Monday, August 15, 2022 at 04:16:04 PM EDT, Cheena Malhotra ***@***.***> wrote:  
 
 


The error you mentioned is thrown by the underlying driver when the hostname does not resolve to an IP address. Here is complete error information:
Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. 
The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. 
(provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known 
    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch) 
    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)

You may want to check if DNS resolves to an IP address for this hostname in this environment.
Are you able to do a quick nslookup to confirm and modify /etc/hosts if needed?

**Comment by cheenamalhotra** [comment] 2022-08-24 05:08
> Is it because of the nature of MIs themselves somehow?

It should not be that way, it is strange why some machines cannot access the managed instance. The problem is generally due to lack of connectivity, but let's do some troubleshooting.

Can you try to connect to the same instance from your client using [mssql-cli](https://github.com/dbcli/mssql-cli/blob/main/doc/installation/macos.md) and SqlClient driver if you use it directly? Let me know if you need any help creating a Dotnet console app to test the same. You would need to initialize and open an instance of [SqlConnection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.connectionstring?view=sqlclient-dotnet-standard-5.0&viewFallbackFrom=dotnet-plat-ext-6.0) with connection string.

Let's try to validate if this is ADS specific issue (may hint us to Access token retrieval issue) or else we'll know if it also occurs with other client drivers.

**Comment by sqlatspeed** [comment] 2022-08-24 11:58
Cheena,
While we are seeing these errors from both Macs and Windows machines, the majority of the errors are on Macs. I would definitely need help creating that app as my .NET skills are fairly rusty at this stage. Happy to test with whatever you send me, though. Thanks for your continued help on this!
Matt Gordon
    On Wednesday, August 24, 2022 at 01:08:35 AM EDT, Cheena Malhotra ***@***.***> wrote:  
 
 



Is it because of the nature of MIs themselves somehow?


It should not be that way, it is strange why some machines cannot access the managed instance. The problem is generally due to lack of connectivity, but let's do some troubleshooting.

Can you try to connect to the same instance from your client using mssql-cli and SqlClient driver if you use it directly? Let me know if you need any help creating a Dotnet console app to test the same. You would need to initialize and open an instance of SqlConnection with connection string.

Let's try to validate if this is ADS specific issue (may hint us to Access token retrieval issue) or else we'll know if it also occurs with other client drivers.

**Comment by cheenamalhotra** [comment] 2022-08-24 17:44
Could you try installing mssql-cli first: https://github.com/dbcli/mssql-cli/blob/main/doc/installation/macos.md

**Comment by sqlatspeed** [comment] 2022-08-25 16:34
Cheena,
Thanks - I had a few minutes between some extensive travel this week and gave it a whirl but my Mac did not like that install attempt. The error is below. I don't have time to dig into this afternoon since I'm getting on an airplane but any guidance you have here is much appreciated. I do appreciate the help very much. 
Matt Gordon

Searching for pip

Reading https://pypi.org/simple/pip/

Downloading https://files.pythonhosted.org/packages/4b/30/e15b806597e67057e07a5acdc135216ccbf76a5f1681a324533b61066b0b/pip-22.2.2.tar.gz#sha256=3fd1929db052f056d7a998439176d3333fa1b3f6c1ad881de1885c0717608a4b

Best match: pip 22.2.2

Processing pip-22.2.2.tar.gz

Writing /tmp/easy_install-9hgzSx/pip-22.2.2/setup.cfg

Running pip-22.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9hgzSx/pip-22.2.2/egg-dist-tmp-xxfS3t

Traceback (most recent call last):

  File "/usr/bin/easy_install", line 13, in <module>

    load_entry_point('setuptools==41.0.1', 'console_scripts', 'easy_install')()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 2316, in main

    **kw

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 145, in setup

    return distutils.core.setup(**attrs)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 418, in run

    self.easy_install(spec, not self.no_deps)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 679, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 705, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 890, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1158, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1144, in run_setup

    run_setup(setup_script, args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 253, in run_setup

    raise

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context

    yield

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 166, in save_modules

    saved_exc.resume()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 141, in resume

    six.reraise(type, exc, self._tb)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 154, in save_modules

    yield saved

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context

    yield

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 250, in run_setup

    _execfile(setup_script, ns)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 44, in _execfile

    code = compile(script, filename, 'exec')

  File "/tmp/easy_install-9hgzSx/pip-22.2.2/setup.py", line 7

    def read(rel_path: str) -> str:

                     ^

SyntaxError: invalid syntax


    On Wednesday, August 24, 2022 at 01:44:47 PM EDT, Cheena Malhotra ***@***.***> wrote:  
 
 


Could you try installing mssql-cli first: https://github.com/dbcli/mssql-cli/blob/main/doc/installation/macos.md

**Comment by cheenamalhotra** [comment] 2022-09-01 01:58
Hi Matt, please try installing latest version of Python as that might be related, and then you should be able to re-install pip.

**Comment by nandita-gupta** [comment] 2022-09-28 16:42
> Hi Matt, please try installing latest version of Python as that might be related, and then you should be able to re-install pip.

Hi Cheena, I am facing same TCP error 35 in mac os Monterey. I tried access mssql cli. but it does not work

nandita ~ % sudo pip install mssql-cli --ignore-installed six
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/Users/nanditagupta/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting mssql-cli
  Downloading mssql_cli-1.0.0-py2.py3-none-macosx_10_11_intel.whl (42.4 MB)
     |████████████████████████████████| 42.4 MB 348 kB/s 
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting configobj>=5.0.6
  Downloading configobj-5.0.6.tar.gz (33 kB)
Collecting applicationinsights>=0.11.1
  Downloading applicationinsights-0.11.10-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 23.1 MB/s 
Collecting prompt-toolkit<2.1.0,>=2.0.0
  Downloading prompt_toolkit-2.0.10-py2-none-any.whl (340 kB)
     |████████████████████████████████| 340 kB 14.6 MB/s 
Collecting Pygments>=2.0
  Downloading Pygments-2.5.2-py2.py3-none-any.whl (896 kB)
     |████████████████████████████████| 896 kB 6.3 MB/s 
Collecting enum34>=1.1.6
  Downloading enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting wheel>=0.29.0
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting future>=0.16.0
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 11.0 MB/s 
Collecting sqlparse<0.3.0,>=0.2.2
  Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
Collecting argparse>=1.2.1
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting cli-helpers<1.0.0,>=0.2.3
  Downloading cli_helpers-0.2.3-py2.py3-none-any.whl (26 kB)
Collecting click<7.1,>=4.1
  Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 16.6 MB/s 
Collecting humanize>=0.5.1
  Downloading humanize-1.0.0-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 1.7 MB/s 
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting terminaltables>=3.0.0
  Downloading terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
Collecting backports.csv>=1.0.0
  Downloading backports.csv-1.0.7-py2.py3-none-any.whl (12 kB)
Collecting backports.functools-lru-cache>=1.2.1; python_version < "3.2"
  Downloading backports.functools_lru_cache-1.6.4-py2.py3-none-any.whl (5.9 kB)
Building wheels for collected packages: configobj, future
  Building wheel for configobj (setup.py) ... done
  Created wheel for configobj: filename=configobj-5.0.6-py2-none-any.whl size=34544 sha256=4c534b258caec263bfbe593a4b967803cd34ca4cc60803fb58b12a93ccb38fff
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-2st82o/wheels/c1/12/7a/c676d85d30d1aa17f3882dab925a777ab1f651c4072cccefd7
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py2-none-any.whl size=502566 sha256=0d850f776dc19ace4754bb93a0b645e5d86a888115ec148ab2403c9ac39f954e
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-2st82o/wheels/5f/11/0c/aad680baf5ef4fbcbab992c9f03e1130357e0c173a4fdabfff
Successfully built configobj future
Installing collected packages: six, configobj, applicationinsights, backports.functools-lru-cache, wcwidth, prompt-toolkit, Pygments, enum34, wheel, future, sqlparse, argparse, terminaltables, backports.csv, cli-helpers, click, humanize, mssql-cli
  WARNING: The script pygmentize is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wheel is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts futurize and pasteurize are installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sqlformat is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Pygments-2.5.2 applicationinsights-0.11.10 argparse-1.4.0 backports.csv-1.0.7 backports.functools-lru-cache-1.6.4 cli-helpers-0.2.3 click-7.0 configobj-5.0.6 enum34-1.1.10 future-0.18.2 humanize-1.0.0 mssql-cli-1.0.0 prompt-toolkit-2.0.10 six-1.16.0 sqlparse-0.2.4 terminaltables-3.1.10 wcwidth-0.2.5 wheel-0.37.1
nandita ~ % mssql-cli -h
zsh: command not found: mssql-cli
nandita ~ %

**Comment by sqlatspeed** [comment] 2022-10-02 14:36
Cheena,
I'm still having the same issue even with the latest version of Python installed. I am about to cycle this Macbook work machine back in for a Windows machine however, so I won't be able to further test this issue. I'd like to bring a colleague into this issue (Joshua Higginbotham, fellow MVP) so he can continue working on it. What is the best way for me to do that?
Matt Gordon
    On Wednesday, September 28, 2022 at 12:43:00 PM EDT, nandita-gupta ***@***.***> wrote:  
 
 



Hi Matt, please try installing latest version of Python as that might be related, and then you should be able to re-install pip.


Hi Cheena, I am facing same TCP error 35 in mac os Monterey. I tried access mssql cli. but it does not work

nandita ~ % sudo pip install mssql-cli --ignore-installed six
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/Users/nanditagupta/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting mssql-cli
Downloading mssql_cli-1.0.0-py2.py3-none-macosx_10_11_intel.whl (42.4 MB)
|████████████████████████████████| 42.4 MB 348 kB/s
Collecting six
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting configobj>=5.0.6
Downloading configobj-5.0.6.tar.gz (33 kB)
Collecting applicationinsights>=0.11.1
Downloading applicationinsights-0.11.10-py2.py3-none-any.whl (55 kB)
|████████████████████████████████| 55 kB 23.1 MB/s
Collecting prompt-toolkit<2.1.0,>=2.0.0
Downloading prompt_toolkit-2.0.10-py2-none-any.whl (340 kB)
|████████████████████████████████| 340 kB 14.6 MB/s
Collecting Pygments>=2.0
Downloading Pygments-2.5.2-py2.py3-none-any.whl (896 kB)
|████████████████████████████████| 896 kB 6.3 MB/s
Collecting enum34>=1.1.6
Downloading enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting wheel>=0.29.0
Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting future>=0.16.0
Downloading future-0.18.2.tar.gz (829 kB)
|████████████████████████████████| 829 kB 11.0 MB/s
Collecting sqlparse<0.3.0,>=0.2.2
Downloading sqlparse-0.2.4-py2.py3-none-any.whl (38 kB)
Collecting argparse>=1.2.1
Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting cli-helpers<1.0.0,>=0.2.3
Downloading cli_helpers-0.2.3-py2.py3-none-any.whl (26 kB)
Collecting click<7.1,>=4.1
Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
|████████████████████████████████| 81 kB 16.6 MB/s
Collecting humanize>=0.5.1
Downloading humanize-1.0.0-py2.py3-none-any.whl (51 kB)
|████████████████████████████████| 51 kB 1.7 MB/s
Collecting wcwidth
Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting terminaltables>=3.0.0
Downloading terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
Collecting backports.csv>=1.0.0
Downloading backports.csv-1.0.7-py2.py3-none-any.whl (12 kB)
Collecting backports.functools-lru-cache>=1.2.1; python_version < "3.2"
Downloading backports.functools_lru_cache-1.6.4-py2.py3-none-any.whl (5.9 kB)
Building wheels for collected packages: configobj, future
Building wheel for configobj (setup.py) ... done
Created wheel for configobj: filename=configobj-5.0.6-py2-none-any.whl size=34544 sha256=4c534b258caec263bfbe593a4b967803cd34ca4cc60803fb58b12a93ccb38fff
Stored in directory: /private/tmp/pip-ephem-wheel-cache-2st82o/wheels/c1/12/7a/c676d85d30d1aa17f3882dab925a777ab1f651c4072cccefd7
Building wheel for future (setup.py) ... done
Created wheel for future: filename=future-0.18.2-py2-none-any.whl size=502566 sha256=0d850f776dc19ace4754bb93a0b645e5d86a888115ec148ab2403c9ac39f954e
Stored in directory: /private/tmp/pip-ephem-wheel-cache-2st82o/wheels/5f/11/0c/aad680baf5ef4fbcbab992c9f03e1130357e0c173a4fdabfff
Successfully built configobj future
Installing collected packages: six, configobj, applicationinsights, backports.functools-lru-cache, wcwidth, prompt-toolkit, Pygments, enum34, wheel, future, sqlparse, argparse, terminaltables, backports.csv, cli-helpers, click, humanize, mssql-cli
WARNING: The script pygmentize is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script wheel is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The scripts futurize and pasteurize are installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script sqlformat is installed in '/Library/Frameworks/Python.framework/Versions/2.7/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Pygments-2.5.2 applicationinsights-0.11.10 argparse-1.4.0 backports.csv-1.0.7 backports.functools-lru-cache-1.6.4 cli-helpers-0.2.3 click-7.0 configobj-5.0.6 enum34-1.1.10 future-0.18.2 humanize-1.0.0 mssql-cli-1.0.0 prompt-toolkit-2.0.10 six-1.16.0 sqlparse-0.2.4 terminaltables-3.1.10 wcwidth-0.2.5 wheel-0.37.1
nandita ~ % mssql-cli -h
zsh: command not found: mssql-cli
nandita ~ %

**Comment by cdunn1331** [comment] 2022-11-18 18:32
Hi @cheenamalhotra -  I'm currently at PASS and @erinstellato-ms mentioned this would be the best way to reach out for you on the error in this thread. I had a handful of Mac users try connecting this morning incase the error was fixed in the latest release (Erin and one of the ADS engineering, mentioned that it could have but weren't completely sure) and still getting that dreaded error.

I'm just wondering when you might think this error will be addressed? We've got about dozen+ users getting the error and it's complicating things when trying to get out of AWS Workspaces.


Thanks!



Colton Dunn
Rev.io 
Help Desk Analyst

**Comment by cheenamalhotra** [comment] 2022-11-18 19:18
Hi @cdunn1331 

Sure, can you copy the error details from the error popup and confirm if you get one of these?

```
....
(provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
```

```
...
(provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name does not resolve
```

Please paste if otherwise.

**Comment by cheenamalhotra** [comment] 2023-03-21 02:39
Closing as inactive and root cause likely related to client env/configurations. 
Please open a new issue if needed with logs for investigations and support.

**Closed by cheenamalhotra** 2023-03-21 02:39 UTC
Labels: Bug, Area - Connection, Needs More Info, Pri: 2, Triage: Done, Size: M
