### ISSUE TITLE
Unable to add Azure account

### ISSUE THREAD

**Issue by realolap** [microsoft/azuredatastudio#6408] opened 2019-07-18 11:22 UTC
Azure Data Studio Version: 1.9.0

The browser device sign-on pops up, but when I return to Data studio I get an error message: "Error adding account Entry not found in cache".
When I do the same, from the same Data studio session,  with my Azure test account (separate tenant) it works fine. Both accounts are in tenants with MFA enabled. Are there other settings/conditions in the AAD that could prevent the connection?

**Comment by mochr** [comment] 2019-08-05 12:43
When I try to add my Azure account (link account), I get the error "Error adding account", without further details. The browser returns "You have signed in to the Azure Data Studio application on your device. You may now close this window.".
I'm attempting to log in using my account that is linked to Windows when using the browser.

I'm also not able to create a new connection using "Azure Active Directory - Universal with MFA upport". Similar behavior is observed. I log in using the browser, but no account is added. Azure Data Studio returns from code/address screen to the connection details screen, but no new account is present in the drop down list.

Might be related to issue #3298, as i have the letter "Ø" in my name.

**Comment by Charles-Gagnon** [comment] 2019-09-16 20:30
I'm going to close this as a duplicate of #3700 - please follow that for any updates! 

Could you respond in the other issue though if there's any errors listed in the developer console (Help -> Toggle Developer Tools) when this occurs?

**Closed by Charles-Gagnon** 2019-09-16 20:30 UTC
Labels: Area: Azure, Bug, Triage: Needed
