### ISSUE TITLE
SSIS, SSAS, SSRS

### ISSUE THREAD

**Issue by ahpitre** [microsoft/azuredatastudio#1080] opened 2018-04-05 18:41 UTC
- SQL Operations Studio Version .27.3
Will Microsoft add to SQL Operations Studio capabilities to connect to and manage SSIS, SQL Agent, and SSRS (like SSMS can)? Find it excellent, but, right now w/o the ability to see my SQL Agent jobs, SSIS projects, etc., SQL Operations Studio is not very useful because you need to go back and forth between 2 tools.

**Comment by kburtram** [comment] 2018-04-06 04:47
@ahpitre we are currently working on SQL Agent support.  There are some details of what we're planning at *#750 Seeking community feedback on SQL Agent UX prototype*.

We don't currently have SSIS and SSRS support in our near-term plans.  We'll be filling in the top missing feature areas from SSMS overtime based on customer demand to try to eliminate the need to switch back-and-forth between tools.

**Comment by affsantos** [comment] 2018-09-17 08:34
@kburtram you didn't mention SSAS. There are plans to add support for SSAS?

**Comment by icbm007** [comment] 2020-07-23 14:37
I agree with this. Azure Data Studio needs to be able to support the Integration Services Catalog feature of SSMS. Major let down its not there.

**Comment by kburtram** [comment] 2021-09-10 18:24
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/1026 or https://github.com/microsoft/azuredatastudio/issues/3758.  It's better to track the different product requests (SSAS, SSIS, SSRS) in individual issues.

**Closed by kburtram** 2021-09-10 18:24 UTC
Labels: Enhancement
