### ISSUE TITLE
case statement check for null - sql notebook issue 

### ISSUE THREAD

**Issue by rkammer** [microsoft/azuredatastudio#17166] opened 2021-09-26 20:02 UTC
When using a sql notebook and running a case statement checking for null values the result is bringing null for every record. The issue appears to be true for the syntax _WHEN NULL_ presented in the following snippet. 

```sql
       CASE ItemExtension.BatchNumberGroupCode WHEN NULL THEN            
            CASE ItemFruitTouch.FruitTouch WHEN 'No' THEN '' ELSE 'Ref' END
       ELSE
            ItemExtension.BatchNumberGroupCode
       END AS AlwaysReturnNULL,
```

However,  it works properly if I use _CASE WHEN field is NULL_ as shown below. 

```sql
    CASE WHEN ItemExtension.BatchNumberGroupCode IS NULL THEN            
            CASE ItemFruitTouch.FruitTouch WHEN 'No' THEN '' ELSE 'Ref' END
       ELSE
            ItemExtension.BatchNumberGroupCode
       END AS Functional,
```

The statement only brings null when running inside a notebook. Running it on a query editor works as expected.

**Comment by smartguest** [comment] 2021-12-01 20:47
Tests on my table using both ADS and SSMS shows that for both query editor (both ADS and SSMS) and Notebooks: reveal that when using WHEN NULL on a column containing one null row, every row is marked as not null.

```
SELECT MyNumericColumn,
CASE MyNumericColumn WHEN NULL then 'NULL'
ELSE 'Not null'
END AS Test
FROM testdatabase.dbo.MyTable
```

But when using WHEN Column IS NULL, it properly marks the null row as null,

```
SELECT MyNumericColumn,
CASE WHEN MyNumericColumn IS NULL then 'NULL'
ELSE 'Not null'
END AS Test
FROM testdatabase.dbo.MyTable
```
There is no difference in results between notebook or query editor, so I'm not sure what is going on here.

**Comment by Charles-Gagnon** [comment] 2021-12-01 21:05
@rkammer NULL can't be directly compared to anything - see https://docs.microsoft.com/en-us/sql/t-sql/language-elements/null-and-unknown-transact-sql?view=sql-server-ver15 for more details.

You should be using IS NULL/IS NOT NULL to compare instead.

So the first query you have is invalid and should never work. I'm not sure how it could be working in a query editor, if you were able to take a screenshot of the query with the results that may help figure out what's going on.

But for now I'm going to close this as "working as intended".

**Closed by Charles-Gagnon** 2021-12-01 21:05 UTC
Labels: Bug, Area - Notebooks, Triage: Done, Triage: Postponed

**Comment by rkammer** [comment] 2021-12-04 00:04
Hi @Charles-Gagnon, 

I apologize for the delay in answering this thread. 

I understand that the correct way to check for _null_ in a statement would be to use the syntax _IS/IS NOT NULL_. But it seems odd that different results are presented by when executing a query in the editor and executing it in a notebook.

I created the following table to provide the an example with screenshots: 

```sql
CREATE TABLE dbo.Commodity (
    Id     INT NOT NULL IDENTITY (1, 1),
    [Name] VARCHAR(10),
    Origin VARCHAR(100) NULL
);

INSERT INTO dbo.Commodity
([Name], Origin)
VALUES
('Avocado',    'California'),
('Avocado',    'Mexico'),
('Avocado',    'Peru'),
('Avocado',    NULL),
('Mango',      'Mexico'),
('Mango',      'Ecuador'),
('Mango',      NULL),
('Watermelon', NULL);
```

Please see the results in the following screenshots.

<figure>
<figcaption>Executing in Query Editor</figcaption>
<img width="463" alt="query=editor" src="https://user-images.githubusercontent.com/2576155/144687739-2e1b4be7-d64f-47aa-9fb1-3ecfe3d1b5f2.png">
</figure>

<figure>
<figcaption>Executing in Notebook</figcaption>
<img width="484" alt="noteboook" src="https://user-images.githubusercontent.com/2576155/144687751-227a4fb9-7385-457e-9779-e669d62a7b57.png">
</figure>

Hope it helps!

**Comment by rkammer** [comment] 2021-12-08 23:42
I'm using version 1.33.1 of Data Studio. SQL Server version Microsoft SQL Server 2017 (RTM-CU25) (KB5003830) - 14.0.3401.7 (X64)
