### ISSUE TITLE
Cannot render timecharts

### ISSUE THREAD

**Issue by kboom** [microsoft/azuredatastudio#20123] opened 2022-07-20 20:19 UTC
- Azure Data Studio Version: 1.37.0
- OS Version: Windows 11 Build 22000.co_release.210604-1628

Steps to Reproduce:

1. Produce any KUSTO query that includes a time series (like summarize by bin(Timestamp, 5m) or make-series)
2. Try to view a timechart. It will not show the time on the x axis, or the time will be one day, unrelated to data, and it will be empty.

Does this issue occur when all extensions are disabled?: Yes (cannot disable the one tested)

To reproduce you can run basically any query that produces time-series compliant data like make-series or summarize by binning timestamp. Here is just one example from the demo cluster.
```
SamplePowerRequirementHistorizedData
| summarize max(value) by bin(timestamp, 1d)
```

You'll get the following result
![image](https://user-images.githubusercontent.com/3975111/180279809-713b055a-b6e7-41f4-bf1d-aa7041aa742d.png)

Make series works the same.

**Comment by alanrenmsft** [comment] 2022-07-21 17:25
will try to repro and triage in Aug milestone

**Comment by alanrenmsft** [comment] 2022-07-25 22:39
I took a look at the time series implementation, and turns out it has special requirements on the data, there must be 3 columns, 
column 1: the series name
column 2: the datetime value
column 3: the numeric value

I used the following T-SQL query:
```T-SQL
select 'a',  CONVERT(datetime2, '2022-02-01'),1
union 
select 'a',  CONVERT(datetime2, '2022-02-02'),2
union 
select'a',  CONVERT(datetime2, '2022-02-03'),3
union 
select'a',  CONVERT(datetime2, '2022-02-04'),4
union 
select'a',  CONVERT(datetime2, '2022-02-05'),5
union
select 'b',  CONVERT(datetime2, '2022-02-01'),3
union 
select 'b',  CONVERT(datetime2, '2022-02-02'),4
union 
select'b',  CONVERT(datetime2, '2022-02-03'),3
union 
select'b',  CONVERT(datetime2, '2022-02-04'),2
union 
select'b',  CONVERT(datetime2, '2022-02-05'),1
```
and produced the following result and chart:
![image](https://user-images.githubusercontent.com/13777222/180885638-f7765d22-51b2-4250-8f24-f5af05da955d.png)

![image](https://user-images.githubusercontent.com/13777222/180885741-b53a6c0c-d75c-4ad9-a776-6f26ed0b1bd6.png)

hope this helps. Meanwhile I am going to work with the PM to see how we can make the requirement more discoverable.

**Comment by alanrenmsft** [comment] 2022-07-25 22:47
@kboom I am closing this issue as a dupe of #16860, if you have additional issues with this feature, please add comments over there to make it easier to manage.

**Closed by alanrenmsft** 2022-07-25 22:47 UTC
Labels: Bug, Area - Query Editor, Area - Notebooks, Triage: Done
