### ISSUE TITLE
Database selection menu no longer visible on dark theme

### ISSUE THREAD

**Issue by oakhousetom** [Microsoft/azuredatastudio#5200] opened 2019-04-25 08:42 UTC
Issue Type: <b>Bug</b>

Since update to latest version of ADS 1.6.0 the database dropdown on the dark theme is no longer visible as the text is black on a dark-grey background.
![09-41-28](https://user-images.githubusercontent.com/30407825/56722182-6a443900-673e-11e9-9b2a-9973731b3fc0.png)

Light theme seems to be working fine.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (4.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.38.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment] 2019-04-29 16:54
Closing as duplicate of #4741.  This will be fixed in the next release.

**Closed by kburtram** 2019-04-29 16:54 UTC
Labels: Area: Query Editor, Bug
