### ISSUE TITLE
Unexpected Error Occurred when trying to connect to database

### ISSUE THREAD

**Issue by CallSign-Filter** [microsoft/azuredatastudio#10576] opened 2020-05-26 22:55 UTC
Issue Type: <b>Bug</b>

Connecting with Windows Authentication through Kerberos

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-29T23:53:03.736Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.99GB free)|
|Process Argv|-psn_0_176171|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-05-27 04:09
I'm closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/7897 - please add any further information you have there. Thanks for the report!

**Closed by Charles-Gagnon** 2020-05-27 04:09 UTC
Labels: Area - Connection, Bug, Needs More Info, Triage: Needed
