### ISSUE TITLE
Occasionally running a query hides the values of the last column 

### ISSUE THREAD

**Issue by yualan** [Microsoft/azuredatastudio#5161] opened 2019-04-23 18:03 UTC
- Azure Data Studio Version: 1.6.0

Steps to Reproduce:

1. Run a query
2. Occasionally will drop last column

Mitigation is to re-rerun the query, but this is definitely a bug. I have the server information that UC used, so the engineer working on this please reach out to me. I saw this bug happen live, but it is hard to consistently reproduce.

![image](https://user-images.githubusercontent.com/30873802/56604647-55896900-65b7-11e9-9346-62bddbabcae6.png)

**Comment by kburtram** [comment] 2019-04-23 22:49
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/3733.

**Closed by kburtram** 2019-04-23 22:49 UTC
Labels: Area: Query Editor, Bug
