### ISSUE TITLE
Automatic Reconnect

### ISSUE THREAD

**Issue by winzig** [microsoft/azuredatastudio#8867] opened 2020-01-13 18:16 UTC
Issue Type: <b>Feature Request</b>

It would be lovely if ADS could automatically reconnect after it is disconnected, e.g. I have a query tab open. I run some commands. I walk away from my computer for a day. I come back, it's disconnected. I highlight a command and hit Run, and it should automatically reconnect and run the command. 

In September of 2018 I chimed in on a similar issue/request, which was closed last January: https://github.com/microsoft/azuredatastudio/issues/2502

If anything, the issue seems to have gotten worse for me over time. 

I am primarily connecting from a macOS Catalina laptop to a SQL Server 2017 server at AWS RDS, over a VPN. Not sure if that matters. I've tried the latest insiders build a few times, and experience the same issue. 

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:37:56.865Z)
OS version: Darwin x64 19.2.0

I searched through the issues here, and have found quite a few people talking about seemingly the same or related issue:

https://github.com/microsoft/azuredatastudio/issues/8656
https://github.com/microsoft/azuredatastudio/issues/7440
https://github.com/microsoft/azuredatastudio/issues/1979
https://github.com/microsoft/azuredatastudio/issues/749
https://github.com/microsoft/azuredatastudio/issues/4931
https://github.com/microsoft/azuredatastudio/issues/2718
https://github.com/microsoft/azuredatastudio/issues/2933

I'm curious if this issue is being worked on by anyone, or if it's completely on the backlog and no one has looked into it? Does anyone have an idea of where in the codebase or architecture the problem may lie?

**Comment by kenvanhyning** [comment] 2020-01-14 17:45
Hi winzig,  this is an issue with the underlying driver we use in Azure Data Studio.  It does not currently have what we call "connection resiliency" for the Mac version.  We have that on Windows but have yet to port that over to the Mac version.  I will be meeting with the driver team next week so I can get an estimate on when we can get that work done for Mac as well.

**Comment by winzig** [comment] 2020-01-14 18:02
@kenvanhyning Awesome, thanks!

**Comment by Dianagard** [comment] 2020-01-27 22:13
Still waiting to hear about this.  Pretty much unusable on my mac as I have to reconnect each time a run a query.

**Comment by winzig** [comment] 2020-03-10 00:38
@kenvanhyning Did you ever hear from the driver team as to when we can expect this feature to make it to Mac? This issue is my single biggest productivity killer across _all_ of my dev tools.

**Comment by winzig** [comment] 2020-04-30 17:09
@kenvanhyning Any update from the driver team? Is there something that outside people could work on or look at to push this forward?

**Comment by winzig** [comment] 2020-07-15 17:36
@kenvanhyning Any update?

**Comment by winzig** [comment] 2020-07-15 18:38
I just went spelunking through this repo trying to ascertain how exactly it connects to SQL Server, but could not figure it out. Could someone point me in the right direction? I.e. the driver that Ken mentioned back in January?

**Comment by Charles-Gagnon** [comment] 2020-07-15 18:42
@winzig The connection stuff is handled by SqlToolsService - a separate C# process that runs alongside ADS.

Most of the connection stuff uses the ReliableSqlConnection class here so if you're wanting to dig into this I'd suggest starting there : 

https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.CoreServices/Connection/ReliableConnection/ReliableSqlConnection.cs#L483

The driver in this case is just Microsoft.Data.SqlClient. I'm unsure of the status of the request though.

**Comment by timothyhoffmann** [comment] 2020-11-24 16:52
Having a "Reconnect" button at the top next to "Connect" would be good for me.  I don't mind clicking on a manual reconnecte after I restart ADS the next day, just would prefer it grabbed the same Connection and reset the "Select Database" to the value at the last shutdown.

**Comment by fluggo** [comment] 2021-05-10 13:01
I think this is an important feature, especially with respect to notebooks—see #7257. I have to close a notebook file and reopen it to get it to reconnect properly.

What's the current status of the code? Can someone point to where the Windows and Mac code differ in this respect?

**Comment by jguidera** [comment] 2021-07-17 21:01
Anyone know if this is being worked.  It is still currently an issue as of this date.  It is extremely annoying to have to constantly be refreshing connections for server explorer and sql windows after every 10 minutes of inactivity (Azure SQL Managed Instance)

**Comment by cheenamalhotra** [comment] 2022-12-14 22:03
Hi @winzig @fluggo @jguidera 

The issue was most likely related to expired access tokens, not being renewed in the backend. We have fixed the behavior recently and is available for testing in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch). With fix, access tokens should be renewed when running query on stale connections. 

Would appreciate feedback on the same :)

**Comment by winzig** [comment] 2022-12-15 00:34
@cheenamalhotra When you say "back-end" and access tokens, are you referring to an Azure-specific fix, or something in general? My issue is related to just a regular non-Azure SQL Server connection. I will say in general it seems to have improved in the last year, but will install the insiders build to see how it goes, thank you.

**Comment by cheenamalhotra** [comment] 2022-12-15 01:16
@winzig 

Thanks for quick turnaround, the underlying driver we use to connect to database takes care of reconnecting if credentials continue to apply. I see this issue was opened a while ago, and in this time drivers have evolved too, so experience should be better now.

In case of Azure, Access tokens would expire and hence connections couldn't be restored, that was recently fixed in ADS.

If you see this issue with latest insiders build, please let us know with server/client info we can use to reproduce and I'll investigate further.

**Comment by cheenamalhotra** [comment] 2023-01-10 03:37
I will proceed to close the issue as it's very generic and many improvements in the area have been made since time. Ideally, our goal is to provide seamless experience where connections are able to reconnect when left inactive for a longer period or server connections drop due to any reason. e.g. we are investigating https://github.com/microsoft/azuredatastudio/issues/21482 for a specific usecase.

Please feel free to open a new issue with specific details when experiencing an issue and we'd be happy to assist!

**Closed by cheenamalhotra** 2023-01-10 03:37 UTC
Labels: Area - Connection, Enhancement, Triage: Done
