### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by guangying94** [Microsoft/azuredatastudio#3095] opened 2018-11-02 02:04 UTC
Issue Type: <b>Bug</b>

Not able to login to Azure.
1. Click on Azure icon on left panel
2. "Sign in to Azure"
3. Being prompted for device login, login in the browser
4. Error to access. 
5. Error message "Error Adding Account", "Error: Entry not found in cache."

Azure Data Studio version: azuredatastudio 1.1.4 (5d6390505643df3edd6f734c80082006efbeff5e, 2018-10-29T20:34:47.838Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.93GB (4.35GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment] 2018-11-13 22:15
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/545.

**Closed by kburtram** 2018-11-13 22:15 UTC
Labels: azure, bug, connection
