### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_ImportFlatFileWizard_ModifyColumns_Colorcontrast : Color contrast ratio of table record focus indication is less than 3:1.

### ISSUE THREAD

**Issue by pranshu512** [microsoft/azuredatastudio#10657] opened 2020-05-30 15:00 UTC
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yWCAG2.1;#DesktopApp;#SQL Azure Data Studio;#FTP;#MAS1.4.11;#Colorcontrast;#AI4D;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider (system setup)
Commit: 8288360
Date: 2020-05-29T05:54:49.731Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Additional Details:**
MAS References: MAS1.4.11
Tool: Accessibility insights for desktop

**Repro Steps:**

1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Install the SQL Server Import extension.
4. Right click on any database undere the connected server & select Import Wizard.
5. Provide Input file details & Next.
6. On Preview Data screen, navigate till Next button & hit enter.
7.Open Accessibility Insights for Desktop and check the Color contrast ratio of table checkbox focus border.

**Actual:**
Color contrast ratio of table checkbox focus border is 2.432:1 i.e less than required 3:1.

**Expected:**
Color contrast ratio of table checkbox focus border must be atleast 3:1.

**User Impact:**
Low vision user would find it difficult to identify table checkbox.

**Attachment link for Reference**:
![bug22](https://user-images.githubusercontent.com/64009219/83331477-57daee00-a2b4-11ea-9692-5833fbe4b602.png)

**Comment by alanrenmsft** [comment] 2020-06-17 23:31
dupe of #10620

**Closed by alanrenmsft** 2020-06-17 23:31 UTC
Labels: Area - SQL Import, Bug, Triage: Done

**Comment by HindujaArugula** [comment] 2023-02-17 09:41
Verified the bug in Azure Data Studio.
Bug is fixed and does not repro.  Hence closing the bug. 
Please find the closing attachment.
**Github Tags:**#Closed;
<img width="648" alt="10657_Closed" src="https://user-images.githubusercontent.com/125462007/219608867-e0d6bf25-e0b7-470f-b255-997f9e5b04f4.png">
