### ISSUE TITLE
Extension doesn't support queries

### ISSUE THREAD

**Issue by pmalits-anstee** [microsoft/azuredatastudio#24282] opened 2023-09-04 09:46 UTC
Type: <b>Feature Request</b>

Execution failed due to an unexpected error: 
	No Handler Registered

Extension version: 0.1.3
Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by lewis-sanchez** [comment] 2023-09-05 19:12
Hi @pmalits-anstee, can you provide additional details about what you're trying to do and what you're using (i.e. Postgres, SQL, etc) when you encounter this error? Any screenshots you can provide will also be helpful to identify the impacted area. Thanks!

**Comment by pmalits-anstee** [comment] 2023-09-06 08:52
Hi there,

I am managed to connect to an Oracle DB v19 via Azure Studio.

However, if I want to query the database – SELECT TOP 100 – I receive the following error message.

***@***.***

Please advise.

------------------------------------------------
Philip Malits-Anstee, MSc, Dip-CII
aka Phil
Data Analytics Lead – Placement
Operations

***@***.******@***.***>
mobile: 07812265199

***@***.***

1 Tower Place, Tower Place East, 1sh Floor, London EC3R 5BU

**Comment by cssuh** [comment] 2023-09-11 17:36
@pmalits-anstee What exactly is the error message you are seeing?

**Comment by pmalits-anstee** [comment] 2023-09-12 08:29
Hello,

It’s the same issue that was raised in #18268.

Does not work with Oracle extension · Issue #18268 · microsoft/azuredatastudio (github.com)<https://github.com/microsoft/azuredatastudio/issues/18268>

It looks like queries are still not supported. Can you confirm please.

------------------------------------------------
Philip Malits-Anstee, MSc, Dip-CII
aka Phil
Data Analytics Lead – Placement
Operations

***@***.******@***.***>
mobile: 07812265199

***@***.***

1 Tower Place, Tower Place East, 1sh Floor, London EC3R 5BU

**Comment by cheenamalhotra** [comment] 2023-09-21 22:43
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/6724 - you may upvote the same so we can better track feature requests.

**Closed by cheenamalhotra** 2023-09-21 22:43 UTC
Labels: Bug, Area - Query Editor, Needs More Info, Triage: Needed, Needs Logs, Area - Oracle
