### ISSUE TITLE
Resource explorer should be "Azure Resources"?

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4003] opened 2019-02-11 22:54 UTC
Issue Type: <b>Bug</b>

On master build, see a very nice suprise - Azure Resource Explorer in the Servers view! Awesome! Only surprise is it shows as "Resource Explorer" with no "Azure" name in sight. Can we fix?

![image](https://user-images.githubusercontent.com/10819925/52599218-de906100-2e0c-11e9-87d8-f327f812a752.png)

Azure Data Studio version: azuredatastudio 1.4.5 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|/Users/kevcunnane/projects/azuredatastudio/.build/electron/Azure Data Studio.app/Contents/MacOS/Electron . --debugBrkPluginHost=36390 --debugId=a6361c7b-da88-458c-8bc6-79a4e5f4cadc --extensionDevelopmentPath=/Users/kevcunnane/projects/SqlOpsStudioExtensions/extensions/aris|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.10.0
PowerShell|ms-|1.11.0

</details>

**Comment by anthonydresser** [comment] 2019-02-28 18:22
Dupe of #4236

**Closed by anthonydresser** 2019-02-28 18:22 UTC
Labels: azure, bug, data explorer, duplicate

**Comment by kevcunnane** [comment] 2019-02-28 18:32
Hey now, shouldn't the other one be closed since mine was first? 😉

**Comment by anthonydresser** [comment] 2019-02-28 18:34
Probably but Karl already referenced his in his PR.
