### ISSUE TITLE
Connection errors with on-premise SQL Server using Apple Silicon 14.0.1

### ISSUE THREAD

**Issue by gbougiakas** [microsoft/azuredatastudio#21320] opened 2022-11-29 10:39 UTC
- Azure Data Studio Version: 14.0.1
- OS Version: macOS 13.0.1

Steps to Reproduce:

1. Connect to an on-premise SQL Server
2. Run any query

Partial results are displayed into the grid and then the following error occurs

Started executing query at Line 1
(1000 rows affected)
Query failed: Invalid operation. The connection is closed.
Total execution time: 00:00:02.289

Does this issue occur when all extensions are disabled?: Yes

**Comment by dzsquared** [comment] 2022-11-30 18:33
I'm seeing this as well in 1.40.1 and not in Insiders.

![2022-11-30_10-18-29 (1)](https://user-images.githubusercontent.com/12227241/204879868-f54191a7-62fd-4b9a-bca6-2f3c31654934.gif)

**Comment by alanrenmsft** [comment] 2022-12-01 20:42
@dzsquared only reproduces on Mac, right?

**Comment by dzsquared** [comment] 2022-12-01 20:49
@alanrenmsft I've only been on macOS in ADS recently, so difficult to say

**Comment by alanrenmsft** [comment] 2022-12-06 19:01
@gbougiakas I was able to reproduce the issue and you can work around it by:
1. Delete the connections from Connections view
2. Restart Azure Data Studio

please let me know if you are still having issue.


@cheenamalhotra , assigning to you for investigation.

**Comment by cheenamalhotra** [comment] 2022-12-12 20:47
I figured out this issue is indeed fixed in Insiders build with PR: https://github.com/microsoft/azuredatastudio/pull/21206, specifically this change:

https://github.com/microsoft/azuredatastudio/pull/21206/files#diff-8e6e02b2056f8700c383eabfb6390f5906007f1c68e9ff9d857b88afad9cc1ceR971

Previously if 'expiresOn' property was present in connection properties, it wasn't checked whether the connection profile is using Azure MFA auth, and reconnect was issued, this led to dropping existing connection in use by query.

I'm looking further into avoiding adding this property for non-AzureMFA, as that seems to be happening in the Insiders build.

**Closed** 2022-12-19 21:04 UTC
Labels: Bug, Area - Connection, Pri: 1, Triage: Done, Size: M
