### ISSUE TITLE
Icon inside Windows10 tile is too big

### ISSUE THREAD

**Issue by bludev** [microsoft/azuredatastudio#13428] opened 2020-11-16 10:41 UTC
- Azure Data Studio Version: 1.24.0

Steps to Reproduce:

1. add ADS tile to Windows 10 start menu.
The icon inside the tile is too large, in both small and medium sizes.
![image](https://user-images.githubusercontent.com/15612827/99242589-ba428f00-27ff-11eb-9ee6-354194e9af67.png)

**Comment by JoshuaGarrison27** [comment] 2020-11-30 18:14
This is happening for me too...

![image](https://user-images.githubusercontent.com/1706923/100647653-d40ac880-330d-11eb-88ec-39715ff4bb43.png)

**OS Name:** Microsoft Windows 10 Enterprise
**Version:** 10.0.17763 Build 17763
**System Model:** Surface Pro 6

**Comment by Charles-Gagnon** [comment] 2020-12-01 02:18
Duplicate of https://github.com/microsoft/azuredatastudio/issues/13452

**Closed by Charles-Gagnon** 2020-12-01 02:18 UTC
Labels: Area - Shell, Bug, Triage: Needed
