### ISSUE TITLE
Old Release download links only download the most recent version

### ISSUE THREAD

**Issue by TimNewsom** [microsoft/azuredatastudio#25929] opened 2024-09-19 14:01 UTC
- Azure Data Studio Version: any verison not the most recent
- OS Version: doesn't matter.

Steps to Reproduce:

1. Go to the releases page
2. Select the download link for any version that is not the current version
3. see that only the current version downloads.

How should I be downloading older releases if the releases link does not work?

**Comment by kburtram** [comment] 2024-09-23 21:12
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/25735 and https://github.com/microsoft/azuredatastudio/issues/25934.

**Closed by kburtram** 2024-09-23 21:12 UTC
