### ISSUE TITLE
capabilities of mysql workbench and reporting service

### ISSUE THREAD

**Issue by zero2000** [microsoft/azuredatastudio#734] opened 2018-02-19 15:56 UTC
- SQL Operations Studio Version:

Version 0.26.7 (0.26.7)

Steps to Reproduce:

hello, I've been seeing the network and I find tool, and I see that it has great potential but what would be useful is that it had design tools similar to those that have mysql workbench
![alt text](https://www.mysql.com/common/images/products/MySQL_Workbench_Visual_Design_Windows.gif "designer")
 that is the best, sure you can implement something like that , as well as the ability to generate reports similar to those offered by reporting services
![alt text](https://www.sqlshack.com/wp-content/uploads/2014/09/ReportProject9MVS.png)
, but without linking it to msssql, that is, independent of the database. apart it would also be of vital importance for those of us who do stored procedures, triggers, views and functions to consider a debugging method 
![alt text](https://www.devart.com/dbforge/mysql/studio/images/tutorials/debugger-fig5.png)
and know that it is possible because visual studio can do it with mysql. to be able to analyze the herrors and improve the performance

**Comment by kburtram** [comment] 2018-03-07 01:15
@zero2000 thanks for the suggestions.  Diagraming, reporting and debugging are all areas we've discussed internally.  Currently we're trying to improve Dashboard extensibility which may meet some of the reporting requirements, though certainly not a 1-to-1 with Reporting Services control in SSMS.

MSSQL debugging protocol is built on DCOM which Windows-only.  We'd need a new cross-platform protocol in the engine to really support this across the supported platforms.  It's been discussed, but hasn't been committed.

Diagramming is an interesting area that we are considering for a future release.  We think it may be a great area for a 3rd party extension to fill, as it's not on our near term backlog based on top upvoted issues.

**Comment by kburtram** [comment] 2019-07-17 22:51
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/94.  To consolidate similar issues.  Please open individual issues for other features you'd like us to add to the product.  Thanks!

**Closed by kburtram** 2019-07-17 22:51 UTC
Labels: Enhancement
