### ISSUE TITLE
A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ScreenReader: Unnecessary Hidden content read by screen reader.

### ISSUE THREAD

**Issue by v-atkulk** [microsoft/azuredatastudio#9469] opened 2020-03-06 05:09 UTC
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#DesktopApp;#MacOs;#Benchmark;#A11y_SQLAzureDataStudioBenchmark;#A11ySev2;#MAS1.3.1;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.15.0-insider
Commit: 3a8b74a
Date: 2020-02-11T05:49:41.181Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
Mac OS:10.15.3

**Additional Details:**
Screen reader: Voice Over
MAS reference: MAS1.3.1

**Repro Steps:**
1.Launch Azure Data Studio.
2.From the left menu, click the 'Extensions' icon to open the Extension Manager.
3.Choose any extension from the library.
4.Click the green 'Install' button to install.
5.Launch VoiceOver screen reader and navigate to the content present below 'Admin pack for SQL Server' heading.
6.Check if hidden content is read by screen reader.

**Actual:**
Hidden content present on the screen is read by screen reader(Voice Over).

**Expected:**
Hidden content present on the screen should not be read by screen reader.

**User Impact:**
Users might get confused as the content that is not present on the screen is read by screen reader.

**Attachment link reference:**
[9469_A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/4296546/9469_A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ScreenReader.zip)

**Comment by alanrenmsft** [comment] 2020-03-06 19:25
dupe of #9256

**Closed by alanrenmsft** 2020-03-06 19:25 UTC
Labels: A11y_AzureDataStudio, Bug, Triage: Done

**Comment by Raghu-addepalli** [comment] 2023-02-14 11:13
https://user-images.githubusercontent.com/91586743/218720402-2b4d626d-3e39-488f-9de3-a2d75f8eb492.mov

Verified the issue now it is not Reproducing Hence closing the bug.

Git Hub Tags: #Closed;

**Comment by mstechie** [comment] 2023-03-05 19:17
GitHubTags:#BM-TCS-SQLADS-MAC-Feb2020;
