### ISSUE TITLE
Want command to rename connection in SERVER

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2910] opened 2018-10-16 21:27 UTC
Issue Type: <b>Feature Request</b>

The name for a server given in SERVERS does not appear in tabs and hte dashboard.

Because of this, I'd like to rename the name in servers so that it matches what does appear in the dashboard.

RECOMMENDATION
1. Add/use the server name given by users to tabs and dashboards so that it is easy to match with the server in SERVERS.
2. Allow users to easily change the name by adding a "Rename" command to the command menu or adding a "Rename" command to a main menu. (Edit menu?).

![image](https://user-images.githubusercontent.com/41927913/47048525-83e14400-d14f-11e8-995b-4e1a6d06c525.png)

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

**Comment by MattIrv** [comment] 2018-10-17 22:38
We got a community contribution that addressed part 1: https://github.com/Microsoft/azuredatastudio/pull/2794

though now it doesn't show the server address at all, just the name, so I wonder if we want to think any more about how to display all the info

**Comment by kburtram** [comment] 2020-02-21 18:07
This is a duplicate of other issues we're tracking to be able to edit connection details.

**Closed by kburtram** 2020-02-21 18:07 UTC
Labels: Area - Connection, Enhancement

**Comment by michaelblyons** [comment] 2020-02-21 18:45
@kburtram Great, I'm all for closing duplicates! Can you link them, please?
