### ISSUE TITLE
SQL Temp tables not persisted between cells

### ISSUE THREAD

**Issue by ChrisUnsworth** [microsoft/azuredatastudio#12647] opened 2020-09-28 11:02 UTC
- Azure Data Studio Version:
1.22
Steps to Reproduce:

1. Create new notebook using an SQL Kernel
2. Create code cell containing:
`DROP TABLE IF EXISTS #Test

SELECT *
INTO #Test
FROM 
 (VALUES (1)) AS v(i)

SELECT * FROM #Test`
3. Create second code cell with:
`SELECT * FROM #Test`
4. observe error message:
`Msg 208, Level 16, State 0, Line 1
Invalid object name '#Test'.
Total execution time: 00:00:00

`

**Comment by Charles-Gagnon** [comment] 2020-09-28 17:25
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/12646

**Closed by Charles-Gagnon** 2020-09-28 17:25 UTC
Labels: Area - Notebooks, Bug, Triage: Needed

**Comment by anisri** [comment] 2022-02-21 16:54
SQL temp tables persist between cells, but intellisense doesn't recognize those table names. Still a lingering issue here.
