### ISSUE TITLE
SQL profiler extension Doesn't produce any output

### ISSUE THREAD

**Issue by jtsom** [Microsoft/azuredatastudio#2168] opened 2018-08-07 18:25 UTC
- SQL Operations Studio Version: 0.32.3-insider

Steps to Reproduce:
Connect to a (localdb)\mssqllocaldb database
Open Profile window (Profiler: New Profile from command palette)
Click Start
Do any operation on the database.

Nothing shows up in the grid.

**Comment by yualan** [comment] 2018-08-07 19:40
I was able to repro.

Repro steps:
- Download latest insider build
- Connect to localhost
- Open Profiler Window (Alt+P)
- Start Profiler (Start Button or Alt+S)

![image](https://user-images.githubusercontent.com/30873802/43798163-98214f16-9a3e-11e8-9952-d0816fc9b6da.png)

The issue is the new changes that were added always defaults to **AlwaysOn_health** instead of to **Profiler.**

Typical user will want to have default to Profiler instead of first option in alphabetical dropdown.

If user selects Profiler and starts, then it will start to track events like T-SQL statements. However, when user clicks stop, dropdown automatically goes back to AlwaysOn_health instead of staying on Profiler.

**Comment by jtsom** [comment] 2018-08-07 19:46
Hm. My dropdown only has AlwaysOn_Health and system_health. I gather other plugins / extensions are needed? Perhaps more info / steps in the docs (or at least on the extension info page) would be helpful?

**Comment by yualan** [comment] 2018-08-07 20:13
Hi jtsom, these are from the custom extended event sessions detected on the server:

![image](https://user-images.githubusercontent.com/30873802/43799644-fc6c6aa6-9a42-11e8-9acb-2424c98fbf35.png)

As viewed on SSMS. 

More info on extended events sessions can be found here: https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/quick-start-extended-events-in-sql-server?view=sql-server-2017

This is something we will investigate. Since my custom session called 'Profiler' is not default (AlwaysOn_health and system_health are), it may be better practice to not select a session at first unless user selects.

**Comment by jtsom** [comment] 2018-08-07 21:02
I think maybe the bigger question is, is this supposed to work on the mssqllocaldb instance? (As I noted in my steps initially)  I’m thinking this may be the underlying issue. (Though the full sql server profiler can profile the localdb just fine)

**Comment by alanrenmsft** [comment] 2018-11-08 23:03
I believe this has been fixed in latest release: https://github.com/Microsoft/azuredatastudio/releases/tag/1.2.4

**Closed** 2018-11-08 23:03 UTC
Labels: bug, needs repro, profiler
