### ISSUE TITLE
OverType doesn't work

### ISSUE THREAD

**Issue by jkarr** [microsoft/azuredatastudio#10269] opened 2020-05-05 14:18 UTC
Issue Type: <b>Bug</b>

When I press the Insert key on my keyboard, it does not toggle the editor into OverType mode.

To reproduce, 
1) Place the cursor at the beginning of a line of text.
2) Press INS on keybaord
3) Start typing

Expected Behavior: the typed text replaced the text at the cursor position as the cursor advances.
Actual Behavior: the typed text is inserted at the cursor position, but the existing text remains (not overtype mode)

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (15.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-05-05 16:08
As a workaround you can install the https://marketplace.visualstudio.com/items?itemName=adammaras.overtype extension for VS Code into ADS and that should work fine. 

This is apparently a long standing ask for VS Code to implement but they have yet to do so in the core editor. https://github.com/microsoft/vscode/issues/1012

**Comment by kburtram** [comment] 2020-05-07 20:12
We rely on vscode for basic editor functions.  Ideally this will be addressed upstream.  I'll close as a duplicate of microsoft/vscode#1012

**Closed by kburtram** 2020-05-07 20:12 UTC
Labels: Area - Query Editor, Bug, Triage: Needed, Upstream
