### ISSUE TITLE
Add options to check and uncheck all objects in Schema Compare

### ISSUE THREAD

**Issue by lucasmarotta** [microsoft/azuredatastudio#20983] opened 2022-10-26 18:00 UTC
**Is your feature request related to a problem? Please describe.**
When using Schema Compare having a lot of differences between a source and target, is difficult to just select what you want per type, action and select or uncheck all.

**Describe the solution or feature you'd like**
Add an option to check and uncheck all object differences. Add ways to check per object type (like table, view, procedure) and per object action (change, add and delete). Also would be could to and search functionality on this screen.  Maybe it could be nested list trees per action or object type.

**Describe alternatives you've considered**
I think at least should be a option check and uncheck all objects.

**Additional context**
I couldn't find a similar request on issues.

**Comment by kisantia** [comment] 2022-10-26 18:15
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/10430

**Closed by kisantia** 2022-10-26 18:15 UTC
