### ISSUE TITLE
[macOS] "Saved connection" not remembered

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Microsoft/azuredatastudio#5026] opened 2019-04-14 04:21 UTC
Issue Type: <b>Bug</b>

Start appication (latest version)
Click on New Connection.
Specify the connection details to an existing running SQL Instance.
Optionally specify the "Name" of the connection.
Click connect...

Expected: if the connection is successful, you expect the connection will be remembered either in "Recent Connection" or "Saved Connections"

Actual: The connection details are not remembered. If you try to re-connect, all the settings need to be specified again. 

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell-Preview|ms-|2.0.0

</details>

**Comment by SQLvariant** [comment] 2019-04-23 00:15
I'm experiencing a similar issue on Windows 10 (today's build.)

**Comment by the-reverend** [comment] 2019-04-24 14:05
i'm experiencing hte same issue.

Azure Data Studio version: Azure Data Studio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T06:14:17.039Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by abist** [comment] 2019-04-30 23:06
@Abhijit-Revamp  @the-reverend Any specific kind of server you guys are connecting to? I can't seem to reproduce this issue.

**Comment by the-reverend** [comment] 2019-05-01 14:53
ms sql server. i'm happy to hop on a video share and demo the issue for you.

**Comment by joshuaquiz** [comment] 2019-05-01 16:48
I am having this issue on windows as well, MS closed my ticket as a dup so I am posting here.

If I have a connection with name "Connection A" and then later I need to update say the password or something else and want to override "Connection A", no override happens. It asks where you want to save it be then does not overwrite the existing connection.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.91GB (4.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by the-reverend** [comment] 2019-05-01 17:03
my issue is that entries no longer show up in the 'Recent Connections' list. i've had no problems with Saved Connections so far, but don't change my connection details frequently. after the most recent update, the 'Recent Connections' list was cleared and no matter how often i connect, it remains cleared.

**Comment by kburtram** [comment] 2019-05-01 17:20
@the-reverend there were some design changes to the MRU which @Charles-Gagnon can explain a bit more.  We should determine if there are two issues here and split them out if necessary.  Thanks!

**Comment by the-reverend** [comment] 2019-05-01 20:49
i think my issue may just be a misunderstanding. i was connecting to servers from the Saved Connections list and expecting them to subsequently start showing up in the Recent Connections list. however, when connecting to an entirely new server, not in my Saved Connections, these show up in Recent Connections.

From a usability perspective, I want my most frequently accessed connections to show up in Recent Connections because it saves me a mouse click to switch tabs to Saved Connections and another mouse click to expand my list of Production Servers.

So at this point, my main complaint boils down to, "The April update cleared my Recent Connections list, and connecting to Saved Connections doesn't subsequently populate Recent Connections." But maybe that Works As Designed? If so, I don't love how that was designed.

**Comment by Charles-Gagnon** [comment] 2019-05-02 17:55
Interesting - that's definitely an issue if it's happening. So to confirm these are the steps you're taking :

1. Start with MRU list that doesn't contain the server you're connecting to
2. Click on the *Saved Connections* tab and connect to a server that isn't in the MRU
3. Connect successfully
4. Go to *Recent Connections* tab and that server isn't being displayed there

Is that correct? I followed those steps and it added the connection to the MRU just fine. Although granted this was on a Windows machine so maybe something is different on a mac - I'll get a hold of one to test and see if I can repro it there.

**Comment by Abhijit-Revamp** [comment] 2019-05-02 18:04
One addition : 
Start with previous released version and let it populate couple of entries.
Then upgrade to latest released version. You will experience the problem

I think there may be some serialisation changes between versions that causing this issue...

**Comment by kburtram** [comment] 2019-05-02 20:55
@Charles-Gagnon I opened this related issue which addresses a specific use-case that I think we should fix for May https://github.com/Microsoft/azuredatastudio/issues/5325.

**Comment by the-reverend** [comment] 2019-05-02 23:51
@Charles-Gagnon - yes. you described it accurately.
@Abhijit-Revamp - nice addition.

**Comment by the-reverend** [comment] 2019-05-02 23:55
point of clarification - i'm using the right rail connection screen that pops up when you press 'Run' or 'Connect' from a query -- not the left nav connections pane.

**Comment by Charles-Gagnon** [comment] 2019-05-03 00:02
Ok cool, yeah so the difference was that if you do it from the "Add Connection" button in OE then it works fine. But if you do it from a query editor then it didn't function correctly. I've fixed this with #5328 so you shouldn't see this after the next release. Thanks for the report!

The clearing MRU entries is a separate issue though - I'll investigate that. I'm going to close this since the reported issue is resolved - feel free to open another issue for the clearing MRU entries on update (if I can repro it I'll open one myself too)

**Closed by Charles-Gagnon** 2019-05-03 00:02 UTC
Labels: Area: Connection, Bug
