### ISSUE TITLE
Context Menu Filter Option for SERVERS tab

### ISSUE THREAD

**Issue by covelloz** [microsoft/azuredatastudio#1628] opened 2018-06-13 21:04 UTC
In the context menu of the SERVERS tab (Ctrl+G), provide a quick-access FILTER functionality.

SSMS has this in its Object Explorer and it is extremely useful to de-clutter the view.
https://docs.microsoft.com/en-us/sql/ssms/object/filter-settings-object-explorer-and-utility-explorer?view=sql-server-2017

Using the "MANAGE > Search box" feature is fantastic for exploration, but it would be nice if you can find what you're looking directly via the SERVERS tab while at the same time remove items you don't care about

**Comment by Charles-Gagnon** [comment] 2020-07-22 23:00
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as cleanup

**Closed by Charles-Gagnon** 2020-07-22 23:00 UTC
Labels: Area - Data Explorer, Enhancement
