### ISSUE TITLE
Notebooks lost on save

### ISSUE THREAD

**Issue by rondunn** [microsoft/azuredatastudio#9101] opened 2020-02-08 06:14 UTC
I'm persistently losing notebooks when I attempt to save.

When I take the SAVE AS... menu option I get a new tab open with the same notebook name, and a save dialog that defaults to a TXT file type.

Taking the SAVE action then creates an empty text file, also deleting the original contents of the notebook in memory.

**Comment by chlafreniere** [comment] 2020-02-11 19:42
@rondunn I can't reproduce your issue at the moment. Are you running our stable (latest is 1.14.1) or insiders build? Can you also share which OS which you're using as well?

**Comment by chlafreniere** [comment] 2020-03-11 19:26
Cannot repro so closing this issue for now. If you can still reproduce this, please feel free to reactivate.

**Closed by chlafreniere** 2020-03-11 19:26 UTC
Labels: Area - Notebooks, Bug, Triage: Done
