### ISSUE TITLE
Server browser (sometimes) fails to connect to AzureDW with MFA

### ISSUE THREAD

**Issue by 7even7** [microsoft/azuredatastudio#7712] opened 2019-10-14 07:16 UTC
Issue Type: <b>Bug</b>

Getting "Failed to connect to server ... " Error in connections - server browser, even though connection is alive. 
I can query the server Ok, with "New query" -> "Connect". I just can't get the browser to show me tables, views etc. This error is sometimes fixed by disconnecting and reconnecting to the server. This problem does not repeat itself every time and right now I can see prod-server OK, but dev-server fails to connect.
Destination DB is Azure DW with MFA enable

![image](https://user-images.githubusercontent.com/18673617/66734244-fec86200-ee6a-11e9-8f5e-d80c67ecf93b.png)

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment] 2019-10-15 16:33
If you open the developer console (Help -> Toggle Developer Tools) and then go to the console tab are there any errors listed there when you try to connect? Or any errors shown when this happens?

**Comment by 7even7** [comment] 2019-10-21 05:47
Only visible errors in UI are the ones in object explorer. In the dev console there are a few errors.

Here's an extract from console:
```
   ERR Cannot read property 'uri' of null: TypeError: Cannot read property 'uri' of null
    at ListDatabasesActionItem.onConnectionChanged (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:206900:42)
    at ListDatabasesActionItem._toDispose.push.connectionManagementService.onConnectionChanged.params (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:206788:102)
    at Emitter.fire (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:11078:38)
    at ConnectionManagementService._notifyConnectionChanged (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:227622:43)
    at ConnectionManagementService.onConnectionChangedNotification (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:227618:18)
    at MainThreadDataProtocol.$onConnectionChangeNotification (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:239392:47)
    at RPCProtocol._doInvokeHandler (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:245007:27)
    at RPCProtocol._invokeHandler (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244992:45)
    at RPCProtocol._receiveRequest (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244924:32)
    at RPCProtocol._receiveOneMessage (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244852:26)
    at RPCProtocol._protocol.onMessage (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244742:52)
    at Emitter.fire (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:11078:38)
    at BufferedEmitter.fire (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33465:35)
    at PersistentProtocol._receiveMessage (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33684:37)
    at PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33558:83)
    at Emitter.fire (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:11078:38)
    at ProtocolReader.acceptChunk (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33291:37)
    at ProtocolReader._register._socket.onData.data (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33260:61)
    at Socket.listener (file:///C:/Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33841:40)
    at ZoneDelegate.invokeTask (c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
 INFO Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxxxdev.database.windows.net|user:firstname.lastname@domain.fi|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxxxdev.database.windows.net|user:firstname.lastname@domain.fi|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxxxdev.database.windows.net|user:firstname.lastname@domain.fi|group:e141eeae-fb18-4299-b646-db25dce16a08
newquery-inverse.svg:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxxxdev.database.windows.net|user:firstname.lastname@domain.fi|databaseDisplayName:master|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxxxdev.database.windows.net|user:firstname.lastname@domain.fi|databaseDisplayName:master|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxxxdev.database.windows.net|user:firstname.lastname@domain.fi|databaseDisplayName:master|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Failed to connect to server xxxxxxxdev.database.windows.net.
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Failed to connect to server xxxxxxxdev.database.windows.net.
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:xxxxxxxprod|server:xxxxxxxprod.database.windows.net|user:firstname.lastname@domain.fi|databaseDisplayName:xxxxxxxprod|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:xxxxxxxprod|server:xxxxxxxprod.database.windows.net|user:firstname.lastname@domain.fi|databaseDisplayName:xxxxxxxprod|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280  INFO Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:xxxxxxxprod|server:xxxxxxxprod.database.windows.net|user:firstname.lastname@domain.fi|databaseDisplayName:xxxxxxxprod|group:e141eeae-fb18-4299-b646-db25dce16a08
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Failed to retrieve data for this request.
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Failed to connect to server xxxxxxxdev.database.windows.net.
c:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Failed to retrieve data for this request.
```

**Comment by kburtram** [comment] 2021-08-17 23:23
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/5173 or one of the other active issues regarding failure to expand the server node.  We will investigate this scenario in an upcoming release to locate additional bugs that may still be present.

**Closed by kburtram** 2021-08-17 23:23 UTC
Labels: Bug, Area - Connection, Needs More Info, Triage: Done
