### ISSUE TITLE
New dashboard table search is a regression: suggestions for improved search

### ISSUE THREAD

**Issue by didii** [microsoft/azuredatastudio#10789] opened 2020-06-08 10:07 UTC
**Is your feature request related to a problem? Please describe.**
The new dashboard search is quick and fancy, but doesn't allow to search on both the schema as well as the table. This is a regression compared to the previous version.

Currently, when I'd use the query `<schema>.<table>` not a single table will show up. This is not intuitive. For large databases, a filter on just the table name is not enough to narrow down the amount of items enough for an easy quick find of a table. Previously, this query was possible to quickly find tables, filtered on both schema and table.

**Describe the solution or feature you'd like**
A more friendly way to search for tables would be where individual words of the query would span over more than a single column. For example, the query `<schema> <table>` should search for each individual word in at least the visible columns. So any word in the query (here `<schema>` and `<table>`) **must** each individually be a substring of table name, schema name or item type. Note that the query `<table> <schema>` should provide the same results.
*see note at the bottom for names with spaces

It would be great if also the `.` syntax would be supported: `<schema>.<table>` should know that left of the `.` should be the schema name (exact match) and the right of it should be the table name (startsWith match).
This might be extended with the syntax `<schema>.` where no string is present at the right of the `.`. This would mean that we are only interested in the schema with exact name `<schema>`.

Unless there is good reason to do so, I don't think including more columns to search in would provide any benefit for the user and would probably only clutter the results. Even filtering on item type should be considered if it is worth it.

*about names with spaces
For names containing a space, while not common, they are still supported in how it is described, but it will include a lot of clutter for all matches with any of the words. Either do a 'relevant sort' where exact matches on the entire string are always shown on top of the list, or introduce the quote or square brace syntax to group words: `table name` would then become `"table name"` or `[table name]` where no searches are made on the words `table` and `name` anymore. If combined with the `.` syntax, I would personally prefer to only use the square brackets, but since double quotes are pretty standard in search queries, it wouldn't hurt to support this as well.
Note that the relevant sort and word grouping are not exclusive.

**Describe alternatives you've considered**
If there are already more precise ways to filter, it should be more clearly documented inside the application. All I can find is to be able to filter by type in the placeholder, which isn't enough (see screenshots below).

**Additional context**
I feel like the above syntax would provide a more intuitive way to search, especially using the `.` syntax, since that is what you'd usually use to query a table. This tries to rely on those conventions rather than inventing a custom syntax everyone will have to learn.

Some screenshot to illustrate my point:
Trying to find the table I'm interested in. Note the location and size of the scrollbar. There doesn't seem a way to further condense the results. Note that the query `t:mad` will give the same results.

![TableSearch](https://user-images.githubusercontent.com/2774842/84014796-2da3c300-a97b-11ea-961d-9453c2300c99.png)

Searching for `<schema> <table>` returns no results (same for `<schema>.<table>`)

![EmptyMatch2](https://user-images.githubusercontent.com/2774842/84014453-a0606e80-a97a-11ea-8b10-498095390812.png)

Searching for only the schema. Note that it returns tables from other schema's.

![SchemaSearch](https://user-images.githubusercontent.com/2774842/84014493-b2daa800-a97a-11ea-9b07-b85023779915.png)

**Comment by alanrenmsft** [comment] 2020-06-08 17:49
this is a dupe of https://github.com/microsoft/azuredatastudio/issues/10601. the fix is already in the insiders build and will be included in the upcoming stable release.

@didii you should be able to search by schema name by {schemaName}.{objectName} now. regarding to your last point, the record from other schema is returned because it has the schema name in the table name, if you want to filter by schema, you can search by schema name followed by a dot.

**Closed by alanrenmsft** 2020-06-08 17:49 UTC
Labels: Area - Dashboard, Enhancement, Triage: Needed

**Comment by didii** [comment] 2020-06-09 08:48
I'll just confirm that this is indeed a dupe of #10601. Sorry for that, I think I only searched for open issues. Great to hear it's coming up in the next stable release!
