### ISSUE TITLE
Query Plan Tree and Top Operations aren't working

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#23566] opened 2023-06-29 18:36 UTC
The Query Plan Tree and Top Operations window appear to have been busted in the vscode source code refresh.  The table isn't rendering correctly and there are exceptions in the dev console.

![image](https://github.com/microsoft/azuredatastudio/assets/599935/1f0ad29e-30b2-4531-8560-ee27ce4ce66a)

```
Uncaught TypeError: inputString.replace is not a function
    at htmlEscape (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:1866:33)
    at appendCellHtml (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:1915:38)
    at appendRowHtml (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:1851:13)
    at renderRows (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2438:9)
    at render (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2509:7)
    at SlickGrid.resizeCanvas (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2143:7)
    at TreeGrid.resizeCanvas (table.ts:306:14)
    at TreeGrid.layout (table.ts:330:8)
    at ResizeObserver.<anonymous> (executionPlanTreeTab.ts:348:13)
C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2270 Uncaught TypeError: Cannot read properties of null (reading 'lastChild')
    at ensureCellNodesInRowsCache (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2270:46)
    at cleanUpAndRenderCells (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2338:9)
    at render (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2504:11)
    at SlickGrid.resizeCanvas (C:\Users\karlb\repos\azuredatastudio\node_modules\slickgrid\slick.grid.js:2143:7)
    at TreeGrid.resizeCanvas (table.ts:306:14)
    at TreeGrid.layout (table.ts:330:8)
    at ResizeObserver.<anonymous> (executionPlanTreeTab.ts:348:13)
```

**Comment by Charles-Gagnon** [comment] 2023-06-29 18:54
Duplicate of https://github.com/microsoft/azuredatastudio/issues/23564 - @lewis-sanchez make sure to check with @aasimkhan30 in case he's already started looking at this

**Closed by Charles-Gagnon** 2023-06-29 18:54 UTC
Labels: Bug, Area - Query Editor, Triage: Done, Subarea - Execution Plan
