### ISSUE TITLE
Notebooks: Only have One Active Session Active at a Time

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3686] opened 2019-01-09 01:12 UTC
In the notebook model, we should only have one active session at a time; now that multiple providers can be passed into the model, only have one session active for the current provider and dynamically start/shutdown sessions based on kernel change events.

**Comment by kevcunnane** [comment] 2019-02-08 00:13
Close as dupe of other issue

**Closed by kevcunnane** 2019-02-08 00:13 UTC
Labels: notebooks
