### ISSUE TITLE
Mac OS X (Catalina) Azure Data Studio - MS Import - flatfileimport.start Not Found

### ISSUE THREAD

**Issue by thebitslinger** [microsoft/azuredatastudio#11448] opened 2020-07-21 14:42 UTC
- Azure Data Studio Version: 1.3.8

Steps to Reproduce:

1. Installed SQL Server Import 0.18.0
2. Selected Database and clicked CTRL = I
3. Got message: command 'flatFileImport.start' not found

Developer console logged the following:

/private/var/folders/n8/5_lt1nh57nl7c85vzgtsv89wzd_41d/T/AppTranslocation/B468B019-1A9D-42A7-9C1C-0CF3E3C7AB9D/d/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280 Error: command 'flatFileImport.start' not found
    at CommandService._tryExecuteCommand (workbench.main.js:198075)
    at workbench.main.js:198069
    at Promise_ctor.CompletePromise_then [as then] (workbench.main.js:18092)
    at CommandService.executeCommand (workbench.main.js:198069)
    at MenuItemAction.ExecuteCommandAction.run (workbench.main.js:98591)
    at MenuItemAction.run (workbench.main.js:98634)
    at workbench.main.js:195162
    at Promise_ctor.CompletePromise_done [as done] (workbench.main.js:18050)
    at Object.notifySuccess [as _notify] (workbench.main.js:17706)
    at Object.enter (workbench.main.js:17372)
    at Promise_ctor._run (workbench.main.js:17594)
    at Promise_ctor._completed (workbench.main.js:17562)

**Comment by Charles-Gagnon** [comment] 2020-07-21 14:48
Is ADS version 1.3.8 accurate? The 0.18 version of the Import extension requires ADS to be at least version 1.20.0, so you'll need to update to the latest version of ADS to use it.

**Comment by Charles-Gagnon** [comment] 2020-07-21 14:49
I'm going to close this as it's working as intended if that's the case. Let us know if you think this is inaccurate and we can investigate further.

**Closed by Charles-Gagnon** 2020-07-21 14:49 UTC
Labels: Area - SQL Import, Bug, Triage: Needed

**Comment by thebitslinger** [comment] 2020-07-21 15:20
@Charles-Gagnon Interesting... I ADS, I check for updates, and it says there are no updates available.
