### ISSUE TITLE
Query History: Double click to copy it to Query Editor

### ISSUE THREAD

**Issue by thiagolunardi** [microsoft/azuredatastudio#8257] opened 2019-11-07 08:33 UTC
SQL History is an awesome feature and is a **must to have** for everyone.
Now I'm missing resources to restore a past query in a more productive way.

First, there is no "Copy" option on the context menu, and `Ctrl+C` also doesn't work if a History Query Item is selected.

Second, I would love to have a "fast recover" way like this:

- ME as an Azure Data Studio user
- WHEN I'm at Query Editor
- AND Double click at any Query History item
- THEN the selected query should appear at Query Editor at the current cursor position;

My setup:
![image](https://user-images.githubusercontent.com/5428523/68372631-8c812f80-0141-11ea-9586-f59ce32f2218.png)

![image](https://user-images.githubusercontent.com/5428523/68372661-999e1e80-0141-11ea-8807-1dd7d05f8066.png)

**Comment by Charles-Gagnon** [comment] 2019-11-07 16:03
Thanks for the suggestion! We've had a few asks for double click instead to open the query in a new query window - would you prefer your suggestion over that assuming we implemented the ctrl + c copy to copy the text from the selecting cell? (which you could then paste into an existing document)

**Comment by thiagolunardi** [comment] 2019-11-16 09:22
Hi @Charles-Gagnon 

That would be a great start, for sure. 

My expectation would be to double click and have it at cursor position at the editor. Maybe this behavior - double click to past at cursor position - could be toggled at settings.

**Comment by Charles-Gagnon** [comment] 2020-01-08 19:07
I'm going to close this as a dupe of #7437 to consolidate the issues we're tracking for this feature.

**Closed by Charles-Gagnon** 2020-01-08 19:07 UTC
Labels: Area - Query History, Enhancement, Triage: Done
