### ISSUE TITLE
Certain table names not returned by intellisense

### ISSUE THREAD

**Issue by agentwalker** [microsoft/azuredatastudio#24126] opened 2023-08-14 10:33 UTC
- Azure Data Studio Version: 1.46
- OS Version: Windows 11

Steps to Reproduce:

1 Create a table that has a name such as  EPDERTesting
2. Start writing a SQL query that looks like this

Select * from Testing

In SSMS the IntelliSense brings back the 'EPDERTesting' table.
In azure data studio the table is not returned.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment] 2023-08-14 15:38
Hi @agentwalker 

This is currently not supported, related enhancement request: https://github.com/microsoft/azuredatastudio/issues/18863
Does running "Refresh Intellisense Cache" command help refresh intellisense manually?

**Comment by cheenamalhotra** [comment] 2023-08-14 15:41
I will close this as duplicate of https://github.com/microsoft/azuredatastudio/issues/18863

**Closed by cheenamalhotra** 2023-08-14 15:41 UTC

**Comment by agentwalker** [comment] 2023-08-14 17:29
This isn't related too the issue you linked.
The example I gave was just to illustrate the table name needed to cause the issue.

You can have any existing table, is it has multiple uppercase characters at the start followed by lower. Entering the lower case characters first fails to find the table. It's the uppercase characters that cause the issue.

**Comment by agentwalker** [comment] 2023-08-14 17:31
Can this be reopened as ssms didn't have the same issue so using intellisense often misses tables.
