### ISSUE TITLE
not able to add azure account

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10733] opened 2020-06-04 18:08 UTC
<img width="234" alt="Screen Shot 2020-06-04 at 11 07 17 AM" src="https://user-images.githubusercontent.com/13777222/83794966-9c1f1300-a653-11ea-86a7-e0c1d1a13784.png">

<img width="464" alt="Screen Shot 2020-06-04 at 11 07 23 AM" src="https://user-images.githubusercontent.com/13777222/83794969-9cb7a980-a653-11ea-81cf-5fcdd777965a.png">

**Comment by aaomidi** [comment] 2020-06-04 23:52
Duplicate of #10734

**Closed by aaomidi** 2020-06-04 23:53 UTC
Labels: Area - Azure, Bug, Triage: Needed
