### ISSUE TITLE
Source control is getting froze when checking ddl changes 

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/azuredatastudio#15362] opened 2021-05-06 23:15 UTC
- Azure Data Studio Version:

Version: 1.28.0 (user setup)
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
Date: 2021-04-15T00:24:15.710Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create or edit DDL in any schema
2. Click file in file to verify changes

The app get froze and after a while I get the message:

![image](https://user-images.githubusercontent.com/33104726/117376284-a9f19f80-ae85-11eb-9df5-e75c8bebb64b.png)

After this I have to restart the app if I click the file in source control the issue keeps happening.
I got report from my team that this is also happening in their machines too.

There are also some errors in the app: [datastudio.log](https://github.com/microsoft/azuredatastudio/files/6438058/datastudio.log)
![image](https://user-images.githubusercontent.com/33104726/117376129-57b07e80-ae85-11eb-9047-d5ed335a2df4.png)

**Comment by Charles-Gagnon** [comment] 2021-05-10 15:39
Duplicate of #15180 - see that issue for instructions to revert to a working version until a build with the fix is released.

**Closed by Charles-Gagnon** 2021-05-10 15:39 UTC
