### ISSUE TITLE
Could not access subscriptions due to expired login refresh token

### ISSUE THREAD

**Issue by rchlkm** [microsoft/azuredatastudio#15976] opened 2021-07-02 00:22 UTC
- Azure Data Studio Version: 1.31.0
- OS Version: Windows_NT x64

On the SQL Migrations extension, my Azure subscriptions weren't populating caused by an expired login token. It looks like I last logged into my Microsoft account on ADS on 2021-02-09. Since it's been more than 90 days, the login token expired. 

There should be some form of communication letting me know I should re-login or why my subscriptions weren't loading.

Resolved this by removing my Microsoft account and logging in again.

Response error! - {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-02-09T19:27:38.3331129Z and was inactive for 90.00:00:00.\r\nTrace ID: {TRACE ID}\r\nCorrelation ID: {CORRELATION ID}\r\nTimestamp: 2021-07-01 23:04:41Z","error_codes":[700082],"timestamp":"2021-07-01 23:04:41Z","trace_id":{TRACE ID},"correlation_id":{CORRELATION ID},"error_uri":"https://login.microsoftonline.com/error?code=700082"} 

![image](https://user-images.githubusercontent.com/14362577/124203104-d1817480-da90-11eb-8e7c-d3e656a6f32e.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment] 2021-07-06 17:34
Duplicate of #14159

**Closed by Charles-Gagnon** 2021-07-06 17:34 UTC
