### ISSUE TITLE
New notebook shortcut (Alt + Windows + N) opening OneNote application instead of new notebook

### ISSUE THREAD

**Issue by JawaharlalMuthinni** [microsoft/azuredatastudio#13871] opened 2020-12-23 07:05 UTC
Issue Type: <b>Bug</b>

New Notebook shortcut is not working as expected (instead opening OneNote)
Below shown methods to open a new notebook.

Method 1: File > New Notebook (opening new ADS notebook) 
Method 2: **Alt + Windows + N** (opening OneNote application)

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.17763

**Comment by chlafreniere** [comment] 2021-01-06 05:25
Closing this as a dupe of #9829.

The keyboard shortcut can be customized by opening the command palette (F1) and typing in "keyboard shortcuts". It can be customized further by double clicking on the following row:

![image](https://user-images.githubusercontent.com/40371649/103732548-77e63480-4f9c-11eb-89d0-c24331b23665.png)

**Closed by chlafreniere** 2021-01-06 05:25 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
