### ISSUE TITLE
Unable to open stored procedure file in database project when name contains '@' maybe also other special characters

### ISSUE THREAD

**Issue by manfredwippel** [microsoft/azuredatastudio#17020] opened 2021-09-08 07:30 UTC
- Azure Data Studio Version: 1.32 (user setup)
- OS Version: Windows_NT x64 10.0.19043
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0

Steps to Reproduce:

1. Open database procject
2. contains a stored procedure with '@' in the name eg. test@info
3. open projects tab
4. name is displayed as test%40sel
5. Error occurs because test%40sel file cannot be found/opened
6. file can be opened in explorer tab
7. Build also fails - maybe due to this issue - no error code

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment] 2021-09-13 20:27
@manfredwippel I'm unable to repro this locally. I tried adding a stored proc with '@' in the name and was able to open the file and build the project.
![image](https://user-images.githubusercontent.com/31145923/133151590-0b263964-6f92-4677-8317-cf5e160eb61b.png)

Can you please share a screenshot of ADS with the error?

**Comment by manfredwippel** [comment] 2021-09-14 06:55
![image](https://user-images.githubusercontent.com/33145253/133209873-0c7c49db-c108-44a1-b5eb-43a6a7369774.png)

**Comment by manfredwippel** [comment] 2021-09-14 07:02
The project was reverse engineered from a database with SSDT 4 years ago and the @ was automatically replaced with %40 in the project file.  It works fine in Visual Studio.

Newly added procedures are added without encoding (@ instead of %40).
I could simply search and replcace %40 with @ in the project file.

**Comment by kisantia** [comment] 2021-09-14 21:23
Ah I see. Thanks for the clarification! We'll target fixing this in the upcoming releases.

**Comment by Andrewnt219** [comment] 2021-10-04 23:07
Hi @kisantia, I want to help with this issue. Can you tell me where in the codebase I should start looking at?

**Comment by kisantia** [comment] 2021-10-04 23:40
@Andrewnt219 we'd love to get your help on this issue! A good place to start would be in this readProjFile() function : https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-database-projects/src/models/project.ts#L110

**Comment by Andrewnt219** [comment] 2021-10-05 00:34
Thanks. I'll research it in the next few days, and come up with a solution if I can at the end of the week.

**Comment by Andrewnt219** [comment] 2021-10-08 22:06
Hi @kisantia, I was trying to set up the dev environment, but I'm stuck. I followed all the steps and installed all the things from the [wiki](https://github.com/Microsoft/azuredatastudio/wiki/How-to-Contribute). 

When I launched with preset "Launch ADS & Debug Renderer and Extension Host", it ran on port 5870, but just show a message "WebSockets request was expected". Do you know what I did wrong?

**Comment by kisantia** [comment] 2021-10-08 22:24
hmm I don't remember seeing that particular error before. A couple things to check:

- make sure yarn run watch is running and that both `[watch-extensions]` and `[watch-client]` are finished 
![image](https://user-images.githubusercontent.com/31145923/136630627-201f6d1f-0d22-44de-be19-7e3b4452c4f4.png)

- try running `./sql.bat` (or `./sql.sh` if not on windows) in the scripts folder and see if ADS launches, then launch "Attach to Extension Host" to debug the sql-database-projects extension. Hopefully this should narrow down if the problem is with launching ADS or with debugging. If it still isn't working, please share a screenshot of the error.

**Comment by Andrewnt219** [comment] 2021-10-13 05:56
Hi @kisantia, I tried all of them, lines by lines, but none seems to work. I might have misunderstood some steps, or my window has some setup that prevents the ADS from running (even when both `watch-client` and `watch-extensions` compiled successfully). 

Unfortunately, I cannot continue with the issue. Thanks so much for your helping me.

**Comment by kisantia** [comment] 2021-11-12 01:11
Closing with the workaround of find-replace any `%40`s that should be `@` in the sqlproj. This updated project should continue to work in SSDT and will be read correctly in ADS.

**Closed by kisantia** 2021-11-12 01:11 UTC
Labels: Bug, Area - SQL Project, Good First Issue
