### ISSUE TITLE
Azure Data Studio crashes after update to macOS Big Sur

### ISSUE THREAD

**Issue by jrlopezbluecarde** [microsoft/azuredatastudio#13429] opened 2020-11-16 12:09 UTC
- Azure Data Studio Version:

Steps to Reproduce:

After updating the OS of my Mac Book Pro to macOS Big Sur 11.0.1 I can not execute Azure Data Studio, because the Mac crashes as soon as it starts.

Do you plan any update of Azure Data Studio to be compatible with the new macOS?
May I do anythnig until the new version (i.e. changing the Mac configuration)?

Thanks in advance

**Comment by rgbattersby** [comment] 2020-11-17 17:14
This issue is also affecting me. As soon as I start Azure Data Studio version 1.24.0, my MacBook Pro crashes completely and restarts.

**Comment by jordang87** [comment] 2020-11-19 20:06
I can confirm Azure Data Studio 1.24 is crashing for me as well for both Catalina and Big Sur. Also looks like the publish date is off on the application
![image](https://user-images.githubusercontent.com/8516827/99718394-68ed0680-2a70-11eb-974a-1a7ab78ccdef.png)

**Comment by rgbattersby** [comment] 2020-11-19 21:03
I've tested a number of previous versions and have had to revert to 1.16, which is the only version I have found that doesn't cause a kernel panic when logging in.

**Comment by kburtram** [comment] 2020-11-23 20:37
We've had a few engineers on the dev team update to Big Sur and haven't been able to get an internal repro for this scenario.  Is there any additional information about the crash?  e.g. such as an error message or stack trace?

**Comment by rgbattersby** [comment] 2020-11-23 20:46
The crash happens specifically when I try and authenticate, and more specifically when the browser is accessing vscode-redirect.azurewebistes.net

I can provide the crash dump, if it helps. What is the best way to provide this?

**Comment by BrentOzar** [comment] 2020-12-19 16:53
After upgrading to Big Sur, I couldn't open Azure Data Studio anymore:
<img width="274" alt="Screen Shot 2020-12-19 at 9 50 03 AM" src="https://user-images.githubusercontent.com/245462/102694646-a237a400-41df-11eb-969a-20495a056fe4.png">

I'm the admin on my machine. Verified that it wasn't a permissions problem on the app, either - right-clicked on Azure Data Studio, went into Get Info, and it reported that I have read & write permissions:

<img width="263" alt="Screen Shot 2020-12-19 at 9 51 58 AM" src="https://user-images.githubusercontent.com/245462/102694684-ea56c680-41df-11eb-8641-a5e34cffe7c8.png">

My guess is that it has something to do with the additional extensions/stuff that ADS installs, like the PostgreSQL or Microsoft SQL Server extension.

**Comment by jordang87** [comment] 2020-12-19 19:01
After upgrading Cisco AMP to the latest release I could connect with integrated login but still crashed on MFA login. Then I upgraded Big Sur to 11.1 and now I can connect to DBs with MFA.

**Comment by kburtram** [comment] 2021-03-05 20:23
We haven't been able to repro widespread upgrade issues with ADS on Big Sur.  I'll close this out due to this.  If anyone is still experiencing issues, please open a new issue with details of the crash from the Developer console.  Thanks!

**Closed by kburtram** 2021-03-05 20:23 UTC
Labels: Area - Shell, Bug, Triage: Done, Triage: Postponed

**Comment by QiangZ** [comment] 2021-03-24 12:22
I have the same problem  with macOS catalina 10.15.7 @kburtram  where is the Developers console to create a new issue?
