### ISSUE TITLE
Python kernel fails to start with latest traitlets package (v5.10.0)

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#24443] opened 2023-09-15 14:18 UTC
- Azure Data Studio Version: 1.46.0-rc1
- OS Version: mac/windows

Steps to Reproduce:

1. Install latest traitlets package: `python3 -m pip install traitlets`
2. Open new notebook
3. Try to change kernel to Python 3

Error:
```
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last):
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\notebook\traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py", line 2009, in _resolve_string
    return import_item(string)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\utils\importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  File "c:\src\azuredatastudio\extensions\notebook\resources\pythonScripts\startNotebook.py", line 2, in <module>
    notebook.notebookapp.main()
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\jupyter_core\application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\config\application.py", line 1044, in launch_instance
    app = cls.instance(**kwargs)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\config\configurable.py", line 555, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py", line 1295, in __new__
    inst.setup_instance(*args, **kwargs)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py", line 1338, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py", line 1314, in setup_instance
    init(self)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\notebook\traittypes.py", line 226, in instance_init
    self._resolve_classes()
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\notebook\traittypes.py", line 238, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment] 2023-09-15 14:46
https://github.com/microsoft/azuredatastudio/issues/24436 has some extra info, including link to issue filed in notebook package repo. It's a dupe of this one though so I closed it - we will use this one for tracking going forward.

**Closed** 2023-09-18 13:22 UTC
Labels: Bug, Triage: Done, Approved

**Comment by Mengni0812** [comment] 2023-09-18 14:45
I solved this problem by:
pip uninstall traitlets
pip install traitlets==5.9.0

**Comment by Suraj-008** [comment] 2023-09-26 11:49
> I solved this problem by: pip uninstall traitlets pip install traitlets==5.9.0

**Comment by Suraj-008** [comment] 2023-09-26 11:50
@Mengni0812 
thanks it worked.

**Comment by kirubel-Biruk-Shiferaw** [comment] 2023-12-30 14:33
Thanks! It worked for me too.

**Comment by Sheminho** [comment] 2024-01-01 21:37
> I solved this problem by: pip uninstall traitlets pip install traitlets==5.9.0

U R a hero man, thanks that helped me too❤.

**Comment by muralimaradana** [comment] 2024-01-10 09:23
(base) PS C:\Users\hp> jupyter notebook
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\notebook\traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 2015, in _resolve_string
    return import_item(string)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\traitlets\utils\importstring.py", line 33, in import_item
    module = __import__(package, fromlist=[obj])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\jupyter_core\application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1073, in launch_instance
    app = cls.instance(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\traitlets\config\configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1292, in __new__
    inst.setup_instance(*args, **kwargs)
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1335, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1311, in setup_instance
    init(self)
  File "C:\ProgramData\anaconda3\Lib\site-packages\notebook\traittypes.py", line 226, in instance_init
    self._resolve_classes()
  File "C:\ProgramData\anaconda3\Lib\site-packages\notebook\traittypes.py", line 238, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'

**Comment by muralimaradana** [comment] 2024-01-10 09:24
error

**Comment by zuryVG** [comment] 2024-02-09 15:36
Si tienes anaconda lo que debes hacer es abrir el Powershell Prompt o la consola y ejecutar este: pip uninstall traitlets esperar a que cargue y luego este pip install traitlets==5.9.0 y volver a abrir jupyter y listo
