### ISSUE TITLE
Notebooks stays on status "Loading Kernels"

### ISSUE THREAD

**Issue by sanderstad** [microsoft/azuredatastudio#11633] opened 2020-08-04 06:30 UTC
Issue Type: <b>Bug</b>

I have a clean Windows 10 Professional VM containing the system install of ADS.

When I try to open an existing PowerShell Notebook It keeps the status on "Loading kernels" and never finishes. This is also the case when I try to create a new Notebook.

I first though this may have been due to some delay but I waited for over an hour to see if it would time out but it would not.

![image](https://user-images.githubusercontent.com/6154981/89260503-aa29e980-d62c-11ea-95ff-b9b32517645e.png)

I have tried removing the powershell_kernel and installing it again.

When I go to the url of the Jupyter service it does respond. I can open the notebook.

I have also tried this in the insiders edition of ADS. I have also tried installing the user installation version.

In a last resort I have rebuild the entire VM from scratch and only installed ADS but unfortunately no solution.

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by chlafreniere** [comment] 2020-08-04 18:09
Dupe of #11607. We're investigating currently.

**Closed by chlafreniere** 2020-08-04 18:09 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
