### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by slee-fdx** [microsoft/azuredatastudio#22294] opened 2023-03-10 14:59 UTC
Issue Type: <b>Bug</b>

Issues in order: 

1. Suddenly could not connect to an established connection using my Azure AD link. 

2. Tried logging out, but then couldn't log in to my account. 

3. Tried deleting my account, and can now not even add a new account. 

Error is: "TypeError: Cannot read properties of undefined (reading 'authLibrary')".  

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (12.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.12.0
import|Mic|1.5.4
profiler|Mic|0.12.2
sql-prompt|Red|0.2.11
vim|vsc|1.23.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment] 2023-03-10 16:37
@slee-fdx can you please take a look at this issue and see if any of the troubleshooting suggestion there help https://github.com/microsoft/azuredatastudio/issues/22227.  This looks like one of the errors reported there, so if you can collect diagnostic logs please post on that issue.

**Comment by kburtram** [comment] 2023-03-10 18:47
I'll close as duplicate of #22227 since we're track this same issue there.  Sorry for the inconvenience caused by this issue.

**Closed by kburtram** 2023-03-10 18:47 UTC
Labels: Bug, Area - Connection, Triage: Needed
