### ISSUE TITLE
While editing the markdown I cannot search for text in it

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#9742] opened 2020-03-26 00:05 UTC
Issue Type: <b>Bug</b>

Repro steps:
- Open a Notebook with a long markdown cell.
- Double click on the markdown cell to edit it.
- Try to search for some text to jump to it so that you can edit over there.

The notebook searches only in the markdown preview and scrolls to it. There is no way to search in the markdown while editing. This makes the editing experience unusable while working with lot's of markdown. 

The work around is to copy the markdown to some other editor like Notepad, edit there and paste it back in ADS.

I would expect find to be within the raw markdown while editing.

Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (a7dbb68f7d4b862d76e91284a619ed022e8b4745, 2020-03-23T06:17:26.698Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment] 2020-03-26 00:18
@qifahs, @MaddyDev has a PR out for this: https://github.com/microsoft/azuredatastudio/pull/9685

I believe this is a dupe of #9196. Is that correct?

**Closed** 2020-03-31 00:53 UTC
Labels: Area - Notebooks, Bug, Impact: Live site
