### ISSUE TITLE
The following query produces a conversion overflow but is fine in SSMS

### ISSUE THREAD

**Issue by stecydube** [microsoft/azuredatastudio#10518] opened 2020-05-20 12:19 UTC
Issue Type: <b>Bug</b>

SELECT ((1-0.0012408944280) * (1-0.010457430943) * (1-0.023635849543048)) - 1

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.1.0
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment] 2021-09-22 21:47
This appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/10541.

**Closed by kburtram** 2021-09-22 21:47 UTC
Labels: Bug, Area - Query Editor, Triage: Done
