### ISSUE TITLE
Connected server is disconnected after open a file folder

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3558] opened 2018-12-10 23:58 UTC
Issue Type: <b>Bug</b>

1. Connect to servers. 
![image](https://user-images.githubusercontent.com/43652751/49769194-1c013280-fc94-11e8-8433-8707cd0886d9.png)
2. Open file folder from File menu.
3. We can see server view is refreshed and all servers are disconnected.
![image](https://user-images.githubusercontent.com/43652751/49769253-510d8500-fc94-11e8-9802-5e8306c399cd.png)

Expected:
All connected servers should be connected.

Azure Data Studio version: azuredatastudio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T22:09:47.695Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (46.81GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.1

</details>

**Comment by YurongHe** [comment] 2018-12-11 00:01
The second issue: we should see folder content. Instead of refreshed server list.

**Comment by kburtram** [comment] 2018-12-11 19:53
This looks like a duplicate of https://github.com/Microsoft/azuredatastudio/issues/991.

**Closed by kburtram** 2018-12-11 19:53 UTC
