### ISSUE TITLE
 create SQL server 2019 big data cluster- running for more than 24 hrs

### ISSUE THREAD

**Issue by dheerr** [microsoft/azuredatastudio#15425] opened 2021-05-12 13:09 UTC
I am trying to create Big Data cluster through Azure data Studio and it  ran well until AKS cluster creation. It's executing " create SQL server 2019 big data cluster" for more than 24 hours and still running. Any help would be appreciated. Thanks
![image](https://user-images.githubusercontent.com/55467539/117979891-6376c780-b301-11eb-98d0-b0a6a542f550.png)

**Comment by Charles-Gagnon** [comment] 2021-05-12 16:12
You can take a look at https://docs.microsoft.com/en-us/sql/big-data-cluster/cluster-troubleshooter-notebooks?view=sql-server-ver15 to see if there's anything there that would help you. I see that you have two pods still listed as pending - I would start there and look through the logs to see what they're waiting on.

Seeing as this is a BDC specific issue though I'm going to close this issue - you can check out https://feedback.azure.com/forums/927307-sql-server-big-data-clusters and submit an issue there as well if you're still unable to determine what the problem is.

**Closed by Charles-Gagnon** 2021-05-12 16:12 UTC
