### ISSUE TITLE
Copy value from field not working

### ISSUE THREAD

**Issue by patricsjoo** [microsoft/azuredatastudio#24503] opened 2023-09-22 12:38 UTC
Type: <b>Bug</b>

I can no longer select a field in results and copy the value.
Either with ctrl + c or righ click

Azure Data Studio version: azuredatastudio 1.46.0 (39449bbe88a0bc4092c9b205cad10d0a556beffd, 2023-09-16T01:40:10.706Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (7.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|1.0.0
azuredatastudio-postgresql|Mic|0.5.0
dacpac|Mic|1.14.0
datavirtualization|Mic|1.13.1
import|Mic|1.5.5
powershell|ms-|2022.7.2
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.3.1
mongodb-vscode|mon|0.9.3

</details>

**Comment by cheenamalhotra** [comment] 2023-09-22 17:52
@patricsjoo 

Please upload logs so we can investigate the issue.

**Comment by kisantia** [comment] 2023-09-22 18:00
@patricsjoo can you please share more details on how to repro this?

This is what I tried: right click copy first, then cmd + c and both are working for me in the 1.46 release
![copy](https://github.com/microsoft/azuredatastudio/assets/31145923/f8fdb819-3996-4841-98e9-1d9ccbc9ea48)

**Comment by jhubsharp** [comment] 2023-09-22 23:20
There are three different issues tracking this that I know of. I opened #24476 and #24043 was opened by someone else. They each seem to be nuanced to particulars with the OS. 

@kisantia On our team the person using ADS on a Mac has had no issues though all of us on Windows and Linux have been broken for about a month.

**Comment by cheenamalhotra** [comment] 2023-09-23 06:14
Hi @patricsjoo 

As mentioned here: https://github.com/microsoft/azuredatastudio/issues/24476#issuecomment-1732225384 could you please verify your settings and confirm if recommendation helps solve the problem?

We will look into fixing the behaviour to respect 64-bit integer values for `number` types.

**Comment by patricsjoo** [comment] 2023-09-25 09:02
Hi

> Hi @patricsjoo
> 
> As mentioned here: [#24476 (comment)](https://github.com/microsoft/azuredatastudio/issues/24476#issuecomment-1732225384) could you please verify your settings and confirm if recommendation helps solve the problem?
> 
> We will look into fixing the behaviour to respect 64-bit integer values for `number` types.

When I changed my text-size to another value. It started to work again !

**Comment by cheenamalhotra** [comment] 2023-09-25 17:54
I'll close this as duplicate of #24476 and will address the setting there.

**Closed by cheenamalhotra** 2023-09-25 17:54 UTC
Labels: Bug, Area - Query Editor, Needs More Info, Triage: Done
