### ISSUE TITLE
Can't copy or drag and drop objects from server pane into Query window

### ISSUE THREAD

**Issue by ottadvantage** [microsoft/azuredatastudio#296] opened 2017-12-06 16:58 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Clicking twice on an object (table, sp, etc) in SSMS doesn't allow you to copy the name of the file (like a rename in file explorer) doesn't let you copy the name of the object (to prevent spelling errors)
2. Similarly, you can't select and drag an object from Server pane into query window to copy the name

**Comment by psimoneau22** [comment] 2017-12-16 13:39
This would also be useful when dragging the columns list for a table into the query window for example when creating a query to select all columns from a table without using select *

**Comment by jasonhorner** [comment] 2019-05-26 06:51
This is a huge blocker for me to make the full time switch from ssms.

**Comment by SQLvariant** [comment] 2019-10-16 19:28
I would really like to see this suggestion get implemented.  When it is implemented, I hope that we will be able to drag an object-name from Object Explorer, to a text pane, regardless of what language that script is being written in (.SQL, .JSON, .PS1, etc...)

**Comment by rbharathkumar** [comment] 2020-05-13 08:38
Truly the only issue that keeps me from switching from SSMS. Would be great to have this drag option for a quick querying experience.

**Comment by kburtram** [comment] 2020-06-04 02:13
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/3630.  This is actively being worked on.

**Closed by kburtram** 2020-06-04 02:13 UTC
Labels: Area - Data Explorer, Area - Query Editor, Enhancement, Triage: Postponed
