### ISSUE TITLE
Database trees no longer expand after recent update

### ISSUE THREAD

**Issue by dbainscp** [microsoft/azuredatastudio#20472] opened 2022-08-24 23:46 UTC
Issue Type: <b>Bug</b>

I just updated Azure Data Studio to 1.39.0 and now none of my database connections show the tree view with tables, views etc. None of them will expand. I click on them, get a spinning cursor while it connects, then nothing is displayed. 

Azure Data Studio version: azuredatastudio 1.39.0 (9fdb2161d49b4d4ab6798809faa042a898ca2eae, 2022-08-20T01:46:47.606Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (2.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.0

</details>

**Comment by cssuh** [comment] 2022-08-25 00:31
Hi @dbainscp, is this for an azure DB or a local DB?

**Comment by woutkroon** [comment] 2022-08-25 12:23
I encounter the same issues, although it does seem to work for some servers if given enough time. The SQL server instances are all  local on my computer (SQL2017/2019) or on premise (running on dedicated DB servers at our office). None of them are Azure DBs.

**Comment by cssuh** [comment] 2022-08-25 20:43
@dbainscp could you also include screenshots of the issue?

**Comment by dbainscp** [comment] 2022-08-25 21:52
Here is the zipped logging folder & the console logs:

[exthost.zip](https://github.com/microsoft/azuredatastudio/files/9428453/exthost.zip)
[vscode-app-1661464134991.log](https://github.com/microsoft/azuredatastudio/files/9428454/vscode-app-1661464134991.log)

**Comment by dbainscp** [comment] 2022-08-25 21:54
And here is a screen shot of my connections. The one in the red box should be showing the Tree  below it:
![NoTree](https://user-images.githubusercontent.com/35049140/186775748-2af992f7-f001-4195-8911-36eca1ab8922.jpg)

**Comment by dbainscp** [comment] 2022-08-25 21:59
And here is the screen shot. The connection with the red box should be showing the tree but it's not.
![NoTree](https://user-images.githubusercontent.com/35049140/186776527-495ff76a-22d4-49f4-b304-7f49ac4b2618.jpg)

**Comment by cssuh** [comment] 2022-08-26 21:00
Hi @dbainscp , is this happening for all your servers?  Have you tried closing and restarting ADS? seems like that might have fixed it for @woutkroon.  Have you been able to successfully connect to these servers before?

**Comment by kburtram** [comment] 2022-08-26 21:05
@dbainscp the log files don't appear to show any errors, or even attempts to connect.  Could you please check the Help->Developer Tools->Console UI after repro'ing this bug to confirm there are no error messages there?   All the `DevTools failed to load source map` errors can be ignored, the relevant errors should say something about Connections or Object Explorer sessions.  Thanks!

**Comment by dbainscp** [comment] 2022-08-26 21:19
> Hi @dbainscp , is this happening for all your servers? Have you tried closing and restarting ADS? seems like that might have fixed it for @woutkroon. Have you been able to successfully connect to these servers before?

I have logged out & in multiple times over the past three days. I even uninstalled & reinstalled, same thing. This is happening on every one of my servers, all of which are SQL server. Thanks -

**Comment by dbainscp** [comment] 2022-08-26 21:22
> @dbainscp the log files don't appear to show any errors, or even attempts to connect. Could you please check the Help->Developer Tools->Console UI after repro'ing this bug to confirm there are no error messages there? All the `DevTools failed to load source map` errors can be ignored, the relevant errors should say something about Connections or Object Explorer sessions. Thanks!

Going back into the console, these are the only two errors I see:

 Failed to load resource: net::ERR_FILE_NOT_FOUND

ERR [Extension Host] (node:30544) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `azuredatastudio --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:30544) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `azuredatastudio --trace-deprecation ...` to show where the warning was created)
log.

**Comment by kburtram** [comment] 2022-08-26 21:39
@dbainscp thanks for the additional information!  This is unusual as there should be various messages generated when trying to establish the connection, which could provide additional context on what's happening.  Could you please try create a new connection to one of the servers using the Connection Dialog and see if that generates an error message?  Also, is the product basically working in other areas that don't require a connection, such as an offline SQL file or a Notebook file?

**Comment by dbainscp** [comment] 2022-08-26 22:09
OK this g

> @dbainscp thanks for the additional information! This is unusual as there should be various messages generated when trying to establish the connection, which could provide additional context on what's happening. Could you please try create a new connection to one of the servers using the Connection Dialog and see if that generates an error message? Also, is the product basically working in other areas that don't require a connection, such as an offline SQL file or a Notebook file?

OK this gets weirder. When I launch ADS, I can connect to *one* of my databases. The tree won't expand, but I can open a new query and get data from that connection. However, only *one* connection will work at a time. Any second connection I click on spins endlessly. I can exit ADS then launch it again, and successfully launch the connection that just spun...as long as it's the first one I try.

I tried creating a new connection and as long as I haven't tried to connect to one of my existing servers in the same session, the connection creates successfully  *and* the tree works properly. Go figure, makes no sense to me. If I try and create a second connection, same thing, it times out I guess and I have to exit Azure & then I can create a second one that works correctly. With my new connections, I can connect to more than one at a time. Very odd.

**Comment by kburtram** [comment] 2022-08-26 22:31
This weird.  It sounds like something is causing the SQL Tools Service to get in a bad state and be unable to handle future messages.  You may try to restore back to "1st-launch" state, which would clear out everything in the application cache using a procedure such as following.

1. Run ADS and backup your connection metadata and server groups from the user settings file.  For example, open the "Open Settings (JSON)" file and copy the ` "datasource.connectionGroups"` and ` "datasource.connections"` properties to a temporary file.  Close ADS.
2. Delete the application cache at `%APPDATA%\azuredatastudio`
3. Run ADS and restore your connection metadata.  Restart ADS.  Backup/restore connection metadata is option but would save the hassle to recreate.

If that doesn't work, please verify that the `Mssql: Tracing Level` is set to `All` in the user settings and try to reproduce the error.  Then close ADS.  Then open the newest folder in `%APPDATA%\azuredatastudio\logs`, specifically the `exthost1\Microsoft.mssql\sqltools.log` file and check for any application errors/exceptions.  Please paste the last several events logged in that file as it could provide an idea if the component was behaving normally.

Thanks for helping investigating and sorry for the inconvenience caused by this bug!

**Comment by dbainscp** [comment] 2022-08-26 22:54
> This weird. It sounds like something is causing the SQL Tools Service to get in a bad state and be unable to handle future messages. You may try to restore back to "1st-launch" state, which would clear out everything in the application cache using a procedure such as following.
> 
> 1. Run ADS and backup your connection metadata and server groups from the user settings file.  For example, open the "Open Settings (JSON)" file and copy the ` "datasource.connectionGroups"` and ` "datasource.connections"` properties to a temporary file.  Close ADS.
> 2. Delete the application cache at `%APPDATA%\azuredatastudio`
> 3. Run ADS and restore your connection metadata.  Restart ADS.  Backup/restore connection metadata is option but would save the hassle to recreate.
> 
> If that doesn't work, please verify that the `Mssql: Tracing Level` is set to `All` in the user settings and try to reproduce the error. Then close ADS. Then open the newest folder in `%APPDATA%\azuredatastudio\logs`, specifically the `exthost1\Microsoft.mssql\sqltools.log` file and check for any application errors/exceptions. Please paste the last several events logged in that file as it could provide an idea if the component was behaving normally.
> 
> Thanks for helping investigating and sorry for the inconvenience caused by this bug!

I'm not seeing any errors in that log file, at least anything that jumps out ast me. I discovered something accidentally though that also makes no sense. If I have the settings.json file open and on the connection section, when I click on a connection, I get a pop-up that says "unable to write into user settings because the file has unsaved changes. Please save the user settings file first and then try again." If I click save & retry, then try that connection again, it connects & the tree pops up. However, it's short-lived. Exiting ADS & relaunching - the connection still doesn't exhibit the tree.

**Comment by woutkroon** [comment] 2022-08-26 23:13
Been busy all day preparing for my upcoming holidays, but just read up until this point. After reading @dbainscp 's comments, I got curious and had another look.

It seems that I spoke too soon when I said that the issue is resolved for me. When I run ADS, and expand the first (topmost, but not sure if that matters) server connection, the tree for that connection is successfully loaded and I can see the database instances etc. However, when I try to expand another server connection, the issue is still there. The second connection did turn green (indicating the connection is established), but the tree does not expand. Every connection after the second just gives me the progress indicator:

![image](https://user-images.githubusercontent.com/15102012/187001708-453f3ab9-87a3-4f34-9aaa-89aa548363dd.png)

I won't be able to provide more info for the next couple of weeks, because of my absence from work.

**Comment by kburtram** [comment] 2022-08-27 03:18
I was able to reproduce this in a different environment when connecting to a SQL Server instance over a slower VPN connection.  From what I can tell this appears related to a change https://github.com/microsoft/sqltoolsservice/commit/08c74be51feb0ae1f04652a13fe3dcebe9cf70c6 that updates the STS message dispatcher resulting in out-of-order/dropped events in this situation.  I've posted a PR to revert that change and will try to get an insiders build out for confirmation of the proposed fix.  A private version of STS with this change resolved the issue in my environment.

**Comment by dbainscp** [comment] 2022-08-29 14:48
> I was able to reproduce this in a different environment when connecting to a SQL Server instance over a slower VPN connection. From what I can tell this appears related to a change [microsoft/sqltoolsservice@08c74be](https://github.com/microsoft/sqltoolsservice/commit/08c74be51feb0ae1f04652a13fe3dcebe9cf70c6) that updates the STS message dispatcher resulting in out-of-order/dropped events in this situation. I've posted a PR to revert that change and will try to get an insiders build out for confirmation of the proposed fix. A private version of STS with this change resolved the issue in my environment.

Thanks very much for the update, I appreciate it.

**Comment by louwill** [comment] 2022-08-30 12:29
Same problem.  Downgrading to 1.38 resolved the problem.

**Comment by kburtram** [comment] 2022-08-30 15:11
@dbainscp @louwill today's insider build has an update that we expect to resolve this issue.  We are planning to release a hotfix today or tomorrow pending test sign-off.  If possible, could you please test the insider build in your repro environment to confirm that the update fixes the problem?  Thanks!  https://azuredatastudio-update.azurewebsites.net/latest/win32-x64-user/insider

**Comment by dbainscp** [comment] 2022-08-30 15:29
> @dbainscp @louwill today's insider build has an update that we expect to resolve this issue. We are planning to release a hotfix today or tomorrow pending test sign-off. If possible, could you please test the insider build in your repro environment to confirm that the update fixes the problem? Thanks! https://azuredatastudio-update.azurewebsites.net/latest/win32-x64-user/insider

I installed the insider build on my test box and it appears to be working correctly. I have five DB connections and all of them will expand the tree. I tried several times, closing & reopening and it was still working correctly. I look forward to the hotfix, thanks for the quick turn around :)

**Comment by Charles-Gagnon** [comment] 2022-08-30 21:22
The hotfix was just released, so please update to the latest (1.39.1) and if you still see this issue let us know!

**Closed by Charles-Gagnon** 2022-08-30 21:22 UTC
Labels: Bug, Area - Object Explorer, Triage: Done, Approved

**Comment by louwill** [comment] 2022-08-30 22:11
> The hotfix was just released, so please update to the latest (1.39.1) and if you still see this issue let us know!

Hotfix worked for me! Thanks for the quick turnaround!

**Comment by dbainscp** [comment] 2022-08-30 22:31
Installed the hotfix and everything is working correctly now. Thanks for the quick response, I appreciate it!


David Bains

Analyst/Programmer, Enterprise Application Engineering

Information Technology Services

Cal Poly, San Luis Obispo, CA



Office: 805-756-5849

tech.calpoly.edu<https://tech.calpoly.edu/>

________________________________

**Comment by alanrenmsft** [comment] 2022-10-07 21:26
@dbainscp Did you enable the setting `mssql.parallelMessageProcessing` when you ran into the issues/.

**Comment by dbainscp** [comment] 2022-10-11 07:20
They are all local, SQL Server databases.

Thanks -

David Bains
Analyst/Programmer, Enterprise Application Engineering
Information Technology Services
Cal Poly, San Luis Obispo, CA

Office: 805-756-5849
tech.calpoly.edu<https://tech.calpoly.edu/>

**Comment by alanrenmsft** [comment] 2022-12-14 22:36
Hi @dbainscp, Previously, we rolled back some changes due to this issue and now we have  re-implemented it, we need you help do some testing using the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) to see whether the issue still reproduces. Appreciate the help.

@caohai FYI.
