### ISSUE TITLE
profiler stop not working

### ISSUE THREAD

**Issue by ashimg** [microsoft/azuredatastudio#21120] opened 2022-11-05 20:48 UTC
Issue Type: <b>Bug</b>

After running sql server profiler to find queries/processes having high resource usage and hitting 'stop' to stop profiler itself does not stop it. The 'stop' button is still active as well as 'pause' and it does not stop.

Extension version: 0.11.0
Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 5|
|Memory (System)|32.00GB (2.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alanrenmsft** [comment] 2022-11-07 18:33
@ashimg what kind of server were you connecting to? how many records were there in the profiler? were you able to reproduce it consistently?

**Comment by SakshiS-harma** [comment] 2023-08-22 19:39
Hey @ashimg , are you still hitting this issue with the latest version of Profiler? Can you give it a try? It should ideally be working. Thanks!

**Comment by SakshiS-harma** [comment] 2023-09-08 19:22
@ashimg Just checking if you got a chance to test the issue, and if you are still seeing it in the latest version.

**Comment by SakshiS-harma** [comment] 2023-10-02 19:52
@ashimg Closing this issue because profiler is working as expected at my end. Please re-open the issue if you are still facing this problem.

**Closed by SakshiS-harma** 2023-10-02 19:52 UTC
Labels: Bug, Needs More Info, Area - SQL Profiler, Triage: Done, Needs Logs
