### ISSUE TITLE
Import Wizard - Changing data type time->int results in error

### ISSUE THREAD

**Issue by mjk5182** [microsoft/azuredatastudio#6594] opened 2019-08-05 18:12 UTC
I get the non-descriptive "Error inserting data into table" error when I change the data type from what ADS Import assumes (time) to the data type it actually is (integer). 

### Repro steps:
1. Create a CSV file where one of the columns only contains 5-digit integers (I assume this is the case for 6-digit as well). 
Example: 
Id,FilmType_id,CanisterBarcode
10076,2,169BZJ
10077,2,159BZI
10078,2,157BZG
10079,2,159AYG
10080,2,169BZJ
10081,2,169BZJ

2. Select this CSV file in the ADS Import plugin
3. Observe the assumed column data types
![ItThinksItIsTime](https://user-images.githubusercontent.com/10965170/62485323-68046880-b78a-11e9-965e-2f8b57bd43a5.png)
4. Change the Id column from time data type to int
5. Import the data (which will fail)

### Notes:
1. I tried importing the data into the database without changing the data types and it works just fine inserting the time data type, so it is not a permissions issue connecting to the target database or anything like that.
2. I inserted a dummy record into the CSV with a 1-digit integer for the Id column and it now interprets the column as smallint. This works, but should not be necessary.

**Comment by aaomidi** [comment] 2019-10-08 01:00
@mjk5182 I've updated the import extension where you should be getting more error messages. These changes will be included in future insiders builds (24-48 from this comment). Hopefully that will give you more context on whats breaking and you can update us as well.

**Comment by aasimkhan30** [comment] 2020-09-21 21:23
Cannot reproduce the error. Closing this issue for now

**Closed by aasimkhan30** 2020-09-21 21:23 UTC
Labels: Area - SQL Import, Bug, Triage: Done
