### ISSUE TITLE
Notebook cells don't have horizonal scroll bars

### ISSUE THREAD

**Issue by ecassidy-etc** [microsoft/azuredatastudio#24122] opened 2023-08-11 16:07 UTC
Type: <b>Bug</b>

The notebook cells don't have horizonal scroll bars.

Azure Data Studio version: azuredatastudio-insiders 1.46.0-insider (2d1be1b330274681fbe3a89b29c3b133f203c158, 2023-08-10T05:35:33.036Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (40 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.89GB (18.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azuredatastudio-postgresql|Mic|0.5.0
profiler|Mic|0.14.0
schema-compare|Mic|1.20.0
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|1.2.0
azdata-sanddance|msr|4.1.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by lucyzhang929** [comment] 2023-08-11 21:09
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/21145. Please enable word wrap in settings as a workaround.

**Closed by lucyzhang929** 2023-08-11 21:09 UTC
