### ISSUE TITLE
Connection to SQL-Server under docker container not accesible

### ISSUE THREAD

**Issue by redelapena** [microsoft/azuredatastudio#9189] opened 2020-02-18 16:50 UTC
Issue Type: <b>Bug</b>

After entering connection details and clicking Connect following message shows after 30 seconds (aprox):

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

SQL-S container is up & running: 

iMac-RDA01:bin rdelapena$ docker ps -a
CONTAINER ID    IMAGE                                         COMMAND                     CREATED         STATUS            PORTS                                NAMES
9cfb335be69d   microsoft/mssql-server-linux   "/opt/mssql/bin/sqls…"   4 weeks ago   Up 7 minutes    0.0.0.0:1433->1433/tcp   sql_server_dev

Accesible with terminal:

iMac-RDA01:bin rdelapena$ mssql -u sa -p pwd
Connecting to localhost...done

sql-cli version 0.6.2
Enter ".help" for usage hints.
mssql> .help
command  description                                    
----------  ------------------------
.help           Shows this message ...

Azure Data Studio version: Azure Data Studio 1.12.0 (f0b6180e15f455ccf9e8112b407a6aa8c5399fe9, 2019-10-01T19:32:03.347Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-02-18 17:11
Thanks for the report @redelapena - I'm going to close this as a dupe of #9116. We'll update that if we have any further information.

**Closed by Charles-Gagnon** 2020-02-18 17:11 UTC
Labels: Area - Connection, Bug, Triage: Needed
