### ISSUE TITLE
restore wizard not able to find files

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#5038] opened 2019-04-15 22:56 UTC
- Azure Data Studio Version: 1.5.2

Steps to Reproduce:

1. Try to restore a database from a file using the GUI, get this error
![image](https://user-images.githubusercontent.com/28786161/56170544-ccf74100-5f96-11e9-865a-412bed6684d2.png)

**Comment by kburtram** [comment] 2019-05-02 16:33
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/4767.

**Closed by kburtram** 2019-05-02 16:33 UTC
Labels: Area: Backup\Restore, Bug
