### ISSUE TITLE
Server Groups ordering

### ISSUE THREAD

**Issue by AhsenBaig** [microsoft/azuredatastudio#1275] opened 2018-04-26 15:49 UTC
- SQL Operations Studio Version: 
Version 0.28.6
Commit 3abbc8fd9713cdf847dcde703402d10a09eaa4ec
Date 2018-04-24T21:19:12.047Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Create two or more server groups and then try to rearrange them in a different order. You can put groups within groups which is fine but you can't reorder the primary groupings.

**Comment by kburtram** [comment] 2018-04-30 16:37
We plan to add this basic functionality to the Server viewlet in an upcoming release.  In the meantime, the workaround is to reorder the group definitions in the settings file.

**Comment by anthonydresser** [comment] 2018-07-18 23:11
This feature might be a larger than we think. The vscode tree doesn't easily give access to top/bottom in the drag call back, but just the target. So this would probably mean a large change to the tree drap/drop code.

**Comment by CodeSeraph** [comment] 2019-05-09 15:29
> 
> 
> We plan to add this basic functionality to the Server viewlet in an upcoming release. In the meantime, the workaround is to reorder the group definitions in the settings file.

Has this enhancement been done? The release from today still doesn't seem to have server group reordering by drag n drop..

**Comment by abist** [comment] 2021-04-23 20:46
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/167

**Closed by abist** 2021-04-23 20:46 UTC
Labels: Area - Data Explorer, Enhancement
