### ISSUE TITLE
Notebooks have strange behavior when path contains '%20'

### ISSUE THREAD

**Issue by dtate22** [microsoft/azuredatastudio#10259] opened 2020-05-04 16:56 UTC
Issue Type: <b>Bug</b>

On my machine, when I run a SQL statement it fails consistent.
- I have a brand new machine 

Rendering is failing for all SQL at various different points...
- If I re-open a SAVED NOTEBOOK mostly

I've installed the tool 5 or 6 times various versions.

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aaomidi** [comment] 2020-05-04 19:06
Hi! Do you have more information and context on what kind of queries are breaking for you? Any information, even if trivial, might help us root cause this problem :)

**Comment by dtate22** [comment] 2020-05-04 19:17
Select * from dbo.account

Simple query…

  *   The problem is on a new computer
     *   Either the login to SQL Server through SQL Server MFA (third party verification) is failing
     *   Or something else
  *   Next the render fails – either login or something else
  *   Once this happens, my Azure Data Studio is toast until Icreate a brand new notebook

I’m available to speak if you need more information – just let me know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dtate22** [comment] 2020-05-04 21:03
Render File: (no problem)

  *   When I open a Notebook the first time, everything is good
  *   SQL executes – no problem
C:\Users\Derrick.Tate\AppData\Roaming\azuredatastudio\logs\20200504T165621\renderer1.log<command:workbench.action.openLogsFolder>


<< file is empty >>


[cid:image002.png@01D62235.F9D75C20]



When I save the notebook.

  *   Close Azure Data Studio
  *   Open Azure Data Studio
  *   Open up the Saved Notebook file
  *   Execute the SQL Cell
  *   Below is what my Render File looks like – with exceptions
C:\Users\Derrick.Tate\AppData\Roaming\azuredatastudio\logs\20200504T165621\renderer1.log<command:workbench.action.openLogsFolder>

[2020-05-04 16:56:45.167] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458
[2020-05-04 16:56:45.168] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458
[2020-05-04 16:56:45.168] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458
[2020-05-04 16:56:46.405] [renderer1] [info] Creating new connection notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb
[2020-05-04 16:56:46.405] [renderer1] [info] Adding connection notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb
[2020-05-04 16:56:46.405] [renderer1] [info] Successfully added connection notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb
[2020-05-04 16:56:46.405] [renderer1] [info] Creating new connection untitled:notebook-editor-0
[2020-05-04 16:56:46.405] [renderer1] [info] Adding connection untitled:notebook-editor-0
[2020-05-04 16:56:46.405] [renderer1] [info] Successfully added connection untitled:notebook-editor-0
[2020-05-04 16:56:46.884] [renderer1] [error] OnConnectionComplete but no connection found 'notebook:c:\TempREPOdel\EMA Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458,notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb,untitled:notebook-editor-0]
[2020-05-04 16:56:46.893] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at e.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2225:841) [<root>]
    at e.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5655:786) [<root>]
    at e.$onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4930:977) [<root>]
    at e._doInvokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5032:707) [<root>]
    at e._invokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5032:399) [<root>]
    at e._receiveRequest (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5031:59) [<root>]
    at e._receiveOneMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5029:908) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5028:136 [<root>]
    at e.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:67) [<root>]
    at fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:576:470) [<root>]
    at t.PersistentProtocol._receiveMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:580:921) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:578:67 [<root>]
    at e.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:67) [<root>]
    at g.acceptChunk (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:574:17) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:573:393 [<root>]
    at Socket.t (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:584:332) [<root>]
    at Socket.ZoneTask.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48) [<root>]
    at Socket.emit (events.js:203:13) [<root>]
    at addChunk (_stream_readable.js:295:12) [<root>]
    at readableAddChunk (_stream_readable.js:276:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:210:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) [<root>]






Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Derrick Tate live<mailto:dtate22@live.com>
Sent: Monday, May 4, 2020 3:17 PM
To: microsoft/azuredatastudio<mailto:reply@reply.github.com>; microsoft/azuredatastudio<mailto:azuredatastudio@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>; Derrick Tate<mailto:Derrick.Tate@outlook.com>; Derrick Tate live<mailto:dtate22@live.com>
Subject: RE: [microsoft/azuredatastudio] This is driving me crazy! (#10259)

Select * from dbo.account

Simple query…

  *   The problem is on a new computer
     *   Either the login to SQL Server through SQL Server MFA (third party verification) is failing
     *   Or something else
  *   Next the render fails – either login or something else
  *   Once this happens, my Azure Data Studio is toast until Icreate a brand new notebook

I’m available to speak if you need more information – just let me know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aaomidi** [comment] 2020-05-04 21:25
Thank you!

**Comment by dtate22** [comment] 2020-05-05 18:13
Hey Amir,  ( MY PROBLEM is now resolved! )

I figure out – what I believe the problem is or was.

I have a laptop where Azure Data Studio runs 100% correct.

On a new PC it didn’t run, it had the weird behavior below.
So, today, I went to my PC and compared

  *   Azure Data Studio to see what extensions I had installed
  *   VS Code to see what extensions that I had installed

I made sure all extensions were installed to be the same and everything started working 100% on my new PC.

What I believe the problem is or was, I didn’t have Python installed in VS code.

  *   The other extensions I don’t think were a big deal, but I have the following extensions just in case you want to know to help your troubleshooting:
     *   Python
     *   Java Test
     *   Azure
     *   SQL Server (mssql)
     *   PowerShell
     *   Angular
     *   Docker
     *   Jupyter
     *   Npm
     *   Groovy
     *   C#
     *   Azure Functions
     *   Azure Account

My problem is resolved, fyi


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Derrick Tate<mailto:derrick.tate@outlook.com>
Sent: Monday, May 4, 2020 5:03 PM
To: microsoft/azuredatastudio<mailto:reply@reply.github.com>; microsoft/azuredatastudio<mailto:azuredatastudio@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>; Derrick Tate live<mailto:dtate22@live.com>
Subject: RE: [microsoft/azuredatastudio] This is driving me crazy! (#10259)


Render File: (no problem)

  *   When I open a Notebook the first time, everything is good
  *   SQL executes – no problem
C:\Users\Derrick.Tate\AppData\Roaming\azuredatastudio\logs\20200504T165621\renderer1.log<command:workbench.action.openLogsFolder>


<< file is empty >>


[cid:image002.png@01D622E7.4736C5D0]



When I save the notebook.

  *   Close Azure Data Studio
  *   Open Azure Data Studio
  *   Open up the Saved Notebook file
  *   Execute the SQL Cell
  *   Below is what my Render File looks like – with exceptions
C:\Users\Derrick.Tate\AppData\Roaming\azuredatastudio\logs\20200504T165621\renderer1.log<command:workbench.action.openLogsFolder>

[2020-05-04 16:56:45.167] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458
[2020-05-04 16:56:45.168] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458
[2020-05-04 16:56:45.168] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458
[2020-05-04 16:56:46.405] [renderer1] [info] Creating new connection notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb
[2020-05-04 16:56:46.405] [renderer1] [info] Adding connection notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb
[2020-05-04 16:56:46.405] [renderer1] [info] Successfully added connection notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb
[2020-05-04 16:56:46.405] [renderer1] [info] Creating new connection untitled:notebook-editor-0
[2020-05-04 16:56:46.405] [renderer1] [info] Adding connection untitled:notebook-editor-0
[2020-05-04 16:56:46.405] [renderer1] [info] Successfully added connection untitled:notebook-editor-0
[2020-05-04 16:56:46.884] [renderer1] [error] OnConnectionComplete but no connection found 'notebook:c:\TempREPOdel\EMA Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EMPDB00|server:empsql01.database.windows.net|user:Derrick.Tate@englemartin.com|databaseDisplayName:EMPDB00|group:C777F06B-202E-4480-B475-FA416154D458,notebook:c:\TempREPOdel\EMA%20Core\DerrickTate\SQLNotebooks\WorkItem_878\Notebook-01.ipynb,untitled:notebook-editor-0]
[2020-05-04 16:56:46.893] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at e.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2225:841) [<root>]
    at e.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5655:786) [<root>]
    at e.$onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4930:977) [<root>]
    at e._doInvokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5032:707) [<root>]
    at e._invokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5032:399) [<root>]
    at e._receiveRequest (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5031:59) [<root>]
    at e._receiveOneMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5029:908) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5028:136 [<root>]
    at e.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:67) [<root>]
    at fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:576:470) [<root>]
    at t.PersistentProtocol._receiveMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:580:921) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:578:67 [<root>]
    at e.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:67) [<root>]
    at g.acceptChunk (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:574:17) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:573:393 [<root>]
    at Socket.t (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:584:332) [<root>]
    at Socket.ZoneTask.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48) [<root>]
    at Socket.emit (events.js:203:13) [<root>]
    at addChunk (_stream_readable.js:295:12) [<root>]
    at readableAddChunk (_stream_readable.js:276:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:210:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) [<root>]






Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Derrick Tate live<mailto:dtate22@live.com>
Sent: Monday, May 4, 2020 3:17 PM
To: microsoft/azuredatastudio<mailto:reply@reply.github.com>; microsoft/azuredatastudio<mailto:azuredatastudio@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>; Derrick Tate<mailto:Derrick.Tate@outlook.com>; Derrick Tate live<mailto:dtate22@live.com>
Subject: RE: [microsoft/azuredatastudio] This is driving me crazy! (#10259)

Select * from dbo.account

Simple query…

  *   The problem is on a new computer
     *   Either the login to SQL Server through SQL Server MFA (third party verification) is failing
     *   Or something else
  *   Next the render fails – either login or something else
  *   Once this happens, my Azure Data Studio is toast until Icreate a brand new notebook

I’m available to speak if you need more information – just let me know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aaomidi** [comment] 2020-05-05 18:24
Oh interesting. It might make sense for ADS to do more handholding in this situation.

**Comment by dtate22** [comment] 2020-05-05 20:14
I got the exact problem….


  *   It wasn’t Python related at all

My directory structure contained a “Notebook”

The name of the Path to the file was:
                C:\TempNoteBooks\EMA%20Core\Notebook-0.ipynb

I changed the name of the directory to “EMA_Core” and everything works now.

In my DevOps REPO when I CLONED the REPO, there is a SPACE in the file name that turns into “%20” which is a valid file name but throws “Azure Data Studio” off.

Thanks for being so responsive,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chlafreniere** [comment] 2021-01-13 04:07
This was discussed previously that this change will not be part of the January release. Moving to February, given that a PR is already out.

**Closed** 2021-04-20 18:40 UTC
Labels: Area - Live site, Area - Notebooks, Bug, Impact: Live site, Triage: Done
