### ISSUE TITLE
Disconnects from SQL Databases

### ISSUE THREAD

**Issue by aarongiust** [microsoft/azuredatastudio#14853] opened 2021-03-24 16:53 UTC
Issue Type: <b>Bug</b>

Azure Data Studio constantly disconnects from Azure SQL Databases which causes functionality to stop working such as Intellisense and object browsing. It should be able to stay connected just as SSMS can stay connected.

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:24:59.168Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cms|Mic|0.8.0

</details>

**Comment by mrjrdnthms** [comment] 2021-04-06 17:37
this is a brutal bug. happens all the time and the team has not addressed it for too long. the only option right now is to close and reopen azure data studio. if you close and reopen it is forced to reconnect to the db and queries execute immediately again. I close and reopen the app about every 10 min. its awfully annoying.

**Comment by cssuh** [comment] 2021-04-13 20:40
@aarongiust what authentication method are you using for these DBs?

**Comment by aarongiust** [comment] 2021-04-13 20:43
Azure Active Directory with MFA

**Comment by mrjrdnthms** [comment] 2021-05-05 20:20
I'm using sql server auth

**Comment by raeokay** [comment] 2021-07-22 13:11
Please stop kicking this can down the road. This issue occurs all day. First thing in the morning, at random all day, when I'm trying to finish my work at night.

**Comment by kburtram** [comment] 2021-07-23 16:24
@aarongiust is the issue you're experiencing with disconnects related to AAD token expiration or just general disconnects?  I'm trying to determine if this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/14159.  Thanks!

**Comment by aarongiust** [comment] 2021-07-23 17:47
I honestly don't remember as I gave up on Azure Data Studio months ago. I went back to SQL Server Management Studio and got a SQL Prompt license. I do work mostly with Azure SQL Databases so it was most likely due to AAD token expiration.

**Comment by kburtram** [comment] 2021-08-23 18:48
Thanks for providing additional context @aarongiust and for taking the time to report these issues!  We're currently working a fix for this bug and are tracking that work in https://github.com/microsoft/azuredatastudio/issues/10352.  I'll close this as a duplicate of that issue.

**Closed by kburtram** 2021-08-23 18:48 UTC
Labels: Bug, Area - Connection, Area - Azure, Triage: Done

**Comment by raeokay** [comment] 2021-08-23 18:59
> 
> 
> Thanks for providing additional context @aarongiust and for taking the time to report these issues! We're currently working a fix for this bug and are tracking that work in #10352. I'll close this as a duplicate of that issue.

Are you certain this is the same bug? I have this issue while only using local SQL Server instances. We don't use Azure services.

**Comment by gvv5485** [comment] 2023-02-07 02:50
This is still happening for me!

**Comment by software-tpg** [comment] 2024-03-18 06:23
Same here.  SQL login and connections drop randomly every 10 to 20 mins.  Only way to get it back is to close program and reopen.  Very frustrating !!!
