### ISSUE TITLE
Linux - Cannot Copy Results to Clipboard

### ISSUE THREAD

**Issue by photoTed** [microsoft/azuredatastudio#24090] opened 2023-08-07 20:38 UTC
- Azure Data Studio Version: 1.45.1
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Using a select statement get results.
2. Select the contents of a cell and copy with Ctrl-C, Shift-Ctrl-C, or with the right mouse menu select Copy or Copy with Headers.  Neither of the Linux clipboards (Ctrl-V or middle mouse button click) are populated.  The last copied text is pasted instead.

BTW, right-mouse-menu "Copy Headers" does work.

Does this issue occur when all extensions are disabled?: Yes.  I do not have any extensions installed.

**Comment by cssuh** [comment] 2023-08-07 20:49
duplicate of https://github.com/microsoft/azuredatastudio/issues/24043, as a workaround please install the xsel extension

**Closed by cssuh** 2023-08-07 20:49 UTC

**Comment by photoTed** [comment] 2023-08-07 21:10
Happy to but I don't know where to find it.

**Comment by photoTed** [comment] 2023-08-07 21:16
Sorry, I thought you meant an azure extension not an OS package.  Installed with apt and it's now working.
