### ISSUE TITLE
Getting endpoints failed after successful deployment

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#7924] opened 2019-10-23 00:17 UTC
my kubeconfig name is somthing different than "config" so when I deploy bdc, I gave the right config name and everything worked fine. However, after deployment was done, getting the endpoint failed becuase the azdata command didn't have the right config name. the environment variable was not set correctly I think. here's the error:

 > azdata login -n mssql-cluster
    stderr: ERROR: azdata Please specify arguments and/or environment variables in non-interactive mode. For a better understanding of the arguments, please run 'Missing --endpoint arg in non-interactive environment. You may also place your kube config in the default location of <user home>/.kube/config or use the KUBECONFIG env var to specify the location of the config, i.e. export KUBECONFIG=path/to/.kube/config. login --help'.
    stderr: 
    >>> $azdata login -n mssql-cluster    ... exited with code: $1
	>>> azdata login -n mssql-cluster   ... errored out: Process exited with code 1

**Comment by yualan** [comment] 2019-10-24 17:33
@alanrenmsft If you get to this, great. But it's fine to punt. Kevin agrees.

**Comment by alanrenmsft** [comment] 2019-12-02 23:07
@llali If we understand correctly, you are running the azdata command outside of the context of notebook, and we only want to control the KUBECONFIG within the context of notebook. closing as by design.

**Closed by alanrenmsft** 2019-12-02 23:07 UTC
Labels: Area - Resource Deployment, Bug, Triage: Done
