### ISSUE TITLE
Maintain default connection when opening a script. Especially big data cluster connections

### ISSUE THREAD

**Issue by yualan** [Microsoft/azuredatastudio#5157] opened 2019-04-23 17:50 UTC
It is common for PowerUser to open many scripts and run them quickly. Each time a script opens, the script is disconnected. 

Feature request is to recognize a good default open connection so that the script can be run on that instance.

**Comment by kburtram** [comment] 2019-04-23 23:29
This looks like a duplicate of https://github.com/Microsoft/azuredatastudio/issues/641.

**Closed by kburtram** 2019-04-23 23:29 UTC
Labels: Area: Connection, Enhancement
