### ISSUE TITLE
Block Comment Formatting Flaw

### ISSUE THREAD

**Issue by chrskrkmn** [microsoft/azuredatastudio#6386] opened 2019-07-16 21:25 UTC
`--This example can be ran as is in an Azure Data Studio SQL Query to reproduce the flaw.

select 0 TestColumn1

/*This is a comment block (Block1) that is unclosed, i.e. does not have a star-slash to close Block1.
    Subsequent code remain part of comment block of Block1, as indicated by the green text format below...
    This correctly prevents the query (TestColumn2) from executing

    select 0 TestColumn2

/*This is a comment block (Block2) that is closed, i.e. has a star-slash to close Block2.
    However, it disables the green text format in the editor after Block2 is closed by the star-slash,
        even though the comment block of Block1 should still be commenting future statments.
    Any prior unclosed comment blocks, in this case Block1,
        should have its comment formatting reflected in all subsequent code until all comment blocks are closed*/

    select 0 TestColumn3

--If run up to this point, an error will be generated for the missing comment block closer.  This is correct execution behaviour.
--However,...

    */
    --...an additional end comment will finally close Block1,
        --preventing an error even though the formatting of the encapsulated query (TestColumn3) doesn't reflect this
    -- It correctly prevent an error that would be thrown, but the green text format doesn't reflect the statements correct commented status
![Capture](https://user-images.githubusercontent.com/52930433/61330741-2741b100-a7d5-11e9-9bac-093b98864383.PNG)
`

**Comment by Charles-Gagnon** [comment] 2021-01-25 17:04
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/848

**Closed by Charles-Gagnon** 2021-01-25 17:04 UTC
Labels: Area - Shell, Triage: Done
