### ISSUE TITLE
Missing icons on Connections panel

### ISSUE THREAD

**Issue by mkorsukov** [microsoft/azuredatastudio#17084] opened 2021-09-15 15:31 UTC
Issue Type: <b>Bug</b>

The 'Connections' panel has missing icons

![image](https://user-images.githubusercontent.com/21244808/133463528-6ff68dcf-4064-4188-be7a-54a3853c6c17.png)

![image](https://user-images.githubusercontent.com/21244808/133463543-cbdcb32c-734e-4e07-97fb-d83f9912f026.png)

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dacpac|Mic|1.8.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.12.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-09-17 20:48
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/17003 - see that for workarounds until the next stable release is out with the fix.

**Closed by Charles-Gagnon** 2021-09-17 20:48 UTC
Labels: Area - Connection, Triage: Needed, Impact: UI
