### ISSUE TITLE
Commit/Rollback

### ISSUE THREAD

**Issue by KahNManN** [microsoft/azuredatastudio#741] opened 2018-02-20 21:31 UTC
- SQL Operations Studio Version: 0.24.1

When performing an update query I would like to be able to choose to commit or rollback  instead of things being automatically committed.  (May already be there but I haven't stumbled onto it yet)

Steps to Reproduce:

**Comment by grbdevnull** [comment] 2018-03-22 16:35
This is essentially a duplicate of #456.

**Comment by alanrenmsft** [comment] 2020-11-03 23:52
@KahNManN I am going through the backlog and realized this issue has been fixed, you can go to user settings in Azure Data Studio and find the following setting: 
![image](https://user-images.githubusercontent.com/13777222/98052960-5e820a00-1dec-11eb-8317-dc1d91a31e1d.png)

**Closed by alanrenmsft** 2020-11-03 23:52 UTC
Labels: Enhancement
