### ISSUE TITLE
Replace * for the column names

### ISSUE THREAD

**Issue by bigleka** [microsoft/azuredatastudio#259] opened 2017-11-30 15:41 UTC
Enable a replace key (TAB,space,etc.) to replace the * (star) on a select statement after end the statement.

Like:
select * from sys.databases;
the user put the cursor on the * and press the replace key,,,

SELECT name, database_id,source_database_id ,,,,
from sys.databases

**Comment by kburtram** [comment] 2018-04-13 01:25
This should be fixed in current builds.

**Comment by opus131** [comment] 2018-06-07 06:10
@kburtram: Could you please advise how to make this feature work? I place the cursor behind the star in a query and then what? I tried all sorts of key-combos but nothing does the trick. The columns are being displayed in the tooltip that I get when I hover the star though...

**Comment by opus131** [comment] 2018-06-13 11:39
@kburtram: Sorry for chasing, but I'm a bit lost - you said this should be fixed in the current builds and closed the issue, but I'm using the current build and yet it does not work for me. Could you explain how I can get the `*` expanded to the actual column names? I'm using a German keyboard, SqlOps version info  below:

```
Version 0.30.3-insider
Commit 8a3509e0062448b1335a0fb2eab7050d50a3a07a
Date 2018-06-01T03:37:19.246Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by opus131** [comment] 2018-06-14 06:57
Thank you for getting back to me, and for reopening the issue. Being able to expand the star into column names is incredibly useful - maybe our team is simply too spoiled by Redgate's _SQL Prompt_, but I won't be able to convince them to switch to _SqlOps_ without that feature.

**Comment by AlexFsmn** [comment] 2018-09-16 11:14
It seems this issue can only be solved by Microsoft since Microsoft.SqlServer.Management.SqlParser.Intellisense isn't open source. Could you verify this @kburtram ?

**Comment by opus131** [comment] 2019-01-20 18:42
Any update on this?

**Comment by opus131** [comment] 2019-04-16 11:58
Any news here? This is a MAJOR adoption blocker...

**Comment by chucker** [comment] 2019-04-16 20:35
Is it? It’s a nice convenience, surely?

**Comment by opus131** [comment] 2019-04-17 04:43
> It’s a nice convenience, surely

@chucker: so nice, indeed, that many devs I know including myself would never consider using a DBMS that does not provide this convenience. So yes, it is a major adoption blocker.

**Comment by kburtram** [comment] 2021-09-10 19:09
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/3152.  Using the newer issue since it has more upvotes and comment history.  Thanks!

**Closed by kburtram** 2021-09-10 19:09 UTC
Labels: Area - Language Service, Enhancement
