### ISSUE TITLE
root directory is C:\ on a Linux container

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#24308] opened 2023-09-06 22:16 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. open server properties on SQL Server 2022 in container
2. "root directory" value is C:\, which seems unlikely (unless I'm missing something about the meaning of that field)

![image](https://github.com/microsoft/azuredatastudio/assets/12227241/a662d173-bf00-4410-a706-cd3e5c883172)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ssreerama** [comment] 2023-09-06 22:26
Does the same server shows diff value on Windows/Mac?

**Comment by barbaravaldez** [comment] 2023-09-08 20:21
Duplicate of https://github.com/microsoft/azuredatastudio/issues/23657

**Closed by barbaravaldez** 2023-09-08 20:21 UTC
Labels: Bug, Triage: Done, Area - Basic Admin
