### ISSUE TITLE
Schema Compare Failed:Unknown error while trying to Compare SQL Datawarehouse and dacpac file using Schema Compare extension

### ISSUE THREAD

**Issue by VikAga** [microsoft/azuredatastudio#14107] opened 2021-01-29 10:11 UTC
- Azure Data Studio Version:1.25.2

Steps to Reproduce:

1.In schema Compare extension, select a SQL Datwarehouse as source  and a dacpac file as target and try to compare.

![Capture](https://user-images.githubusercontent.com/78205980/106262003-f8890100-61e7-11eb-88ad-0ea08795fe25.PNG)

**Comment by udeeshagautam** [comment] 2021-01-29 19:16
@VikAga thanks for reporting this issue. We have some followup questions that would help use debug this better,
1. Can you please confirm if this is happenieng for a specific DW database or all DW databases for you. If this happeneing for a specific database would it be possible for you to share a sample dacpac/model file for us.
2. Can you please open the Dev Console in ADS (Help --> Toggel Developer Tools --> Console) and share with us any error call stack you see when this happens.

**Comment by amit0904** [comment] 2021-02-02 05:03
Same issue, recently started for me also.

**Comment by VikAga** [comment] 2021-02-03 10:47
@udeeshagautam 

1.Yes ,this is happening for all DW Databases. Its working for dacpac vs master DB and failing for dacpac vs DWH.

2.Please find below error from console:

![error](https://user-images.githubusercontent.com/78205980/106736296-e4c00f00-65da-11eb-85d1-fe9ada20bff8.PNG)

**Comment by phil-boyd-iat** [comment] 2021-02-16 16:08
I'm getting a similar issue...brand new project, just created from scratch
` WARN Could not find descriptor for child component component1_7 when removing from container component1_16
2
log.ts:197   ERR An unknown error occurred. Please consult the log for more details.`
`[2021-02-16 10:52:15.591] [renderer1] [error] Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined
    at h.isAbsolutePath (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:593:730)
    at _.withProvider (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2364:343)
    at _.doResolveFile (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2365:599)
    at _.resolve (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2365:324)
    at le.createListEntries (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:6190:387)
    at le.mapListEntries (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:6191:649)
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:6187:370
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:388:26)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:138:43)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:421:31)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:188:47)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:595:35)`

**Comment by kisantia** [comment] 2021-02-23 21:57
@VikAga does this also happen when using the SSDT schema compare? 

@phil-boyd-iat did the build for the project succeed? If the issue is not related to a DW database, please open another issue to track it separately. Thanks!

**Comment by erapade** [comment] 2021-03-10 19:53
Happens for me to:
notificationsAlerts.ts:40 Schema Compare failed: Unknown
onDidChangeNotification @ notificationsAlerts.ts:36
(anonymous) @ breadcrumbsModel.ts:294
fire @ event.ts:570
addNotification @ notifications.ts:205
notify @ notificationService.ts:94
(anonymous) @ mainThreadLogService.ts:16
ZoneAwarePromise @ C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:891
_showMessage @ mainThreadLogService.ts:16
$showMessage @ mainThreadLogService.ts:16
_doInvokeHandler @ rpcProtocol.ts:351
_invokeHandler @ rpcProtocol.ts:351
_receiveRequest @ rpcProtocol.ts:296
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:104
fire @ event.ts:570
fire @ ipc.net.ts:437
_receiveMessage @ ipc.net.ts:778
(anonymous) @ ipc.net.ts:633
fire @ event.ts:570
acceptChunk @ ipc.net.ts:185
(anonymous) @ ipc.net.ts:185
t @ ipc.net.ts:21
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181

**Comment by ssreerama** [comment] 2021-03-13 00:23
@VikAga I have tried the steps you mentioned to repro the issue, but couldn't repro it both ADS and SSDT SC. Could you please upload any sample bacpacs that you were able to repro the issue. Thanks :)

**Comment by mastercorp-usa** [comment] 2021-04-08 18:07
I am having the same problem.. 

/C:/Users/venum/AppD…desktop.main.js:494 [Extension Host] (node:19064) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))

**Comment by ssreerama** [comment] 2021-06-09 10:04
This issue has been fixed and changes are merged to the code base, and will be available with the coming release, the main focus on this error is users are unable to see the real error when schema comparing the data warehouse data bases. With the fix, users can see the real time errors causing the failure and able to know the reason what causing them. closing this ticket, if you need anymore assistance you can log a new request, Thank you :)

**Closed** 2021-06-09 10:05 UTC
Labels: Area - Schema Compare, Bug, Needs More Info, Triage: Done
