### ISSUE TITLE
AAD token should automatically refresh when reconnecting to a server

### ISSUE THREAD

**Issue by jheavin-iit** [microsoft/azuredatastudio#6872] opened 2019-08-22 15:01 UTC
- Azure Data Studio Version: 1.10

Steps to Reproduce:

1. Connect to a server with AAD Multi factor authentication
2. Leave idle for a while so the connection gets dropped.
3. Try to do any action on the server and you will be unable to reconnect to the server. Error "Failed to connect Server" (Refresh also fails).

Workaround:
Close and Re-open Azure Data studio

**Comment by jheavin-iit** [comment] 2019-12-11 00:53
Any idea when this might be fixed? This is the only issue that is preventing me from switching to this as my daily driver over SSMS (and I definitely want to switch :) )

**Comment by scottfagg** [comment] 2020-06-12 07:16
Is there a likely timeframe for this to be addressed ?

**Comment by kburtram** [comment] 2021-08-17 20:22
@caohai this looks like a duplicate of the AAD refresh token you're looking at.

**Comment by kburtram** [comment] 2021-08-23 18:47
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/10352.  We'll use #10352 for tracking this bug fix since it has more investigation details.  Thanks!

**Closed by kburtram** 2021-08-23 18:47 UTC
Labels: Bug, Area - Connection, Triage: Done
