### ISSUE TITLE
Misleading error message while trying to view properties of detached database

### ISSUE THREAD

**Issue by abhikum** [microsoft/azuredatastudio#24317] opened 2023-09-06 22:37 UTC
Repro steps:
1. Right click on database and click Detach (Preview)
2. Click Script button in Detach Database dialog.
3. Run the detach script.
4. Right click on database and click Properties (Preview)

**Expected:** Error message should indicate unable to connect as database does not exist.
Actual: Error message should indicate unable to connect as login failed.
"An error occurred while opening the properties dialog for database: keep_adstest. Cannot open database "keep_adstest" requested by the login. The login failed. Login failed for user..."

![image](https://github.com/microsoft/azuredatastudio/assets/9576880/64638700-5cfc-43f8-b406-5a2877d416a7)

**Comment by corivera** [comment] 2023-09-06 23:18
This is another query editor one where we don't refresh the object explorer after running a script. Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/24315

**Closed by corivera** 2023-09-06 23:18 UTC
