### ISSUE TITLE
Left join query fails

### ISSUE THREAD

**Issue by kmartin-at-ziing-ca** [microsoft/azuredatastudio#21347] opened 2022-12-01 17:57 UTC
Issue Type: <b>Bug</b>

Error Message:
 10:45:43 AMStarted executing query at Line 7
 (1 row affected)
 Query failed: Object reference not set to an instance of an object.
 Total execution time: 00:00:00.105

Query:
-- The following query fails in Azure Data Studio when table_b row is null
-- (the same query runs fine in a python script using pyodbc)

select * 
from table_a 
left join table_b on table_b.id = table_a.id

-- The query will run if table_b null rows are filtered out
select * 
from table_a 
left join table_b on table_b.id = table_a.id 
where table_b.id is not null

Azure Data Studio version: azuredatastudio 1.40.1 (Universal) (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T19:35:40.769Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No
Preview Features: Enabled

**Comment by dzsquared** [comment] 2022-12-02 18:45
This should be the minimal repro of the issue, which is also reported in #18714 and #20292 

Credit to @raoulteeuwenPE for including a bunch of details on #18714

```sql
drop TABLE [dbo].[ObjectErrorTable1];
drop TABLE [dbo].[ObjectErrorTable2];
GO


-- THIS IS TABLE 1
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ObjectErrorTable1](
    [SomeColumn] NVARCHAR(50) NOT NULL
) ON [PRIMARY]
GO


-- THIS IS TABLE 2
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ObjectErrorTable2](
[SomeOtherColumn] NVARCHAR(50) NOT NULL
    , [MeBeingEmptyAndATimeStampTypeThrowsAnError] [TIMESTAMP] NOT NULL -- THE EXISTENCE OF THIS TIMESTAMP COLUMN WITH NULL VALUES WITH CAUSES THE ERROR
) ON [PRIMARY]
GO


-- INSERT DATA
insert into [dbo].ObjectErrorTable1 (SomeColumn)
select 'theresavaluehereontable1'
    ;
GO

-- RUN QUERY TO THROW ERROR
SELECT t1.*, t2.*
FROM [dbo].[ObjectErrorTable1] t1
LEFT OUTER JOIN [dbo].[ObjectErrorTable2] t2 ON t1.SomeColumn = t2.SomeOtherColumn
WHERE t1.SomeColumn='theresavaluehereontable1';
go





-- -- INSERT A MATCHING ROW TO TABLE 2
-- insert into [dbo].[ObjectErrorTable2] (SomeOtherColumn)
-- select 'theresavaluehereontable1';
-- go

-- -- RUN QUERY AGAIN WITHOUT ERROR
-- SELECT t1.*, t2.*
-- FROM [dbo].[ObjectErrorTable1] t1
-- LEFT OUTER JOIN [dbo].[ObjectErrorTable2] t2 ON t1.SomeColumn = t2.SomeOtherColumn
-- WHERE t1.SomeColumn='theresavaluehereontable1';
-- go

```

**Comment by alanrenmsft** [comment] 2022-12-06 19:19
dupe of #18714

**Closed by alanrenmsft** 2022-12-06 19:19 UTC
Labels: Bug, Area - Query Editor, Triage: Done
