### ISSUE TITLE
Autoclose notification after copying data to clipboard

### ISSUE THREAD

**Issue by rubenruvalcabac** [microsoft/azuredatastudio#24119] opened 2023-08-11 01:14 UTC
Since the last release, after copying to the clipboard from the resultset it shows the following notification: "Selected data has been copied to the clipboard. Row count: xx" This information is useless, but I could ignore it. The problem is the notification keeps open until click on the "Close" button. I would like to be able to disable this notification, or at least the notification auto-close after a few seconds.

**Comment by Mnior** [comment] 2023-08-11 13:30
Duplicate of #24009 (Closed)

The fix is now merged in main:

- Notifications will auto-close in 3 seconds (when they show up)
- You will have an option to disable them completely with below setting:
Query Editor > Results: Show Copy Completed Notification

This support will be available in the September release (v1.46+).

**Comment by cheenamalhotra** [comment] 2023-08-14 16:40
Thanks @Mnior - closing as duplicate.

**Closed by cheenamalhotra** 2023-08-14 16:40 UTC
