### ISSUE TITLE
remembered passwords eventually forgotten

### ISSUE THREAD

**Issue by scottfagg** [microsoft/azuredatastudio#17698] opened 2021-11-18 03:19 UTC
Issue Type: <b>Bug</b>

Within a single session of Azure Data studio, if i make a connection and tick 'remember password', it will eventually forget the password. seems to remember it at most for a couple of minutes.

Tried editing the .json connection file, but they are eventually removed from their too.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:43:30.222Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
extra-sql-script-as|pac|0.3.0
simple-data-scripter|sea|0.1.6

</details>

**Comment by JeffBusterCase** [comment] 2021-11-18 15:02
This problem is nuts....

Duplicate of [#17594](https://github.com/microsoft/azuredatastudio/issues/17594)

**Closed** 2021-11-18 17:37 UTC
