### ISSUE TITLE
Database Folder not Expanding

### ISSUE THREAD

**Issue by joelvega** [microsoft/azuredatastudio#6450] opened 2019-07-22 13:21 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste:

Issue Type: <b>Performance Issue</b>

With connecting to an Azure SQL Database, the Database folder will not expand. It will always timeout.

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    67	 67428	azuredatastudio main
    1	    76	  2236	   window (Issue Reporter)
    1	   230	 29960	   window (Azure Data Studio)
    0	   109	 68796	     extensionHost
    0	    69	 22236	       "c:\Users\JVega\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.105\MicrosoftSqlToolsServiceLayer.exe" --log-file C:\Users\JVega\AppData\Roaming\azuredatastudio\mssql\sqltools_68796.log --tracing-level Critical
    0	     7	 26060	         console-window-host (Windows internal process)
    0	    15	 60868	       "c:\Users\JVega\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.105\SqlToolsResourceProviderService.exe" --log-file C:\Users\JVega\AppData\Roaming\azuredatastudio\mssql\resourceprovider_68796.log --tracing-level Critical
    0	     7	  3852	         console-window-host (Windows internal process)
    0	    18	 66156	       "C:\Users\JVega\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe" "c:\Users\JVega\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=68796
    0	    15	 69092	       "c:\Users\JVega\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.105\MicrosoftSqlToolsCredentials.exe" --log-file C:\Users\JVega\AppData\Roaming\azuredatastudio\mssql\credentialstore_68796.log --tracing-level Critical
    0	     7	 35800	         console-window-host (Windows internal process)
    0	    47	 35700	   shared-process
    0	   103	 63632	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by Charles-Gagnon** [comment] 2019-07-23 02:37
Could you please paste the contents of the original report? Does this happen consistently and is there any error displayed when you try to expand or does it just sit there spinning forever?

**Comment by joelvega** [comment] 2019-07-23 15:18
> Could you please paste the contents of the original report? Does this happen consistently and is there any error displayed when you try to expand or does it just sit there spinning forever?

I copied and pasted the entire error message and results in the original post. This problem does happen consistently since I have applied an update from Azure Data Studio. After spinning from some time, it gives the error message "Object Explorer task didn't complete within 45 seconds."

I am able to right-click on the database and select **Manage** and then I instantly get a list of the table and I can do my work from there. This issue seems to be isolated to opening the database folder in the object explorer.

**Comment by juniordeveloperbootcamp** [comment] 2019-07-25 14:54
I have a simlar issue after update to version 1.9.0.  Please take a look at  the screenshots provided
<img width="1218" alt="Screen Shot 2019-07-25 at 10 50 07 AM" src="https://user-images.githubusercontent.com/46457876/61884478-48d42400-aeca-11e9-9df7-b00adf809b5d.png">


if I right click  database folder and choose to manage, then it opens database tables and SPs in the dashboard view

<img width="807" alt="Screen Shot 2019-07-25 at 10 50 54 AM" src="https://user-images.githubusercontent.com/46457876/61884599-82a52a80-aeca-11e9-8502-383be7c7f16d.png">

**Comment by chaibloom** [comment] 2019-11-07 21:39
It would be nice if this bug got more love.  We have Azure servers hosting 5000 DBs, and they always time out when trying to open <Server>/Databases in the connections pane.  While it can take a bit to populate that data in SSMS, it does eventually come up, and typically in less than 45 seconds.

**Comment by aaomidi** [comment] 2019-11-11 19:54
@chaibloom which version of ADS are you using?

**Comment by chaibloom** [comment] 2019-11-11 20:19
@aaomidi - 1.13.0

**Comment by fluggo** [comment] 2019-11-26 16:33
I have this same issue in 1.13.1. Like juniordeveloperbootcamp, if I choose to "Manage" and then refresh the Object Explorer view, I am able to see the tables and views. Otherwise, it times out.

Server I'm connecting to is version 14.0.3045.24.

**Comment by nvonbenken** [comment] 2019-12-18 14:23
I get this issue as well from time to time on 1.15.0-insider

**Comment by bew4lsh** [comment] 2020-01-29 17:28
Experiencing this issue at version 1.14.1. Would love to use this product in place of ssms, but this basic feature's incompatibility with azure SQL strikes me as disqualifying. 'Azure' data studio, huh.

**Comment by xspdr1800** [comment] 2020-02-25 03:10
same issue here. connecting to SQL 2014 and can't expand the database folders since I install Azure data studio a week ago. another issue, I deleted the Server Dashboard Search tables  widget and i can't get it back, any ideas how to? I only have the tasks widget. see below. I appreciate any help.

![Capture](https://user-images.githubusercontent.com/61443276/75211571-4ed8fe80-5752-11ea-86f5-09791d8f1efa.JPG)

**Comment by Charles-Gagnon** [comment] 2020-02-25 17:15
@xspdr1800 - You can reset that by opening the command pallet and running the `Preferences: Open Settings (JSON)` command. Then find the `"dashboard.server.widgets"` value and delete it and everything in the square brackets after it. This will be something like this :

```
"dashboard.server.widgets": [
    {
        "name": "Tasks",
        "widget": {
            "tasks-widget": [
                "newQuery",
                "mssqlCluster.task.newNotebook",
                {
                    "name": "restore",
                    "when": "!mssql:iscloud && mssql:engineedition != 11"
                },
                "configureDashboard"
            ]
        },
        "gridItemConfig": {
            "sizex": 1,
            "sizey": 1
        }
    },
    {
        "widget": {
            "backup-history-server-insight": null
        }
    },
    {
        "widget": {
            "all-database-size-server-insight": null
        }
    }
]
```

Then re-open the dashboard and the widget should appear again. 

@alanrenmsft @kisantia This is pretty annoying that there doesn't seem to be an easy way to reset the default dashboard widgets - let's make sure we have that be easy with the new Dashboard refactor.

**Comment by cairneym** [comment] 2020-03-25 00:16
Also experiencing the expansion timeout with 500 databases on Azure SQL DB. Connection to the server is fine and the dashboard shows the full list of databases alsmost instantaneously.

However trying to expand the databases node on Object Explorer results in the 45 seconds timeout.

Is the timeout value configurable in the settings anywhere?

**Comment by alanrenmsft** [comment] 2020-03-25 06:32
> @xspdr1800 - You can reset that by opening the command pallet and running the `Preferences: Open Settings (JSON)` command. Then find the `"dashboard.server.widgets"` value and delete it and everything in the square brackets after it. This will be something like this :
> 
> ```
> "dashboard.server.widgets": [
>     {
>         "name": "Tasks",
>         "widget": {
>             "tasks-widget": [
>                 "newQuery",
>                 "mssqlCluster.task.newNotebook",
>                 {
>                     "name": "restore",
>                     "when": "!mssql:iscloud && mssql:engineedition != 11"
>                 },
>                 "configureDashboard"
>             ]
>         },
>         "gridItemConfig": {
>             "sizex": 1,
>             "sizey": 1
>         }
>     },
>     {
>         "widget": {
>             "backup-history-server-insight": null
>         }
>     },
>     {
>         "widget": {
>             "all-database-size-server-insight": null
>         }
>     }
> ]
> ```
> 
> Then re-open the dashboard and the widget should appear again.
> 
> @alanrenmsft @kisantia This is pretty annoying that there doesn't seem to be an easy way to reset the default dashboard widgets - let's make sure we have that be easy with the new Dashboard refactor.

@Charles-Gagnon I could find the original comment provided by @xspdr1800, but I think we can do it by adding a task 'Restore settings' to server and database dashboards, the workflow would be:
1. click the 'Restore settings' task button in the tasks widget
2. prompt the user with impact of the action and ask for confirmation (using standard vscode popup notification)
3. remove the customization done by user

I will run this by the team in our next dashboard improvement meeting this week.

**Comment by tbolon** [comment] 2020-04-29 09:23
This error still occurs on latest version (1.17). Was already submitted in #3270.

As suggested in the other issue, the database listing is instant when using the server details, but fails when using the left pane browser. For just displaying the database nodes, the query you execute could be optimized.

**Comment by perrydyball** [comment] 2020-06-19 15:31
Still an issue in 1.19

Changing to using full fat SQL SSMS

**Comment by tbolon** [comment] 2020-07-16 08:21
Still occurring on latest version with less than 50 databases on a Azure Sql Database server. Same error: the server browser tries to connect to all databases one after another with a global timeout of 45 seconds. Unsurprisingly, it does not scale well when you have any serious amount of databases. And it works perfectly well when you use the Manage Server pane to list all databases (certainly only using master db to populate this list and restraining itself from doing any operation on each database while enumerating).

I am surprised that this issue is not given any attention, since it completely ruins basic Azure Data Studio usage when connecting to Azure Sql Database Server with more than any trivial amount of databases.

**Comment by alanrenmsft** [comment] 2020-07-16 17:21
@abist could you please take a look?

**Comment by abist** [comment] 2020-07-16 18:54
@alanrenmsft I don't think I will be able to work on this for August release, this is a perf issue and a non-trivial task

**Comment by hfleitas** [comment] 2020-10-23 19:54
From terminal, click output, Log (Window) 

```
authenticationType:SqlLogin|database:|server:SQLSVR2019|user:hiram|group:37244e90-6961-4ab4-b7d2-dfaa19ef5e44
[2020-10-23 15:46:08.088] [renderer1] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:hiramdb|server:SQLSVR2019|user:hiram|group:37244e90-6961-4ab4-b7d2-dfaa19ef5e44
[2020-10-23 15:46:08.169] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-10-23 15:46:08.170] [renderer1] [error] Cannot read property 'isCloud' of null: TypeError: Cannot read property 'isCloud' of null
	at t.MssqlIconProvider.getConnectionIconId (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:411:37875)
	at d.$getConnectionIconId (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:697:248)
	at g._doInvokeHandler (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:969:707)
	at g._invokeHandler (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:969:399)
	at g._receiveRequest (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:968:59)
	at g._receiveOneMessage (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:966:886)
	at c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:965:34
	at l.fire (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:475)
	at v.fire (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:259:381)
	at c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1149:963
	at l.fire (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:475)
	at v.fire (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:259:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:264:451)
	at c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:489
	at l.fire (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:475)
	at p.acceptChunk (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:851)
	at c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:203
	at Socket.t (c:\Users\hfleitas\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:266:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-10-23 15:46:08.574] [renderer1] [error] Failed to create Object Explorer session
```

**Comment by Charles-Gagnon** [comment] 2020-10-23 20:07
@hfleitas I think your issue is more along the lines of https://github.com/microsoft/azuredatastudio/issues/12992

Has this also recently just started happening for you? (as in with the latest release)

I'm going to leave instructions for some further logs to provide in the linked issue - the issue seems to be in a separate part of the application. So if you could get me those that would be helpful.

**Comment by hfleitas** [comment] 2020-10-23 20:17
@Charles-Gagnon yes, this is recently occurring for me and my team. I'll send the logs in the linked issue. Thx

**Comment by hastiAu** [comment] 2021-01-09 08:00
hi Charles-Gagnon 
I find this "dashboard.server.widgets": 

but I cant delete it 
how can I delete?

**Comment by Charles-Gagnon** [comment] 2021-01-11 17:26
What do you mean you can't delete it? If you open the JSON settings you should be able to delete the entry from the JSON text editor that is opened.

**Comment by hastiAu** [comment] 2021-01-11 18:57
I see this code in setting.json

{
    "workbench.enablePreviewFeatures": true,
    "datasource.connectionGroups": [
        {
            "name": "ROOT",
            "id": "C777F06B-202E-4480-B475-FA416154D458"
        }
    ],
    "datasource.connections": [
        {
            "options": {
                "connectionName": "Server",
                "server": "185.55.224.2",
                "database": "etransfer_db",
                "authenticationType": "SqlLogin",
                "user": "etransfer_user1",
                "password": "",
                "applicationName": "azdata",
                "groupId": "C777F06B-202E-4480-B475-FA416154D458",
                "databaseDisplayName": "etransfer_db"
            },
            "groupId": "C777F06B-202E-4480-B475-FA416154D458",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "c69f6f6f-e72c-4e62-a519-5b649cceb9e1"
        },
        {
            "options": {
                "connectionName": "localhost",
                "server": "Localhost",
                "database": "",
                "authenticationType": "SqlLogin",
                "user": "sa",
                "password": "",
                "applicationName": "azdata",
                "groupId": "C777F06B-202E-4480-B475-FA416154D458",
                "databaseDisplayName": ""
            },
            "groupId": "C777F06B-202E-4480-B475-FA416154D458",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "53c6503d-9eb7-44b3-934b-2c2a3db35bb8"
        }
    ],
    "workbench.startupEditor": "welcomePage"
}



--------------------
but "dashboard.server.widgets": 

is in defaultsetting.json that I cant change this file

**Comment by Charles-Gagnon** [comment] 2021-01-11 19:16
You shouldn't be modifying the defaults.

Since you don't have a custom setting in the user settings JSON then it should be using the default one. Is this not happening?

Note that this dashboard stuff has nothing to do with the database folder not expanding. This was just a separate issue that someone else was having. If you're also having problems with the dashboard widgets then I would suggest opening another issue and we can help you there so that we can keep this one on topic.

**Comment by grayspace** [comment] 2021-02-25 16:23
I've had this same issue happening for months, currently on version 1.25.2. I keep updating to see if it works itself out, but so far it hasn't. Love everything about ADS except this.

**Comment by kburtram** [comment] 2021-02-25 16:31
@grayspace the next time you hit this error could you please check if there are any exceptions in the "Help->Developer Tools" Console?  We haven't been able to get a consistent repro for this, so we're not sure how to resolve yet.

**Comment by tbolon** [comment] 2021-02-25 16:39
@kburtram 
![image](https://user-images.githubusercontent.com/127185/109185616-782ad100-7790-11eb-8a65-64f9475b0d53.png)

**Comment by grayspace** [comment] 2021-03-08 16:44
> @grayspace the next time you hit this error could you please check if there are any exceptions in the "Help->Developer Tools" Console? We haven't been able to get a consistent repro for this, so we're not sure how to resolve yet.

I don't always get an error, and the issue seems to be occurring less frequently than before, but I have gotten the same error as in the @tbolon screenshot.

**Comment by firxworx** [comment] 2021-03-09 06:10
We reported similar issue in #13836 that was closed due to possible duplicate with this one. I'm not sure that it exactly is but it could be related. Over in that one we [multiple users] note cases where everything runs as expected in SSMS but not ADS.

With ADS I had read-only users with sufficient permissions to view db/tables and when I encountered the issue I even tried explicitly granting VIEW Definition, EXECUTE, etc. and on master VIEW ANY DATABASE to see if that would change anything for the affected users and no luck. My error in the log matched the OP's -- `"Could not find ServerInfo for connection" ... "when updating icon"`.

Also of note if I had a user with super-high privileges/perms then it would work fine in ADS. It seemed to only affect users that _should_ be able to expand the database folder and tables/fields (and can do so in SSMS) that in my case were read-only.

**Comment by silverspringhusker** [comment] 2021-04-13 22:36
I am experiencing the same thing as referenced in [13836](https://github.com/microsoft/azuredatastudio/issues/13836) 

I have no problem in SSMS expanding Databases and within a database, Tables. But in both ADS 1.27.0 for Mac and Windows 10, clicking on Databases doesn't show anything. However, in both Windows and Mac, in the Connection Details pane, I can choose a database from the Database drop-down. But once I establish a connection to a particular database, I can't see any properties or anything else for that database. On this server, unlike others where I have not experienced this issue, I don't have sysadmin privileges, just public, with db_owner privileges on the individual databases. (These are all on-premise SQL Servers, using integrated authentication from both Mac and Windows)

One possible additional clue. I just tried establishing a connection in IntelliJ IDEA to the problematic database server. I am using the Microsoft JDBC Driver 9.2 for SQL Server with integrated authentication. If I specify the database, I can browse only the tables in the dbo. schema (including sysdiagrams), none of the tables in other schemas.

**Comment by silverspringhusker** [comment] 2021-04-28 22:35
> I am experiencing the same thing as referenced in [13836](https://github.com/microsoft/azuredatastudio/issues/13836)
> 
> I have no problem in SSMS expanding Databases and within a database, Tables. But in both ADS 1.27.0 for Mac and Windows 10, c

I am no longer experiencing this issue in ADS 1.28.0.

**Comment by tbolon** [comment] 2021-05-18 09:53
This error is still there in the latest version.

See this full reproduction cases for our server. You can observe:

- that the "Manage > Search" pane works perfectly and list all databases in a few seconds, without any virtualization on the list
- that the server has (only) 450 databases
- that the database folder times out

![Animation2](https://user-images.githubusercontent.com/127185/118630946-51989700-b7cf-11eb-8527-ccd606f7b0ff.gif)

**Comment by JamesAlexander42** [comment] 2021-06-08 02:31
I've noticed this only occurs to me if I have a Serverless SQL Azure DB that's asleep. If I refresh it after a couple minutes it works just fine. Why would Serverless DB's be an issue?

**Comment by ddejohn** [comment] 2022-03-15 18:19
Checking in with this issue still occurring in 2022...

**Comment by Charles-Gagnon** [comment] 2022-04-27 23:37
@kburtram FYI

I've been looking into this and have identified what seems to be the main cause of the issue - SMO is currently attempting to connect to every database when the databases folder is expanded. This can easily cause timeouts on Azure servers with many DB's.

We're currently working on addressing that by doing a best attempt to not require connecting to every DB on a server unless a db-specific property is accessed (which ADS isn't doing currently). That should help address the most common timeouts that people are having. 

There's still an issue that if any of the databases are inaccessible for some reason then SMO will attempt to connect to that database multiple times (retry logic was added for serverless scenarios among other reasons), but if the DB is completely inaccessible then we have to wait for the login attempt to time out which can take 5+seconds for each attempt and thus very quickly go over the 45sec limit.

Unfortunately this second one is a lot trickier to solve - we're looking at ways to do that but unfortunately there doesn't seem to be a way that we can do that without breaking other scenarios. The only true way to solve this completely would be to use SFC queries directly (like SSMS does) to populate the list and only when a database node itself is expanded use the full SMO DB object. This would require a bigger refactor of the core OE logic though so I'm planning on getting these SMO changes in and seeing how much of an improvement we're seeing there, and then looking into the refactoring if there's still enough cases of people hitting the timeout issues.

**Comment by firxworx** [comment] 2022-04-28 19:05
Interesting insight @Charles-Gagnon. 

Since you mentioned "many Azure DB's" I wanted to confirm that this issue can be encountered with very few DB's. To add more context -- this issue totally prevented adoption of Azure Data Studio in an environment where I don't recall more than a handful of SQL servers (the company in question was connecting to SQL Server on Windows-powered AWS EC2 instances via VPN). It was a while back now (what an old issue!) but IIRC it was **3**. I wanted to offer it over SSMS because it could also connect to a couple Postgres servers and train users on a common client/tool that would (or was at least expected to) play really nice with SQL Server.

**Comment by Charles-Gagnon** [comment] 2022-04-28 19:19
Thanks for the info, I'll be adding more logging too so we can track down exactly what issues are in different cases which should help.

You're saying that you were seeing this even with on-prem instances on a VM? That's definitely pretty odd - the investigation I'm doing is centered around Azure since that's where we get the most latency issues since we haven't seen an indication that box/standard SQL instances have these same issues.

**Comment by xaxum** [comment] 2022-07-19 00:51
For Azure SQL with 10 DBs I can confirm if a serverless DB is asleep it fails to show the databases in the explorer window.  If I wake up the database and they all are online it shows the DBs pretty quickly without issue.

**Comment by cheenamalhotra** [comment] 2023-01-16 21:45
Issue is now fixed with https://github.com/microsoft/azuredatastudio/issues/21475 addressed.
The [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) contains fix, it will be available in the next stable release.

**Closed by cheenamalhotra** 2023-01-16 21:45 UTC
Labels: Bug, Impact: Performance, Area - Object Explorer, Triage: Done, Triage: Postponed
