### ISSUE TITLE
Ability to connect to Synapse Spark Pool in notebooks

### ISSUE THREAD

**Issue by mirsky72** [microsoft/azuredatastudio#14904] opened 2021-03-30 15:24 UTC
Please allow for Azure data studio to connect to spark pools via an Azure Data Studio notebook.

**Comment by Charles-Gagnon** [comment] 2021-11-08 17:50
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/14693

**Closed by Charles-Gagnon** 2021-11-08 17:50 UTC
Labels: Area - Notebooks, Enhancement, Triage: Done
