### ISSUE TITLE
Tab Color Does Not Change on Change Connection

### ISSUE THREAD

**Issue by jsteinbergTCALLC** [microsoft/azuredatastudio#24919] opened 2023-11-08 19:13 UTC
Type: <b>Bug</b>

Ensure that tabColorMode setting is set to Fill
Add a Server group with a server with Color A (e.g. red), lets call this PROD
Add Connection to Server "PROD" to Server Group PROD
Add a Server group with a server with Color B (e.g. green), lets call this TEST
Add Connection to server "TEST" to server group TEST
Open a query from Server TEST , in Server Group TEST 
Observe that the Tab is correctly Colored Green.
Using the "Change" toolbar button,  Change Connection on the query tab to Server PROD
Expected Behavior: The Tab Color should change to Red
Actual Behavior: Tab color does not change
Why this is a bug: 
This behavior is incredibly dangerous. The tab color is a powerful visual cue as to the current connection.  Given this behavior , the tab is telling me it is connected to a TEST server when it is in reality connect to a production server.  If you are going to add tab coloring functionality to the application, you must ensure that the visual cue matches the state of the connection. 
This may be the way the application was desinged to work, but in that case this is a  bug in the in requirements.
If not feasible to determine the correct server group color for a tab after connection change, then at the very least the coloring should be removed altogether.

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|28.00GB (16.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
query-history|Mic|0.5.3
sql-prompt|Red|0.2.12

</details>

**Comment by cheenamalhotra** [comment] 2023-11-08 21:13
Duplicate of #24249

**Closed by cheenamalhotra** 2023-11-08 21:13 UTC
Labels: Bug, Area - Connection, Triage: Done

**Comment by jsteinbergTCALLC** [comment] 2023-11-08 22:04
Fine, it's a duplicate. Are you fixing it?
