### ISSUE TITLE
In Progress Query Lost When Saving Untitled Query

### ISSUE THREAD

**Issue by benrr101** [Microsoft/azuredatastudio#3666] opened 2019-01-03 15:42 UTC
- Azure Data Studio Version:
Version 1.2.4
Commit 1ebfd0235690ad044ed2874a02e65188f5fea01c
Date 2018-11-02T21:50:52.634Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:
1. Connect to a database
2. Create a new query --do not save it--, enter something that take a long time (I'm using a database restore script)
3. Execute the query
4. While query is still executing, save the query.

Expected: File is saved, query continues to execute, and results are still being displayed
Actual: File is saved, query execution disappears, results are gone

There's a couple open-ended questions here: 
* What's the best expected result here: Should ADS show a warning that there's a query running before saving the file? Should the results be moved over to the new tab?
* What happened to my query: Did sqltoolsservice kill the query when the untitled file was closed or did it continue to completion and leak resources?

**Comment by kburtram** [comment] 2019-01-08 01:20
This looks like a variation of https://github.com/Microsoft/azuredatastudio/issues/1876, though I agree there are some interesting concerns related to editors with executing queries vs. editors with completed queries.

**Comment by anthonydresser** [comment] 2019-02-07 00:49
I'll close as dupe of #1876 since all these scenarios are the same basic issue

**Closed by anthonydresser** 2019-02-07 00:49 UTC
Labels: bug, query editor
