### ISSUE TITLE
Incorrect App title when pinned to Start Menu

### ISSUE THREAD

**Issue by uberda** [microsoft/azuredatastudio#19133] opened 2022-04-18 00:27 UTC
Issue Type: <b>Bug</b>

When pinned to the start menu, the icon's title is "Code - OSS". If you hover over it, the pop-up title says "Azure Data Studio". 

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2022-04-18 05:11
Duplicate of https://github.com/microsoft/azuredatastudio/issues/18618, this will be fixed in the upcoming release.

**Closed by Charles-Gagnon** 2022-04-18 05:11 UTC
