### ISSUE TITLE
Escape character \ causes incorrect colour formatting

### ISSUE THREAD

**Issue by Exicle** [microsoft/azuredatastudio#10280] opened 2020-05-06 10:43 UTC
### Azure Data Studio Version:
Version: 1.17.1 (system setup)
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-30T00:16:35.943Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393
### Steps to Reproduce:
Example code:

SELECT *
FROM LoadType
WHERE CHARINDEX(**'\\' + LoadTypeName + '\\', @Filename) > 0;**

The code still runs OK but the colour formatting is a bit unnerving...

**Comment by Exicle** [comment] 2020-05-06 10:49
(I'm using this with a subsequent big chunk of SQL and the whole thing has a tinge of red to it as if it was dynamic SQL but with the actual character literals in blue/black...)

**Comment by Exicle** [comment] 2020-05-06 11:04
Workaround:
USE CHAR(92) instead of '\'

**Comment by Charles-Gagnon** [comment] 2020-05-06 13:51
Duplicate of https://github.com/microsoft/azuredatastudio/issues/10208 - see that for a workaround to revert to older version of the language file.

**Closed by Charles-Gagnon** 2020-05-06 13:51 UTC
Labels: Area - Query Editor, Bug, Triage: Needed
