### ISSUE TITLE
Kusto: cannot select database when creating a connection, need to reopen connection after creation

### ISSUE THREAD

**Issue by baselsalam** [microsoft/azuredatastudio#12666] opened 2020-09-29 21:13 UTC
- Azure Data Studio Version: v1.22.0
- Kusto extension version v1.1.0

Steps to Reproduce:

1. File > New Notebook.
2. Kernel > Kusto
3. Attach to > Change Connection
4. Enter cluster info, choose default auth type (user auth) and click on Database dropdown. You don't see a list of databases and cant select them.
5. However, if you come back and try to modify the connection under 'Recent connections', you can see the list of Databases and can select one.

**Comment by chlafreniere** [comment] 2020-10-09 20:50
This is almost certainly not a notebooks issue. Changing area to kusto to triage.

**Comment by MsSQLGirl** [comment] 2020-10-28 18:23
@JustinMDotNet / @gupta1 - FYI

**Comment by JustinMDotNet** [comment] 2020-10-29 22:00
Is this issue a duplicate of this?
https://github.com/microsoft/azuredatastudio/pull/13115/files

**Closed** 2020-11-16 19:24 UTC
Labels: Area - Kusto, Bug, Triage: Done
