### ISSUE TITLE
Unable to recompare after change of options

### ISSUE THREAD

**Issue by MartinRyx** [microsoft/azuredatastudio#24395] opened 2023-09-13 09:12 UTC
Type: <b>Bug</b>

1. Starta a Schema Compare
1. Click the Options button 
1. Change a random setting
1. Click OK

I now get a question if I want to recompare since I changed the option. The problem is there is no Yes-button, only a No-button

![image](https://github.com/microsoft/azuredatastudio/assets/9428639/ccb91ff2-4caa-4671-a64e-0de5e0536068)

After that I can make a new comparison with the changed settings by clicking the Compare-button, but it's a bit confusing

Extension version: 1.20.0
Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (13.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment] 2023-09-13 16:22
Duplicate of https://github.com/microsoft/azuredatastudio/issues/24120. The fix for this will be in the September release

**Closed by kisantia** 2023-09-13 16:22 UTC
