### ISSUE TITLE
No Way to Recover from MFA Login Token Retrieval Failure 

### ISSUE THREAD

**Issue by bradwestness** [microsoft/azuredatastudio#12637] opened 2020-09-25 19:53 UTC
- Azure Data Studio Version: 1.22.0

Steps to Reproduce:

1. I'm not really sure how to reproduce this, but I have a bunch of saved connections in my settings.json, which I added by using the UI. They are all Azure SQL Managed Instance databases, although I just added them by entering the server names, I didn't go through the Azure panel. They look like this:

```json

"datasource.connections": [    
    {
        "options": {
            "connectionName": "Dev",
            "server": "<servername>.database.windows.net",
            "database": "",
            "authenticationType": "AzureMFA",
            "user": "<my MSA email>",
            "password": "",
            "connectTimeout": 30,
            "applicationName": "azdata",
            "azureAccount": "<my MSA email>",
            "groupId": "<a guid>",
            "databaseDisplayName": ""
        },
        "groupId": "<a guid>",
        "providerName": "MSSQL",
        "savePassword": true,
        "id": "<a guid>"
    },
    ...
```

They are authenticated using the Azure AD account associated with my corporate MSA. I can still authenticate and log in using SSMS and that all works fine.

As soon as Azure Data Studio opens, I get an error like this:
![image](https://user-images.githubusercontent.com/1802434/94309442-b6039f00-ff3d-11ea-8985-4f1f87d6657e.png)

If I look in the console, I see an error that says:
```json
Response error! - {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2020-03-24T15:16:55.9202886Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2020-09-04T15:03:30.0000000Z'.\r\nTrace ID: <a guid>\r\nCorrelation ID: <a guid>\r\nTimestamp: 2020-09-25 19:44:52Z","error_codes":[50173],"timestamp":"2020-09-25 19:44:52Z","trace_id":"<a guid>","correlation_id":"<a guid>","error_uri":"https://login.microsoftonline.com/error?code=50173"}
```

My domain password did expire and I had to change it earlier this month so it seems like that's probably related. However, the real issue is that there doesn't seem to be any way to get out of this state in Azure Data Studio. 

![image](https://user-images.githubusercontent.com/1802434/94309828-4c37c500-ff3e-11ea-8438-cf156095938f.png)

If I click the link to refresh my credentials (which, incidentally, is very hard to read on the default theme), it opens the Microsoft Account login page and then redirects me to a page that looks like this:

![image](https://user-images.githubusercontent.com/1802434/94309865-5b1e7780-ff3e-11ea-8c55-401268f4d357.png)

However when I close the window, Azure Data Studio just shows an error about being unable to retrieve a token:

![image](https://user-images.githubusercontent.com/1802434/94309912-6d98b100-ff3e-11ea-8f78-65bf251602f0.png)

If I look in the developer tools then, I see this:

![image](https://user-images.githubusercontent.com/1802434/94310199-d97b1980-ff3e-11ea-8c9c-bdb6d33f4c59.png)

If I click "Add an account" in the Account drop-down, the same thing happens. There's no way to remove the existing account that I can find.

**Comment by dzsquared** [comment] 2020-09-25 21:15
if you click the "person" icon in the lower left, are you able to add/remove any Azure AD accounts from that pane? I have previously been stuck in a loop where removing and adding the account from that pane cleared it up.

**Comment by bradwestness** [comment] 2020-09-26 00:55
Ah, yep that did it.

**Comment by dzsquared** [comment] 2020-09-26 01:12
I've seen this a few times - perhaps we should consider opening the pane under certain AAD connection failure conditions? Or otherwise improve the discoverability of it? 🤔

**Comment by bradwestness** [comment] 2020-09-26 01:29
Yeah, I'm glad it's working again, but there's definitely some improvements that could be made around showing meaningful/actionable errors and suggesting this as the fix. The notification that's just an empty set of curly braces and the "Token retrieval failed with error" message don't really drive you in the direction of resolving the issue at all, in addition to the "Refresh your credentials" link being almost impossible to read in the default theme and evidently not being sufficient to actually resolve the issue.

**Comment by SQLDBAWithABeard** [comment] 2020-10-05 10:46
Thank you so much @dzsquared  and @bradwestness - Just faced this exact experience myself, removing and readding via the

![image](https://user-images.githubusercontent.com/6729780/95070547-2f4e7f00-0700-11eb-959f-82989693c66c.png)

Accounts worked like a charm (added link because I like pictures and it may help others

Interestingly I could access the instance from the Azure connections in the Serve Connection pane but couldn't do the compare which was what I needed!

**Comment by SQLDBAWithABeard** [comment] 2020-10-05 10:49
This should definitely be improved. Suggestions

- Get the token from a single place?? Enable readding in the server connection to refresh that token?
- A better error message than open Dev Tools? (This puts off generic users)
- Opening the Azure Accounts pane but will also need some instructions
- Add to the documentation

**Comment by smathew-relativity** [comment] 2020-11-10 23:02
Hey all, I'm stuck in this loop today after resetting my AD password last week. I removed the Microsoft account, closed the application, reopened and tried to reconnect, but no luck. Still getting this error 
![Screen Shot 2020-11-10 at 4 56 40 PM](https://user-images.githubusercontent.com/34111345/98743942-78849500-2376-11eb-9199-299d4b1c988a.png)

**Comment by dzsquared** [comment] 2020-11-10 23:28
@smathew-relativity if you open developer tools (ctrl+shift+i), can you share the error message from there?

**Comment by smathew-relativity** [comment] 2020-11-10 23:30
![Screen Shot 2020-11-10 at 5 30 13 PM](https://user-images.githubusercontent.com/34111345/98746114-70c6ef80-237a-11eb-9dec-a4da56e869f4.png)

**Comment by bijeebuss** [comment] 2020-11-30 21:35
same thing happened to me but deleting the account and adding it back fixed it

**Comment by smathew-relativity** [comment] 2020-12-01 02:13
deleting the account and adding it back didn't help. i ended up removing the app and reinstalling it, that did the trick

**Comment by ShaneCourtrille** [comment] 2020-12-16 16:55
Expecting the user to remove the account and add it back is just plain silly.  Why not just tell the user you need to refresh the token (so they're not surprised by the browser opening up) and then run that process?

**Comment by janpieterz** [comment] 2020-12-20 12:35
A company policy password reset also caused this to trigger. Removing and adding the account again did not resolve it in my case either.

> Response error! - {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2020-09-18T09:34:42.3391599Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2020-12-16T10:03:16.0000000Z'.\r\nTrace ID: 1b46f4c8-1912-405c-911e-2ed9b2ca0d00\r\nCorrelation ID: 313defce-3c84-47fd-b831-cec1bb1efdd2\r\nTimestamp: 2020-12-20 12:29:53Z","error_codes":[50173],"timestamp":"2020-12-20 12:29:53Z","trace_id":"1b46f4c8-1912-405c-911e-2ed9b2ca0d00","correlation_id":"313defce-3c84-47fd-b831-cec1bb1efdd2","error_uri":"https://login.microsoftonline.com/error?code=50173"}

**Comment by Dlutchy** [comment] 2020-12-27 03:37
I have Azure Data Studio v1.25.1 and have not used it to logon to Azure SQL Database for over 90 days. I am getting the same error as @smathew-relativity.

**Comment by cssuh** [comment] 2021-01-04 17:45
Some users have mentioned that removing and re-adding their account from the accounts pane does not work. Please try this:


Remove your account from the accounts pane.  However, once you have deleted the account do not re-add it through the accounts pane.  Instead, select the "New Connection" icon ![Screen Shot 2021-01-04 at 12 41 24 PM](https://user-images.githubusercontent.com/18150417/103563081-29487580-4e8a-11eb-84b4-06997f6e744b.png) and then in the "New Connection" screen select "Add an Account" and re-add your Azure account there. ![Screen Shot 2021-01-04 at 12 42 12 PM](https://user-images.githubusercontent.com/18150417/103563166-454c1700-4e8a-11eb-8727-45e98f949e1f.png)

**Comment by robjackstewart** [comment] 2021-01-08 12:50
I think this is a caching issue.

Like others above, I changed my password and was then unable to access azure hosted databases nor their information. I attempted to reauthenticate to no success, and I tried re-adding the account which also did not solve the problem. However, Removing the account, running the **"clear azure account token cache"** command, then re-adding the account resolved this issue.

**Comment by allan-stewart** [comment] 2021-02-10 22:35
This was a huge pain for me as well. I ended up reinstalling to fix because fussing within the app was more painful than just starting over.

**Comment by cesarfp** [comment] 2021-03-05 16:02
> Thank you so much @dzsquared and @bradwestness - Just faced this exact experience myself, removing and readding via the
> 
> ![image](https://user-images.githubusercontent.com/6729780/95070547-2f4e7f00-0700-11eb-959f-82989693c66c.png)
> 
> Accounts worked like a charm (added link because I like pictures and it may help others
> 
> Interestingly I could access the instance from the Azure connections in the Serve Connection pane but couldn't do the compare which was what I needed!

This just happened to me as well and it worked. Thank you everybody.

**Comment by recbrasil5** [comment] 2021-05-21 19:22
> I think this is a caching issue.
> 
> Like others above, I changed my password and was then unable to access azure hosted databases nor their information. I attempted to reauthenticate to no success, and I tried re-adding the account which also did not solve the problem. However, Removing the account, running the **"clear azure account token cache"** command, then re-adding the account resolved this issue.

what is the `clear azure account token cache` command?

**Comment by robjackstewart** [comment] 2021-05-21 20:23
> > I think this is a caching issue.
> > Like others above, I changed my password and was then unable to access azure hosted databases nor their information. I attempted to reauthenticate to no success, and I tried re-adding the account which also did not solve the problem. However, Removing the account, running the **"clear azure account token cache"** command, then re-adding the account resolved this issue.
> 
> what is the `clear azure account token cache` command?

@recbrasil5 you should be able to find it by pressing Ctrl+P and typing it

**Comment by recbrasil5** [comment] 2021-05-24 19:51
> > > I think this is a caching issue.
> > > Like others above, I changed my password and was then unable to access azure hosted databases nor their information. I attempted to reauthenticate to no success, and I tried re-adding the account which also did not solve the problem. However, Removing the account, running the **"clear azure account token cache"** command, then re-adding the account resolved this issue.
> > 
> > 
> > what is the `clear azure account token cache` command?
> 
> @recbrasil5 you should be able to find it by pressing Ctrl+P and typing it

thank you!  I ended up having to delete my account and re-add it.  Then it worked; hopefully this wasn't just a result of changing my password or this will be a recurring problem until it gets fixed.

**Comment by lehmus** [comment] 2021-06-24 14:01
I had this problem when trying to connect "directly" from the script window. Removing and re-adding the account didn't work, neither did deleting the Azure account cache from local files. I have to connect to the database from the Connections pane on the left first, and then connect the script windows individually. When the token expires, I just disconnect and reconnect to the server from the Connections pane. Has worked for me so far.

**Comment by Ian1971** [comment] 2021-07-28 08:32
This issue really stops me from going all in with Azure Data Studio. The account thing does fix it.

**Comment by Ian1971** [comment] 2021-11-08 14:22
This has been an issue for ages. I can't recommend data studio to colleagues with this kind of flaw.

**Comment by Shaul-Z** [comment] 2021-12-14 15:50
Same issue.
I tried all the above suggestions nothing helped...
I'm using MSSQL extension in VSCODE. Please Help! problem started 12-12-2021, until then everthing worked just fine.

**Comment by Charles-Gagnon** [comment] 2021-12-14 17:01
@Shaul-Z This issue (and repo) is for Azure Data Studio, not the VS Code extension. Any issues for that should be reported here : https://github.com/Microsoft/vscode-mssql

**Comment by peteryates** [comment] 2022-02-02 11:15
On Windows machines the steps I take are:

* navigate to `%AppData%`\azuredatastudio\Azure Accounts
* delete `azureTokenCache_azure_publicCloud`
* open Azure Data Studio and reconnect

**Comment by ShaneCourtrille** [comment] 2022-02-03 15:48
@peteryates And the fact you have to do that is so insanely stupid for an issue that has been known about for how long now?

**Comment by pg-hps** [comment] 2023-02-08 15:03
Hi - I am facing a similar issue but it's even more strange. I was able to use Azure with MFA in the past but now I am not able to login to my SQL MI as I can't add an account. I tried deleting the cached connections using the below steps but I still have the same issue 

navigate to %AppData%\azuredatastudio\Azure Accounts
delete azureTokenCache_azure_publicCloud
open Azure Data Studio and reconnect

Can you please help ? 

Here's a screenshot ( when I click on the refresh account, nothing happens and I my colleague just installed this and when he clicks on add account nothing happens either )

**Comment by cheenamalhotra** [comment] 2023-04-26 01:54
Closing as the issue is too generic and multiple improvements have been made in this area.
For any concerns with adding account please refer to [known possible issues](https://learn.microsoft.com/en-us/sql/azure-data-studio/azure-connectivity?view=sql-server-ver16#common-authentication-issues) or open a new issue with relevant Azure-Account logs attached.

**Closed by cheenamalhotra** 2023-04-26 01:54 UTC
Labels: Bug, Area - Azure, Pri: 3, Triage: Done, Impact: Live site, Size: S
