### ISSUE TITLE
Width of row number column too small

### ISSUE THREAD

**Issue by JipingWang** [microsoft/azuredatastudio#12062] opened 2020-09-01 18:41 UTC
Issue Type: <b>Bug</b>

Width of row number column (first) in Results pane too small. 
rows of 1-9 shown normal, but rows after 9 show three dots.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.18363

**Comment by kburtram** [comment] 2021-08-18 04:30
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/10849.  Thanks!

**Closed by kburtram** 2021-08-18 04:30 UTC
Labels: Bug, Area - Query Editor, Triage: Done
