### ISSUE TITLE
Installation and Insiders Build naming

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/azuredatastudio#4491] opened 2019-03-14 12:21 UTC
Somewhat related to #3921 but giving more context around issues experienced when trying to install both editions side-by-side...

1. Programs and Features only shows one entry. And using it seems to only uninstall the last one you installed. (I installed stable and then insiders, and only insiders was removed.)

1. Folder structure, there are a couple different directories in play but I'm not sure which ones are associated with which edition I installed on my machine:

- `%userprofile%\.azuredatastudio (this is for extensions and you will need to rename this for insiders)
- `%userprofile%\AppData\Roaming\Azure Data Studio` (only thing I've ever seen in this directory is logs)
- `%userprofile%\AppData\Roaming\azuredatastudio` (main folder for my user-level settings)

**Comment by kburtram** [comment] 2019-05-02 16:53
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/3921.

**Closed by kburtram** 2019-05-02 16:53 UTC
Labels: Area: Acquisition, Enhancement
