### ISSUE TITLE
Drag & drop of table column name (or Columns) put columnname with schemname

### ISSUE THREAD

**Issue by DashGandhi** [microsoft/azuredatastudio#18142] opened 2022-01-22 13:48 UTC
Issue Type: <b>Bug</b>

Dragging & dropping of individual ColumnName or all Columns of a Table from Connection Tab, it prepends the SchemaName to the ColumnName. 
eg Dragging & dropping a ColumnName called VNo from a Table dbo.Sales, results in dropping "[dbo].[VNo]", instead of expected "[VNo]".

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7
schema-compare|Mic|1.12.0
azdata-sanddance|msr|3.3.0

</details>

**Comment by Charles-Gagnon** [comment] 2022-01-22 22:12
Duplicate of https://github.com/microsoft/azuredatastudio/issues/18004

**Closed by Charles-Gagnon** 2022-01-22 22:12 UTC
