### ISSUE TITLE
Closing server dashboard collapses OE tree

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22803] opened 2023-04-20 18:47 UTC
1.44-insiders

1. Connect to server and expand tree
2. Open up dashboard for that server
3. Close dashboard

The tree now collapses. Closing the dashboard shouldn't affect the tree state at all.

![DashboardTreeCollapse](https://user-images.githubusercontent.com/28519865/233459538-5a17fb30-203f-44e8-9a6f-659c3890ec9c.gif)

**Comment by cheenamalhotra** [comment] 2023-04-20 20:20
Duplicate of https://github.com/microsoft/azuredatastudio/issues/22709

**Closed by cheenamalhotra** 2023-04-20 20:20 UTC
Labels: Bug, Area - Object Explorer, Triage: Needed
