### ISSUE TITLE
Database Folder not Expanding in Azure data studio on mac

### ISSUE THREAD

**Issue by hastiAu** [microsoft/azuredatastudio#13934] opened 2021-01-09 11:53 UTC
I have ADS on mac
I want to connect to server but I can't 

Everything is ok 
user pass and is created db on server
when i want to connect server after set user pass 
I see all databases on server and can choose my db 

 
<img width="503" alt="Screen Shot 2021-01-09 at 11 48 57 AM" src="https://user-images.githubusercontent.com/67632833/104090787-474d1600-528e-11eb-9cd5-9d57dab42775.png">
.48.57 AM.png

but when  I connect to server I see green button 
I see anther database name on server 
but I can't see my database and its related files

why ? 

 
 
<img width="1531" alt="Screen Shot 2021-01-09 at 7 58 46 PM" src="https://user-images.githubusercontent.com/67632833/104103069-6ad78700-52b5-11eb-9368-c8c546ba7fcb.png">

- Azure Data Studio Version:

Steps to Reproduce:

1.

**Comment by Charles-Gagnon** [comment] 2021-01-11 20:10
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12992

**Closed by Charles-Gagnon** 2021-01-11 20:10 UTC
