### ISSUE TITLE
Edit data does not save new rows when moving from a non-editable cell on the new row to the previous row

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#2574] opened 2018-09-13 20:51 UTC
- SQL Operations Studio Version: master

Steps to Reproduce:
1. Open edit data for a table with at least 1 editable column and 1 non-editable column (such as a precomputed index)
2. Create a new row, fill in the editable cell, and use tab or shift-tab or click to get to the non-editable cell, then use the arrow keys, shift-tab, or the mouse to go to the previous row

Expected behavior: The new row is saved, just like when you do the same actions from the editable cell
Actual behavior: The new row is lost

**Comment by kburtram** [comment] 2020-02-12 21:51
Let's close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/6638 and track this category of related issues there.

**Closed by kburtram** 2020-02-12 21:51 UTC
Labels: Area - Edit Data, Bug
