### ISSUE TITLE
notebook cell add cell dropdown menu items  are displayed horizontally

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10739] opened 2020-06-04 20:20 UTC
on windows, the add cell button dropdown for the cell is not showing the options vertically

![Screen Shot 2020-06-04 at 11 53 31 AM](https://user-images.githubusercontent.com/13777222/83805883-7b5fb900-a665-11ea-9459-f08d57325879.png)

the main toolbar works as expected
![Screen Shot 2020-06-04 at 11 53 20 AM](https://user-images.githubusercontent.com/13777222/83806306-2b352680-a666-11ea-9119-aa05ea41de89.png)

**Comment by Charles-Gagnon** [comment] 2020-06-04 20:39
Interesting - this doesn't repro for me...

**Comment by chlafreniere** [comment] 2020-06-04 22:22
![image](https://user-images.githubusercontent.com/40371649/83816434-39d80980-a677-11ea-9f8a-12a86150b834.png)

Doesn't repro for me, either. Let's move this out of June.

@alanrenmsft can you see if you can repro this still with latest RC bits?

**Comment by alanrenmsft** [comment] 2020-06-04 22:43
well, i can open repro this with insider build. what is the delta between master and the release branch for notebook features? anything could cause this?

**Comment by Charles-Gagnon** [comment] 2020-06-04 23:12
Yup, can confirm this repros on master for me too now. Probably the VS Code merge. Assigning to @halerankin to look at

**Comment by halerankin** [comment] 2020-06-05 15:39
This is a Windows only issue, right?

**Comment by chlafreniere** [comment] 2020-06-05 20:22
Looks like this was caused by:

https://github.com/microsoft/vscode/commit/01b37c6b5d991f959f0b31a58055fecf6bc52729#diff-13d0c92933a37f90318d68f52e3c22d0

with the `anchorAsContainer` property in dropdown.ts being set to true in all cases.

There's a fix that went in as part of https://github.com/microsoft/vscode/commit/f8577ad1b6d8b5ed0bd0fade90aec430e0bada1e

This may fix our issue; let's re-evaluate when we get this commit as part of a vscode merge. Was able to verify that not hardcoding `anchorAsContainer` to true does fix this:

![image](https://user-images.githubusercontent.com/40371649/83919474-854dee80-a72f-11ea-88ad-ae269de76612.png)

**Comment by chlafreniere** [comment] 2020-07-06 19:45
This has since been fixed.

**Closed by chlafreniere** 2020-07-06 19:45 UTC
Labels: Area - Notebooks, Bug, Triage: Done
