### ISSUE TITLE
Cannot view currently running queries in top tabs

### ISSUE THREAD

**Issue by drusbasanRD** [microsoft/azuredatastudio#19726] opened 2022-06-14 16:40 UTC
Issue Type: <b>Feature Request</b>

Would be nice to easily view which tabs have queries that are executing. Most of the time if there's a long running query, I'll work on something else on another tab, and have no idea when the other query finishes or errors out. If there's multiple tabs open, it's hard sometimes to even find which tab has the long running query.

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

**Comment by alanrenmsft** [comment] 2022-06-14 17:28
dupe of #9334

**Closed by alanrenmsft** 2022-06-14 17:28 UTC
Labels: Area - Query Editor
