### ISSUE TITLE
Program eating all available memory and causing instability?

### ISSUE THREAD

**Issue by sassora** [microsoft/azuredatastudio#9628] opened 2020-03-14 09:31 UTC
- Azure Data Studio Version: 1.15.1
- WIndows 10 Enterprise, 8GB RAM

I was running a few left joins and counts on about 500k rows of data, no heaving lifting. The lack of RAM available affects the performance of the program as a whole. E.g. not showing files in version control, intellisense / code suspension, lists of extensions in the marketplace not showing.

Does looking at the processes running help? I understand that task manager only shows "private bytes" (memory allocated to the process that cannot be shared). So I downloaded process explorer to see the "working set bytes". These seem to account for why I am seeing 90% RAM usage when that seems high if you only consider task manager memory values for individual processes.

This seems like issue #3717, reported early last year, in that the MicrosoftSQLToolsServiceLayer.exe makes a significant contribution to memory usage. Here is the task manager output:
![Untitled](https://user-images.githubusercontent.com/22264544/76678034-5dd20480-65cc-11ea-9b0b-0ebe76502108.png)
)

**Comment by kburtram** [comment] 2021-08-18 00:17
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/3717.  Thanks for reporting this bug!

**Closed by kburtram** 2021-08-18 00:17 UTC
Labels: Bug, Area - Performance, Area - Shell, Triage: Done
