### ISSUE TITLE
Connection Dialog shows wrong options

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#23949] opened 2023-07-20 20:44 UTC
- Azure Data Studio Version: 1.44.1
- OS Version: 13.4.1 Ventura (Intel based Mac)

Steps to Reproduce:

1. Try to connect to a DB that will throw an error (for example, put wrong servername)
2. Error message will show up
3. Close Connection Dialog
4. Open Connection Dialog again and it will show the Azure Active Directory options even though SQL Login is selected.
<img width="2032" alt="Screenshot 2023-07-20 at 1 28 21 PM" src="https://github.com/microsoft/azuredatastudio/assets/18150417/21425e43-032d-4052-84c2-4caedb4da090">

**Comment by cheenamalhotra** [comment] 2023-07-21 03:41
Duplicate of https://github.com/microsoft/azuredatastudio/issues/11727

**Closed by cheenamalhotra** 2023-07-21 03:41 UTC
Labels: Bug, Area - Connection, Triage: Done
