### ISSUE TITLE
Cannot copy/paste data anymore

### ISSUE THREAD

**Issue by cameronj86** [microsoft/azuredatastudio#21316] opened 2022-11-28 17:27 UTC
Issue Type: <b>Bug</b>

When I run a query, I cannot take the data out of ADS. Also, I cannot even try a work around and 'save as a CSV' without the system hanging indefinitely. 

I like the software as a concept but it is extremely buggy. Previously I couldn't copy w/ headers without the system crashing and that was 'fixed' for a release or so before things got worse and now no data can be exported from ADS.

It is hard for me to recommend it to anyone because I never know what will stop working with every updated release and so I have to revert to SSMS yet again. 

Azure Data Studio version: azuredatastudio 1.40.0 (3fbaa3de931ef433090fe3deb8c89cba99d7952b, 2022-11-11T22:47:05.361Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (0.18GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
machine-learning|Mic|0.12.0
azdata-sanddance|msr|4.0.1

</details>
cause it was too large to send. Please paste.

**Comment by alanrenmsft** [comment] 2022-12-06 19:15
@cameronj86 could you please share more information?
1. what is the size of data were you working with. number of rows and columns.
2. have you tried to select the cells and copy it directly?

**Comment by Spinks90** [comment] 2023-01-16 13:06
I have a similar related issue, and was unsure wether to create a new ticket or add to this.

Gathering all this information for the ticket has made me realise that it's the copy/paste feature is extremely delayed in certain circumstances rather than not working. It can take up to like 30 seconds for the value to get copied. I'm using VPN for my work which is based in the UK and the server I'm querying is in CN.

I'm using 
```
Version: 1.40.2 (system setup)
Commit: 661384637db384fe5d4e6224069adbe708580b16
Date: 2022-12-22T22:17:02.658Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Windows_NT x64 10.0.19045
```

**Scenario:**
I've also noticed once the values are not copyable, you see the results in the grid. So, you can manually type them out if you wanted. Click on the "Messages" tab then click on the "Results" tab and the values go blank.

![image](https://user-images.githubusercontent.com/63308868/212677129-313bed5b-5579-4cca-9c31-f8bd2c2f10f6.png)

Then around 5 seconds later the blanks values will populate again and now they're copyable.

I'm taking guess but I think once you click to copy on the results grid that it must go back to the server for something before you are allowed to copy the value and since my connection has high latency that's causing the issue. Ping to the server is around 302ms on average with 1 packet loss out of 100 packets.
Or
Once the grid has been populated visually, there is additional work in the background with the server before it's allowed to be copied.

I hope this helps identify the problem. I'm happy to provide any additional information. Thanks.

**Comment by alanrenmsft** [comment] 2023-06-07 19:52
I am going to resolve this as a dupe of https://github.com/microsoft/azuredatastudio/issues/23264, I have made some improvements to the copy data feature, please see the PR associated with it.

**Closed by alanrenmsft** 2023-06-07 19:52 UTC
Labels: Bug, Area - Query Editor, Needs More Info, Triage: Done
