### ISSUE TITLE
Jupyter Book - SQL Server 2019 Guide links don't work in a tab resulted from Preview Readme.md

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9286] opened 2020-02-24 02:10 UTC
As I was browsing through some of the _SQL Server 2019 Guide Jupyter book_, I’ve come across the following notebook where the links under the _Related_ section didn’t work in my environment:
C:\Users\username\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\monitor-k8s\tsg009-get-nodes.ipynb

To repro: 
1.	Open _Jupyter Books: SQL Server 2019 Guide_ from Command Palette in ADS. 
2.	From the Welcome page, click on _6. Monitor Kubernetes_, which should open “Preview readme.md” for _SQL Server Big Data Cluster Kubernetes monitoring notebooks_.
3.	Click on _TSG009 – Get nodes (Kubernetes)_, which should open a new notebook in a new tab. 
4.	From this TSG009 notebook, scroll down to _Related_ cell, then click on _TSG006 - Get system pod status_ or _TSG007 - Get BDC pod status_. ADS doesn’t open the file. 

![image](https://user-images.githubusercontent.com/6405919/75124706-d137c480-5665-11ea-94fe-aaac6545ab5a.png)

The linked TSGs do exist though, i.e. below is an example for TSG006. 
![image](https://user-images.githubusercontent.com/6405919/75124733-f0365680-5665-11ea-82fb-2d78dac4dacb.png)

However, if I go to TSG009 directly from the Jupyter Book viewlet, I can click on the links mentioned in the _Related_ cell. The links as shown when I hover over TSG006 and TSG007 is the same as the links of TSG009's that I opened from _Preview Readme.md_ tab. 
Note: In my scenario, if I already had TSG006 opened (that originated from _Preview Readme.md_), browsing _Related_ links from the TSG006 didn't work either.  However, if I closed the tab that resulted from _Preview Readme.md_, I can open TSG006 fine. 
**My rough guess here is that perhaps a tab that is a result of opening from Preview readme.md might not be able to open some links.**

I can repro the above from the _Diagnose_ Preview Readme.md and navigating to _TSG078 - Is cluster healthy_ which has a number of _Related_ links which don’t work on this tab.

ADS Versions tested – both Insiders and the public version.
Version: 1.16.0-insider (user setup)
Commit: 7eef23f2321a8f95220c974209561593f802d918
Date: 2020-02-20T05:49:05.139Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment] 2020-02-24 16:10
@MsSQLGirl - This is by design - Notebooks won't open links until they're trusted. (markdown preview files don't have this restriction so the links will always work)

@chlafreniere Has there been any discussion around making this behavior more obvious? Some mouse icon or text or something to indicate that the link is blocked? It's definitely unintuitive for new users and while easy to solve with a quick google search is bound to cause confusion as Notebooks become more widely adopted.

**Comment by MsSQLGirl** [comment] 2020-02-24 18:27
@Charles-Gagnon  - thanks for this! (Looks like it's something that I seem to be forgetting quite a bit when I'm tired 😅). 
Agreed, making the behavior more obvious would be handy.

**Comment by chlafreniere** [comment] 2020-03-06 02:05
We've since talked about this quite a bit this week. We have new trusted behavior for markdown-only notebooks, and for notebooks where cells have been executed. Because of this, let's close this issue for now. There are a lot of good ideas, but we should track any customer asks separately, as this particular issue has been solved 😄

**Closed by chlafreniere** 2020-03-06 02:05 UTC
Labels: Area - Notebooks, Bug, Triage: Done
