### ISSUE TITLE
Jupter Notebook|Kernal: SQL|Change Connections

### ISSUE THREAD

**Issue by yeliangAD** [microsoft/azuredatastudio#18542] opened 2022-02-24 00:16 UTC
Issue Type: <b>Bug</b>

Hi, 

I get an error 100% of the time when switching to another connection in jupter notebook using sql kernal.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0

</details>

**Comment by Charles-Gagnon** [comment] 2022-04-07 17:03
I'm going to close this since we haven't seen any other reports and without logs are unable to determine what the issue is. If you can provide more information let us know and we can re-open as necessary!

**Closed by Charles-Gagnon** 2022-04-07 17:03 UTC
Labels: Area - Notebooks, Triage: Done, Needs Logs
