### ISSUE TITLE
"Search" has to be expanded in the limited functionality beyond just the connections.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#4792] opened 2019-04-01 20:49 UTC
Issue Type: <b>Bug</b>

Search is not working across Azure servers. We need the functionality for Search to be expanded beyond local connections to servers in Azure. Also search right now is pretty limiting and we need to be able to search across files as well if we expand to ADLS.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/22312581/55358760-fbe4c180-5484-11e9-9c7d-b5028dd98b38.png">

Azure Data Studio version: Azure Data Studio 1.6.0-insider (a4c2463b2f63c495f2840cefea6e74eda024777d, 2019-04-01T07:14:32.930Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|-psn_0_4895915|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.390
azuredatastudio-postgresql|Mic|0.1.0
import|Mic|0.7.0

</details>

**Comment by kburtram** [comment] 2019-04-24 01:42
Closing as duplicate of #860

**Closed by kburtram** 2019-04-24 01:42 UTC
Labels: Area: Data Explorer, Enhancement
