### ISSUE TITLE
Support searching databases within a server

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#2934] opened 2018-10-17 20:23 UTC
Issue Type: <b>Bug</b>

Support searching within a the databases within a server from the servers panel.

Also, consider searching tables within a database from the servers panel.

Currently users who want to search database and tables within a database must do this from the search panel within the Manage page for the server.

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.99GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by kburtram** [comment] 2018-10-22 19:48
We currently recommend using Redgate SQL Search to search through active database connections.  It would be great to have extensibility point in OE and the Search viewlet so that extensions could provide this functionality.

**Comment by kburtram** [comment] 2018-11-14 00:57
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/2634.

**Closed by kburtram** 2018-11-14 00:57 UTC
Labels: object explorer, suggestion
