### ISSUE TITLE
Saving an Untitled file Causes Query Editor to disconnect

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#6585] opened 2019-08-05 00:18 UTC
- Azure Data Studio Version: 1.9.0

Steps to Reproduce:

1.  Connect to server
2. Open new query 
3. Write query
4. Save query (ctrl + S)
5. Query window disconnects from the server

**Comment by alanrenmsft** [comment] 2019-08-05 18:46
dupe of #1876

**Closed by alanrenmsft** 2019-08-05 18:46 UTC
Labels: Bug
