### ISSUE TITLE
Clicking on a notebook in git changes viewlet gives error...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7567] opened 2019-10-08 16:07 UTC
Issue Type: <b>Bug</b>

Could not start session: ENOENT: no such file or directory, unlink 'C:\Users\<blah>\AppData\Roaming\jupyter\kernels\sparkkernel\kernel.json'

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (cacbcb54156f4748a0a2d3181f9fc0ad16805b13, 2019-10-07T07:56:20.452Z)
OS version: Windows_NT x64 10.0.18995

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (12.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by Charles-Gagnon** [comment] 2019-10-08 16:16
Looks like a dupe of https://github.com/microsoft/azuredatastudio/issues/7560 so closing this one, thanks for verifying this though @uc-msft!

@chlafreniere @corivera Did anything change here recently that might be causing this?

**Closed by Charles-Gagnon** 2019-10-08 16:16 UTC
