### ISSUE TITLE
Clicking cell with empty content In Results Grid  Opens new blank tab

### ISSUE THREAD

**Issue by jsteinbergTCALLC** [microsoft/azuredatastudio#24935] opened 2023-11-09 22:23 UTC
Type: <b>Bug</b>

repro
Connect to a SQL Server db
Execute this statment:
select ''  as col
observe result grid with cell containing no content
Click on the cell
Observe that a new Editor Tab is opened, with the title Untitled-1, and this becomes the active tab.
Expected behaviour - Should not do this!

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|28.00GB (13.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
query-history|Mic|0.5.3
sql-prompt|Red|0.2.12

</details>

**Comment by kisantia** [comment] 2023-11-09 23:16
looks related to https://github.com/microsoft/azuredatastudio/issues/24929

**Comment by cheenamalhotra** [comment] 2023-11-16 02:40
Closing as the issue is addressed in the Insiders build, and fix will be available in the next milestone release.

**Closed** 2023-11-16 02:40 UTC
Labels: Bug, Area - Query Editor
