### ISSUE TITLE
BDC dashboard shows spinning circles for some errors...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7898] opened 2019-10-22 19:04 UTC
![ads-circles](https://user-images.githubusercontent.com/10999577/67321166-0d92c280-f4c4-11e9-97a6-69c21f754b12.PNG)
Issue Type: <b>Bug</b>

If for some reason the connection fails, all you get is spinning circles. To clarify, this was to a server with valid connection. So different from similar bug that happened while connecting to non-existent endpoint.

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (65fb77ef5ce93fa1090033fe31606138b8059bbc, 2019-10-22T10:25:42.157Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7-8890 v2 @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|24.00GB (17.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by uc-msft** [comment] 2019-10-22 19:19
One reason why this happens is if the user does not have permission to the controller endpoint. This would be the case for pretty much any AD user that is not part of the bdc admins group. So we should fail gracefully, and render UI with some appropriate message indicating some parts of the UI is not available due to permissions.

**Comment by Charles-Gagnon** [comment] 2019-10-22 21:04
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/7721

**Closed by Charles-Gagnon** 2019-10-22 21:04 UTC
Labels: Area - Big Data Cluster, Bug, Triage: Needed
