### ISSUE TITLE
Save is broken for the new notebooks

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#3444] opened 2018-12-05 00:26 UTC
![image](https://user-images.githubusercontent.com/44002319/49481765-32fddb80-f7e1-11e8-97ca-dd328877ea75.png)

Steps to Reproduce:

1. Connect to a sever and create a new notebook
2. Add some random content.
3. Hit save button.

**Comment by kevcunnane** [comment] 2018-12-05 00:32
Dupe of #3432

**Closed by kevcunnane** 2018-12-05 00:32 UTC
Labels: bug, notebooks
