### ISSUE TITLE
Provide a command that display a diagram describing the database (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#4942] opened 2019-04-09 17:37 UTC
When you are learning about or documenting a database it is great to have a diagram (e.g, ER diagram) of the database.

It would be great to have the ability to create a database diagram from for a database using ADS.

**Comment by gengelbms** [comment] 2019-04-09 18:16
Duplicate of Please add database diagramming (#1752)

**Comment by kburtram** [comment] 2019-04-24 01:54
Closing as duplicate of #1752

**Closed by kburtram** 2019-04-24 01:54 UTC
Labels: Area: Extensibility, Enhancement
