### ISSUE TITLE
Copy with headers is changing to order of the values columns

### ISSUE THREAD

**Issue by lberrocal** [microsoft/azuredatastudio#8282] opened 2019-11-08 21:43 UTC
Issue Type: <b>Bug</b>

1) Create a temporary table for the session like #temp (1 varchar column)
2) Insert some data on it (in my case 700 records)
3) select * of a Left join with a 13 column table on a varchar column with the same name (not sure if indexed or not)
4) On the results tab, select 15 records, copy with headers.
5) Paste the result of the copy on an excel file or a notepad

While in the the results view you'll have something like this:
Col1 Col2 Col3 Col4
Val1 Val2 Val3 Val4
Val1 Val2 Val3 Val4
Pasting it will mix the order of the column values
Col1 Col2 Col3 Col4
Val1 Val4 Val2 Val3
Val1 Val4 Val2 Val3

It's also happening with regular copy, comy as csv seems to work fine.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.2

</details>

**Comment by Charles-Gagnon** [comment] 2019-11-08 21:50
Duplicate of #8210

This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release. Sorry about the inconvenience!

**Closed by Charles-Gagnon** 2019-11-08 21:50 UTC
