### ISSUE TITLE
AsyncServerTree - Dragging tree items expands connection nodes as they're dragged over

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11886] opened 2020-08-20 17:18 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. Place a server inside a server group.
2. Drag and drop the server out of the test group to remove it from the group.

Expected - Should be able to move a server out of a group by dragging out

Actual - Not possible now, and other servers that are hovered on while dragging, get connected to.

**Comment by Charles-Gagnon** [comment] 2020-08-20 18:26
From your description I believe this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/11874. 

I'm going to update it to refer to the dragging connection issue instead since that's a separate thing.

**Closed** 2020-08-25 01:07 UTC
Labels: Area - Data Explorer, Bug, Triage: Done
