### ISSUE TITLE
a bar with run button is disappeared 

### ISSUE THREAD

**Issue by emmaziinggg** [microsoft/azuredatastudio#16929] opened 2021-08-29 15:22 UTC
Issue Type: <b>Bug</b>

a bar with run button is disapeared on my Azure Data Studio window. Pls help. 
I cannot run any query now.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:13:05.032Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
datavirtualization|Mic|1.12.0
import|Mic|1.3.1
query-history|Mic|0.1.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-08-29 17:47
Could you please attach a screenshot of the issue?

If this is for a new query window (or opening an existing .sql file) does the issue still occur if you open a new query window/file?

**Comment by emmaziinggg** [comment] 2021-09-03 03:49
@Charles-Gagnon 
Thank you.
For your question:
It's ok with new query window 
![image](https://user-images.githubusercontent.com/89739609/131947792-62a03355-8d53-4126-9394-4aaf803fd670.png)

But It occurs when I save a new file or open an existing .sql file. 
![image](https://user-images.githubusercontent.com/89739609/131947692-e120fa2d-ad22-4c3b-8f9b-ab298dd0413a.png)

**Comment by alanrenmsft** [comment] 2021-09-03 17:49
@emmaziinggg looks like you are not using the latest ADS, please upgrade to 1.32 and see whether this still repro.

**Comment by Charles-Gagnon** [comment] 2021-09-03 18:45
@emmaziinggg If you're still seeing this issue after updating please follow these steps so we can get some additional logs : 

1. Download a private build of ADS with some extra logging I added : https://sqltools.blob.core.windows.net/public/azuredatastudio-win32-x64.zip
1. Unzip it 
2. Close all other instances of ADS
3. In the unzipped folder run `azuredatastudio-insiders.exe`
4. Open up an editor in a way that causes it to not display the toolbar
5. Run the `Developer: Open Logs Folder` command
6. Zip up the entire contents of that folder and then either attach them to this issue or e-mail them to me at chgagnon@microsoft.com

**Comment by kburtram** [comment] 2021-09-22 21:36
Closing based on previous suggestions.  Please updated to latest ADS version and let us know if the issue reproduces.  If so, please provide additional log data as requested above.  Thanks!

**Closed by kburtram** 2021-09-22 21:36 UTC
Labels: Bug, Area - Query Editor, Needs More Info
