### ISSUE TITLE
Change Order of Server Groups

### ISSUE THREAD

**Issue by rgmane** [microsoft/azuredatastudio#15017] opened 2021-04-07 12:58 UTC
It is not currently possible to drag-rearrange server groups. To change the order of custom server groups, the user must delete and remake the groups in the desired sequence. It is possible to drag and drop server groups inside one another, but not to drag them above and below to change their order.

Change the UI to allow the order to be altered by moving server groups above and below.

Create a button that opens the settings in a text file for modification

![image](https://user-images.githubusercontent.com/82099055/113869982-57866b80-977f-11eb-9512-993a868c4257.png)

**Comment by Charles-Gagnon** [comment] 2021-04-07 16:46
As a workaround you can also modify the settings file directly.

1. Run the `Preferences: Open Settings (JSON)` command
2. Find the `datasource.connectionGroups` section
3. Re-order the groups there as desired
4. Close and re-open ADS

The groups should now be in the new order.

**Comment by rgmane** [comment] 2021-04-07 21:45
That worked. Thanks @Charles-Gagnon

**Comment by abist** [comment] 2021-04-23 20:46
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/167

**Closed by abist** 2021-04-23 20:46 UTC
Labels: Area - Data Explorer, Enhancement, Triage: Done
