### ISSUE TITLE
Dashboard shows incorrect OS Version

### ISSUE THREAD

**Issue by abist** [Microsoft/azuredatastudio#4735] opened 2019-03-27 21:28 UTC
- Azure Data Studio Version: master

Steps to Reproduce:

1. Open Server Dashboard

**Expected** - OS Version of the server in details

**Actual** - Lots of extra details. Screenshot attached -

![Capture](https://user-images.githubusercontent.com/6411451/55113457-8354be00-509c-11e9-9a2d-302203abfd37.JPG)

**Comment by kburtram** [comment] 2019-04-23 23:38
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/2793

**Closed by kburtram** 2019-04-23 23:38 UTC
Labels: Area: Dashboard
