### ISSUE TITLE
Expanding Databases gives invalid argument

### ISSUE THREAD

**Issue by NelGson** [microsoft/azuredatastudio#8122] opened 2019-10-30 21:03 UTC
When I expand for example Databases, I get invalid argument. It is not consistent, so that it can be reproduced every time, but very often, I can reproduce it. If I connect to a BDC for example, and wait a while (for example work on queries and stuff, and then try to expand databases while still connected to the cluster, it usually goes into this mode where it shows "invalid argument" under the Databases node. It is the same when expanding tables/views in an already expanded Database. Almost like it loses connection.

**Comment by vickyharp** [comment] 2019-10-31 00:01
I see this today (and I had not noticed it before) but with a different message. Seeing this on Insider's on Windows.

![image](https://user-images.githubusercontent.com/8250560/67907860-9f3ea780-fb36-11e9-90b6-5621d66dc08e.png)

I had first connected probably 2 hours ago and my laptio has probably slept since then.

**Comment by vickyharp** [comment] 2019-10-31 16:22
From the console log:

c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Invalid operation. The connection is closed.
c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Invalid operation. The connection is closed.
sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery-insider.json:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery-insider.json:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED

**Comment by vickyharp** [comment] 2019-10-31 16:42
I can now reproduce this at will (understanding it's not quite the same error message) by switching what wifi I am attached to.

Log Here: [changewifi.log](https://github.com/microsoft/azuredatastudio/files/3794904/changewifi.log)


![ChangeWifi](https://user-images.githubusercontent.com/8250560/67967172-59c7bc00-fbc2-11e9-9b10-8a8a0269cc9b.gif)

**Comment by aaomidi** [comment] 2019-10-31 18:23
This is a sqltoolsservice bug - we're not checking the state of the connection before executing "stuff" on it. I'll try to tackle it there.

**Comment by kburtram** [comment] 2019-10-31 20:10
@aaomidi I think that logic was supposed to be built into the ReliableConnection wrappers to automatically reconnect if the connection is closed.  Do you have a particular code snippet in mind regarding your previous comment, or is that just a general observation based on the details in the issue?

**Comment by kburtram** [comment] 2019-10-31 20:11
@vickyharp that looks like a slightly different error, but could be related.  Let me see if that repro's on my private test builds at the below URLs.

Windows User Setup - https://azuredatastudiobuilds.blob.core.windows.net/test/1.13.0/azuredatastudio-windows-user-setup-1.13.0.exe
Windows Setup - https://azuredatastudiobuilds.blob.core.windows.net/test/1.13.0/azuredatastudio-windows-setup-1.13.0.exe
Windows ZIP - https://azuredatastudiobuilds.blob.core.windows.net/test/1.13.0/azuredatastudio-windows-1.13.0.zip
macOS ZIP - https://azuredatastudiobuilds.blob.core.windows.net/test/1.13.0/azuredatastudio-macos-1.13.0.zip
Linux TAR.GZ - https://azuredatastudiobuilds.blob.core.windows.net/test/1.13.0/azuredatastudio-linux-1.13.0.tar.gz
Linux RPM - https://azuredatastudiobuilds.blob.core.windows.net/test/1.13.0/azuredatastudio-linux-1.13.0.rpm
Linux DEB - https://azuredatastudiobuilds.blob.core.windows.net/test/1.13.0/azuredatastudio-linux-1.13.0.deb

**Comment by kburtram** [comment] 2019-10-31 20:19
@vickyharp I was actually able to repro this now using basically what you have in your video.  I had to pause for about 30-60 seconds with WiFi so the connection would detect the dropped network, and then I'd either get the invalid argument or the closed connection error.  I was able to see both in different tests.

We'll continue investigating.  Thanks for adding that additional context.

**Comment by kburtram** [comment] 2019-10-31 20:24
@vickyharp I wasn't able to repro with the "disable WIFI" step on the test build above.  Could you please give it try with that build when you have a moment?  Thanks!

**Comment by aaomidi** [comment] 2019-10-31 20:26
Unfortunately it looks like we're not using the ReliableConnection stuff where this problem exists.

@kburtram I've narrowed it down to these files:

This function gets called when expanding: https://github.com/microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/SmoModel/SmoChildFactoryBase.cs#L87-L127

Which then goes ahead and finds the right SmoQueriers and does a .Query on them: 

https://github.com/microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/SmoModel/SmoChildFactoryBase.cs#L127

When we request the Server, we call EnsureConnectionOpen:

https://github.com/microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/SmoModel/SmoQueryContext.cs#L177-L186

Which is calling this function:

https://github.com/microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/SmoModel/SmoWrapper.cs#L23-L30

What I've discovered is that, that function returns true even if the connection is closed.

**Comment by vickyharp** [comment] 2019-10-31 20:45
I am not reproducing the issue on the new build posted.

**Comment by aaomidi** [comment] 2019-10-31 21:27
@kburtram Those builds fixed the problem for me as well. What changed?

**Comment by Charles-Gagnon** [comment] 2019-10-31 21:53
@aaomidi - He rolled back STS to before the SqlClient change (moving from System.Data.SqlClient to Microsoft.Data.SqlClient). So it would appear that something there has changed with how it's reporting the connected state.

**Comment by kevcunnane** [comment] 2019-11-13 21:43
@Karl - isn't this fixed? Can we close this out or are you tracking the SqlClient fix with this?

**Closed** 2019-12-09 23:09 UTC
Labels: Area - Big Data Cluster, Bug, Pri: 0, Triage: Done
