### ISSUE TITLE
ADS crashes when trying to open staged change in source control

### ISSUE THREAD

**Issue by dutchorka** [microsoft/azuredatastudio#15323] opened 2021-05-04 09:34 UTC
Issue Type: <b>Bug</b>

When trying to review a staged change coming from an open sql project in ADS the window freezes and eventually quits with an OOM error. Issue introduced in latest version. Issue can be reproduced on another workstation.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
datavirtualization|Mic|1.12.0
import|Mic|1.3.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
schema-compare|Mic|1.10.0
sql-database-projects|Mic|0.8.2
azdata-sanddance|msr|3.1.0
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment] 2021-05-04 15:56
Duplicate of https://github.com/microsoft/azuredatastudio/issues/15180 - see that issue for instructions to revert to a working version until a build with the fix is released.

**Closed by Charles-Gagnon** 2021-05-04 15:56 UTC
