### ISSUE TITLE
Creating SQL Server 2019 Big Data Cluster

### ISSUE THREAD

**Issue by NavtejSaini-MSFT** [microsoft/azuredatastudio#15449] opened 2021-05-13 03:07 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1.I am trying to create a SQL server 2019 Big Data Cluster through Azure Data Studio to be used for the PySpark connection. I have given the necessary details for my Azure subscription and it has created AKS cluster.
The "Create SQL Server 2019 Big Data Cluster" task has taken more than 18 hrs and it's still executing the task.
Please help me to fix this.
TIA
![95559-image](https://user-images.githubusercontent.com/52257742/118071912-bb034a80-b376-11eb-8185-ca240e662105.png)

We have recieved this issue on Microsoft Q&A  - https://docs.microsoft.com/en-us/answers/questions/391072/index.html

**Comment by Charles-Gagnon** [comment] 2021-05-13 04:55
Closing this as a dupe of https://github.com/microsoft/azuredatastudio/issues/15425 - see that for suggestions on next steps for troubleshooting and where to follow up with any further issues.

**Closed by Charles-Gagnon** 2021-05-13 04:55 UTC
