### ISSUE TITLE
Query tabs aren't visible

### ISSUE THREAD

**Issue by OfcMeowMeowFuzzyFace** [microsoft/azuredatastudio#25078] opened 2023-11-30 21:18 UTC
Type: <b>Bug</b>

Just adding a new query, it will replace the current query with with a blank one and there's an error pop-up: h.defaultValue?.toLocaleLowerCase is not a function

If I blindly click in the area above the query window, I can get back to the query so I believe it is creating a new tab, I just can't see the tab names.

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:19:19.203Z)
OS version: Darwin arm64 23.1.0
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|36.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-mysql|Mic|1.0.0

</details>

**Comment by cheenamalhotra** [comment] 2023-11-30 22:26
@OfcMeowMeowFuzzyFace 

Can you please share your settings `F1 > Preferences: Open User Settings (JSON)`?
You may skip connection list from `datasource.connections` section.

**Comment by OfcMeowMeowFuzzyFace** [comment] 2023-12-01 14:20
Here it is. I also got a pop-up with the same error I initially reported when I opened the settings. I also get the error when attempting to save a query.

{
    "workbench.editorAssociations": {
        "*.{sqlplan}": "workbench.editor.executionplan"
    },
    "datasource.connectionGroups": [
        {
            "name": "ROOT",
            "id": "C777F06B-202E-4480-B475-FA416154D458"
        }
    ],
    "datasource.connections": [
    ],
    "workbench.enablePreviewFeatures": true
}

**Comment by jasontressler** [comment] 2023-12-06 14:14
Seeing the same behavior on Windows 11. Also causes all tabs to disappear in the 'Open Editors' in Explorer.

Version: 1.47.0 (system setup)
Commit: c7c2b2f21505562d21972d4c135119d00806db4f
Date: 2023-11-07T17:17:45.669Z
VS Code: 1.82.0
Electron: 25.8.4
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by WiReCoder** [comment] 2023-12-08 12:24
Same issue for me, after a fresh install of the latest Azure Data Studio:

Version: 1.47.0 (system setup)
Commit: c7c2b2f21505562d21972d4c135119d00806db4f
Date: 2023-11-07T17:17:45.669Z
VS Code: 1.82.0
Electron: 25.8.4
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Any info on workarround, confiig change and/or is a previous version of Azure Data Studio working ok?

**Comment by OfcMeowMeowFuzzyFace** [comment] 2023-12-27 15:47
Hi, I see you've been working on this, but I wanted to give an update - I had Azure Data Studio running from my Downloads folder and it turned out that was causing this issue. I realized it when I went to check for updates and got an error there. I won't close, because maybe it *should* work from Downloads, but just wanted to let everyone know that was experiencing it - you may be able to get around it by moving it to Applications.

@jasontressler @WiReCoder

**Comment by cheenamalhotra** [comment] 2023-12-27 19:11
Could someone try the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) and confirm if the issue is resolved?

**Comment by jasontressler** [comment] 2023-12-27 19:20
@cheenamalhotra Everything is look good on my end

**Comment by cheenamalhotra** [comment] 2023-12-27 20:07
Thanks for confirming!

The fix will be released in the linked milestone, I will close the issue as resolved.
You may use the Insiders build in the meantime if this is blocking.

**Closed by cheenamalhotra** 2023-12-27 20:07 UTC
Labels: Bug, Area - Query Editor, Triage: Done, Size: XS

**Comment by rivaros** [comment] 2024-01-11 10:50
@cheenamalhotra when will you release the fix?

Latest version of Azure Data Studio still has it (1.47.1)
<img width="637" alt="Screenshot 2024-01-11 at 2 48 39 PM" src="https://github.com/microsoft/azuredatastudio/assets/1242369/6ece4818-9059-4fbd-a2bc-def9008802ce">

**Comment by cheenamalhotra** [comment] 2024-01-11 10:55
This is targeted for February Stable Release, as per milestone linked.
