### ISSUE TITLE
Support connecting and querying MySQL Server/Database

### ISSUE THREAD

**Issue by dipakyadav** [microsoft/azuredatastudio#14105] opened 2021-01-29 07:44 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alanrenmsft** [comment] 2021-01-29 17:38
close as dupe of #4904

**Closed by alanrenmsft** 2021-01-29 17:38 UTC
