### ISSUE TITLE
Loading Kernel stuck never ends 2

### ISSUE THREAD

**Issue by eliassal** [microsoft/azuredatastudio#12805] opened 2020-10-08 07:07 UTC
Issue Type: <b>Bug</b>

When I ope some notebooks with powershell (mainly to use dbatools ), I the bar where we have "Cell Run All Kernel...."
In font of Kernel = Loading Kernel....
and never ends, restarted ADS, rebooted the machine but nothing helped

![ADS-Kernel](https://user-images.githubusercontent.com/8447864/95426101-a88ae380-0945-11eb-8812-88dbd56bbb22.jpg)

Azure Data Studio version: azuredatastudio 1.22.1 (1b5c54dd8c6eb03bf7ed1e04889d9f41de0523b3, 2020-09-29T16:41:11.578Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eliassal** [comment] 2020-10-08 07:07
This time with system information

**Comment by chlafreniere** [comment] 2020-10-09 23:07
Dupe of #12804.

**Closed by chlafreniere** 2020-10-09 23:07 UTC
Labels: Area - Notebooks, Triage: Needed
