### ISSUE TITLE
I cannot sign into my SQL server using Azure Active Directory Auth

### ISSUE THREAD

**Issue by pbbpage** [microsoft/azuredatastudio#18146] opened 2022-01-24 19:06 UTC
Issue Type: <b>Bug</b>

I attempt to refresh credentials, the web page pops up and says that the account was successfully added, then I go to connect to my server and it says failure getting token and to look at the developer tools. When I open the developer tools, there isn't much additional information that is indicating what the problem is.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.0
kusto|Mic|0.5.4

</details>

**Comment by Charles-Gagnon** [comment] 2022-01-31 17:43
@cssuh This seems similar to the other AAD issues we have - could you close this and link to the main tracking issues if so?

**Comment by cssuh** [comment] 2022-02-27 22:48
duplicate of https://github.com/microsoft/azuredatastudio/issues/14159

**Closed by cssuh** 2022-02-27 22:48 UTC
Labels: Bug, Area - Azure, Triage: Needed
