### ISSUE TITLE
Copy to Clipboard Slow, hard to tell when complete

### ISSUE THREAD

**Issue by dhsipe** [microsoft/azuredatastudio#3132] opened 2018-11-06 14:24 UTC
Issue Type: <b>Performance Issue</b>

The copy to clipboard on larger data sets (5K+) is slow, and progressively slower as the dataset increases in size.  A notification when the clipboard copy is complete would be helpful, to let the user know when they are able to paste the data elsewhere.  

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.14GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   119	 16396	azuredatastudio main
    0	    75	 16492	   window (Issue Reporter)
    0	   138	 16628	   gpu-process
    0	   346	 17020	   window (● SQLQuery_1 - Migration - Azure Data Studio)
    0	    18	 12348	     searchService
    0	   255	 16052	     extensionHost
    0	   182	  1440	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.52\MicrosoftSqlToolsServiceLayer.exe" --log-file C:\Users\siped01\AppData\Roaming\azuredatastudio\mssql\sqltools_16052.log --tracing-level Critical
    0	     5	  3164	         console-window-host (Windows internal process)
    0	    19	  8748	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.52\MicrosoftSqlToolsCredentials.exe" --log-file C:\Users\siped01\AppData\Roaming\azuredatastudio\mssql\credentialstore_16052.log --tracing-level Critical
    0	     5	  8368	         console-window-host (Windows internal process)
    0	    20	 10624	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.52\SqlToolsResourceProviderService.exe" --log-file C:\Users\siped01\AppData\Roaming\azuredatastudio\mssql\resourceprovider_16052.log --tracing-level Critical
    0	     5	 11924	         console-window-host (Windows internal process)
    0	     9	 16092	     watcherService 
    0	     5	 16020	       console-window-host (Windows internal process)
    0	    50	 17296	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● SQLQuery_1 - Migration - Azure Data Studio)
|    Folder (Migration): 139 files
|      File types: sql(134) mdx(1) ssmssln(1) csv(1) ssmssqlproj(1)
|                  ssms_suo(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by anthonydresser** [comment] 2019-02-07 00:44
related #1388 probably the same thing

**Comment by kburtram** [comment] 2020-02-21 18:25
Closing as duplicate of #1388.  Thanks for reporting.  We plan to fix in an upcoming release.

**Closed by kburtram** 2020-02-21 18:25 UTC
Labels: Area - Query Editor, Bug
