### ISSUE TITLE
unsaved tabs crashing

### ISSUE THREAD

**Issue by anand348** [microsoft/azuredatastudio#6763] opened 2019-08-15 12:59 UTC
- Azure Data Studio Version:

Version: 1.9.0 (system setup)
Commit: 78a42e1d112ae3231777722b51eaf44f83ddbe55
Date: 2019-07-10T04:31:36.998Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. open a new sql tab
2. write some tsql code and connected to an instance
3. after some idle time, the pop with the error message shows up and the tab closes automatically

Error: Unable to open 'SQLQuery_1 - *****...grated)': Cannot read property 'slice' of undefined.

Note: the problem occurs rarely.

**Comment by hfleitas** [comment] 2019-08-15 18:49
@brentwc

**Comment by dzsquared** [comment] 2019-08-20 20:51
I would say this occurs for me about once to twice a week?  This will also happen on tabs where the query has been saved previously.


Version: 1.10.0 (user setup)
Commit: 5fdb967ffcea41df0335ec17cfa396a694bb174e
Date: 2019-08-14T18:28:10.311Z
VS Code 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by anthonydresser** [comment] 2019-09-17 17:41
could be related #7177

**Comment by bsmithart** [comment] 2019-10-10 16:16
This just happened to me. Quite frustrating.

**Comment by BHARATH1986-A1** [comment] 2019-11-27 06:06
frequently encountering this issue.
![image](https://user-images.githubusercontent.com/58246143/69698010-190a8680-111f-11ea-8175-671ac32d42de.png)

**Comment by BHARATH1986-A1** [comment] 2019-11-27 07:16
Is there any way to open the closed file?

**Comment by danilo900** [comment] 2020-01-13 17:13
Still happing.

**Comment by stelth240** [comment] 2020-01-15 18:46
This is also still happening to me as well about once or twice a week, and I am losing important queries that I was not planning on saving, but just working on temporarily. I am unfortunately unable to use ADS until this issue is resolved.

Version: 1.14.1 (user setup)
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:42:26.303Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by anthonydresser** [comment] 2020-01-15 19:14
When this happens could you post the error from the logs? F1 -> `Developer: Show Logs` -> Window

**Comment by stelth240** [comment] 2020-02-04 23:52
Hi Anthony, thank you for responding. I just had another tab crash, but the Window log does not show any errors. SQLQuery_3 was the tab that crashed, right after I closed SQLQuery_5. Here is the log anyway just in case, and a screenshot of the developer tools error.

2020-02-04 14:01:55.861] [renderer1] [info] Creating new connection untitled:SQLQuery_3
[2020-02-04 14:01:55.861] [renderer1] [info] Adding connection untitled:SQLQuery_3
[2020-02-04 14:01:55.861] [renderer1] [info] Successfully added connection untitled:SQLQuery_3
[2020-02-04 14:13:53.211] [renderer1] [info] Creating new connection untitled:SQLQuery_5
[2020-02-04 14:13:53.212] [renderer1] [info] Adding connection untitled:SQLQuery_5
[2020-02-04 14:13:53.214] [renderer1] [info] Successfully added connection untitled:SQLQuery_5
[2020-02-04 15:29:38.564] [renderer1] [info] Deleting connection untitled:SQLQuery_1
[2020-02-04 15:30:26.200] [renderer1] [info] Deleting connection untitled:SQLQuery_5
[2020-02-04 15:30:26.230] [renderer1] [info] Deleting connection untitled:SQLQuery_3
[2020-02-04 15:30:57.877] [renderer1] [info] Deleting connection untitled:SQLQuery_2

![image](https://user-images.githubusercontent.com/11980837/73797946-3767b080-4766-11ea-9d68-3ca58ac037fe.png)

**Comment by stelth240** [comment] 2020-02-05 00:06
This is the JS code that it says is failing. Not sure if this is relevant or if it helps, but I thought I would post it just in case.

![image](https://user-images.githubusercontent.com/11980837/73798610-32a3fc00-4768-11ea-840e-f07a62dd375a.png)

**Comment by dzsquared** [comment] 2020-02-28 18:23
I'm seeing this issue in ADS as well.  I'll have an (unsaved) query editor open with results, switch to another query editor or dashboard, then when I attempt to return to the query editor the tab dissapears and I get "cannot read property 'slice' of undefined"

Same dev console logs as above except my instance is a system install.

Version: 1.15.0 (system setup)
Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
Date: 2020-02-12T20:48:43.389Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19569

**Comment by stelth240** [comment] 2020-06-16 23:27
Hi @kburtram, is there any update on this issue? I am currently unable to use the software due to potential loss of work from this bug. Thank you.

**Comment by kburtram** [comment] 2020-06-17 00:38
@stelth240 unfortunately the error message provided doesn't give enough information to go on.  Basically it says we're calling slice somewhere with a null object, which could be one of numerous places in the code.  The Zone code is a wrapper to handle calls that cross an isolation boundary and isn't the actual source of the error.  I haven't been able to repro this yet, but some mentioned that perhaps force killing Azure Data Studio could force this bug to occur, but I haven't had a chance to test that out.  I'll take a look again to try to repro.

**Comment by stelth240** [comment] 2020-07-17 21:29
@kburtram Thanks for the reply. I actually did find where I think the error is occurring based on the error message that is thrown. Maybe that will help trace back to the root issue. It is in the "vs" folder under "src", so is it something that the vscode team would need to fix?

Here is the line with the error that is emitted:

https://github.com/microsoft/azuredatastudio/blob/5613a97fae6b5cb37f079a67c33c4694f0046c17/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1064

**Comment by bwilson-cjusd** [comment] 2020-09-02 18:49
error also occurs on mac.
![image](https://user-images.githubusercontent.com/60520393/92023970-6224e200-ed12-11ea-827e-2efc0b43a83f.png)

**Comment by ScriptPup** [comment] 2020-09-16 02:26
I'm seeing the same issue. It seems to mostly happen on one file which was saved previously. I can open the file, run the query, then change tabs and leave it for a while - at which point when I try switching back to the tab it will crash with the same error.
![image](https://user-images.githubusercontent.com/6163646/93284954-ced3be00-f7a1-11ea-88cd-3a55b185533c.png)

I'm getting a ton of stack traces like the one below in `Log (Window)` but I don't know if it's related.

```
[2020-09-15 20:16:30.608] [renderer1] [error] TreeError [MarkersView] Tree element not found: [object Object]: Error: TreeError [MarkersView] Tree element not found: [object Object]
    at new i (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:127:950) [<root>]
    at t.ObjectTreeModel.getElementLocation (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:218:613) [<root>]
    at t.ObjectTreeModel.setCollapsed (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:217:855) [<root>]
    at j.expand (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1509:277) [<root>]
    at H.autoReveal (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8931:818) [<root>]
    at H.onActiveEditorChanged (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8928:842) [<root>]
    at file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8927:715 [<root>]
    at file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:190:827 [<root>]
    at c.fire (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:423) [<root>]
    at F.doHandleActiveEditorChangeEvent (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7989:92) [<root>]
    at F.handleActiveEditorChange (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7988:882) [<root>]
    at file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:7989:202 [<root>]
    at c.fire (file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:423) [<root>]
    at file:///C:/Users/USER_NAME/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8228:665 [<root>]
```
The most recent error in that window log after the problem occurs and I see the error pop-up, though, are these:
[```
2020-09-15 21:22:24.781] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-09-15 21:22:33.585] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-09-15 21:23:37.538] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-09-15 21:23:41.789] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-09-15 21:23:49.722] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-09-15 21:23:55.931] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
```
Of course this is IN the log, so I'm not sure what I'm supposed to consult for more details.

**Comment by mrjrdnthms** [comment] 2020-09-16 22:02
this happens to me couple times a week :*(

**Comment by Kanmuri** [comment] 2020-11-04 22:15
This has happened to me seemingly randomly over the past year or so, and just happened to me again twice today, both on unsaved tabs. This time it was a tab with the same name twice.

The window log was useless and had nothing in it, but the developer tools gave me the following error:
![image](https://user-images.githubusercontent.com/9996449/98173118-c3eaff00-1eaf-11eb-9922-d47210d9d483.png)

I still don't know how to reproduce this issue, but hopefully this screenshot of the error helps track down this issue.

**Comment by Kanmuri** [comment] 2020-11-19 22:37
It happened again just now. Similar error as last time, but with a slightly different stack trace:
![image](https://user-images.githubusercontent.com/9996449/99732076-131e5b80-2a7c-11eb-9e5d-f4ed46949262.png)

I had just saved another tab and was switching back to "SQLQuery_1" to check something when that tab crashed and gave me that error.

**Comment by Kanmuri** [comment] 2020-12-02 01:09
Happened again, just now. Here's the stack trace this time:
![image](https://user-images.githubusercontent.com/9996449/100814798-b9b11780-33ff-11eb-9f58-d1485b15ff3d.png)
Looks like it's the same as last time.

So what happened before this error?
I went to a tab I had an opened saved file to that I hadn't switched to for a few hours, and did a Save As to save it with a different name so I could make some tweaks to it for a task I'm working on, and when I switched back to the last unsaved tab I was in (with Ctrl+Tab), that tab then crashed.

I had a similar sequence of events for the last crash I reported, so hopefully this helps narrow things down a bit.

**Comment by hillsrobin** [comment] 2020-12-30 18:08
Any additional logs or details that would help troubleshoot this?  I have it re-occur frequently enough in ADS that it is unproductive.

**Comment by elmat0** [comment] 2021-01-04 21:58
Likewise. This issue occurs for me several times a week.

**Comment by estebanbernal77** [comment] 2021-01-12 19:36
happening to me to... very frustrating... 

Version: 1.25.1

**Comment by ibuda** [comment] 2021-02-03 09:21
Hi, I get the same error, but not only on unsaved tabs:
Unable to open 'playground.sql - 35.242...l_user)': Cannot read property 'slice' of undefined.

```
Version: 1.25.1
Commit: e7eacc32c0d20bd4da843320c3bfac231b308c98
Date: 2020-12-11T01:51:41.708Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-65-generic
```

**Comment by nonanomalous** [comment] 2021-03-04 21:58
Happening to me several times a day.  I now save every query every on every change.  Very annoying.

**Comment by Charles-Gagnon** [comment] 2021-04-05 16:43
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/14929 - see that for some more information on additional logging we added recently to try and track this down.

**Comment by kburtram** [comment] 2021-08-23 17:10
Reopening since we're still getting duplicate reports of this.  #14929 is closed so reopening the earliest report with investigation history.

**Comment by alanrenmsft** [comment] 2021-08-23 18:05
![image](https://user-images.githubusercontent.com/13777222/130495149-26aaa98c-33ad-4945-8229-0a2039d05145.png)

I also ran into this issue today, previously I fixed some places, looking at my stack trace, it is the chart that is having issue, i'll have a fix for it.

**Comment by stelth240** [comment] 2021-09-09 15:42
This just happened to me again as well. I have a lot of errors and warnings in my console log, and I have uninstalled and reinstalled ADS quite recently. I have attached the log as well as a screenshot of the slice error. Thank you.

[Console Log 2021-09-09.log](https://github.com/microsoft/azuredatastudio/files/7137913/Console.Log.2021-09-09.log)

![image](https://user-images.githubusercontent.com/11980837/132717730-aa9eb049-e5a7-4a21-a718-c8658e07ac62.png)

**Comment by Charles-Gagnon** [comment] 2021-09-09 18:42
@stelth240 Do you recall what you were doing when this happened? Was it just idle as the original issue described or were you doing something like switching tabs?

**Comment by stelth240** [comment] 2021-09-09 23:32
@Charles-Gagnon I actually remember the exact steps I took. I had three tabs open (1, 2, 3). Tabs 1 and 2 were connected to one server, and tab 3 was connected to a different server. Tab 2 was just opened minutes before the issue occurred, and I had somewhat recently clicked on both tabs 1 and 3 before tab 2 was open.

I finished my work in tab 2, clicked the X in the corner, and said Don't Save. Immediately, both tabs 2 and 3 closed, with the error occurring on tab 3.

There are also times when I just switch from one tab to another, and the tab I am switching to closes immediately. I believe that is what happened with the scenario above, but it switched to tab 3 as a result of me closing tab 2.

Hope this helps.

**Comment by Kanmuri** [comment] 2021-09-12 00:50
Running version 1.32.0, I just got this error again:
![image](https://user-images.githubusercontent.com/9996449/132967004-05085e84-869e-4829-83a1-a9acdd73d072.png)

I was just closing several saved tabs I no longer needed open and when I closed the last of them, it switched to one of my unsaved tabs and that tab crashed. This is with SQL Server. I believe the unsaved tab is one I hadn't looked at in a while.

Unfortunately I still haven't been able to consistently reproduce this issue or pin down a specific sequence of events that lead to it. However, it does seem to occur most often when I have closed another tab and ADS has then automatically switched to the tab that then crashes.

**Comment by stelth240** [comment] 2021-09-13 22:12
@Charles-Gagnon I received the error again today, but I was doing something different than I have done in the past. I was dragging a tab from its own column back into the main tabs. I have attached the stack trace screenshot and the console log. Thanks!

[Console Log 2021-09-13.log](https://github.com/microsoft/azuredatastudio/files/7157600/Console.Log.2021-09-13.log)

![image](https://user-images.githubusercontent.com/11980837/133122456-fe85223e-125b-46f1-a03f-bc158b34493a.png)

**Comment by alanrenmsft** [comment] 2021-10-06 16:49
I have made an improvement in this area, when the issue occurs, the editor won't crash, and you can save the query and open a new query editor.

Closing the issue because users would most likely to open new issue for the new symptom:
![image](https://user-images.githubusercontent.com/13777222/136127065-317ccec7-4225-4cc9-a62f-32dfe774de57.png)

I've added more logging that would help identify the root cause of the issue, please share the logs with us when you run into this issue.

**Comment by stelth240** [comment] 2021-11-10 23:21
Hi @alanrenmsft ,

I am still receiving the same error as before, and the tabs are still closing on me. I am currently at version 1.33.1. Below is a screenshot of the error in my stack trace. I had closed another tab and clicked Don't Save. It ended up closing both tabs at the same time, and the error appeared as normal. I was just in that tab shortly before this occurred, maybe 30 minutes before the error.

I know this issue was closed, but the improvement does not seem to be working as expected, at least from what I just experienced.

Thank you for your help with this isue.

![image](https://user-images.githubusercontent.com/11980837/141208357-9665f4aa-27c8-4a2f-8b91-445d6afc11fc.png)

**Closed** 2021-12-02 17:38 UTC
Labels: Bug, Area - Query Editor, Triage: Done

**Comment by alanrenmsft** [comment] 2021-12-03 18:46
@stelth240 by looking at the call stack, it should have been caught by my previous fix, are you sure you are using 1.33.1 when the error occurred? anyway, I've made another change to stop if from crashing.

**Comment by stelth240** [comment] 2021-12-04 07:52
@alanrenmsft Hi Alan. Yes, I am sure. Below is a screenshot of the About dialog. I have not updated since the error occurred, so this is the version I was on. A tab actually closed on me again last week as well. I did not grab the stack trace that time, though it looked the same as the other times. Thank you for looking into this; it is stopping my whole team from using ADS since they are having the same issue and do not want to lose their work.

![image](https://user-images.githubusercontent.com/11980837/144702067-a77c0315-3890-4487-aad2-cfa4882e395b.png)

**Comment by alanrenmsft** [comment] 2021-12-06 18:30
@stelth240 our new release will be available in a week or so, please give it a try and definitely let us know if the problem is still there. You can also use the insider build which already have my most recent fix.

**Comment by stelth240** [comment] 2021-12-07 16:59
@alanrenmsft Thank you. I will wait for the new release to be available, and check it then. I really appreciate the help with this issue.

**Comment by stelth240** [comment] 2022-02-25 16:10
@alanrenmsft It has been a while, but I finally received the error that the connection is no longer valid and to save and reopen the tab. I did not lose my work and was able to copy/paste the query without losing it. I really appreciate the help getting this workaround in place!

**Comment by alanrenmsft** [comment] 2022-02-25 17:45
@stelth240 that's great!
