### ISSUE TITLE
MIAA Overview dashboard

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12109] opened 2020-09-03 18:58 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. MIAA properties on dashboard should align with Azure - Azure properties on left and resource properties on right.

**Comment by Charles-Gagnon** [comment] 2020-09-23 17:21
Closing as dupe of https://github.com/microsoft/azuredatastudio/issues/12107

**Closed by Charles-Gagnon** 2020-09-23 17:21 UTC
Labels: Area - Azure Arc, Triage: Done
