### ISSUE TITLE
Failed to create Object Explorer session

### ISSUE THREAD

**Issue by sjmcallister** [Microsoft/azuredatastudio#4789] opened 2019-04-01 16:26 UTC
Issue Type: <b>Bug</b>

Tried to connect to a server that I wasn't actively connected to.  When clicking on the server name, I get an error message dialog that says "Failed to create Object Explorer session."

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (4.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment] 2019-04-01 17:12
This looks like a duplicate of https://github.com/Microsoft/azuredatastudio/issues/4742 as far as I can tell.  Please add comments to that issue if it's incomplete.  Thanks!

**Closed by kburtram** 2019-04-01 17:12 UTC
Labels: bug, connection
