### ISSUE TITLE
Table schema not updating

### ISSUE THREAD

**Issue by rwlpf** [microsoft/azuredatastudio#8470] opened 2019-11-25 20:47 UTC
Created script to update the schema of a table, ran the script in Azure Data Factory which ran succesfully.

Right hand mouse click on table node eg 'dbo.Stages' in the database, clicked on 'Refresh', did not update the table schema.  Right hand mouse click on Tables Folder node in the database, clicked on 'Refresh', did not update the table schema.  

Then went to SSMS which was already connected to the same database.  Right hand mouse click on table node eg 'dbo.Stages' in the database, clicked on 'Refresh', and the table  schema, was refreshed.

**Comment by kburtram** [comment] 2019-11-26 21:55
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/8455.  I haven't been able to repro.  Could you please check if there are errors in the "Help->Developer Tools" Console?  If so, please add to issue #8455.  Thanks!

**Closed by kburtram** 2019-11-26 21:55 UTC
Labels: Area - Data Explorer, Bug, Triage: Needed
