### ISSUE TITLE
UI scale (zoom) resets to default upon choosing "Manage" context menu

### ISSUE THREAD

**Issue by BurstX** [microsoft/azuredatastudio#16708] opened 2021-08-11 15:04 UTC
Issue Type: <b>Bug</b>

1. open ADS
1. Press Ctrl+minus (to zoom out the UI) one or two times
1. expand a connection node in "Connections" pane (to actually connect, i.e. to make the connection "green"). (1) on the screenshot below
1. right-click the connection node, choose "Manage" ; (2) on the screenshot below:
![image](https://user-images.githubusercontent.com/3790231/129053748-249fc180-706f-45bc-ac1b-29a120f613be.png)
1. observe the zoom has reset to its default state

if I press Ctrl+minus again the zoom will be set to a value 1 level less than it was set by me originally, not 1 level less than the default zoom level.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kburtram** [comment] 2021-08-19 01:05
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/14128, which we'll use to track the various "Reset Zoom" repros.  Thanks!

**Closed by kburtram** 2021-08-19 01:05 UTC
Labels: Bug, Area - Shell, Triage: Needed
