### ISSUE TITLE
T-SQL editor is querying sys.dm_cluster_endpoints even if doesn't need to...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#8074] opened 2019-10-28 23:51 UTC
Issue Type: <b>Bug</b>

Subject says it all. Every new T-SQL window is trying to query the BDC DMV. This is not necessary.

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (a7f597c9431c2ee82e6175eb744c328e8c680019, 2019-10-28T07:38:19.274Z)
OS version: Windows_NT x64 10.0.19008

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment] 2019-10-29 01:19
Hi @uc-msft can you describe the customer impact?

**Comment by chlafreniere** [comment] 2019-11-12 18:56
I'm unclear how this is a notebooks issue. This appears to be related to BDC, as when I start Profiler and do a query in the query editor, we see the following:

 SELECT [name], [description], [endpoint], [protocol_desc] FROM .[sys].[dm_cluster_endpoints];

**Comment by chlafreniere** [comment] 2019-11-12 18:56
@kevcunnane can you help here?

**Comment by Charles-Gagnon** [comment] 2019-11-12 19:09
This is a SQL Tools Service thing. We're doing this when gathering the server info (which is done for pretty much every connection)

We can look into scoping this down or not fetching it unless we need it but in general this is like the server version query we/SSMS does and shouldn't have a huge customer impact. Although in this case the DMV is probably doing more than a single version lookup so there might be perf considerations if we're running this a lot.

I don't believe we've gotten any customer complaints about this though so I'm inclined to say we leave it unless we have actual reasoning as to why this would negatively impact customers.

**Comment by kevcunnane** [comment] 2019-11-12 21:44
For every new connection we run some basic queries to get server state. I can see a future optimization where we already know this is cached (e.g. if there's a single connection to a server, no need for additional information) but it's likely that changing DB might mean we need to refresh this (for example to detect SQL DB vs. DW where at server level they're the same, handle DB compat). 

I'd be inclined to close this as "by design" for now and see if down the line we need to optimize whether we need to query server/db info when we've already connected somewhere in the tool. For now, closing but willing to reopen if we have solid customer data of an impact here.

**Closed by kevcunnane** 2019-11-12 21:44 UTC
Labels: Area - SQL 2019, Bug, Triage: Needed
