### ISSUE TITLE
Unable to Script out External Table from ADS/SSMS if DATA_SOURCE = SqlDataPool

### ISSUE THREAD

**Issue by demoolya** [microsoft/azuredatastudio#7506] opened 2019-10-04 06:04 UTC
Issue Type: <b>Bug</b>

1. In SQL Server 2019 BDC create an External table using data source SqlDataPool:
```

IF NOT EXISTS(SELECT * FROM sys.external_tables WHERE name = 'web_clickstream_clicks_data_pool')
   CREATE EXTERNAL TABLE [web_clickstream_clicks_data_pool]
   ("wcs_user_sk" BIGINT , "i_category_id" BIGINT , "clicks" BIGINT)
   WITH
   (
      DATA_SOURCE = SqlDataPool,
      DISTRIBUTION = ROUND_ROBIN
   );

```

2. Right Click on this newly created table and click on 'Script as Create'.
3. The Scripting fails stating: `No script was returned when scripting as Create on object Table`
4. In SSMS as well we see the following error while scripting the external table if data source is SqlDataPool:
```
TITLE: Microsoft SQL Server Management Studio
------------------------------
To accomplish this action, set property Location. (Microsoft.SqlServer.Smo)
For help, click: https://go.microsoft.com/fwlink?ProdName=Microsoft+SQL+Server&ProdVer=15.0.18183.0+((SSMS_Rel).190930-0732)&EvtSrc=Microsoft.SqlServer.Management.Smo.ExceptionTemplates.PropertyNotSetExceptionText&LinkId=20476
------------------------------
BUTTONS:
OK
------------------------------
```

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (6582debd7388b1be512fc3a9b956d3e54f6115e7, 2019-10-03T08:56:27.454Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|32.00GB (27.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0
vscode-kubernetes-tools|ms-|1.0.4
vscode-yaml|red|0.5.2

</details>

**Comment by Charles-Gagnon** [comment] 2019-10-04 14:34
Thanks for the report @demoolya - this looks to be a duplicate of #7260 so I'm going to close this one.

**Closed by Charles-Gagnon** 2019-10-04 14:34 UTC
