### ISSUE TITLE
Tables no longer appear in Connections -> Servers -> DB -> Tables 

### ISSUE THREAD

**Issue by SheldonHage** [microsoft/azuredatastudio#21282] opened 2022-11-20 09:36 UTC
I have multiple Windows systems and Mac systems all running Azure Data Studio.  On all Windows systems, after the recent update listed below to 1.40, the table list for a DB no longer appears under **Connections** -> **Servers** -> **DB**.   **I typically work with two Azure databases; one shows the table list as normal; the other does not.  This is consistent across multiple systems.**

I have removed and recreated the connection to the database in question with the same result.

**Here is my version info for Windows:**
Version: 1.40.0 (user setup)
Commit: 3fbaa3de931ef433090fe3deb8c89cba99d7952b
Date: 2022-11-11T22:47:05.361Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Windows_NT x64 10.0.19044

**Here is my Mac version (working)**
Version: 1.39.1
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:12:48.559Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

From v1.40:
<img width="875" alt="Screen Shot 2022-11-20 at 4 01 49 AM" src="https://user-images.githubusercontent.com/49240336/202896212-3d275f37-c283-4990-bb33-4b25906ed9f1.png">

From v1.39:
<img width="875" alt="Screen Shot 2022-11-20 at 4 05 32 AM" src="https://user-images.githubusercontent.com/49240336/202896255-ef5c052e-91dc-4e4b-b6fd-8d6152036625.png">

**Comment by Charles-Gagnon** [comment] 2022-11-20 19:56
Duplicate of https://github.com/microsoft/azuredatastudio/issues/21245 - we'll use that issue for tracking status and providing updates.

**Closed by Charles-Gagnon** 2022-11-20 19:56 UTC
