### ISSUE TITLE
  A11y_SQLAzureDataStudio_ConnectToASQLServer_AdvancedProperties_ScreenReader: Hidden content is read by screen reader.

### ISSUE THREAD

**Issue by v-atkulk** [microsoft/azuredatastudio#9186] opened 2020-02-18 13:50 UTC
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”
#A11yMAS; #A11yTCS; #SQL Azure Data Studio; #DesktopApp; #Win32; #MAS1.3.1; #JAWS; #NVDA; #Benchmark; #A11y_SQLAzureDataStudio; #A11ySev2;
 
**Environment Details:**
Version: 1.16.0-insider
Commit: 506c6a5e5f8423d3249670f55b1466b1980a5f03
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
 
Additional Details:
Screen reader: NVDA(2019.3.1), JAWS(2020.2001.70)
MAS reference: MAS1.3.1

 **Repro Steps:**
1. Launch Azure Data Studio.
2. Select the Connections icon (if not already selected) from left bar.
3. Hover over the 'Servers' header and select the 'New Connection' icon.
4. Navigate till Advanced button under Connection details & hit enter.
5. Launch Narrator desktop app.
6. Check if hidden content is read by screen reader.

**Actual:**
After hitting Advanced button present on Connection details screen "Advanced Properties" screen is opened.
On "Advanced properties" screen on pressing shift+tab hidden content is being read by JAWS.

**Similar issue has been observed with NVDA also.**

**Expected:**
Hidden content which is the content present behind "Advanced properties" screen should not be read by screen reader.

**User Impact:**
Users might get confused as the hidden content is read which is not present visually.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**MAS Reference:**
**MAS 1.3.1**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Attachment link reference:**
https://microsoftapc-my.sharepoint.com/:v:/g/personal/v-atkulk_microsoft_com/Ech-nzjmVXtNlrf_xTSgskcBN0Ir3fBf_uEAM1lVCfkwzQ?e=WFh7ET

**Comment by alanrenmsft** [comment] 2020-03-05 07:40
dupe of #9407

**Closed by alanrenmsft** 2020-03-05 07:40 UTC
Labels: A11y_AzureDataStudio, Area - Connection, Bug, Triage: Done

**Comment by Harika1702** [comment] 2023-02-14 10:56
https://user-images.githubusercontent.com/100270074/218715327-cb9c73ec-e182-42d1-85cb-707b035b9e6a.mp4

Verified this issue now it is fixed.
GitHub Tags:#Closed;

**Comment by mstechie** [comment] 2023-03-05 19:45
GitHubTags:#SQLADS-Win32-Feb2020;
