### ISSUE TITLE
Notebook change kernel Python3 not work

### ISSUE THREAD

**Issue by danr76** [microsoft/azuredatastudio#11773] opened 2020-08-12 14:43 UTC
Issue Type: <b>Bug</b>

Changing kernel to Python3 , just hanging nothing happens. Output:
Starting Notebook server
    > "C:\Users\danr\azuredatastudio-python\0.0.1\python.exe" "c:\Users\danr\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --no-mathjax --notebook-dir "c:\Users\danr" --port=9018 --NotebookApp.token=544f5966c26d258a4eeb35da306f69cec47e835be846a5ef

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (9.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bentleysj** [comment] 2020-08-12 15:16
Same issue here., changing to any non-SQL kernel, or if already a Python Notebook, dropdown stays at 'loading kernels'. Version etc. the same. I got about 20 minutes of being able to work on a notebook after first installing, and this issue ever after. Reinstalls, changing the python environment, nothing seems to help. Searching has turned up a few previous examples of this issue being raised, but nothing useful.

**Comment by ojintoad** [comment] 2020-08-12 16:27
Same issue here.

![image](https://user-images.githubusercontent.com/3084796/90041363-2f4d7800-dc97-11ea-9018-a008ac9d5879.png)

**Comment by ojintoad** [comment] 2020-08-12 16:33
Looks like a 1.21.0 update has fixed this for me, worth trying for others?

**Comment by chlafreniere** [comment] 2020-08-12 19:40
Indeed, this is a dupe of #11607. We released a new update for Azure Data Studio (1.21.0) today, which should fix this problem.

**Closed by chlafreniere** 2020-08-12 19:40 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
