### ISSUE TITLE
Alt + Windows + N command opens OneNote app instead of Notebooks? 

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#19328] opened 2022-05-10 19:21 UTC
- Azure Data Studio Version: 1.36.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Use the "Alt + Windows + N" shortcut in Azure Data Studio 

Expected 

This should open the Notebooks extension 

Actual 

This command opens the oneNote app 

![image](https://user-images.githubusercontent.com/72947001/167705940-75e4b2ac-95fe-4aeb-82b8-a8c32edf15ab.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment] 2022-05-10 19:37
@chlafreniere Was there ever a decision made on switching the default keybinding? Unfortunately OneNote taking that key combo isn't something we can do anything about so unless we change ours there isn't anything we can do.

**Comment by chlafreniere** [comment] 2022-05-17 21:25
This is a dupe of https://github.com/microsoft/azuredatastudio/issues/9829.

We talked about this quite a bit in the past and went through... many... possibilities, none of which turned out to be available in ADS 😢. Happy to go through it again if anyone has any suggestions, but combinations of ctrl/alt/windows/shift + 'n' previously weren't fruitful.

**Comment by chlafreniere** [comment] 2022-05-18 01:27
(let's continue chat on #9829 and close this one)

**Closed by chlafreniere** 2022-05-18 01:27 UTC
Labels: Bug, Area - Notebooks, Triage: Needed
