### ISSUE TITLE
mssql: SQL Tools Service component exited unexpectedly. Please restart SQL Operations Studio.

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#286] opened 2017-12-04 19:32 UTC
Moving a bug that was originally reported in the vscode-mssql repo to here. Original link: https://github.com/Microsoft/vscode-mssql/issues/1039

Original text:
> MSSQL Extension Version: ??
> VSCode Version: 1.18.1
> OS Version: 8.1 pro
> Steps to Reproduce:
> 
> start sqlops.exe
> The app worked the first few times i started it. I toyed with the git integration which caused problems (warn: to many changes or words to that affect). After that, i don't know if its related however, I then started getting this error and now it will not establish a db connection.

**Comment by MattIrv** [comment] 2017-12-04 19:39
@seanrockster If you think it might be an issue with git integration, could you try opening up SQL Ops Studio's settings (`ctrl + ,`) and setting "git.enabled" to false, then restarting SQL Ops Studio and letting us know if it starts up successfully afterward? Not a permanent fix of course, but it could at least help us narrow down the issue and may be an ok workaround if you're not relying on git integration elsewhere. Thanks!

**Comment by seanrockster** [comment] 2017-12-08 17:26
I restarted my pc and the problem has gone away - but i will continue to play with this app.

**Comment by mrkaminski77** [comment] 2018-02-07 23:08
I had the same issue. I tried what @MattIrv suggested and disabled git and that solved the problem. However I use git. I edited my gitconfig and added http.proxy and enabled git in sqlops and the problem was solved.

**Comment by AshleyPoole** [comment] 2018-02-19 08:04
I also have this issue after a fresh install. Every time I add a new connection and try to connect, I just get a message that the SQL Tools Service component exited unexpectedly.

For what it's worth, the install was done via an administrators account and I'm trying to run it as a user account (that has access to the databases).

**Comment by AshleyPoole** [comment] 2018-02-23 08:36
Running SQL Ops Studio as another user (administrator that installed it), it works. So the issue is localised to the my profile/user. Anything I can try @MattIrv to debug further?

**Comment by MattIrv** [comment] 2018-02-26 23:54
@AshleyPoole Unfortunately I can't seem to reproduce that error even when installing SQL Ops Studio as an administrative user and then trying to run it using a different user, but the SQL Tools Service log may have more information about the error. See https://github.com/Microsoft/sqlopsstudio/wiki/Troubleshooting-Issues for info on how to enable it and where to find the logs.

If you enable logging following those instructions and then run SQL Ops Studio and get the error, the newest `sqltools_<some numbers>.log` file in the log directory should have a log of the error. If you look in the log you may be able to find more info about what's going on, or if you're willing to share it by attaching it here then we can take a look.

**Comment by AshleyPoole** [comment] 2018-02-27 11:41
Here's the log as requested @MattIrv 

```
27/02/2018 11:40:03 [NORMAL] - Method "Initialize" at line 126 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Utility\Logger.cs

    Initializing SQL Tools Service Host logger

27/02/2018 11:40:03 [NORMAL] - Method "Main" at line 41 of D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Program.cs

    Starting SQL Tools Service Host

27/02/2018 11:40:04 [VERBOSE] - Method "InitializeService" at line 56 of D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\TaskServices\TaskService.cs

    TaskService initialized

27/02/2018 11:40:04 [VERBOSE] - Method "InitializeService" at line 132 of D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\ObjectExplorerService.cs

    ObjectExplorer service initialized

27/02/2018 11:40:04 [VERBOSE] - Method "InitializeService" at line 42 of D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Formatter\TSqlFormatterService.cs

    TSqlFormatter initialized

27/02/2018 11:40:04 [VERBOSE] - Method "ListenForMessages" at line 249 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs

    Received message of type[Request] and method[initialize]

27/02/2018 11:40:04 [VERBOSE] - Method "InitializeService" at line 135 of D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Workspace\WorkspaceService.cs

    Initializing workspace service

27/02/2018 11:40:04 [VERBOSE] - Method "WriteMessage" at line 63 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageWriter.cs

    Sending message of type[Response] and method[initialize]

27/02/2018 11:40:04 [VERBOSE] - Method "ListenForMessages" at line 249 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs

    Received message of type[Event] and method[initialized]

27/02/2018 11:40:04 [VERBOSE] - Method "ListenForMessages" at line 249 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs

    Received message of type[Event] and method[workspace/didChangeConfiguration]

27/02/2018 11:40:04 [VERBOSE] - Method "HandleDidChangeConfigurationNotification" at line 323 of D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Workspace\WorkspaceService.cs

    HandleDidChangeConfigurationNotification

27/02/2018 11:40:04 [VERBOSE] - Method "ListenForMessages" at line 249 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs

    Received message of type[Request] and method[version]

27/02/2018 11:40:04 [VERBOSE] - Method "WriteMessage" at line 63 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageWriter.cs

    Sending message of type[Response] and method[version]

27/02/2018 11:40:04 [VERBOSE] - Method "ListenForMessages" at line 249 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs

    Received message of type[Request] and method[capabilities/list]

27/02/2018 11:40:04 [VERBOSE] - Method "WriteMessage" at line 63 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageWriter.cs

    Sending message of type[Response] and method[capabilities/list]

27/02/2018 11:40:29 [VERBOSE] - Method "ListenForMessages" at line 249 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs

    Received message of type[Request] and method[connection/connect]

27/02/2018 11:40:29 [VERBOSE] - Method "HandleConnectRequest" at line 982 of D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs

    HandleConnectRequest

27/02/2018 11:40:29 [VERBOSE] - Method "WriteMessage" at line 63 of D:\a\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageWriter.cs

    Sending message of type[Response] and method[connection/connect]

```

**Comment by AshleyPoole** [comment] 2018-03-13 08:51
@MattIrv anything else to check or grab logs for?

**Comment by MattIrv** [comment] 2018-03-13 20:32
@AshleyPoole unfortunately the error didn't make it into the log and I haven't been able to reproduce the bug yet. Could you tell me what operating system & version of SQL Ops Studio you're using so I can make sure I'm following the right steps to reproduce it? Thanks

**Comment by AshleyPoole** [comment] 2018-03-15 17:32
OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299

Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by AshleyPoole** [comment] 2018-03-19 17:55
@MattIrv do we need more debug logging?

I've tried doing a fresh install by clearing our app settings folders, etc, but it's the same.

**Comment by wandoschneider** [comment] 2019-05-02 16:07
It's happening to me as well. 

Azure Data Studio
Version: 1.6.0
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T06:10:28.959Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-13-generic
VM: Gnome Shell 3.32

**Comment by kburtram** [comment] 2019-06-06 19:18
This message is a generic error when the SQL Tools Service crashes, which can happen for any number of reasons.  The original bug was opened to track a stackoverflow issue with the SQL Parser.  That bug has been fixed, so I'll close this out now.  Please open new bugs for new crashes.

**Closed by kburtram** 2019-06-06 19:18 UTC
Labels: Bug
