### ISSUE TITLE
Focus indicator for main Notebook toolbar cell focus indicator very large

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10742] opened 2020-06-04 20:57 UTC
It overlaps the run button next to it

![image](https://user-images.githubusercontent.com/28519865/83809388-3474c200-a66b-11ea-8bb1-9c5e6f61f578.png)

**Comment by alanrenmsft** [comment] 2020-06-04 22:10
dupe of #10714 10677

**Comment by Charles-Gagnon** [comment] 2020-06-04 22:11
You opened so many guess I missed this one among the pile 😁

**Closed** 2020-06-04 22:10 UTC
Labels: Area - Notebooks, Triage: Done
