### ISSUE TITLE
Apply filter in Tables/Views folder

### ISSUE THREAD

**Issue by jojeswe** [microsoft/azuredatastudio#3761] opened 2019-01-17 08:37 UTC
Issue Type: <b>Feature Request</b>

We have a database with hundreds of tables and views. It would be great if I could apply a filter on what tables and views I would like to show in the Tables/Views folders under the server explorer window in Azure Data Studio. It should work the same way as in SSMS. Folding/unfolding objects based on schema would also be nice.

Azure Data Studio version: Azure Data Studio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:17:16.459Z)
OS version: Darwin x64 18.2.0

**Comment by philosophicles** [comment] 2019-03-19 22:14
I think this might be a duplicate of #3331?

Personally, I'd keep #3331 and close this one, as the other is a little broader (filtering on all kinds of object, not just tables or views). I think this feature would be applicable beyond just tables and views.

**Comment by Charles-Gagnon** [comment] 2020-07-22 22:59
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as cleanup

**Closed by Charles-Gagnon** 2020-07-22 22:59 UTC
Labels: Area - Data Explorer, Enhancement
