### ISSUE TITLE
[Accessibility]A11y_ Azure Data Studio_ NewNotebook_ScreenReader:Screen reader is not announcing the label "Kernal" associated with the  combo box.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [microsoft/azuredatastudio#5613] opened 2019-05-24 05:53 UTC
[Check out Keros! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.
**Environment Details:**
Application name: Azure Data Studio
Version: 1.8.0-insider (user setup)
Commit: 2ca39b5
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
NVDA Version: 2019.1

**Additional Details:**
Tools Name: NVDA
MAS Number  :MAS1.3.1,MAS4.2.5,MAS2.4.6

**Steps to Reproduce :**
1. Install the app Azure Data Studio.
2. Connect to the Database->Go to file->New Notebook.
3. Start NVDA.
4. Navigate to the  first combo box .
5. Observe that Screen reader is not announcing the label associated with the combo box.

**Actual:**
Navigate till  the first combo box on the page ,screen reader announce that “Combobox SQL Collapsed” .It is not reading the label for that combo box that is “Kernal”.
Same issue observed with combo box for “Attach To”.

**Expected:** 
Screen Reader  should read the label associated with the combo box such as “Kernal ”  combobox and “Attach To” combobox.

**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screen reader only users find it difficult to understand what is purpose of combobox.

**MAS Reference:**
MAS1.3.1-
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

MAS4.2.5-
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={07857fe1-d8ef-409e-a594-f440a8359566}

MAS2.4.6-
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0cf80872-800d-4643-90cf-0c1c3d3e6260}

**Attachment for Reference:**
[5613_[Accessibility]A11y_ Azure Data Studio_ NewNotebook_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3215328/5613_.Accessibility.A11y_.Azure.Data.Studio_.NewNotebook_ScreenReader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by chlafreniere** [comment] 2019-06-27 17:25
This was fixed by #6181 and is a dupe of #5678.

**Closed by chlafreniere** 2019-06-27 17:25 UTC
Labels: A11yMAS, A11yTCS, A11y_AzureDataStudio, Area: Notebooks, Bug, Impact: Accessibility
