### ISSUE TITLE
Support AttachDB as a connection option in Ops Studio

### ISSUE THREAD

**Issue by mareksip** [microsoft/azuredatastudio#415] opened 2018-01-02 12:00 UTC
Hi. I am unable to load LocalDB .mdf file. Is it possible? If not, is there any oplan to support LocalDB ?

Thanks.

**Comment by SebastianPfliegel** [comment] 2018-01-02 12:12
LocalDB works splendid for me. This is how I connect:
Server name: (localdb)\v11.0
Authentication Type: Windows Authentication

It's important to include the instance name (which might be different for you).

**Comment by mareksip** [comment] 2018-01-02 12:57
@SebastianPfliegel Thank you for quick reply.

I am running latest version on Windows 0.24.1
Version details
[Imgur](https://i.imgur.com/RWeTaDi.png)

After Connect I receive

[Imgur](https://i.imgur.com/rt7ETFz.png)

> Cannot open database "C:\Users\marek.ARR\Documents\servis\servis-anetca\ckasa\anetca - Aša - měna\anetca\anetcadbloc.mdf" requested by the login. The login failed. Login failed for user 'ARR\marek'.

Is there anything I am missing?

Thanks for your reply.

**Comment by SebastianPfliegel** [comment] 2018-01-02 14:11
I think the issue is that you try to pass the file path to the MDF. If your database is already attached to the localdb(server) it should be sufficient to simply use the database name. Connect to your localdb using master as default database. After that simply check if your database is already attached and if not, do so by this script:

```sql
USE [master]
GO
CREATE DATABASE [ExtMountingDeliveryNote] ON 
( FILENAME = N'C:\Users\marek.ARR\Documents\servis\servis-anetca\ckasa\anetca - Aša - měna\anetca\anetcadbloc.mdf' ),
( FILENAME = N'C:\Users\marek.ARR\Documents\servis\servis-anetca\ckasa\anetca - Aša - měna\anetca\anetcadbloc_log.ldf' )
 FOR ATTACH
GO
```

**Comment by SebastianPfliegel** [comment] 2018-01-02 14:30
Just checked. Management Studio is able to connect via the MDF file name (instead of using the database name), but only if the MDF is already attached to the localDB instance. SQLOpsStudio is currently not able to connect via MDF file name, but only with (attached) database name.

Also check out if your instance name is correct:
`sqllocaldb.exe i` lists all instances.

**Comment by mareksip** [comment] 2018-01-05 12:27
@SebastianPfliegel can confirm this, thank you. I was missing that the database was not attached and SQLOpsStudio does not currently support attach as in SQL Server Management Studio. So I had to attach the db with sqlcmd as following:

SQL 2012 instance name: (localdb)\V11.0
SQL Server 2014 instance name: (LocalDb)\MSSQLLocalDB

`sqlcmd -S (LocalDb)\MSSQLLocalDB`

```
USE [master]
GO
CREATE DATABASE [database_name] ON 
( FILENAME = N'C:\Users\marek.ARR\Documents\servis\servis-anetca\ckasa\mena\anetca\anetcadbloc.mdf'' ),
( FILENAME = N'C:\Users\marek.ARR\Documents\servis\servis-anetca\ckasa\mena\anetca\anetcadbloc_log.ldf' )
 FOR ATTACH ;
GO
```

**Comment by kevcunnane** [comment] 2018-01-08 19:33
Renamed this to accurately reflect the request. This is a request to support the same semantics for attaching a DB via MDF file as works in SSMS

**Comment by cheenamalhotra** [comment] 2023-03-21 02:34
We are considering adding support for a new connection option where one can provide "Attach DB Filename" as path to .mdf file. This property will be available in the 'Advanced' options of the connection dialog, and will be consumed by the SqlClient library respectively: https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.attachdbfilename?view=sqlclient-dotnet-standard-5.1

**Comment by cheenamalhotra** [comment] 2023-03-21 17:49
Apologies, didn't realize this actually exists in Advanced options, closing as resolved.

<img src="https://user-images.githubusercontent.com/13396919/226697632-3d3f6b99-fd14-4c51-b999-558deed00bb2.png" width=500 />

**Closed by cheenamalhotra** 2023-03-21 17:49 UTC
Labels: Area - Connection, Enhancement, Triage: Done
