### ISSUE TITLE
Notebook should support embedded images 

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#12005] opened 2020-08-28 22:07 UTC
Users are not able to freely share notebooks if they have images linked to them. Currently there is no way to embedded images and also ADS does not show embedded images

Users should be able to embed screenshots or images inline similar to Jupyter book supports

**Comment by MsSQLGirl** [comment] 2020-09-14 21:15
Some thoughts to consider - 
* When a user is taking a screenshot, how do we easily provide a way to copy + paste. 
* When users have an image file locally, how do they also easily do copy + paste. 

Note: the URL-based image copy+paste experience level of ease of use is what we are after here with screenshot image and local image :)

**Comment by chlafreniere** [comment] 2020-09-14 21:31
Thanks, @MsSQLGirl. Would you say that the existing WYSIWYG scenario doesn't adequately cover this? Just trying to understand where the "blocking" bar is;

Currently in WYSIWYG mode, users will see the image embedded in the notebook, but it doesn't use the attachments functionality; it looks like this and is just a base64 encoded image:

`![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABNQAAAKwCAYAAABQ/SL/AAAgAElEQVR4Aey913JjaZalmRdBrbVW0CA0CK1JgKDWWmvpdBURmVXVLzMXYzZjczc9T1TdbV0tqrW8XGNr/........=)` (and continues for quite a while).

**Comment by MsSQLGirl** [comment] 2020-09-19 06:32
Thanks @chlafreniere for the details. Let's close this. 

I see the screenshot copy & paste is working properly 💯 
Copying image locally from an editor also works. 

ADS version where these are confirmed.
Version: 1.22.0-rc1 (user setup)
Commit: 5a2fdc4034b63c72e110e21d8d9dfc5b27f540f3
Date: 2020-09-19T04:15:34.721Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041


Note: there could be a drag and drop file which either easily upload an image (similar to what GitHub does today) which is outside the scope of this issue.

**Closed** 2020-09-22 04:04 UTC
Labels: Area - Notebooks, Blocking: ADS TSG adoption, Impact: Live site, Triage: Done
