### ISSUE TITLE
TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by marrim-myob** [microsoft/azuredatastudio#19763] opened 2022-06-17 04:27 UTC
Issue Type: <b>Bug</b>

TypeError: Cannot read property 'token' of undefined

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by caohai** [comment] 2022-06-17 17:23
Hi @marrim-myob , can you share a bit more details about this issue? With what operation are you seeing this error?

**Comment by chlafreniere** [comment] 2022-06-17 20:35
https://github.com/microsoft/azuredatastudio/pull/19755/files#diff-8e6e02b2056f8700c383eabfb6390f5906007f1c68e9ff9d857b88afad9cc1ceR914 should address the property of undefined, but there is still an issue around token acquiry to begin with it looks like.

**Comment by alanrenmsft** [comment] 2022-08-17 20:32
@cheenamalhotra @dnethi is actively experiencing the issue, please contact him if you need a live repro.

**Comment by alanrenmsft** [comment] 2022-08-17 20:33
@candiceye FYI

**Comment by candiceye** [comment] 2022-08-17 20:39
@cheenamalhotra Dinakar is unable to connect his Azure Account to ADS as seen in these screenshots:

![image](https://user-images.githubusercontent.com/22386690/185238549-f4414b03-aa47-4bd4-8dd9-107368f95d0e.png)

![image](https://user-images.githubusercontent.com/22386690/185238679-6f425333-c0f7-49e9-b733-73eeaff2a079.png)

He is seeing errors like:
Please provide below info when asking for support: timestamp = 2022-08-12T16:58:08.7228965Z, correlationId = 3c19aa51-66f3-4b01-9f07-bcd89f116b74. (NoValidSubscriptionsInQueryRequest)
Error: Error fetching resource groups for account Dinakar Nethi - dinethi@microsoft.com (9c1a17be-338f-4b3c-90e9-55eb526c5aef) subscription 0cd6095b-b140-41ec-ad1d-32f2f7493386 (1IS - One Integration Service - NonProduction) tenant 9323b596-236d-4890-bed3-60232a849027 : Cannot read property 'token' of undefined

Failed to get subscriptions for account 9c1a17be-338f-4b3c-90e9-55eb526c5aef (tenant '9323b596-236d-4890-bed3-60232a849027'). Error: Cannot read property 'token' of undefined

Is this something you can help us troubleshoot? It is affecting the Azure Arc experience within ADS.
@dnethi

**Comment by cheenamalhotra** [comment] 2022-12-02 22:02
Confirmed offline with @dnethi and the latest insiders build fixes the issue with MSAL library enabled. 
We would proceed to close the issue, as MSAL will now be the new default for upcoming releases.

**Closed by cheenamalhotra** 2022-12-02 22:02 UTC
Labels: Bug, Area - Connection, Triage: Done
