### ISSUE TITLE
Data Workspace extension causing High CPU usage

### ISSUE THREAD

**Issue by aakoch** [microsoft/azuredatastudio#18513] opened 2022-02-22 03:31 UTC
Issue Type: <b>Bug</b>

I was experiencing high CPU usage and used the extension bisect tool to try to isolate the issue. It reports Data Workspace as the culprit. I was watching the extensionHost process in the VS Code Process Explorer at it would be above 300 both before and during the bisecting.

Extension version: 0.1.1
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|16.00GB (4.02GB free)|
|Process Argv|--crash-reporter-id d3afae23-9334-4b66-8330-3fb8a50b4ca0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by kisantia** [comment] 2022-03-04 22:06
closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/17087. Please provide the requested information there. Thank!

**Closed by kisantia** 2022-03-04 22:06 UTC
Labels: Bug, Triage: Needed, Area - SQL Project
