### ISSUE TITLE
SQL Server Profiler stop working - Failed to create session

### ISSUE THREAD

**Issue by loiseKG0U** [microsoft/azuredatastudio#17379] opened 2021-10-18 05:11 UTC
Steps to Reproduce:
1. Connect to Azure SQL database
2. Launch Profiler on the database
3. Got the error: Failed to create session: An XEvent session named ADS_Standard_Azure already exists

I uninstalled and reinstalled the Azure Data Studio and SQL Server Profiler, the above was the first action with the new app and profiler.

The Developer Tool showed:
![image](https://user-images.githubusercontent.com/92707423/137672340-7984a37f-113a-4dbd-9b43-1e9e326e5e7c.png)

I can see the sessions that were created in previous installations, but they got the same error when creating.
![image](https://user-images.githubusercontent.com/92707423/137673978-a925ae97-6406-4d43-9b2a-5ca5fc98c744.png)

**Comment by kburtram** [comment] 2021-10-19 22:00
@loiseKG0U this appears unexpected as I thought the Profiler would try to reuse an existing session.  We'll follow-up on what's going on here.

As a workaround, have you tried deleting the XEvent sessions manually and see if that gets past the exception?  For reference, sessions can be removed using T-SQL such as `DROP EVENT SESSION [ADS_Standard_Azure] ON SERVER; `

**Comment by smartguest** [comment] 2021-11-09 23:02
Issue does not appear to reproduce when I start a session on one normal ADS client and then attempt to create another instance on a debug client, it successfully recognizes there's a session and uses the monitor on that session without any issue on both clients. Somehow it seems STS isn't detecting or receiving any information from the server that there is an XEvents session with that name in the server. @loiseKG0U Please let me know what kind of SQL server you are using and if creating a new database with similar data reproduces the issue. If you can, could you please attempt to create a new server with similar data and see if the issue reoccurs on it?

**Comment by smartguest** [comment] 2021-11-30 17:49
@loiseKG0U Any update on being able to reproduce the issue with a different server or new database? So far, I cannot reproduce this issue with the current profiler feature, there seems to be an issue causing the server not to be seen by the SQL tools service.

**Comment by kburtram** [comment] 2021-12-01 21:28
Closing as "no repro" and there isn't sufficient detail to investigate further.  Please let us know if you're still impacted by this bug.  Thanks!

**Closed by kburtram** 2021-12-01 21:28 UTC
Labels: Bug, Area - SQL Profiler, Triage: Done
