### ISSUE TITLE
Seeing purple bar (should be blue) when opening a new window

### ISSUE THREAD

**Issue by rtonev** [microsoft/azuredatastudio#9287] opened 2020-02-24 06:33 UTC
Issue Type: <b>Bug</b>

ADS has a blue bar at the bottom. However, when I go to File > New Window, the new window has a purple bar at the bottom instead. 

Should be in blue, in order to maintain visual consistency. 

<img width="1680" alt="Screen Shot 2020-02-23 at 10 29 59 PM" src="https://user-images.githubusercontent.com/1131714/75132602-6352c380-568c-11ea-9f63-d68f89c0d95e.png">

Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (7eef23f2321a8f95220c974209561593f802d918, 2020-02-20T06:07:09.261Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
sqldm-performance-insights|IDE|0.4.0
admin-pack|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.2.0
datavirtualization|Mic|1.3.0
import|Mic|0.13.1
machineLearningServices|Mic|1.0.0
ml-services|Mic|0.1.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.2.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by kburtram** [comment] 2020-02-24 18:26
Duplicate of https://github.com/microsoft/azuredatastudio/issues/6999.

**Closed by kburtram** 2020-02-24 18:26 UTC
Labels: Bug, Triage: Needed
