### ISSUE TITLE
Keep Electron in Parity with Visual Studio Code

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/azuredatastudio#25894] opened 2024-09-09 13:45 UTC
As an extension contributor (`PowerShell` extension) we have many things we want to do but are held back for compatibility reasons because the version of electron (and subsequently NodeJS) are much older in Azure Data Studio than VSCode.

I ask it be made a priority to keep parity with VSCode for new electron releases to help the extension ecosystem to flourish. Thanks.

**Comment by kburtram** [comment] 2024-10-08 16:58
Duplicate of https://github.com/microsoft/azuredatastudio/issues/25938.  We're looking into this.

**Closed by kburtram** 2024-10-08 16:58 UTC
