### ISSUE TITLE
Order compat mode list and exclude current compat mode

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23720] opened 2023-07-10 17:25 UTC
Version: 1.45.0-insider (user setup)
Commit: d555c8d5cc35d1e89546fa0bed025affb4f69ede
Date: 2023-07-10T06:04:09.720Z
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

When viewing the compat list in the drop down, the current value is "missing" from the list, which makes it look like the list is not ordered correctly.  Examples below:

![image](https://github.com/microsoft/azuredatastudio/assets/98599126/d986e805-1462-4486-9bdc-39cfdf8a7a67)

![image](https://github.com/microsoft/azuredatastudio/assets/98599126/92410107-843f-4c82-9052-d9bbca1502cc)

Suggestion: include the entire list of values below the selected one (e.g.):

![image](https://github.com/microsoft/azuredatastudio/assets/98599126/452c75ff-bb27-47ec-88ca-97457a2c23c7)

**Comment by chlafreniere** [comment] 2023-07-10 23:17
Dupe of #23726

**Closed by chlafreniere** 2023-07-10 23:17 UTC
Labels: Area - Basic Admin
