### ISSUE TITLE
Connecting to a server from the Edit Connection window zooms the UI in

### ISSUE THREAD

**Issue by sputnik-adam** [microsoft/azuredatastudio#18324] opened 2022-02-11 11:24 UTC
Issue Type: <b>Bug</b>

1. Right-click on a connection

2. Edit the connection

3. Connect

4. Observe your UI getting zoomed in.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|24.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.0
schema-visualization|R0t|0.7.1

</details>

**Comment by lewis-sanchez** [comment] 2022-04-05 23:26
Hi @sputnik-adam, are you still experiencing this issue when you edit connections in Azure Data Studio? I followed the repro steps in the description, but wasn't able to trigger any zooming effect when editing connections.

**Comment by lewis-sanchez** [comment] 2022-04-07 23:29
Closing as a duplicate of this other zoom in issue reported in Azure Data Studio while adding connections: #14128.

**Closed by lewis-sanchez** 2022-04-07 23:29 UTC
Labels: Bug, Area - Connection, Triage: Done
