### ISSUE TITLE
Run current query (Ctrl + F5) short cut does not work 

### ISSUE THREAD

**Issue by tksbng** [microsoft/azuredatastudio#10548] opened 2020-05-26 07:43 UTC
Issue Type: <b>Bug</b>

Run current query (Ctrl + F5) short cut does not work.

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
import|Mic|0.15.0
profiler|Mic|0.11.0
schema-compare|Mic|1.4.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment] 2020-05-26 17:22
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/10543

**Closed by Charles-Gagnon** 2020-05-26 17:22 UTC
Labels: Area - Query Editor, Bug, Triage: Needed
