### ISSUE TITLE
Save as Excel rounds large numbers

### ISSUE THREAD

**Issue by Tim-Butterfield** [microsoft/azuredatastudio#25455] opened 2024-03-01 15:53 UTC
Type: <b>Bug</b>

Run the below SQL and Save as Excel.  When viewing the results file in Excel, there is a set of rows with the large numbers ending in '20' and another set with the large numbers ending in '30'.  The intermediate large numbers are rounded up or down, but are not in the Excel file the same as in the SQL results grid.

-----

CREATE TABLE #tmp_test
(
    Id INT IDENTITY(1,1) PRIMARY KEY CLUSTERED,
    LargeNum BIGINT
)
GO

INSERT INTO #tmp_test (LargeNum)
VALUES
    (9221000000028920),
    (9221000000028921),
    (9221000000028922),
    (9221000000028923),
    (9221000000028924),
    (9221000000028925),
    (9221000000028926),
    (9221000000028927),
    (9221000000028928),
    (9221000000028929),
    (9221000000028930)

SELECT * FROM #tmp_test

DROP TABLE #tmp_test

-----

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (8.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment] 2024-03-04 22:45
Interesting, it seems we've had this issue from very long time.. also reproduced in 1.41.3.

**Comment by cssuh** [comment] 2024-07-10 19:18
@Tim-Butterfield this is a limitation of Excel, from https://learn.microsoft.com/en-us/office/troubleshoot/excel/last-digits-changed-to-zeros:

>  Excel therefore stores only 15 significant digits in a number and changes digits after the fifteenth place to zeros

**Comment by cssuh** [comment] 2024-07-10 19:24
@Tim-Butterfield one workaround is you can change your data type from BIGINT to TEXT and this will export the values correctly, although your excel cells will be strings.

**Comment by cssuh** [comment] 2024-07-10 19:41
One way to work around this is to cast your BIGINT to CHAR like so:

`SELECT CAST(LargeNum AS char) FROM #tmp_test4`

Exporting this query result will result in the following excel file:
![Screenshot 2024-07-10 at 3 40 53 PM](https://github.com/microsoft/azuredatastudio/assets/18150417/b750a323-4dc8-4767-83d6-2df14bbdeeea)

**Comment by cssuh** [comment] 2024-07-10 19:42
Closing this since it is an Excel behavior

**Closed by cssuh** 2024-07-10 19:42 UTC
Labels: Bug, Area - Query Editor, Triage: Done
