### ISSUE TITLE
Syntax highlighting: Nested multi-line comments not properly highlighted

### ISSUE THREAD

**Issue by bensherman1** [microsoft/azuredatastudio#19205] opened 2022-04-25 19:46 UTC
When executed, the syntax below is valid and has nothing to execute. Based on the syntax highlighting, it looks like it should return a single row result set with the value of `1` and/or error out.

```sql
/*
SELECT 'a'
-- foo bar
/* far bin */
SELECT 1
*/
```

**Comment by Xanadu333** [comment] 2022-10-25 11:13
Hi, I am having the same issue and would like it to be reviewed/solved.
Note: SSMS works perfectly fine with this concept and yet Azure Data Studio doesn't.

**Comment by Xanadu333** [comment] 2022-12-26 20:16
Is this not an issue worth looking forward to?

**Comment by OwlsSleeping** [comment] 2023-05-09 18:04
Duplicate of #848 

Also related thread with more detail on the vscode extension repo-
https://github.com/microsoft/vscode-mssql/issues/1014

**Closed** 2023-05-30 19:01 UTC
Labels: Bug, Area - Language Service, Area - Query Editor, Triage: Done, Size: S
