### ISSUE TITLE
run sql code for sql group? [server group]

### ISSUE THREAD

**Issue by OSch24** [microsoft/azuredatastudio#4573] opened 2019-03-18 09:54 UTC
Hello, I've been using Azure Data Studio for a few days now. I used ssms with a few AddOns before. First of all a big praise to the developers. I've changed so far, but I'm missing a very important feature in Azure Data Studio.

There is the possibility to group the servers. So far great. These possibilities also exist in ssms. What I am missing now is that I can create a new query on a server group, which is then executed on all servers in the group.
This is possible in ssms, so I can save a lot of work, e.g. I have to import a procedure over several SQL servers. 

ssms displays the result of the query to a grid.
ssms adds the server from which the result came as the first column.

Would this also be possible for Azure Data Studio?
Then I could completely "say goodbye" to ssms.

in ssms, i can even move one sql group to another sql group, so i can nest my sql servers extensively. if i send a sql statement on the top level of my sql group, it executes it on all sql servers. i need this function several times a day.

regards Oliver

**Comment by kburtram** [comment] 2021-09-10 19:27
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/28.  Thanks for opening this feature suggestion!

**Closed by kburtram** 2021-09-10 19:27 UTC
Labels: Area - Object Explorer, Enhancement
