### ISSUE TITLE
When clicking on past changes in Timeline, ADS freezes and "The window is no longer responding" occurs

### ISSUE THREAD

**Issue by MULINE** [microsoft/azuredatastudio#15240] opened 2021-04-26 18:07 UTC
- Azure Data Studio Version: **1.28.0**
- Version: 1.28.0 (user setup)
- Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
- Date: 2021-04-15T00:24:15.710Z
- VS Code: 1.51.0
- Electron: 9.4.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 6.3.9600

Steps to Reproduce:

When clicking on past commits via Timeline with any file, the application instantly freezes and eventually the Window is not responding message pops up  

![image](https://user-images.githubusercontent.com/25353144/116129879-359e4b80-a690-11eb-8e8d-24d39e127cff.png)

![image](https://user-images.githubusercontent.com/25353144/116128419-890f9a00-a68e-11eb-8f69-7aeb9b5517e4.png)

The application is installed as a System Install on Windows 2012 R2 Standard.

All users are experiencing the same issue.  All users are connecting via Remote Desktop.

**Comment by Charles-Gagnon** [comment] 2021-04-26 18:09
Dupe of https://github.com/microsoft/azuredatastudio/issues/15180 - see that issue for more context and how to get versions that don't have this issue until we publish a release with a fix.

**Closed by Charles-Gagnon** 2021-04-26 18:09 UTC
