### ISSUE TITLE
Feature Request: Ability to view query results to the side

### ISSUE THREAD

**Issue by rmedved7** [microsoft/azuredatastudio#5724] opened 2019-05-29 18:20 UTC
- Azure Data Studio Version 1.7.0

It would be great to have the ability to view the results grid to the side when working in a query editor. When I'm writing large queries (that take up lots of vertical space), I run the query and the results grid appears below, shrinking my editor window so that only a small portion of the query SQL is visible. 

I would love to be able to move the results grid to the side (like having another editor window) so that I can see both the results, and the all of my query at the same time.

**Comment by Galaeci** [comment] 2022-12-23 13:59
This is the same as #6551

**Comment by cheenamalhotra** [comment] 2023-09-13 18:09
Closing as duplicate of #6551

**Closed by cheenamalhotra** 2023-09-13 18:09 UTC
Labels: Area - Query Editor, Enhancement
