### ISSUE TITLE
Allow toggling of 4 part naming errors

### ISSUE THREAD

**Issue by paweston70** [microsoft/azuredatastudio#19886] opened 2022-06-29 16:03 UTC
Issue Type: <b>Feature Request</b>

I'm not sure if this is a feature request or a bug, but...

I'd like to be able to disable the error checking on 4-part names, for which ADS is unable to obtain details of a table structure.

We have both local and remote servers of various flavours, including standard SQL Server, Azure, Informix and (occasionally) Oracle.  In some cases, when a linked server is created for some of these platforms, ADS is unable to simply connect and pull the structure details for tables (we may not be privy to such information, for instance).

ADS seems to see this as an error and highlight the code with the slightly annoying red squiggles.  I'd like to be able to either toggle errors on/off, or, better yet, have ADS check to see if schema information is available and _not_ use error highlighting in these cases.

Thanks in advance for even taking the time to read the request.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by alanrenmsft** [comment] 2022-07-28 21:55
closing as a dupe of #20107

**Closed by alanrenmsft** 2022-07-28 21:55 UTC
Labels: Bug, Area - Language Service, Triage: Done

**Comment by paweston70** [comment] 2022-07-29 09:47
Apologies - had forgotten that I'd put this in already.  Thanks @alanrenmsft
