### ISSUE TITLE
Unable to create firewall rule if SqlLogin authentication was used (regression)

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#11492] opened 2020-07-23 18:00 UTC
- Azure Data Studio Version:
![Screen Shot 2020-07-23 at 1 58 44 PM](https://user-images.githubusercontent.com/18150417/88321224-cce30680-ccec-11ea-90c0-614a5ed5ffb4.png)

Steps to Reproduce:

1. Attempt to connect to Azure DB that doesn't have the correct firewall rule set (so ADS will prompt you to add one)
2. Add Azure account in the firewall rule prompt
3. Select OK (in firewall rule prompt)
![Screen Shot 2020-07-23 at 1 47 18 PM](https://user-images.githubusercontent.com/18150417/88320866-3c0c2b00-ccec-11ea-876a-4f8041d6bb5f.png)

**Comment by cssuh** [comment] 2020-07-23 18:02
not sure why the commit says 2 years ago, when I do a git log it gives me 
![Screen Shot 2020-07-23 at 2 02 15 PM](https://user-images.githubusercontent.com/18150417/88321405-1e8b9100-cced-11ea-9ad6-91df0d3b8582.png)

**Comment by aaomidi** [comment] 2020-07-24 17:49
This should be fixed in the new insiders. Can you test it again?

**Comment by dzsquared** [comment] 2020-07-27 01:05
@aaomidi I'm seeing this same behavior in today's insiders - unable to create a firewall rule with this error message:

Firewall rule error: Error: Specifed tenant with ID 'undefined' not found.


**Version info**
Version: 1.21.0-insider (user setup)
Commit: eccf3cf5fe8f60d04d70096bc94c654cab60d81a
Date: 2020-07-24T09:33:09.435Z
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041


![image](https://user-images.githubusercontent.com/12227241/88494296-4fc4c500-cf6a-11ea-86bb-ea370c6bc083.png)

This error occurs in both cases if the account is added to ADS from the firewall rule wizard or from the general accounts pane.

**Comment by aaomidi** [comment] 2020-07-27 18:44
Thanks I found out what the issue is. If we use SqlLogin the tenantId isn't populated... We need to get the tenantId somehow. Maybe the account picker needs to also have a tenant picker.

@Charles-Gagnon any ideas?

**Comment by Charles-Gagnon** [comment] 2020-07-27 19:23
Where is the tenant id used in this case?

**Comment by aaomidi** [comment] 2020-07-27 20:04
https://github.com/microsoft/azuredatastudio/blob/587abd43c2d92d83af1214399172fe8734597915/src/sql/workbench/services/resourceProvider/browser/firewallRuleDialogController.ts#L64

**Closed** 2020-08-01 03:07 UTC
Labels: Area - Azure, Bug, Fixed: needs validation, Triage: Done

**Comment by franciscohanna92** [comment] 2021-03-08 23:47
I'm having this issue on:
![image](https://user-images.githubusercontent.com/12707758/110396859-81992080-804f-11eb-88d1-c5bee8054c16.png)
