### ISSUE TITLE
Does not work with Oracle extension

### ISSUE THREAD

**Issue by ejkitchen** [microsoft/azuredatastudio#18268] opened 2022-02-09 19:55 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:

Install Azure Data Studio. Install Oracle extension. Connect to my Oracle instance which is green and shows no errors with the username/password provided. Then I write a simple select statement with the 1 table in the Oracle DB that I have 

use countrydata
select * from countrydata

and....

Execution failed due to an unexpected error:  No Handler Registered. 

No amount of google search helps and your system provides no clue as to where to start. So the bug here I think is this error is probably very easy to solve but the app makes it impossible to tackle or figure out. 

Also, if I navigate to my table under my schema and right-click on the table and select "Select Top 1000", I get "Select scripts not supported by the current provider". I am baffled as to why such a simple operation would not be supported and require something that special by the application to implement. I understand this is a Microsoft product but with the great direction that VS Code has taken, I was expecting the same level of seamlessness with this product.

Again, this is probably a very simple fix but the error should be clearer or documented. When I use PL/SQL Developer, everything works perfectly fine. I switched to your product because I wanted something less intense and quick.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by Charles-Gagnon** [comment] 2022-02-09 20:39
@nahk-ivanov This is working as intended, right? From the extension README : 

```
Current limitations
Not all Azure Data Studio features are currently supported when connecting to Oracle database. Below is the list of current limitations:

Server management and dashboard are not supported
Packaged objects are not supported
Table data preview/editing is not supported
Query execution is not supported
```

**Comment by ejkitchen** [comment] 2022-02-10 00:39
but why does a simple sql select statement not work and what does that error message mean? There is no documentation on this at all.

PLSQL has no issue connecting using the exact same credentials:

![image](https://user-images.githubusercontent.com/823511/153314608-24742ca7-f990-449a-a2ea-14419f89efbf.png)

**Comment by ejkitchen** [comment] 2022-02-10 00:41
And here is Azure Data Studio


![image](https://user-images.githubusercontent.com/823511/153314935-82e7001c-96cb-43a9-b636-e3c266734880.png)

**Comment by ejkitchen** [comment] 2022-02-10 00:42
You cannot have a simpler SQL statement than that so this is very baffling

**Comment by Charles-Gagnon** [comment] 2022-02-10 00:48
The error message is because the extension doesn't implement the query provider - i.e. it doesn't provide the capabilities to run queries. 

Providers can provide a subset of functionality in ADS such as listing in OE, connecting, running queries, etc. 

I can't speak to the reasoning behind not supporting this (I didn't work on that feature) though, hopefully @nahk-ivanov can provide some context there. But I know it was intentional as the feature set they were targeting didn't require supporting running generic queries and so that (among other things) was not included. 

The UI here could be a lot more clear in that regard I'll admit - I'll file a separate bug for that to make it clear when a provider doesn't support that functionality.

**Comment by JConroyNYCC** [comment] 2022-02-10 12:30
Thanks for answering the question @Charles-Gagnon, it was driving me mad too- you're absolutely right that it's mentioned on the details tab, and this is a preview feature, so bugs/missing features etc are to be expected.

I see you've also opened a suggested improvement failing gracefully, thought another potential suggestion could be making any limitations a little more obvious - e.g is this was a car, not having query support feels a little like releasing a new car with the following limitations:

- Unable to open bonnet
- Indicators not available
- Radio not available
- Engine disconnected from drivetrain

Just putting
**- Please Note: Engine currently disconnected from drivetrain - this car cannot move**
at the top in bold would be useful.

Again, I know all the detail is there if I'd read through it fully, just a little user friendly little formatting would be useful for any issues with core functionality!

Cheers,

Jon

**Comment by nahk-ivanov** [comment] 2022-02-10 17:10
Hey,

As Charles pointed out (and as documented), Oracle's extension does not currently support running queries, so this is by design and per documentation.

The main scenario for the Oracle extension right now is migrating your Oracle databases to Microsoft SQL, as explained in [this article](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/dsct/oracle-to-mssql/convert-oracle-database-objects-to-mssql?view=sql-server-ver15), rather than administering your Oracle databases.

I honesty don't know how much more can be done here - we already have limitations documented in the readme. 

We are looking into adding this functionality in the future releases. cc @aciortea 

Regards,
Alex.

**Comment by Charles-Gagnon** [comment] 2022-02-10 17:17
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/6724

**Closed by Charles-Gagnon** 2022-02-10 17:17 UTC

**Comment by Charles-Gagnon** [comment] 2022-02-10 17:20
@nahk-ivanov The comment about putting the limitations in a much more visible space at the top of the README is not a bad idea though - would help avoid further confusion (and maybe even provide a link to the oracle support issue so people don't open duplicates)

**Comment by indieshack** [comment] 2022-02-16 14:04
I've been searching Google for an answer to "Execution failed due to an unexpected error: No Handler Registered"
...wait, so the Oracle extension doesn't allow queries?
THIS SHOULD BE WRITTEN IN LARGE LETTERS ON THIS PAGE:
https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-oracle?view=sql-server-ver15

**Comment by oliverdrummond** [comment] 2022-08-03 05:15
Another user that had this "feature" tricked him :(

**Comment by agurruchaga1** [comment] 2023-03-15 13:48
any plans on supporting oracle query execution in ADS?

**Comment by indieshack** [comment] 2023-03-15 13:52
> any plans on supporting oracle query execution in ADS?

Suggest moving onto DataGrip if financially feasible; there are too many gaps in ADS.

**Comment by COF-RNorman** [comment] 2023-07-25 17:23
Just as a side note, there are Oracle Tools for VS Code available. So depending on the structure it might be migratable to this tool. Just thought I'd share since I use that all the time and was surprised to find this limitation here.

[https://marketplace.visualstudio.com/items?itemName=Oracle.oracledevtools](https://marketplace.visualstudio.com/items?itemName=Oracle.oracledevtools)

**Comment by wlopezemr** [comment] 2024-03-01 16:19
Please remove the extension.  It's completely useless.
