### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by SPeacock1978** [Microsoft/azuredatastudio#4231] opened 2019-02-28 13:56 UTC
Issue Type: <b>Bug</b>

I'm trying to add my Azure account to Azure Data Studio but get the following error in a popup after entering the device code in a browser...
"Error: self signed certificate in certificate chain"

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.43GB free)|
|Process Argv|C:\Users\simon.peacock\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.36.1
import|Mic|0.5.0
profiler|Mic|0.6.0
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment] 2019-03-01 01:47
@SPeacock1978 this looks like a duplicate of https://github.com/Microsoft/azuredatastudio/issues/3723.  Please see the discussion there and add any additional comments if that isn't helpful.  Thanks!

**Closed by kburtram** 2019-03-01 01:47 UTC
Labels: azure, bug
