### ISSUE TITLE
Unable to Add Azure account to Linked Accounts in Azure Data Studio Insiders with version 1.23

### ISSUE THREAD

**Issue by tarry87** [microsoft/azuredatastudio#13353] opened 2020-11-11 18:52 UTC
Hello Team,

Im unable to add my organization Azure Account to the Azure Data studio v 1.23 (october 2020) release.

When i try to add i keep on getting "You have no clouds enabled. Go to Settings -> Search Azure Account Configuration -> Enable at least one cloud" and when i go to settings and search for above string setting is already enabled for Public cloud.

![image](https://user-images.githubusercontent.com/46358346/98851916-edda8d80-247c-11eb-9b52-33bc8bfc7a68.png).

The real issue besides this is , im unable to login to Azure SQL DB with my own Azure MFA account. 

Please help.

**Comment by Charles-Gagnon** [comment] 2020-11-11 19:23
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/11260.

To help us track down this issue could you : 

1. Download the insiders build of ADS (https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main)
1. Repro the issue
1. Open command palette (Click View -> Command Palette)
1. Run the command: Developer: Open Logs Folder
1. This will open the log file locally. Attach the renderer.log to this issue or e-mail it to me directly

**Closed by Charles-Gagnon** 2020-11-11 19:23 UTC
