### ISSUE TITLE
Azure Data Studio is unable to connect to SQL Server with MFA enabled

### ISSUE THREAD

**Issue by abjbhat** [microsoft/azuredatastudio#15208] opened 2021-04-22 07:31 UTC
Hello All,

My Azure SQL Server uses _Azure Active Directory - Universal with MFA support_. After I reset my password, Azure Data Studio is unable to reconnect to this server. However, SSMS can connect just fine.

The login prompt asks me to sign into the browser, I sign in successfully, but then Azure Data Studio fails to connect with this error message:

`
Error: Token retrieval failed with an error. Open developer tools to view the error
`

This is the error in the developer tools..
`
Response error! - {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on 'DateRedacted' and the TokensValidFrom date (before which tokens are not valid) for this user is 'Redacted'.\r\nTrace ID: Redacted\r\nCorrelation ID: Redacted\r\nTimestamp: 2021-04-22 07:18:13Z","error_codes":[50173],"timestamp":"2021-04-22 07:18:13Z","trace_id":"redacted","correlation_id":"redacted","error_uri":"https://login.microsoftonline.com/error?code=50173"}
`

I am on the latest version of Azure Data Studio as of now.

Any help on this issue would be very helpful.

Thank you.

**Comment by cssuh** [comment] 2021-06-08 17:16
duplicate of https://github.com/microsoft/azuredatastudio/issues/12637 
@abjbhat if you follow the instructions in the linked issue, you should be able to find a solution - many users were able to remove their azure account and then re-add it to get it working again.

**Closed by cssuh** 2021-06-08 17:16 UTC
Labels: Area - Azure, Bug, Triage: Needed
