### ISSUE TITLE
Newline are not displayed correctly if begin with [ 

### ISSUE THREAD

**Issue by salinsde** [microsoft/azuredatastudio#11127] opened 2020-06-27 00:10 UTC
- Azure Data Studio Version:

Steps to Reproduce:
1. We have each 'text' on a newline but when displayed it is not displaying correctly on each line, it displays all together.  (see Images below)
2) To resolve I had to add the \  (only \ no space after) to get the new line to work properly.  

**Current Display:**
![image](https://user-images.githubusercontent.com/1909866/85909411-8e7e2880-b7ce-11ea-974c-d902a222d003.png)

**Current Display Markdown:**
![image](https://user-images.githubusercontent.com/1909866/85909427-b3729b80-b7ce-11ea-87a6-0f2b4758e458.png)

**Corrected Markdown to work:**
![image](https://user-images.githubusercontent.com/1909866/85909541-63e09f80-b7cf-11ea-8fcc-64eb1df84591.png)

**Displays Correctly:** 
![image](https://user-images.githubusercontent.com/1909866/85909585-7fe44100-b7cf-11ea-849e-7a54e15dee00.png)

**Comment by chlafreniere** [comment] 2020-07-06 19:27
This is by design based on the renderer used (which is shared with vscode). Two spaces or a '\' at the end of the line (or a <br>) will create a newline here for various items.

![image](https://user-images.githubusercontent.com/40371649/86632257-01805f80-bf84-11ea-9d42-7e569fc10969.png)

**Comment by rajeshka** [comment] 2020-07-17 20:08
Can we assign this bug to VSCode for addressing this issue ?

**Comment by chlafreniere** [comment] 2020-11-06 19:44
The linked issue shows how this is by design, so closing this issue as well.

**Closed by chlafreniere** 2020-11-06 19:44 UTC
Labels: Area - Notebooks, Bug, Impact: Live site, Triage: Done
