### ISSUE TITLE
LinkedServer -> Database, Object and table/columns list

### ISSUE THREAD

**Issue by naimsulejmani** [microsoft/azuredatastudio#4428] opened 2019-03-13 09:23 UTC
- Azure Data Studio Version: 1.4.5

Steps to Reproduce:
To show the list of the object on Linked Server Folder -> 
![image](https://user-images.githubusercontent.com/12331526/54267742-0d1f6a00-457a-11e9-9dfe-a1b94e14ac3e.png)

**Comment by kburtram** [comment] 2021-04-23 17:45
Closing as duplicate of #2217 as that issue is encompasses this enhancement request.

**Closed by kburtram** 2021-04-23 17:45 UTC
Labels: Area - Data Explorer, Enhancement
