### ISSUE TITLE
Azure Databases are not listed on the left side

### ISSUE THREAD

**Issue by Alzemand** [microsoft/azuredatastudio#16385] opened 2021-07-21 18:45 UTC
- Azure Data Studio Version: 1.31.0
- OS Version: Windows_NT x64 10.0.19042

Azure connections It's not listed on the left side, but it's listed on the tab. 

![image](https://user-images.githubusercontent.com/10548468/126542541-694d0696-60b3-43a8-b89f-6cfc6daaef7f.png)

Does this issue occur when all extensions are disabled? Yes

**Comment by Alzemand** [comment] 2021-07-22 02:35
LOGS
[console.log](https://github.com/microsoft/azuredatastudio/files/6859664/console.log)

[LOG.zip](https://github.com/microsoft/azuredatastudio/files/6859684/LOG.zip)

**Comment by kburtram** [comment] 2021-07-30 19:37
@Alzemand the error is saying the server didn't respond with schema metadata within 45 seconds.  Typically simple DMV queries should respond much quicker than this, and these timeouts are typically an indication of a issue on the server (perhaps heavy-load, slow network, etc.).  We could look at adding a setting to increase this timeout to an arbitrary duration.  The suggested workaround would be to disconnect & reconnect the connection node.

**Comment by kburtram** [comment] 2021-08-19 00:43
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/5173.  Thanks for reporting this issue.

**Closed by kburtram** 2021-08-19 00:43 UTC
Labels: Bug, Area - Object Explorer, Triage: Done, Needs Logs
