### ISSUE TITLE
Unable to open SQL Server import wizard 

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4232] opened 2019-02-28 14:01 UTC
Issue Type: <b>Bug</b>

Unable to open SQL Server import wizard dialogs. 

Activating extension 'Microsoft.import' failed: Cannot find module 'htmlparser2'.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280

![image](https://user-images.githubusercontent.com/8250560/53571636-4fe84780-3b61-11e9-9993-2076a01a25fe.png)

Azure Data Studio version: azuredatastudio 1.5.0-insider (291f591af3421899481725016ccb08a40424c036, 2019-02-28T03:34:08.321Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (4.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by vickyharp** [comment] 2019-02-28 14:02
Possibly a dup of #4140

**Comment by anthonydresser** [comment] 2019-02-28 18:25
looks like it is a dupe of #4140

**Closed** 2019-02-28 23:09 UTC
Labels: bug, dacfx, duplicate
