### ISSUE TITLE
Intellisence not working

### ISSUE THREAD

**Issue by eghazal** [microsoft/azuredatastudio#11030] opened 2020-06-22 11:23 UTC
Issue Type: <b>Performance Issue</b>

Intellisence not working when connecting to Azure SQL database.

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    68	 35956	azuredatastudio main
    0	    19	 10884	   utility
    2	   153	 28440	   gpu-process
    0	    54	 28980	   shared-process
    2	   213	 31672	   window (Dev:ATT_MACRO_TURF - Azure Data Studio)
    0	    73	 36016	     extensionHost
    0	    21	  7496	       "C:\Users\User\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe" "c:\Users\User\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=36016
    0	   101	 19064	       "c:\Users\User\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\2.0.0-release.70\MicrosoftSqlToolsServiceLayer.exe" --log-file c:\Users\User\AppData\Roaming\azuredatastudio\logs\20200622T104706\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical
    0	     4	 33568	         console-window-host (Windows internal process)
    0	    19	 19944	       "c:\Users\User\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\2.0.0-release.70\SqlToolsResourceProviderService.exe" --log-file c:\Users\User\AppData\Roaming\azuredatastudio\logs\20200622T104706\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical
    0	     4	 14432	         console-window-host (Windows internal process)
    0	    19	 28528	       "c:\Users\User\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\2.0.0-release.70\MicrosoftSqlToolsCredentials.exe" --log-file c:\Users\User\AppData\Roaming\azuredatastudio\logs\20200622T104706\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical
    0	     4	 11988	         console-window-host (Windows internal process)
    1	    67	 40072	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
sql-prompt|Red|0.2.2

</details>

**Comment by Charles-Gagnon** [comment] 2020-06-22 14:51
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/4817 - if you have any further specific information to give that might help us please post it there! Unfortunately there's a number of known issues with Intellisense that we've been unable to track down so I don't have any update on a potential fix at this point in time.

**Closed by Charles-Gagnon** 2020-06-22 14:51 UTC
Labels: Area - Connection, Bug, Triage: Needed
