### ISSUE TITLE
Azure doesn't show tables in a server

### ISSUE THREAD

**Issue by LeoNguyen92** [microsoft/azuredatastudio#13567] opened 2020-11-29 19:54 UTC
Issue Type: <b>Feature Request</b>

On my left hand menu, it only shows the server IP Address. When I click to the drop down arrow, it didn't show any thing.

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:35:27.682Z)
OS version: Darwin x64 20.1.0

**Comment by Charles-Gagnon** [comment] 2020-11-30 17:09
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12992

**Closed by Charles-Gagnon** 2020-11-30 17:09 UTC
