### ISSUE TITLE
The non-English characters Azure AD account name are not displayed properly. 

### ISSUE THREAD

**Issue by yehh** [microsoft/azuredatastudio#17754] opened 2021-11-29 06:30 UTC
- Azure Data Studio Version: 1.33.1
- OS Version: Windows 11 Pro 21H2

Steps to Reproduce:

1. Add a new Azure subscription in the Connection tab (I am using the Azure China region)
2. Log with corresponding Azure account, it will redirect to corresponding page and log with your Azure AD account and sucessful, then to close the page. 
3. Go back to Azure Data Studio, you will able to see the Azure AD name with non-English characters are not displayed properly.

Attached the screenshot for your reference:
![image](https://user-images.githubusercontent.com/618842/143819022-68a89220-21c5-48b2-afca-044213542d07.png)

Does this issue occur when all extensions are disabled?: No

**Comment by Charles-Gagnon** [comment] 2021-12-08 17:48
@smartguest Can we close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/15598 to consolidate issues?

**Comment by kburtram** [comment] 2022-02-07 21:19
Closing as duplicate per previous comment.

**Closed by kburtram** 2022-02-07 21:19 UTC
Labels: Bug, Area - Azure, Area - Localization
