### ISSUE TITLE
Kusto extension is raising an error on startup on dev builds

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#12026] opened 2020-08-31 18:51 UTC
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Run ADS on dev build

Expected: No errors on startup

Actual: Kusto is raising an error on startup

![image](https://user-images.githubusercontent.com/599935/91755649-4f7aa380-eb80-11ea-8839-77fee3bf3492.png)

**Comment by kburtram** [comment] 2020-08-31 18:53
@gupta1 @qifahs could someone please take a look and resolve this?  I have to dismiss these notifications everytime I debug currently.

**Comment by Charles-Gagnon** [comment] 2020-08-31 19:31
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/11984

@qifahs @gupta1 Any progress on the fix? This is affecting everyone developing in ADS currently.

**Closed by Charles-Gagnon** 2020-08-31 19:31 UTC
Labels: Area - Kusto, Bug

**Comment by gupta1** [comment] 2020-08-31 20:19
> Closing as duplicate of #11984
> 
> @qifahs @gupta1 Any progress on the fix? This is affecting everyone developing in ADS currently.

Working on the fix. I will send a PR soon.
