### ISSUE TITLE
In SQL Database Project 0.21.0 (preview) - unable to generate script if I have logins that have "@" in the filename

### ISSUE THREAD

**Issue by Pio-labuda** [microsoft/azuredatastudio#22261] opened 2023-03-09 09:19 UTC
Using Azure Data studio 1.41.2
Using SQL Database Project Extension:
Last updated
1/20/2023, 24:00:00
Identifier
microsoft.sql-database-projects

I am unable to generate a compare between project in a repository and a database, because my logins/users contain "@" (Azure SQL Server Elastic Pool DB).
The issue is how Database Projects tries to handle the "@" sign and replaces it with %40. The filename looks like this:
![image](https://user-images.githubusercontent.com/81429801/223975696-0f512c46-901f-47fe-9df6-c3b60a9047af.png)
If I use the explorer it's correctly showing with an "@"
![image](https://user-images.githubusercontent.com/81429801/223975937-5cbf44bd-b87c-4af4-9258-fc1d5b9185a8.png)

Any time SQL Database Project tries to do anything with the login files, it expect something different. The file name is actually user@domain.com but it's looking for user%40domain.com and fails with a "file not found" error. 

Let me know if you would like me to extend on this issue. 

I have seen version of SQL Database Project Extension 0.22.0 (preview) in a screenshot somewhere, but when I try to update the extension and Data Studio, there are no updates found.

**Comment by kisantia** [comment] 2023-03-09 17:00
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/17020. Workaround is https://github.com/microsoft/azuredatastudio/issues/17020#issuecomment-966738340

**Closed by kisantia** 2023-03-09 17:00 UTC
Labels: Bug, Triage: Done, Area - SQL Project

**Comment by phw198** [comment] 2024-01-16 14:51
Can a proper fix not be put in place? It makes a barrier to adoption of ADS if SSDT is creating the sqlproj file with `%40` file references. Should be simple to automatically have ADS replace them with `@`  instead of hoping users stumble across the workaround?
