### ISSUE TITLE
WYSIWYG: Copy pasted content looses fidelity after the notebook is saved

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#16490] opened 2021-07-29 23:49 UTC
- Azure Data Studio Version: 1.31.1
- OS Version: Windows 10

**Steps to Reproduce:**

1. Copy OneNote  content and paste into a notebook next cell. The pasted content looks exactly similar to OneNote.
2. 
![image](https://user-images.githubusercontent.com/29285871/127580746-7fa78a14-3a51-4e90-938e-c56ede60ba3a.png)

3. Now save the notebook and the content looses its fidelity
4. 
![image](https://user-images.githubusercontent.com/29285871/127580805-700d97ae-67d8-479f-aa9a-dd4af0f0bb9a.png)

This causes frustration to users.

**Expectation:**
Atleast if the pasted content looks like the content after it is saved it would reduce some of users frustration

**Comment by MsSQLGirl** [comment] 2021-08-05 23:51
@rajeshka  This seems to be a duplicate to this issue that I reported earlier: https://github.com/microsoft/azuredatastudio/issues/14051

**Comment by chlafreniere** [comment] 2021-08-20 20:01
Closing as dupe of #14051.

**Closed by chlafreniere** 2021-08-20 20:01 UTC
Labels: Area - Notebooks, Enhancement, Pri: 2, Triage: Done, Impact: Live site
