### ISSUE TITLE
'GitHub.copilot' CANNOT use API proposal: terminalDataWriteEvent.

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23766] opened 2023-07-11 06:15 UTC
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Console error captured on startup:

```
Error: Extension 'GitHub.copilot' CANNOT use API proposal: terminalDataWriteEvent.
Its package.json#enabledApiProposals-property declares: inlineCompletionsAdditions but NOT terminalDataWriteEvent.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot
```

**Comment by cheenamalhotra** [comment] 2023-07-11 15:51
Ohk, didn't realize there's similar open issue.. I'll close it as duplicate then. Thanks!

**Comment by lewis-sanchez** [comment] 2023-07-11 16:18
@Charles-Gagnon, yeah, it's because of that. The extension needs to be pushed up to the gallery.

**Comment by lewis-sanchez** [comment] 2023-07-11 16:21
Even after the extension is pushed up to the gallery we may still see this. I noticed it in VS Code, and Karl's recommendation was to copy over the proposed API's as they appear in the product json for VS Code release 1.79.2.

**Comment by Charles-Gagnon** [comment] 2023-07-13 03:56
@lewis-sanchez Please verify whether this is an issue that needs to be fixed for July, or whether this is expected behavior

**Comment by lewis-sanchez** [comment] 2023-07-13 20:53
@cheenamalhotra and @Charles-Gagnon, I'm seeing the same error in VS Code 1.79.2, which is the same VS Code version powering Azure Data Studio after our most recent merge.



![Image](https://github.com/microsoft/azuredatastudio/assets/87730006/988a3936-85c5-402d-94a2-3443b153e652)

**Comment by Charles-Gagnon** [comment] 2023-07-13 21:37
Sounds good, thanks. I'd still probably let Jordan know to make sure there aren't any issues they're aware of, but we can probably close this as completed for now then.

**Comment by kisantia** [comment] 2023-07-14 17:51
@lewis-sanchez can you please move this issue out of the July milestone or close it if this is expected behavior for the July release?

**Closed** 2023-07-14 17:53 UTC
Labels: Bug, Triage: Done, Approved, Area - Copilot

**Comment by Hiradpi** [comment] 2024-09-24 09:39
im using arch linux with vscode insiders and i was able to solve this issue by downloading an AUR package called code-features-insiders
`yay -S code-features-insiders`
