### ISSUE TITLE
Installation Error related to Books feature

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#7766] opened 2019-10-17 18:10 UTC
I got the following error while installing ADS insider build on Windows.

![Screen Shot 2019-10-17 at 11 07 02 AM](https://user-images.githubusercontent.com/13777222/67035379-68947600-f0ce-11e9-9d58-d47da850c427.png)

@MaddyDev looks familiar to you?

**Comment by alanrenmsft** [comment] 2019-10-17 18:12
More info: I had an older insider version installed.

**Comment by MaddyDev** [comment] 2019-10-17 18:39
@alanrenmsft  I haven't seen this before, does this happen when you're installing ADS?

**Comment by MaddyDev** [comment] 2019-10-17 18:56
I was able to repro this. I just pinged Stuart and asked him to update the name of the file. I tested this yesterday on Mac and didn't run into this, looks like this's a windows thing. I'll push an update as soon as I hear back from Staurt. Thanks @alanrenmsft

**Comment by ellbosch** [comment] 2019-10-17 19:54
This is a duplicate of #7761, so I'll close this thread.

**Closed by ellbosch** 2019-10-17 19:54 UTC
