### ISSUE TITLE
Diagram and Table Design UI

### ISSUE THREAD

**Issue by WisdomCorp** [microsoft/azuredatastudio#11787] opened 2020-08-13 05:47 UTC
** We would like the Diagram and Table Design UI like in SQL Server Management Studio like in Windows. **
Diagram like how we visually build relationship in Sql Server Management Studio in Windows. Thanks

**Comment by kburtram** [comment] 2021-09-10 22:05
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/282 and https://github.com/microsoft/azuredatastudio/issues/94.  Thanks for opening this suggestion!

**Closed by kburtram** 2021-09-10 22:05 UTC
Labels: Enhancement, Triage: Needed
