### ISSUE TITLE
Notebook Kernel doesn't load; and "Could not display contents: Cannot read property 'layout' of undefined" error

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11839] opened 2020-08-18 00:50 UTC
- Azure Data Studio Version: (Note: This build is from @gupta1 )
Version: 1.21.0
Commit: c44e2bc6104d3cfcdc4b2800d9ec56515491f988
Date: 2020-08-13T19:16:41.418Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a notebook (or create a new one)
Kernel is stuck. 
![image](https://user-images.githubusercontent.com/6405919/90458001-015e9e00-e0b2-11ea-8313-ee988ff86005.png)
and the following error showed up.
![image](https://user-images.githubusercontent.com/6405919/90457966-dffdb200-e0b1-11ea-9df1-3bc99fda423b.png)

Error log:

C:\azuredatastudio-win32-x64\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] Message {0} Started didn't get externalized correctly. (at Object.localize (c:\azuredatastudio-win32-x64\resources\app\extensions\kusto\dist\main.js:1:62410))
console.<computed> @ C:\azuredatastudio-win32-x64\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
C:\azuredatastudio-win32-x64\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 Could not display contents: Cannot read property 'providerName' of undefined
console.<computed> @ C:\azuredatastudio-win32-x64\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
2C:\azuredatastudio-win32-x64\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] (node:15628) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))

**Comment by MsSQLGirl** [comment] 2020-08-18 02:20
+ @gupta1 
It seems that in the build, the only way I can create a new notebook using this build is to launch it from either (a) "Manage" dashboard or (b) from right click server > New Notebook. 
If I do "File" > "New Notebook" it doesn't work.

**Comment by chlafreniere** [comment] 2020-08-18 18:13
This was fixed on Friday and I verified the fix in the latest insiders build.

Dupe of #11818.

**Closed by chlafreniere** 2020-08-18 18:13 UTC
Labels: Area - Notebooks, Bug, Impact: Kusto, Triage: Needed
