### ISSUE TITLE
Python.exe processes being left behind using ADS

### ISSUE THREAD

**Issue by stuartpa** [Microsoft/azuredatastudio#4920] opened 2019-04-09 15:21 UTC
Through my normal usage pattern, lots of python.exe processes are getting left behind.  Some of these processes end up holding locks on files, which then tend to break other things (like upgrades to those files). 

These python.exe processes are still around after stoppping and restarting ADS many times.

C:\temp>kill python
process python.exe (22448) - '' killed
process python.exe (17164) - '' killed
process python.exe (23784) - '' killed
process python.exe (17636) - '' killed
process python.exe (9828) - '' killed
process python.exe (20128) - '' killed
process python.exe (1836) - '' killed
process python.exe (23864) - '' killed
process python.exe (2036) - '' killed
process python.exe (16404) - '' killed
process python.exe (22960) - '' killed
process python.exe (3692) - '' killed
process python.exe (14404) - '' killed
process python.exe (22216) - '' killed
process python.exe (23968) - '' killed
process python.exe (19880) - '' killed
process python.exe (13816) - '' killed
process python.exe (8252) - '' killed
process python.exe (11588) - '' killed
process python.exe (18856) - '' killed
process python.exe (13644) - '' killed
process python.exe (19480) - '' killed
process python.exe (21096) - '' killed
process python.exe (15808) - '' killed
process python.exe (25832) - '' killed
process python.exe (17456) - '' killed
process python.exe (5960) - '' killed
process python.exe (21592) - '' killed
process python.exe (18988) - '' killed
process python.exe (21248) - '' killed
process python.exe (9896) - '' killed
process python.exe (19624) - '' killed
process python.exe (25144) - '' killed
process python.exe (24928) - '' killed
process python.exe (19124) - '' killed
process python.exe (18088) - '' killed
process python.exe (22136) - '' killed
process python.exe (28504) - '' killed
process python.exe (6756) - '' killed
process python.exe (13008) - '' killed
process python.exe (23292) - '' killed
process python.exe (16752) - '' killed
process python.exe (22816) - '' killed
process python.exe (1364) - '' killed
process python.exe (12008) - '' killed
process python.exe (11072) - '' killed
process python.exe (8172) - '' killed
process python.exe (1416) - '' killed
process python.exe (16196) - '' killed
process python.exe (22352) - '' killed
process python.exe (7392) - '' killed

C:\temp>

**Comment by chlafreniere** [comment] 2019-04-12 16:58
This is a dupe of #3477

**Closed by chlafreniere** 2019-04-12 16:58 UTC
