### ISSUE TITLE
Connect to SQL managed instance dialogue box appears after instance's tab has been closed

### ISSUE THREAD

**Issue by nasc17** [microsoft/azuredatastudio#12748] opened 2020-10-05 20:25 UTC
This was found when I would accidentally click on my SQL managed instance. I would close out of the tab and continue to the correct resource I was trying to view and the dialogue box would open on my screen even though I was longer viewing the instance. 

Steps to Reproduce:

1. Click to open SQL managed instance from controller dashboard. 
2. Quickly close tab. 
3. Wait for dialogue box to still appear. (In this example I was already on the dashboard page for my PostgreSQL instance)
![bugproof](https://user-images.githubusercontent.com/69922333/95128374-2ebce500-070e-11eb-9bce-fc3de4527cca.png)

**Comment by Charles-Gagnon** [comment] 2020-10-05 21:01
Could add a cancellation token for this kind of scenario to make sure we're only opening opening the dialog when it makes sense.

Even if we don't close the tab but move to another one it would still pop up later on too.

Might even be worth looking into popping up the dialog right away and then displaying a loading spinner until we get the MIAA endpoint info.

**Comment by Charles-Gagnon** [comment] 2020-11-13 00:42
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/13373

**Closed by Charles-Gagnon** 2020-11-13 00:42 UTC
Labels: Area - Azure Arc, Triage: Done
