### ISSUE TITLE
script renders in red from line 2,as if inside a string literal

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#10315] opened 2020-05-08 13:18 UTC
Issue Type: <b>Bug</b>

This script

```SQL
declare @ varchar(200) = N'\'
set @ = replace(@, N'\', N'\\') 
select @

```
reders in red from line 2, as if it is inside a string literal, which it  is not.  It runs fine.

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.6
powershell|ms-|2020.4.0

</details>

![image](https://user-images.githubusercontent.com/12263288/81409406-0902c400-910d-11ea-9ecc-91ddc3995e84.png)

**Comment by Charles-Gagnon** [comment] 2020-05-08 14:18
Duplicate of #10208 - see that for a workaround to revert to older version of the language file.

**Closed by Charles-Gagnon** 2020-05-08 14:18 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
