### ISSUE TITLE
Databases not loading from server

### ISSUE THREAD

**Issue by JelmerWouters** [microsoft/azuredatastudio#21126] opened 2022-11-07 10:50 UTC
Issue Type: <b>Bug</b>

I can connect to a server, but in my 'Connections' menu the server keeps 'spinning', thus not loading the databases within that server

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 22.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment] 2022-11-07 18:17
Duplicate of #5173

**Closed by cheenamalhotra** 2022-11-07 18:17 UTC
