### ISSUE TITLE
Copy and paste values into a query in list form

### ISSUE THREAD

**Issue by kierenj** [microsoft/azuredatastudio#5226] opened 2019-04-26 09:36 UTC
Issue Type: <b>Feature Request</b>

Hi,

I'd love to be able to select some cells in a result set, then paste it into the query window as a list.

For instance, I just copied 3 GUIDs to my clipboard.  They paste as:

```
3e91e219-0bb4-4c2c-ba5a-4d4d14609c16
49e792b5-c401-466c-98e7-315953de0e24
8b45898e-7903-4914-a67f-a2e6446be5a2
```

However, I'd love them to paste as:

```
(
'3e91e219-0bb4-4c2c-ba5a-4d4d14609c16',
'49e792b5-c401-466c-98e7-315953de0e24',
'8b45898e-7903-4914-a67f-a2e6446be5a2'
)
```

(for use in an IN query)

Would this be best as an extension?  Or as a core part of the product?

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alanrenmsft** [comment] 2023-06-09 20:55
close as dupe of https://github.com/microsoft/azuredatastudio/issues/5226, I added list as a format.

**Closed by alanrenmsft** 2023-06-09 20:55 UTC
Labels: Area - Query Editor, Enhancement
