### ISSUE TITLE
sqlmi/pg instance creation from wizard shows blank controller context

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12377] opened 2020-09-16 22:17 UTC
![depwiz-pg](https://user-images.githubusercontent.com/10999577/93398081-b90cda00-f82f-11ea-90e9-945279584a45.png)
![depwiz-sqlmi](https://user-images.githubusercontent.com/10999577/93398083-b9a57080-f82f-11ea-8217-25df040fb413.png)

Issue Type: <b>Bug</b>

Repro Steps:

1. Invoke the "New Deployment" wizard from servers viewlet
2. Pick SQLMI / PG create
3. Data controller should be populated from current context and/or shown here

See attached screenshots for current behavior. There is no way for user to proceed further.

Azure Data Studio version: azuredatastudio-rc1 1.22.0-rc1 (fb28b69bb0897660e38b85ffabdff79c345a8043, 2020-09-16T19:25:06.133Z)
OS version: Windows_NT x64 10.0.20215

**Comment by Charles-Gagnon** [comment] 2020-09-16 22:29
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12344

**Closed by Charles-Gagnon** 2020-09-16 22:29 UTC
Labels: Bug, Triage: Needed
