### ISSUE TITLE
Can't login in Azure China

### ISSUE THREAD

**Issue by tcbjc** [microsoft/azuredatastudio#14121] opened 2021-01-30 08:51 UTC
- Azure Data Studio Version: 1.25.2 for Windows

Steps to Reproduce:
1. Setting - Extensions - Azure Account Configuration - enable China Cloud
2. Add China Account - redirect to browser - fill in user & password - get error
![image](https://user-images.githubusercontent.com/26422656/106352064-3dfa1b00-631b-11eb-9a9b-9d75b356baf9.png)

**Comment by jebouruama** [comment] 2021-02-01 08:47
Same error when using kusto plugin to connect to ADX in China azure cloud.

**Comment by tcbjc** [comment] 2021-03-16 07:07
@cssuh @kburtram We are still waiting for Azure Data Studio support China Azure. I find the bug have moved to backlog from March 2021 Release, Would you please let us know when it can work?

**Comment by yehh** [comment] 2021-08-04 05:30
It looks still failed to redirect when we enabled the Azure China, and it prompt when I try to " Add account" even we enabled the Azure China only.

**Comment by zhengyiqun** [comment] 2021-08-08 14:41
Linux version 1.31.1, still unable to add Chinese account. The error is: "The resource principal named https://management.core.windows.net/ was not found in the tenant named *.partner.onmschina.cn"

**Comment by zhengyiqun** [comment] 2021-08-08 14:43
Linux version 1.31.1, still unable to add azure china account. The error is: "The resource principal named https://management.core.windows.net/ was not found in the tenant named *.partner.onmschina.cn"

**Comment by Charles-Gagnon** [comment] 2021-08-09 16:18
@JustinMDotNet - Is there anything else people need to do to enable this scenario?

**Comment by yehh** [comment] 2021-08-09 17:00
There are 2 issues: 
1. If I only check the Azure China account, it will prompt "At least one Azure cloud should be enabled", we expect to redirect to *.onmschina.cn url once I click Add Account.
2. Thus, I have to select other than Azure China (Global and China). it will redirect to Global url once I click the Add Account

**Comment by JustinMDotNet** [comment] 2021-08-13 19:09
Looks like this needs additional research / work. Reopening.

**Comment by JustinMDotNet** [comment] 2021-08-13 19:10
> There are 2 issues:
> 
> 1. If I only check the Azure China account, it will prompt "At least one Azure cloud should be enabled", we expect to redirect to *.onmschina.cn url once I click Add Account.
> 2. Thus, I have to select other than Azure China (Global and China). it will redirect to Global url once I click the Add Account

Hi Jeffrey, could you provide screenshots of this so we can duplicate the issue and research further?

**Comment by yehh** [comment] 2021-08-17 14:47
Please check the screenshot if I only check the Azure China. 
<img width="1332" alt="Untitled" src="https://user-images.githubusercontent.com/618842/129747996-9246eabd-6a27-4314-89eb-c280f423026b.png">

**Comment by yehh** [comment] 2021-08-17 14:53
If I turn on the options for Azure China and Azure Public, it will redirect to Login page of Azure Global. 
<img width="1330" alt="Untitled1" src="https://user-images.githubusercontent.com/618842/129748816-270810c3-4d12-46df-8152-249ea0c86fd9.png">
<img width="1278" alt="Untitled2" src="https://user-images.githubusercontent.com/618842/129748829-3c1ad0ca-3bda-4da5-b8ae-92ac3bd50f4f.png">

**Comment by cheenamalhotra** [comment] 2022-12-16 20:58
Checking in, can someone please test and confirm with the latest stable and insiders build, if the issue is now addressed.
Thanks for taking the time!

**Comment by cheenamalhotra** [comment] 2023-01-16 21:40
Closing as issue seems fixed with PR https://github.com/microsoft/azuredatastudio/pull/15746

**Closed by cheenamalhotra** 2023-01-16 21:40 UTC
Labels: Bug, Area - Azure, Pri: 2, Triage: Done, Size: S
