### ISSUE TITLE
Azure Data Studio-Log In issue-log in with Windows authentication with alternate credentials 

### ISSUE THREAD

**Issue by sraycpa** [Microsoft/azuredatastudio#2807] opened 2018-10-10 14:21 UTC
I am interested in doing a test drive on Azure Data Studio and thus downloaded it and installed it but was not able to connect with our SQL Server database because the choice of credentials for Windows Authentication does not have the choice of alternate credentials as a sign on choice.
It will be great if the Azure Data Studio can be configured to enable us to log in with Windows authentication with alternate credentials as a choice as my Excel Power Query connection as shown below connecting to our SQL Server data warehouses
I have given below the screenshot from my Excel connection to our BI SQL Server 2014 data warehouse.
Also I have given below the Azure data warehouse connection choices. Although it has Windows authentication does not have the choice for Windows Authentication with alternate credentials and thus cannot connect to SQL Server with Azure data studio.

It will be great if this can be incorporated as a suggestion and looked into.
Thank
Kind Regards,
Somnath

Somnath Ray, CPA, Diploma in IFRS (ACCA UK), SAP HANA Certified (SAP Germany)
Business Intelligence Coordinator
Decision Support & Financial Analytics
Brant Community Healthcare System
200 Terrace Hill Street
Brantford, ON N3R 1G9
Ph: 519.751.5544 ext. 2507
cell: (647) 530 0675
email: Somnath.RayChaudhuri@bchsys.org
www: bchsys.org

**Comment by MattIrv** [comment] 2018-10-10 18:07
Thanks for reporting this. I think there are 2 issues here:
- We don't support specifying alternate Windows Auth credentials. See https://github.com/Microsoft/azuredatastudio/issues/112 for the existing issue. Is starting Azure Data Studio using `runas` an acceptable solution for you?
- We don't support Azure Active Directory auth yet, which it sounds like is what you're using for Azure DW. That's on our roadmap for the near future, see https://github.com/Microsoft/azuredatastudio/issues/13

I'm going to close this issue as a duplicate of those ones but please let me know if they don't capture the problems you're having.

**Closed by MattIrv** 2018-10-10 18:07 UTC

**Comment by sraycpa** [comment] 2018-10-10 18:34
Thanks I am able to log in

**Comment by sraycpa** [comment] 2018-10-10 18:34
Many many thanks
