### ISSUE TITLE
Sorting while cells are selected and then exporting those cells exports "wrong" cells

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20988] opened 2022-10-26 18:45 UTC
Stable/Insiders

Version: 1.39.1 (user setup)
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:11:13.047Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22621

1. Run query with results
2. Select some number of cells
3. Export (any should do, I used CSV) - check the selected cells are exported
4. Sort one of the grid columns so that the row order changes
5. Notice that the "selected" cells are now different (the cell contents change, not what cells themselves are selected). This seems fine to me
6. Export results again
7. The exported results are still the original selected cells, NOT the ones that are currently shown to be selected

![ExportSorting](https://user-images.githubusercontent.com/28519865/198109369-3cf6be63-39c2-4f38-b0b2-14388754bffd.gif)

**Comment by alanrenmsft** [comment] 2022-11-02 20:44
dupe of https://github.com/microsoft/azuredatastudio/issues/19030

**Closed by alanrenmsft** 2022-11-02 20:44 UTC
Labels: Bug, Area - Query Editor, Triage: Needed
