### ISSUE TITLE
ADS fails to get credentials for an azure account

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#14165] opened 2021-02-04 23:15 UTC
- Azure Data Studio Version: 1.25.2
Steps to Reproduce:

1. Add an azure account in ADS
2. Open the account in data explorer. 

![image](https://user-images.githubusercontent.com/6816294/106967311-cdc50e00-66fb-11eb-9d3d-42358462f9a1.png)

**Comment by abist** [comment] 2021-02-05 00:16
@aasimkhan30 Could you please use the template to include the ADS version in the issue as well

**Comment by Charles-Gagnon** [comment] 2021-03-09 22:48
@rajeshsetlem The error states `The user account is disabled` - have you confirmed that the account you're attempting to use is indeed active?

**Comment by rajeshsetlem** [comment] 2021-03-09 23:35
@Charles-Gagnon The account is active in my AAD home organization. But since I got added to other AAD tenants, my account is locked out in one of them and ADS should ideally have improved exception handling.

**Comment by kenvanhyning** [comment] 2021-04-05 16:43
Moving tenant related work to May.  Too large of a change to add for ask mode.

**Comment by cssuh** [comment] 2023-03-30 22:10
We have since fixed the tenant fetching logic, so closing this.

**Closed by cssuh** 2023-03-30 22:10 UTC
Labels: Bug, Area - Azure, Triage: Postponed
