### ISSUE TITLE
GO N command flagged as error in query editor

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#7690] opened 2019-10-11 16:53 UTC
Issue Type: <b>Bug</b>

The valid syntax "GO 50" is showing red squigglies in both query editors and notebooks.

![image](https://user-images.githubusercontent.com/8250560/66669585-b4e24080-ec0c-11e9-8f35-211b30b8f329.png)

![image](https://user-images.githubusercontent.com/8250560/66669609-bdd31200-ec0c-11e9-85d2-6e78d4653f9c.png)

However the "problems" pane seems to show the error a little differently for notebooks vs query editors

![image](https://user-images.githubusercontent.com/8250560/66669529-98460880-ec0c-11e9-8fb2-d8c29f5acbe5.png)

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (cacbcb54156f4748a0a2d3181f9fc0ad16805b13, 2019-10-07T07:56:20.452Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
big-data-cluster|Mic|0.0.1
cms|Mic|0.5.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
powershell|ms-|2019.9.0
profiler|Mic|0.10.0
query-history|Mic|0.1.0
schema-compare|Mic|0.7.0
sql-vnext|Mic|0.14.1
azdata-sanddance|msr|1.3.7

(1 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment] 2019-10-11 17:44
dupe of https://github.com/microsoft/azuredatastudio/issues/6974

**Closed by alanrenmsft** 2019-10-11 17:44 UTC
