### ISSUE TITLE
A11y_AzureDataStudio_ManageAccessForFile_Zoom:After zooming to 150% data is getting lost . 

### ISSUE THREAD

**Issue by V-sheman** [microsoft/azuredatastudio#7811] opened 2019-10-18 07:50 UTC
GitHubTags: #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG1.4.4;#DesktopApp;#Win32;#Zoom;
**Environment Details: **
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit:6582debd7388b1be512fc3a9b956d3e54f6115e7
Date: 2019-10-03T08:56:27.454Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
**Additional Details:**
Tool Name : Zoom
**Steps to Reproduce:**
1.Install and Launch the application the azure data studio application.
2.Connet to the servers with the required credentials.
3.Navigate to the control panel and click on the “Jupyter books” icon.
4.Navigate till HDFS folder and right click on it and click on manage access.
5. Zoom the screen by pressing CTRL + 
**Actual:**
After zooming to 150% data of the Screen getting disappear and there is no scroll bar to access the content.
**Expected:**
Data of the screen should not disappear at least till 200%
**User Impact:**
Low vision user will not able to use the data as the data is gettin lost.
**Attachment for Reference:**
[7811_A11y_AzureDataStudio_ManageAccessForFile_Zoom.pptx](https://github.com/microsoft/azuredatastudio/files/3750156/7811_A11y_AzureDataStudio_ManageAccessForFile_Zoom.pptx)
Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment] 2019-11-18 15:35
This is fixed in current insiders builds.

**Closed by Charles-Gagnon** 2019-11-18 15:35 UTC
Labels: A11yMAS, A11y_ADS_OctTestPass, Area - Big Data Cluster, Bug, Impact: Accessibility, Triage: Done

**Comment by vinodbk197** [comment] 2020-01-31 12:03
Verified this issue on:
Azure Data Studio
Version: 1.15.0-insider (user setup)
The issue is resolved, Hence closing this bug.
[7811_Closed.pptx](https://github.com/microsoft/azuredatastudio/files/4139166/7811_Closed.pptx)

**Comment by fsteffi** [comment] 2023-03-03 11:32
#Azure Data Studio - New Features_win32;

**Comment by sspatil123** [comment] 2023-05-31 10:35
#A11ySev2;
