### ISSUE TITLE
Azure Arc Extension is stuck on Loading controllers step. 

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/azuredatastudio#17120] opened 2021-09-21 07:24 UTC
Issue Type: <b>Bug</b>

- Azure Data Studio Version: 1.32.0
- OS Version:  Windows 10 Enterprise 21H1

Steps to Reproduce:
1. Install Azure Arc Extension (v0.9.6)

2. Under the **Azure Arc Controller connection tab**, the status is stuck at **Loading controllers...**. Also, the create and connect controller button is not working.
   
![image](https://user-images.githubusercontent.com/45102602/134127742-4fca9fc3-b12d-4b62-82e6-47fb87a26374.png)

Extension version: 0.9.6
Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment] 2021-09-21 16:03
@candiceye

**Comment by chlafreniere** [comment] 2021-12-01 00:49
Closing as we need logs to further debug this issue. If the issue is still reproducible, please feel free to reactivate with the logs requested. Thanks!

**Closed by chlafreniere** 2021-12-01 00:49 UTC
Labels: Bug, Triage: Needed, Needs Logs, Area - Azure Arc

**Comment by sumitmalik51** [comment] 2021-12-03 14:21
@chlafreniere Was able to resolve the issue after updating Data studio.
