### ISSUE TITLE
Errors launching and connecting to databases

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#20919] opened 2022-10-21 19:41 UTC
- Azure Data Studio Version: 
```
Version: 1.40.0-insider (user setup)
Commit: 533e1ec1b921d2d246695f6edc441a8231790e9a
Date: 2022-10-21T16:25:06.751Z
VS Code: undefined
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22621
```

Steps to Reproduce:

1. Launch ADS-Insiders
2. See error message in notification:
 
![image](https://user-images.githubusercontent.com/13488/197276193-edee1a82-cc3c-429c-a789-023e8be9b991.png)

![image](https://user-images.githubusercontent.com/13488/197276241-dbf8b954-f335-4450-bf3d-227a87953918.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

There is no Report Issue menu item.

**Comment by Charles-Gagnon** [comment] 2022-10-21 21:01
Dupe of https://github.com/microsoft/azuredatastudio/issues/20916 - we have a fix out and this will be resolved with the next build. Thanks and sorry for the inconvenience!

**Closed by Charles-Gagnon** 2022-10-21 21:01 UTC
Labels: Bug, Area - Connection, Triage: Needed

**Comment by raphaelquati** [comment] 2022-10-21 21:06
To the error is different:

![image](https://user-images.githubusercontent.com/815086/197287888-3bb585f4-7989-42ca-ab8c-143cccb64ae7.png)

```
[2022-10-21 18:02:19.939] [renderer1] [warning] [Microsoft.azure-cosmosdb-ads-extension]: No description specified to show.
[2022-10-21 18:02:23.560] [renderer1] [error] [/c:/Users/raphc/.azuredatastudio-insiders/extensions/microsoft.azuredatastudio-mysql-0.2.3-alpha.1]: Version specified in `engines.vscode` (*) is not specific enough. For vscode versions before 1.0.0, please define at a minimum the major and minor desired version. E.g. ^0.10.0, 0.10.x, 0.11.0, etc.
[2022-10-21 18:02:23.562] [renderer1] [error] [/c:/Users/raphc/.azuredatastudio-insiders/extensions/microsoft.import-1.5.0]: Version specified in `engines.vscode` (*) is not specific enough. For vscode versions before 1.0.0, please define at a minimum the major and minor desired version. E.g. ^0.10.0, 0.10.x, 0.11.0, etc.
[2022-10-21 18:02:23.564] [renderer1] [error] [/c:/Users/raphc/.azuredatastudio-insiders/extensions/microsoft.query-history-0.5.1]: Version specified in `engines.vscode` (*) is not specific enough. For vscode versions before 1.0.0, please define at a minimum the major and minor desired version. E.g. ^0.10.0, 0.10.x, 0.11.0, etc.
[2022-10-21 18:02:23.566] [renderer1] [error] [/c:/Users/raphc/.azuredatastudio-insiders/extensions/microsoft.sql-migration-1.1.1]: Version specified in `engines.vscode` (*) is not specific enough. For vscode versions before 1.0.0, please define at a minimum the major and minor desired version. E.g. ^0.10.0, 0.10.x, 0.11.0, etc.
[2022-10-21 18:02:23.570] [renderer1] [error] [/c:/Users/raphc/.azuredatastudio-insiders/extensions/microsoft.kusto-0.5.7]: Version specified in `engines.vscode` (*) is not specific enough. For vscode versions before 1.0.0, please define at a minimum the major and minor desired version. E.g. ^0.10.0, 0.10.x, 0.11.0, etc.

```
