### ISSUE TITLE
Viewlet icons don't render correctly in some themes

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#20962] opened 2022-10-25 15:50 UTC
- Azure Data Studio Version: `insider`

Steps to Reproduce:

1. Open ADS and switch themes to Solarized or Quiet Light, for example 

Expected: Icons in action bar render consistently

Actual: Some icons are using a white outline rather than a theme aware color.  Screenshot below.

![image](https://user-images.githubusercontent.com/599935/197821455-d841e313-a71e-4766-abe1-75ab78c4558f.png)

**Comment by Charles-Gagnon** [comment] 2022-10-25 16:10
Duplicate of https://github.com/microsoft/azuredatastudio/issues/11930 so not a recent regression.

Given that we've now opened this issue a number of times maybe worth actually fixing here though?

I'll close the other issue since that one only mentions Notebooks

**Closed** 2022-10-27 02:27 UTC
Labels: Bug, Area - Shell, Triage: Done, Size: S
