### ISSUE TITLE
New deployment isn't working from welcome screen

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#9475] opened 2020-03-06 11:28 UTC
Issue Type: <b>Bug</b>

when clicking "new deployment" on welcome screen, nothing happens.

it does work fine from the contect menu next to open connections

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (13.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-03-06 18:13
Duplicate of https://github.com/microsoft/azuredatastudio/issues/9120

@chlafreniere What's the state of your PR?

**Closed by Charles-Gagnon** 2020-03-06 18:13 UTC
Labels: Bug, Triage: Needed
