### ISSUE TITLE
Better formatting for generated T-SQL from Open API spec

### ISSUE THREAD

**Issue by zijchen** [microsoft/azuredatastudio#17234] opened 2021-10-04 21:39 UTC
Current formatting when generating sqlproj from Open API spec:
```sql
CREATE TABLE [SwaggerPetstore.Models].[NewPet](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](4000) NOT NULL,
	[Tag] [nvarchar](4000) NULL,
 CONSTRAINT [PK_NewPet] PRIMARY KEY CLUSTERED 
(
	[Id]
)
)
```

**Comment by zijchen** [comment] 2021-10-04 23:08
Same table from extract: 
```sql
CREATE TABLE [SwaggerPetstore.Models].[NewPet] (
    [Id]   INT             NOT NULL,
    [Name] NVARCHAR (4000) NOT NULL,
    [Tag]  NVARCHAR (4000) NULL,
    CONSTRAINT [PK_NewPet] PRIMARY KEY CLUSTERED ([Id] ASC)
);
```

**Comment by Benjin** [comment] 2021-10-05 20:32
This is how SMO generates scripts

Options:
* SMO scripting options to prettify it
* scriptdom interpret -> generate
* vscode format document

**Comment by udeeshagautam** [comment] 2022-04-22 18:51
Closing as by design (from SMO) for now.

**Closed by udeeshagautam** 2022-04-22 18:51 UTC
Labels: Enhancement, Triage: Done, Area - SQL Project
