### ISSUE TITLE
Can't reset zoom

### ISSUE THREAD

**Issue by MartinDemberger** [microsoft/azuredatastudio#19584] opened 2022-06-01 10:58 UTC
Issue Type: <b>Bug</b>

Long ago I changed the zoom in Azure Data Studio for screen sharing.

Now I can't reset the zoom back to 100%.

When I select `View: Reset Zoom` it changes to 100% but after a while it changes back to my presentation zoom setting.

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (9.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cms|Mic|0.8.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
schema-compare|Mic|1.13.1
sql-assessment|Mic|0.6.1

</details>

**Comment by Charles-Gagnon** [comment] 2022-06-01 16:15
Duplicate of https://github.com/microsoft/azuredatastudio/issues/14128

If there's a specific action that you've noticed resets your zoom please add it to that issue so we can make sure to track the places this occurs for fixing!

**Closed by Charles-Gagnon** 2022-06-01 16:15 UTC
