### ISSUE TITLE
Split is duplicating data

### ISSUE THREAD

**Issue by superiusonline** [microsoft/azuredatastudio#16430] opened 2021-07-25 13:14 UTC
Issue Type: <b>Bug</b>

function "split" is duplicating the query and does not allow to use the tabs with different query

Azure Data Studio version: azuredatastudio 1.31.0 (a430fd2592763ef4c4a406821967e4b7b2b3d876, 2021-07-20T19:49:59.277Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 7|
|Memory (System)|4.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-pt-BR|Mic|1.31.0

</details>

**Comment by superiusonline** [comment] 2021-08-01 15:34
no one had this problem?

Every time I click on the split, it duplicates the query and any change I make, does in both

**Comment by Charles-Gagnon** [comment] 2021-08-02 19:15
I am able to repro this myself, let me take a look here...was this something that recently started having issues?

**Comment by superiusonline** [comment] 2021-08-02 19:38
Hi Charles, Thank you for your help.

Yes, recently. More specifically, when I upgraded to the latest version (Release number: 1.31.1
Release date: July 29, 2021). I use a Mac Air 13, run the Big Sur 11.5 OS

I've already tried to clear the user settings. However, it remains the same. By clicking the "Split" button, instead of opening a new blank page to write a new query, the system duplicates the current query and any changes you make to one, tb makes the same change in the other.

**Comment by Charles-Gagnon** [comment] 2021-08-02 20:29
So from my testing this seems to be working as intended. When splitting the editor it will duplicate the current editor in the new group - after which you can close the editor in the old group if you wish. This is behavior we inherited from VS Code and it looks like this isn't something they intend on changing currently.

https://github.com/microsoft/vscode/issues/112756 

In that issue they mention a workaround - you can use the `View: New Editor Group to the Right` command to open a new blank group. This command can then be bound to a keyboard shortcut for easier use. 

I'm going to close this as working for intended for now, let us know if you think there's another issue here that I'm missing!

**Closed by Charles-Gagnon** 2021-08-02 20:29 UTC
Labels: Area - Query Editor, Bug, Triage: Done
