### ISSUE TITLE
Include Files From Explorer Into Database Project

### ISSUE THREAD

**Issue by sudhirhota1993** [microsoft/azuredatastudio#17989] opened 2022-01-05 13:38 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Once you mistakenly exclude the file/folder from SQL database Project, then there is no option to include it again even if it is available under explorer. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment] 2022-01-05 17:26
closing as duplicate of #14383

**Closed by kisantia** 2022-01-05 17:26 UTC
