### ISSUE TITLE
Error: The element data_1 is not supported in Microsoft Azure SQL Database v12.

### ISSUE THREAD

**Issue by maur1ce-m** [microsoft/azuredatastudio#24494] opened 2023-09-21 17:42 UTC
Type: <b>Bug</b>

1. Create a new table
2. Click Publish Changes

Error: Table schema validation failed with error: One or more errors occured during validation.1. The element data_1 is not supported in Microsoft Azure SQL Database v12.

Table:
CREATE TABLE [dbo].[TestTable] (
    [column_1] INT NULL
);

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (13.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

Server:
General Purpose - Serverless: Gen5, 2 vCores

**Updated Data Studio (1.46.0) and the same error occurs.**
Version: 1.46.0 (user setup)
Commit: 39449bbe88a0bc4092c9b205cad10d0a556beffd
Date: 2023-09-16T01:40:10.706Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by maur1ce-m** [comment] 2023-09-21 17:44
Table:
CREATE TABLE [dbo].[TestTable] (
    [column_1] INT NULL
);

**Comment by kisantia** [comment] 2023-09-21 20:32
duplicate of https://github.com/microsoft/azuredatastudio/issues/24123. Please use this other issue for more discussion

**Closed by kisantia** 2023-09-21 20:32 UTC
Labels: Bug, Triage: Needed, Area - Designer
