### ISSUE TITLE
Notebook: White space around markdown cells

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#10319] opened 2020-05-08 17:09 UTC
Issue Type: <b>Feature Request</b>

Hi,

There seems to be lot of white spaces around the markdown cells. Is this by design?

![image](https://user-images.githubusercontent.com/22312581/81430238-f6d85400-9113-11ea-8786-827aa2d61d11.png)

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment] 2020-05-08 17:12
Thanks for the issue, @ronychatterjee. This is a dupe of #10191, which has been fixed in master.

**Closed by chlafreniere** 2020-05-08 17:12 UTC
Labels: Area - Notebooks
