### ISSUE TITLE
Copied data from results pane has strange sorting

### ISSUE THREAD

**Issue by vonPryz** [microsoft/azuredatastudio#8291] opened 2019-11-11 12:37 UTC
Issue Type: <b>Bug</b>

Data displayed on results pane is in proper order. Results copied via clipboard to Notepad has incorrect order. 

Steps to reproduce: run tsql sample, copy results, paste into Notepad.
-- Sample
declare @foo table(id int identity(1,1), rowdata datetime2(0));
declare @i int = 0;
while @i <30
  begin
  insert @foo(rowdata) values (getdate());
  waitfor delay '00:00:01';
  set @i = @i + 1;
end
select id, rowdata from @foo order by id;
-- /Sample

Expected results after copy-paste: sort order preserved, as per SQL query.
Observed results after copy-paste: sort order is not preserved. Results are in strange order: 1, 2, 11, 12, 13...20, 3, 21, 22...

I don't recognize the sort order. It's neither dictionary, nor ASCII order. Doing the same from SSMS works fine. IIRC, this issue didn't exist in earlier a version of Azure Data Studio.

Save as CSV is not affected.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2019-11-11 16:25
Closing as a duplicate of #8210

This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release. Sorry about the inconvenience!

**Closed by Charles-Gagnon** 2019-11-11 16:25 UTC
