### ISSUE TITLE
Ability to connect Azure Analysis Services and Analysis Services as well

### ISSUE THREAD

**Issue by ndondapati** [microsoft/azuredatastudio#3757] opened 2019-01-16 22:10 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by demyte** [comment] 2019-01-20 21:42
Duplicate of #1026 I think

**Comment by kburtram** [comment] 2020-02-21 18:54
Closing as duplicate of #1026

**Closed by kburtram** 2020-02-21 18:54 UTC
Labels: Enhancement
