### ISSUE TITLE
Incorrect data display on the data grid when large data display

### ISSUE THREAD

**Issue by cengiz** [microsoft/azuredatastudio#24740] opened 2023-10-20 14:59 UTC
Type: <b>Bug</b>

I have a column where I store the message data from Whatsapp in json format. Json length is around 4500 characters. When I query the table in the datagrid in Azure data studio, this column and subsequent columns appear incorrect. When I copy, it copies the correct data to the clipboard, but the display on the grid is incorrect. After navigating between tabs it shows correctly.

Incorrect Display :
![incorrect display](https://raw.githubusercontent.com/cengiz/cengiz/master/azure_data_studio_datagrid_display_error.png)

Correct Display :
![correct display](https://raw.githubusercontent.com/cengiz/cengiz/master/azure_data_studio_datagrid_display_normal.png)

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by cheenamalhotra** [comment] 2023-10-20 17:14
@cengiz 

Could you please gather logs for the event when you query and incorrect data is loaded?

**Comment by allan-stewart** [comment] 2023-11-06 15:08
I also noticed this issue today. I did a simple query to pull a single table row from the database, then as I scrolled through, I noticed that some fields contained HTML where that is not allowed, then realized it was repeating the same data.

But when I select those fields directly, it comes up with the correct data, even when I run the two queries together:

![image](https://github.com/microsoft/azuredatastudio/assets/1467577/30c972d1-a872-4c8e-94a6-6c22a0469295)

This is a **really bad bug** that makes ADS nearly unusable. I don't know if I can trust what I see when I use ADS anymore. I can't spend all day double checking if ADS is showing me correct data or decided to lie to me again.

Here is my version info:
```
Version: 1.46.1
Commit: ba29842b81dec01177415e53948ca2168e69c3f8
Date: 2023-10-02T18:15:27.480Z
VS Code: 1.79.2
Electron: 22.3.25
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

My coworker is not experiencing this issue and he's on version `1.46.0`, so maybe that might help you find the problem?

I followed the instructions you have to @cengiz above, and have attached my console.log and application logs.

[console.log](https://github.com/microsoft/azuredatastudio/files/13268201/console.log)
[20231106T074836.zip](https://github.com/microsoft/azuredatastudio/files/13268240/20231106T074836.zip)

I looked though the logs and didn't see any sensitive info, but there's a lot of little files in there...

Also important: after restarting the app, the incorrect display of data didn't happen every time as before, but only happened when I only did the single `select *` statement. So it definitely happened, just not every time (which is why you'll see multiple runs of the same queries in the log).

**Comment by cengiz** [comment] 2023-11-30 07:56
Hello, I haven't experienced this issue again. I tried again under the same conditions and viewed it without any problems.
That's why I didn't get back to you. The issue might have been resolved.
Thank you for your interest

**Comment by kisantia** [comment] 2024-02-12 22:03
Closing since it hasn't been encountered again. Please reopen if it happens again and can be reproduced :)

**Closed by kisantia** 2024-02-12 22:03 UTC
Labels: Bug, Area - Query Editor, Pri: 1, Triage: Done, Needs Logs
