### ISSUE TITLE
Changing kernel to Python 3 doesn't work

### ISSUE THREAD

**Issue by pete1854** [microsoft/azuredatastudio#11611] opened 2020-08-03 11:17 UTC
Issue Type: <b>Bug</b>

1. Install ADS
2. Create a new Notebook
3. Change kernel to Python 3
4. Let ADS install a new instance of Python
5. Let ADS launch the notebook server w/ the previously installed python instance

The output windows shows the Notebook server is starting. But the Kernel drop-down keeps displaying "_Changing kernel..._". Clicking on "Run cell" results in a notification saying "_The session for this notebook will start momentarily_".

![Anteckning 2020-08-03 131532](https://user-images.githubusercontent.com/47314226/89177985-e86fcc00-d58c-11ea-888d-4c82e5c805e3.png)

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (22.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment] 2020-08-04 17:34
This is a dupe of #11607. Tracking the issue there.

**Closed by chlafreniere** 2020-08-04 17:34 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
