### ISSUE TITLE
Add sorting feature in Declarative Table Component

### ISSUE THREAD

**Issue by stuti149** [microsoft/azuredatastudio#17030] opened 2021-09-09 06:49 UTC
- Azure Data Studio Version:
- OS Version:

Sorting is a feature that needs to be added to the declarativeTable component.
Needed for Task 1339604: ADS UI - Sort by column on the migration status table

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment] 2021-09-09 17:47
@stuti149 do you have the mockup?

**Comment by stuti149** [comment] 2021-09-10 05:01
> @stuti149 do you have the mockup?

Please look into this Figma screen to view the sort icon. Link below:
https://www.figma.com/file/8Sot7uP9IUOblkav27aW8C/ADS-Migrations?node-id=4978%3A496762

![image](https://user-images.githubusercontent.com/87131830/132802032-bf7de1d6-daed-484d-a405-96d604b942d5.png)

Note: The table is sorted 'ascending' by the first column (Databases).

mockup to show column resize design.
https://www.figma.com/file/8Sot7uP9IUOblkav27aW8C/ADS-Migrations?node-id=6256%3A137366

![image](https://user-images.githubusercontent.com/87131830/132802149-d07e58d8-63fa-4f81-b054-335e8a102bbd.png)

**Comment by alanrenmsft** [comment] 2021-09-10 17:42
@aasimkhan30 do you remember why are we using declarativeTable instead of table component here?  the declarative table is not really meant to be an actual table, it is more of a layout component.

**Comment by aasimkhan30** [comment] 2021-09-10 17:44
We are using declarative table because it has the flexibility of having flex containers in it.

**Comment by alanrenmsft** [comment] 2021-09-10 18:16
@aasimkhan30 I am not sure whether we should implement the feature requested here, there might be another requirement for filtering tomorrow. these features are already implemented in the table component, I'd suggest to switch to the table component and add the missing features there. for example the context menu column type.

@Charles-Gagnon  what do you think?

**Comment by Charles-Gagnon** [comment] 2021-09-10 18:23
Hmm, I generally agree but we do already have filtering enabled for the declarative table so that's something to consider.

I really wish we didn't have these two table types and instead just added support to slickgrid for the stuff we needed...but I doubt we're going to be able to make that happen so here we are.

So I would suggest that first you look into adding any missing functionality into the table component as the preferred method, but if that ends up being too huge of a task then I don't think it'd be a huge deal to have it in the declarative table instead...

**Comment by aasimkhan30** [comment] 2021-09-10 18:54
While I agree with the overall sentiment towards moving to table component, there is a lot of work that needs to be done to make it look like this one from the mockups.

1. support for components. 
2. rich styling support 
3. ability to sort according to columns 
4. context menus 
5. Filtering data

If that is something that needs to be done, I can start working on it and we can deprecate declarative table for the sake of having a single table component in ADS.

**Comment by alanrenmsft** [comment] 2021-09-10 21:54
also consider this issue opened by @brian-harris : https://github.com/microsoft/azuredatastudio/issues/16445, a major issue with the declarative table component is it is not virtualized, all the items are directly added to the DOM tree, if there are too many of them, it will hang or crash as described in it.

the sorting feature requested in the issue isn't that useful if there are only small number of rows, and if there are too many rows it will cause a hang.

so, the conclusion is we should move to table component, by moving there you won't have:
1. multiple icons in a single column like the one you have in the migration status column (which I don't think it looks good anyway)

the improvements we need to make
1. 'check all' in the column header
2. context menu column type support
3. expose the icon with text column type through azdata API.

please discuss with your team and see how would you guys like to proceed.

**Comment by alanrenmsft** [comment] 2021-10-01 21:02
@brian-harris @aasimkhan30 any update? I am going to move this to next milestone

**Closed** 2022-02-08 01:00 UTC
Labels: Area - Extensibility, Enhancement, Triage: Done
