### ISSUE TITLE
Deployment from portal to launch ADS and into "Create data controller" wizard.. with values filled in

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#13927] opened 2021-01-07 18:20 UTC
The Azure Arc data controller deployment flow from portal builds the user experience with values that they typed in such as Azure subscription info etc. When the user clicks on "Launch ADS" at the end of the flow, we want to be able to drop the user into ADS > Wizard.

(1) detect whether ADS is already installed and if its not, fwd them over to ADS download page.. and (2) if its installed, check the extensions are installed and point the customer to download them if not installed.. and (2) if ADS is available, and appropriate extensions are installed then launch the Create Azure Arc data controller wizard and populate the values that the user already typed in the portal.

**Comment by Charles-Gagnon** [comment] 2021-01-07 18:28
@dnethi 1 isn't something we can really do in ADS (since if it's not installed how are we supposed to be able to do anything about it?)

Typically what I've seen done is that the portal would inform the user that they must have ADS installed and provide a link to download it if they don't.

For 2 that's a duplicate of https://github.com/microsoft/azuredatastudio/issues/11794

**Closed by Charles-Gagnon** 2021-01-07 18:28 UTC
