### ISSUE TITLE
Image links not rendering with whitespace preceding link

### ISSUE THREAD

**Issue by tobarnes** [microsoft/azuredatastudio#19548] opened 2022-05-26 21:58 UTC
Issue Type: <b>Bug</b>

Load the notebook in ADS.
Note that neither image link is rendering.
Delete the whitespace on the line before the link definition
Link is now rendered

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-devops-simplified-prs|ads|0.1.3
spellright|ban|3.0.52
adslivesite|Mic|0.0.57
cognitive-search-for-ads|Mic|1.0.2
kusto|Mic|0.5.4
powershell|ms-|2021.12.0
back-n-forth|nic|0.2.1

</details>
<!-- generated by issue reporter --
[bug.zip](https://github.com/microsoft/azuredatastudio/files/8782375/bug.zip)
>

**Comment by chlafreniere** [comment] 2022-06-01 22:07
Hi @tobarnes which notebook are you referring to (or has this been reported offline)?

**Comment by chlafreniere** [comment] 2022-06-18 18:39
Hi @tobarnes,

I took a look, but this appears to be by design. Here's what GitHub does:

First, I have no spaces before the image tag in markdown:
```
![msft logo](https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31)
```
![msft logo](https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31)

Below, we add four spaces before the image tag in markdown, e.g.
```
    ![msft logo](https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31)
```
    ![msft logo](https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31)

This results in the code block, which is what I see in the notebook.

Is this what you're referring to?

**Comment by chlafreniere** [comment] 2022-06-27 22:57
Hi @tobarnes if my previous understanding is correct, closing this issue as it is by design. If my understanding is not correct, please feel free to reopen. Thanks!

**Closed by chlafreniere** 2022-06-27 22:57 UTC
Labels: Bug, Area - Notebooks, Triage: Done, Subarea - MD Rendering
