### ISSUE TITLE
schema compare drops constraints on table if other changes are made to table

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#21378] opened 2022-12-07 23:29 UTC
Issue Type: <b>Bug</b>

option 1:
1. create a project from an adventureworks database
2. add 1 or more columns to the SalesLT.Customer table in the sql project
3. run schema compare from the database to the sql project
4. constraints are going to be removed from the sql project
5. using object explorer to script the table for the database still shows the constraints
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/12227241/206319377-e7f80b37-d65c-4a17-accd-5377befd14fe.png">

option 2:
1. create a project from an adventureworks database
2. add an index to the SalesLT.Customer table in the database
3. run schema compare from the database to the sql project
4. constraints are going to be removed from the sql project
5. using object explorer to script the table for the database still shows the constraints

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/12227241/206319289-95b55a22-372f-45a0-9480-c18bc337b2ed.png">

Extension version: 1.17.0
Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:22:25.529Z)
OS version: Darwin arm64 22.1.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment] 2022-12-22 23:43
SSDT doesn't have this problem, so this has to do with how the script is getting generated for ADS and it happens with both the sql project and the dacpac from that project.

When generating the script for applying the changes from project to db, only the alter table to add the column is in the script, nothing about dropping constraints, so looks like the problem is just with the script used for displaying in the compare, but not with the actual apply.

**Comment by rw152** [comment] 2023-04-20 13:49
I'm having this same issue. Has anyone come up with a work around in the mean time? 

Not sure if this is a separate issue, but I also can't generate scripts if comparing the database to my .sqlproj file (the option is grayed out), but if I switch and compare the .sqlproj to my database, the option becomes available again.

<img width="642" alt="Screenshot 2023-04-20 at 9 47 45 AM" src="https://user-images.githubusercontent.com/5873535/233386849-df5d2b0b-b276-49ae-afcc-2b0980fe4a76.png">

**Comment by rw152** [comment] 2023-04-21 19:18
> ... so looks like the problem is just with the script used for displaying in the compare, but not with the actual apply.

In my case, it definitely drops the Foreign Keys in the Schema project, unfortunately. And then when I recompare, oddly enough it tries to add them back to the Schema project.

**Comment by rw152** [comment] 2023-04-22 12:30
@kisantia is there a publicly available repo for the Schema Compare extension?

**Comment by kisantia** [comment] 2023-04-24 16:33
@rw152 the backend for schema compare uses DacFx, which is not available in a public repo and this is where the fix will need to be made for this bug.

For the generate script button being disabled when the target, this is by design. It's only enabled when the target is a database because a script can be run on the database to update it with the changes. This isn't applicable for when the target is a sql project or a dacpac.

**Comment by kisantia** [comment] 2023-05-03 23:42
@rw152 I moved this into the July milestone. I'm working on a fix now, but don't think it'll get in for the upcoming May release. Hoping it will be out in insiders in the next couple weeks and be included in the July release.

**Comment by rw152** [comment] 2023-05-03 23:50
Thank you for your work, @kisantia! I am looking forward to giving it a shot.

**Comment by snoa93** [comment] 2023-06-08 12:04
Looking forward to this release!

I have been testing out using Schema Compare in ADS over Schema Compare in Visual Studio Professional, but I ran into the issue described above. For those looking for a work-around, I can suggest using Visual Studio Professional (or Community if you are in open source projects) as it works fine there.

**Comment by kisantia** [comment] 2023-06-14 19:21
SSDT is not currently available on Visual Studio for Mac :(

Update on the fix status: The actual fix for dropping the constraints during publish has been checked in, but during testing found that the scripts displayed in schema compare were still showing the constraints as being dropped. I'm having to make a few more changes to update this, but expect to have this updated in insiders next week!

**Comment by snoa93** [comment] 2023-06-14 21:30
You could run Visual Studio with SSDT in a Windows VM on your Mac, but its not the ideal solution

**Comment by dzsquared** [comment] 2023-06-14 21:58
> You could run Visual Studio with SSDT in a Windows VM on your Mac, but its not the ideal solution

clarifying, if you install arm64 Visual Studio, SSDT is not available.

**Comment by snoa93** [comment] 2023-06-20 11:16
> > You could run Visual Studio with SSDT in a Windows VM on your Mac, but its not the ideal solution
> 
> clarifying, if you install arm64 Visual Studio, SSDT is not available.

Thanks for clarifying! 👍 

By default, the ARM version of Visual Studio 2022 will be installed. I installed the x64 version (instead of arm64) using the command line:

.\vs_professional.exe --arch x64

https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022

**Closed** 2023-06-27 21:56 UTC
Labels: Bug, Pri: 2, Area - Schema Compare, Triage: Done, Area - SQL Project, Size: M

**Comment by kisantia** [comment] 2023-06-28 20:47
This fix for this issue is now available in the [ADS Insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch)! Please give it a try and verify that this is fixed.
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/3dea5e78-a289-4d5b-8181-ff332a385a27)
