### ISSUE TITLE
Saved server connections sometimes confusing

### ISSUE THREAD

**Issue by pierobox** [microsoft/azuredatastudio#21229] opened 2022-11-15 09:46 UTC
Issue Type: <b>Bug</b>

I created two server connections to the same azure sql database, which only differ in their "profile" name and in the ApplicationIntent property (one has "ReadOnly", the other not, so it's readwrite)
I create a query from the R/O connection, and it works.
I then expand from the connections pane the R/W connection and it renames the R/O connection with the same name and properties of the R/W one.
At this point I have two identical connections on the pane, so I have to delete the duplicate connection and create again the R/O one, which is quite annoying... For some reason, it seems that the two are considered to be the same, so it probably updates both when connecting..

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (34.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment] 2022-11-16 23:37
Hi @pierobox 

This is a known design issue. Currently both Profile Name and Advanced options are not considered for connection differentiation. We hope to address this in future releases. 

Duplicate of https://github.com/microsoft/azuredatastudio/issues/17438

**Closed** 2022-11-16 23:40 UTC
Labels: Area - Connection, Triage: Done
