### ISSUE TITLE
Windows Authentication username defaults to terminal's prompt name for Mac

### ISSUE THREAD

**Issue by ellbosch** [microsoft/azuredatastudio#7077] opened 2019-09-05 17:30 UTC
Windows Authentication on Mac expects the username to be equal to the specified name on the Terminal prompt. Windows Authentication on Mac works when both the Terminal and SQL Server use the same username, but this should not be expected.

Steps to repro:
1. On Mac, clear cached Kerberos ticket by calling `kdestroy`
2. Ensure terminal on Mac uses a prompt name that's unequal to the needed username for Windows Authentication
3. Try to connect to SQL Server instance using Windows Authentication on Mac environment
4. Connection error should appear, click "Run kinit"
5. `kinit` attempts to create Kerberos ticket with incorrect username

Workaround:
1. In ADS's terminal, specify the correct username by calling `kinit [YOUR USERNAME]@[YOUR DOMAIN].com`
2. Enter password
3. Reconnect to SQL Server instance with Windows Authentication—should now work

At a minimum, if authentication initially fails, ADS should specify the user call `kinit` followed by their user account for Windows Authentication, rather than attempt to make assumptions for the user.

**Comment by ellbosch** [comment] 2019-09-05 17:39
As a follow-up, I created a feature request: #7079. This suggests enabling the username and password inputs in the New Connection form.

**Comment by kburtram** [comment] 2021-08-17 20:19
Closing as a duplicate of #112.  Which was the resolution for related issue #7079.  Thanks!

**Closed by kburtram** 2021-08-17 20:19 UTC
Labels: Bug, Area - Connection, Triage: Done
