### ISSUE TITLE
expandable rows in the properties table is not as clear as SSMS

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#18392] opened 2022-02-15 19:29 UTC
especially the numbers are misleading
in ADS
![image](https://user-images.githubusercontent.com/13777222/154134346-524e4638-f9cc-4b2d-afe1-3a77e8a24147.png)

in SSMS
![image](https://user-images.githubusercontent.com/13777222/154134538-e36141eb-3c48-40b0-903b-a681bf803c25.png)

**Comment by aasimkhan30** [comment] 2022-02-15 20:51
This is a duplicate of the #18357. Those properties are just present before the parent.

**Closed by aasimkhan30** 2022-02-15 20:51 UTC
Labels: Bug, Triage: Needed, Area - Execution Plan
