### ISSUE TITLE
"Open Changes" from Source Control causes ADS to crash with out of memory error

### ISSUE THREAD

**Issue by SQLGuyJPS** [microsoft/azuredatastudio#15453] opened 2021-05-13 14:26 UTC
Issue Type: <b>Bug</b>

I've noticed this issue just in the last few weeks.

### Steps to Reproduce

1. Open Source Control

2. Click on a file name to show changes, or right-click on a file name and select "Show changes" from the menu.

3. Nothing else happens for several seconds, then a pop-up messages appears saying the current window has become unresponsive and you can reopen or close the window or keep waiting. While the app is unresponsive, clicking on anything in the window has no effect. When the mouse pointer is hovering over the window, the pointer shape remains the same as what it was at step 2, e.g. standard arrow pointer or "hand" pointer, regardless of what part of the window it is hovering over.

4. After choosing "Keep waiting" a few times, a new pop-up appears saying, "The window has crashed (reason: 'oom'). We are sorry for the inconvenience! You can reopen the window to continue where you left off." 

### Logs

I checked the log files in ~\AppData\Roming\azuredatastudio\logs, and I found a log titled "renderer4.log" (attached) that shows several errors. The app appears to be looking for a folder named ".azuredatastudio" inside network folders that I have added to my workspace, but that folder doesn't exist in any of them. I'm not sure that's what caused the problem, though.
[renderer4.log](https://github.com/microsoft/azuredatastudio/files/6473367/renderer4.log)

Example: 

```
[2021-05-13 09:15:37.738] [renderer4] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'w:\Data Analytics\Power BI\Apps\.azuredatastudio'
[2021-05-13 09:15:37.738] [renderer4] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'w:\Data Analytics\Ad Hoc Requests\.azuredatastudio'
[2021-05-13 09:15:37.738] [renderer4] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'w:\Data Analytics\Measure Specs and SQLs\.azuredatastudio'
[2021-05-13 09:15:37.738] [renderer4] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'h:\SQL dump\.azuredatastudio'
[2021-05-13 09:15:37.738] [renderer4] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'w:\Data Analytics\Transition\SQL\.azuredatastudio'
[2021-05-13 09:15:39.362] [renderer4] [error] Failed opening file c:\Users\jmanning\AppData\Roaming\azuredatastudio\logs\20210513T091245\exthost4\exthost.log for writing: Permission denied: Error: Failed opening file c:\Users\jmanning\AppData\Roaming\azuredatastudio\logs\20210513T091245\exthost4\exthost.log for writing: Permission denied
    at createRotatingLogger (c:\Users\jmanning\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\spdlog\index.js:34:9)
    at c:\Users\jmanning\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\spdlog\index.js:27:7
    at c:\Users\jmanning\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\mkdirp\index.js:48:26
    at FSReqCallback.oncomplete (fs.js:159:5)
```

The extension 'vscode.git' generated an unresponsive warning with its own log, "exthost-c10988.cpuprofile", which I have also attached.

> [2021-05-13 09:13:58.674] [renderer4] [warning] UNRESPONSIVE extension host, 'vscode.git' took 100% of 5263.194ms, saved PROFILE here: 'c:\Users\jmanning\AppData\Local\Temp\exthost-c10988.cpuprofile' [{"id":"gc","total":3379,"percentage":0},{"id":"program","total":105,"percentage":0},{"id":"self","total":7668,"percentage":0},{"id":"vscode.git","total":5251804,"percentage":100}] 

[exthost-c10988.txt](https://github.com/microsoft/azuredatastudio/files/6473154/exthost-c10988.txt)

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
import|Mic|1.3.0
query-history|Mic|0.1.0
azdata-sanddance|msr|3.1.0
sql-search|Red|0.4.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment] 2021-05-13 15:54
Duplicate of #15180 - see that issue for instructions to revert to a working version until a build with the fix is released.

**Closed by Charles-Gagnon** 2021-05-13 15:54 UTC

**Comment by SQLGuyJPS** [comment] 2021-05-13 16:04
Thank you!
