### ISSUE TITLE
Compare feature: Settings and changes Select/ deselect all

### ISSUE THREAD

**Issue by pavants** [microsoft/azuredatastudio#24242] opened 2023-08-29 12:01 UTC
Should be useful to have in compare Result, column "include" a function to select/deselect all the rows

In Options>Schema Compare Options - General Options and Include Object Types should be useful to have same button/selector to select all/nothing.

![image](https://github.com/microsoft/azuredatastudio/assets/12910135/40d12df9-16e5-4a4f-a7f5-e65752632d8f)

![image](https://github.com/microsoft/azuredatastudio/assets/12910135/c44fe6d2-ea83-4b89-a372-6878548b8e3c)

**Comment by kisantia** [comment] 2023-08-29 17:50
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/10430

**Closed by kisantia** 2023-08-29 17:50 UTC
Labels: Enhancement, Area - Schema Compare
