### ISSUE TITLE
Kerberos no longer working under 1.25

### ISSUE THREAD

**Issue by sterlingpetersen** [microsoft/azuredatastudio#13754] opened 2020-12-10 17:52 UTC
Issue Type: <b>Bug</b>

Authentication using Kerberos isn't working. It works under version 1.24 but not version 1.25. Just keep getting the prompt to run `kinit`, which isn't needed as a ticket is already in place.

Thanks!

Azure Data Studio version: azuredatastudio 1.25.0 (8c6bd8c857592c14afbb589a7d307baec1f5b5ed, 2020-12-05T06:43:11.244Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7
azdata-sanddance|msr|3.1.0

</details>

**Comment by Charles-Gagnon** [comment] 2020-12-10 18:06
Duplicate of https://github.com/microsoft/azuredatastudio/issues/13751

**Closed by Charles-Gagnon** 2020-12-10 18:06 UTC
Labels: Area - Connection, Bug, Triage: Needed
