### ISSUE TITLE
Connection dialog - issue with scrollbar for the connection tree

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#3101] opened 2018-11-02 18:06 UTC
- Azure Data Studio Version:
at least starting from 1.0.0

Steps to Reproduce:
first make sure you have a few connections in both recent connections and saved connections

1. Open ADS and reduce its height so that the connection list will need to scroll
2. Open connection dialog and you will see the saved connection list can be scrolled
3. Now maximize the window

Expected:
all the connections can be displayed without scrollbar.

Actual:
the connection list doesn't expand as the window size changed and the scroll bar is still there.

**Comment by kburtram** [comment] 2021-08-16 19:47
This appears to be fixed in current builds.  Please reactive if the issue is still impacting you.

**Closed by kburtram** 2021-08-16 19:47 UTC
Labels: Bug, Area - Connection
