### ISSUE TITLE
It isn't possible to modify connection information for a server

### ISSUE THREAD

**Issue by bkline** [microsoft/azuredatastudio#6915] opened 2019-08-23 19:33 UTC
- Azure Data Studio Version: 1.10 (Windows and Mac)

Steps to Reproduce:

1. Create a server connection
2. Receive memo that the connection port has changed
3. Attempt to edit the connection information

**Comment by Charles-Gagnon** [comment] 2019-08-23 20:53
Thanks for the suggestion - I'm going to close this as a dupe of #5158 so follow that one for any updates in this area!

**Closed by Charles-Gagnon** 2019-08-23 20:53 UTC
Labels: Bug
