### ISSUE TITLE
Mac SQL Server Flat File Import Error

### ISSUE THREAD

**Issue by NI296920** [microsoft/azuredatastudio#25287] opened 2024-02-02 06:13 UTC
Type: <b>Bug</b>

Failed to start Flat File Import Service

Extension version: 1.6.0
Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T00:30:19.136Z)
OS version: Darwin arm64 23.3.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|36.00GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by NI296920** [comment] 2024-02-03 05:47
> Type: Bug
> 
> Failed to start Flat File Import Service
> 
> Extension version: 1.6.0 Azure Data Studio version: azuredatastudio 1.47.1 ([b6f7beb](https://github.com/microsoft/azuredatastudio/commit/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e), 2024-01-10T00:30:19.136Z) OS version: Darwin arm64 23.3.0 Restricted Mode: No Preview Features: Enabled Modes:
> 
> System Info
> Item	Value
> CPUs	Apple M3 Max (14 x 24)
> GPU Status	2d_canvas: enabled
> canvas_oop_rasterization: enabled_on
> direct_rendering_display_compositor: disabled_off_ok
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> opengl: enabled_on
> rasterization: enabled
> raw_draw: disabled_off_ok
> video_decode: enabled
> video_encode: enabled
> vulkan: disabled_off
> webgl: enabled
> webgl2: enabled
> webgpu: enabled
> Load (avg)	4, 3, 3
> Memory (System)	36.00GB (0.50GB free)
> Process Argv	
> Screen Reader	no
> VM	0%

**Comment by kisantia** [comment] 2024-02-05 22:42
Could be related to #25205. Can you check the output pane and see if there were any errors when downloading the Flat File Import Service? It should look like this for a successful download: 
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/9bb37deb-2591-41a0-be5a-68368cab04ad)

**Comment by kburtram** [comment] 2024-08-16 19:21
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/25779

**Closed by kburtram** 2024-08-16 19:21 UTC
Labels: Bug, Needs More Info, Area - SQL Import, Triage: Done
