### ISSUE TITLE
Search not working in the Explorer tab.

### ISSUE THREAD

**Issue by hjpinndx** [microsoft/azuredatastudio#23242] opened 2023-05-30 08:26 UTC
Type: <b>Bug</b>

Before the latest update, when I typed while focussed in the Explorer, I could search the document file names to find a file easier. This is no longer working.

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.24GB (14.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment] 2023-05-30 16:02
@hjpinndx the File Explorer component is picked-up from upstream VS Code source code and we try to maintain feature parity with that unless there is a specific customization needed to optimize the data management experience.  The 1.44 release brought in a few months of VS Code changes that updated this scenario.

I wasn't able to notice any difference between the current ADS behavior and current VS Code behavior for this particular use-case.  Please let me know if I'm misunderstanding the issue.  Otherwise, please open an issue for VS Code with the suggested change and we'll pick it up in a future source code refresh.  Thanks!

**Comment by Charles-Gagnon** [comment] 2023-05-30 16:26
@hjpinndx If you press ctrl+f when on the tree then the search widget should appear. This was a change VS Code did a while back (you used to be able to filter just by typing when focus was on the tree).

**Comment by kburtram** [comment] 2023-05-31 06:05
Closing as "by design" based on changes in upstream behavior in this scenario.  Please let us know if you are seeing any difference between ADS and VS Code in this scenario.  Thanks for opening this issue.

**Closed by kburtram** 2023-05-31 06:05 UTC
Labels: Bug, Area - Shell, Triage: Done, Size: S

**Comment by hjpinndx** [comment] 2023-05-31 07:25
@kburtram, thanks for the feedback. ctrl+f does the trick!
