### ISSUE TITLE
Notebooks with parameters in Kernel SQK

### ISSUE THREAD

**Issue by hajerty** [microsoft/azuredatastudio#19811] opened 2022-06-23 14:37 UTC
**Is your feature request related to a problem? Please describe.**
The executions of a notebook with parameters is not allowed for SQL Kernel. 

**Describe the solution or feature you'd like**
Enable the execution with parameters as for others kernel https://docs.microsoft.com/it-it/sql/azure-data-studio/notebooks/run-with-parameters?view=sql-server-ver16

**Comment by Charles-Gagnon** [comment] 2022-06-23 17:21
Duplicate of https://github.com/microsoft/azuredatastudio/issues/18709 @chlafreniere @VasuBhog

**Closed by Charles-Gagnon** 2022-06-23 17:21 UTC
