### ISSUE TITLE
Duplicate Grid Result

### ISSUE THREAD

**Issue by nilact** [Microsoft/azuredatastudio#3962] opened 2019-02-07 08:41 UTC
Issue Type: <b>Bug</b>

While executing any query, sometimes it shows the duplicate Grid in the result tab for the same Query.

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 6.1.7601

**Edit:** I found an issue already reported [here](https://github.com/Microsoft/azuredatastudio/issues/3759)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.67GB free)|
|Process Argv|C:\Users\nileshthak\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment] 2019-02-12 20:00
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/3759.  The fix will be in the Feb release planned for this week.

**Closed by kburtram** 2019-02-12 20:00 UTC
