### ISSUE TITLE
New Database focus starts on "Cancel" button

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23821] opened 2023-07-12 19:51 UTC
After opening the "New Database" dialog the focus is initially on the cancel button. It should start in the name field to make it easier to use, otherwise users using keyboard navigation have to press tab to be able to enter information.

**Comment by corivera** [comment] 2023-07-12 22:16
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/23644

**Closed by corivera** 2023-07-12 22:16 UTC
Labels: Bug, Triage: Needed, Area - Basic Admin
