### ISSUE TITLE
Wrong Intellisense / Missing SQL Keywords

### ISSUE THREAD

**Issue by aersamkull** [microsoft/azuredatastudio#15893] opened 2021-06-24 13:51 UTC
Issue Type: <b>Bug</b>

There are some SQL Keywords/Syntaxes not supported (gets red on writing): CREATE OR ALTER PROCEDURE / OPENJSON 

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (20.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
datavirtualization|Mic|1.12.0
import|Mic|1.3.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.10.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-06-24 14:07
1. Please update to ADS >=1.30, there was a fix there for the language service that fixes a number of issues people were seeing
2. If you still see issues, please provide the query you're using and what type of server you're connected to

**Comment by kburtram** [comment] 2021-08-19 00:34
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/13518.  `OPENJSON` appears fine on the current build.

![image](https://user-images.githubusercontent.com/599935/129989421-7947121d-8afa-4704-821d-36901f8a216d.png)

**Closed by kburtram** 2021-08-19 00:34 UTC
Labels: Bug, Area - Language Service, Triage: Needed
