### ISSUE TITLE
Error on BDC Deployment page allows moving to next page

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7855] opened 2019-10-21 15:24 UTC
Latest master

Got an error on the first page of the deployment wizard, but as you can see from the screenshot the **Next** button is enabled and clickable.

![image](https://user-images.githubusercontent.com/28519865/67219020-32136f80-f3dc-11e9-9980-3d98cb382464.png)

Clicking on it does correctly display the error message `Please select a deployment profile.` and not actually move to the next page, but the button should be disabled until a valid profile is chosen.

**Comment by kevchant** [comment] 2019-10-21 17:37
Has the BDC wizard being removed in the latest version, as just updated the Insider build and it now appears to be gone?

**Comment by Charles-Gagnon** [comment] 2019-10-21 17:45
@kevchant - Apologies for that - it was accidentally removed as being a built-in extension from the latest insiders. That'll be fixed for tomorrow but in the meantime you can download and install the VSIX manually from here :

https://sqlopsextensions.blob.core.windows.net/extensions/resource-deployment/resource-deployment-0.0.1.vsix

**Comment by kevchant** [comment] 2019-10-21 17:48
Thanks, was just singing it's praises in a blog post so will be good to have it back...

**Comment by alanrenmsft** [comment] 2019-10-21 18:24
@Charles-Gagnon  we have 2 different ways of handling the the navigation  validation:
1. disable the Next button - this is how we handle the required input fields
2. show the error message when user tries to move to next page  - profile selection page, cluster settings page as well as service settings page

I personally think it is better to use mixed mode just like the way it is now. it is obvious if the user hasn't filled out all the required fields, but for other validations it would be hard if we disable the Next button. It seems better to me to let user click on next and then tell them what is wrong.

**Comment by Charles-Gagnon** [comment] 2019-10-21 18:41
I'm not sure I agree, especially with it being mixed it's confusing when sometimes I can click next and sometimes I can't. I found myself repeatedly clicking next only to have it warn me I was missing something I didn't see and having breaking my flow. 

But I'll defer to your implementation if you think that's the correct way. I assume you've ran this by design?

**Comment by alanrenmsft** [comment] 2019-10-21 21:21
for the validations other than the required validation, we have to show the error messages otherwise there is no way user can tell why the next button is disabled. 2 options: 
1. show the error when Next is clicked
2. show the error when inputs are changed, this could be annoying when the user are still working on it.

I am going to close this as by design and revisit this if users are complaining about this.

**Closed by alanrenmsft** 2019-10-21 21:21 UTC
Labels: Area - Resource Deployment, Enhancement, Triage: Done
