### ISSUE TITLE
Unable to install Azure Data Studio on MacOs Catalina

### ISSUE THREAD

**Issue by yomiBazuaye** [microsoft/azuredatastudio#8916] opened 2020-01-20 11:05 UTC
- Azure Data Studio Version:
1.14.1
Mac OS version: 10.15.2, Catalina

Steps to Reproduce:
Download the binary from here: 
https://docs.microsoft.com/en-gb/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15

When installing the binary the attached error appears:

![image](https://user-images.githubusercontent.com/6269982/72721713-fde75080-3b7c-11ea-84cb-8db24db48963.png)

**Comment by Charles-Gagnon** [comment] 2020-01-21 17:58
Closing this as a dupe of #7747

Open System Preferences -> Security -> General and then try to re-open Azure Data Studio. You should see a security check pop up regarding Azure Data Studio and prompts you if you'd still like to open it. Select "Open Anyway" to grant permission, and now you may open the app. You should only need to do this once.

We're working on fixing this, but hopefully the steps above will unblock you. Please let us know if you run into any other problems.

**Closed by Charles-Gagnon** 2020-01-21 17:58 UTC
Labels: Bug, Triage: Needed

**Comment by pvenzke** [comment] 2020-01-21 20:29
Hello, @Charles-Gagnon 

I followed the steps above, but had the same result.  Is it possible that there is an additional step needed after opening the Security preferences on my computer?  The only thing I could see that might impact was an option to restrict non-Apple developer resources, but that was not selected at the time.

Thanks.

**Comment by Charles-Gagnon** [comment] 2020-01-21 21:15
Try running this command 

`xattr -d com.apple.quarantine <app-path>`

You should also be able to right click on the icon and select `Open` from there to bypass the check.

**Comment by pvenzke** [comment] 2020-01-21 21:20
I was unsuccessful with right click, and I am not familiar with how to run the command line.  I found the Terminal app, but I believe I need something in the <app-path> section to make that work.  Not sure how to point to something that isn't installed.

**Comment by Charles-Gagnon** [comment] 2020-01-21 21:25
First right click on the icon and select `Open in Finder`

Then find the ADS icon again and press the command key then right click to bring up the context menu - that should have an option to `Copy "Azure Data Studio" as Path Name`. Do that and then paste that value in the terminal in place of `<app-path>`

**Comment by pvenzke** [comment] 2020-01-22 00:12
I really must be missing something here.  This is the response I get in Terminal:

Pats-MacBook-Pro:~ patvenzke$ xattr -d com.apple.quarantine /Users/patvenzke/Desktop/Azure Data Studio.app
xattr: No such file: /Users/patvenzke/Desktop/Azure
xattr: No such file: Data
xattr: No such file: Studio.app

**Comment by pvenzke** [comment] 2020-01-22 00:24
Hi, Charles:

Disregard.  I have access now.  Thank you for all your assistance.
