### ISSUE TITLE
Import data from excel or data source

### ISSUE THREAD

**Issue by abdullah-abunada** [microsoft/azuredatastudio#1871] opened 2018-07-08 12:36 UTC
Please Add import from data source feature.

**Comment by dirq** [comment] 2021-08-20 15:23
My God, every MS database product (SSMS and Data Studio) should have a super awesome Excel Import Wizard. They are both MS products!  And it's been YEARS.  Free MySQL Workbench can do so much more.  Most data starts out in spreadsheets and not having a good import mechanism is completely ridiculous. dbForge sucks too.

**Comment by yzorg** [comment] 2022-08-10 17:43
Please prioritize Excel (*.xlsx) over other data sources.  The file format has been openly documented since 2007.  Any design or usability justification for supporting xlsx for export but not import?

**Comment by aasimkhan30** [comment] 2022-12-08 22:03
Duplicate of #1871

**Closed by aasimkhan30** 2022-12-08 22:03 UTC
Labels: Area - SQL Import, Enhancement, Triage: Done

**Comment by dirq** [comment] 2022-12-09 22:42
Wait.  You closed this?
