### ISSUE TITLE
Connections on connections panel now go to server root instead of selected database

### ISSUE THREAD

**Issue by Ravatsaas** [microsoft/azuredatastudio#6394] opened 2019-07-17 15:28 UTC
The behavior of connections on the connections have changed since upgrading to ADS 1.9.0.

Previously they would take you directly to the chosen database. In the new version they take you to the root node of the server. This is a lot less useful. To get to where I want to go I need to expand Databases, scroll through a long list of databases on the server and select the one I want. Since we pack a ridiculous amount of databases on the same server this is a very cluttered user experience. 

**Steps to Reproduce:**

1. Add a new connection, selecting a server and database.
2. Expand the new connection node.

Result:
```
▼ myServer, myDatabase (Windows Authentication)
   ▼ Databases
      ► System Databases
      ► _IDE_0910
      ► AdventureWorks2012
      ► SomeOtherTeamsDatabase
      ► TestDbWeForgotToDeleteOnce
      ► AnotherDatabaseIDontWant
      ► IDontEvenKnowWhatThisOneDoes
      ▼ myDatabase
           ► Tables
           ► Views
           ► Synonyms
           ► Programmability
           ► Etc ...
      ► ThisOneIActuallyLookAtSometimes
      ► ... (and about a hundred more)
   ► Security
   ► Server Objects
```

Expected result:
```
▼ myServer, myDatabase (Windows Authentication)
   ► Tables
   ► Views
   ► Synonyms
   ► Programmability
   ► Etc ...
```

**Comment by Charles-Gagnon** [comment] 2019-07-17 15:59
This was an intended change since we had users who were confused by the nodes being at different levels without any indication of what was different between the connections.

We had discussed making this a configurable option too - which we may do if there's enough negative feedback to reverting to using server level connections for everything. 

So for now we considering this working as intended but I'll leave this issue open - if anyone else dislikes this change please use the 👍 reaction on the original issue and we'll use that as a gauge for how impactful this change was when triaging issues for our upcoming releases.

**Comment by evandouglas** [comment] 2019-07-22 17:26
I agree with Ravatsaas. The connection string displays "ServerRoot, DatabaseName", which seems enough to indicate the difference between the connections. Compare that to now, where we have multiple connections with different database names in the connection string, but they all point to the server root. 
In my opinion, the current state seems more confusing than previous.

**Comment by MikeMKH** [comment] 2019-07-22 18:00
Agree with @Ravatsaas and @evandouglas, this change seems confusing and does not respect the database give in the set up of the connection string.

**Comment by AisoRed** [comment] 2019-07-26 15:18
All of my connections that were previously pointed to a single database are now pointless. This was a very frustrating change to upgrade too. At a minimum, I would like to see this as an option to turn on in the settings. Thanks for your consideration @Charles-Gagnon.

**Comment by Charles-Gagnon** [comment] 2019-07-26 20:49
Thanks for the feedback everyone! I have a PR out now that will revert this change so you should see that in the next stable release of ADS (or in the insiders build after the change goes through).

**Comment by kburtram** [comment] 2021-08-17 19:37
This was fixed by PR mentioned above.  The connections are working as expected on the current build.

**Closed by kburtram** 2021-08-17 19:37 UTC
Labels: Bug, Area - Connection, Triage: Done
