### ISSUE TITLE
"disconnected" after "go to definition"

### ISSUE THREAD

**Issue by rami-fmj** [microsoft/azuredatastudio#8590] opened 2019-12-06 19:03 UTC
Issue Type: <b>Bug</b>

When you select "go to definition" of a view or store procedure (SQL Server) you appear as disconnected, and you have to reconnect in order to work. It would be good to be connected to the same connection of the original view or procedure.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (2.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2019-12-09 23:07
Thanks for the feedback! I'm closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/6298 - you can track that one for status updates.

**Closed by Charles-Gagnon** 2019-12-09 23:07 UTC
Labels: Bug, Triage: Needed
