### ISSUE TITLE
Always be able to open sql result cells with JSON easily

### ISSUE THREAD

**Issue by o-o00o-o** [microsoft/azuredatastudio#19231] opened 2022-04-27 14:36 UTC
Issue Type: <b>Bug</b>

Through trial and error it seems that the ability to click on a cell with json contents and have it helpfully open in a seperate page is not intuitive or consistent.

I am using sql based jupyter notebooks but the same behaviour appears in a simple sql query in ADS

I have a table with an nvarchar(max) column that has json contents (or null)

If I return just a single row with json in, I can click the cell and it opens nicely

However if I return multiple rows where the first row is null, I can't

Please can you fix this behaviour by evaluating the first non-null cell instead of just the first row so this always works consistently for the same query regardless of whether the first row returns null or an xml document?

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
kusto|Mic|0.5.4
powershell|ms-|2021.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.13.1
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.16.1
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.3.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by chlafreniere** [comment] 2022-04-27 23:26
@alanrenmsft we don't have a grid area path, do we?

**Comment by alanrenmsft** [comment] 2022-04-27 23:42
@chlafreniere  this query editor path works. closing since this is a dupe of #17634

**Closed by alanrenmsft** 2022-04-27 23:42 UTC
Labels: Bug, Area - Query Editor, Triage: Needed
