### ISSUE TITLE
Connections - no way to rearrange within a group

### ISSUE THREAD

**Issue by LarsFosdal** [microsoft/azuredatastudio#13698] opened 2020-12-07 16:18 UTC
Issue Type: <b>Bug</b>

Let's say you have a server group:
- Prod

You start adding connections, and they appear in the order you create them.
Eventually you have so many connections that you would like to sort or rearrange them.  Dragging within the server group does not work.  How can you rearrange them?

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (12.62GB free)|
|Process Argv|-S 10.227.16.14\INDUSTRIELL -D PSD106Test -U root -aad -r|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0
azdata-sanddance|msr|3.1.0

</details>

**Comment by kburtram** [comment] 2020-12-07 19:03
@LarsFosdal this is a feature gap we need to fill.  In the meantime, the workaround is to (1) open the Settings JSON file from the Command Palette (2) rearrange the connection metadata in the JSON file.  The display order in the tree should match the order of the connections listed in the settings file.

**Comment by LarsFosdal** [comment] 2020-12-08 07:23
@kburtram Looking forward to having those gaps filled, but in the meanwhile, editing the JSON file will work. Thank you for the tip!

**Comment by abist** [comment] 2021-04-23 20:46
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/167

**Closed by abist** 2021-04-23 20:46 UTC
Labels: Area - Connection, Enhancement, Triage: Done
