### ISSUE TITLE
Icon for Mac OS

### ISSUE THREAD

**Issue by vitaha123** [microsoft/azuredatastudio#14125] opened 2021-02-01 07:40 UTC
Issue Type: <b>Bug</b>

The Azure Data Studio icon is not symmetrical. It stands out from the general appearance of Microsoft and Mac OS icons.
<a href="http://piccy.info/view3/14185094/46667d6d372c1d523b890c2c3b3b1f12/orig/" target="_blank"><img src="http://i.piccy.info/i9/75a0ba7f9db81ff90636950dd2158f89/1612164743/27265/1415897/Snymok_ekrana_2021_02_01_v_09_33_31_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2021-02-01-07-32/i9-14185094/800x135-r" target="_blank"><img src="http://i.piccy.info/a3/2021-02-01-07-32/i9-14185094/800x135-r/i.gif" alt="" border="0" /></a>

Azure Data Studio version: azuredatastudio 1.25.2 (4d4917d328ab7a7526817a0f0ef03237a79aa54d, 2021-01-20T22:47:41.882Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2021-02-01 18:20
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/14125

By "symmetrical" do you mean that it extends above and below the other icons?

**Closed by Charles-Gagnon** 2021-02-01 18:20 UTC
