### ISSUE TITLE
Schema compare - filter Database schemas 

### ISSUE THREAD

**Issue by dp33Fr** [microsoft/azuredatastudio#22750] opened 2023-04-16 11:55 UTC
**Is your feature request related to a problem? 
N/A 

**Describe the solution or feature you'd like**
Add a drop down filter field to filter SQL Database schemas. Azure Synapse dedicated SQL pool can contains a lot of schemas. Schema compare is too slow to compare all tables, views… 
With a schema option filter, we could just compare one or more specifics schemas. 

**Describe alternatives you've considered**

**Additional context**

**Comment by kisantia** [comment] 2023-04-17 17:47
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/12964

**Closed by kisantia** 2023-04-17 17:47 UTC
Labels: Enhancement, Area - Schema Compare, Triage: Done
