### ISSUE TITLE
Release Notes are broken

### ISSUE THREAD

**Issue by joserocha** [Microsoft/azuredatastudio#5121] opened 2019-04-19 00:42 UTC
Issue Type: <b>Bug</b>

The 'Show Release Notes' command are broke, showing the correct version with updates from september 2016.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2019-04-19 00:48
Thanks for the report! I'm closing this as a dupe of #5105  though - you can follow that for status updates.

**Closed by Charles-Gagnon** 2019-04-19 00:48 UTC
