### ISSUE TITLE
Save query results to a file or by copying leads to bad or missing data

### ISSUE THREAD

**Issue by peterrow** [microsoft/azuredatastudio#8288] opened 2019-11-10 17:20 UTC
Issue Type: <b>Bug</b>

Issue 1:
- Run a query or stored procedure that returns multiple resultsets, each with no more than 10 columns
- Click button on the right of the results pane to save to Excel
- Open in Excel
- PROBLEM: Only the 1st result set has been saved.
- ASSERTION: Save each result set to a new sheet within the same file.

Issue 2:
- Run a query that returns a result set with several columns (9 in my case) with a few rows (16 in my case)
- Click in one of the cells of the resultset, press Ctrl-A to select all data.
- Right click on the results grid and chose the "Copy with headers" option.
- Open Excel, click cell A1, press Ctrl-V to paste the data.
- PROBLEM: The header row is first but then the rows of data are in a some form of random order rather than the order they appeared in the resultset in Azure Data Studio.
- FURTHER INFO: Performing the same actions in SQL Server Management Studio and the header and rows of data paste into Excel in the order as they appear in the result set, thus it's a bug in Azure Data Studio

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
import|Mic|0.12.0
profiler|Mic|0.9.0

</details>

**Comment by oappelt** [comment] 2019-11-11 13:43
Same/similar thing happened to me.
Resultset with 18 columns and 23 rows.
click on cell -> "select all" (or click upper left grid corner) "copy with headers"
After pasting into Excel, not only were the rows jumbled - but also the column values got shuffled around.

Pretty sure this problem is new in 1.13.

> Version: 1.13.0
> Commit: cacd481bff25c890e4130aee392569bae43b7e60
> Date: 2019-11-01T23:20:53.295Z
> VS Code: 1.38.0
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Linux x64 4.15.0-64-generic

**Comment by Charles-Gagnon** [comment] 2019-11-11 16:17
1 I'm closing as a duplicate of #4399. We currently don't support saving multiple result sets to the same file.

2 is a duplicate of #8210

This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release. Sorry about the inconvenience!

**Closed by Charles-Gagnon** 2019-11-11 16:17 UTC

**Comment by peterrow** [comment] 2019-11-11 18:27
> 1 I'm closing as a duplicate of #4399. We currently don't support saving multiple result sets to the same file.
> 
> 2 is a duplicate of #8210
> 
> This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release. Sorry about the inconvenience!

We know you don't support saving multiple result sets but the fact that you have at least 2 issues now asking about it and both suggesting a fairly obvious and simple way it could be done seems like you should add it to your backlog.
