### ISSUE TITLE
ADS should not start after an unattended setup

### ISSUE THREAD

**Issue by Matteo-T** [Microsoft/azuredatastudio#4797] opened 2019-04-02 12:47 UTC
Azure Data Studio Version: latest

Steps to Reproduce:
1. Run: AzureDataStudioUserSetup.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /LOG=%TEMP%\ADS.log /NORESTART

Result:
ADS is automatically started

Expected:
ADS should not start by itself

**Comment by kburtram** [comment] 2019-04-02 19:02
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/549.  The current behavior is needed for auto-update to work correctly.  We'll need to look at how to support other acquisition scenarios.

**Closed by kburtram** 2019-04-02 19:02 UTC
Labels: acquisition, feature request
