### ISSUE TITLE
Running a query twice crashed

### ISSUE THREAD

**Issue by csi-lund** [microsoft/azuredatastudio#15891] opened 2021-06-24 07:26 UTC
Issue Type: <b>Bug</b>

Take a normal query run it,
its runs successfully 
run again immediately afer, runs and hangs

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19042

`[Error - 09:42:07] Request edit/dispose failed.
  Message: Edit data session not found
  Code: 0 
[Error - 09:46:24] Request query/subset failed.
  Message: Unhandled exception while handling request method query/subset: "list index out of range"
  Code: -32603 
[Error - 09:46:38] Request query/subset failed.
  Message: Unhandled exception while handling request method query/subset: "list index out of range"
  Code: -32603 
`

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by chlafreniere** [comment] 2021-06-25 02:18
@csi-lund are you running a query against a postgres database?

**Comment by csi-lund** [comment] 2021-06-26 18:18
Yes tats correct

**Comment by alanrenmsft** [comment] 2021-07-08 18:34
@csi-lund not able to reproduce the issue, are you still seeing it?

**Comment by csi-lund** [comment] 2021-07-14 14:30
No, can't seem to reproduce it so must have been something immediately after the install. Probably not worth investigating further

**Comment by chlafreniere** [comment] 2021-07-14 16:59
Thanks folks. Closing this for now; feel free to reopen it if it surfaces again.

**Closed by chlafreniere** 2021-07-14 16:59 UTC
Labels: Area - Query Editor, Bug, Triage: Needed
