### ISSUE TITLE
Can add filters when comparing databases such as object schema

### ISSUE THREAD

**Issue by fmartinezf74** [microsoft/azuredatastudio#18179] opened 2022-01-27 21:34 UTC
Can add a filter section when compare?
When database have to many objects, and i only wants to compare some objects using schema. Not always wants compare al database objects. 
For example, i have serveral schemas y i only wants compare Kaysch stored procedures or just tables changes

The feature a like can add its a filters, in the options section, a tab with filters like schema, maybe filter by date was created or changed 
Thanks for advance.

**Comment by kisantia** [comment] 2022-02-03 21:25
Have you tried only keeping the wanted object types to compare selected in the options dialog? You can specify which objects to include in the comparison in the "Include Object Types" tab.

**Comment by fmartinezf74** [comment] 2022-02-03 21:54
> Have you tried only keeping the wanted object types to compare selected in the options dialog? You can specify which objects to include in the comparison in the "Include Object Types" tab.

Hello, yes, I already applied the filter in the object types dialog by stored procedure, but even so there are too many stored procedures of different schemas, and I want to pre-filter by the name of a schema.
In addition, all the objects appear preselected and it is very slow to deselect all the objects that I do not want.
Thank you so much.

**Comment by kisantia** [comment] 2022-02-03 22:09
closing as duplicate of #12964. Please thumbs up this other issue to help track the interest in this feature. Thanks!

**Closed by kisantia** 2022-02-03 22:09 UTC
Labels: Enhancement, Area - Schema Compare
