### ISSUE TITLE
SQL connection toolbar disappears when saving new .sql file or opening an existing .sql file

### ISSUE THREAD

**Issue by jesman3** [microsoft/azuredatastudio#16441] opened 2021-07-26 17:14 UTC
I just updated to 1.31 today and now when I start a new query from the Connections pane I can write and execute queries but as soon as I save the query file the connection toolbar in the editor window disappears and I can no longer execute the query. If I open any saved .sql files the connection toolbar does not appear and I cannot execute the opened query either. Please notice the Run, Cancel, Disconnect, Change Connection and DB drop down near the top of the screenshot that is missing from the second screen shot.
![New Query window before save](https://user-images.githubusercontent.com/12089698/127030783-4960407c-056b-42b4-bdaf-f83df7ea5beb.PNG)
![New Query window after save](https://user-images.githubusercontent.com/12089698/127030799-256690b9-281c-4939-8b5d-acb9080590a8.PNG)

**Comment by Charles-Gagnon** [comment] 2021-07-26 18:32
Duplicate of https://github.com/microsoft/azuredatastudio/issues/16436 - could you reply in that issue with the things I asked for there? (mostly - does this happen in subsequent launches of ADS after closing the files?)

**Closed by Charles-Gagnon** 2021-07-26 18:32 UTC
