### ISSUE TITLE
Light theme icon path is shared with Dark theme

### ISSUE THREAD

**Issue by geleems** [microsoft/azuredatastudio#6365] opened 2019-07-12 01:56 UTC
Light theme icon path is shared with Dark theme.

https://github.com/microsoft/azuredatastudio/blob/6606be998b58711a27cf70d9d75dac9f3992c71b/extensions/cms/src/cmsResource/tree/registeredServerTreeNode.ts#L59-L62

**Comment by abist** [comment] 2019-07-12 18:59
This is intentional and not a bug. We use the same icon for both themes. Closing this issue for now.

**Closed by abist** 2019-07-12 18:59 UTC
Labels: Bug

**Comment by Charles-Gagnon** [comment] 2019-07-12 20:31
@abist 
Why is this being intentional not a bug? This should be fixed in order to comply with accessibility requirements - have you reached out to design to see about getting a proper dark themed icon?

**Comment by abist** [comment] 2019-07-12 21:04
We had this discussion before as well. UX suggested me to take the icons from SSMS and SSMS doesn't have theme aware icons. Also, the icons look fine in both themes. If you disagree with the UX, feel free to reopen the issue and maybe ask the UX team about it.
