### ISSUE TITLE
No file corresponding to the given URI

### ISSUE THREAD

**Issue by iaclarke** [microsoft/azuredatastudio#7201] opened 2019-09-13 20:11 UTC
Issue Type: <b>Bug</b>

Executing selected/highlighted queries (any queries) from a saved file against Azure Database for PostgreSQL returns the following error. The same queries can be copy and pasted into a new query tab and run successfully.

Execution failed due to an unexpected error: 
Unhandled exception while handling request method query/executeDocumentSelection: "No file corresponding to the given URI"

Request query/executeDocumentSelection failed.
  Message: Unhandled exception while handling request method query/executeDocumentSelection: "No file corresponding to the given URI"
  Code: -32603 

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|14.00GB (10.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.1

</details>

**Comment by akamath46297** [comment] 2019-09-13 20:40
This is a regression with the latest release i.e. 1.11.0 . I verified the older version worked fine.

**Comment by Charles-Gagnon** [comment] 2019-09-16 20:37
@akamath46297 This is likely because of changes in how URIs are handled - we've seen a few issues with the encoding not being done in some cases so you end up with different URIs (file://c:/myfile.txt vs file://c%2a/myfile.txt for example)

Can you confirm if this is the case here?

**Comment by wwdenis** [comment] 2019-09-17 11:39
Same here, verison 1.11.0, Windows 10 x64 10.0.18362.356

**Fail: Open File**

![OPENFILE_FAILED](https://user-images.githubusercontent.com/21691662/65038537-6f558f00-d950-11e9-814e-a629dfe2dded.gif)

**Success: New Query**

![PASTE_SUCCESS](https://user-images.githubusercontent.com/21691662/65038547-754b7000-d950-11e9-8f31-0591d0590b22.gif)

**Comment by anthonydresser** [comment] 2019-09-17 17:44
This will probably require updates to the pgsql extension to work properly. @Charles-Gagnon can you work with @akamath46297 to identify the issue in the pgsql extension since you performed a similar fix in the sqltoolservice?

**Comment by mark-uscbi** [comment] 2019-09-17 19:53
Is there going to be a hotfix available for this?

**Comment by olebenny** [comment] 2019-09-18 08:27
This problem is also found in 1.12.0-insider ( user setup )

**Comment by akamath46297** [comment] 2019-09-18 19:49
I have https://github.com/microsoft/pgtoolsservice/pull/219 out for this

**Comment by aaomidi** [comment] 2019-10-14 22:00
This problem should be resolved in the next release / insiders.

**Closed by aaomidi** 2019-10-14 22:00 UTC
Labels: Area - Query Editor, Bug, Pri: 1, Triage: Done
