### ISSUE TITLE
MSSQL query against linked server shows 'Invalid Object Name' although query works

### ISSUE THREAD

**Issue by mjnorman** [microsoft/azuredatastudio#19253] opened 2022-04-29 17:39 UTC
Issue Type: <b>Bug</b>

Azure Data studio running on MacOS connecting to MSSQL v 14.0.3436.1
Sql Server has a Linked Server to another Target Sql Server.
This linked server shows up in Azure Data Studio, however I'm unable to browse catalogs for that server as in SSMS.  I'm not sure if this is by design or not.
Running a query against the linked server will show `Invalid Object Name` as an error, however the query does run successfully.

![image](https://user-images.githubusercontent.com/21270587/165995078-22dcb5bd-14ef-4661-b1f7-e492fb226bd9.png)

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:00:06.749Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-server-diagnostic-book|ema|0.2.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.13.1
sql-database-projects|Mic|0.16.1
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment] 2023-03-03 00:54
Duplicate of https://github.com/microsoft/azuredatastudio/issues/20107

**Closed by Charles-Gagnon** 2023-03-03 00:54 UTC
Labels: Bug, Area - Language Service, Triage: Needed
