### ISSUE TITLE
Irrelevant window is closing after save

### ISSUE THREAD

**Issue by malicanli** [microsoft/azuredatastudio#13797] opened 2020-12-14 12:18 UTC
![Capture](https://user-images.githubusercontent.com/62541287/102080448-86b74c80-3e1f-11eb-9abd-66b4aca5963e.JPG)
Issue Type: <b>Bug</b>

1- Query script has been saving
2- When you click Irrelevant other query window, giving error message at right bottom corner
3- Message is: Unable to open 'SQLQuery_5 - SERVERNAME...grated)': Cannot read property 'slice' of undefined.
4- And Query window which you clicked is closing and disapperaing without warning and saving

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.1.0

</details>

**Comment by alanrenmsft** [comment] 2021-03-05 00:41
@malicanli Do yo have a consistent repro of the issue?

**Comment by Charles-Gagnon** [comment] 2021-04-05 16:44
Closing this as a duplicate of #14929 - see that for some more information on additional logging we added recently to try and track this down.

**Closed by Charles-Gagnon** 2021-04-05 16:44 UTC
Labels: Area - Query Editor, Bug, Triage: Done
