### ISSUE TITLE
Filtering for Azure subscription doesn't sustain after restarting

### ISSUE THREAD

**Issue by rickixie** [microsoft/azuredatastudio#22572] opened 2023-03-31 19:52 UTC
Issue Type: <b>Bug</b>

I tried to filter the subscription to displayed on the server page but it doesn't sustain after I closed and reopen ADS. It is the same with the stable release and the insider version. I am on Mac. It is not subscription specific and have tried with other subscription I own.

![CleanShot 2023-03-31 at 12 55 50 2](https://user-images.githubusercontent.com/5816630/229218600-ba044741-bc5e-4411-af30-1c6088dcc3c1.gif)

Azure Data Studio version: azuredatastudio 1.42.0 (Universal) (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:04:34.407Z)
OS version: Darwin x64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azcli|Mic|1.8.0

</details>

**Comment by cheenamalhotra** [comment] 2023-03-31 21:57
Hi @rickixie 

I cannot reproduce that on Windows, @cssuh can you try on Mac if behavior is different?
Since this is saved in User Workspace storage, can you check your settings file and share any related modified settings?

**Comment by cssuh** [comment] 2023-03-31 22:03
@cheenamalhotra I am able to repro this behavior on Mac

**Comment by rickixie** [comment] 2023-04-05 23:26
Sorry just saw this - here's partial of my setting's file in JSON (i don't think i change anything). I also have VS code insider install, and it has been having random issue as well so not sure if it is related.

```
    "mssql.objectExplorer.groupBySchema": false,
    "workbench.enablePreviewFeatures": true,
    "notebook.pythonPath": "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7",
    "notebook.useExistingPython": true,
    "dashboard.database.properties": true,
    "workbench.useVSCodeNotebooks": true,
    "notebookViews.enabled": true
```

> Hi @rickixie
> 
> I cannot reproduce that on Windows, @cssuh can you try on Mac if behavior is different? Since this is saved in User Workspace storage, can you check your settings file and share any related modified settings?

**Comment by cssuh** [comment] 2023-04-11 23:44
Not able to repro, this seems to be fixed in the latest insiders build

**Closed by cssuh** 2023-04-11 23:44 UTC
Labels: Bug, Area - Azure, Triage: Done
