### ISSUE TITLE
Trying to Reconnect a Disconnected Query Crashes ADS

### ISSUE THREAD

**Issue by XMLDiva** [microsoft/azuredatastudio#23301] opened 2023-06-02 03:25 UTC
Type: <b>Bug</b>

If I open ADS with a query that I had open, if I try to click on "Connect" and then choose from my list of saved server connection strings, ADS will crash right after clicking the connect button. This happens for both Azure instances as well as hosted local sql servers.
 
Additionally this works the same with notebooks. I cannot try to connect it to a server without it crashing. Making them and any saved query unusable.

I must copy the query, right click on the saved server, do New Query, and then paste the code in it.

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:50:03.880Z)
OS version: Darwin arm64 22.3.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 3|
|Memory (System)|64.00GB (3.31GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
demo-mode|dre|1.1.1
copilot|Git|1.82.15
newdatabase|kev|1.0.0
ssmskeymap|kev|1.1.0
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
cms|Mic|0.9.3
dacpac|Mic|1.13.0
import|Mic|1.5.5
powershell|ms-|2022.7.2
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.19.0
server-report|Mic|0.2.4
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|1.1.1
whoisactive|Mic|0.1.5
azdata-sanddance|msr|4.0.1
sqlops-spexecutesql-to-sql|pej|1.0.2
schema-visualization|R0t|0.8.2
simple-data-scripter|sea|0.1.6
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment] 2023-06-05 17:45
Hi @XMLDiva 

I couldn't reproduce the issue by using steps above, please upload logs for investigation.

**Comment by XMLDiva** [comment] 2023-06-10 02:55
Hi @cheenamalhotra ,

[LogFile.zip](https://github.com/microsoft/azuredatastudio/files/11711360/LogFile.zip)

Attached log files after setting tracing to all attached.

**Comment by cheenamalhotra** [comment] 2023-06-13 19:22
I don't see any connection related error. The only reasonable logs I can find are these:

```
[exthost] [info] ExtensionService#_doActivateExtension Microsoft.xml-language-features, startup: false, activationEvent: 'onLanguage:sql'
[exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:sql'
[exthost] [info] Extension host terminating: renderer closed the socket
[exthost] [info] Extension host with pid 12812 exiting with code 0
```

```
[renderer1] [warning] SettingsEditor2: Settings not included in settingsLayout.ts: sql.query.shortcut1, 
sql.query.shortcut2, sql.query.shortcut3, sql.query.shortcut4, sql.query.shortcut5, sql.query.shortcut6, sql.query.shortcut7, 
sql.query.shortcut8, sql.query.shortcut9, notebookExplorerSearch.actionsPosition, notebookExplorerSearch.collapseResults, 
notebookExplorerSearch.exclude, notebookExplorerSearch.followSymlinks, notebookExplorerSearch.globalFindClipboard, 
notebookExplorerSearch.location, notebookExplorerSearch.maintainFileSearchCache, 
notebookExplorerSearch.quickOpen.history.filterSortOrder, notebookExplorerSearch.quickOpen.includeHistory, 
notebookExplorerSearch.quickOpen.includeSymbols, notebookExplorerSearch.searchEditor.doubleClickBehaviour, 
notebookExplorerSearch.searchOnType, notebookExplorerSearch.searchOnTypeDebouncePeriod, 
notebookExplorerSearch.seedOnFocus, notebookExplorerSearch.seedWithNearestWord, 
notebookExplorerSearch.showLineNumbers, notebookExplorerSearch.smartCase, notebookExplorerSearch.sortOrder, 
notebookExplorerSearch.useGlobalIgnoreFiles, notebookExplorerSearch.useIgnoreFiles, notebookExplorerSearch.usePCRE2, 
notebookExplorerSearch.useReplacePreview, notebookExplorerSearch.useRipgrep, serverTree.useAsyncServerTree, 
resultsGrid.autoSizeColumns, resultsGrid.cellPadding, resultsGrid.fontFamily, resultsGrid.fontSize, resultsGrid.fontWeight, 
resultsGrid.letterSpacing, resultsGrid.maxColumnWidth, resultsGrid.rowHeight, resultsGrid.showJsonAsLink, 
sql.defaultAuthenticationType, sql.defaultEngine, sql.maxRecentConnections, notebookViews.enabled

[renderer1] [critical] Extension 'github.copilot' wants API proposal 'interactive' but that proposal DOES NOT EXIST. 
Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.

[renderer1] [warning] Settings pattern "debug.*" doesn't match any settings
[renderer1] [warning] Settings pattern "launch" doesn't match any settings
[renderer1] [warning] Settings pattern "audioCues.*" doesn't match any settings
[renderer1] [warning] Settings pattern "notebook.*" doesn't match any settings
[renderer1] [warning] Settings pattern "tableDesigner.*" doesn't match any settings
[renderer1] [error] An unknown error occurred. Please consult the log for more details.
```

**Comment by cheenamalhotra** [comment] 2023-07-05 18:31
@XMLDiva 

Can you please confirm if this issue still occurs for you using the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch)?

**Comment by cssuh** [comment] 2023-09-21 19:35
Closing as no relevant logs were provided

**Closed by cssuh** 2023-09-21 19:35 UTC
Labels: Bug, Area - Connection, Triage: Done, Needs Logs
