### ISSUE TITLE
When saving a notebook file after copying to WYSIWYG mode, the format changed

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#14576] opened 2021-03-05 18:18 UTC
- Azure Data Studio Version:
Version: 1.26.1 (user setup)
Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
Date: 2021-02-24T23:42:55.085Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Copy and paste OneNote to Notebook where it has multiple list items, paragraphs, table and some formatted text with spans.
2. Edit Notebook, e.g. change a top line to be a header.. add a new text after the first paragraph. 
3. Save file. 

For some reason the newline break (and may be something else) was removed in other parts of notebooks.

**Comment by barbaravaldez** [comment] 2021-03-05 19:46
Hi @MsSQLGirl, do you know if this is a regression?

**Comment by MsSQLGirl** [comment] 2021-03-05 20:23
I'm not sure actually. @chlafreniere has been looking into this. 
Chris mentioned that he could repro in stable, and couldn't repro it in the Insiders version anymore. I just also tested, and confirmed that is the case.

**Comment by chlafreniere** [comment] 2021-03-05 23:33
This was fixed by #14529. New for March.

**Comment by MsSQLGirl** [comment] 2021-03-06 00:13
Note: this happens to existing notebook files not just a fresh oneNote to Notebook copy+paste.

**Comment by lucyzhang929** [comment] 2021-03-08 21:22
@chlafreniere @MsSQLGirl Can this issue be closed now since it was fixed by https://github.com/microsoft/azuredatastudio/pull/14529?

**Comment by chlafreniere** [comment] 2021-03-15 20:00
Verified that it has been fixed by #14529. Closing.

**Closed by chlafreniere** 2021-03-15 20:00 UTC
Labels: Area - Notebooks, Bug, Impact: Live site
