### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by isaias-izquierdo** [microsoft/azuredatastudio#8299] opened 2019-11-11 19:30 UTC
Issue Type: <b>Bug</b>

The update this morning seems to break copy and paste.
I did the following:
- Crtl-a
- Ctrl-c
- Ctrl-v in Excel
=> The data is copied but it is all wrong. The data column do not match the select grid. It is the same with the rows.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (23.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2019-11-11 19:46
Closing as a duplicate of #8210

This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release. Sorry about the inconvenience!

**Closed by Charles-Gagnon** 2019-11-11 19:46 UTC
