### ISSUE TITLE
Server Group styling looks distorted for Async Server Tree

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23129] opened 2023-05-13 01:08 UTC
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/9b1bc5be-353c-4273-82a3-6c9e09723a27)
(only for Async Server Tree)

**Comment by aasimkhan30** [comment] 2023-05-13 01:23
@cheenamalhotra . Thats's by design due to contrast issue when highlighting search results

**Comment by cheenamalhotra** [comment] 2023-05-16 06:32
Can we try to fix the contrast issue by selecting colors more carefully - for both dark/light themes?

**Comment by aasimkhan30** [comment] 2023-05-26 00:40
Closing as it is by design and not a bug

**Closed by aasimkhan30** 2023-05-26 00:40 UTC
Labels: Bug, Area - Object Explorer, Triage: Needed
