### ISSUE TITLE
copying the value of cell in results view does not work

### ISSUE THREAD

**Issue by beowulf1416** [microsoft/azuredatastudio#24066] opened 2023-08-03 00:40 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. run any query that produces an output in the results window
2. click on a cell in the results window
3. open any text editor
4. paste copied value in text editor
5. copied value is wrong

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by beowulf1416** [comment] 2023-08-03 00:53
running ubuntu linux 22.04.2 LTS and azure data studio 1.45.0
don't have this issue in 1.44.1
recently upgraded to 1.45.0 yesterday

**Comment by cheenamalhotra** [comment] 2023-08-03 00:55
In that case it seems duplicate of https://github.com/microsoft/azuredatastudio/issues/24043 - please follow the same for updates. Thanks.

**Closed by cheenamalhotra** 2023-08-03 00:55 UTC
Labels: Bug, Area - Query Editor, Needs More Info, Triage: Needed

**Comment by beowulf1416** [comment] 2023-08-03 01:03
fixed it by installing xsel

**Comment by beowulf1416** [comment] 2023-08-10 21:57
closing
