### ISSUE TITLE
Failed to change kernel. Kernel SQL will be used. Error was: Can't find notebook manager for provider jupyter

### ISSUE THREAD

**Issue by ottolaz72** [microsoft/azuredatastudio#16746] opened 2021-08-12 13:51 UTC
Issue Type: <b>Bug</b>

1) Open a new notebook. Kernel takes some time to load and defaults to SQL.
2) Select from dropdown menu Python 3.
3) Error appears: Failed to change kernel. Kernel SQL will be used. Error was: Can't find notebook manager for provider jupyter
4)Cmd+shift+P to reinstall Notebook Dependencies. -> new error: Command 'Reinstall Notebook dependencies' resulted in an error (command 'jupyter.reinstallDependencies' not found)
5) Removed Azure Data Studio and deleted folders. 
6) Reinstalled ADS. Same behaviour.
7) Command python3 run in built in ADS Terminal shows: 
(base) user@computerXYZ ~ % python3
Python 3.9.6 (default, Jun 29 2021, 05:25:02) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:13:05.032Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
azdata|Mic|0.6.4
dacpac|Mic|1.8.0
datavirtualization|Mic|1.12.0
import|Mic|1.3.1
machine-learning|Mic|0.10.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.1
sql-dw|Mic|0.0.1
azdata-sanddance|msr|3.3.0

</details>

**Comment by lucyzhang929** [comment] 2021-08-12 19:08
Hi @ottolaz72, could you provide logs please (instructions to get logs above).
In addition, are you able to run Configure Python for Notebooks (also located in the Command Palette - Cmd+Shift+P)?

**Comment by chlafreniere** [comment] 2021-09-28 23:30
Closing since we need logs to delve deeper into this issue. Feel free to reactivate if logs can be provided. Thanks!

**Closed by chlafreniere** 2021-09-28 23:30 UTC
Labels: Bug, Area - Notebooks, Triage: Done, Needs Logs

**Comment by Maclenn77** [comment] 2023-09-08 18:41
Hi, @chlafreniere and @lucyzhang929 ! I'm facing a similar issue (same error message, same way to reproduce).

I add the last logs in my output:

... Ensuring C:\Users\user\AppData\Roaming\jupyter\instances\80234e77-4a66-4612-9f49-d5b9959b3fbf exists
... Ensuring C:\Users\user\AppData\Roaming\jupyter\instances\80234e77-4a66-4612-9f49-d5b9959b3fbf\config exists
... Ensuring C:\Users\user\AppData\Roaming\jupyter\instances\80234e77-4a66-4612-9f49-d5b9959b3fbf\data exists
... Ensuring C:\Users\user\AppData\Roaming\jupyter\instances\80234e77-4a66-4612-9f49-d5b9959b3fbf\config\custom exists
... Ensuring C:\Users\user\AppData\Roaming\jupyter\kernels exists
... Starting Notebook server
    > "C:\Users\user\azuredatastudio-python\python.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --ip=127.0.0.1  --no-mathjax --notebook-dir "c:\Users\user" --NotebookApp.token=A_TOKEN_VALUE

**Comment by lucyzhang929** [comment] 2023-09-08 18:51
Hi @Maclenn77, your issue seems to be similar to this: https://github.com/microsoft/azuredatastudio/issues/23945. Can you try pinning the notebook package to v6.5.5 and see if that fixes your issue?
```
pip3 install notebook==6.5.5
```

**Comment by Maclenn77** [comment] 2023-09-08 19:25
Thanks so much, @lucyzhang929 ! That solved the issue.
