### ISSUE TITLE
Attempting to "Create Azure Arc Data Controller" give account error

### ISSUE THREAD

**Issue by EricBuMSFT** [microsoft/azuredatastudio#14776] opened 2021-03-17 20:04 UTC
Hi,

I get the following error in the "Create Azure Arc Data Controller" Wizard. Step 1. 

ADS Insiders Build 1.27.0
Azure Arc Extension 0.9.0

Error: Error fetching subscriptions for account Eric Burgess - ericbu@microsoft.com tenant 105bXXXX-XXXX-XXXX-XXXX-24d304d195dc : Token retrieval failed with an error. Open developer tools to view the error
Error: Error fetching subscriptions for account Eric Burgess - ericbu@microsoft.com tenant 72f9XXXX-XXXX-XXXX-XXXX-2d7cd011db47 : Token retrieval failed with an error. Open developer tools to view the error.

**While this error was happening I was unable to select the drop down to pick a valid subscription.** Hence the Wizard wouldn't work.

Error: Error fetching subscriptions for account Eric Burgess - ericbu@microsoft.com tenant XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX : Token retrieval failed with an error. Open developer tools to view the error	at c:\Users\EricBu\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:16:18559	at processTicksAndRejections (internal/process/task_queues.js:94:5)	at async Promise.all (index 0)	at async Object.t.getSubscriptions (c:\Users\EricBu\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:16:18283)	at async j (c:\Users\EricBu\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\resource-deployment\dist\main.js:1:46128)	at async t (c:\Users\EricBu\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\resource-deployment\dist\main.js:1:38716)	at async Timeout._onTimeout (c:\Users\EricBu\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\resource-deployment\dist\main.js:1:39057) (at c:\Users\EricBu\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:16:18653)

I get around the error, by removing my account from ADS, and adding back the same Azure account. 
I was able to deploy the Arc Data Controller.

MAR2021BUGBASH

**Comment by Charles-Gagnon** [comment] 2021-03-19 22:53
Issues with the security tokens for Azure accounts are a known issue - see https://github.com/microsoft/azuredatastudio/issues/12165 - so I'm going to close this as a dupe of that (and also since it's not specifically an Arc issue)

**Closed by Charles-Gagnon** 2021-03-19 22:53 UTC
Labels: Area - Azure Arc, Triage: Needed
