### ISSUE TITLE
Unable to close notebook without saving

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#14127] opened 2021-02-01 17:53 UTC
Issue Type: <b>Bug</b>

I seem to be unable to exit a notebook without saving changes, whether or not I have made the changes myself or (in the gif) using an external process like my parameterization test notebook.

![Azure Data Studio - Unable to Close without Saving](https://user-images.githubusercontent.com/8250560/106497743-482f2d00-6473-11eb-89fb-fa489d176d17.gif)

Azure Data Studio version: azuredatastudio-insiders 1.26.0-insider (8651db1e7edfe83452c01c6aeb4cfe6d20baabfa, 2021-01-28T07:00:09.975Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
sales-by-salesperson|Adv|0.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
adslivesite|Mic|0.0.36
agent|Mic|0.47.0
arc|Mic|0.7.1
asde-deployment|Mic|0.4.0
azdata|Mic|0.5.1
azuredatastudio-mysql|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.6.0
datavirtualization|Mic|1.12.0
import|Mic|1.2.0
kusto|Mic|0.4.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
sql-database-projects|Mic|0.5.1
azdata-sanddance|msr|3.1.0
azuredatabot|vas|0.0.2

</details>

**Comment by MaddyDev** [comment] 2021-02-11 18:56
This is a corner case caused by parametrization.
Repro steps:
1. Get the Papermill-Parametrization notebooks from https://github.com/VasuBhog/AzureDataStudio-Notebooks and save them.
2. Open the folder where you saved the notebooks and open both ExcecuteInput_UsingPapermill.ipynb and output.ipynb
3. Update the contents of ExcecuteInput_UsingPapermill.ipynb to below and run the notebook.

```python
import papermill as pm

pm.execute_notebook(
   '<PathToNotebooks>\\Papermill-Parameterization\\Input.ipynb',
   '<PathToNotebooks>\\Papermill-Parameterization\\Output.ipynb',
   parameters = dict(x = 10, y = 20)
)
```
4. This would update the output.ipynb and show both the notebooks dirty. Now try closing the output.ipynb. It'll not let you close unless saved.

**Comment by chlafreniere** [comment] 2021-02-17 20:03
I'm able to repro this with the following:

- Open notebook with injected parameters cell
- Make a change (editor shows dirty)
- Attempt to close + don't save

Editor will remain open

**Comment by chlafreniere** [comment] 2021-02-18 05:30
Ported to release/1.26.

**Closed by chlafreniere** 2021-02-18 05:30 UTC
Labels: Approved, Area - Notebooks, Bug, Triage: Done
