### ISSUE TITLE
Editing a text cell with embedded image cause the existing image to be duplicated

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#16004] opened 2021-07-06 16:53 UTC
- Azure Data Studio Version:
- OS Version:

In the stable version 1.30.0, as detailed at the end of this comment, we noticed that if a user has an attachment image in a text cell, the next time the user makes an edit to the text cell, the existing attachment image is duplicated (and I think the reference is changed also). One of the notebook that I created using v1.30.0 managed to explode to 3MB. After manually cleaning it up, it became 320KB - it duplicated ~20x. 
Version: 1.30.0 (user setup)
Commit: 59c4b8e90cf2d3a24bed72623197f10f8d090fdc
Date: 2021-06-16T19:04:08.858Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

Mentioning it here only as a FYI and make sure that the test case covers for this experience, i.e. editing existing cell with existing attachment image. 

@Charles-Gagnon 
The steps to repro:
1. Create a text cell using WYSIWYG mode. Type a few lines (with words / numbers etc)
2. Copy and paste an image between the ines. This should invoke the attachment image. 
3. Exit out of text cell. Save. 
4. Edit the cell that you have just created. Above the image, remove or add a new line of words / numbers etc.
5. Save the file.
6. Go to notepad++ and open the notebook file and you'll see the json file will create a duplicate image.

This is reproable in  1.30.0. It seems to be solved in Insiders, but I would recommend to include this as part of a test case in Insiders.

A couple of users from live site have reported that they have experienced this behavior which cause the notebook to be bloated unnecessarily therefore causing ADS to be sluggish. 

> Note: I think this is fixed in Insiders 1.31. **Please add this as a test case**

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment] 2021-07-06 17:10
Let's confirm if this is accurate : 

`This is reproable in 1.30.0. It seems to be solved in Insiders, but I would recommend to include this as part of a test case in Insiders.`

If it is then we can close this.

**Comment by chlafreniere** [comment] 2021-07-06 20:08
@MsSQLGirl can you confirm what @Charles-Gagnon posted above?

**Comment by chlafreniere** [comment] 2021-07-07 01:18
Closing this as @dhgrajeda confirmed that existing images aren't duplicated.

**Closed by chlafreniere** 2021-07-07 01:18 UTC
Labels: Area - Notebooks, Bug, Impact: Live site, Pri: 1
