### ISSUE TITLE
SQL Import extension can't handle single column CSV file

### ISSUE THREAD

**Issue by peterrow** [microsoft/azuredatastudio#8155] opened 2019-10-31 19:24 UTC
- Azure Data Studio Version:
Version: 1.12.2 (system setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. In Excel one row 1, column A enter "Name", then on rows 2, 3, 4, enter a name, save as CSV
2. In SQL Import extension select the server, choose the CSV file you saved, you a simple message saying it was unsuccessful and to go back and select different file at the stage it would normally give you a preview data and choose field types.
3. Edit the Excel file and in row 1, column B enter "Anything", save as CSV.
4. Repeat step 2 having done nothing but added a 2nd empty column and now with the same data it magically works

**Comment by aasimkhan30** [comment] 2020-09-21 20:59
I have test this out and cannot reproduce it. Closing the issue

**Closed** 2020-09-21 20:58 UTC
Labels: Area - SQL Import, Bug, Triage: Done
