### ISSUE TITLE
Minimized window when not running Windows Explorer is blank (no restore/maximize/close buttons)

### ISSUE THREAD

**Issue by tburgesspw** [microsoft/azuredatastudio#21224] opened 2022-11-14 22:16 UTC
- Azure Data Studio Version: 1.39.1 (system setup)
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Run Windows without Windows Explorer running (no explorer.exe processes running)
2. Run Azure Data Studio
3. Minimize Azure Data Studio

Does this issue occur when all extensions are disabled?: Yes

![azuredatastudio_noexplorer](https://user-images.githubusercontent.com/92603142/201779491-3a22657a-4c07-49f7-b279-102173c1b11d.png)

**Comment by alanrenmsft** [comment] 2022-11-21 18:35
@tburgesspw do you have vscode installed? does vscode behave the same?

**Comment by tburgesspw** [comment] 2022-11-21 19:40
> @tburgesspw do you have vscode installed? does vscode behave the same?

I just installed VSCode. Yes, it does the same thing.

**Comment by alanrenmsft** [comment] 2022-11-21 21:35
@tburgesspw could you please open an issue in VSCode repo:https://github.com/microsoft/vscode?, Azure Data Studio is a fork of VSCode, if the issue is fixed in VSCode, we will also get it.

**Comment by alanrenmsft** [comment] 2022-11-21 21:36
closing as upstream.

**Closed** 2022-11-21 21:35 UTC
Labels: Bug, Area - Shell, Triage: Needed
