### ISSUE TITLE
Scrollbar too tiny

### ISSUE THREAD

**Issue by JCKodel** [microsoft/azuredatastudio#8605] opened 2019-12-09 17:06 UTC
Issue Type: <b>Feature Request</b>

Please, increase the size of horizontal scroll bar on grid results. Too tiny to be used with a mouse >.<

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18362

**Comment by kburtram** [comment] 2021-09-10 21:20
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/5139.  I believe we made the scrollbars larger since this issue was created but we'll double-check as part of resolving #5139.

**Closed by kburtram** 2021-09-10 21:20 UTC
Labels: Area - Query Editor, Enhancement
