### ISSUE TITLE
Bottom row of data being clipped

### ISSUE THREAD

**Issue by dazinator** [microsoft/azuredatastudio#21352] opened 2022-12-02 10:51 UTC
Issue Type: <b>Bug</b>

There is a bug with the results tab that display the grid of results after executing a query against an Azure SQL Server database.

To replicate:-

1. You have to execute a SQL query that selects enough columns so that the results tab enables horizontal scrolling (i.e the horizontal scrollbars for the results grid become visible)
2. You have to select enough rows of data, so that vertical scroll bars of the results grid also become enabled.

Then if you use the vertical scroll bar to try to scroll to the bottom of the grid of results (i.e to the last row) - you can't quite scroll to make the last row visible and it ends up being clipped by the purple status bar that azure data studio displays underneath.

Note: that if the horizontal scroll bar is not enabled, then this bug doesn't manifest and the vertical scroll position works correctly.

In the screenshot below, I have used my cursor to scroll the vertical scroll bar as far to the bottom as it will go, yet I still can't see the final row.

![image](https://user-images.githubusercontent.com/3176632/205276763-fc4096a2-cf56-48b2-832f-fe3907e6cf43.png)

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.11.0
import|Mic|1.5.3
profiler|Mic|0.11.0
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2021.8.1046824664
azdata-sanddance|msr|4.0.1

</details>

**Comment by alanrenmsft** [comment] 2022-12-16 05:40
I think this is a dupe of https://github.com/microsoft/azuredatastudio/issues/21231.

@dazinator please try the latest insider and see whether it is fixed for you: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch

**Closed by alanrenmsft** 2022-12-16 05:40 UTC
Labels: Bug, Area - Query Editor, Needs More Info, Triage: Done
