### ISSUE TITLE
Object explorer task didn't complete within 45 seconds

### ISSUE THREAD

**Issue by ehpmfigueroa** [microsoft/azuredatastudio#20545] opened 2022-09-06 13:35 UTC
Issue Type: <b>Bug</b>

1. Open the CONNECTIONS tab
2. Navigate to an existing connection
3. Click on the Databases node

The following error message shows up under the Databases node: Object explorer task didn't complete within 45 seconds.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (6.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none  
  

[Console.log](https://github.com/microsoft/azuredatastudio/files/9497421/Console.log)
[LogsFolder.zip](https://github.com/microsoft/azuredatastudio/files/9497423/LogsFolder.zip)

**Comment by Charles-Gagnon** [comment] 2022-09-12 17:54
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/6450 

@cheenamalhotra FYI in case the logs here are useful for your investigation into these areas at all

**Closed by Charles-Gagnon** 2022-09-12 17:54 UTC
