### ISSUE TITLE
Dashboard: Deleting widget from one dashboard deletes in all

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#2589] opened 2018-09-14 16:30 UTC
- SQL Operations Studio Version: master

Steps to Reproduce: 

1.  Go to any server's dashboard and click on `Edit` to delete one of the widgets.
2. Go to any other server's dashboard.

Expected - The server dashboards should be independent of each other.
Actual - The widget is deleted from all the dashboards.

**Comment by MattIrv** [comment] 2018-09-14 17:27
I think this is the intended behavior. @anthonydresser do you know?

**Comment by anthonydresser** [comment] 2018-09-14 17:50
Yeah there's 1 global setting for servers and 1 for databases. We had an ask to somehow specify to a server, but we came up with the solution is to specify at the widget level rather than the setting level.

**Comment by anushash** [comment] 2019-03-29 17:28
I have a few charts on #1 server and my other servers #2 and #3 have widgets without charts and has the error 'Error: Query has no results to return'. Thats because the query uses tables in server #1, and not server #2 or #3. But its annoying to see many widgets with errors when i dont even need them to be there. 

Is there a setting at widget level to specify server?

Thank you!

**Comment by kburtram** [comment] 2020-02-21 17:55
Closing older issues.  This should be addressed as part of dashboard refactor in-progress.

**Closed by kburtram** 2020-02-21 17:55 UTC
Labels: Area - Dashboard, Bug
