### ISSUE TITLE
Data studio frequently times-out and does not auto-reconnect to SQL Server (Azure Managed)

### ISSUE THREAD

**Issue by jguidera** [microsoft/azuredatastudio#16390] opened 2021-07-21 23:52 UTC
In SSMS and every other tool on the market the tool will automatically attempt to re-connect to SQL server if the connection has expired (e.g. token expired).  Data studio does not (Platform: Windows).  This means that I am constantly having to disconnect/reconnect the server explorer and "change connection" on individual sql query windows throughout the day.  Aside from being extremely annoying, its a huge productivity killer.  Please modify so that the client (azure data studio) attempt to transparently re-connect in the manner that SSMS (and every other third party management tool) does.

**Comment by raeokay** [comment] 2021-07-22 13:11
Looks like this issue, which I am still having:  https://github.com/microsoft/azuredatastudio/issues/14853

**Comment by kburtram** [comment] 2021-07-23 16:22
@jguidera I'll close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/14159 and move that issue into the current milestone.  We've been planning to fix in the past couple months but area committer has been finishing up work in a different product area.

**Closed by kburtram** 2021-07-23 16:22 UTC
