### ISSUE TITLE
Subcategories for Server did not open up

### ISSUE THREAD

**Issue by Matahari2000** [microsoft/azuredatastudio#13351] opened 2020-11-11 07:33 UTC
Issue Type: <b>Bug</b>

since one of the last updates i cannot open subcategories of server any more
I just see the related IP adress or name but i cannot see any related subcategories
I am connected and could run SQL scripts but with this i could not see for example table details

There are several, it works for example with microsoft SQL

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (9.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by abist** [comment] 2020-11-11 21:26
@Matahari2000 Thanks for opening this issue. Can you elaborate on what you mean by subcategories? Can you not expand the server nodes from the Connections Explorer?

**Comment by Charles-Gagnon** [comment] 2020-11-11 21:45
This seems like a duplicate of https://github.com/microsoft/azuredatastudio/issues/12992 - if your issue seems different please let us know!

**Closed by Charles-Gagnon** 2020-11-11 21:45 UTC
Labels: Needs More Info
