### ISSUE TITLE
App name incorrect in Win11 start menu

### ISSUE THREAD

**Issue by bralter** [microsoft/azuredatastudio#18825] opened 2022-03-25 16:52 UTC
Issue Type: <b>Bug</b>

Pin Azure Data Studio to start menu on Win11. It'll be shown as "Code - OSS" which is very confusing! It shows up correctly in the full app list.

This is happening because Data Studio doesn't correctly set the ShortDisplayName:

AppResolverPropertyIds::AppID: Microsoft.azuredatastudio
AppResolverPropertyIds::DisplayName: Azure Data Studio
AppResolverPropertyIds::ShortDisplayName: Code - OSS
AppResolverPropertyIds::SuiteName: Azure Data Studio

This should be updated.

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.22579
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (15.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2022-03-25 17:05
Duplicate of https://github.com/microsoft/azuredatastudio/issues/18618, this will be fixed in the upcoming release.

**Closed by Charles-Gagnon** 2022-03-25 17:05 UTC
