### ISSUE TITLE
Request connection/listdatabases failed.   Message: Microsoft.Data.SqlClient.SqlException 

### ISSUE THREAD

**Issue by lluthus** [microsoft/azuredatastudio#21803] opened 2023-02-01 09:03 UTC
Issue Type: <b>Bug</b>

is annoing me with this message each time i run a query, but the query works.

[Error - 10:00:01] Request connection/listdatabases failed.
  Message: Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'.

Azure Data Studio version: azuredatastudio 1.41.0 (cf5e0fe1a33709e2a82dc94f42dbe88487803d62, 2023-01-24T17:25:45.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.78GB (40.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.12.2
schema-compare|Mic|1.18.0
sql-database-projects|Mic|0.21.0

</details>

**Comment by cheenamalhotra** [comment] 2023-02-01 19:46
Seems duplicate of #21752 (ref: [comment](https://github.com/microsoft/azuredatastudio/issues/21752#issuecomment-1410887350))

**Closed** 2023-02-01 20:05 UTC
Labels: Duplicate
