### ISSUE TITLE
Personalize Server Connection

### ISSUE THREAD

**Issue by ehutton** [microsoft/azuredatastudio#8377] opened 2019-11-18 14:29 UTC
Issue Type: <b>Feature Request</b>

It would be good if you could set the "color" property of a server , as you can in SSMS.  This makes it easy to tell which server you are connected to in a quick glance.  I typically use a green, yellow, red color scheme for my development, testbed, and production servers.

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.16299

**Comment by cheenamalhotra** [comment] 2023-04-12 07:23
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/13683

**Closed by cheenamalhotra** 2023-04-12 07:23 UTC
Labels: Area - Connection, Enhancement, Triage: Done
