### ISSUE TITLE
Add an Account not works behind proxy (azure auth code grant)

### ISSUE THREAD

**Issue by esauaguilar-kr** [microsoft/azuredatastudio#18296] opened 2022-02-10 15:59 UTC
Issue Type: <b>Bug</b>

1- Click on the account icon over the settings gear icon, then open the linked account menu on the right side and click on Add an account button.
<img width="1792" alt="Screen Shot 2022-02-10 at 9 34 37" src="https://user-images.githubusercontent.com/94638011/153443561-4bc4f82a-5f49-414f-af08-d1f5801ef43a.png">

2- Web browser opens Sign-in page, and select your account

3- It gets stuck and still loading, never finishes to link the account
<img width="1792" alt="Screen Shot 2022-02-10 at 9 36 06" src="https://user-images.githubusercontent.com/94638011/153443704-36c7979a-796f-4567-816f-5b66914d5c83.png">

note: Azure Device code not works for me (when I select this option shows nothing)

- I tried to use VSCode using mssql plugin, to replace azure data studio, but I guess it works like  azure data studio because both get stuck at the step to add an account, but the sign-in works on VSCode - azure tools plugin (using the same proxy)

    - I register a bug in the mssql plugin repo where I describe almost the same proccess and i got the same results as azure data studio: https://github.com/microsoft/vscode-mssql/issues/17234

Azure Data Studio version: azuredatastudio-insiders 1.35.0-insider (250532f39d2c460f25e646e701bb94d9860d7365, 2022-02-10T06:31:40.825Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.9.1
import|Mic|1.5.0
powershell|ms-|2021.12.0
profiler|Mic|0.12.1

</details>

**Comment by cssuh** [comment] 2022-02-16 21:17
Hi @esauaguilar-kr, can you go into the settings and enable Verbose logging for Azure?  Then try this process again and report back with the relevant logs.  You can find the logs by hitting control + shift + P and selecting `Developer: Open Logs Folder`, and following this path: `[default log folder]/exthost1/output_logging_[earliest timestamp]/2-Azure Acounts.log`

**Comment by villanisaac-kr** [comment] 2022-03-04 21:57
I' having the same issue 

![image](https://user-images.githubusercontent.com/90802542/156846633-47cbdd96-d316-4e51-ab4f-ebcdfccb162e.png)

My Azure configuration looks like in below picture

![image](https://user-images.githubusercontent.com/90802542/156846738-fdd28867-bf02-4df5-b337-cd6e6a327572.png)

#----main.log---contents--------
[2022-03-04 15:44:27.070] [main] [info] window: vscode-file:// protocol is explicitly disabled
[2022-03-04 15:44:27.246] [main] [info] update#setState idle
[2022-03-04 15:44:57.252] [main] [info] update#setState checking for updates
[2022-03-04 15:44:58.412] [main] [info] update#setState downloading
[2022-03-04 15:46:27.202] [main] [info] update#setState ready

#---------------------------------


#-----render1.log---contents---------
[2022-03-04 15:45:01.928] [renderer1] [info] Cancelling connection for URI connection:providerName:MSSQL|applicationName:azdata|authenticationType:|database:|server:|user:|group:undefined
[2022-03-04 15:45:06.896] [renderer1] [warning] Settings pattern "debug.*" doesn't match any settings
[2022-03-04 15:45:06.896] [renderer1] [warning] Settings pattern "launch" doesn't match any settings
[2022-03-04 15:45:06.898] [renderer1] [warning] Settings pattern "notebook.*" doesn't match any settings
[2022-03-04 15:45:06.898] [renderer1] [warning] SettingsEditor2: Settings not included in settingsLayout.ts: sql.query.shortcut1, sql.query.shortcut2, sql.query.shortcut3, sql.query.shortcut4, sql.query.shortcut5, sql.query.shortcut6, sql.query.shortcut7, sql.query.shortcut8, sql.query.shortcut9, notebookExplorerSearch.actionsPosition, notebookExplorerSearch.collapseResults, notebookExplorerSearch.exclude, notebookExplorerSearch.followSymlinks, notebookExplorerSearch.globalFindClipboard, notebookExplorerSearch.location, notebookExplorerSearch.maintainFileSearchCache, notebookExplorerSearch.quickOpen.history.filterSortOrder, notebookExplorerSearch.quickOpen.includeHistory, notebookExplorerSearch.quickOpen.includeSymbols, notebookExplorerSearch.searchEditor.doubleClickBehaviour, notebookExplorerSearch.searchOnType, notebookExplorerSearch.searchOnTypeDebouncePeriod, notebookExplorerSearch.seedOnFocus, notebookExplorerSearch.seedWithNearestWord, notebookExplorerSearch.showLineNumbers, notebookExplorerSearch.smartCase, notebookExplorerSearch.sortOrder, notebookExplorerSearch.useGlobalIgnoreFiles, notebookExplorerSearch.useIgnoreFiles, notebookExplorerSearch.usePCRE2, notebookExplorerSearch.useReplacePreview, notebookExplorerSearch.useRipgrep, serverTree.useAsyncServerTree, resultsGrid.autoSizeColumns, resultsGrid.cellPadding, resultsGrid.fontFamily, resultsGrid.fontSize, resultsGrid.fontWeight, resultsGrid.letterSpacing, resultsGrid.maxColumnWidth, resultsGrid.rowHeight, sql.defaultAuthenticationType, sql.defaultEngine, sql.maxRecentConnections, notebookViews.enabled
[2022-03-04 15:45:09.280] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2022-03-04 15:45:10.606] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2022-03-04 15:45:52.043] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2022-03-04 15:46:59.084] [renderer1] [warning] Settings pattern "debug.*" doesn't match any settings
[2022-03-04 15:46:59.084] [renderer1] [warning] Settings pattern "launch" doesn't match any settings
[2022-03-04 15:46:59.085] [renderer1] [warning] Settings pattern "notebook.*" doesn't match any settings
[2022-03-04 15:50:59.606] [renderer1] [info] Cancelling connection for URI connection:providerName:MSSQL|applicationName:azdata|authenticationType:|database:|server:|user:|group:undefined

#----------------------

#-------sharedprocess.log------contents--------
[2022-03-04 15:44:40.324] [sharedprocess] [info] [logs cleanup]: Starting to clean up old logs.
[2022-03-04 15:45:00.323] [sharedprocess] [info] [code cache cleanup]: Starting to clean up old code cache folders.
[2022-03-04 15:45:00.324] [sharedprocess] [info] [storage cleanup]: Starting to clean up storage folders.
[2022-03-04 15:45:10.326] [sharedprocess] [info] [language pack cache cleanup]: Starting to clean up unused language packs.

#-------------------


#----exthost/exhthost1.log--contents---
[2022-03-04 15:44:30.645] [exthost] [info] extension host started
[2022-03-04 15:44:30.679] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.azurecore {"startup":true,"extensionId":{"value":"Microsoft.azurecore","_lower":"microsoft.azurecore"},"activationEvent":"*"}
[2022-03-04 15:44:30.679] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/azurecore/dist/extension
[2022-03-04 15:44:30.934] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.data-workspace {"startup":true,"extensionId":{"value":"Microsoft.data-workspace","_lower":"microsoft.data-workspace"},"activationEvent":"*"}
[2022-03-04 15:44:30.934] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/data-workspace/dist/main
[2022-03-04 15:44:30.954] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2022-03-04 15:44:30.954] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/git/dist/main
[2022-03-04 15:44:30.988] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.notebook {"startup":true,"extensionId":{"value":"Microsoft.notebook","_lower":"microsoft.notebook"},"activationEvent":"*"}
[2022-03-04 15:44:30.988] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/notebook/dist/extension
[2022-03-04 15:44:32.321] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2022-03-04 15:44:32.321] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/github/dist/extension.js
[2022-03-04 15:44:32.330] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.mssql {"startup":true,"extensionId":{"value":"Microsoft.mssql","_lower":"microsoft.mssql"},"activationEvent":"*"}
[2022-03-04 15:44:32.330] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main
[2022-03-04 15:44:35.234] [exthost] [info] eager extensions activated
[2022-03-04 15:44:35.238] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2022-03-04 15:44:35.240] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2022-03-04 15:44:35.244] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2022-03-04 15:44:35.244] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/testing-editor-contributions/dist/extension.js
[2022-03-04 15:47:10.463] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2022-03-04 15:47:10.464] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2022-03-04 15:47:10.471] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2022-03-04 15:47:10.471] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Azure Data Studio.app/Contents/Resources/app/extensions/json-language-features/client/dist/node/jsonClientMain

#-----------------------


All other log files are empty.

**Comment by thevinnie** [comment] 2022-08-26 15:14
We're having this same issue for a customer and wanted to check in on the situation. The customer is generating details of the issue, but is this being pulled into the backlog or are there any known workarounds?

**Comment by thevinnie** [comment] 2022-08-26 15:44
A little more detail here...  What my colleague has uncovered is that the Data Studio application is picking up an environment variable value stored in HTTPS_PROXY. In our situation, the customer has an Azure CLI installation that populates this with a value that is specific for the Azure CLI and other applications (like Data Studio) need to go to a different endpoint. (We're trying to "unbungle" the proxy setup, but that's a long-term objective)

Can we confirm the following:
- When present, Data Studio will use the value of HTTPS_PROXY during the authentication process
- If there is a setting which will allow for overriding that environment variable value

The issue we're facing seem similar to what's happening here:
https://github.com/microsoft/azuredatastudio/issues/15342

**Comment by cheenamalhotra** [comment] 2022-08-26 16:05
@thevinnie 
Have you tried providing Proxy details in Settings (Ctrl+,) in Azure Data Studio?

**Comment by cheenamalhotra** [comment] 2022-09-01 02:45
@thevinnie 
I'll proceed to close this issue as its duplicate of #17356 and progress can be tracked there instead.

**Closed by cheenamalhotra** 2022-09-01 02:45 UTC
Labels: Bug, Area - Connection, Area - Azure, Triage: Done
