### ISSUE TITLE
Unsaved query gets closed by itself. Unable to open again-Lost it

### ISSUE THREAD

**Issue by JeffBusterCase** [microsoft/azuredatastudio#17798] opened 2021-12-02 19:51 UTC
Just using a normal query tab on SQL Server. After sometime the query disapears, I think that maybe this happens when refocusing the Application.  There is a Log on Developers Tool window of a slice or something error:

Unable to open 'SQL Query_4 -------' : Cannot read property slice of undefined.
OnDidChangeNotification: workbench.desktop.main.js:1633

It happend three times I think already...

One query tab still shows up, but the other is gone..
![bug_azure_data_studioQ](https://user-images.githubusercontent.com/12688410/144492290-284e38f1-563d-4fa6-b4e9-a9b5feef0200.png)

![image](https://user-images.githubusercontent.com/12688410/144492662-4275a311-edd9-42b3-b48f-f4ab312bf575.png)

<html>
<body>

CPUs | Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.91GB (19.70GB free)
Process Argv |  
Screen Reader | no
VM | 0%

</body>
</html>

<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
ssmskeymap | kev | 1.1.0
admin-pack | Mic | 0.0.2
admin-tool-ext-win | Mic | 0.0.3
agent | Mic | 0.48.0
dacpac | Mic | 1.8.0
import | Mic | 1.5.0
managed-instance-dashboard | Mic | 0.4.2
profiler | Mic | 0.11.0
query-history | Mic | 0.1.0
azdata-sanddance | msr | 3.3.0

</body>
</html>

**Comment by Charles-Gagnon** [comment] 2021-12-02 19:54
Duplicate of https://github.com/microsoft/azuredatastudio/issues/6763 - the next release should fix it so at least it won't close the editor (allowing you to save your work and re-open in another tab) while we investigate the issue causing this to happen.

**Comment by Charles-Gagnon** [comment] 2021-12-02 19:54
@alanrenmsft FYI

**Closed by Charles-Gagnon** 2021-12-02 19:54 UTC
