### ISSUE TITLE
BDC dashboard looks really bad in dark themes...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#8500] opened 2019-11-28 00:06 UTC
![ads2](https://user-images.githubusercontent.com/10999577/69767180-eddc6300-112f-11ea-9d37-50d2727f17c5.png)

![ads](https://user-images.githubusercontent.com/10999577/69767135-aa81f480-112f-11ea-8875-11215537366f.png)
Issue Type: <b>Bug</b>

See attachments for how it looks in Atom & the default dark theme.

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (39e6b9933d98002ce10ffa74f69e7d85d7df130b, 2019-11-27T21:06:43.843Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.44.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.0.0
datavirtualization|Mic|1.1.0
import|Mic|0.12.0
profiler|Mic|0.10.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment] 2019-11-28 21:52
Thanks for the feedback @uc-msft ! I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/7400 for now, but I'm planning on improving this for the next release.

**Closed by Charles-Gagnon** 2019-11-28 21:52 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
