### ISSUE TITLE
Object Explorer task didn't complete within 45 seconds

### ISSUE THREAD

**Issue by andy-fenn** [microsoft/azuredatastudio#19167] opened 2022-04-21 08:17 UTC
Issue Type: <b>Bug</b>

- Upgrade to version 1.36

- Click on CONNECTIONS tab

- Navigate to an existing connection.

- Navigate to and expand Tables

    - **Expected:** All tables within the database are displayed

    - **Actual:** Error message "Object Explorer task didn't complete within 45 seconds"

This is happening to all our users who have upgraded to 1.36 on both Windows and Mac

Azure Data Studio version: azuredatastudio 1.36.0 (0704471e6b4a79f0c2c2425b22dc6bee60a1c2a8, 2022-04-19T18:20:54.197Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-oracle|Mic|0.1.2
import|Mic|1.5.0
net-6-runtime|Mic|1.0.0
query-history|Mic|0.1.0
schema-compare|Mic|1.13.1
sql-database-projects|Mic|0.16.1

</details>

**Comment by Charles-Gagnon** [comment] 2022-04-21 16:29
Duplicate of https://github.com/microsoft/azuredatastudio/issues/19166

**Closed by Charles-Gagnon** 2022-04-21 16:29 UTC

**Comment by kburtram** [comment] 2022-04-21 16:39
@andy-fenn could you please add error logs to https://github.com/microsoft/azuredatastudio/issues/19166 following instructions on that issue, if possible?  Thanks!

**Comment by conradsuuna** [comment] 2022-05-17 10:35
Kindly update your Azure data studio. Fixed the issue on my end.

**Comment by Trymzet** [comment] 2023-07-17 08:15
Broken again (or still) on 1.44.1 on Windows 11. My old version from 1 year ago worked so going back to that.
