### ISSUE TITLE
OK button is disabled

### ISSUE THREAD

**Issue by ranjCS** [microsoft/azuredatastudio#23473] opened 2023-06-26 07:24 UTC
- Azure Data Studio Version:
1.44.1
- OS Version:
Windows 11 Enterprise
Steps to Reproduce:

1. Select the source DB, 
2. Select the target DB
I expect the OK button button to be enabled so I can click, but it is not. Any reason for that?

Does this issue occur when all extensions are disabled?: Yes/No
No

![image](https://github.com/microsoft/azuredatastudio/assets/14230893/99dc41fa-a586-49e5-aa43-361a11c5a8e9)

**Comment by kisantia** [comment] 2023-06-26 19:00
@ranjCS does this consistently happen? If you close and reopen the dialog does this still happen?

**Comment by ranjCS** [comment] 2023-06-27 14:55
Yes it does, the only workaround is to restart the whole application.

Regards
Ranj

**Comment by kisantia** [comment] 2023-06-27 16:10
@SakshiS-harma can you please look into this? Sounds like it might be a race condition

**Comment by SakshiS-harma** [comment] 2023-06-27 17:12
@ranjCS can you provide the application logs when this issue happens? 
1. Is there a particular server/database with which this issue happens or it happens consistently for all/any server/db combination?
2. Is/Are the server/s connected before starting Schema compare or are they added from the blue "Connect" icon from this dialog?
3. Is/Are the server/s really connected?
4. Has this issue happened before or are you seeing it after an update as a regression?

**Comment by ranjCS** [comment] 2023-06-30 13:26
1- I have tried wit h3 servers and I can recreate the issue when I try to
edit eg. the database selected for compare
[image: image.png]
2- the servers are connected before compare
[image: image.png]

3- yes they are as I show in #2
4- I am not sure I understand the question. But this is my first time I use
the tool.

Regards
Ranj

**Comment by SakshiS-harma** [comment] 2023-07-06 18:59
Hi @ranjCS, just to clarify this issue only happens when editing/choosing a new connection in the schema compare dialog? Is it while updating server or database that this issue happens?
From what I am reading, it sounds like if the servers are already connected and selected along with populated dbs dropdown- the issue doesn't happen. It only happens when the db is changed?

Also, in the last reply, no images were posted, can you share the email on sakshis@microsoft.com

**Comment by ranjCS** [comment] 2023-07-07 07:50
Hi

I am resending my earlier mail, and yes I have attached screenshots. Please
let me know if you still can not see it. As I mention in item 1-, the issue
occurs when I try to update the database.

1- I have tried with 3 servers and I can recreate the issue when I try to
edit eg. the database selected for compare
[image: image.png]
2- the servers are connected before compare
[image: image.png]

3- yes they are as I show in #2
4- I am not sure I understand the question. But this is my first time I use
the tool.

Regards
Ranj

**Comment by SakshiS-harma** [comment] 2023-07-09 17:29
Do you mind sending this email to sakshis@microsoft.com . The images attached here aren't visible.

Thanks for confirming that the issue happens when database is updated. It is a helpful piece of information for further investigation.

**Comment by SakshiS-harma** [comment] 2023-07-19 17:24
Hi @ranjCS , just wanted to check, is it ok if I share a private built vsix with you for collecting some logs ? I have some additional logging turned on to figure out what the issue is. I haven't been able to repro the issue at my end and I am not sure why this might be happening. Let me know if it works, and I will share the schema compare vsix with you.

**Comment by ranjCS** [comment] 2023-07-20 08:38
I can not share any logs , it is company data

**Comment by SakshiS-harma** [comment] 2023-07-25 20:16
The logs are devoid of any server/database-specific information, making them safe for sharing.

**Comment by SakshiS-harma** [comment] 2023-07-28 18:15
Hi @ranjCS , I sent out an email to you with a custom VSIX for further investigation. Hope you hear back from you on this.

**Comment by SakshiS-harma** [comment] 2023-08-04 20:25
@ranjCS Just checking if you have any update/logs for me to dig deeper into the issue.

**Comment by SakshiS-harma** [comment] 2023-08-14 20:06
@ranjCS Gentle reminder that I need some more logs to continue working on this issue. If not, then unfortunately I will have to close this issue and you can open it once you have some logs for me to work on.

Thanks! Hoping to hear back from you.

**Comment by SakshiS-harma** [comment] 2023-08-16 18:36
@ranjCS I am closing this issue for now, since I haven't received any response from your end and I have no further data to work on this issue. Please re-open it if you have any new logs for me to work with.

**Closed by SakshiS-harma** 2023-08-16 18:36 UTC
Labels: Bug, Pri: 1, Area - Schema Compare, Triage: Done, Needs Logs
