### ISSUE TITLE
SQL Database project - allow schema compare from database into database project and enable generate script / apply

### ISSUE THREAD

**Issue by aisbergde** [microsoft/azuredatastudio#13935] opened 2021-01-09 20:08 UTC
**Is your feature request related to a problem? Please describe.**
I want to use schema compare from a database source into the project target (as I can do in SSDT) AND generate scripts / apply changes.
Currently, I can compare a database source with a dacpac target. For example with the target "d:\Repos\_test\DatabaseProjectWideWorldImporters-test\bin\Debug\DatabaseProjectWideWorldImporters-test.dacpac"
I see differences, but I can't generate script or apply the changes. These options are disabled.

**Describe the solution or feature you'd like**
I would like to do what I can do in SSDT: update a project from a database

**Describe alternatives you've considered**
SSDT works, or third party software

**Additional context**

**Comment by kisantia** [comment] 2021-01-11 18:06
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/13308

**Closed by kisantia** 2021-01-11 18:06 UTC
Labels: Area - SQL Project, Enhancement, Triage: Needed
