### ISSUE TITLE
The "Code or Text" link no longer showing up in between Cells

### ISSUE THREAD

**Issue by carofe82** [microsoft/azuredatastudio#11159] opened 2020-06-30 20:11 UTC
Issue Type: <b>Bug</b>

I am not sure if this is a feature request for something that was removed on purpose or it is a bug.

The Code or Text link is not longer showing up in between cells. This was a very useful feature as it was close in proximity to where you wanted to put your new cell, and you could do it in one click. It was frictionless.
I see it still shows up when you open a brand new notebook, but to add more cells you need to go to the top left corner of the cell prior to where you want to add the new cell, and click the "+" and then click on "Code" or on "text". It creates more friction for a task that used to be easier and quicker to do. A task that it is also done fairly frequently in notebooks.

Thank you.

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:03:19.036Z)
OS version: Darwin x64 19.5.0

**Comment by yualan** [comment] 2020-06-30 20:45
Hi Carlos, this feature was removed and replaced as an action at each cell. 

![image](https://user-images.githubusercontent.com/30873802/86175174-b673d180-bad7-11ea-937c-701b5588d940.png)

We received feedback in the past that the buttons between cells were leading to more redundant whitespace and users did not want the hovering visual effect as they run their mouse down the notebook. It is helpful to know that there are some users who did find the previous behavior useful.

**Comment by chlafreniere** [comment] 2020-07-06 16:07
Closing as by design.

**Closed by chlafreniere** 2020-07-06 16:07 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
