### ISSUE TITLE
Machine ID and session ID are no longer populated

### ISSUE THREAD

**Issue by alextercete** [Microsoft/azuredatastudio#1773] opened 2018-06-28 13:57 UTC
**SQL Operations Studio version:** 0.30.6

It seems like, as of #1299, `vscode.env.machineId` and `vscode.env.sessionId` are no longer populated. The snippet below shows the function that could be causing this behaviour.

https://github.com/Microsoft/sqlopsstudio/blob/0c58f09e59fcd2b9d5262ebca7f9c0214412e2d9/src/vs/platform/telemetry/common/telemetryService.ts#L79-L88

As a consequence, [Microsoft/vscode-extension-telemetry](https://github.com/Microsoft/vscode-extension-telemetry) doesn't include these properties when reporting events:

https://github.com/Microsoft/vscode-extension-telemetry/blob/8c6081a615987ee25e269a17d2124677492afda0/src/telemetryReporter.ts#L80-L84

I'm not sure whether or not this was intentional, but we'd like to use the machine ID, as extension authors, to aggregate usage stats.

**Comment by kevcunnane** [comment] 2018-06-28 16:42
This was done intentionally as part of the GDPR review process. At the moment we have no plans to bring these back. What I'd suggest is that you could leverage the code from app insights / VSCode that generates these IDs and use in your own telemetry pipeline. Basically extend this with a new ID that you could use instead of the previously built-in ones.

**Comment by kburtram** [comment] 2018-11-14 01:14
Closing as "By Design"

**Closed by kburtram** 2018-11-14 01:14 UTC
Labels: suggestion
