### ISSUE TITLE
Pyspark/Spark | Scala/Spark | R kernel notebooks in ADS failing

### ISSUE THREAD

**Issue by demoolya** [microsoft/azuredatastudio#13366] opened 2020-11-12 11:02 UTC
### In ADS 1.23 version 'Pyspark', 'Spark | Scala' and 'Spark | R' kernel notebooks are failing with the following error:

> The code failed because of a fatal error:
> 	Failed to change language to python.
> Exception details:
> 	"'Namespace' object has no attribute 'url'".
> 

> Some things to try:
> a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
> b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
> c) Restart the kernel.

### Installing ADS 1.24+ resolves this issue.
https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

### Affected ADS version:
Version: 1.23.0 (user setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by chlafreniere** [comment] 2020-11-17 00:55
Hi @demoolya did ADS ask you to reinstall any dependencies for insiders? @VasuBhog did we make any changes in this area recently?

**Comment by VasuBhog** [comment] 2020-11-17 02:42
Hi @demoolya can you tell me what sparkmagic version you are using via the package manager in ADS? I recommend downgrading as this seems to be an issue that is currently happening with sparkmagic version 0.17.0 (link below).
@chlafreniere this seems to be a bug within spark magic itself.

[SparkMagic Github Issue](https://github.com/jupyter-incubator/sparkmagic/issues/683)

**Comment by VasuBhog** [comment] 2020-11-17 03:00
Closing this issue as it's a duplicate of this [issue](https://github.com/microsoft/azuredatastudio/issues/13366). 
Please follow the issue here!

**Closed** 2020-11-17 03:00 UTC
Labels: Area - Notebooks, Bug, Triage: Done

**Comment by demoolya** [comment] 2020-11-17 04:30
Hello @VasuBhog, The sparkmagic version used was 0.17.0 and downgrading it to 0.16.0 addresses the issue. Thank you for the update. Will wait for the issue to be patched in.

**Comment by VasuBhog** [comment] 2020-11-18 21:40
@demoolya there is a new patch release for [sparkmagic 0.17.1](https://github.com/jupyter-incubator/sparkmagic/releases/tag/0.17.1) that now fixes the issue as well. You can go ahead and install this new version via the ADS package manager.
