### ISSUE TITLE
There isn't any Copy as Json or Copy as Html Table option 

### ISSUE THREAD

**Issue by mobsoftware** [microsoft/azuredatastudio#1065] opened 2018-04-04 19:17 UTC
There isn't any Copy as Json or Copy as Html Table option in the Results Pane

**Comment by alanrenmsft** [comment] 2023-06-09 20:56
close as dupe of https://github.com/microsoft/azuredatastudio/issues/168

**Closed by alanrenmsft** 2023-06-09 20:56 UTC
Labels: Area - Query Editor, Enhancement
