### ISSUE TITLE
pandas dependency not met on a new python for ADS installation

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#13388] opened 2020-11-13 00:39 UTC
**Steps to Reproduce:**
One a completely new machine with no previous ADS and ADS Python installed.
1. Install ADS and run the command 'Configure python for Notebook'
2. Kickoff the 'Create Azure Arc data controller' wizard. Complete all input screens information and finally hit 'deploy'
3. A new notebook opens and starts to run the notebook. However, this quickly runs into the following error:

**Actual:**
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-6ef7876bc4e6> in <module>
----> 1 import pandas,sys,os,json,html,getpass,time, tempfile
      2 pandas_version = pandas.__version__.split('.')
      3 pandas_major = int(pandas_version[0])
      4 pandas_minor = int(pandas_version[1])
      5 pandas_patch = int(pandas_version[2])

ModuleNotFoundError: No module named 'pandas'

**Actual:** There is a spurious information message stating:
`Following tools: Azure Data CLI were still not discovered. Please make sure that they are installed, running and discoverable`
**Expected:**  The notebook runs successfully and a new Azure Arc Data Controller gets deployed.

**ADS Version:**
_Version: 1.25.0-insider (user setup)
Commit: 8504221
Date: 2020-11-12T07:04:19.873Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042_

**Comment by chlafreniere** [comment] 2020-11-13 00:45
Dupe of #10886.

**Closed** 2020-11-13 00:45 UTC
Labels: Area - Azure Arc, Pri: 0
