### ISSUE TITLE
Main window displays only a blank screen

### ISSUE THREAD

**Issue by skinfrakkijm** [microsoft/azuredatastudio#8775] opened 2019-12-24 14:13 UTC
- Azure Data Studio Version:1.14.0

Steps to Reproduce:Start Azure Data Studio in menu or command line

New window appears. Blank white space. Menu items show, but does nothing. Need to revert to previous version if there is a link

**Comment by kburtram** [comment] 2019-12-26 17:06
@skinfrakkijm previous versions are available from https://github.com/microsoft/azuredatastudio/releases.  We'll take a look at this bug.  It didn't show up on CentOS during our release sign-off testing.

Do you happen to know if there are any errors in the "Tools->Developer Tools" Console?

**Comment by skinfrakkijm** [comment] 2019-12-26 17:08
Nothing functions. I can’t bring up the console

**Comment by MattGrdinic** [comment] 2019-12-26 18:34
Just wanted to say same here With Ubuntu 18.04.3. Blank white screen, console doesn't work and menu just has Exit option.

**Comment by nilact** [comment] 2019-12-27 11:47
This issue is still reproducible with 1.14.1 on Windows Server 2008 R2. I have not checked with other Windows OS version. At times, it depends on the theme selected, the blank screen appears and Azure Data Studio becomes unresponsive. After a few minutes, if you drag it by selecting the title bar, you have your editor back.

**Comment by dzsquared** [comment] 2019-12-28 00:01
Same here with the blank black screen, Windows 10 Pro, build 19536.1000.

It continued in 1.14.1 with all extensions uninstalled and I was able to cause the issue to start on command by launching an extension dev host (even on a simple extension such as SSMS keymap). 

When I rolled back to 1.13.1 the behavior stopped. Here are the dev logs -

![v1141extLog](https://user-images.githubusercontent.com/12227241/71536272-f19c0a80-28d2-11ea-83e6-5f0aa6165087.png)
![v1131extLog](https://user-images.githubusercontent.com/12227241/71536274-f19c0a80-28d2-11ea-870f-d2475c71630a.png)

**Comment by troglobytor** [comment] 2019-12-30 21:42
Same on Centos 7

**Comment by evaldez89** [comment] 2020-01-02 16:00
Same on Windows 7 Enterprise. Azure Data Studio Version:  1.14.1.

![image](https://user-images.githubusercontent.com/12959163/71675916-4ddcaf80-2d55-11ea-89cb-6fdd889b4d6e.png)

5 Seconds later:
![image](https://user-images.githubusercontent.com/12959163/71675946-5d5bf880-2d55-11ea-95fe-792df21e8019.png)

**Comment by anthonydresser** [comment] 2020-01-08 22:28
Can you try disabling gpu acceleration? Here's steps on how to do this.
https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by skinfrakkijm** [comment] 2020-01-08 22:47
Never had to before. Should work in the same manner as previous versions

**Comment by anthonydresser** [comment] 2020-01-08 23:01
We upgrade our electron version for security and performance reasons, which comes with underlying changes with platform level code that we don't have control over.

If it is a gpu acceleration issue then its an issue with the graphics drivers on the os you are running on.

**Comment by skinfrakkijm** [comment] 2020-01-08 23:02
Even across platforms?

**Comment by anthonydresser** [comment] 2020-01-08 23:10
I know the gpu-acceleration issue is an issue on every platform, but I'm not sure if you are having an issue gpu-acceleration or not, since this is a hardware compatibility issue, so its difficult to repro/debug.

**Comment by dzsquared** [comment] 2020-01-09 02:24
@anthonydresser I could have sworn I tested the GPU acceleration flag before I commented on this ticket, but I can't find my screenshots from that before so I'll give it a try tomorrow.

**Comment by nilact** [comment] 2020-01-09 05:38
> I know the gpu-acceleration issue is an issue on every platform, but I'm not sure if you are having an issue gpu-acceleration or not, since this is a hardware compatibility issue, so its difficult to repro/debug.

It is not gpu-accelaration issue, verified after setting the flag value to true and restarting the ADS. It is the same behavior, "blank screen".

**Comment by kburtram** [comment] 2020-01-16 21:45
@anthonydresser I see this upstream issue on vscode repo that looks possibly related https://github.com/microsoft/vscode/issues/86773.  Though it looks like their issue bot has closed all those issues without resolution.  

We've had numerous reports of this type of issue since 1.14.  Do you know if we bump Electron in that release?  Any ideas if there is an upstream fix pending, or if there is anything we can do?  I assuming downgrading Electron is not really practical at this point?

**Comment by kburtram** [comment] 2020-01-16 21:47
Oh, and I saw in one of the vscode issues that running in Windows 8 compatibility mode may workaround this issue on Windows platforms.  It would be good to confirm that if possible,

**Comment by kburtram** [comment] 2020-01-23 21:27
@anthonydresser I'm repro'ing this on CentOS 7 (not sure about the Windows repros, perhaps a different issue).

I see the below exception related to missing C runtime.  I know at one time we had to install a particular GCC version on the Linux build machines to ensure the binaries would work on both recent Ubuntu and CentOS distros.  

Do you know if this step to use a specific GCC was ported to the new build pipeline?

```
main 2020-01-22T09:49:03.286Z] Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at n (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/node_modules.asar/vscode-sqlite3/lib/sqlite3.js:1:77)
    at Module.o._compile (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at t.load (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:16:119)
    at e.load (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:13:586)
    at i (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:29:189)
    at Object.errorback (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:29:313)
    at e.triggerErrorback (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:13:955)
    at /home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:13:659
    at /home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:16:494
    at u (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:18:547)
    at ReadFileContext.callback (/home/karlb/Downloads/azuredatastudio-linux-x64/resources/app/out/vs/loader.js:18:634)
```

**Comment by kburtram** [comment] 2020-01-23 21:33
For reference here are the previous GCC steps from the build definition.  I didn't see equivalents in the yaml files from a cursory look.

```
sudo add-apt-repository http://us.archive.ubuntu.com/ubuntu/ && sudo apt-get update && sudo apt-get install -y --no-install-recommends pkg-config libsecret-1-dev libx11-dev libxkbfile-dev libkrb5-dev fakeroot libxss1 libgconf-2-4 libunwind8 rpm g++-4.8 xvfb
sudo rm /usr/bin/gcc
sudo rm /usr/bin/g++
sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
```

**Comment by kburtram** [comment] 2020-01-23 22:12
It looks like there are at least two distinct issues being tracked here.  The GCC issue on CentOS\RHEL should be straightforward to resolve.

**For anyone experiencing this issue on Windows or macOS**, please download the latest insiders build linked from the repo readme (https://github.com/microsoft/azuredatastudio).  We've updated to Electron 7 in the latest insiders build and are planning to release that in Feb.  It's possible we picked up an upstream fix.  Thanks!

**Comment by dzsquared** [comment] 2020-01-24 13:26
So far so good on the latest insiders build, thanks @kburtram and team 🎉

**Comment by hlattanzio** [comment] 2020-02-05 15:51
Been using the Insiders Build as well and I haven't had the issue there yet, while on the main build I am getting this issue constantly when I have more than one workspace open.  

So hopefully this next release will resolve it.  Thank you

**Comment by anthonydresser** [comment] 2020-02-22 22:48
Since it seems the electron update in insiders has fixed the issues for most I'll close this as resolved (even though we aren't 100% sure what the issue was). If this continues to happen on insiders feel free to open a new issue.

**Closed by anthonydresser** 2020-02-22 22:48 UTC
Labels: Area - Shell, Bug, Triage: Done
