### ISSUE TITLE
Name consistency for Arc data services

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12192] opened 2020-09-09 01:17 UTC
We need to align the product names everywhere - Deployment hub, dashboards etc.

"SQL managed instance - Azure Arc"
"PostgreSQL Hyperscale - Azure Arc"

The tiles on the Deployment hub should continue to show the suffix "(preview)" while we are still in preview, though.

**Comment by dnethi** [comment] 2020-09-09 17:19
update on PG, should be:

"PostgreSQL Hyperscale server group - Azure Arc".

**Comment by Charles-Gagnon** [comment] 2020-09-16 20:52
Closing as dupe of https://github.com/microsoft/azuredatastudio/issues/12148

**Closed by Charles-Gagnon** 2020-09-16 20:52 UTC
Labels: Area - Azure Arc, Bug, Pri: 2, Triage: Done
