### ISSUE TITLE
ADS takes way more time to connect to localDB than SMSS

### ISSUE THREAD

**Issue by gregveres** [microsoft/azuredatastudio#5462] opened 2019-05-11 00:14 UTC
Issue Type: <b>Performance Issue</b>

SMSS connects to Sql server LocalDB much, much faster than Azure Data Studio. It takes about 30+ seconds to connect to localDB with Azure Data Studio but with SMSS, it takes 1-3 seconds.

In fact, I have had enough time to write this bug report while ADS is trying to connect to a localDB in the background. It finally connected. I would say that was more like a minute to connect

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (2 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    9	    83	 13852	azuredatastudio main
    3	    74	  1984	   window (Issue Reporter)
    9	   185	  5484	   window (Azure Data Studio)
   34	   218	  3964	     extensionHost
    5	    94	  6928	   gpu-process
    0	    68	 14924	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by kburtram** [comment] 2019-05-11 00:56
@gregveres is this happening right after starting Azure Data Studio, or after its been running a while in the middle of session.  When ADS starts-up it needs to wait for background services to load before DB connections can be established.  Could you please retry the connection after seeing the "Starting service" message appear in the status bar?

**Comment by gregveres** [comment] 2019-05-11 01:56
You are correct. I started Azure Data Studio and I waited until it said that the services were started. It then connected to localDB quickly. 
I restarted Azure Data studio and tried to connect to localDB immediately. I then watched the status bar to see the message of starting ... and then started... come up. Once it had started, it connected to localDB a couple of seconds after that. 

So you are correct that it isn't connecting to localDB that is the problem, it is that starting the services must some times take up to a minute. This doesn't seem to happen on my instance installed on my mac, just on the instance running in a VM on windows.

**Comment by Charles-Gagnon** [comment] 2019-06-07 01:08
Closing this as things seem to be working as intended. The slow startup is not ideal - does your VM otherwise perform adequately and have enough resources assigned to it?

**Closed by Charles-Gagnon** 2019-06-07 01:08 UTC
Labels: Area: Connection, Area: Performance, Bug

**Comment by gregveres** [comment] 2019-06-07 01:47
> Closing this as things seem to be working as intended. The slow startup is not ideal - does your VM otherwise perform adequately and have enough resources assigned to it?

The VM has 8 GB of ram, 2 cores (on a 2 core machine) and runs off an SSD on a 2014 mac book pro. The startup of ADS seems slower than SMSS.
