### ISSUE TITLE
Msg 18456 - Token is expired

### ISSUE THREAD

**Issue by lipoteFR** [microsoft/azuredatastudio#14497] opened 2021-03-02 16:37 UTC
When i let my connection (MFA) opened for a while i have the message :
```
Msg 18456, Level 14, State 233, Line 1
Login failed for user '<token-identified principal>'. Token is expired.

```
Would it be possible to silent-refresh the token ?
Rgds
L

**Comment by Charles-Gagnon** [comment] 2021-03-02 17:59
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/13866 so I'm closing this one, thanks for the report!

**Closed by Charles-Gagnon** 2021-03-02 17:59 UTC
