### ISSUE TITLE
Can't add account

### ISSUE THREAD

**Issue by ZimbaaLSD** [microsoft/azuredatastudio#9386] opened 2020-02-28 07:18 UTC
Issue Type: <b>Bug</b>

Whenever I try to add a new account I get redirected to https://localhost:51352/signin?nonce={key}

I have nothing answering on this address. 

Clean install of Azure data studio.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aaomidi** [comment] 2020-02-28 08:48
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/9147

Please feel free to comment if it's not the same issue.

**Closed by aaomidi** 2020-02-28 08:48 UTC
Labels: Area - Azure, Bug, Triage: Done
