### ISSUE TITLE
Azure Data Studio taking longer time to connect to database/Server while executing query

### ISSUE THREAD

**Issue by ypradeep23** [microsoft/azuredatastudio#15230] opened 2021-04-24 03:48 UTC
ADS is taking long time start the Query execution, every time (not only first time).
As shown in below image... Its showing "Executing Query..." but time taking is "00:00" only, Also not getting "Started executing query".

Once its started execution... not taking time to complete. Not sure why its taking long to start execution.

Note: Data Connection is already there. Experiencing this not only 1st time execution, but later queries as well.;

![image](https://user-images.githubusercontent.com/2938274/115946228-7144e400-a4dd-11eb-85e4-0edb8d8591b9.png)

**Comment by mrjrdnthms** [comment] 2021-04-24 19:08
yep. its super annoying. team is not addressing it or responding to the issue when its posted.

see
[https://github.com/microsoft/azuredatastudio/issues/8965](https://github.com/microsoft/azuredatastudio/issues/8965)
#14853

**Comment by alanrenmsft** [comment] 2023-06-21 21:43
@ypradeep23 @mrjrdnthms could you please try the latest insiders build and see whether the issue is gone.

**Comment by cheenamalhotra** [comment] 2023-08-26 01:01
This issue has been fixed in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch).
Closing as resolved.

**Closed by cheenamalhotra** 2023-08-26 01:01 UTC
Labels: Bug, Area - Query Editor

**Comment by martinleo** [comment] 2024-09-17 10:50
This is not resolved, or broken again. I'm on 1.49.1
