### ISSUE TITLE
Unable to see saved connections in Restricted Mode

### ISSUE THREAD

**Issue by krishanth3** [microsoft/azuredatastudio#17535] opened 2021-10-29 06:19 UTC
Issue Type: <b>Bug</b>

I am unable see saved sql server connections nor able to establish a new connection. Even recent connections are not available. All places just show "Loading..." text. 

Azure Data Studio version: azuredatastudio 1.33.0 (6783aa6967e8c6d086b6f04e5fbf527659981389, 2021-10-26T17:28:15.782Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (15.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment] 2021-10-29 21:40
@choelterati @krishanth3 are you seeing any errors in the "Help->Toggle Developer Tools" Console?

**Comment by choelterati** [comment] 2021-10-29 22:41
I'm not running any extensions, but I am seeing errors in the dev tools console log. Attached is an image and a txt log of them all.

![image](https://user-images.githubusercontent.com/18740209/139508112-014ed218-a9ac-48ca-b656-846147373791.png)

[azure data studio console errors.txt](https://github.com/microsoft/azuredatastudio/files/7445289/azure.data.studio.console.errors.txt)

**Comment by kburtram** [comment] 2021-10-29 23:01
@choelterati thanks for the additional context.  This appears to be the same issue as https://github.com/microsoft/azuredatastudio/issues/17530.  You can try the workaround I suggested on that issue which may clear out some invalid state triggering this bug.  We're continuing to investigate and get an internal repro.  The callstack seems to be complaining about https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/connection/browser/connectionDialogService.ts#L308 but not clear why capabilities would be null there.

Please let us know if you can think of any other customization or configuration that may be helpful in determining what's going on.

**Comment by Charles-Gagnon** [comment] 2021-11-01 17:56
@kburtram I wonder if this is something to do with the Workspace Trust? The behavior shown in the screenshot (everything showing as loading) is what happens when you don't "trust" a workspace (since it doesn't load any extensions when that happens...)

![image](https://user-images.githubusercontent.com/28519865/139717609-8817340a-fdcb-43b1-9b5d-8eb37ede093a.png)

For people in the thread - do you see the "Restricted Mode is intended..." message at the top of the window?

**Comment by kburtram** [comment] 2021-11-01 21:45
I see in the original bug text that ADS is running in restricted mode, which would explain this behavior.  I've updated the title to reflect this.  We'll investigate how to improve this experience in Dec.

**Comment by kburtram** [comment] 2021-11-02 16:22
This issue should be resolved in today's insider build.  Please let us know if you still experience this problem with those builds.  We're discussing potentially pushing this change as a hotfix due to the confusion/inconvenience caused by this bug.

**Comment by goudstad** [comment] 2021-11-04 03:19
Please deploy the fix. I am having the same issue after upgrading to version 1.33.0. I don't see that I am in the restricted mode, however.

**Comment by Charles-Gagnon** [comment] 2021-11-04 14:18
@goudstad Could you try out the latest [insiders build](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) and see if you're still seeing the issue there?

**Comment by goudstad** [comment] 2021-11-05 16:15
I just upgraded to version 1.33.1.  and I am no longer seeing the issue.  Many thanks for fixing it.

**Comment by Charles-Gagnon** [comment] 2021-11-08 17:22
Closing this since the hotfix with the fix has been released, if anyone else is still encountering issues let us know!

**Closed by Charles-Gagnon** 2021-11-08 17:22 UTC
Labels: Bug, Area - Object Explorer, Area - Connection, Approved
