### ISSUE TITLE
Copy/Paste in October release results are pasted wrong order

### ISSUE THREAD

**Issue by csabhickory** [microsoft/azuredatastudio#8278] opened 2019-11-08 15:35 UTC
Issue Type: <b>Bug</b>

1. Run query with multiple columns results and an order by first column.
2.  Click in the result grid upper left corner to select the results.
3.  Right click, and copy 
4.  Paste results, note the results are out of order and the columns are in wrong order.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.3.5

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment] 2019-11-08 17:06
Duplicate of #8210

This has been fixed on the insiders build that you can install now - otherwise it'll be available in the next stable release.

**Closed by Charles-Gagnon** 2019-11-08 17:06 UTC
Labels: Bug

**Comment by winzig** [comment] 2019-11-14 21:23
@Charles-Gagnon This is a pretty major bug, would you expect a stable release fixing it prior to the next month's stable build?

**Comment by Charles-Gagnon** [comment] 2019-11-14 22:25
We'll be releasing a hotfix release for this - that should be out today or tomorrow.
