### ISSUE TITLE
Notebook: Orphan Jupyter processs left running

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3477] opened 2018-12-05 22:37 UTC
After testing opening and closing the same IPYNB file for about an hour I've found a pretty good number of processes still open. At the time of these screenshots there are no files open in Azure Data Studio at all. It is 2:36 PM and there are 22 Jupyter processes going back to 1:19 PM.
![image](https://user-images.githubusercontent.com/8250560/49548720-7b79cf80-f89b-11e8-8af5-f8b0fced6b85.png)

![image](https://user-images.githubusercontent.com/8250560/49548582-04dcd200-f89b-11e8-9a84-4e01bc35b926.png)

Azure Data Studio version: azuredatastudio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:37:09.298Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (3.87GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment] 2018-12-05 22:58
Good use case to fix for December - we should be disposing but clearly something is failing in the "kill Jupyter process" logic so we'll need to investigate.

**Comment by vickyharp** [comment] 2018-12-05 23:20
Do you need to look at my machine at all before I shut down Azure Data Studio today?

**Comment by kevcunnane** [comment] 2018-12-05 23:22
For this, no. I suspect we can repro with lots of open/close ops. I think this'll warrant some integration tests.

**Comment by kevcunnane** [comment] 2019-02-08 00:01
While we've improved on this we're still not perfect. Needs investigation in March

**Comment by YurongHe** [comment] 2019-04-10 22:57
I didn't repro it on recent master

**Comment by YurongHe** [comment] 2019-04-10 23:01
I reproed the issue by open notebook from opened folder.

**Comment by chlafreniere** [comment] 2019-04-11 00:44
@YurongHe I hope this is helpful. I was able to repro this happening in the following situations:

- Saving an untitled notebook (editor reloads, but before that, we don't shutdown Jupiter)
- Closing an untitled notebook (and clicking 'Don't Save')

**Comment by YurongHe** [comment] 2019-04-12 22:57
This is comments from Kevin for the fix.
Manager may receive server-level events independent of this. These will fail
In the future, we should reduce total number of Jupyter sessions. In particular it should be 1 per folder / 1 per workspace if files are inside an ADS workspace. In this case closing a single notebook shouldn't shut down the server
Correct disposal is to be handled either by the extension or our front end, not by this layer.
I think we should take a careful look at this path and decide how to proceed. Doing this right now is a bit dangerous and so let's chat about what scenarios we need to fix and look at alternatives.

**Comment by YurongHe** [comment] 2019-04-12 22:58
The issues are in two areas:
- File menu save untitled Python Notebook
- Save/unsave untitled Python Notebook by closing 
  The problem is tricky. check file \azuredatastudio\src\sql\workbench\api\node\extHostNotebook.ts
The first python notebook can shutdown Jupyter server correctly in handleNotebookClosed() manager.dispose().

After the first notebook is closed, if create the second untitled notebook, the notebookUri will be the same as the first one. So it wouldn't
createManager() in $getNotebookManager() since the uri is reused and the previous adapter is not deleted.

            let adapter = this.findManagerForUri(uriString);
	if (!adapter) {
		adapter = await this._withProvider(providerHandle, (provider) => {
			return this.createManager(provider, uri);
		});
	}

**Comment by chlafreniere** [comment] 2019-04-27 00:46
This should now be fixed. If there is a new corner case found, we will open a new issue, but for the majority of cases we should have a vast improvement here.

**Closed by chlafreniere** 2019-04-27 00:46 UTC
Labels: Area: Notebooks, Bug
