### ISSUE TITLE
UI not rendering

### ISSUE THREAD

**Issue by FredipusRex** [Microsoft/azuredatastudio#3741] opened 2019-01-15 16:09 UTC
I am trying to migrate from SQL Operations Studio to Azure Data Studio using Centos 7/Mate.

SQL Ops (v0.31.4) works fine - the Electron renderer displays the normal GUI and seems to be rendering the menus as well (as they aren't anti-aliased).

ADS (v1.3.8) only displays the window chrome (title bar, frame) and the menu bar (which appears to be Mate rendering, as it's anti-aliased). The rest of the interior is just a black rectangle.

I've looked at all the permissions of the two apps and they look largely identical (ADS has the execute flags enabled on libffmpeg.so, while SOS does not). Doing an ldd on both apps shows largely the same system libraries being used and the few app-specific libraries are being accessed from the appropriate directories.

When running ADS in --verbose mode, I do get the following error show up a few times:

Gtk-WARNING **: Theme parsing error: gtk-widgets.css:161:27: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

But that is the only error reported.

- Azure Data Studio Version: 
v1.3.8

Steps to Reproduce:
Install on CentOS Linux release 7.5.1804 (Core) 
MATE 1.16.2
Open app - a whole lot of black screen

**Comment by tomkv** [comment] 2019-02-02 00:34
Getting the same on Centos 7.6.1810:

```
/usr/share/azuredata…t/zone-node.js:2280 Loading "spdlog" failed
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function)	@	/usr/share/azuredata…t/zone-node.js:2280

/usr/share/azuredata…t/zone-node.js:2280 Detail:  Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:686:36)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:21:3)
    at Module.NodeScriptLoader._initNodeRequire.Module._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:718:45)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at nodeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:1671:32)
    at NodeScriptLoader.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:735:39)
    at OnlyOnceScriptLoader.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:581:32)
    at loadNextPath (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:1434:41)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:1442:25)
    at OnlyOnceScriptLoader.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:594:36)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:581:151
    at ReadFileContext.<anonymous> (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:748:25)
    at ZoneDelegate.invokeTask (/usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js:496:34)
    at ReadFileContext.ZoneTask.ZoneTask.cancelFn.invoke (/usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js:485:48)
    at ReadFileContext.data.args.(anonymous function) [as callback] (/usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js:1317:25)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function)	@	/usr/share/azuredata…t/zone-node.js:2280
```

Which sounds about right, as CentOS 7/RHEL 7 have only libstdc++ 6.0.19 (GLIBCXX_3.4.19).

**Comment by tomkv** [comment] 2019-02-02 12:55
@kburtram The required libstdc++.so.6 is present, but spdlog.node library is asking for versioned symbols, in versions not present in Centos/RHEL (i.e. the library is there, but the symbols in it are not).

```bash
$ nm spdlog.node | c++filt | grep GLIBCXX_3.4.2[0-9]
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@@GLIBCXX_3.4.21
                 U std::runtime_error::runtime_error(char const*)@@GLIBCXX_3.4.21
                 U std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@@GLIBCXX_3.4.21
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@@GLIBCXX_3.4.21
                 U std::__throw_out_of_range_fmt(char const*, ...)@@GLIBCXX_3.4.20

```

Did you change the build toolchain between 1.2.x and 1.3.x releases? That would explain it.

Wrt depencencies, the rpm claims it needs:
```bash
$ rpm -qp --requires azuredatastudio-linux-1.3.9.rpm |grep libstdc++
libstdc++.so.6()(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.10)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
```
which, given the above, is not really true. The dependency scanner is failing somewhere, it didn't catch the 3.4.18 and 19 symbols before either, but RHEL7 has those, so it didn't manifest.

**Comment by Cronan** [comment] 2019-02-04 08:49
I can confirm I see the same behaviour on CentOS Linux release 7.5.1804 (Core)

**Comment by kburtram** [comment] 2019-02-06 03:37
It looks like something changed on the Linux build machines since the 1.2.X releases.  We use the same machines for building a few products, so it's difficult to identify exactly what happened to update the C++ toolchain.

I'll see if I can setup some dedicated build machines to resolve this.  Here's an RPM with the latest `master` that I built from a newly imaged CentOS 7 build machine that should avoid this issue https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-1.4.4-1549422956.el7.x86_64.rpm.

**Comment by tomkv** [comment] 2019-02-06 19:43
Thanks, this rpm works.

Also, you might not need dedicated build machines for distributions with their specifics. RPM-based builds can be done with a tool called 'mock' (https://github.com/rpm-software-management/mock, some distributions like Ubuntu have it in repositories), which will do the build inside chroot (or container), so your real distribution won't contaminate the artefacts.

**Comment by kburtram** [comment] 2019-02-06 20:45
@tomkv thanks for the suggestion!  I'll take a look.  We need to get a bit better at how we build\test our Linux releases.

**Comment by kburtram** [comment] 2019-02-12 19:58
We updated our build lab to resolve this issue.  It looks like the Azure Pipelines Hosted Linux machines where updated which broke a step we use to install a specific gcc version.  The fix will be included in the Feb release.

**Closed by kburtram** 2019-02-12 19:58 UTC
Labels: bug, shell
