### ISSUE TITLE
SQL Notebooks slow

### ISSUE THREAD

**Issue by thesalientone** [microsoft/azuredatastudio#21291] opened 2022-11-22 16:07 UTC
We have written the needed data into your clipboard because 
Issue Type: <b>Performance Issue</b>

Sometimes after having a SQL notebook open for a while and running a lot of queries, the notebook starts to lag. The queries return fine, but I can type like 20 characters on my keyboard, and they won't show until like 20 seconds later

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.77GB (34.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   101	 92072	azuredatastudio main
    0	    34	 59224	   utility
    0	    85	 62668	   window (Issue Reporter)
    0	    77	 67452	   shared-process
    0	    61	107144	     ptyHost
    0	   125	 93968	   gpu-process
    0	   296	114060	   window (● Customer Reporting MSCert.ipynb - Azure Data Studio)
    0	   121	 26168	     extensionHost
    0	    23	 62888	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.2.1.6\MicrosoftSqlToolsCredentials.exe" --locale en --log-file c:\Users\stjenkins\AppData\Roaming\azuredatastudio\logs\20221121T133657\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical --autoflush-log
    0	     6	 85324	         console-window-host (Windows internal process)
    0	    85	107816	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.2.1.6\MicrosoftSqlToolsServiceLayer.exe" --locale en --log-file c:\Users\stjenkins\AppData\Roaming\azuredatastudio\logs\20221121T133657\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical --autoflush-log
    0	     6	 41912	         console-window-host (Windows internal process)
    0	    24	108352	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.2.1.6\SqlToolsResourceProviderService.exe" --locale en --log-file c:\Users\stjenkins\AppData\Roaming\azuredatastudio\logs\20221121T133657\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical --autoflush-log
    0	     6	 64320	         console-window-host (Windows internal process)
    0	    67	118004	       "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=26168
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none
it was too large to send. Please paste.

**Comment by chlafreniere** [comment] 2022-12-03 00:08
@lucyzhang929 can you help here?

**Comment by lucyzhang929** [comment] 2023-03-03 20:39
Duplicate of notebook perf issue: https://github.com/microsoft/azuredatastudio/issues/17623

**Closed by lucyzhang929** 2023-03-03 20:39 UTC
Labels: Bug, Area - Notebooks, Triage: Done
