### ISSUE TITLE
Enable renaming of existing connections

### ISSUE THREAD

**Issue by SvenAelterman** [Microsoft/azuredatastudio#4158] opened 2019-02-24 17:01 UTC
Issue Type: <b>Feature Request</b>

If you make a typo when creating a connection, or you don't rename it and later decide the default naming convention isn't suitable, there's no way to rename the connection. You have to delete it and recreate it.
I would like to be able to just right-click and Rename.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kburtram** [comment] 2019-02-25 21:53
@SvenAelterman this looks like a duplicate of https://github.com/Microsoft/azuredatastudio/issues/3963.  Please leave any additional related info on that issue.  Thanks!

**Closed by kburtram** 2019-02-25 21:53 UTC
Labels: connection, feature request
