### ISSUE TITLE
Disconnnect from database on file save

### ISSUE THREAD

**Issue by solexecution** [microsoft/azuredatastudio#8516] opened 2019-12-01 20:33 UTC
Issue Type: <b>Bug</b>

connection is terminated on save of new query file 

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (2.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|1.3.9
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment] 2019-12-03 00:35
Thanks for reporting this issue.  This appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/8333.  Please add any additional comments to that issue.

**Closed by kburtram** 2019-12-03 00:35 UTC
Labels: Bug, Triage: Needed
