### ISSUE TITLE
Error: Position is outside of file line range (Parameter: 'line')

### ISSUE THREAD

**Issue by aborremans** [microsoft/azuredatastudio#20503] opened 2022-08-30 17:48 UTC
Issue Type: <b>Bug</b>

After updating to ADS 1.39.0 I am getting the following error in certain query windows.

```
Execution failed due to an unexpected error: 
	Position is outside of file line range (Parameter 'line')
```

To fix the issue, I have to close the entire window in order for queries to start running again. This seems to happen occur after writing insert statements. This is also new to 1.39.0 as I have not run into it previously. Problem seems sporadic and I am unable to reproduce consistently. 

To the best of my ability, here are the steps I am taking when this seems to occur:

- Open ADS and navigate to file explorer
- Open a .sql file from folder and connect to database
- Write an insert statment using the following syntax:

```
INSERT INTO dbo.Table
VALUES 
(integer1,integer2,'string1','string2')
```
- Attempt to execute insert. Hit error.
- Any query you attempt to run will then hit same error
- You need to open a new query window to solve problem.

https://user-images.githubusercontent.com/13876614/187506829-ce3fc82c-4a96-4855-a575-0b493792836d.mp4

Azure Data Studio version: azuredatastudio 1.39.0 (9fdb2161d49b4d4ab6798809faa042a898ca2eae, 2022-08-20T01:46:47.606Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (19.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.4
import|Mic|1.5.0
sql-migration|Mic|1.0.4

</details>

**Comment by Charles-Gagnon** [comment] 2022-08-30 17:59
@aborremans Could you try installing the latest insiders build and see if you still experience the issue there? 

https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

We have a hotfix coming out for a different issue, but I'm wondering if the root cause is the same.

**Comment by Charles-Gagnon** [comment] 2022-08-30 18:04
Also please follow the instructions above to enable logging so we can see if there's anything useful there. 

You can start by looking yourself to see if the application logs caught anything (like a callstack) that might help us track this down. To do this run the `Developer: Open Logs folder` command, then go up a directory to the `logs` directory and zip up all the timestamp-named folders you see there and attach them here. (you can also try searching yourself for the error message `Position is outside of file line range` and only include the log files that contain that message if you want to keep the size smaller).

**Comment by aborremans** [comment] 2022-08-30 18:07
Attached are my zipped logs. I also just finished installing the insider build I am not readily reproducing in the insider build.

[LogFolders.zip](https://github.com/microsoft/azuredatastudio/files/9455464/LogFolders.zip)

**Comment by Charles-Gagnon** [comment] 2022-08-30 18:14
Perfect, thanks! The hotfix should be out shortly, but in the meantime if you're OK using the insiders build that will help determine if this is still an issue. 

Unfortunately your logs didn't provide anything useful - for some reason the Tools Service logs aren't even being created. Is there something about your environment that might be preventing those from being created?

**Comment by aborremans** [comment] 2022-08-30 18:22
@Charles-Gagnon I'm not sure why my Tool Service logs wouldn't be created. I'm not running anything special or weird other than updating ADS yesterday.

I am now readily able to reproduce in 1.39.0 with a specific insert command. I'd be more than happy to make another video or show if you if you need. I'm not able to find anything logged with this error in the Developer Logs folder in 1.39.0. I am attaching my console log from the above instructions from when I reproduce.

I have yet to reproduce in the insiders build. I'm cool using that build for a few days until the hotfix comes out. Let me know if you need anything or if there is anything else you need.

[console.txt](https://github.com/microsoft/azuredatastudio/files/9455533/console.txt)

**Comment by aborremans** [comment] 2022-08-30 18:31
Here is a video of the exact steps I am taking to reproduce. I am connecting to an Azure SQL DB.

https://user-images.githubusercontent.com/13876614/187515465-535600c3-ef9c-45bc-91a1-5aee584b22d2.mp4

Create Table Syntax
```
CREATE TABLE [qry].[Query](
	[QueryId] [smallint] IDENTITY(1,1) NOT NULL,
	[ParentId] [int] NULL,
	[EntityTypeId] [int] NOT NULL,
	[Label] [varchar](200) NOT NULL,
	[Description] [varchar](4000) NOT NULL,
	[SQLQuery] [varchar](max) NULL,
	[LayoutJSON] [nvarchar](max) NULL,
	[DisplayOrder] [smallint] NULL,
	[QueryTypeId] [tinyint] NULL,
	[CanEdit] [bit] NOT NULL,
	[CanSprayEvent] [bit] NOT NULL,
	[CanSprayRecurring] [bit] NOT NULL,
	[IsEnabled] [bit] NOT NULL,
	[GenerateLayout] [bit] NULL,
	[CanMap] [bit] NOT NULL,
	[GeoColumn] [varchar](50) NULL,
	[StyleId] [int] NULL,
	[DataQTypeId] [int] NULL,
	[DataMask] [nvarchar](max) NULL,
	[Links] [varchar](200) NULL,
	[OldQueryId] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [qry].[Query] ADD  CONSTRAINT [PK__Query] PRIMARY KEY CLUSTERED 
(
	[QueryId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
```

Insert Query
```
INSERT INTO qry.Query
VALUES 
(536,2020,'Query Name','Query Description',NULL,NULL,1,NULL,0,0,0,1,1,0,NULL,NULL,NULL,NULL,'Asset[Account]',NULL)
```

**Comment by Charles-Gagnon** [comment] 2022-08-30 21:21
@aborremans I was still not able to repro it. We just released the hotfix for the other issue though, so I'm going to close this for now and if you still see it even after updating then let us know and we can investigate more!

**Closed by Charles-Gagnon** 2022-08-30 21:21 UTC
Labels: Bug, Area - Query Editor, Triage: Needed, Needs Logs

**Comment by aborremans** [comment] 2022-08-30 21:32
Thanks for looking into it. I'll let you know if I run into it after the hotfix.
