### ISSUE TITLE
queries may get saved broken to history 

### ISSUE THREAD

**Issue by trdgit1** [microsoft/azuredatastudio#14364] opened 2021-02-19 11:11 UTC
Issue Type: <b>Bug</b>

![изображение_2021-02-19_141019](https://user-images.githubusercontent.com/11870372/108497227-32679780-72bc-11eb-8cae-300cdd467227.png)

Azure Data Studio version: azuredatastudio 1.25.3 (b277eafb8f5328ea26c6edfddd1999292ac27937, 2021-02-09T23:10:35.151Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.48GB (5.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.6.0
import|Mic|1.2.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-02-22 17:41
This looks to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/11865 so I'm going to close it - let me know if that doesn't seem to be the case here.

**Closed by Charles-Gagnon** 2021-02-22 17:41 UTC
Labels: Area - Query History, Bug, Triage: Needed
