### ISSUE TITLE
Query action bar replicate icon

### ISSUE THREAD

**Issue by EwertonJordao** [Microsoft/azuredatastudio#3026] opened 2018-10-28 03:34 UTC
Issue Type: <b>Bug</b>

In action bar, icons replicate above titles for 3 or 2 times, in cancel or run button i see 3 icons.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-3520M APU with Radeon(tm) HD Graphics (4 x 1597)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.48GB (8.60GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

![image](https://user-images.githubusercontent.com/12378570/47611710-75e1cc00-da49-11e8-8e0d-dd74d9e19339.png)

**Comment by kburtram** [comment] 2018-10-29 18:40
@alanrenmsft is this a high-contrast issue that you recently fixed?

**Comment by alanrenmsft** [comment] 2018-10-29 18:47
@kburtram, nope, but i will take care of it.

**Comment by alanrenmsft** [comment] 2018-10-31 18:11
dupe of #2719

**Closed by alanrenmsft** 2018-10-31 18:11 UTC
Labels: bug, query editor
