### ISSUE TITLE
SQL server connections collapse when editor tabs close

### ISSUE THREAD

**Issue by aakims** [microsoft/azuredatastudio#23244] opened 2023-05-30 15:58 UTC
- Azure Data Studio Version: 1.44.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Create a new connection with the following parameters:

- Connection type: MS SQL Server
- Authentication type: Windows Authentication
- Database: *NOT default* (connections to the server (i.e., not a specific database) does not have this issue)
- Encrypt: True
- Trust server certificate: True
- Server group: default or otherwise (doesn't affect the issue)

2. Expand the new connection to view the list of tables or views.
3. Open a query editor for anything. e.g., select top 1000, script as create
4. Close the editor tab 
5. See that the connection object tree that was expanded automatically collapses when the editor closes
6. As noted above, the connection made to the server (default) does not have the same issue. This issue began when I updated ADS with the most recent release. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment] 2023-06-03 08:35
Hi @aakims 

Please check your settings.json, if this setting is enabled:
`"serverTree.useAsyncServerTree": true`

The issue is known and has been addressed in latest insiders build. You may disable this option to resolve the error in stable version, as Async server tree feature is in preview in current stable release.

**Comment by cheenamalhotra** [comment] 2023-06-03 08:37
Closing as issue is resolved in latest insiders build.

**Closed by cheenamalhotra** 2023-06-03 08:37 UTC
Labels: Bug, Area - Object Explorer, Triage: Needed
