### ISSUE TITLE
Intelisense stops working

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/azuredatastudio#13500] opened 2020-11-20 14:30 UTC
Issue Type: <b>Bug</b>

I leave ADS open for long periods of time. Usually I leave it open overnight. Next day when I pick up working again all editors and the server browser are disconnected. No biggie. Although annoying I just reconnect everything.
All is good but Intellisense. It is never able to refresh. No matter how many times I ask it to do so. 
The work around is to close ADS and open it again. Intellisense comes back alive. 
So to reproduce it just leave ADS open overnight and try to use Intellisense the next day. 

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|28.00GB (21.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0
schema-compare|Mic|1.7.0

</details>

**Comment by Charles-Gagnon** [comment] 2020-11-20 16:41
Closing this as a duplicate of other such issues such as https://github.com/microsoft/azuredatastudio/issues/9424

**Closed by Charles-Gagnon** 2020-11-20 16:41 UTC
