### ISSUE TITLE
Context menu > New File leads to broken editor and non closing tab

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23765] opened 2023-07-11 06:10 UTC
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Right click on empty ADS shell and select 'New File'
2. A new editor opens, Select a language - choose 'Sql'
3. Notice that header resembles SQL editor, but there is no editor, neither this tab can be closed.

With ADS v1.44.1 (stable) - 'New File' leads to opening New SQL Editor tab implicitly.

![BrokenEditor](https://github.com/microsoft/azuredatastudio/assets/13396919/6559b5ac-24e3-47d7-81d7-35183ddfa6f3)

**Comment by Charles-Gagnon** [comment] 2023-07-11 21:46
Closing this as dupe of https://github.com/microsoft/azuredatastudio/issues/17135 - this isn't a recent regression

**Closed by Charles-Gagnon** 2023-07-11 21:46 UTC
Labels: Bug, Area - Query Editor, Area - Shell, Triage: Done
