### ISSUE TITLE
Service Broker components doesn't appear

### ISSUE THREAD

**Issue by alfeuduran** [microsoft/azuredatastudio#757] opened 2018-02-22 23:52 UTC
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:17:29.202Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Enable Service Broker, create messages, contracts and queues
2. In the object explorer viewer this components up here doesn't appear. 
<img width="855" alt="captura de tela 2018-02-22 as 20 51 41" src="https://user-images.githubusercontent.com/36578943/36570730-3976611c-1812-11e8-9891-4faf4df39e75.png">

**Comment by kburtram** [comment] 2021-09-10 18:52
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/2831.

**Closed by kburtram** 2021-09-10 18:52 UTC
Labels: Area - Object Explorer, Enhancement
