### ISSUE TITLE
First query hangs

### ISSUE THREAD

**Issue by KevinLeeBuchan** [microsoft/azuredatastudio#10793] opened 2020-06-08 17:01 UTC
Issue Type: <b>Bug</b>

This does not happen consistently, but it is often.

I will open a new tab.  If it opens with an active connection, I will click "change connection" or disconnect/connect.  I then dbl-click a recent connection from the list.

From there, I change the selected database and enter my query.  When I run the query, usually but not always by clicking "run", the display changes to the "running" mode and hangs.  The UI continues to respond, so the process doesn't seem to be hung, but results never complete and the query cannot be canceled.  My solution is to close the tool, relaunch and try again.

If I can be told how to enable logging to capture what's happening, I'd love to provide that.

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (3.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0

</details>

**Comment by KevinLeeBuchan** [comment] 2020-06-08 19:38
[20200608T124306.zip](https://github.com/microsoft/azuredatastudio/files/4748150/20200608T124306.zip)

**Comment by kburtram** [comment] 2020-06-08 20:30
@KevinLeeBuchan thanks for attaching the logs!  Unfortunately, I didn't see anything problematic captured there.  I'll try to the repro sets a few times to see if I can encounter the same problem.

**Comment by KevinLeeBuchan** [comment] 2020-06-08 22:05
I think the log may have been overwritten when I restarted.
I'll collect them again, when I have the issue again.  Likely tomorrow.

**Comment by Charles-Gagnon** [comment] 2020-06-08 22:19
@KevinLeeBuchan There should be a separate folder for each session of ADS - so if you go up a directory you should see something like this

![image](https://user-images.githubusercontent.com/28519865/84085903-73708380-a99b-11ea-8f6c-fa0be93e1fe5.png)

You can use the timestamps to determine which one is the correct log file.

**Comment by KevinLeeBuchan** [comment] 2020-06-08 22:28
Looks like the timestamps are in UTC?

I think this is the right folder and I saw something that looked like an uncaught exception in the logs.
[20200608T124058.zip](https://github.com/microsoft/azuredatastudio/files/4748903/20200608T124058.zip)

**Comment by KevinLeeBuchan** [comment] 2020-06-22 17:10
Here are updated logs where it happened again.
[20200619T204620.zip](https://github.com/microsoft/azuredatastudio/files/4814615/20200619T204620.zip)

**Comment by kburtram** [comment] 2020-07-02 16:15
@KevinLeeBuchan I couldn't see anything that I could use to locate a root cause from the logs.  I only saw the below errors, which unfortunately are too generic to identify what went wrong.  I'll continue to try to get an internal repro.

```
[2020-06-22 12:51:21.415] [renderer1] [error] An unknown error occurred. Please consult the log for more details.

[2020-06-08 12:43:00.998] [renderer1] [error] Object has been destroyed: Error: Object has been destroyed
    at WebContents../lib/browser/api/web-contents.js.WebContents.send (electron/js2c/browser_init.js:3634:15)
    at IpcMain.<anonymous> (C:\Program Files\Azure Data Studio\resources\app\out\vs\code\electron-main\main.js:511:593)
```

**Comment by KevinLeeBuchan** [comment] 2020-07-02 19:18
Thank you for your efforts.

At the time I reported the issue, it was maddenly common.  Now it doesn't
even happen daily.  Perhaps it was more OS related and patches largely
resolved it.

Since there is not a lot of detail logged, I will not add more info until I
am able to reliably reproduce the issue.
______________________________
Kevin Buchan

**Comment by julielerman** [comment] 2021-05-18 15:03
Oddly, I have the opposite problem. When I execute a query (local server) and then attempt to re-execute, it hangs. I have to create a new query window and paste the query into there and then it's fine. (Or open of SSMS) . Looking for existing issue to read up on. This is all I found so far. (using latest 1.28.0)

**Comment by cheenamalhotra** [comment] 2022-08-26 02:41
I would like to close the issue in regards to #7440 that is already tracking the same subject across ADS.
Please feel free to open a new issue if there is a reproducible user scenario.

**Closed by cheenamalhotra** 2022-08-26 02:41 UTC
Labels: Bug, Area - Connection, Triage: Done
