### ISSUE TITLE
unable to connect to azure sql server using alias

### ISSUE THREAD

**Issue by nirajchahar** [microsoft/azuredatastudio#17165] opened 2021-09-25 03:48 UTC
this is wierd situation, i have been using aliases for azure sql server for long time now.

but this time when i created a alias i cant connect to server, i tried with Azure AD auth and sql auth, if i use the actual server name it works fine.

actual_server_name.database.windows.net works fine
alias_server_name.database.windows.net does not work

i am sure i am using the right alias name, to validate i have verified using Get-AzSqlServerDnsAlias

**Comment by nirajchahar** [comment] 2021-09-25 03:50
error message when trying to connect using alias:
--------------------------------------------
TITLE: Connect to Server
------------------------------

Cannot connect to alias_server_name.database.windows.net.

------------------------------
ADDITIONAL INFORMATION:

Cannot open Failover Group "alias_server_name.database.windows.net" requested by the login. The login failed. (Microsoft SQL Server, Error: 40971)

For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&EvtSrc=MSSQLServer&EvtID=40971&LinkId=20476

------------------------------
BUTTONS:

OK
------------------------------

**Comment by cheenamalhotra** [comment] 2022-08-25 07:52
Closing as duplicate of #71 enhancement request.
Would recommending upvoting the same to help us prioritize the issue!

**Closed by cheenamalhotra** 2022-08-25 07:52 UTC
Labels: Area - Connection, Enhancement, Triage: Done
