### ISSUE TITLE
Intellisense - Nested Comments must keep green 

### ISSUE THREAD

**Issue by SaschaProdware** [microsoft/azuredatastudio#22980] opened 2023-05-05 11:33 UTC
Issue Type: <b>Bug</b>

SQL: 

select 'test' as Test

/*
test 

/* Test */

select 'this is a nested commented and won''t be executed but it is not green' as Test

*/

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

**Comment by SaschaProdware** [comment] 2023-05-05 11:34
![image](https://user-images.githubusercontent.com/87972931/236447270-7b1923ea-6b8f-4ea4-b72b-67fe074b1c63.png)

**Comment by SaschaProdware** [comment] 2023-05-05 11:34
![image](https://user-images.githubusercontent.com/87972931/236447447-3a5031c0-af7f-4677-9fe8-124563001c04.png)

**Comment by SaschaProdware** [comment] 2023-05-05 11:36
![image](https://user-images.githubusercontent.com/87972931/236447747-832cd97a-6342-44fe-bb9d-c845604a3b32.png)

**Comment by Charles-Gagnon** [comment] 2023-05-05 16:38
Duplicate of https://github.com/microsoft/azuredatastudio/issues/19205

**Comment by kburtram** [comment] 2023-05-06 03:18
Closing to track with duplicate issue.

**Closed by kburtram** 2023-05-06 03:18 UTC
