### ISSUE TITLE
Pressing "Run" to execute SQL query has several seconds delay

### ISSUE THREAD

**Issue by scholtes** [microsoft/azuredatastudio#4217] opened 2019-02-27 15:51 UTC
Issue Type: <b>Bug</b>

1. Open a connection to a database in an Azure SQL Server  
2. Open a new query and write a simple query
3. Execute it by pressing "run", and then modify the query a little bit  
4. Repeat step 3  several times

Note that during step 4, you may notice that the UI does nothing for several seconds even though the "total execution time" is on the order of milliseconds.

I know this is not due to an expensive query, SQL Server performance issues, or bad network because: 
1. The queries are simple, e.g. `select 1, 2, 3`
2. The Azure SQL server is not under heavy load
3. The issue is not observed outside of Azure Data Studio (e.g., the same queries with the same connection works without delay in SSMS, and works without delay in code via ODBC drivers) 

Possibly related issues: #3627 #3904 #3868 

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (21.19GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ashwinimohan** [comment] 2021-08-20 10:25
Any update on this issue? It has been a long time since notified and we are still waiting for the fix.
It's really annoying to wait for very first query (after connecting to the server) to take more than 1 - 2 mins.

**Comment by betorolim1** [comment] 2022-11-08 14:39
I have the same problem here! Any update?

**Comment by kwenzel1** [comment] 2023-02-08 15:12
Still an issue...  any update?

**Comment by SDragon42** [comment] 2023-02-14 22:20
I have been experiencing it too, though my wait time could be up to 30 seconds.

I've actually been able to try to run the query, wait for a few seconds, load up SSMS, connect to the server, run the query there, and get a result before Data Studio will run the query.

It doesn't happen consistently, and I have yet to see a pattern for it's cause.

**Comment by boyukbas** [comment] 2023-03-20 10:12
4+ years, wow!
Maybe it is even worse now as mentioned in the previous comment.

**Comment by erinstellato-ms** [comment] 2023-03-20 20:49
@boyukbas @SDragon42 @kwenzel1 @betorolim1 @ashwinimohan Wanted to confirm that you all are still experiencing the behavior on the latest version of ADS (1.41.2).  If not, please upgrade to the latest stable release and re-test, and also consider trying the latest Insider build.  We have been working to address connectivity issues in Azure Data Studio as a whole, which may indirectly affect Query Editor.  If the problem is still occurring, then any logs or errors that you can share would be helpful.

**Comment by alanrenmsft** [comment] 2023-06-21 19:39
similar to https://github.com/microsoft/azuredatastudio/issues/23145, issue has been fixed in latest insiders build, please give it a try. let me know if it still reproes.

**Comment by erinstellato-ms** [comment] 2023-07-03 23:13
@boyukbas following up to see if you've had a chance to re-try this in the latest Insiders build (1.45)...thanks!

**Comment by boyukbas** [comment] 2023-07-04 02:21
Sorry for late response.
I don't have my PC with me but I will definitely try it and write the result here when I return from vacation.
Thanks for your time.

**Comment by boyukbas** [comment] 2023-07-12 16:02
Hi @alanrenmsft @erinstellato-ms 
I tried it just now with **1.46.0-insider (system setup)**
![image](https://github.com/microsoft/azuredatastudio/assets/7711024/e0dbff22-ac66-4429-8b12-fd5e2023722e)
I had 20 seconds to take this screenshot.
![image](https://github.com/microsoft/azuredatastudio/assets/7711024/b6030b2e-22bd-4af1-b787-a03337810389)
The query I wrote was very simple. It takes only few miliseconds on SSMS.

Repro steps:
Open ADS 1.46.0-insider
Open a new tab
Connect to a server (I am connecting a DB in the Cloud)
Write a simple query like "Select top 10 * from dbo.Company" and immediately execute it

Result:
In the active tab, Run button is disabled, Cancel button is enabled
At the bottom bar you can see "Executing query..." and duration will stay still as 00:00:00
I took few screenshots at that moment
After 20 seconds (it can vary), results will be there and you can see row count. For my case, duration was 00:00:00 because the query was very simple.

Same thing happened again when I added another query right after the first query and run it immediately.
But when I run it again without a change, it returns the result immediately.
Same thing happened again when I added another query right after the second query and run it immediately.
But when I run it again without a change, it returns the result immediately.

Here is my guess:
Intellisense might be blocking the main thread and because of that, query waits until intellisense gets table names or whatever. I don't have any proof.

That's all I observed about this issue.

Thanks for both of your time

**Comment by alanrenmsft** [comment] 2023-07-12 16:05
@boyukbas did you turn on the parallel message processing setting? if not, could you please give it a try?

![image](https://github.com/microsoft/azuredatastudio/assets/13777222/dff4b8c9-28d7-48a3-9700-5128bdd7a4dd)

**Comment by boyukbas** [comment] 2023-07-12 16:23
@alanrenmsft Tried it few times but the result is the same. After trying 10-20 times, it started happening less but it still happens.
I opened a new tab, wrote the query quickly and hit F5.
Once it took 5 seconds, once it took 13 seconds. But the query duration is 00:00:00

**Comment by alanrenmsft** [comment] 2023-07-12 16:25
@boyukbas did you restart ADS after making the setting change?

**Comment by boyukbas** [comment] 2023-07-12 16:27
yes of course

**Comment by alanrenmsft** [comment] 2023-07-12 16:59
@cheenamalhotra could you please follow up on this?

**Comment by cheenamalhotra** [comment] 2023-07-12 19:17
I believe this might be related with #23400 - which is still under investigation.
@boyukbas Can you provide us with MSSQL logs?

**Comment by boyukbas** [comment] 2023-07-13 07:26
Yes, it is the same issue. I'll do the suggested action when I have time.
Thanks

**Comment by cheenamalhotra** [comment] 2023-08-26 00:22
This issue has been addressed in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), proceeding to close as resolved.

**Closed by cheenamalhotra** 2023-08-26 00:22 UTC
Labels: Bug, Area - Query Editor, Needs Logs
