### ISSUE TITLE
No way to output to text like in SSMS

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#3011] opened 2018-10-26 12:27 UTC
- Azure Data Studio Version: 1.1.3
Commit 2c007115f77427a7ff7af47ad6916fccf111ea11
Date 2018-10-17T21:21:46.083Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Run a script that generates nothing but text, for example, if you have a scaffolding script that generates SQL by using information_schema system views.

PROBLEM:
The text that your print out is shown in the message pane with **no** newlines/tabs, it all appears on one massively long line.

In SSMS on the toolbar you could choose to output to text, when you run the script it would then output with all newlines/tabs etc... intact thus you could then copy and paste that output.

I prefer the styling of ADS over SSMS and try to use it all the time but there are still a lot of things that that SSMS does that there is no equivalent in ADS.

**Comment by kburtram** [comment] 2020-03-23 17:41
@abist this is the issue we're using to track the "Output to Text" feature in ADS.

**Comment by kburtram** [comment] 2021-09-10 18:56
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/52.  Please add any additional context to that issue if applicable.  Thanks!

**Closed by kburtram** 2021-09-10 18:56 UTC
Labels: Area - Query Editor, Enhancement, Triage: Postponed
