### ISSUE TITLE
Import Wizard imports negative decimal values as nulls

### ISSUE THREAD

**Issue by armchairdeity** [microsoft/azuredatastudio#2602] opened 2018-09-16 21:32 UTC
[sqlops.zip](https://github.com/Microsoft/sqlopsstudio/files/2387036/sqlops.zip)

Issue Type: <b>Bug</b>

1. Connect to a SQL Server using sqlops
2. Right-click on a DB and do "Import Wizard"
3. Import the attached data file (detach and unzip, obvs)
4. Run a `SELECT * FROM TABLE` against your import table
5. Observe Nulls

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:30:28.766Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by aasimkhan30** [comment] 2020-09-21 21:01
I have test this out and cannot reproduce the bug in 1.0. Closing it now.

**Closed** 2020-09-21 21:02 UTC
Labels: Area - SQL Import, Bug
