### ISSUE TITLE
Moving folder deletes subfolders from target folder

### ISSUE THREAD

**Issue by ststeedman** [microsoft/azuredatastudio#20675] opened 2022-09-27 10:35 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

Issue Type: <b>Bug</b>

When moving a folder in ADS, if the target folder has subfolders (and files?), these will all be hard-deleted with no chance of undo.

[I was able to restore my files from OneDrive]

If the same is done in File Explorer, the folders/files remain, (and individual options are given to overwrite or make new duplicate files).

I'm not expecting that much but would simply like any files/folders that were already there to remain or be overwritten.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0
sql-prompt|Red|0.2.10

</details>

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aasimkhan30** [comment] 2022-09-28 01:58
@ststeedman, I have tried this on my end but I could not reproduce it. Can you please tell me the exact steps that you have performed to see this bug?

**Comment by ststeedman** [comment] 2022-09-28 08:35
OK, so let us suppose I have a folder X with a subfolder Y with a subfolder Z, and another folder A with a subfolder Y with a subfolder C:

X\Y\Z
A\Y\C

If I move the folder Y into A, subfolder C will disappear.  Undo returns the folder to X but C is still missing.

To test what happens to files, I put a file in each subfolder named after the complete path, i.e. x.txt, xy.txt, xyz.txt etc. - 6 files in total.

As with the subfolders, the previous files contained with Y have now disappeared.  Performing the same action in Windows File Explorer achieves the correct result.

So it looks like Y in A is being treated as an object that is being entirely replaced by moving Y from X To A by the version in X.

If I wanted to achieve this, I could delete the folder Y in X and then move the folder Y in A to X.

**Comment by aasimkhan30** [comment] 2022-09-28 17:55
We do show a prompt before  moving the folder Y (in folder X) to folder A
<img width="304" alt="image" src="https://user-images.githubusercontent.com/6816294/192854034-c4b8b06c-1945-44e9-b5b2-0f73e00db550.png">

This prompt does state that moving would replace the original Y folder and the action is irreversible. Please correct me if I am wrong but this is consistent with what your example is, right?

**Comment by ststeedman** [comment] 2022-09-29 10:33
Yes, it is, and I am aware of that prompt.  Whilst I do not want to get into a discussion about the wording of this prompt, I would argue that "replacing a folder" means that any  identically named files that exist in the folder/subfolders will be overwritten, and those that exist and are NOT in the folder being copied will remain.  This is how it works, as I am sure you are aware, in File Explorer.

So, to me, it looks lazy that the functionality of moving files has only been partially implemented.  I can't think of a situation where I would want moving a folder to work as it currently does in ADS.  Thus, I have to remind myself to not do it, and instead use File Explorer.

**Comment by Charles-Gagnon** [comment] 2022-09-29 16:41
Closing this as it's upstream behavior we inherited from VS Code. We try to avoid changing their behavior as much as possible to reduce friction for users moving between the apps. 

There's a couple issues/enhancement requests for changing this but it doesn't look like it's gotten any traction - you can try opening another issue though to see if anyone there will respond now. 

https://github.com/microsoft/vscode/issues/146137
https://github.com/microsoft/vscode/issues/143028

**Closed by Charles-Gagnon** 2022-09-29 16:41 UTC
Labels: Bug, Area - Shell, Triage: Needed
