### ISSUE TITLE
Cannot connect to Azure SQL using AAD

### ISSUE THREAD

**Issue by shand-obs** [microsoft/azuredatastudio#5952] opened 2019-06-10 15:20 UTC
Issue Type: <b>Bug</b>

Authentication type: Azure Active Directory - Universal with MFA support
Database: master
Selected an AAD account and AAD tenant.

Fails to connect with the following error:

Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.

![image](https://user-images.githubusercontent.com/21341273/59205843-f7ade200-8b60-11e9-954d-8336cc96e3a0.png)

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (21.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1

</details>

**Comment by Charles-Gagnon** [comment] 2019-06-10 15:38
Closing this as a dupe of #4085

**Closed by Charles-Gagnon** 2019-06-10 15:38 UTC
