### ISSUE TITLE
Unable to log in to Azure / Linked accounts on Windows

### ISSUE THREAD

**Issue by isamllr** [Microsoft/azuredatastudio#545] opened 2018-01-25 13:26 UTC
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Open Linked accounts
2. Use Copy & Open button, paste code --> Login in Browser (tried Chrome and Edge) listed as successful
3. Message in Studio: **Error adding account. Error: Entry not found in cache.**

I am using my internal Azure account, using multiple tenants & subscriptions. _When using another account with an MSDN subscription everything works fine, even though also here I got multiple tenants and access to multiple subscriptions.

C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  SimpleKeybinding  for  grid.toggleResultPane
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296
C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  SimpleKeybinding  for  grid.toggleMessagePane
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296
C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296 [createInstance] First service dependency of RecentConnectionActionsProvider at position 1 conflicts with 3 static arguments
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296
C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296 [91m[main 2:18:54 PM][0m Error while adding account: Error: Entry not found in cache.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296
C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296 [91m[main 2:21:51 PM][0m Error while adding account: Error: Entry not found in cache.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296
error @ workbench.main.js:169
(anonymous) @ workbench.main.js:86162
notifyError @ workbench.main.js:13650
enter @ workbench.main.js:13342
_run @ workbench.main.js:13509
_error @ workbench.main.js:13482
error @ workbench.main.js:13184
ZoneDelegate.invoke @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388
Zone.run @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138
(anonymous) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:870
ZoneDelegate.invokeTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
drainMicroTaskQueue @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:594
ZoneTask.invokeTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:499
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:484
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

Also appearing randomly:
[91m[main 2:32:13 PM][0m Error while adding account: Error: Polling_Request_Cancelled
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296
error @ workbench.main.js:169
(anonymous) @ workbench.main.js:86162
notifyError @ workbench.main.js:13650
enter @ workbench.main.js:13342
_run @ workbench.main.js:13509
_error @ workbench.main.js:13482
error @ workbench.main.js:13184
ZoneDelegate.invoke @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388
Zone.run @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138
(anonymous) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:870
ZoneDelegate.invokeTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
drainMicroTaskQueue @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:594
ZoneTask.invokeTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:499
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:484
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296 [91m[main 2:32:44 PM][0m Error while adding account: Error: Entry not found in cache.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2296
error @ workbench.main.js:169
(anonymous) @ workbench.main.js:86162
notifyError @ workbench.main.js:13650
enter @ workbench.main.js:13342
_run @ workbench.main.js:13509
_error @ workbench.main.js:13482
error @ workbench.main.js:13184
ZoneDelegate.invoke @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388
Zone.run @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138
(anonymous) @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:870
ZoneDelegate.invokeTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
drainMicroTaskQueue @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:594
ZoneTask.invokeTask @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:499
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:484
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

**Comment by kburtram** [comment] 2018-12-03 21:06
Closing as a duplicate of #3298 since this looks like the same underlying issue.  There is a fix pending in PR #3391.  Please let me know if that fix doesn't resolve this problem.

**Closed by kburtram** 2018-12-03 21:06 UTC
Labels: azure, bug

**Comment by 2axDeveloper** [comment] 2019-02-13 20:10
I'm still getting this error in Azure Data Studio as of 2/11/19
