### ISSUE TITLE
Spinning forever "Loading Account"

### ISSUE THREAD

**Issue by jxc517** [microsoft/azuredatastudio#20818] opened 2022-10-12 14:58 UTC
Issue Type: <b>Bug</b>

Unable to connect to any profile. When trying to click on Accounts it keeps spinning "Loading Accoutns" for hours but nothing shows up. Checked default browser settings and everything but nothing pops-up for MFA or anything.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/78751982/195377950-3e509568-db75-44e1-9b23-beeb3e71090a.png">

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
arc|Mic|1.6.0
azcli|Mic|1.6.0
azure-cosmosdb-ads-extension|Mic|0.1.3
dacpac|Mic|1.10.1
import|Mic|1.5.0
kusto|Mic|0.5.4
profiler|Mic|0.11.0

</details>

**Comment by cheenamalhotra** [comment] 2022-12-02 22:42
Hi @jxc517 

This might be a behavior when ADS starts and extensions are not yet activated.
Reopening this pane should resolve this issue. We will look into enhancing this experience, so window gets refreshed when extensions are done activating.

**Comment by cheenamalhotra** [comment] 2022-12-08 19:09
Closing as duplicate of #20606 - please follow the same for progress on this issue.

**Closed by cheenamalhotra** 2022-12-08 19:09 UTC
Labels: Bug, Area - Azure, Triage: Done, Duplicate

**Comment by mdiianni** [comment] 2023-03-03 13:54
this is happening using 

```
Version: 1.41.2
Commit: 0f0960d0e774e1ce903b79378addff96117c27a6
Date: 2023-02-08T20:15:24.215Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.3.0
