### ISSUE TITLE
Kernel dropdown selecting two options at the same time

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#23863] opened 2023-07-13 20:19 UTC
Version: 1.45.0-rc1 (user setup)
Commit: 90fccfda34a4aed6bee24a454f5b92f29884cdb6
Date: 2023-07-12T03:59:45.962Z
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23493

1. Create a new notebook
2. Change kernel 

<img width="118" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/34872381/d5b1a3f8-cb9a-4c4a-a59f-f49795cca611">

**Comment by MaddyDev** [comment] 2023-07-13 21:32
FYI This is not a regression, am seeing the same behavior in last release:
![image](https://github.com/microsoft/azuredatastudio/assets/12754347/2f88465f-27e6-402f-a93b-5872599ae175)

**Comment by corivera** [comment] 2023-09-12 20:10
Closing since issue no longer repros in latest insiders.

**Closed by corivera** 2023-09-12 20:10 UTC
Labels: Bug, Area - Notebooks, Triage: Done
