### ISSUE TITLE
Edit Data: On edit data the table name isn't shown anywhere

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#9006] opened 2020-01-31 17:12 UTC
- Azure Data Studio Version:

Steps to Reproduce:

1. Open any table and right click to launch edit data.

Expected: 
It should open table in edit mode and show the table name on the title-header.
Current behavior:
It opens the table in edit mode but doesn't show the table name info anywhere. It shows the query instead of the table-name now.

**Comment by MaddyDev** [comment] 2020-03-12 19:37
I see this issue again.

**Comment by kburtram** [comment] 2020-03-12 20:29
This looks like the same underlying issue as https://github.com/microsoft/azuredatastudio/issues/9058.  And should be fixed in today's release/1.16 build.

**Comment by kburtram** [comment] 2020-03-13 20:14
Closing as duplicate of #9058 which is fixed in today's build

**Closed by kburtram** 2020-03-13 20:14 UTC
Labels: Approved, Area - Edit Data, Bug, Triage: Done
