### ISSUE TITLE
Navigating away from .ipynb file and lost all changes :(

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3944] opened 2019-02-06 23:10 UTC
- Azure Data Studio Version:
1.4.4 insider

Steps to Reproduce:

1. Open 1.ipynb file
2. Make some edits
3. Click another 2.ipynb file to view
4. 1.ipynb file no long in tabs above
5. Click 1.ipynb file
6. all changes made to file in step 1 gone

**Comment by amthomas46** [comment] 2019-02-06 23:13
Wait it gets better. I closed it and opened it several times. Then gave up and started over, making modifications similar to that in step #1. Then, try to save the file (doesn't work). Then, navigate to a .sql file. Return to 1.ipynb and all the old edits are there!

**Comment by kevcunnane** [comment] 2019-02-07 00:19
@amthomas46 I'm seeing an issue where when tabbing we lose the scroll position. Is this what you mean? I'm struggling to reproduce where on editing you lose visibility on the file, since as soon as you edit this should mark file as dirty and not close it.

Note there is a related issue from what you mentioned:
- Ctrl+S isn't saving right now. @rajmusuku  is working on that and it's tracked in another bug. Workaround is to use the "Save" button in the notebook

**Comment by amthomas46** [comment] 2019-02-07 00:22
No, this was something else, it was super weird. Let me see if I can repro it

**Comment by kevcunnane** [comment] 2019-02-07 19:09
OK please let me know, looking forward to trying to solve as many of these as possible (you should see a bunch of your bugs getting closed)

**Comment by kevcunnane** [comment] 2019-03-06 01:34
I'm going to close, please reopen once we have a repro

**Closed by kevcunnane** 2019-03-06 01:34 UTC
Labels: bug, notebooks
