### ISSUE TITLE
Can't connect to SQL Server using "Windows Authentication" from Linux

### ISSUE THREAD

**Issue by RealLucasMeyer** [microsoft/azuredatastudio#3781] opened 2019-01-19 02:42 UTC
Issue Type: <b>Bug</b>

setspn -L SERVERNAME

Result:
```
Registered ServicePrincipalNames for CN=SERVERNAME,DC=l1,DC=l2,DC=company,DC=com:
        MSSQLSvc/l1.l2.company.com`
```

After running `kinit`, `klist` returns:

```
01/18/2019 18:22:22  01/19/2019 04:22:22  krbtgt/L1.L2.COMPANY.COM@L1.L2.COMPANY.COM
	renew until 01/19/2019 18:22:18
01/18/2019 18:23:26  01/19/2019 04:22:22  MSSQLSvc/servername.l1.l2.company.com@L1.L2.COMPANY.COM
	renew until 01/19/2019 18:22:18
```

Using the `odbc` package in R works with Trusted_Authentication=Yes

However, using `Windows Authentication` in Azure Data Studio fails with error:

```
System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (Message stream modified).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 520
ClientConnectionId:83092e2b-91fc-4526-bc4f-615bbec7b001
```

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:47:37.469Z)
OS version: Linux x64 4.20.3-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3613)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.21GB (22.34GB free)|
|Process Argv|/opt/azuredatastudio/azuredatastudio --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by moxixuan** [comment] 2019-02-08 08:24
https://docs.microsoft.com/zh-cn/sql/azure-data-studio/enable-kerberos?view=sql-server-ver15

**Comment by Charles-Gagnon** [comment] 2020-01-16 17:01
I'm going to close this one as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8713, please follow that for any updates.

In that issue I suggested a possible fix that has helped resolve the issue for some users (https://github.com/microsoft/azuredatastudio/issues/447#issuecomment-546407390) - please try that and let us know in the other issue if that still doesn't resolve your issue.

**Closed by Charles-Gagnon** 2020-01-16 17:01 UTC
Labels: Area - Connection, Bug
