### ISSUE TITLE
Query Plan breaks when tab is switched

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8065] opened 2019-10-28 20:02 UTC
Steps to Reproduce:

1. Run any query.
2. Click on `Explain` for `Query Plan`. The  `Query Plan` appears.
3. Go to `Results` tab and click on the  `Query Plan` link to open the XML file.
4. Switch back to `Query Plan` tab.

Expected -  `Query Plan` appears normally.
Actual - The lines connecting the different nodes are now missing.

![Capture](https://user-images.githubusercontent.com/6411451/67713557-4084fc80-f983-11e9-960c-8b9a9d67c8a4.JPG)

**Comment by kburtram** [comment] 2019-10-28 22:29
Duplicate of https://github.com/microsoft/azuredatastudio/issues/4755

**Closed by kburtram** 2019-10-28 22:29 UTC
Labels: Area - Query Plan, Bug, Triage: Needed
