### ISSUE TITLE
Html Table Tag in Saved Notebook Causes Error When Opened

### ISSUE THREAD

**Issue by netsec4u** [microsoft/azuredatastudio#10093] opened 2020-04-20 22:44 UTC
Azure Data Studio version 1.16.1

Steps to reproduce:

1. Create a new notebook
2. Add Text
3. Within text block, add "<table><tr><th>Test</th></tr></table>"
4. Save  and close notebook
5. Open notebook and the error "Could not display contents: Cannot read property 'children' of undefined"

The Kernel is stuck in the "Loading kernels" state.  Any code blocks in the notebook will not execute.

**Comment by chlafreniere** [comment] 2020-04-20 23:08
Thanks for reporting this issue, and apologies for this.

This is a duplicate of #9830. Will be fixed in the upcoming April release.

**Closed by chlafreniere** 2020-04-20 23:08 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
