### ISSUE TITLE
Custom widget show details does not have item details.

### ISSUE THREAD

**Issue by scottwojack** [Microsoft/azuredatastudio#3200] opened 2018-11-13 13:13 UTC
I have the latest update for Data Studio

1. Click on show details in widget.

The insights panel Item details is always empty.  The only exception to this is the first time show details is used after starting Azure data studio.  After closing Data studio and clicking show details it works, but only one time for all widgets.

Thanks

**Comment by alanrenmsft** [comment] 2018-11-15 00:10
@scottwojack  Could you please provide some screenshots?

**Comment by scottwojack** [comment] 2018-11-15 07:53
Hi,

Attached is a screen shoot of a empty details pane when there should be details.

Thanks
Scott

**Comment by abist** [comment] 2019-04-29 18:23
Duplicate of https://github.com/Microsoft/azuredatastudio/issues/4684, and hence tracking there. Closing this issue.

**Closed by abist** 2019-04-29 18:23 UTC
Labels: Area: Dashboard, Area: Extensibility
