### ISSUE TITLE
Named connections get overwritten in ADS

### ISSUE THREAD

**Issue by sergten** [microsoft/azuredatastudio#19307] opened 2022-05-09 15:58 UTC
Wnen I connect to a server (SQL Server or Oracle, doesn’t matter) with the same server name and same login name, but give it different names – then the first connection gets overwritten by the second one.

Example:

1.	Create the first connection:
![image](https://user-images.githubusercontent.com/1912050/167449278-32e3d0e8-96fb-4c5b-b115-729f4cda847b.png)

2.	Watch it appear in the list of Servers:
![image](https://user-images.githubusercontent.com/1912050/167449318-3f8f439e-521f-47d5-a7b4-b7d8838f853d.png)

3.	Create the second connection with the same server and username:
![image](https://user-images.githubusercontent.com/1912050/167449365-c3e74756-7efa-466d-ab43-640b59c80585.png)
 
4.	Upon connection, watch the first connection replaced by the second one:
![image](https://user-images.githubusercontent.com/1912050/167449394-50f5c61e-bf92-432d-9c4b-f2b6356f4216.png)
 
The example above uses an Oracle connection type, but same behavior can be observed for SQL Server connections.

It appears that the name (marked as optional) doesn’t make it into the connection identification.

**Comment by alanrenmsft** [comment] 2022-05-10 20:56
Hi @sergten I think this is by design, you have to make sure the name is unique or empty, otherwise it will be overwritten. please let us know if you have any questions.

**Comment by Charles-Gagnon** [comment] 2022-05-10 21:27
This doesn't seem like behavior we want - the bug @sergten is describing is that we are essentially ignoring the name when saving connections. So despite them being given unique names the new one (which should be unique because it was given a unique name) it's overwriting the original one.

We should allow having multiple connections that share connection information as long as the Name given is unique.

**Comment by alanrenmsft** [comment] 2022-05-10 21:34
sorry, Overlooked the description, the names used are actually different.

**Comment by cheenamalhotra** [comment] 2022-11-07 23:34
This request will require significant changes to the way connection profile identity is created.
I'd like to re-valuate how is this is a useful request from practical point of view?

@sergten 
Can you elaborate why this would be a useful feature for an end user? Why would you want to create multiple connections with differing names for the same server/db connection?

**Comment by sergten** [comment] 2022-11-08 00:32
Namely for transaction management. I may have uncommitted changes in one connection that I don't want to see from another - that was my main use case. I can think of other use cases, such as for SQL Server I can have a DAC connection, for Oracle - SYSDBA.

**Comment by sergten** [comment] 2022-11-08 00:53
But not super-critical, feel free to de-prioritize.

**Comment by cheenamalhotra** [comment] 2022-11-08 02:37
Fyi, you don't need a new connection in server tree to not view uncommitted results btw, since every new query opens a different new connection with database underneath.

If you want to query uncommitted data, just open a new query window from the same server tree connection, and that should work for you!

**Comment by sergten** [comment] 2022-11-08 02:41
I know. I was mocking with Oracle, whose provider doesn't allow running arbitrary scripts, so I was messing with the tree itself. Like I said - not critical. It's just mathematically incorrect to give a connection a name and watch it being applied to something else.

**Comment by artemsaveliev** [comment] 2023-01-31 23:28
To us the usefulness is in running multiple mysql connections. In ms sql, port number is/can be part of server name. Not so in mysql - so when trying to run multiple containers with mysql running, it's not possible to store several connections.

Only possible workaround (when using localhost) is to start using multiple loopback addresses (127.0.0.1, 2, 3 etc) to disambiguate the ports.

**Comment by cheenamalhotra** [comment] 2023-01-31 23:57
Hi @artemsaveliev 

We're considering fixing this behavior in upcoming release. 
Similar issue we're tracking: #17438

**Comment by cheenamalhotra** [comment] 2023-03-28 20:56
_We're almost ready, moving milestone to May to add additional time to test with the insiders build._

**Comment by cheenamalhotra** [comment] 2023-04-24 22:18
Support is now available in latest insiders with https://github.com/microsoft/azuredatastudio/pull/22735 merged, closing as resolved.

**Comment by cheenamalhotra** [comment] 2023-05-18 00:21
Reopening as the PR was reverted, will be targeted for next release.

**Comment by cheenamalhotra** [comment] 2023-06-21 21:11
The support is now available in latest insiders, and will be available in next release.

Oracle and other providers don't yet support the new design, but will be able to adopt this feature as needed. 
[Contribution points](https://github.com/microsoft/azuredatastudio/wiki/Contribution-points) are updated.

**Closed by cheenamalhotra** 2023-06-21 21:11 UTC
Labels: Area - Connection, Enhancement, Triage: Done
