### ISSUE TITLE
Filtering Tables and Stored Procedures

### ISSUE THREAD

**Issue by chrisrendall** [microsoft/azuredatastudio#2724] opened 2018-09-30 03:47 UTC
- Azure Data Studio Version: 1.0.0

Steps to Reproduce: With Servers selected on the left navigation, navigate to the Tables or Stored Procedures for a database, and when right-clicking there is no option to filter the items in the folder like in the SSMS client.  The database for our ERP system has a lot of tables and stored procedures and I need a way to filter to make the list of items smaller.  Ideally I could save the filter so I would have a quick way to get the smaller list of items.

**Comment by philosophicles** [comment] 2019-03-19 22:19
I think this is also a near-duplicate for #3331? 

The unique aspect to this request is: "Ideally I could save the filter so I would have a quick way to get the smaller list of items." Which is also an awesome idea IMO, but possibly a separate feature to just implementing some kind of filtering like SSMS does. This is the kind of feature that would actually encourage people (me) from SSMS to ADS!

**Comment by A-damW** [comment] 2019-09-19 21:05
Yes please...

**Comment by Charles-Gagnon** [comment] 2020-07-22 22:59
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as cleanup

**Closed by Charles-Gagnon** 2020-07-22 22:59 UTC
Labels: Area - Data Explorer, Enhancement
