### ISSUE TITLE
Go to Definition is readonly - is this expected

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#5707] opened 2019-05-29 00:20 UTC
- Azure Data Studio Version:
Version: 1.8.0-insider (system setup)
Commit: 3e8f25d8642c9560f6296d97bde2b164aedf25df
Date: 2019-05-27T07:46:13.508Z
VS Code 1.33.1
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

From todays insiders build and dev build I am noticing that Go to definition is opening a readonly editor where as Peek definition is still editable. This is a new behavior. Is this expected? 

Peek
![image](https://user-images.githubusercontent.com/46980425/58520528-1a0d2c00-816d-11e9-9492-08b8cf2943d0.png)

Go To
![image](https://user-images.githubusercontent.com/46980425/58520551-35783700-816d-11e9-81ac-809e1d76f008.png)

**Comment by Charles-Gagnon** [comment] 2019-05-29 00:44
This is likely a dupe of #5684 which is from something in the latest VSCode merge. I'm investigating currently - although maybe @anthonydresser has an idea of what's wrong.

(It appears to be something with how editor input is assigned, the Editor code will set it to readonly if the Input is anything but UntitledEditorInput but with the latest changes the input is a FileEditorInput. I'm not sure what this was like before though so it's possible this is expected and something else to blame).

**Closed by Charles-Gagnon** 2019-05-29 00:44 UTC
Labels: Area: Language Service, Area: Query Editor, Bug

**Comment by anthonydresser** [comment] 2019-05-29 00:50
Probably an option we need to add when we open the editor.
