### ISSUE TITLE
Add Secondary Side Bar like in VS Code

### ISSUE THREAD

**Issue by patamu1223** [microsoft/azuredatastudio#20901] opened 2022-10-20 20:31 UTC
Since Azure Data Studio is based on VS Code and VS Code has the Secondary Side Bar, could we get that functionality added to Azure Data Studio? That way I could get rid of the fairly useless tabs.

**Comment by Charles-Gagnon** [comment] 2022-10-20 20:43
We will eventually! We merge in changes from VS Code on a regular basis - but we lag behind to keep things more stable and give us time to make sure the features are working as intended. 

I'm going to close this since it's not something we'll be actively working on as a specific feature, so just keep an eye on our releases to see when we bring in this feature from VS Code. (No ETA at the moment unfortunately, sometimes the merge takes longer than anticipated)

**Closed by Charles-Gagnon** 2022-10-20 20:43 UTC

**Comment by Charles-Gagnon** [comment] 2022-10-20 21:04
Actually, I have good news - it looks like this was included in the merge we just brought in!

![image](https://user-images.githubusercontent.com/28519865/197057656-3c3bed4a-9f27-42d3-b67e-dd20566203f5.png)

So if things go according to plan you should see this feature in the next major release in November.
