### ISSUE TITLE
Connections and Notebook activity bar icons not visible/incorrect in some color themes

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20420] opened 2022-08-19 17:29 UTC
Quiet Light/Solarized Light

![image](https://user-images.githubusercontent.com/28519865/185674630-673efd66-e8c9-47e5-9e38-846f3cc911e7.png)

High Contrast (they're dimmer than the other ones)

![image](https://user-images.githubusercontent.com/28519865/185674784-9e601e61-226a-4972-a425-95eb00b407c7.png)

**Comment by chlafreniere** [comment] 2022-08-19 18:47
Dupe of #11930, which I've moved into October.

**Closed by chlafreniere** 2022-08-19 18:47 UTC
Labels: Bug, Area - Shell, Area - Notebooks, Triage: Needed
