### ISSUE TITLE
Notebook Deployment Feature does not terminate CMD.EXE,MSSQLCTL.EXE,PYTHON.EXE post Deployment/ADS Closure.

### ISSUE THREAD

**Issue by pradm** [Microsoft/azuredatastudio#4799] opened 2019-04-02 16:46 UTC
Issue Type: <b>Bug</b>

Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

I am noticing that ADS post application closure doesn’t terminate the respective child applications which it had launched for Notebook cluster deployment feature.
Ideally once the execution is complete the process should terminate itself and should not be resident in memory. It looks like due to some reason the process never got terminated.

1.	On 28th March I was using ADS Notebook Deployment feature to deploy an Aris Cluster.
2.	It looks like ADS initiates a CMD.EXE and posts a MSSQLCTL.exe command for cluster deployments and administration.
3.	Today Morning I had closed the ADS application, but it looks like the child CMD.EXE -> MSSQLCTL.EXE -> PYTHON.EXE never gets terminated.
4.	The Python.exe is holding a lock on C:\Users\pradm\.mssqlctl\logs\mssqlctl.log & against the MSSQLCTL.LOG which it had generated
5.	Why I am so sure that the CMD.EXE could be launched by ADS -> The command line for CMD.EXE launch is the complete Cluster Creation command that by default doesn’t happen some application has called CMD.EXE with these input parameters.

Is this a Known issue which is getting fixed in future ADS builds. Attaching the ADS logs for your further review.

C:\Users\pradm\AppData\Roaming\azuredatastudio\logs\20190330T024928
C:\Users\pradm\AppData\Roaming\azuredatastudio\logs\20190330T024928\exthost1\
C:\Users\pradm\AppData\Roaming\azuredatastudio\logs\20190330T024928\exthost1\output_logging_20190330T024932

•	main.log does not show any indications of application closure exceptions
•	sharedprocess.log does not show any indications of application closure exceptions
•	exthost.log does not show any indications of application closure exceptions
•	3-Jupyter Notebooks.log does not show any indications of application closure exceptions

![adsbdc1](https://user-images.githubusercontent.com/27516588/55420571-fa0a2380-5594-11e9-8a2d-3baec9e59efd.png)
![adsbdc2 png](https://user-images.githubusercontent.com/27516588/55420576-fd051400-5594-11e9-92a5-a7c26d95f14e.jpg)

[20190330T024928.zip](https://github.com/Microsoft/azuredatastudio/files/3035050/20190330T024928.zip)

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (12 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (4.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.37.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment] 2019-04-24 21:37
This is a dupe of #3477.

**Closed by chlafreniere** 2019-04-24 21:37 UTC
Labels: Area: Notebooks, Bug
