### ISSUE TITLE
Dropping a database starts an "Update database" task

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24190] opened 2023-08-22 20:12 UTC
The text here doesn't seem correct

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/2035ac34-aa93-44c0-afba-93102ac5466c)

**Comment by corivera** [comment] 2023-08-22 20:13
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/24188

**Closed by corivera** 2023-08-22 20:13 UTC
Labels: Bug, Area - Backup Restore, Triage: Needed
