### ISSUE TITLE
Create my own schedule?

### ISSUE THREAD

**Issue by dabasys** [microsoft/azuredatastudio#8899] opened 2020-01-16 14:12 UTC
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:
When creating a new job, and i want to put it on a schedule - would love to be able to create my own schedule, instead of using those in the "pick a schedule" list - they dont have good descriptions either, so I cant for example see one with 1 minute interval.

**Comment by Charles-Gagnon** [comment] 2020-01-16 15:51
Thanks for the feedback! I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8873 though - please follow that for any updates.

**Closed by Charles-Gagnon** 2020-01-16 15:51 UTC
Labels: Area - SQL Agent, Enhancement, Triage: Needed
