### ISSUE TITLE
Results progressively slower

### ISSUE THREAD

**Issue by nige6** [microsoft/azuredatastudio#5099] opened 2019-04-18 09:37 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

when executing sql statements (e.g. debugging a SP, or even repeatedly executing tsql) the results window progressively gets slower and slower to populate

initially execution time and results appearing match 
but over a short period of time the results take over a minute to appear, even for a execution time of under a second

e.g.
the message window could state 00:00:00.020
the results will not appear for over a minute, and when they do will be empty [i.e. not headers or rows, just "RESULTS" heading]
then eventually blank rows
and finally several minutes later data will appear

MicrosoftSqlToolsServiceLayer was using over 2gb in this particular case, and I have raised a separate issue () for high memory usage, but not sure if this is related but do always have several tabs open in ADS

I have been experiencing this issue for quite some time (months), across 3 different pcs each with ram from 8 or 16gb.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.37.0

</details>

**Comment by nige6** [comment] 2019-04-18 10:11
Perhaps some kind of memory leak ?
Closing ADS and running a just a few select queries, I'm now in the position of a select statement showing execution time of 2.845 seconds, wiht 6 rows
Results pane, has headers, 6 rows but all empty
and MicrosoftSqlToolsServiceLayer over 5Gb and growing

**Comment by anthonydresser** [comment] 2019-06-19 04:26
looks like this might be a dupe of #5249

**Comment by kburtram** [comment] 2019-06-19 16:37
Closing as duplicate.

**Closed by kburtram** 2019-06-19 16:37 UTC
Labels: Area: Performance, Area: Query Editor, Bug
