### ISSUE TITLE
v1.11 broke intellisense, again

### ISSUE THREAD

**Issue by jakodev** [microsoft/azuredatastudio#7161] opened 2019-09-11 07:58 UTC
Hi guys, la latest version (v1.11) broke the intellisense. I had to downgrade to v1.10.
Please be aware about this functionality, is the one of most important... imho

thank you and good job,
J.

**Comment by Charles-Gagnon** [comment] 2019-09-11 15:05
Could you please provide details on what exactly broke? What server type/version are you connecting to and what problems are you seeing exactly?

**Comment by konpl** [comment] 2019-09-11 18:25
+1. Strange behavior. All is OK when I choose "New Query" from Connections Browser. But when I creating new file or open some sql file, intellisense isn`t working. "Choose SQL Language provider"  on status bar. But I'm already connected to MSSQL Database =).
System: Windows 7.

**Comment by Charles-Gagnon** [comment] 2019-09-11 22:56
@konpl Are you sure the query window is connected?

You should see this in the action bar of the editor :

![image](https://user-images.githubusercontent.com/28519865/64741131-56f6f780-d4ac-11e9-90a4-43d019bdf2f3.png)

If you see this (Connect button and other things disabled) that means the editor isn't connected to a database so it's expected you wouldn't have Intellisense at that point.

![image](https://user-images.githubusercontent.com/28519865/64741120-4ba3cc00-d4ac-11e9-94ea-4d2544a5bb83.png)


@jfcarr I can't repro this myself on a 2016 instance. And reverting back to 1.10 resolved the issue? Could you try uninstalling ADS and then reinstalling 1.11 to see if that helps anything? If not could you open the developer console (Help -> Toggle Developer Tools) and see if there's any errors in the console tab?

**Comment by konpl** [comment] 2019-09-12 05:48
@Charles-Gagnon 
I see this
![изображение](https://user-images.githubusercontent.com/48159828/64757167-f0201f80-d539-11e9-9ad0-678d282d2df4.png)

**Comment by konpl** [comment] 2019-09-13 11:07
@Charles-Gagnon Didn't try to reinstall because I having many server connections and don't want to rewrite them.

[sqltools.log](https://github.com/microsoft/azuredatastudio/files/3609737/sqltools.log)
Steps for log write:
1. Open ADS;
2. Select "New Query" from connections window;
3. Write simple SQL query and execute it (Intellisense working);
4. Save file. After this happenned disconnect (It's correct behavior?);
5. Connect to the same SQL Server;
6. Try to call Intellisense, but it isn't working.

**Comment by jakodev** [comment] 2019-09-13 13:42
> Could you please provide details on what exactly broke? What server type/version are you connecting to and what problems are you seeing exactly?

I'm sorry for late response:
When I type **select * from dbo. ...** _I'm excepecting a list of tables/schemas_ but appears only a list o previous typed words _[abc]etc etc_
The same happens for **select * from dbo.mytable t where t. ...** _I'm excepecting a list of columns_ but nothing appears

I'm using:
SQL SERVER v14.0.2027.2 on Windows Server 2012 R2 Standard (6.3)
SQL SERVER v12.0.6329.1 on Microsoft Windows NT 6.3 (9600)

I've tried to uninstall and reinstall, but works only with v1.10

Thank you very much,
J.

**Comment by kburtram** [comment] 2019-09-13 15:47
@jakodev if you have time to verify if the below build resolves the issue that would be helpful in narrowing down where to investigate.  This build is from master yesterday with a downgraded SMO component.  Thanks!

Windows: https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-windows-intellisense-bug.zip
macOS: https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-macos-intellisense-bug.zip

**Comment by HumorMe** [comment] 2019-09-13 17:46
Seeing the same problem. I tried with both SQL2008 and SQL2016, so I think you can rule out SQL version as mattering. The key repro seems to just be saving the file kills intellisense.

**Comment by HumorMe** [comment] 2019-09-13 17:56
@kburtram I tried the windows version you linked in your last post. It did not fix the problem. 
I am using exact same repro steps as @Charles-Gagnon against a local SQL Server 2016 from a client with Windows 10 build 18362.

**Comment by kburtram** [comment] 2019-09-13 19:11
@HumorMe thanks for confirming!  That helps us narrow down where not to look.

Azure Data Studio keeps its persisted state in `C:\Users\[USERNAME]\AppData\Roaming\azuredatastudio` and `C:\Users\[USERNAME]\.azuredatastudio`.  These directories shouldn't be altered during uninstall\install.  The connection data specifically is in `C:\Users\[USERNAME]\AppData\Roaming\azuredatastudio\User\settings.json` in case you'd like to "backup" those settings before reinstalling.

**Comment by jakodev** [comment] 2019-09-16 14:50
> @jakodev if you have time to verify if the below build resolves the issue that would be helpful in narrowing down where to investigate. This build is from master yesterday with a downgraded SMO component. Thanks!
> 
> Windows: https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-windows-intellisense-bug.zip
> macOS: https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-macos-intellisense-bug.zip

Hi @kburtram,
I'm trying this release (v1.12) and the intellisense this time works only if I'm using it in a new clean query sheet. In old/saved query sheet intellisense still doesn't work. Very strange...

Let me know if you need further tests
J.

**Comment by kburtram** [comment] 2019-09-16 19:10
@jakodev I'm able to repro now with saved SQL files.  Previously I was testing with untitled files.  This should be enough to determine the root cause.  Thanks!

**Comment by Charles-Gagnon** [comment] 2019-09-16 20:23
Alright, I've tracked down an issue that was indeed introduced in the last release. I'm working on a fix now - will update if I need any more information!

**Comment by cesarlaforet** [comment] 2019-09-17 15:03
While it i not fixed, not sure if everyone knows this but in a query windows after connecting to the database if we run "Refresh IntelliSense Cache" then it works for that query window/database. (v1.11.0)

**Comment by jakodev** [comment] 2019-09-17 15:54
> While it is not fixed, not sure if everyone knows this but in a query windows after connecting to the database if we run "Refresh IntelliSense Cache" then it works for that query window/database. (v1.11.0)


Yes, I've already tried without success...thansks for the suggestion.
J.

**Comment by Charles-Gagnon** [comment] 2019-09-19 18:32
Fix merged in https://github.com/microsoft/sqltoolsservice/pull/867 - once we get an updated SqlToolsService then I'll update insiders with the new version.

**Comment by Epivaral** [comment] 2019-09-25 03:22
> 
> 
> Fix merged in [microsoft/sqltoolsservice#867](https://github.com/microsoft/sqltoolsservice/pull/867) - once we get an updated SqlToolsService then I'll update insiders with the new version.

when this fix will be available in the insiders?

**Comment by Charles-Gagnon** [comment] 2019-09-25 15:00
@Epivaral The insiders build from last night should have the fix! Try it out and let us know if anyone is still having issues after the update.

**Closed by Charles-Gagnon** 2019-09-25 15:00 UTC
Labels: Area: Connection, Bug, Triage: Done

**Comment by ideoclickVanessa** [comment] 2019-09-25 15:18
when can non-insiders expect to see this fix?

**Comment by Charles-Gagnon** [comment] 2019-09-25 15:21
@ideoclickVanessa We're targeting next week for a stable release
