### ISSUE TITLE
Missing Features.

### ISSUE THREAD

**Issue by JGarCo** [microsoft/azuredatastudio#1816] opened 2018-07-02 15:14 UTC
- SQL Operations Studio Version: 0.30.6

Steps to Reproduce: N/A.

Missing features: Table design (or equivalent), and Table properties, to set permissions, etc. Will there be integration with SQL Versioning software?

**Comment by VaclavElias** [comment] 2018-10-08 15:27
Hey @JGarCo do you mean versioning directly e.g. Stored Procedures, Functions, Tables, anything what could be scripted to the Source Versioning software e.g git?

E.g. there could be an option to add a git repo to the Database and with a click push all changes to repo?

I am also looking into this feature 😃

**Comment by kburtram** [comment] 2021-09-10 18:36
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/282.  Please open separate issues for individual feature requests if applicable.  Thanks!

**Closed by kburtram** 2021-09-10 18:36 UTC
Labels: Enhancement
