### ISSUE TITLE
compat level ordering in new database dialog is almost backwards

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#23650] opened 2023-07-05 20:41 UTC
![image](https://github.com/microsoft/azuredatastudio/assets/12227241/6734e08b-40a2-4913-95e4-34d87cc77dd0)

suggest we order these descending, not whatever order this is

**Comment by chlafreniere** [comment] 2023-07-05 20:58
Dupe of #23649 (sorry just a bit too slow, @dzsquared 😄)

**Closed by chlafreniere** 2023-07-05 20:58 UTC
Labels: Triage: Needed, Area - Basic Admin
