### ISSUE TITLE
Add the option to include scripts in SQL DB projects

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/azuredatastudio#13850] opened 2020-12-18 14:35 UTC
**Is your feature request related to a problem? Please describe.**
There is only the option to exclude from projects. I have the issue of members in my team creating the scripts without using projects or by accident excluding files. Then we have to manually include the script into the `sqlproj` file or use VS19 so the script can be mapped again.

![image](https://user-images.githubusercontent.com/33104726/98606889-e6f52480-229c-11eb-9163-c1ca3770d9c9.png)

**Describe the solution or feature you'd like**
There should be an option like in Visual Studio 2019 to include files in the project:

![image](https://user-images.githubusercontent.com/33104726/98607024-2754a280-229d-11eb-86af-0ef1edd54999.png)

**Comment by kisantia** [comment] 2020-12-18 18:59
duplicate of https://github.com/microsoft/azuredatastudio/issues/13344

**Closed by kisantia** 2020-12-18 18:59 UTC
Labels: Area - SQL Project, Enhancement, Triage: Needed
