### ISSUE TITLE
Install button for extensions opening links to GitHub

### ISSUE THREAD

**Issue by borgdylan** [microsoft/azuredatastudio#1363] opened 2018-05-07 20:23 UTC
- SQL Operations Studio Version: 0.29.3
- OS: Ubuntu 18.04 using Linux 4.16.7 x64 kernel
Steps to Reproduce:

Attempt to install an extension such as MSSQL Instance Insights, a link to the repo hosting it will appear. I expected sqlops to just download and install the extension just like VSCode does.

**Comment by kburtram** [comment] 2018-05-08 17:25
@borgdylan this is currently the "By Design" behavior for 3rd-party extensions.  The reason here is that we don't currently have a real extension marketplace, so publishers haven't agreed to a "Terms of Service" and we don't have infrastructure to virus scan the 3rd-party bits.  

We're working through the legal compilance story and determining how best to implement marketplace functionality.  In the meantime, the best we could come up with is to launch the extender's landing page and allow users to make a determination if they'd like to install the extension.  We plan to improve this experience overtime.

**Comment by kburtram** [comment] 2020-02-21 02:25
Closing out older issues.  This is by design until we have proper marketplace integration.  Hopefully that will land sometime this year.  Thanks for reporting this suggestion!

**Closed by kburtram** 2020-02-21 02:25 UTC
Labels: Area - Extensibility, Enhancement
