### ISSUE TITLE
Azure AD auth fails with 'Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8283] opened 2019-11-08 23:36 UTC
Issue Type: <b>Bug</b>

Went through the usual steps to connect to an Azure SQL DB using AAD and got this error message.

![image](https://user-images.githubusercontent.com/14988070/68517713-88d2d300-023d-11ea-8601-d0e03b07fdca.png)
![image](https://user-images.githubusercontent.com/14988070/68517716-8c665a00-023d-11ea-8f78-a4a9186ce36d.png)

Azure Data Studio version: azuredatastudio-insiders 1.11.0-insider (d885bb3ce30b420395988065759cdb454f782d8b, 2019-08-28T01:36:12.816Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment] 2019-11-10 19:37
Closing as duplicate of #4085

**Closed by Charles-Gagnon** 2019-11-10 19:37 UTC
