### ISSUE TITLE
Feature for searching database objects in Servers Pane

### ISSUE THREAD

**Issue by kunalpatel2706** [microsoft/azuredatastudio#860] opened 2018-03-07 19:25 UTC
Ability to search in Servers pane within a database(s) will be a great feature.
Currently it only supports searching server names. Once server and a database is selected, searching tables, stored procedures, etc. will be helpful specially when there are n number of objects.

**Comment by hypermagicmountain** [comment] 2018-04-20 14:06
It's not really dashboard related, I think OP means the left side (File/Server browser)

This would improve the workflow drastically. Right now you have to switch the tab to "Manage" in order to search for tables, views etc. which can get really confusing.

**Comment by garfbradaz** [comment] 2018-06-05 20:11
Yeah searching within **Servers** for the following objects within a SQL instance would be great:

-  Table names
-  Column names within those tables

**Comment by jplonghi** [comment] 2018-07-06 23:50
+1

**Comment by kburtram** [comment] 2018-07-07 00:13
@jplonghi have you tried the Redgate SQL Search extension?  It doesn't integrate with Servers viewlet, but it does efficiently perform global searches across a connection.

**Comment by DianGermishuizen** [comment] 2018-07-27 09:49
Yes, please add this feature! I would love to filter the list of objects in the database! When you have hundreds of Tables, Procedures etc. in a database, this makes it a lot easier to find things.

**Comment by Charles-Gagnon** [comment] 2020-08-19 21:36
Closing as a duplicate of #8052 - this has been added and will be available in the upcoming insiders build for early testing. Feedback is appreciated!

**Closed by Charles-Gagnon** 2020-08-19 21:36 UTC
Labels: Area - Data Explorer, Enhancement
