### ISSUE TITLE
Edit Connection via UI

### ISSUE THREAD

**Issue by nabrond** [Microsoft/azuredatastudio#2751] opened 2018-10-03 15:01 UTC
Issue Type: <b>Feature Request</b>

There is no UI component or mechanism by which an existing connection can be modified. It is possible to open the UserSettings.json file and manually edit the configured settings, but this should be something which the UI should support. The existing connection creation UI view should be reused for consistency between creating and editing connections.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kburtram** [comment] 2018-11-14 00:46
This appears to be a duplicate of https://github.com/Microsoft/azuredatastudio/issues/1339.  We're looking at implementing in an upcoming release.

**Closed by kburtram** 2018-11-14 00:46 UTC
Labels: connection, suggestion
