### ISSUE TITLE
href  attribute removed from untrusted notebooks

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#12990] opened 2020-10-19 16:52 UTC
Links are only clickable on Mac and Trusted Windows Notebooks.
Encounter this issue when fixing [12899](https://github.com/microsoft/azuredatastudio/issues/12899).
On Windows, the href attribute is removed from the element if it contains an URI-encoded absolute path when sanitizing the contents. 
This only happens with untrusted notebooks on Windows.

**Comment by chlafreniere** [comment] 2020-10-29 02:44
Hmm, I'm a little confused. Does this only happen on Windows or also on Mac?

Links being sanitized away is by design.

**Comment by chlafreniere** [comment] 2021-08-30 20:55
Closing as by design.

**Closed by chlafreniere** 2021-08-30 20:55 UTC
Labels: Bug, Needs More Info, Area - Notebooks
