### ISSUE TITLE
Create Chart fail for "Image" type

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8023] opened 2019-10-25 18:46 UTC
Run any query and create a chart. Choose `Image` from the chart type dropdown.

Expected - Image to show.
Actual - An error image appears -

![Capture](https://user-images.githubusercontent.com/6411451/67596059-be939a00-f71c-11e9-9d76-dffa0ece25c1.JPG)

Error in the console - 
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: N, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (azuredatastudio\node_modules\moment\moment.js:320:98)
    at configFromString (azuredatastudio\node_modules\moment\moment.js:2368:15)
    at configFromInput (azuredatastudio\node_modules\moment\moment.js:2594:13)
    at prepareConfig (azuredatastudio\node_modules\moment\moment.js:2577:13)
    at createFromConfig (azuredatastudio\node_modules\moment\moment.js:2544:44)
    at createLocalOrUTC (azuredatastudio\node_modules\moment\moment.js:2631:16)
    at createLocal (azuredatastudio\node_modules\moment\moment.js:2635:16)
    at hooks (azuredatastudio\node_modules\moment\moment.js:12:29)
    at momentify (azuredatastudio\node_modules\chart.js\src\scales\scale.time.js:197:11)
    at parse (azuredatastudio\node_modules\chart.js\src\scales\scale.time.js:219:14)
    at ChartElement.determineDataLimits (azuredatastudio\node_modules\chart.js\src\scales\scale.time.js:551:20)
    at ChartElement.update (azuredatastudio\node_modules\chart.js\src\core\core.scale.js:201:7)
    at ChartElement.update (azuredatastudio\node_modules\chart.js\src\scales\scale.time.js:511:40)
    at getMinimumBoxSize (azuredatastudio\node_modules\chart.js\src\core\core.layouts.js:192:19)
    at Object.each (azuredatastudio\node_modules\chart.js\src\helpers\helpers.core.js:108:9)
    at Object.update (azuredatastudio\node_modules\chart.js\src\core\core.layouts.js:206:11)
    at Chart.updateLayout (azuredatastudio\node_modules\chart.js\src\core\core.controller.js:443:12)
    at Chart.update (azuredatastudio\node_modules\chart.js\src\core\core.controller.js:398:7)
    at Graph.set data [as data] (azuredatastudio/out/sql/workbench/parts/charts/browser/graphInsight.js:139:30)
    at Graph.set options [as options] (azuredatastudio/out/sql/workbench/parts/charts/browser/graphInsight.js:252:23)
    at Insight.set options [as options] (azuredatastudio/out/sql/workbench/parts/charts/browser/insight.js:43:42)
    at ChartView.buildOptions (azuredatastudio/out/sql/workbench/parts/charts/browser/chartView.js:175:38)
    at Object.set (azuredatastudio/out/sql/workbench/parts/charts/browser/chartView.js:72:34)
    at azuredatastudio/out/sql/workbench/parts/charts/browser/chartView.js:241:62
    at Emitter.fire (azuredatastudio/out/vs/base/common/event.js:458:38)
    at SelectBoxList.onMouseUp (azuredatastudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:617:39)
    at SelectBoxList.<anonymous> (azuredatastudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:579:31)
    at Emitter.fire (azuredatastudio/out/vs/base/common/event.js:461:41)
    at azuredatastudio/out/vs/base/common/event.js:55:106
    at Emitter.fire (azuredatastudio/out/vs/base/common/event.js:458:38)
    at HTMLDivElement.fn (azuredatastudio/out/vs/base/browser/event.js:9:35)

```

**Comment by chlafreniere** [comment] 2019-10-25 21:48
This is broken in the release branch as well.

**Comment by smartguest** [comment] 2019-10-28 17:33
From what I was able to find out, in imageInsight, in the set Data function, the code simply takes the first element of the first row and tries to convert that into base64 encoded image data from presumably hexadecimal strings.

All of this means that the data section of that code does not actually convert the table into an image, but rather feeds junk data into the image src, resulting in an image failure.  This means that there must be significant processing to turn the text into a readable image data along with things like spacing and bars.

**Comment by anthonydresser** [comment] 2019-10-28 21:57
This isn't broken, this is by design. @kevcunnane has more context but this feature is for a very specific scenario where you can export charts as an image from sql server and it outputs it as a base64 encoded text string.

Maybe we need better handling about how we show this error, but this is by design.

**Comment by smartguest** [comment] 2019-10-28 22:04
Alright, I will identify what is passed into the function when it is properly used and figure out a way to handle erroneous results

**Comment by aaomidi** [comment] 2019-12-13 21:44
Is this solved? Can we close it?

**Comment by kburtram** [comment] 2020-01-15 21:28
Closing based on #8086.

**Closed by kburtram** 2020-01-15 21:28 UTC
Labels: Area - Charting, Bug, Triage: Done
