### ISSUE TITLE
Focus stays on cancel button when opening New database dialog

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#23644] opened 2023-07-05 20:31 UTC
When the new database dialog finishes loading, I expect the focus to be on the Name input box so I can start typing the new name, rather than staying on the Cancel button.

**Comment by corivera** [comment] 2023-09-28 20:54
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/22965

**Closed** 2023-09-28 20:54 UTC
Labels: Bug, Triage: Done, Area - Basic Admin
