### ISSUE TITLE
Forward slash in server group name creates child server group

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/azuredatastudio#5403] opened 2019-05-07 19:47 UTC
Version: 1.6.0 (user setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Add a server group
2. Type a Server group name that contains a /
3. Click OK.

Result: the portion of the server group name before the slash becomes a parent to a child server group with the name that's the portion after the slash.

**Comment by kburtram** [comment] 2019-05-07 20:09
This is a "by design" shortcut to create server group hierarchies.  Though I recall that there was discussion whether this is a discoverable, intuitive functionality.  We can revisit that discussion during while triaging issues for the next release.

**Comment by kburtram** [comment] 2019-05-13 21:25
I'll close this as a duplicate of this issue https://github.com/microsoft/azuredatastudio/issues/472 which describes the same behavior reported here.

**Closed by kburtram** 2019-05-13 21:25 UTC
Labels: Area: Data Explorer, Bug
