### ISSUE TITLE
CREATE OR ALTER - Build error SQL70001

### ISSUE THREAD

**Issue by NathanCreek-RC** [microsoft/azuredatastudio#24125] opened 2023-08-14 01:26 UTC
Type: <b>Bug</b>

When an entity (eg. stored procedure) uses "CREATE OR ALTER" building the Database Project results in
```
build error SQL70001: This statement is not recognized in this context.
```

I have created an example of this at https://github.com/NathanCreek-RC/AzureDataStudioReproRepo/tree/main/CreateOrAlterDemo
```
CREATE OR ALTER PROCEDURE [dbo].[DemoSP1]
AS
  SELECT * FROM [dbo].[DemoTable1]
```

Reproduction steps

* git clone git@github.com:NathanCreek-RC/AzureDataStudioReproRepo.git
* In Azure Data Studio
  * "Open Workspace from File" -> "CreateOrAlterDemo\CreateOrAlterDemo.code-workspace"
  * Select the "Database Projects" tab
  * Right click on the "CreateOrAlterDemo" project and select "Build"

Output
```
    stdout: Build FAILED.
e:\Dev\github\AzureDataStudioReproRepo\CreateOrAlterDemo\DemoSP1.sql(1,1,1,1): Build error SQL70001: This statement is not recognized in this context. [e:\Dev\github\AzureDataStudioReproRepo\CreateOrAlterDemo\CreateOrAlterDemo.sqlproj]
```

Extension version: 1.2.0
Azure Data Studio version: azuredatastudio-insiders 1.46.0-insider (2d1be1b330274681fbe3a89b29c3b133f203c158, 2023-08-10T05:35:33.036Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by kisantia** [comment] 2023-08-14 21:00
Closing as by design. Only `CREATE` statements are supported in sql projects, which is the same behavior as SSDT in Visual Studio.

**Closed by kisantia** 2023-08-14 21:00 UTC
Labels: Bug, Triage: Needed, Area - SQL Project
