### ISSUE TITLE
Query failed: The connection does not support MultipleActiveResultSets.

### ISSUE THREAD

**Issue by LucasWBritz** [microsoft/azuredatastudio#3594] opened 2018-12-11 16:47 UTC
I'm not sure if this is a bug related to Azure data studio or if there is something else that's causing this but I'm getting the error "Query failed: The connection does not support MultipleActiveResultSets." when I'm trying to execute a simple SQL. 

![query error](https://user-images.githubusercontent.com/24421665/49815647-65648700-fd53-11e8-8bce-1ca831332e1d.PNG)

The SQL that I'm executing is:
`SELECT TOP (1000) [Id]
      ,[UserId]
      ,[CreatedOn]
      ,[CountryId]
  FROM [dbo].[TargetLocation]`

Steps to Reproduce:

1. This happened today, and I was unable to reproduce or get a step by step on how to reproduce this. 

I solved this closing and reopening Azure data studio. 

Version info:
**Version 1.2.4
Commit 1ebfd0235690ad044ed2874a02e65188f5fea01c
Date 2018-11-02T21:50:52.634Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64**

**Comment by MattIrv** [comment] 2018-12-11 19:04
Is there any chance you had the query window open and connected for a long time before running the query that returned this error, or that there was something else that might have caused your query to get disconnected for some reason?

I've seen this error message once or twice lately and I think it has something to do with our recent changes to make query tabs more resilient to getting unexpectedly disconnected, but am not entirely sure how to reproduce it

**Comment by LucasWBritz** [comment] 2018-12-11 19:34
Yes, If I'm not wrong the query window was open for at least 15 minutes.  
I executed this query then did some other stuff here and after some time tried to execute it again receiving this error.

**Comment by michaelvickers-bw** [comment] 2019-03-21 20:10
In Management studio, the same behavior is noted - however, on the second attempt to execute the query automatically reconnects to the previous datasource. Can that functionality be mirrored here?

**Comment by NickyClark1** [comment] 2019-05-24 05:36
Seconded. We first get an error re: 'connection closed' and then get this error on re-attempting to run the query. We can never come back to queries after more than 10 minutes or so, we have to close the tab and start a new one in order to establish a connection again.

**Comment by williamadba** [comment] 2019-06-06 20:47
Same as @NickyClark1, after a while, the above happens. Reconnecting doesn't help. Opening/closing the file (in this case, an ADS Notebook) solves the problem.

**Comment by ibuda** [comment] 2019-07-03 12:51
Same as @williamadba, getting the  "Query failed: The connection does not support MultipleActiveResultSets." error on the default "SELECT TOP 100 FROM" query in a notebook. Disconnecting, reconnecting does not help, only restarting ADS helps.

**Comment by richardtallent** [comment] 2019-10-20 15:05
I'm constantly having the same problem, both connected to Azure SQL Databases and internally-hosted MSSQL instances.

**Comment by rockneverdies55** [comment] 2020-01-29 05:14
Having the same issue. Any updates here?

**Comment by chrisblanch** [comment] 2020-02-11 18:02
Also having this issue, querying an SQL Server hosted on Azure, using the MacOS app.

If I attempt the query a third time, then the tab itself closes and an error message is displayed in the bottom right that reads: "Unable to open 'SQLQuery_3 - <db_name>)': Cannot read property 'length' of null."

This renders Azure Data Studio almost worthless to me, which is frustrating since we are on a completely Microsoft infrastructure.

**Comment by miguelguadarrama** [comment] 2020-02-17 04:25
Same here as everyone else. Nowadays I don't wait for the error anymore, if I leave a tab unattended for more than 5 minutes then I proactively close it and right click database > new query again. This seems like a basic functionality that should be sorted out IMO.

**Comment by CallSign-Filter** [comment] 2020-05-07 16:40
Any way this can be fixed? This may seem trivial to other users but I run into this problem constantly as I am developing full stack. I spend all day with Azure open writing stored procedures and front end code so my same files stay open all of the time. I would move to another SQL editor but Azure seems to be the only one that supports Windows Authentication through Kerberos

**Comment by silkfire** [comment] 2020-05-07 18:15
I think this error could occur when a connection to the database is being established, but at the same time, other threads are trying to run the Connect() method as well. I think it could probably be solved with a semaphore or a mutex.

**Comment by gjpsiqueira** [comment] 2020-05-12 22:29
I Having the same issue. To resolve, I having than open a tab 'new query' to run the query and reconnecting to database. That's much frustrating.
There's no nothing to resolve this problem ?

**Comment by yesspadilla75** [comment] 2020-06-18 16:26
I'm also having the issue. Is there any way in which this is avoided? It's really annoying to have to reconnect every half an hour... or opening multiple query notepads, in the end you lose track of what you query on.  Any news on this?

**Comment by CoolDixon** [comment] 2020-08-15 05:22
I do also vote for this fix!!. My workaround is to click on disconnect and connect again but it is so constant issue that is annoying
I migrated from SSMS to ADS as I like the later for everyday use leaving former only to edit SQL Agent Jobs (that ADS doesn't handle properly), but I miss this "always reconnect by itself" from SSMS

**Comment by LukeStephen** [comment] 2020-11-23 21:44
having the same issue, closing and opening a new tab fixes it. Previous tab had completed just fine

**Comment by ozhug** [comment] 2020-12-11 03:47
yes same error error as well needed to restart Azure Data Studio to fix

**Comment by yesspadilla75** [comment] 2021-02-01 11:18
HI again.

This is happening now more frequently than before. It seems as though you cannot leave a tab unnatended for more than 5 minutes before it somehow disconnects or simply stops responding. My work around is to copy the script in one tab and create a new but this is quite suboptimal. Af the end of the day I end up with 20 tabs opened, which makes my work very confusing. ANy idea of a fix to this? is there, maybe, a time configuration so the connections get opened and fresh for longer?

please advise.!

**Comment by Joeylu-master** [comment] 2021-05-26 07:50
Any update for this issue? This issue occur very frequently, i think.

**Comment by cheenamalhotra** [comment] 2023-08-29 05:06
I haven't seen this issue in a while and there have been no recent reports, I will proceed to close as stale.
Please reopen the issue or open a new one if you experience the same with latest release.

**Closed by cheenamalhotra** 2023-08-29 05:06 UTC
Labels: Bug, Area - Query Editor, Triage: Postponed
