### ISSUE TITLE
Blank data controller context when sqlmi/pg instance creation is done from the arc dashboard

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12379] opened 2020-09-16 22:22 UTC
Issue Type: <b>Bug</b>

subject says it all. try instance creation from the arc dashboard.

Azure Data Studio version: azuredatastudio-rc1 1.22.0-rc1 (fb28b69bb0897660e38b85ffabdff79c345a8043, 2020-09-16T19:25:06.133Z)
OS version: Windows_NT x64 10.0.20215

**Comment by Charles-Gagnon** [comment] 2020-09-16 22:30
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12344

**Closed by Charles-Gagnon** 2020-09-16 22:30 UTC
Labels: Area - Dashboard, Bug, Triage: Needed
