### ISSUE TITLE
Refresh button on SQL Server Agent 0.38 not working

### ISSUE THREAD

**Issue by HanzoX7** [microsoft/azuredatastudio#5383] opened 2019-05-06 21:29 UTC
So, hitting the refresh button on the SQL Server Agent, between the stop and edit job icons doesn't do anything. To get something to refresh, you need to hit the upper right hand refresh button.

Here's the version info from the about:

Version: 1.6.0 (user setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

And the version information from the extension:

Name: SQL Server Agent
Id: microsoft.agent
Description: Manage and troubleshoot SQL Agent jobs
Version: 0.38.0
Publisher: Microsoft

**Comment by Charles-Gagnon** [comment] 2019-07-03 22:14
You're talking about the Refresh button on the Jobs page?

![image](https://user-images.githubusercontent.com/28519865/60627909-7b47a100-9da4-11e9-9bd7-f0db9ab49184.png)

This seems to be working for me. Note that it won't appear to do anything if nothing has changed (for example no additional runs of the job have occurred) And all the other refresh buttons also seem to be working as intended. I'll close this for now - but if you are still seeing this issue please reopen it so we can investigate!

![screen](https://user-images.githubusercontent.com/28519865/60628197-34a67680-9da5-11e9-9904-618ce8e4181f.gif)

**Closed by Charles-Gagnon** 2019-07-03 22:14 UTC
Labels: Bug
