### ISSUE TITLE
extension from Microsoft Ready 2019 lab  is not supported by current  version

### ISSUE THREAD

**Issue by databull** [microsoft/azuredatastudio#4668] opened 2019-03-22 13:32 UTC
Issue Type: <b>Bug</b>

extension from Microsoft Ready 2019 lab  is not supported by current  version. not sure if this is where i log issues about extensions, feel free to point me elsewhere.

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|28.00GB (22.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.1.0

</details>

**Comment by kevcunnane** [comment] 2019-03-22 17:10
Is this in the wiki or is there a reference source I should look at? What's the error / compile time failure that's happening? Thanks.

**Comment by databull** [comment] 2019-03-22 22:58
sorry I should have added more details, its from wiki - https://github.com/Microsoft/azuredatastudio/wiki/Microsoft-Ready-2019-lab first example, dashboard widget. 
Error on install says - Unable to install version '0.0.1' of extension 'io.io-0.0.1' as it is not compatible with Azure Data Studio '1.5.2'.

when i tried running code with debugging from VS Code, i got it working only complaining about "No description specified to show."

Where would i capture "compile time failure that's happening"

is this the best place to discuss, dont want to pollute official site

**Comment by kevcunnane** [comment] 2019-03-22 23:04
This is fine, we have the samples in this repo so issues should go here. As mentioned on twitter, downgrading the vscode dependency, .e.g to 1.30.0, will likely fix this. The problem is that extension install using npm install tends to pick highest available VSCode version but we ship a lower one.

F1 -> About Azure Data Studio will show the VSCode version we ship with.
![image](https://user-images.githubusercontent.com/10819925/54857316-f2589e00-4cbb-11e9-857d-af5e00d99274.png)

Note that we hope to mostly resolve this in the next release by aligning much more closely to the latest VSCode release. This should mostly mitigate this issue, but we can look at fixing the project generator to have a slightly more sensible implementation in the future.

**Comment by databull** [comment] 2019-03-22 23:27
thanks for details, took me a while to realize where and what to change but it worked! Appreciate your swift replies. 
Cannot wait for next release, if you would need any help or test it, please let me know.

**Comment by dzsquared** [comment] 2019-11-18 02:28
I've created a pull request for the extension generator as this continues to be a barrier for new extension devs 
https://github.com/llali/generator-azuredatastudio/pull/18
@llali

**Comment by kburtram** [comment] 2021-08-17 00:31
Closing this older issue since it is referring to an extension from an event from 2019.  Please let us know if you're still impacted by this issue.

**Closed by kburtram** 2021-08-17 00:31 UTC
Labels: Bug, Area - Extensibility
