### ISSUE TITLE
Windows Authentication with Linux causing mssql Extension to crash

### ISSUE THREAD

**Issue by jkupcho** [microsoft/azuredatastudio#18844] opened 2022-03-28 20:18 UTC
- Azure Data Studio Version: 1.35.1
- OS Version: Ubuntu 20.04.4

Steps to Reproduce:

1. Using a previously configured database (as in before upgrading to 1.35.1), try making connection using Windows Authentication.
2. After trying to connect, a toast message is presented with "SQL Tools Service component exited unexpectedly. Please restart Azure Data Studio.
3. In the developer tools there is an error message with the following message:
> SQL Tools Service component exited unexpectedly. Please restart Azure Data Studio.
> onDidChangeNotification	@	workbench.desktop.main.js:1582

Does this issue occur when all extensions are disabled?: Yes

Other notes:

* If I revert to version 1.34.0 the saved connections begin to work again.
* The logs do not seem to produce anything of value, even on debug level logging.

**Comment by baconapplications** [comment] 2022-03-28 21:48
+1.  1.34 is working fine 1.35+ trusted authentication via kerberos no longer works.  Same error as above.

**Comment by Spice-King** [comment] 2022-03-29 18:43
I'll chip in that I'm getting the same thing on Pop!_OS 21.10. I got a hold of 1.35.0 to test, same issue as 1.35.1. Downgrading to 1.34.0 fixes it.

**Comment by Spice-King** [comment] 2022-08-02 21:13
Kinda forgot about this ticket since it feels very little priority is allocated to it with the issue being kicked down the road twice since I started following it. Here is a small update from my usage after 4 months.

I've since updated to Pop!_OS 22.04 LTS, 1.34.0 no longer opens (the older Electron version has issue with newer libraries or something, adding the `--no-sandbox` allows it to run, but is explicitly noted as something for testing/development, not production use) and 1.38.0 still has the component crash.

**Comment by Noggington** [comment] 2022-08-04 09:17
Hi Guys - I have been trying this on OpenSuse Tumbleweed, Kubuntu 22.04 and Fedora 36. 

I can get kerberos working on each platform mentioned above but Azure data studio will not connect to a local Windows SQL Server using kerberos.  I get the same errors the op mentioned above.

Is there any updates to this?

**Comment by jkupcho** [comment] 2022-08-08 16:16
No update on my end, only running an older version seems to fix the issue.

**Comment by cheenamalhotra** [comment] 2022-08-18 22:18
The issue was reproduced and fix verified with SqlClient update to v3.1.1.
It will be fixed in Azure Data Studio **v1.39 (upcoming release)**.

**Closed by cheenamalhotra** 2022-08-18 22:18 UTC
Labels: Bug, Area - Connection, Triage: Done, Approved
