### ISSUE TITLE
Unexpected Error Occurred while Connecting

### ISSUE THREAD

**Issue by NKarolak** [microsoft/azuredatastudio#7488] opened 2019-10-03 13:01 UTC
Issue Type: <b>Bug</b>

Viewing table data by using the context menu worked ("Select Top 1000"), however choosing "Edit data" led to an expected error. I tried it on another table and in a table of another database, still without success.

Azure Data Studio version: azuredatastudio 1.12.0 (f0b6180e15f455ccf9e8112b407a6aa8c5399fe9, 2019-10-01T18:01:40.565Z)
OS version: Windows_NT x64 10.0.18362

Log file (anonymised): [renderer1 - Copy.log](https://github.com/microsoft/azuredatastudio/files/3686117/renderer1.-.Copy.log)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment] 2019-10-03 16:49
It looks like these are some of the more important errors in the log:

```
[2019-10-03 14:49:47.721] [renderer1] [error] OnConnectionComplete but no connection found 
[2019-10-03 14:48:43.125] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at ConnectionStatusManager.onConnectionComplete (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:169436:23)
    at ConnectionManagementService.onConnectionComplete (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:227560:60)
    at MainThreadDataProtocol.$onConnectionComplete (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:239347:47)
    at RPCProtocol._doInvokeHandler (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244968:27)
    at RPCProtocol._invokeHandler (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244953:45)
    at RPCProtocol._receiveRequest (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244885:32)
    at RPCProtocol._receiveOneMessage (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244813:26)
    at RPCProtocol._protocol.onMessage (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244703:52)
    at Emitter.fire (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:11078:38)
    at BufferedEmitter.fire (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33465:35)
    at PersistentProtocol._receiveMessage (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33684:37)
    at PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33558:83)
    at Emitter.fire (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:11078:38)
    at ProtocolReader.acceptChunk (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33291:37)
    at ProtocolReader._register._socket.onData.data (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33260:61)
    at Socket.listener (file:///C:/Users/MyWindowsName/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:33841:40)
    at ZoneDelegate.invokeTask (c:\Users\MyWindowsName\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\MyWindowsName\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (c:\Users\MyWindowsName\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (c:\Users\MyWindowsName\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)

```

Thanks for reporting.  We'll investigate and try to determine what's happening.

**Comment by NKarolak** [comment] 2019-10-08 09:17
FYI, I've just updated to version 1.12.1 and the issue still exists.

**Comment by Charles-Gagnon** [comment] 2019-11-10 19:41
Closing this as a duplicate of #7897 to consolidate these - we're still in the process of investigating this issue though!

**Closed by Charles-Gagnon** 2019-11-10 19:41 UTC
Labels: Area - Connection, Triage: Done
