### ISSUE TITLE
Allow filter objects in Connections Sidebar

### ISSUE THREAD

**Issue by gxzzin** [microsoft/azuredatastudio#19301] opened 2022-05-06 16:53 UTC
It would be very helpful if we could filter objects in all servers levels (tables, procedures, views, etc.) We can do this in SS Management Studio.

![image](https://user-images.githubusercontent.com/33432992/167177279-1d865a91-ea84-4997-af5a-0304714606f6.png)

![image](https://user-images.githubusercontent.com/33432992/167176941-e1438361-696b-41d8-a05e-ed2114cfe59f.png)

**Comment by Charles-Gagnon** [comment] 2022-05-06 19:03
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12932

**Closed by Charles-Gagnon** 2022-05-06 19:03 UTC
