### ISSUE TITLE
Error when using Select Top 1000 on table: Cannot read properties of undefined (reading 'serverInfo')

### ISSUE THREAD

**Issue by sivisal** [microsoft/azuredatastudio#21737] opened 2023-01-26 15:00 UTC
Issue Type: <b>Bug</b>

Connecting to SQL Server using a connection string with parameter "Initial Catalog" makes Azure Data Studio throw an error when right clicking a table and choosing "Select Top 1000" or "Edit Top 200". Error:
Scripting failed
Cannot read properties of undefined (reading 'serverInfo')

This started maybe 6 months ago

Azure Data Studio version: azuredatastudio 1.41.0 (cf5e0fe1a33709e2a82dc94f42dbe88487803d62, 2023-01-24T17:25:45.514Z)
OS version: Windows_NT x64 10.0.22623
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by dadlMilestone** [comment] 2023-01-26 22:43
I am experiencing the same issue.

**Comment by seanmmcd** [comment] 2023-01-31 20:37
I'm also experiencing the same issue on Linux.

OS Version: Pop!_OS 22.04 LTS
Preview Features: Enabled

**Comment by Krighaar** [comment] 2023-02-01 22:02
Are you using SQL in Azure? Have you added your IP to the Network panel?
I had the same issue, could log on, but not do a `Select top 1000 * from XX` 

Normal I would expect not to be able to log on, if my ip was not on the list. But this time I did not get an error.

![image](https://user-images.githubusercontent.com/6849269/216173288-760f49b7-8105-4376-bc44-592c6950db70.png)

**Comment by dadlMilestone** [comment] 2023-02-01 22:36
The issue I was having was identical to the original post, and I am no longer seeing that issue. 

@Krighaar I did make sure when I posted before that my IP was whitelisted.

Here is info on system:

Azure Data Studio version: azuredatastudio 1.41.0 (https://github.com/microsoft/azuredatastudio/commit/cf5e0fe1a33709e2a82dc94f42dbe88487803d62, 2023-01-24T17:25:45.514Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Not Enabled

**Comment by 2ndcahl** [comment] 2023-02-02 08:52
I'm still having the issue on 1.41.1.

**Comment by vidalsasoon** [comment] 2023-02-04 16:25
@2ndcahl I had the same error but it went away when I updated to the latest version (1.41.1). I know that's the version you're using... Just saying what worked for me.

**Comment by collins-okafor** [comment] 2023-02-13 10:05
Also having the same issue at the moment. And none of the suggestions here so far has worked out

**Comment by sivisal** [comment] 2023-02-13 10:22
I have just tried with 1.41.2 and still have the same problem.

**Comment by liam-ot** [comment] 2023-02-14 14:40
Using 1.41.2 when i right click a table and try `Script as Create` i get the error: `Cannot read properties of undefined (reading 'serverInfo')`

**Comment by musaffarpatel** [comment] 2023-02-25 19:54
Same issue here, problems occurs when right clicking and selecting the option "select top 1000 rows" or "script create as"

**Comment by mechon** [comment] 2023-03-03 03:02
Same issue. 
![image](https://user-images.githubusercontent.com/1097959/222620785-c08ae390-4305-4b98-bd0d-f740d84d44f2.png)

Version: 1.41.2
Commit: 0f0960d0e774e1ce903b79378addff96117c27a6
Date: 2023-02-08T20:18:32.853Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.3.0

**Comment by autb** [comment] 2023-03-08 15:04
Same issue with version 1.41.2 here when right clicking and selecting the option "select top 1000 rows" for a new connection created to a new azure database. Old other already created connection with older version of azure data studio continue to running well as before.

**Comment by redfave** [comment] 2023-03-10 14:49
It seems to me, that this bug only occurs whne you add a new connection and directly start to work with the database.
When disconneticting and reconnecting to the database or just restarting Azure Data Studio, this bug hasn't occured to me.

**Comment by henkla** [comment] 2023-03-13 07:43
I too am experiencing this bug when operating on Azure Database. Regardless of:

- Restarting ADS
- Reconnecting to the server and/or database

Version: 1.41.2

**Comment by autb** [comment] 2023-03-13 08:54
@redfave, you right once "disconnecting and reconnecting to the database or just restarting Azure Data Studio, this bug hasn't occured to me." it's fixed it.
(I missed to say also in my case it was with an azure database)

**Comment by Petar24T** [comment] 2023-03-22 08:34
i too am experiencing the same issue

**Comment by sivisal** [comment] 2023-03-23 09:06
Still an issue in 1.42.0

**Comment by Wyseguys** [comment] 2023-03-29 20:37
Same issue.  

https://learn.microsoft.com/en-us/answers/questions/1193097/cannot-read-properties-of-undefined-(reading-serve pointed me to disabling some plugins and it works again.

I disabled the following:
 - Azure SQL migration
 - Extension for Oracle
 - SQL Server Agent
 - SQL Server Dacpac
 - SQL Server Import
 - SQL Server Profiler

With those gone (I didn't try to find a more specific culprit) I'm back and working again.

**Comment by sivisal** [comment] 2023-03-31 07:09
@Wyseguys Interesting. I haven't got any of those extensions installed - actually haven't installed any extensions in ADS. However, ADS did come with some extensions that are showing as running (like Azure (Core)), so I will try to have a look at that when I have some time.

**Comment by sivisal** [comment] 2023-04-20 08:01
Seems like 1.43 have solved the issue. Can other people confirm?

**Comment by andrewgl504** [comment] 2023-06-08 15:12
Just running into this issue. No extensions installed.

`Version: 1.44.1
Commit: 8f53a316fa00a98264f1ab119641cd540b5af25c
Date: 2023-06-01T02:13:21.084Z (1 wk ago)
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.5.0`

**Comment by aasimkhan30** [comment] 2023-06-29 02:00
Seems similar to #23414. Assigning it to @smartguest

**Comment by cheenamalhotra** [comment] 2023-07-10 20:32
Couldn't reproduce this in the latest insiders build - moving to next milestone as of now.

**Comment by cheenamalhotra** [comment] 2023-08-02 06:31
_Checking in_ - any reports of this issue from latest v1.45?

**Comment by New-Authentication** [comment] 2023-08-02 06:49
Hi @cheenamalhotra, 
I've had no issues since 1.43 and 1.45 still working fine, last tried yesterday. Like the little status that shows that ADS is performing the operation!
![image](https://github.com/microsoft/azuredatastudio/assets/135658651/b245c4b4-49f5-4180-b89f-b283798b043d)

**Comment by andrewgl504** [comment] 2023-08-04 18:50
Just updated and running into this issue again.

Version: 1.45.0
Commit: 8eff468100f02157f2219335f7a566d14451ca49
Date: 2023-07-24T18:20:58.743Z
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

**Comment by jmontiel336** [comment] 2024-01-12 03:31
> It seems to me, that this bug only occurs when you add a new connection and directly start to work with the database. When disconnecting and reconnecting to the database or just restarting Azure Data Studio, this bug hasn't occured to me.

This worked for me. Disconnecting and re-connecting did the trick. Thanks for the tip!

**Closed** 2024-02-15 23:06 UTC
Labels: Bug, Area - Connection, Triage: Done, Size: S

**Comment by premChezuba** [comment] 2024-06-13 04:30
> It seems to me, that this bug only occurs when you add a new connection and directly start to work with the database. When disconnecting and reconnecting to the database or just restarting Azure Data Studio, this bug hasn't occured to me.

Thanks this worked for me !! I am using the version 1.41.2. But this tip worked.
