### ISSUE TITLE
SqlClient encrypt resets default to false

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20981] opened 2022-10-26 17:46 UTC
- Azure Data Studio Version: Insiders
- OS Version: Windows Enterprise

Steps to Reproduce:

1. Set Encrypt property default to "False" and connect to server

2. Customer (me) realizes cert is not trusted so I disconnect in OE with the intention of setting the default back to "True" 

![image](https://user-images.githubusercontent.com/72947001/198096100-235c2155-663f-4c83-be89-f1ea364ec815.png)

3. After disconnecting in OE, I right-click on server connection and select "Edit connection" to set the default to "True" and hit "Connect"

![image](https://user-images.githubusercontent.com/72947001/198096474-1951c1cd-d7d0-49c8-963c-c8a8a2f8e882.png)

![image](https://user-images.githubusercontent.com/72947001/198096741-de665ffd-3d4d-4837-bc91-7a6dcdf7188a.png)

4. I am unable to connect, which is expected behavior

![image](https://user-images.githubusercontent.com/72947001/198096943-f8b44e12-1557-413a-878f-66ec7cd58c75.png)

5. I then "Cancel" out of the connection dialog box (assuming my encrypt default is now set to "True").  I need to do this so I can get back to the main window. No other way to do this. 

6. I notice that my server (localhost) is connected even though I had disconnected (step 3) 

![image](https://user-images.githubusercontent.com/72947001/198097717-168f70ba-68e4-428e-8aa7-ece57bd9d1cc.png)

7. So I re-check the encrypt default settings and I see that the default has been reset to "False" even though I had set the default to "True" (step 3) 

![image](https://user-images.githubusercontent.com/72947001/198098298-1a9973ee-3e8c-4c10-a34d-39cc8416856d.png)

Expected: 

Once I have disconnected my server and reset the encrypt default to "True", my server should remain disconnected after I "Cancel" out of the connection dialog box. 

Actual: 

Server(localhost) somehow re-connects

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment] 2022-10-26 18:32
@tdoshin I'm going to close this because this is currently expected behavior - changes to a connection require that the connection is able to successfully be made, which means that we only apply the changes when "Connect" is clicked and the connection successfully goes through. 

Hitting cancel will discard all changes, that's expected.

We could consider allowing edit connection to have a separate "Save" button that doesn't actually test the connection and just saves the connection details as they are - but I'm not sure how useful of a feature that would be (why save a connection that doesn't work?)

**Closed by Charles-Gagnon** 2022-10-26 18:32 UTC
