### ISSUE TITLE
Excel export fails when data includes non-printable characters

### ISSUE THREAD

**Issue by goodmanmd** [microsoft/azuredatastudio#13135] opened 2020-10-29 15:53 UTC
Issue Type: <b>Bug</b>

Trying to export a query result to Excel resulted in the error message `Failed to save results. Error: Failed to save Results1.xlsx: The Writer is closed or in error state.`

After some digging in the underlying data, non-printable characters were found in a varchar column in some of the export rows - specifically, the ASCII character 0x1B (ESC). Testing an export with this single record resulted in failure, while excluding this record resulted in success.

For what it's worth, an export to CSV does work properly, and does in fact export the non-printable characters successfully.

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (15.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0

</details>

**Comment by goodmanmd** [comment] 2020-10-29 15:55
Possibly related: #5202

**Comment by alanrenmsft** [comment] 2022-05-05 17:26
dupe of #5202

**Closed by alanrenmsft** 2022-05-05 17:26 UTC
Labels: Bug, Area - Query Editor, Triage: Done
