### ISSUE TITLE
Incorrect application name displayed in Windows start menu

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#19042] opened 2022-04-13 15:55 UTC
Issue Type: <b>Bug</b>

If you pin Azure Data Studio to the start menu of Windows 11, the application name shows "Code - OSS" instead of Azure Data Studio. See screenshot:
<screenshot>
![image](https://user-images.githubusercontent.com/22226386/163221059-f4984b99-c02b-44db-b015-bb6df220258a.png)
</screenshot>

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|1.1.0
azcli|Mic|1.1.0
azdata|Mic|0.6.4
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by Charles-Gagnon** [comment] 2022-04-13 15:59
Duplicate of https://github.com/microsoft/azuredatastudio/issues/18618, this will be fixed in the upcoming release (see that issue for a workaround if this is really annoying for you)

**Closed by Charles-Gagnon** 2022-04-13 15:59 UTC
