### ISSUE TITLE
Tabs closing

### ISSUE THREAD

**Issue by aarongiust** [microsoft/azuredatastudio#14929] opened 2021-03-31 14:29 UTC
Issue Type: <b>Bug</b>

Tabs are closing on their own in Azure Data Studio. A tab will be open, I go to another tab, but when I go back to the original tab ADS says it is unable to open it.

The message says "Unable to open 'file name/tab name': Cannot read property 'slice' of undefined."

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:24:59.168Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (19.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cms|Mic|0.8.0

</details>

**Comment by Charles-Gagnon** [comment] 2021-03-31 17:19
This seems to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/6763

(https://github.com/microsoft/azuredatastudio/issues/13797 looks to be too)

**Comment by Charles-Gagnon** [comment] 2021-04-05 16:43
Note - for anyone having this issue we added some more information to our logging to help track this down. It's currently in the latest [Insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) build so if you're able to use that and then hit the issue please attach the logs as described above.

Otherwise the logging will be included in the next stable update and so when that is released then we would appreciate anyone hitting this issue helping get us the logs to try and track this down. Thanks!

**Comment by stelth240** [comment] 2021-05-06 15:05
The issue just popped up again for me. I am not running the insiders build but hopefully I am on the latest stable release that  contains the additional logging information. Attached is my console log and application logs for review.

Thank you!

[Logs.zip](https://github.com/microsoft/azuredatastudio/files/6435607/Logs.zip)

**Comment by stelth240** [comment] 2021-05-07 22:21
It just occurred again today. I have attached the logs.

[Logs 2.zip](https://github.com/microsoft/azuredatastudio/files/6444587/Logs.2.zip)

**Comment by Charles-Gagnon** [comment] 2021-05-10 16:59
Thanks! So the callstack is this : 

```
TypeError: Cannot read property 'slice' of undefined
    at p.get batchSets [as batchSets] (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5068)
    at $.set queryRunner [as queryRunner] (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8633)
    at _.set queryRunner [as queryRunner] (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8661)
    at _.onShow (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8661)
    at c.showTab (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1580)
    at w.showResults (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8667)
    at w.setQueryRunner (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8663)
    at w.set input [as input] (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8666)
    at e.setInput (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8671)
    at e.setInput (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8689)
    at p.doSetInput (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:6151)
    at p.openEditor (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:6150)
    at Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8967
    at e.doShowEditor (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8967)
    at e.doOpenEditor (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8967)
    at e.openEditor (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8966)
    at e.doCloseActiveEditor (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8970)
    at e.doCloseEditor (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8970)
    at e.closeEditor (Users/username/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8970)
```

So it looks like for some reason we're setting the input with a disposed QueryRunner (that's the only way I see that _batchSets could be undefined here : https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/query/common/queryRunner.ts)

Fixing it to not throw would be easy but I'm concerned about the fact that the QueryRunner appears to be disposed here so I feel like we should try to investigate that a bit more first.

What's interesting as well is that there are a whole bunch of other errors, such as `Trying to add a disposable to a DisposableStore that has already been disposed of.` and `Index was out of range. Must be non-negative and less than the size of the collection.` so it looks like there's a number of things going wrong in your environment @stelth240. What kind of tasks are you doing during this - just running scripts or something else? Do you notice any other weird behavior?

**Comment by stelth240** [comment] 2021-05-13 22:58
@Charles-Gagnon Thanks for the reply! I am just running SQL scripts, some from doing "Script as Alter", some from scratch. I usually have several tabs open with different connections, and I tend to move editors around as I work to be able to compare data and work on related scripts. I am not doing anything terribly complex. I do have several extensions installed. Could they be causing issues, including this tab closing issue?

**Comment by Charles-Gagnon** [comment] 2021-05-13 23:08
When you say move editors around do you mean within a single instance of ADS or do you have multiple instances of ADS open at once?

Have you noticed any sort of pattern to when this happens? Like does it generally happen right after you move an editor into a different pane or anything?

Extensions affecting this isn't super likely since they're generally pretty sandboxed from the actual editors and inputs, but out of curiosity what extensions do you have installed?

And then to confirm - this seems like this isn't something that happens consistently, am I correct? Could you estimate how often this happens to you?

**Comment by stelth240** [comment] 2021-05-26 15:28
Yes, usually within a single instance of ADS. I sometimes open up multiple instances, but not usually. It seems to happen if I leave a tab open for some time (over a day perhaps) and then go back to it later. All I do is click the tab.

It does not seem to make a difference what I do before it occurs. I have sometimes gone back to ADS the next day and simply clicked a tab, which subsequently closes. Length of time does seem to be a factor, and it may occur on large scripts, but I have not been able to confirm that. Not sure if others had the same observations.

It definitely does not happen all the time. It depends on how heavily I use ADS. Sometimes I may not see it for days or even weeks, and then I can see it happen a couple times a day. Usually the more I use it, the more it occurs, which makes sense.

I clicked through all my tabs this morning and none of them closed.

I have lots of extensions running:

Admin Pack for SQL Server
Azure Data CLI
Database Administration Tools
MSSQL Db Insights
MSSQL Instance Insights
Query History
Redgate SQL Search
SandDance for Azure Data Studio
Server Reports
SQL Server Agent
SQL Server Dacpac
SQL Server Diagnostic Book
SQL Server Profiler
SQL Server Schema Compare
Visual Studio IntelliCode
whoisactive
SentryOne Plan Explorer (disabled)
SQL Server Import (disabled)

Thank you all for your help with this!

**Comment by jesman3** [comment] 2021-06-22 13:56
I can duplicate this issue 100% of the time with the following steps. I am not sure if all of these steps are relevant but these duplicate the bug 100% of the time for me.
1) Connect to a VPN that has access to the Azure database
2) Execute a long running stored procedure
3) Disconnect the VPN while the stored procedure is still running.
4) A message is transport error message is displayed because connectivity has been lost\
5) While still disconnected from the VPN execute the query again
6) The message window displays "Total execution time: 00:00:00"
7) Click on another query tab in Azure Data Studio and then Click back on the original tab and you will get the slice error and the tab will disappear.

This is the number one concern for us in using this tool as we still haven't learned our lesson. We still write many lines of sql in an unsaved tab and this affects my team about once a week.

Thank you
-Jesse

**Comment by Charles-Gagnon** [comment] 2021-06-22 16:50
@jesman3 and anyone else hitting these issues (especially if you have a consistent repro)

@alanrenmsft recently fixed some places where these errors could occur. The fixes are still in insiders but if you are able to test it out that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by alanrenmsft** [comment] 2021-06-22 18:01
@jesman3 I can confirm the scenario you posted has been fixed in the latest insider build now.

**Comment by jesman3** [comment] 2021-06-22 19:26
I tested this scenario myself in the latest insider build and it is resolved. Thank you!!!

**Comment by alanrenmsft** [comment] 2021-06-22 19:31
@aarongiust Please reopen if you are still seeing the error.

**Closed by alanrenmsft** 2021-06-22 19:31 UTC
Labels: Area - Query Editor, Area - Shell, Bug, Triage: Done
