### ISSUE TITLE
Character do not display correctly

### ISSUE THREAD

**Issue by easinus** [microsoft/azuredatastudio#15598] opened 2021-05-31 10:37 UTC
Issue Type: <b>Bug</b>

My name contains characters with Polish accents and diacritical marks which are not displayed correctly in Azure Data Studio when I connect using AD credentials.

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
arc|Mic|0.9.3
azdata|Mic|0.6.3
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0

</details>

**Comment by smartguest** [comment] 2021-06-18 20:59
For the latest build: 

In the account creation section for AD, I replaced my name with random Polish letters with marks. When I looked at a couple of places the marks showed up fine.

![PolishScreenshot1](https://user-images.githubusercontent.com/18018452/122615065-bba99380-d03c-11eb-92d4-74c7ca538d05.png)
![PolishScreenshot2](https://user-images.githubusercontent.com/18018452/122615070-bd735700-d03c-11eb-925c-5975430cb75f.png)
![PolishScreenshot3](https://user-images.githubusercontent.com/18018452/122615082-c2d0a180-d03c-11eb-888f-657b229ad0c9.png)

Can you relay the exact steps for getting the account added into ADS and characters that are not appearing on ADS? Also try the latest insiders build to see if the issue reproduces there. Thanks!

**Comment by kburtram** [comment] 2021-07-14 21:43
Closing based on above comment.  Please let us know if you're still impacted by this issue.

**Comment by easinus** [comment] 2021-09-02 21:24
Yes, the issue persists. I have removed and added my account again to ADS with no effect. This is a minor issue, and I simply gave up. The characters which are not displayed correctly are ł and ó.

**Comment by easinus** [comment] 2021-09-03 08:25
This is how the error looks like. It should read "Paweł"

![Azure Data  Studio error](https://user-images.githubusercontent.com/60778253/131974624-300853b6-5ab6-4586-a49c-b628f4e0618e.jpg)

**Comment by smartguest** [comment] 2021-09-24 18:46
Unfortunately, I am unable to reproduce this issue without having my account name changed which I cannot do by myself easily. I literally changed the name retrieved from the token response that was given from the Azure Login (not set by ADS) to match the problematic name and it appeared to display fine on ADS without any issues. It seems the way Azure formats names with certain characters is not compatible with ADS currently. I will need to have an azure account on hand with such a problematic name in order to be able to reproduce this issue.

@kburtram Is it possible to change my Microsoft account name temporarily to address this issue or to create a fake-real azure active directory account in order to identify the name value being passed through? Nothing in ADS seems to be affected when the account name is directly changed to the problematic name as a string.

**Comment by smartguest** [comment] 2022-11-02 17:11
@easinus We have made a fix that seems to address the issue, please download ADS insiders and see if it works on your side: https://github.com/microsoft/azuredatastudio/pull/21070

**Closed by smartguest** 2022-11-02 17:11 UTC
Labels: Bug, Area - Shell, Triage: Done
