### ISSUE TITLE
OS Verison for SQL server missing starting M

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3092] opened 2018-11-01 23:53 UTC
Issue Type: <b>Bug</b>

Connect to Standalone Sql Server for example: sqltools2019-3
Right click  server name-> select manage-> Check Home page

OS version is missing M
![image](https://user-images.githubusercontent.com/43652751/47886288-61f5eb80-ddf6-11e8-8e28-f525a27a067f.png)

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (51.68GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.8.0

</details>

**Comment by kburtram** [comment] 2018-11-14 00:38
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/2793

**Closed by kburtram** 2018-11-14 00:38 UTC
Labels: bug, dashboard
