### ISSUE TITLE
Azure Data Studio is very slow executing anything

### ISSUE THREAD

**Issue by awbmansour** [microsoft/azuredatastudio#21692] opened 2023-01-22 10:40 UTC
Issue Type: <b>Bug</b>

consistently very slow performance executing any TSQL commands compared with SSMS.

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Disabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.47GB free)|
|Process Argv|--enable-proposed-api ms-toolsai.jupyter|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
azcli|Mic|1.7.0
cms|Mic|0.9.2
dacpac|Mic|1.11.0
import|Mic|1.5.4
machine-learning|Mic|0.12.0
powershell|ms-|2022.7.2
profiler|Mic|0.11.0
query-history|Mic|0.5.3
schema-compare|Mic|1.17.0
sql-assessment|Mic|0.6.3
sql-database-projects|Mic|0.20.0
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353
azdata-sanddance|msr|4.0.1
extra-sql-script-as|pac|0.5.0

</details>

**Comment by Jabberrwocky** [comment] 2023-01-26 14:12
@alanrenmsft, I have been having the same issue for what seems like months. It makes a great tool unusable. 😞 

ADS ver: 1.41.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (10.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by awbmansour** [comment] 2023-01-26 16:34
Dears, I improved (maybe by a 50% reduction in wait time) by disabling Telemetry !! (File -> Telemetry Settings)

**Comment by alanrenmsft** [comment] 2023-01-26 17:05
@awbmansour that is interesting. could you please share some execution time comparison between ADS and SSMS?

**Comment by Jabberrwocky** [comment] 2023-01-26 17:44
> Dears, I improved (maybe by a 50% reduction in wait time) by disabling Telemetry !! (File -> Telemetry Settings)
> 
> I wonder what else can be done (disabled) to improve the performance even further. Still slowerrrr than SSMS in executing simple single-line TSQL commands.

Unfortunately, this did not appear to improve the experience for me.

**Comment by Jabberrwocky** [comment] 2023-01-26 17:46
> @awbmansour that is interesting. could you please share some execution time comparison between ADS and SSMS?

I find the the "execution time" is reported as the same (less than a second). Unfortunately, ADS appears to stall the execution for several minutes after I run it. I normally use Ctrl+Enter keys to execute. But I have had delayed execution when clicking the play button icon at the top of the screen.

**Comment by cheenamalhotra** [comment] 2023-09-06 04:40
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/18524

**Closed by cheenamalhotra** 2023-09-06 04:40 UTC
Labels: Bug, Area - Query Editor, Triage: Done
