### ISSUE TITLE
Column Encryption

### ISSUE THREAD

**Issue by alexr-degreed** [microsoft/azuredatastudio#5922] opened 2019-06-06 20:43 UTC
Issue Type: <b>Bug</b>

I am trying set up a connection to one of my Sql Azure databases using the "Column Encryption Setting=Enabled" advanced setting.
When I try to query the table that has one of the columns encrypted, this setting does not appear to work as I am trying to view the data decrypted.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (4.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.7.0
whoisactive|Mic|0.1.1

</details>

**Comment by Charles-Gagnon** [comment] 2019-06-06 22:00
Closing this as a duplicate of #39 - currently Always Encrypted is not supported in .NET Core (https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-client-development)

**Closed by Charles-Gagnon** 2019-06-06 22:00 UTC
Labels: Area: Connection, Bug
