### ISSUE TITLE
Expanded copy commands in results grid

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/azuredatastudio#242] opened 2017-11-29 13:35 UTC
The current feature to save the result set to CSV, JSON and Excel is very cool, but the copy functionality is limited to tab-delimited and tab-delimited with headings. Please add "Copy to JSON" and "Copy to CSV" to the menu as well.

- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:

**Comment by weblorin** [comment] 2018-05-03 00:50
Conversely, Save as... choices do not include tab-delimited. Thanks to this suggestion, I've learned that i can accomplish this by choosing copy, then pasting into an empty text file.

**Comment by nlandess** [comment] 2018-05-07 17:12
I have the same issue as weblorin - I would like the option to save the results grid to a tab delimited file.  This can be accomplished by copying to the clipboard and saving to a file, but it seems like a very small dev step to take to make this functionality available in the same way as the other "Save as ..." options.

**Comment by alanrenmsft** [comment] 2020-11-03 22:35
dupe of https://github.com/microsoft/azuredatastudio/issues/168

**Closed by alanrenmsft** 2020-11-03 22:35 UTC
Labels: Area - Query Editor, Enhancement
