### ISSUE TITLE
Screen goes blank

### ISSUE THREAD

**Issue by brhaut0802** [microsoft/azuredatastudio#8987] opened 2020-01-29 21:15 UTC
Screen goes blank all the time.  Sometimes resizing makes it go back.  Happens all the time

**Comment by kburtram** [comment] 2020-01-31 21:09
@brhaut0802 have you been able to see any pattern when this happens?  e.g. running large queries, restoring from minimized state, running low on memory, etc.?  Or does this happen apparently randomly?  We've had numerous reports of this issue but we still don't have an intern repro to investigate yet.

**Comment by brhaut0802** [comment] 2020-01-31 21:40
It has nothing to do with query size or minimized state.  Could possibly have to do with memory but not much has changed in what I have open or am running.  Usually a web browser, vs code, visual studio and data studio all open.  Have a surface pro 4 i7 16gb memory.  I will watch for more specifics next time it happens and share what I find back to this thread.  Closing and opening the application does not help.

**Comment by kburtram** [comment] 2020-02-03 20:22
@brhaut0802 thanks for the additional details!  We think the issue may have been fixed in the latest insiders build, and will be in the Feb release later this week.  Though we still don't have an internal repro to validate.  I'll close this issue as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8775 to consolidate issues a bit.

**Closed by kburtram** 2020-02-03 20:22 UTC
Labels: Area - Shell, Bug, Triage: Done
