### ISSUE TITLE
Add Line Bookmark Construct and Move to Next/Previous Bookmark Action

### ISSUE THREAD

**Issue by ooriblestsmshemir** [microsoft/azuredatastudio#7889] opened 2019-10-22 14:28 UTC
Add a construct of a "bookmark", i.e. a way to mark a line in the code editing window, and the ability to jump to previous or next bookmarked lines.

I suggest the shortcut of "ctl-b" to bookmark a line, and "ctl-n" to jump to the next bookmarked line, and "ctl-p" to jump to the previous bookmarked line.

Each tab should have it's own bookmark namespace.

I see the "breadcrumb" concept in the Visual Studio Code, but I think it's a different concept.
https://code.visualstudio.com/updates/v1_26#_breadcrumbs

What I'm asking for is a way to mark locations in a long file, and to jump between next and previous locations.  When I'm working on a big file, I need a way to easily jump between important sections.  Other editors like SublimeText and Teradata SQL Assistant have this functionality, and it's been very useful in the past.

-Add Bookmark
-Delete/Remove Bookmark
-Jump to Next
-Jump to Previous

If I add or remove lines, the bookmark should stay with the code on the line, not with the absolute line number.  For example, if I put a bookmark on line 500, and then I delete lines 200 to 210, the code marked by the bookmark will then be on line 490. (or, is it line 489?)

**Comment by kburtram** [comment] 2021-09-10 18:41
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/13645

**Closed by kburtram** 2021-09-10 18:41 UTC
Labels: Area - Notebooks, Enhancement, Triage: Done
