### ISSUE TITLE
SQL VM Deployment Wizard Broken

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#17615] opened 2021-11-06 00:14 UTC
While attempting to deploy a new SQL VM instance, I get the following error:

```
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'name' of undefined
at l.populateVmImageVersionDropdown (/Applications/Azure Data Studio.app/Contents/Resources/app/extensions/resource-deployment/dist/main.js:12)
at processTicksAndRejections (internal/process/task_queues.js:93)
```
Screenshot:
![image](https://user-images.githubusercontent.com/40371649/140590984-283caa9f-6a3e-498b-87b3-9bf3ed534fd5.png)

The dropdown never gets out of the 'loading' state, and prevents me from progressing in the wizard.

Note: this is **not** a regression from 1.32.

**Comment by Charles-Gagnon** [comment] 2021-11-19 18:52
@chlafreniere I wasn't able to repro this - looking at the code it seems like what may have happened is that the call here https://github.com/microsoft/azuredatastudio/blob/main/extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/vmSettingsPage.ts#L293 came back with an empty list of image versions and thus there was no default value (so line 314 threw).

Are you still able to repro this? And if so it would be good to see if this happens for all subscriptions/regions to see if it was a thing with just a specific area. 

I suppose that's something we should be able to handle since it's always a possibility to happen, but I'm not really sure what the appropriate behavior here is. @aasimkhan30 do you have any ideas here?

**Comment by aasimkhan30** [comment] 2021-11-19 19:30
In the migration extension, we just have a default error message when a dropdown does not load. I think implementing something similar over here should help.  There is not much we can do here if the azure apis are not returning any data or throwing an exception.

**Comment by aasimkhan30** [comment] 2021-11-19 19:32
@chlafreniere, what region did you select in the previous screen?

**Comment by chlafreniere** [comment] 2021-11-24 18:31
@aasimkhan30 I can't repro anymore either. I can't say definitively what region that I chose, but it was either the default (Australia Central) or West US.

Agreed that surfacing some sort of error would be a better experience.

**Comment by kburtram** [comment] 2022-03-03 19:52
Closing since previous comments say this is no longer reproducible.

**Closed by kburtram** 2022-03-03 19:52 UTC
Labels: Bug, Area - Resource Deployment, Triage: Needed, Triage: Done
