### ISSUE TITLE
Search in server tree

### ISSUE THREAD

**Issue by ezequiel89** [Microsoft/azuredatastudio#2634] opened 2018-09-19 20:45 UTC
- SQL Operations Studio Version: 0.32.9

Not is posible search a table in the server tree

**Comment by adhayward** [comment] 2018-09-27 08:32
As someone who regularly works on databases with hundreds of tables I agree this would be incredibly useful.

Yes, while the functionality is available in the Database Dashboard (double click on DB name in Server Tree) it would be great to see this embedded into the tree itself or perhaps as an option in the Search Pane. Another possibility could be to have a cut down dashboard for the currently connected Database as another pane alongside the Servers/Search/Extensions etc.

Just somewhere it can be quickly accessed rather than having to go back to the Database Dashboard tab every time I need to confirm something about the table structure when writing a query.

**Comment by kburtram** [comment] 2018-10-12 20:07
Have you tried using the Redgate SQL Search extension?  It's a little different than the suggestion, but that is our recommendation for searching database connections.

**Comment by kburtram** [comment] 2018-11-14 01:45
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/69.  Please add additional comments to that issue if any particulars are missing.  Thanks!

**Closed by kburtram** 2018-11-14 01:45 UTC
Labels: object explorer, suggestion
