### ISSUE TITLE
Notebook Viewlet icon color issue for a number of Color Themes

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11930] opened 2020-08-23 04:52 UTC
- Azure Data Studio Version:
Version: 1.21.0 (user setup)
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:52:47.502Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.Choose any of these  Color Themes:  PowerShell ISE, Queit Light, Solarized Light, Kimbie Dark, High Contrast
Actual- Notebook Viewlet color seems to use the incorrect shade / color.
Here's an example of PowerShell ISE color theme - 
![image](https://user-images.githubusercontent.com/6405919/90971050-bf25ca00-e4c0-11ea-8015-8c0333be4b27.png)

Expected: the notebook viewlet color should be adjusted (since it's not active) to the appropriate inactive color

**Comment by chlafreniere** [comment] 2020-09-09 20:05
Doesn't meet the bar at this point for September, since this isn't a regression.

**Comment by Charles-Gagnon** [comment] 2022-10-25 16:11
Duplicate of https://github.com/microsoft/azuredatastudio/issues/20962 - using that one for tracking

**Closed by Charles-Gagnon** 2022-10-25 16:11 UTC
Labels: Bug, Area - Notebooks, Triage: Done, Subarea - Jupyter Book
