### ISSUE TITLE
Cannot connect account: No clouds are enabled

### ISSUE THREAD

**Issue by jongoneok** [microsoft/azuredatastudio#13220] opened 2020-11-04 17:50 UTC
Issue Type: <b>Bug</b>

Install Azure Data Studio or Azure Data Studio Insiders.
Click Add Account
Receive error that No clouds are enabled. Even though "Enable Public Cloud" is selected.

 

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.00GB (3.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-11-04 17:52
Duplicate of https://github.com/microsoft/azuredatastudio/issues/11260

I've asked for some additional information there (most importantly the console logs) so if you could reply there with that information that may help track this down.

**Closed by Charles-Gagnon** 2020-11-04 17:52 UTC
