### ISSUE TITLE
A table designer plugin would be great

### ISSUE THREAD

**Issue by luismiguelgilbert** [Microsoft/azuredatastudio#2668] opened 2018-09-23 06:08 UTC
It would be great if you could create a table designer plugin with same SSMS features:
- Add, delete, edit table columns
- Add, delete, edit table indexes

**Comment by kburtram** [comment] 2018-11-14 01:16
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/282.  Thanks for the suggestion.

**Closed by kburtram** 2018-11-14 01:16 UTC
Labels: suggestion
