### ISSUE TITLE
Cannot select multiple cells by holding Shift key

### ISSUE THREAD

**Issue by peflorencio** [microsoft/azuredatastudio#2727] opened 2018-10-01 10:33 UTC
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1. Run any query that returns multiple columns or rows.
2. Click on a cell of the `Query Results`
3. Hold <kbd>Shift</kbd> and click on another cell

Expected Behavior:
The cells in the range of the first and the last cell clicked should be selected

Actual Behavior:
Only the last cell clicked is selected

**Comment by kburtram** [comment] 2019-06-05 00:25
I was just getting ready to log a duplicate of this bug.

**Comment by Kirlac** [comment] 2019-07-10 04:21
I was just about to file an issue for this - ctrl+click also doesn't seem to allow multi select - in this case obviously without taking the range between.

I'm not sure how that nicely this would play with the behaviour of opening json strings etc in a new tab when the cell is clicked (as documented in #6295) - although you could probably have shift/ctrl+click override the open in new tab behaviour and simply select the cell which would maybe solve both issues?

**Comment by kburtram** [comment] 2021-08-17 19:54
This appears to be working on current builds.  Please let us know if you're still impacted by this issue.

**Comment by jchandracoupa** [comment] 2022-05-16 00:13
I just tried this on 1.36.1 and this definitely not working.  I thought it was working before...

**Comment by kburtram** [comment] 2022-05-16 02:46
@jchandracoupa holding down the Ctrl key while clicking on different regions in the grid should allow selecting multiple regions.  I just checked and this is working for me on 1.36.1.  Is that not working for you?

**Comment by jchandracoupa** [comment] 2022-05-16 02:56
Ah, my bad.  I used the Shift key which I thought should work by clicking the first cell and clicking the last cell that I want and I feel that it should select all in between.  But you are correct, Ctrl and dragging or Ctrl and clicking a bunch of things will work.  Ctrl  + Shift + arrow key to select a region of rows and columns doesn't seem to work tho.  A bit of an accessibility issue?

**Comment by kburtram** [comment] 2022-05-16 05:15
@jchandracoupa you should be able to click on a cell, then hold down Shift + arrow key to select a region of cells.  Please let us know if that isn't working.  I'll chat with @alanrenmsft to review the various cell selection options to ensure they are consistent/intuitive.

**Comment by kchungmsft** [comment] 2022-07-06 00:08
I can confirm that this is still an issue in ADS Version 1.37.0. Shift clicking continues to not work. Using shift+arrow keys is a bit of a workaround though annoying. I believe this used to work in the past as well, curious what type of change would regress this behavior.

**Comment by nicksoan** [comment] 2022-09-08 11:40
I am using ADS 1.38.0: 
Holding shift and using the arrow keys correctly selects multiple cells
Ctrl+Click correctly adds each clicked item to the selection
Shift+Click to multi select is still not working.

**Closed** 2022-10-15 02:44 UTC
Labels: Area - Query Editor, Enhancement

**Comment by alanrenmsft** [comment] 2022-10-15 02:45
I've added support for SHIFT key, here is a summary of the selection behaviors
**NOTE**: The multi-selection key is CTRL for Windows/Linux, CMD key for macOS.

**Scenarios**
1. Select all - click the header of row number column
![select-all](https://user-images.githubusercontent.com/13777222/195930089-9b29a3f2-6c74-4961-bf11-2e4852cfaf16.gif)

4. Select a single column - click the column header
![select-single-column](https://user-images.githubusercontent.com/13777222/195930545-15630d3a-3dc9-4cc3-9f44-deb8c3885e1e.gif)

5. Select columns individually - click the header of the columns with CTRL/CMD key pressed
![select-multiple-columns-ctrl](https://user-images.githubusercontent.com/13777222/195931525-22805a97-d443-4674-a960-33ed5ec03159.gif)

6. Select columns in a range - select the start column (a cell or entire column), then select the end column header with SHIFT key pressed
![select-multiple-columns-shift](https://user-images.githubusercontent.com/13777222/195932277-0dc5e89c-fff9-49d1-87d8-f4d23a6dbf77.gif)

7. Select a row - click the row number cell
![single-row-selection](https://user-images.githubusercontent.com/13777222/195932862-87936b00-33e5-4bf2-881d-85db247f7659.gif)

8. Select muliple rows individually - click the row number cells with CTRL/CMD key pressed
![multi-row-selection-ctrl](https://user-images.githubusercontent.com/13777222/195933162-6d91aeb2-487f-45f7-af70-b5fc19badb7a.gif)

9. Select rows in a range - select the start row (a cell or the row header), then select the end row header with SHIFT key pressed
![multi-row-selection-shift](https://user-images.githubusercontent.com/13777222/195934588-02f7572e-5a1b-4d92-bf48-81b1490907ae.gif)

10. Select cells in a range with mouse - press and hold the select button in the start cell, then move the cursor to the end cell and release the button
![cell-range-selection-mouse](https://user-images.githubusercontent.com/13777222/195935885-869e2d6d-b377-42da-b765-1f071a84d372.gif)

11. Select cells in a range with keyboard only - select the start cell, press and hold SHIFT key, then use the arrow keys to select the range
![cell-range-selection-keyboard-only](https://user-images.githubusercontent.com/13777222/195937607-33369094-0684-469d-9253-d45a09ae3a5a.gif)

12. Select cells in a range with mouse and SHIFT key - select the start cell, press and hold SHIFT key, then click the end cell
![cell-range-selection-mouse-shift](https://user-images.githubusercontent.com/13777222/195937951-d52cd9f5-c059-4861-ae48-81cd47f7fce7.gif)

13.  Select multiple ranges - Select a range with the options listed above and then with CTRL/CMD pressed and keep adding new selections.
![select-multiple-ranges](https://user-images.githubusercontent.com/13777222/195940406-e51911c7-2aee-4c7d-bf39-ef306df8433d.gif)
