### ISSUE TITLE
OE: ERR Cannot read property 'contextValue' of null: TypeError: Cannot read property 'contextValue' of null

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4406] opened 2019-03-12 16:35 UTC
Double click a node in OE. Getting exception:

ERR Cannot read property 'contextValue' of null: TypeError: Cannot read property 'contextValue' of null
    at TreeModel.setFocus (file:///D:/git/azuredatastudio/out/vs/base/parts/tree/browser/treeModel.js:1054:30)
    at TreeModel.setInput (file:///D:/git/azuredatastudio/out/vs/base/parts/tree/browser/treeModel.js:745:18)
    at FileIconThemableWorkbenchTree.Tree.setInput (file:///D:/git/azuredatastudio/out/vs/base/parts/tree/browser/treeImpl.js:119:31)
    at CustomTreeView.createTree (file:///D:/git/azuredatastudio/out/sql/workbench/browser/parts/views/customView.js:307:23)
    at CustomTreeView.activate (file:///D:/git/azuredatastudio/out/sql/workbench/browser/parts/views/customView.js:417:22)
    at CustomTreeView.setVisibility (file:///D:/git/azuredatastudio/out/sql/workbench/browser/parts/views/customView.js:241:22)
    at CustomTreeViewPanel.updateTreeVisibility (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/views/customView.js:84:27)
    at CustomTreeViewPanel [as constructor] (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/views/customView.js:50:19)
    at create (file:///D:/git/azuredatastudio/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///D:/git/azuredatastudio/out/vs/platform/instantiation/common/instantiationService.js:107:35)
    at InstantiationService.createInstance (file:///D:/git/azuredatastudio/out/vs/platform/instantiation/common/instantiationService.js:76:31)
    at DataExplorerViewlet.createView (file:///D:/git/azuredatastudio/out/sql/parts/dataExplorer/viewlet/dataExplorerViewlet.js:97:46)
    at _loop_1 (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/views/viewsViewlet.js:231:36)
    at DataExplorerViewlet.ViewContainerViewlet.onDidAddViews (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/views/viewsViewlet.js:254:17)
    at DataExplorerViewlet.onDidAddViews (file:///D:/git/azuredatastudio/out/sql/parts/dataExplorer/viewlet/dataExplorerViewlet.js:92:61)
    at DataExplorerViewlet.ViewContainerViewlet.create (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/views/viewsViewlet.js:137:22)
    at DataExplorerViewlet.create (file:///D:/git/azuredatastudio/out/sql/parts/dataExplorer/viewlet/dataExplorerViewlet.js:68:44)
    at SidebarPart.CompositePart.showComposite (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/compositePart.js:140:27)
    at SidebarPart.CompositePart.doOpenComposite (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/compositePart.js:86:18)
    at SidebarPart.CompositePart.openComposite (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/compositePart.js:59:25)
    at SidebarPart.openViewlet (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:101:25)
    at ViewletService.openViewlet (file:///D:/git/azuredatastudio/out/vs/workbench/services/viewlet/browser/viewletService.js:84:57)
    at ViewletActivityAction.run (file:///D:/git/azuredatastudio/out/vs/workbench/browser/parts/activitybar/activitybarActions.js:60:40)
    at ActionRunner.runAction (file:///D:/git/azuredatastudio/out/vs/base/common/actions.js:172:40)
    at ActionRunner.run (file:///D:/git/azuredatastudio/out/vs/base/common/actions.js:165:25)
    at CompositeActionItem.BaseActionItem.onClick (file:///D:/git/azuredatastudio/out/vs/base/browser/ui/actionbar/actionbar.js:132:32)
    at Immediate.<anonymous> (file:///D:/git/azuredatastudio/out/vs/base/browser/ui/actionbar/actionbar.js:107:70)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by anthonydresser** [comment] 2019-03-12 19:50
Is this is the server view OE or the azure?

**Comment by anthonydresser** [comment] 2019-03-12 19:51
possible dupe of  #4352

**Comment by anthonydresser** [comment] 2019-03-12 19:56
confirmed

**Closed by anthonydresser** 2019-03-12 19:56 UTC
Labels: bug, data explorer
