### ISSUE TITLE
When querying using WHILE, ADS hangs and memory usage spikes

### ISSUE THREAD

**Issue by Gre2dys** [microsoft/azuredatastudio#16590] opened 2021-08-06 07:37 UTC
When using WHILE statement, HANG occurs in ADS even if it is running for a short time, and the memory usage rate rapidly increases

**Comment by cheenamalhotra** [comment] 2023-09-13 19:13
Duplicate of #5042 
Issue is now resolved, WHILE Loop queries cancel as needed.

**Closed by cheenamalhotra** 2023-09-13 19:13 UTC
Labels: Bug, Area - Query Editor, Triage: Done
