### ISSUE TITLE
"No kernel found" errors for .NET Interactive kernel completions

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19070] opened 2022-04-13 22:52 UTC
1. Create new .NET interactive notebook and add a code cell (I've repro'd this with both sql and C# cells), then start typing in it

I'm seeing a bunch of these errors, and it doesn't seem like intellisense is working

![image](https://user-images.githubusercontent.com/28519865/163282616-ff2f83e1-250c-4b44-beaf-4282a23bbdf4.png)

**Comment by Charles-Gagnon** [comment] 2022-04-13 22:54
Maybe same issue as https://github.com/microsoft/azuredatastudio/issues/18639

**Comment by corivera** [comment] 2022-04-29 18:08
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/18639

**Closed by corivera** 2022-04-29 18:08 UTC
Labels: Bug, Area - Notebooks, Triage: Needed, Subarea - .NET Interactive
