### ISSUE TITLE
Console error when switching to AzureMFA auth type in connection dialog

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21640] opened 2023-01-18 23:53 UTC
RC1

1. Open dev tools and go to console
2. Open connection dialog
3. Switch auth type to AzureMFA
4. See this error in the log 

`Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'key')`

Unclear what effect this has - things still seem to work correctly (I was able to select and connect with an account from the dropdown)

**Comment by cheenamalhotra** [comment] 2023-01-19 00:32
Thanks Charles,
Since they're not blocking, we'll resolve in main and target resolving them for next release.

**Comment by cheenamalhotra** [comment] 2023-03-10 06:05
This issue no longer occurs it seems, I cannot reproduce it anymore. 
Likely addressed with recent changes. Closing as resolved.

**Closed by cheenamalhotra** 2023-03-10 06:05 UTC
Labels: Bug, Area - Connection, Area - Azure, Triage: Done
