### ISSUE TITLE
Session lost when your query returns an error

### ISSUE THREAD

**Issue by extrobe** [Microsoft/azuredatastudio#3029] opened 2018-10-28 23:41 UTC
- **Azure Data Studio Version**:
Version 1.1.3
Commit 2c007115f77427a7ff7af47ad6916fccf111ea11
Date 2018-10-17T21:21:46.083Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Steps to Reproduce:**
New page
`select 1 as i, 1 as s, 5 as t into #tmp`

Force a syntax error
`select * fro #tmp`

This will return an error. Correct the error and resubmit
`select * from #tmp`

returns
`Msg 208, Level 16, State 0, Line 1 Invalid object name '#tmp'.`

**Comment by kburtram** [comment] 2018-10-29 18:30
This is a duplicate of https://github.com/Microsoft/azuredatastudio/issues/2996.  I'm going to publish a October Recovery build tonight that will contain a fix for this issue.

**Closed by kburtram** 2018-10-29 18:30 UTC
