### ISSUE TITLE
Filter in folders 

### ISSUE THREAD

**Issue by willmanrojas** [microsoft/azuredatastudio#3331] opened 2018-11-28 15:32 UTC
Issue Type: <b>Feature Request</b>

It does not have filters on the folders, since it is very complicated to look for functions, stored procedures, other objects, inside a folder, thanks.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

**Comment by beor** [comment] 2018-11-29 09:45
I miss that feature too, that would be a great improvement on daily working and would make me change definitively to Operation Studio.

**Comment by philosophicles** [comment] 2019-03-19 22:16
From #3761 by @jojeswe, which is a very close or exact dupe: "Folding/unfolding objects based on schema would also be nice."  <--- I agree with this in addition to the original text of this feature request.

**Comment by philosophicles** [comment] 2019-03-22 22:27
Just spitballing now but in my dream implementation of this, I'd want to be able to: 

* Filter at the server node level, using name matching to limit what databases are visible under that node (sometimes servers have a LOT of DBs)
* Filter on a database node, matching any combination of schema names and/or object names, to limit what objects _of all types_ are visible within that database. I.e. this would affect visibility of all of: tables, views, synonyms, sprocs, and functions etc within that DB. 
* Filter on one of the object type folders (`Tables`, `Views`, `Synonyms` etc), again on both schema and/or object name, to limit visibility within that folder (and any subfolders) only. 
* Combine multiple filter condition strings with `and`, `or`, or `not` logic, on the same filtering target. For example, to show only Tables with name matching either `%Sales%` **or** `%Returns%`. Same for schemas. 
* Use regular expressions in addition to SQL `like`-syntax wildcard searches.

**Comment by A-damW** [comment] 2019-09-19 21:48
In my opinion (especially for large/complex DB's), these are essential feature(s).

Another feature I would like to see, is the ability to apply a saved filter as a default.

**Comment by seanlmcgill** [comment] 2020-04-22 12:41
A ReSharper-like Ctrl-T - universal search all the 'things' in the DB and display in an autocomplete filtered list, which then shortcuts you to the location in the 'Servers tree view' would be cool... but mostly yea, just need a filter of some sort in that main tree view.

**Comment by clansing-chr** [comment] 2020-05-18 14:50
> In my opinion (especially for large/complex DB's), these are essential feature(s).
> 
> Another feature I would like to see, is the ability to apply a saved filter as a default.

I agree.  Unfortunately right now this is the only thing holding me back from switching from SSMS

**Comment by Charles-Gagnon** [comment] 2020-07-22 22:59
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as cleanup

**Closed by Charles-Gagnon** 2020-07-22 22:59 UTC
Labels: Area - Data Explorer, Enhancement

**Comment by mammadkoma** [comment] 2021-05-31 10:34
How we can filter tables like SSMS by right click on Tables folder?

**Comment by j-iggy** [comment] 2022-02-25 20:48
Until this is a feature, I'm forced to use DBeaver.
