### ISSUE TITLE
Queries don't execute properly after latest update

### ISSUE THREAD

**Issue by peterrow** [microsoft/azuredatastudio#18563] opened 2022-02-26 14:05 UTC
Issue Type: <b>Bug</b>

1) Connect to a SQL Server 2016 DB that has stored procedures
2) In a new query window run an SP with:   exec dbo.NameOfSp
3) <EPIC FAIL REGRESSION> You get a message saying command executed successfully, but it does not display the table of records returned by the SP, tried different SPs, tried closing/reopening and re-running and nothing. It was completely fine the moment before the upgrade!!!

How on earth did this even happen!

**[UPDATE]** I have a bunch of queries I run all the time, but I never save them because ADS does this automatically to a temp file and reopens it the next time it starts. However after this update it turns out the tab with the contents in had the windows logo icon instead of the red query icon. I copied the text, started a new query window and pasted it in again and all was well with the world again.

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:36:02.883Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
ssmskeymap|kev|1.1.0
import|Mic|1.5.0
profiler|Mic|0.11.0
azdata-sanddance|msr|3.3.0

</details>

**Comment by kburtram** [comment] 2022-02-28 20:25
@alanrenmsft any idea what's happening here?  it sounds like the language auto-detection feature may be messing up files in the hotexit auto-restore list after upgrade?

@peterrow are you still having problems associated with this issue?  or was this only related to files that open & unsaved during upgrade?

**Comment by alanrenmsft** [comment] 2022-02-28 22:06
@peterrow is this what you mean by "Windows logo" 
![image](https://user-images.githubusercontent.com/13777222/156066192-08025616-d592-4bb1-8372-3b150a285d5d.png)

when it first happened to you, do you see the normal query editor toolbar (with execute, connect buttons...)at the top of the editor window?

**Comment by alanrenmsft** [comment] 2022-02-28 22:10
@peterrow also, can you share a screenshot for the query results not rendering issue?

**Comment by peterrow** [comment] 2022-03-02 11:53
@alanrenmsft - yes that screenshot is the windows logo on the tab I was getting and yes it did show the normal query window toolbar.

To resolve the problem I copied all the text out of the hotexit auto-restore window, opened a new query window and pasted into it and all was working again. So in this instance it is definitely something to do with the hotexit auto-restore unsaved content after upgrade that was broken.

**Comment by magozsolt-ec** [comment] 2022-03-08 09:45
had similar error since last update, I guess its somehow related to the collation of the db,
tested on a db with Hungarian_Technical_CI_AS 
--create table tmpx(a integer, b varchar(128));
--insert into tmpx values (1,'abc'), (2, 'bcd');
select a from tmpx;
go --returns 2 rows
select a,b from tmpx;
go --returns empty set with headers
select a,b collate Latin1_General_CI_AS from tmpx;
go --returns 2 rows

**Comment by alanrenmsft** [comment] 2022-04-01 23:11
dupe of #18800, will be fixed in our next stable release.

**Closed by alanrenmsft** 2022-04-01 23:11 UTC
Labels: Bug, Area - Query Editor, Triage: Done, Needs Logs

**Comment by peterrow** [comment] 2022-04-02 16:22
@alanrenmsft errrm how is this item the duplicate? The ID of this item is #18563, the item you mention is #18800.
This item came almost 300 items before!

**Comment by alanrenmsft** [comment] 2022-04-04 06:57
@peterrow the issue description but it is caused by the same underlying issue, you are not able to execute the query because it is not recognized as a SQL file. I fixed that one first and while looking at this one I realized it is the same issue.
