### ISSUE TITLE
Webview extensions do not render and throw an error

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#16323] opened 2021-07-19 20:32 UTC
Issue Type: <b>Bug</b>

Repro:
- Install Sandance extension
- Query any data source like SQL or Kusto using Azure Data Studio
- Click on the Visualizer icon next to the data table
![image](https://user-images.githubusercontent.com/7318752/126223207-92d3132b-6dfa-4237-8884-bb2029c01fd8.png)
- An error is displayed
![image](https://user-images.githubusercontent.com/7318752/126223332-76ae10f0-9c18-4695-9b94-c44123fb440b.png)

Azure Data Studio version: azuredatastudio-rc1 1.31.0-rc1 (6555fff09f919126fabdd34ac65cba6eaf93ef11, 2021-07-16T21:19:57.899Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (11.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by qifahs** [comment] 2021-07-19 20:57
Here is the callstack from the developer tools for this error:
![image](https://user-images.githubusercontent.com/7318752/126226317-92b2696f-50b0-4566-a14c-5f15d5c7ab70.png)

**Comment by qifahs** [comment] 2021-07-19 21:00
Attaching logs from ADS: 
[20210719T121318.zip](https://github.com/microsoft/azuredatastudio/files/6843868/20210719T121318.zip)

**Comment by kburtram** [comment] 2021-07-20 17:02
@qifahs I'm still not able to repro locally and the logs aren't providing clear context on what's happening.  Please add additional repro steps if you're able to narrow down what's triggering this.

**Comment by kburtram** [comment] 2021-08-05 17:08
Moving into backlog for future investigation.  I don't have a repro and we haven't seen additional reports of this issue after release 1.31.0 stable build.

**Comment by kburtram** [comment] 2021-08-23 18:03
Closing due to lack of repro availability.  Please let us know if you see this on 1.32 and have additional details that would help reproduce this issue.

**Closed by kburtram** 2021-08-23 18:03 UTC
Labels: Bug, Area - Extensibility, Triage: Done, Area - Live site
