### ISSUE TITLE
unresponsive large memory when copy large dataset to Windows clipboard

### ISSUE THREAD

**Issue by OzBob** [microsoft/azuredatastudio#20448] opened 2022-08-24 01:00 UTC
Issue Type: <b>Bug</b>

when query 18000 rows from Azure SqlServer database, then select all and copy the large dataset to clipboard, app is unresponsive and memory spikes. It has been non-responseive now for 5 min and windows 11 is prompting to 'end process or wait', task manager says it's now at 2500MB memory allocation.
I'm gong back to SSMS19

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.4
dacpac|Mic|1.10.1
schema-compare|Mic|1.15.0
sql-database-projects|Mic|0.18.0
sql-migration|Mic|1.0.4

</details>

**Comment by OzBob** [comment] 2022-08-24 01:02
screen shot of TaskManager and windows error prompt
![AzureDataStudioMemoryIssue2022-08-24 085629](https://user-images.githubusercontent.com/1796771/186294224-1f983941-83eb-403c-bc16-66fb301f6926.jpg)

**Comment by alanrenmsft** [comment] 2023-06-07 19:52
dupe of https://github.com/microsoft/azuredatastudio/issues/23264

**Closed by alanrenmsft** 2023-06-07 19:52 UTC
Labels: Bug, Impact: Performance, Area - Query Editor
