### ISSUE TITLE
Intellisense not working after AAD token gets expired

### ISSUE THREAD

**Issue by caohai** [microsoft/azuredatastudio#17179] opened 2021-09-28 00:06 UTC
Steps to Reproduce:

1. Start a query editor with a server using AAD-MFA auth
2. Wait for 1 hour and intelisense stops working.

**Comment by Charles-Gagnon** [comment] 2021-09-28 17:38
@caohai One thing I was thinking about for your work on these issues - what might actually be best is if you could look into updating the data protocol client itself : https://github.com/microsoft/sqlops-dataprotocolclient/blob/master/src/main.ts

That way everything using those functions will automatically get "fixed" instead of having to track down each location that uses them. This includes extensions - which right now would continue to be broken until the extension itself implemented the refresh code. 

(an alternative that I brought up earlier would be to have STS do it, which is also not a bad idea. But with the dp client you save a round trip to STS and back which might be best.

**Comment by kburtram** [comment] 2022-02-15 19:53
This area is high-risk for regressions and since this bug isn't newly changed behavior it makes more sense to take for April, and allow more verification time insiders builds.

**Comment by kburtram** [comment] 2022-04-13 17:06
The current PR is encountering a bug with STS message framework and the UX isn't quite what we want (e.g. there isn't a notification prompt to renew the token, just happens automatically with seemingly random tenant selection prompt).  Due to pending changes to the PR we need to push to June.  The fix should be available in insiders build in a week or two though.

**Comment by Trailbear** [comment] 2022-05-02 23:39
Is there a workaround for this issue that doesn't require restarting the application?

**Comment by cssuh** [comment] 2022-05-13 18:49
fixed with: https://github.com/microsoft/azuredatastudio/pull/19214 and https://github.com/microsoft/sqltoolsservice/pull/1476

**Comment by caohai** [comment] 2022-05-13 19:01
@cssuh Do we need to do a STS vbump in ADS for your changes in STS to take effective?

**Comment by cssuh** [comment] 2022-05-13 19:03
@caohai yes I'm opening the PR for that

**Comment by Charles-Gagnon** [comment] 2022-05-13 19:03
Yes, please keep this issue open until that PR is in and the fix is verified.

**Closed** 2022-05-13 20:18 UTC
Labels: Bug, Area - Fundamentals, Triage: Done, Approved
