### ISSUE TITLE
Unable to close Developer Tools Console

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#21226] opened 2022-11-14 23:56 UTC
- Azure Data Studio Version:
![image](https://user-images.githubusercontent.com/18150417/201792400-2d41a5aa-33d1-4ebd-a9f2-0d9f861d8569.png)

- OS Version: 
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎29/‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

Steps to Reproduce:

1. Open Developer Tools Console
2. The close button for ADS overlaps the close button for the Developer Tools Console (in the top right of the image)
3. As a result, you are not able to close the Developer Tools Console window without closing ADS itself.
![insiders-devtoolsconsole](https://user-images.githubusercontent.com/18150417/201792544-5b0bf155-6615-4346-80d5-254317166c42.png)

As a reference, this is what the close button looks like in the current ADS stable:
![stable-devtoolsconsole](https://user-images.githubusercontent.com/18150417/201792641-66652ce8-6db5-41dd-b28a-97defa82ce58.png)

**Comment by cssuh** [comment] 2022-11-15 00:04
I also see this behavior in the RC1 build for November

**Comment by Charles-Gagnon** [comment] 2022-11-15 00:09
Duplicate of https://github.com/microsoft/azuredatastudio/issues/20924

You can use ctrl + shift + d to change the dock position of the window as a workaround for the time being.

**Closed by Charles-Gagnon** 2022-11-15 00:09 UTC
Labels: Bug, Area - Shell, Triage: Needed
