### ISSUE TITLE
Feature Request: Simple Grid Results Aggregation

### ISSUE THREAD

**Issue by coreywebber** [microsoft/azuredatastudio#570] opened 2018-01-29 05:23 UTC
Add a extra bar at the bottom of the grid post query that will all a user be able to select a column to sum, max, min, distinct count of the values in a column for post query analysis.

**Comment by alanrenmsft** [comment] 2020-11-04 00:22
dupe of https://github.com/microsoft/azuredatastudio/issues/512

**Closed by alanrenmsft** 2020-11-04 00:22 UTC
Labels: Area - Query Editor, Enhancement
