### ISSUE TITLE
New connection: Windows Authentication should enable username and password fields

### ISSUE THREAD

**Issue by ellbosch** [microsoft/azuredatastudio#7079] opened 2019-09-05 17:38 UTC
This feature request is related to issue #7077. ADS makes makes assumptions about the username when attempting to connect using Windows Authentication. If the username isn't correct, the experience requires using the command line to specify the correct username.

I recommend that ADS enables the username and password inputs in the New Connection form so users may input credentials without needing to call `kinit` in the command line.

**Comment by Charles-Gagnon** [comment] 2019-09-09 16:19
Thanks for the suggestion @ellbosch - this appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/112 so I'll be closing this one. Please follow that for any updates on the request!

**Closed by Charles-Gagnon** 2019-09-09 16:19 UTC
Labels: Area: Connection, Enhancement, Triage: Needed
