### ISSUE TITLE
Forward slash in server group name creates child server group

### ISSUE THREAD

**Issue by jphellemons** [microsoft/azuredatastudio#472] opened 2018-01-11 09:37 UTC
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Make a new server group
2. use as name: "Work - Development/test"

<img width="208" alt="word-break" src="https://user-images.githubusercontent.com/1119134/34818358-d56c546a-f6ba-11e7-8715-6e6f579bef80.PNG">

The /t is used as tab or something and makes it too wide and the next word is on the second line and only visible when you unfold it.

I think the slash should be escaped. or something. It's a minor issue though. But it surprised me.
If you edit the group, it cuts off the 'test' (2nd line) part. So if you want to shorten it. You need to delete the group and re-create.

**Comment by jphellemons** [comment] 2018-03-14 10:32
The designed behavior could speed up the process of creating nested groups. Is this infinite deep? Or only for two levels? But as you said, it was confusing for me because it was not mentioned in the dialog. Perhaps add a small line there: "Pro tip: create two or more nested groups by using the slash '/' character!" 
![epic-design](https://user-images.githubusercontent.com/1119134/37397241-5fa91852-277b-11e8-8694-d76d61e5b156.jpg)

**Comment by kburtram** [comment] 2019-05-13 21:26
updated title to better reflect the behavior being discussed in this issue.

**Comment by kburtram** [comment] 2020-02-21 02:06
Closing this out as "by design."  It's not the most intuitive feature, but it works for users in some scenarios.  Thanks for logging!

**Closed by kburtram** 2020-02-21 02:06 UTC
Labels: Area - Data Explorer, Enhancement
