### ISSUE TITLE
Databases not listed

### ISSUE THREAD

**Issue by acohenOT** [microsoft/azuredatastudio#13378] opened 2020-11-12 21:14 UTC
Issue Type: <b>Bug</b>

Create a connection to SQL Server 2019. Expand the server. No databases are listed. Databases view is blank, too.

![image](https://user-images.githubusercontent.com/34688558/98997209-27a1a780-2502-11eb-8dc2-33d124be27e3.png)

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (12.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
sql-assessment|Mic|0.3.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment] 2020-11-12 21:44
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12992

**Closed by Charles-Gagnon** 2020-11-12 21:44 UTC
