### ISSUE TITLE
Schema Compare failed: Unexpected exception ...: Unable to cast object of type 'System.Boolean' to type 'System.Int32'.

### ISSUE THREAD

**Issue by pgeorge-redmond** [microsoft/azuredatastudio#24551] opened 2023-09-29 23:35 UTC
- Azure Data Studio Version:1.46.0
- OS Version: Windows 10 Enterprise - 10.0.19044

I have two Synapse Serverless Instances DWH Prod & UAT.

I am trying to compare schemas.  Loading the servers as Source and destination Yields:

Schema Compare failed: Unexpected exception caught during population of target model: Unable to cast object of type 'System.Boolean' to type 'System.Int32'.
Unexpected exception caught during population of source model: Unable to cast object of type 'System.Boolean' to type 'System.Int32'.

Note:
- There are no boolean or bit fields in these serverless db instances.
- Error occurs in about 3 seconds
- All my (6) other Serverless synapse dbs work fine.

Does this issue occur when all extensions are disabled?:  Yes, but I could not disable the schema compare as thats what I was using.

Unable to use "report Issue". "Preview in Github"  does not work

**Comment by SakshiS-harma** [comment] 2023-10-02 19:27
@pgeorge-redmond 
1. Is this problem occurring with only a particular combination of source and server? 
2. Can you try creating a dacpac out of these dbs and try comparing them? Does the comparison still fail with the same error?

**Comment by pgeorge-redmond** [comment] 2023-10-02 20:15
S,

1) This issue only occurs with these two DHW DB instances.  Switching source/target yields the same error.  if I remove one of the DHW instance and compare it to any other Non-DWH DB, the error stays with the DWH (source or destination)

2) I did create 2 dacpac files and the error does not occur. However, getting a list of differences is only part of the issue. I need to move the changes "downward" to DEV (Vendor updated Prod directly for months). No CD/CI or deployment process was ever created. (but will be when cleaned up)

Another factor is that not all the changes will be moved, this is because some of the code is "in-progress." With all this, A schema compare, visually scanning the change and then pushing the update button appeared to be my best choice. I can do this with other Serverless instances, just not the "DWH" one. VS doesn't support this)

**Comment by SakshiS-harma** [comment] 2023-10-04 18:35
Thank you for your response @pgeorge-redmond .
Just cross checking , this issue happens on all the DWH instances or just the two specific ones you mentioned?
Also, is it a regression? Did this comparison used to work as expected before and something just changed recently or has this never worked before?

**Comment by pgeorge-redmond** [comment] 2023-10-04 18:53
SakshiS,

This problem only occurs with our "D365-DWH" and our "D365-DWH-UAT" Serverless, synapse instances. All other Synapse Serverless instances work fine and comparing dacpac files works fine.

I cannot say for sure if this ever worked. Since some things worked and this didn't, I wasn't paying specific attention to this. It would be my opinion that this has never worked.

**Comment by pgeorge-redmond** [comment] 2023-10-04 19:04
Just updated to 1.46.1  No change
![image](https://github.com/microsoft/azuredatastudio/assets/146492649/0dc20ea3-c041-4854-8579-7fc475c032b4)

**Comment by SakshiS-harma** [comment] 2023-10-04 19:11
Thanks for confirming @pgeorge-redmond . The problem needs to be triaged deeply by DacFx team, I am creating a separate issue in their repo (and will tag you once created). Hope it resolves for you soon. Thanks!

**Comment by SakshiS-harma** [comment] 2023-10-04 19:55
Closing this one, since it has been moved to DacFx repo. Please re-open if any help is needed from our end. Thanks!

**Closed by SakshiS-harma** 2023-10-04 19:55 UTC
Labels: Bug, Needs More Info, Area - DacFX, Area - Schema Compare, Triage: Done

**Comment by llali** [comment] 2023-10-06 18:14
@SakshiS-harma @kisantia can you please provide some info how to get logs (stack trace) for this error?
