### ISSUE TITLE
Can't open SQL file from Azure Data Studio's file explorer

### ISSUE THREAD

**Issue by miguel-misstipsi** [microsoft/azuredatastudio#24508] opened 2023-09-25 07:18 UTC
Type: <b>Bug</b>

NOTHING HAPPENS when I try to open a SQL file with the Query Editor. I have opened the Developer Tools Console, and it's trace the following logs:

 ERR Cannot read properties of undefined (reading 'getSelection'): TypeError: Cannot read properties of undefined (reading 'getSelection')
    at e.ServerTreeView.getSelection (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2625:46292)
    at e.ObjectExplorerService.getSelectedProfileAndDatabase (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:919:3159)
    at y (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1525:93983)
    at e.QueryEditorLanguageAssociation.connectInput (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2828:10755)
    at e.QueryEditorLanguageAssociation.syncConvertInput (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2828:10615)
    at Object.createEditorInput (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3310:17167)
    at async pn.doResolveEditor (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2300:26438)
    at async pn.resolveEditor (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2300:20406)
    at async e.EditorService.openEditor (vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3312:41657)
    at async vscode-file://vscode-app/c:/Users/migue/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3515:56753

Azure Data Studio version: azuredatastudio 1.46.0 (39449bbe88a0bc4092c9b205cad10d0a556beffd, 2023-09-16T01:40:10.706Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azuremonitor|Mic|0.1.9
dacpac|Mic|1.14.0
import|Mic|1.5.5
powershell|ms-|2023.2.1
profiler|Mic|0.14.0
query-history|Mic|0.5.3
sql-assessment|Mic|0.6.4
azdata-sanddance|msr|4.0.1

</details>

**Comment by cheenamalhotra** [comment] 2023-10-24 20:25
Closing as duplicate of #24058 - actively investigating the same.

**Closed by cheenamalhotra** 2023-10-24 20:25 UTC
Labels: Bug, Area - Object Explorer, Area - Query Editor, Triage: Done
