### ISSUE TITLE
Time outs connecting to servers

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2913] opened 2018-10-16 22:08 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

I encounter timeouts when connecting to servers and clusters.

![image](https://user-images.githubusercontent.com/41927913/47050453-4a133c00-d155-11e8-857f-a529de03987b.png)

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   49	   180	 11234	azuredatastudio main
    2	   115	 11235	   gpu-process
    0	   377	 11236	   window (chinookss.database.windows.net)
    0	   180	 11243	     extensionHost
    0	    49	 11273	       /Users/gengelb/.azuredatastudio/extensions/microsoft.sql-vnext-0.6.9/scaleoutdataservice/OSX/0.1.0/MicrosoftSqlToolsScaleOutData --log-dir /Users/gengelb/Library/Application Support/sqlops/scaleoutdata
    0	    82	 11282	       /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.34/MicrosoftSqlToolsServiceLayer --log-dir /Users/gengelb/Library/Application Support/azuredatastudio/mssql
    0	    33	 11285	       /Users/gengelb/.azuredatastudio/extensions/microsoft.import-0.2.0/flatfileimportservice/OSX/0.0.2/MicrosoftSqlToolsFlatFileImport --log-dir /Users/gengelb/Library/Application Support/azuredatastudio/flatfileimport
    0	    49	 11286	       /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.34/SqlToolsResourceProviderService --log-dir /Users/gengelb/Library/Application Support/azuredatastudio/mssql
    0	    49	 11287	       /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.34/MicrosoftSqlToolsCredentials --log-dir /Users/gengelb/Library/Application Support/azuredatastudio/mssql
    0	    33	 11401	       electron_node jsonServerMain.js 
    0	    16	 13483	       python3.6 /Users/gengelb/.scaleoutdata/python/0.0.1/bin/jupyter-notebook --no-browser --notebook-dir /Users/gengelb --port=8890 --NotebookApp.token=825d4b6faae550902a7e5c908ee709ff4449be2b84801457
    0	    16	 13492	         /Users/gengelb/.scaleoutdata/python/0.0.1/bin/python3.6 -m sparkmagic.kernels.pyspark3kernel.pyspark3kernel -f /Users/gengelb/Library/Jupyter/runtime/kernel-a1c059eb-1089-4f3a-858a-72a468fcbcc1.json
    0	    16	 13499	       python3.6 /Users/gengelb/.scaleoutdata/python/0.0.1/bin/jupyter-notebook --no-browser --notebook-dir /Users/gengelb --port=8889 --NotebookApp.token=ac4631526b99cb732a02ad7d17b2997d89c666de9f2d3b94
    0	    16	 13506	         /Users/gengelb/.scaleoutdata/python/0.0.1/bin/python3.6 -m sparkmagic.kernels.pyspark3kernel.pyspark3kernel -f /Users/gengelb/Library/Jupyter/runtime/kernel-4b58a5df-b4aa-4510-ac0c-c645f6f53de3.json
    0	    16	 13515	       python3.6 /Users/gengelb/.scaleoutdata/python/0.0.1/bin/jupyter-notebook --no-browser --notebook-dir /Users/gengelb --port=8888 --NotebookApp.token=424630d814192e407d974ae4be159c76f1c632cc9992c7d4
    0	    16	 13522	         /Users/gengelb/.scaleoutdata/python/0.0.1/bin/python3.6 -m sparkmagic.kernels.pyspark3kernel.pyspark3kernel -f /Users/gengelb/Library/Jupyter/runtime/kernel-e37f9eb0-aa64-4db9-8316-7ac4ddf69b14.json
    0	    16	 13698	       python3.6 /Users/gengelb/.scaleoutdata/python/0.0.1/bin/jupyter-notebook --no-browser --notebook-dir /Users/gengelb/Desktop/ADS --port=8891 --NotebookApp.token=726aea0a5de46574c01172af86c36ada8c8164e8d8064923
    0	    82	 14411	         /Users/gengelb/.scaleoutdata/python/0.0.1/bin/python3.6 -m sparkmagic.kernels.pyspark3kernel.pyspark3kernel -f /Users/gengelb/Library/Jupyter/runtime/kernel-33246baf-ba3a-41c1-b494-bd003a54ce77.json
    0	    16	 14744	       python3.6 /Users/gengelb/.scaleoutdata/python/0.0.1/bin/jupyter-notebook --no-browser --notebook-dir /Users/gengelb/Desktop/ADS --port=8892 --NotebookApp.token=acb7381d8c3ffdd988d54d46fc1e1e41d4a860bbecaa2f7f
    0	    16	 14753	         electron_node bdbe.js 
    0	    49	 11244	     searchService
    0	    82	 11247	   shared-process
    0	    49	 13701	   window (undefined)
    0	    49	 13714	   window (undefined)
    0	    66	 13930	   window (undefined)
    0	    49	 14402	   window (undefined)
    0	    33	 14748	   window (undefined)
    0	    33	 14761	   window (undefined)
    2	    82	 15179	   window (Issue Reporter)
    9	     0	 15181	   (ps)
   12	     0	 15182	   (ps)
   14	     0	 15183	   (ps)
   16	     0	 15184	   (ps)
   16	     0	 15185	   (ps)
    8	     0	 15186	   (ps)
    0	     0	 15187	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by kburtram** [comment] 2018-10-17 00:33
@gengelbms I'm not sure there is much we can do client-side for timeouts connecting to servers.  Probably the recommendation would be to increase the timeout in the Connection Dialog Advanced options, or troubleshot either the network or server load.  Is there any reason to suspect this is a client-side issue?

**Comment by kburtram** [comment] 2018-10-17 22:12
@gengelbms I agree that the timeout is likely not client-side.  It is likely related to network connectivity or server responsiveness issues if I had to guess.  Typically a timeout means that there was some type of communication error with the server.  

One exception would be on the 1-core scenario where SqlClient is timing-out during the handshake.  Though this is pretty rare and likely wouldn't occur on both your mac and Windows box.

Have you tried using SSMS from the Windows machine to connect to the same server?  If you can repro the timeout in ADS and then concurrently connect successfully in SSMS this would help scope the investigation.  If you do this test, you should connect from both tools at about the same time to eliminate the impact transient network issues.

**Comment by gengelbms** [comment] 2018-10-17 22:28
Sounds good. I will these this tomorrow morning.


George Engelbeck

Senior Design Researcher | Azure Data Platform

Microsoft Corporation

Mobile: + 1.425.281.0836

<http://aka.ms/weboutlook>


________________________________

**Comment by gengelbms** [comment] 2018-10-18 15:20
Have you tried using SSMS from the Windows machine to connect to the same server? If you can repro the timeout in ADS and then concurrently connect successfully in SSMS this would help scope the investigation.

> SSMS was very fast. Click..Done.

> ADS (on Mac) spun the doughnut for a good 20-30 seconds.

> ADS (on Windows) took 2-3 seconds.



George Engelbeck

Senior Design Researcher | Azure Data Platform

Microsoft Corporation

Mobile: + 1.425.281.0836

<http://aka.ms/weboutlook>


________________________________

**Comment by EmanueleMeazzo** [comment] 2019-03-26 17:27
I'm writing here since I have this issue basically any day; I'm able to connect right a way from SSMS while I can't connect from ADS. Restarting ADS doesn't solve the issue, which seems to present itself randomly.
I have the same issue with query execution, which sometimes don't start right away but get "stuck"

How can I help you solve this? Which logs do I need to provide?

**Comment by Charles-Gagnon** [comment] 2020-01-07 00:33
Closing this as a dupe of #1727 - there's a lot of general timeout issues and for cleanup purposes I'm going to bucket them all in one place.

**Closed by Charles-Gagnon** 2020-01-07 00:33 UTC
Labels: Area - Connection, Bug

**Comment by christowers** [comment] 2021-07-07 04:25
Are you specifying the database you are trying to connect to? I was having the same issue becuase I was not. As soon as I specified a database the problem went away.
