### ISSUE TITLE
Does not start on Mac Os Catalina 10.15.7

### ISSUE THREAD

**Issue by mchern** [microsoft/azuredatastudio#20711] opened 2022-10-03 19:09 UTC
- Azure Data Studio Version:
- OS Version:
Mac Os 10.15.7
Steps to Reproduce:

1.Download
2.Double click Azure Data Studio - Insiders.app

<img width="423" alt="image" src="https://user-images.githubusercontent.com/72808/193658728-b9e6ad67-ae52-4dfb-b1a2-280369aa1316.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mchern** [comment] 2022-10-03 19:09
Process:               Electron [40112]
Path:                  /Applications/azure/*/Azure Data Studio - Insiders.app/Contents/MacOS/Electron
Identifier:            com.azuredatastudio.oss.insiders
Version:               1.40.0-insider (1.40.0-insider)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [40112]
User ID:               501

Date/Time:             2022-10-03 15:09:24.857 -0400
OS Version:            Mac OS X 10.15.7 (19H15)
Report Version:        12
Anonymous UUID:        4B34D88E-D53E-2788-7EEF-F0428653CC65

Sleep/Wake UUID:       E5F4D11D-D4BB-4D58-A9D1-0783201892D2

Time Awake Since Boot: 200000 seconds
Time Since Wake:       16000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/azure/*/Azure Data Studio - Insiders.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/azure/datastudio/Azure Data Studio - Insiders.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/azure/datastudio/Azure Data Studio - Insiders.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x106a14000 -        0x106a63fcf +com.azuredatastudio.oss.insiders (1.40.0-insider - 1.40.0-insider) <AB3CB5D1-EB3F-388F-8C63-416A00DA1AAA> /Applications/azure/*/Azure Data Studio - Insiders.app/Contents/MacOS/Electron
       0x10eec7000 -        0x10ef58f47  dyld (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> /usr/lib/dyld

Model: MacBookPro11,5, BootROM 199.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.8 GHz, 16 GB, SMC 2.30f2
Graphics: kHW_AMDRadeonR9M370XItem, AMD Radeon R9 M370X, spdisplays_pcie_device, 2 GB
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.2)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM1024G, 1 TB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller

**Comment by kburtram** [comment] 2022-11-08 22:09
@mchern do you know if this is a new error from a recent build?  I'm not sure the team has a machine with this particular macOS version.  I confirmed the latest build is working with the current macOS version.

@alanrenmsft any ideas about this issue?

**Comment by alanrenmsft** [comment] 2022-11-08 22:33
@mchern I found a similar issue in VSCode repository: https://github.com/microsoft/vscode/issues/110761, how did you exactract the azure data studio archive? does it help if you follow the instructions in the vscode issue?

**Comment by kisantia** [comment] 2023-11-29 00:05
closing since there haven't been any other reports of this.

**Closed by kisantia** 2023-11-29 00:05 UTC
Labels: Bug, Area - Acquisition, Triage: Done
