### ISSUE TITLE
Add an option to remove a Database

### ISSUE THREAD

**Issue by mhosman** [microsoft/azuredatastudio#395] opened 2017-12-23 17:53 UTC
Provide an option to remove a Databse and disconnect it automatically. If I run manually the query DROP DATABASE xxxx, I get the message that the DB is being used.

**Comment by kburtram** [comment] 2018-01-18 01:07
@mhosman we'll add this suggestion to our backlog for consideration for a future release.

Typically if you're running a "DROP DB" statement and can't get an exclusive lock it's likely that the editor window is holding the lock (which is by design if connected to that DB).  

As a workaround you can try to connect to a different DB on the server, commonly `master` is used, and run the DROP DB statement from that editor.  In that case, SQL Ops Studio shouldn't be holding a lock on the target DB.

**Comment by kburtram** [comment] 2019-06-06 20:29
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/109

**Closed by kburtram** 2019-06-06 20:29 UTC
Labels: Area: Data Explorer, Enhancement
