### ISSUE TITLE
Can't connect via MFA after update to 1.17.0

### ISSUE THREAD

**Issue by SteveDMurphy** [microsoft/azuredatastudio#10197] opened 2020-04-28 20:34 UTC
Issue Type: <b>Bug</b>

Updated to new version today (1.17.0) and can no longer connect to azure data warehouse with MFA. Have removed existing accounts, etc. and still same error. NT AUTHORITY\ANONYMOUS LOGON

Azure Data Studio version: azuredatastudio 1.17.0 (b32a48ab73d8914647d33d9684bcb7b48adfe0cc, 2020-04-24T00:06:48.375Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz (8 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-04-28 20:42
@aaomidi

**Comment by SteveDMurphy** [comment] 2020-04-28 20:49
This is what I was able to get out of the renderer.log just now (removed connection info)
```
[2020-04-28 16:35:45.398] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|
[2020-04-28 16:35:45.398] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|
[2020-04-28 16:35:45.399] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|
[2020-04-28 16:35:46.929] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|
[2020-04-28 16:35:46.944] [renderer1] [error] Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.
[2020-04-28 16:39:22.488] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-04-28 16:39:43.909] [renderer1] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by aaomidi** [comment] 2020-04-28 20:50
To confirm, were you able to connect to this server with azure authentication before? Does authenticating with SqlLogin work?

**Comment by SteveDMurphy** [comment] 2020-04-28 20:52
Thanks for the quick response @aaomidi - yes was able to connect just a couple of hours ago. A teammate was having issues connecting after the update and confirmed that I ran into the same issue after I did the update

**Comment by jtandrew** [comment] 2020-04-28 20:53
I am having the exact same issue on my Mac and on a Windows machine. 
Here is my information.  I was able to connect using this method earlier today.  I have the same issue with the Insiders Build

`[2020-04-28 13:43:23.602] [renderer1] [error] Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined
    at Object.t.isAbsolutePath (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:513:215)
    at e.withProvider (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2178:95)
    at e.doResolveFile (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2179:487)
    at e.resolve (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2179:212)
    at t.createListEntries (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6058:915)
    at t.mapListEntries (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6060:150)
    at r (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6054:333)
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6054:360
    at ZoneDelegate.invoke (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:388:26)
    at Zone.run (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:138:43)
    at /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:872:34
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:188:47)
    at drainMicroTaskQueue (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:595:35)
[2020-04-28 13:43:41.053] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:xxxxxx.database.windows.net|user:first.lastname@company.com|group:C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx
[2020-04-28 13:43:41.053] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:xxxxxx.database.windows.net|user:first.lastname@company.com|group:C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx
[2020-04-28 13:43:41.054] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:xxxxxx.database.windows.net|user:first.lastname@company.com|group:C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx
[2020-04-28 13:43:43.466] [renderer1] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxx.database.windows.net|user:first.lastname@company.com|group:C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx
[2020-04-28 13:44:02.758] [renderer1] [warning] Cannot find node status for session: xxxxxx.database.windows.net_master_first.lastname@company.com_AzureMFA_C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx and node path: xxxxxx.database.windows.net/Databases/DatabaseName
[2020-04-28 13:44:02.797] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxx.database.windows.net|user:first.lastname@company.com|group:C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx
[2020-04-28 13:44:02.797] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxx.database.windows.net|user:first.lastname@company.com|group:C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx
[2020-04-28 13:44:02.798] [renderer1] [info] Removing connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:master|server:xxxxxx.database.windows.net|user:first.lastname@company.com|group:C777F06B-202E-4480-B475-xxxxxxxxxxxxxxx
[2020-04-28 13:44:20.556] [renderer1] [error] Error: Failed to get Azure account token for connection
    at e.connectWithOptions (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5647:607) [<root>]
    at async e.handleDefaultOnConnect (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7815:137) [<root>]
    at async file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7813:205 [<root>]
[2020-04-28 13:44:25.539] [renderer1] [error] Error: Failed to get Azure account token for connection
    at e.connectWithOptions (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5647:607) [<root>]
    at async e.handleDefaultOnConnect (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7815:137) [<root>]
    at async file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7813:205 [<root>]
[2020-04-28 13:44:44.329] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:DatabaseName|server:xxxxxx.database.windows.net|user:first.lastname@company.com|databaseDisplayName:DatabaseName|group:428d2aaa-b0f1-4d78-95cf-xxxxxxxxxxxxxxx
[2020-04-28 13:44:44.329] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:DatabaseName|server:xxxxxx.database.windows.net|user:first.lastname@company.com|databaseDisplayName:DatabaseName|group:428d2aaa-b0f1-4d78-95cf-xxxxxxxxxxxxxxx
[2020-04-28 13:44:44.329] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:DatabaseName|server:xxxxxx.database.windows.net|user:first.lastname@company.com|databaseDisplayName:DatabaseName|group:428d2aaa-b0f1-4d78-95cf-xxxxxxxxxxxxxxx
[2020-04-28 13:44:44.601] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:DatabaseName|server:xxxxxx.database.windows.net|user:first.lastname@company.com|databaseDisplayName:DatabaseName|group:428d2aaa-b0f1-4d78-95cf-xxxxxxxxxxxxxxx
[2020-04-28 13:44:44.621] [renderer1] [error] Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.
`

**Comment by SteveDMurphy** [comment] 2020-04-28 20:54
Interesting twist as well, noticed that the MFA connection works when connecting to a separate sql database but not a data warehouse

**Comment by aaomidi** [comment] 2020-04-28 21:26
My team and I haven't been able to repro this on a SQL DW connection. Unfortunately issues that come with auth are really difficult to debug and get to the bottom of.

I would suggest trying to reset your ADS to a clean state. This would delete any saved settings and connections you have. You can backup these settings if you want to just try a "fresh install/clean state".

ADS stores most of its files on `~/Library/Application Support/azuredatastudio`.

If you close ADS and rename this folder to something like `azuredatastudio-backup` and then open ADS again, a new folder should be created with the default settings.

Login to your AAD account again, and try to connect to this SQL DW server. Does the issue still happen then?

Thanks!
Amir

**Comment by jtandrew** [comment] 2020-04-28 21:36
@aaomidi  I cleared out the settings by doing the rename as you suggested.  When I opened the app I went to add a new connection with the same settings I used before, it opened Chrome and requested my token from my account.  When the token was finished adding it went back to the app and I received the following error message now:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): Device not configured
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 549
ClientConnectionId:00000000-0000-0000-0000-000000000000
```

**Comment by aaomidi** [comment] 2020-04-28 21:38
That's an interesting error, I don't think it has anything to do with this though.

Local internet connectivity/dns issues?

**Comment by jtandrew** [comment] 2020-04-28 21:42
@aaomidi yeah user error on that one.  I type the wrong server name that time, sorry about that.  
On my windows machine I can connect to the same ADW instance with SSMS.

Here is the correct error I am getting 


```
System.Net.Sockets.SocketException (22): Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName) in /xplat/cfxfork/corefx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 5157
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle.Receive(SNIPacket& packet, Int32 timeoutInMilliseconds)
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.ReadSyncOverAsync(Int32 timeoutRemaining, UInt32& error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 549
```

**Comment by aaomidi** [comment] 2020-04-28 22:03
Hmm that still looks like general network issues rather than AAD issues :/

**Comment by jtandrew** [comment] 2020-04-28 22:14
@aaomidi I tried connecting via SQL login from this same machine and it worked.  Then went back to Azure Active Directory - Universal with MFA Support.  I still got the same Invalid Error message.

**Comment by SteveDMurphy** [comment] 2020-04-28 23:14
@aaomidi - sorry for the delay, just got back to try renaming the directory and got the same error, same info in renderer1.log

**Comment by SteveDMurphy** [comment] 2020-04-28 23:16
Adding the log after successfully connecting to a database instead:
```
[2020-04-28 19:10:24.690] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:10:24.690] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:10:24.691] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:10:26.339] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:10:26.355] [renderer1] [error] Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.
-- failure above, success below
[2020-04-28 19:12:57.134] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:12:57.134] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:12:57.134] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:12:59.292] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:12:59.292] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:12:59.292] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:13:00.656] [renderer1] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:13:00.656] [renderer1] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
[2020-04-28 19:13:00.656] [renderer1] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|server:|user:|databaseDisplayName:|group:
```

**Comment by mateeyas** [comment] 2020-04-29 13:27
Have the same issue. Was able to connect just before the software update. And can still connect now with SSMS, just no longer with ADS.

```
[2020-04-29 21:16:26.860] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|user:|databaseDisplayName:|group:
[2020-04-29 21:16:26.860] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|user:|databaseDisplayName:|group:
[2020-04-29 21:16:26.860] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|user:|databaseDisplayName:|group:
[2020-04-29 21:16:28.222] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:|user:|databaseDisplayName:|group:
[2020-04-29 21:16:28.255] [renderer1] [error] Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.
```

**Comment by jtandrew** [comment] 2020-04-29 14:04
I just had to roll back to a previous version to get connections using AAD to work on our ADW.
1.17.0 and Insiders 1.18.0 had the same issue with the NT AUTHORITY\ANONYMOUS LOGON error.

**Comment by aaomidi** [comment] 2020-04-29 20:46
So I've been able to root cause this issue. This issue happens specifically when connecting to the SQL DW DB, rather than the server itself (with no specific DB) (Can someone else confirm this too?)

I think the PR above fixes the problem from some quick testing. We'll discuss a potential hotfix for this release with this change set, but we need to make sure this doesn't break any other services.

Thanks!

**Comment by SteveDMurphy** [comment] 2020-04-29 20:49
@aaomidi - thanks! Can confirm it succeeds when removing the DB for me 👍

**Comment by aaomidi** [comment] 2020-04-29 21:09
To double check this change, please do this if you can:

Close Azure Data Studio

if you're on Windows/Linux (not sure if you can do this on OSX since stricter security requirements)

If you navigate to the location the application is installed:

for me:

```C:\Users\USER_PROFILE\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\azurecore\dist
```

In this path, there is an `extension.js` file, open this file in your favorite editor and search for `https://database.windows.net`, change that URL to be `https://database.windows.net/`.

Open Azure Data Studio and try again

Does this solve your problem?

**Comment by jtandrew** [comment] 2020-04-29 21:23
Yeah I was unable to find that on OSX.  I will wait and hope this fixes it.

**Comment by aaomidi** [comment] 2020-04-29 21:23
@jtandrew That file would be in `/Applications/Azure Data Studio/resources/app` on OSX.

**Comment by jtandrew** [comment] 2020-04-29 21:44
@aaomidi I was able to drill into the package contents and change the URL, that fixed it for me too.  Thanks!!

**Comment by aaomidi** [comment] 2020-04-29 21:45
Thank you for confirming, we'll get a hotfix out ASAP :)

**Comment by kburtram** [comment] 2020-05-01 00:00
The 1.17.1 release contains a fix for this issue.

**Closed** 2020-04-30 23:59 UTC
Labels: Approved, Area - Connection, Bug, Needs Logs, Triage: Needed

**Comment by SteveDMurphy** [comment] 2020-05-01 18:12
Thanks everyone and @aaomidi for the quick help with this! Moved to 1.17.1 today and connection worked perfectly 👍
