### ISSUE TITLE
output list is not available in the property table

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#18393] opened 2022-02-15 19:33 UTC
![image](https://user-images.githubusercontent.com/13777222/154135355-1fcca9e3-b0df-4d57-8ab0-781a423b3f2b.png)

in SSMS:

![image](https://user-images.githubusercontent.com/13777222/154135435-bfa82e34-0f0e-4178-a7dc-e7c9bebf1d96.png)

**Comment by aasimkhan30** [comment] 2022-02-15 20:48
@alanrenmsft , the properties are just displayed in the wrong order. This is a duplicate of #18357

**Closed by aasimkhan30** 2022-02-15 20:48 UTC
Labels: Bug, Triage: Needed, Area - Execution Plan
