### ISSUE TITLE
Model is disposed error in query editor IntelliSense

### ISSUE THREAD

**Issue by AliBaghernejad** [microsoft/azuredatastudio#8373] opened 2019-11-17 07:52 UTC
When you are working with query editor and IntelliSense, pressing ctl+space or dot after an instance will list all members of that instance, but It seems that appeared drop-down menu is frozen and click on the menu items will cause  **Model is disposed** error.
the below record shows the detail:

![intellisenseDisposedModel](https://user-images.githubusercontent.com/10639835/69004644-16907b80-092c-11ea-9180-5c84f1b11a13.gif)

- Azure Data Studio Version:
Version: 1.12.2
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Open a new query editor and insert your query
2. use IntelliSense to list member of an alias instance and the drop-down menu has appeared
3. press enter or click on any appeared items cause **Model is disposed**  error
4. It seems that the drop-down menu is frozen    
                                                                                 
Create a new tab and paste the query into that will fix the issue.

**Comment by Charles-Gagnon** [comment] 2019-12-12 18:25
Closing this as a duplicate of #7504

**Closed by Charles-Gagnon** 2019-12-12 18:25 UTC
Labels: Area - Query Editor, Bug, Triage: Done
