### ISSUE TITLE
Source File Empty/Blank After Viewing Changes in Source Control Tab and Closing Changes View

### ISSUE THREAD

**Issue by ambroselittle** [microsoft/azuredatastudio#15427] opened 2021-05-12 15:42 UTC
## Azure Data Studio Version:

Version: 1.29.0-rc1
Commit: 56cc1202d5af561a54b771169926a8e5401b5a2f
Date: 2021-05-12T03:41:06.659Z (11 hrs ago)
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.4.0

## Steps to Reproduce:
Note, I have seen this behavior for basically as long as I've been using this app (> 1 years). I just work around it, but not today. :) 

1. Open a folder.
2. Open a .sql file somewhere in that structure. Mine happens to be in a subfolder.
3. Make a change and save.
4. Switch to Source Control tab.
5. Select that file in there to view changes.
6. Close the compare/working tree view.

## Actual:
Main source file tab is now empty.

## Expected:
Main source file to still be there/not empty.

## Workaround:
Close the blanked out tab and re-open the source file.

After doing this, if you view again in source control compare, it blanks it out again. 

## Notes
FWIW, opening same folder and interacting in similar way in Visual Studio Code does not have the same problem (and never has).

**Comment by SQLGuyJPS** [comment] 2021-05-13 14:04
Same thing has been happening to me, though recently ADS has started to lock up whenever I try to view changes from the Source Control menu.

**Comment by ambroselittle** [comment] 2021-05-13 14:11
@SQLGuyJPS, that is probably another issue recently fixed. If you want the fix now: 
https://github.com/microsoft/azuredatastudio/issues/15180 
OR, get the RC: 
https://github.com/microsoft/azuredatastudio/issues/15385 
 
Seems to be fixed in the RC, in my initial testing.

**Comment by kburtram** [comment] 2021-08-18 05:37
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/12293.

**Closed by kburtram** 2021-08-18 05:37 UTC
Labels: Bug, Area - Shell
