### ISSUE TITLE
Please Add a "Currently Executing Query" Indicator/Icon to File Tabs

### ISSUE THREAD

**Issue by sebcruz** [Microsoft/azuredatastudio#1265] opened 2018-04-25 20:31 UTC
Please add some kind of indicator to the file tabs to let me know that a query is actively being run.

**Comment by kburtram** [comment] 2018-11-14 01:38
Closing as a duplicate of https://github.com/Microsoft/azuredatastudio/issues/227.  Thanks for the suggestion.

**Closed by kburtram** 2018-11-14 01:38 UTC
Labels: query editor, suggestion, ux
