### ISSUE TITLE
Kernel restarts when a notebook is saved while running

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#6061] opened 2019-06-17 21:30 UTC
Issue Type: <b>Bug</b>

If you Save As... a notebook while a cell is running it cancels out and restarts the kernel

Can repro by adding a SQL code cell for waitfor delay '00:00:10' and then, while it is running, going File...Save As... and saving as a new file.

Azure Data Studio version: azuredatastudio 1.8.0-insider (c1f73255b530e025c5dce4020decc0ef867db22d, 2019-05-21T07:55:53.957Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.40GB free)|
|Process Argv|C:\Users\viharp\AppData\Local\Microsoft\Windows\INetCache\Content.Outlook\H1GFXF1L\HERO001 - (Modified)Create AKS cluster and deploy BDC_CTP3.1.ipynb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.40.0
import|Mic|0.8.0
profiler|Mic|0.8.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1
azdata-sanddance|msr|1.2.0
tsqllint|tsq|1.2.0

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment] 2019-06-18 17:13
This is a dupe of #4539.

**Closed by chlafreniere** 2019-06-18 17:13 UTC
Labels: Area: Notebooks, Bug, Triage: Needed
