### ISSUE TITLE
Opening Database explorer zooms IDE in

### ISSUE THREAD

**Issue by Jopnert** [microsoft/azuredatastudio#19672] opened 2022-06-08 07:25 UTC
Issue Type: <b>Bug</b>

When double clicking on a server in the "Servers" list to explore the server. The IDE zooms in and i've to reset the zoom level.
This happens everytime.
I recently zoomed in manually to show something to a collegue and i think the above behavior started since then.

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (12.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.11.0
simple-data-scripter|sea|0.1.6
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment] 2022-06-08 16:36
Duplicate of https://github.com/microsoft/azuredatastudio/issues/14128

Could you try the latest [Insiders build](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) and see if the workaround fixes your issue?

**Comment by alanrenmsft** [comment] 2022-06-08 17:51
or you can wait for a few days, the new release 1.37 will also include the workaround. please let us know if it doesn't work for you.

**Closed by alanrenmsft** 2022-06-08 17:51 UTC
