### ISSUE TITLE
New Deployment option missing from Connections Viewlet

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#15896] opened 2021-06-24 17:42 UTC
Version: 1.31.0-insider
Commit: c636e24d037463ea3d4eac2130701140b400f2b0
Date: 2021-06-23T05:49:51.602Z
VS Code: 1.56.0
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.5.0

The New Deployment... option from the Connections Viewlet is missing.

STABLE
![Screen Shot 2021-06-24 at 10 26 05 AM](https://user-images.githubusercontent.com/34872381/123306813-97cfcd00-d4d6-11eb-83fe-fe325edf6d0c.png)

INSIDERS
![Screen Shot 2021-06-24 at 10 23 40 AM](https://user-images.githubusercontent.com/34872381/123306520-41628e80-d4d6-11eb-89ff-0ed9ae338280.png)

**Comment by Charles-Gagnon** [comment] 2021-06-24 17:50
Duplicate of https://github.com/microsoft/azuredatastudio/issues/15824

**Closed by Charles-Gagnon** 2021-06-24 17:50 UTC
Labels: Bug, Triage: Needed
