### ISSUE TITLE
Authentication failure AAD

### ISSUE THREAD

**Issue by alexmbaker** [microsoft/azuredatastudio#5711] opened 2019-05-29 05:44 UTC
Given I have 2 Azure Active directories:
* mycompany.onmicrosoft.com - domain verified as "mycompany.org.au"
* myazurehosting.onmicrosoft.com

I have a user account "me" in the directory "mycompany.onmicrosoft.com", my user name is "me@mycompany.org.au"

"me@mycompany.org.au" is also an external "member" user in the directory "myazurehosting.onmicrosoft.com"

I have a number of Azure SQL instances in subscriptions associated with the "myazurehosting.onmicrosoft.com" tenant.

When I try to create a new connection to an Azure SQL Server I:
* Enter my-servername.database.windows.net
* Authentication type - Azure Active Directory - Universal with MFA support
* Account - Select "Add Account" and follow the process to sign 
* Azure AD Tenant - "myazurehosting.onmicrosoft.com"
* Database - "mydatabase"

When I press connect the error "Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON' is shown

I have tried '<Default>' and 'master' as the database and get the same error. 

The connection can be made without issue with SQL Server Management Studio

**Comment by Charles-Gagnon** [comment] 2019-06-07 01:00
Thanks for the report! This seems to be a dupe of #4085 so closing this one - you can follow the linked issue for updates.

**Closed by Charles-Gagnon** 2019-06-07 01:00 UTC
Labels: Area: Connection, Bug
