### ISSUE TITLE
Copy and Paste functionality broken

### ISSUE THREAD

**Issue by kyle-depasquale-schoolzilla** [microsoft/azuredatastudio#7189] opened 2019-09-12 20:38 UTC
Issue Type: <b>Bug</b>

Step 1:
Execute a query and copy a column of results. Paste these results in another program, such as Excel. 

Result: Whatever was previously in the clipboard pastes instead.

Step 2: Copy a different column of results. Paste these into another program, such as Excel.

Result: The column copied from Step 1 pastes, not the column from Step 2.

Azure Data Studio version: Azure Data Studio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T17:14:33.682Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|-psn_0_827594|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.42.0
azuredatastudio-postgresql|Mic|0.2.1
import|Mic|0.10.0
profiler|Mic|0.9.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1

</details>

**Comment by aaomidi** [comment] 2019-09-13 19:28
I'm unable to reproduce this on the same version as the one you're referencing. How are you copy pasting the columns?

**Comment by kyle-depasquale-schoolzilla** [comment] 2019-09-13 19:43
I'll click and highlight a column or two, use Cmd + C or right click and copy and Cmd +P or right click and paste.

**Comment by lpvezina** [comment] 2019-11-05 20:21
Running v 1.13.0, copy/paste of a resultset is still not working properly. 

Version: 1.13.0 (user setup)
Commit: cacd481bff25c890e4130aee392569bae43b7e60
Date: 2019-11-02T00:40:05.147Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by aaomidi** [comment] 2019-11-05 20:30
going to close this in favor of https://github.com/microsoft/azuredatastudio/issues/8210

**Closed by aaomidi** 2019-11-05 20:30 UTC
Labels: Area - Query Editor, Bug
