### ISSUE TITLE
Notebook-related views have blank empty state

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#9080] opened 2020-02-06 23:46 UTC
Examples: https://emptystat.es/

Generally, instead of having a blank list when a list is empty (e.g. no saved books), you want to have a button to create a new book to help the user along

**Comment by MaddyDev** [comment] 2020-02-07 22:00
Duplicate of #8053 We are already working on create book experience and open-book had been added to the view to open any existing books.

**Closed by MaddyDev** 2020-02-07 22:00 UTC
Labels: Area - Notebooks, Enhancement
