### ISSUE TITLE
Object browser data type display incomplete

### ISSUE THREAD

**Issue by SomeTroglodyte** [microsoft/azuredatastudio#13873] opened 2020-12-23 11:11 UTC
(Version: 1.25.1)
Drilling down into database objects under Connections to the level of columns and Proc/Function Parameters displays "(type, input/output, default) as node label and as tooltip.

a) Data type xml is shown empty, i.e. "(, Input, No Default)" where it should be "( **xml**, Input, No Default)"
b) This information would be nicely improved by showing lengths/precision (including e.g. varbinary **(max)**, datetime2 **(precision)** )

**Comment by kburtram** [comment] 2021-08-18 22:52
Thanks for reporting this issue!  This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/11834.  Please add any comments to that issue if there is any additional context you'd like to add for this bug.

**Closed by kburtram** 2021-08-18 22:52 UTC
Labels: Bug, Area - Object Explorer, Triage: Done
