### ISSUE TITLE
"Query Canceled by User" when querying encrypted fields

### ISSUE THREAD

**Issue by C-Roseberry** [microsoft/azuredatastudio#12611] opened 2020-09-24 14:22 UTC
Issue Type: <b>Bug</b>

When querying encrypted fields, query cancels itself, and "Query Canceled by User" message is returned.
- Using Azure Key Vault
- SSMS is working
- Azure account is connected
- "Always Encrypted" is Enabled
- Secure Enclave is not being used

**Steps to Reproduce:**
1. Clean install of Azure Data Studio 1.22.0 (Also attempted with clean install of 1.19.0)
1. Enable "Always Encrypted"
1. Execute query with any encrypted field selected

**Expected Results**
Results are returned for selected encrypted fields

**Actual Results**
Query is canceled by system before results are returned. Following system message is returned:
>Started executing query at Line 1
>(X rows affected)
>Query was canceled by user
>Total execution time: X

No errors are returned in any logs

Azure Data Studio version: azuredatastudio 1.22
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (3.39GB free)|
|Process Argv|-psn_0_208947|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by egorchabala** [comment] 2021-03-02 01:41
Same issue on my end

- macOS 11.2.1
- ADS 1.26.1

**Comment by javacavaj** [comment] 2021-03-05 01:38
Same issue here.

- Using Azure Key Vault

- SSMS is working

- Azure account is connected

- "Always Encrypted" is Enabled

- Secure Enclave is not being used

- macOS 11.2.2

- ADS 1.26.1

I iterated through the archived versions, and the last time this work was ADS v1.20.1

**Comment by Charles-Gagnon** [comment] 2021-03-05 01:57
@Xtrimmer Do you think this might be caused by the SqlClient issue that was recently fixed? We had to roll back the driver update due to another regression so the current driver being used doesn't contain that fix.

**Comment by Xtrimmer** [comment] 2021-03-05 19:35
@Charles-Gagnon it is quite possible, especially if it is within a non-windows environment. We knew that without the Microsoft.Data.SqlClient driver version 2.1.0 or greater, there will be issues with the Always Encrypted feature on MacOS and Linux platforms.

**Comment by disfracted** [comment] 2021-03-05 19:38
I'm experiencing the same thing and I'm on Windows

**Comment by chlafreniere** [comment] 2021-03-10 20:03
Merged into release/1.27.

**Closed by chlafreniere** 2021-03-10 20:03 UTC
Labels: Approved, Area - Query Editor, Bug, Triage: Done
