### ISSUE TITLE
Collation dropdown is slow to load; any other options?

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#23724] opened 2023-07-10 17:35 UTC
The Database properties collation dropdown takes 500ms - 5s to load on my computer.  Is there anything we can do to ease this?

Ideas:

* Select core language first (e.g. Begali), then options second (e.g. `CI_AI`, `CI_AS`, etc.)
* Preload more of the drop-down (after the dialog opens, but before the dropdown is clicked, if possible)
* Typing dropdown filter (similar to how quickpicks work)

**Comment by corivera** [comment] 2023-07-17 22:22
Duplicate of https://github.com/microsoft/azuredatastudio/issues/23648

**Closed by corivera** 2023-07-17 22:22 UTC
Labels: Bug, Triage: Done, Approved, Area - Basic Admin
