### ISSUE TITLE
BDC dashboard partially unreadable in dark theme

### ISSUE THREAD

**Issue by capnsue** [microsoft/azuredatastudio#9349] opened 2020-02-26 16:44 UTC
Issue Type: <b>Bug</b>

using Dark Azure Data Studio theme, some areas of the Big Data cluster dashboard screen have white text on a white background and can't be read.

Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (628fd8d74d94f36313bb6e1528e6ff69dc026df0, 2020-02-25T05:51:05.047Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|127.89GB (107.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.5.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.2.0
datavirtualization|Mic|1.3.0
import|Mic|0.13.1
profiler|Mic|0.11.0
schema-compare|Mic|1.2.0
whoisactive|Mic|0.1.3

</details>

**Comment by capnsue** [comment] 2020-02-26 16:45
![image](https://user-images.githubusercontent.com/6115950/75366894-71bbfd80-588d-11ea-9a58-207e996ffdd5.png)

**Comment by Charles-Gagnon** [comment] 2020-02-26 18:10
Thanks for the feedback @capnsue! I'm going to close this as a dupe of https://github.com/microsoft/azuredatastudio/issues/7400.

As for addressing this - we're doing a overall dashboard refactor which will include moving this over to use that new experience. So with that work we're going to be making sure that dark theme is handled a lot better.

**Closed by Charles-Gagnon** 2020-02-26 18:10 UTC
Labels: Area - Big Data Cluster, Bug, Triage: Needed
