### ISSUE TITLE
When creating a new connection after giving all the details, and when add account section it navigates to a browser to login, once details are given it keeps spinning and never logs in.

### ISSUE THREAD

**Issue by vafe23** [microsoft/azuredatastudio#25704] opened 2024-06-17 19:33 UTC
Type: Bug

When creating a new connection after giving all the details, and when add account section it navigates to a browser to login, once details are given it keeps spinning and never logs in.

Azure Data Studio version: azuredatastudio 1.48.0 (https://github.com/microsoft/azuredatastudio/commit/4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

System Info
Item	Value
CPUs	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)
GPU Status	2d_canvas: enabled
canvas_oop_rasterization: enabled_on
direct_rendering_display_compositor: disabled_off_ok
gpu_compositing: enabled
multiple_raster_threads: enabled_on
opengl: enabled_on
rasterization: enabled
raw_draw: disabled_off_ok
video_decode: enabled
video_encode: enabled
vulkan: disabled_off
webgl: enabled
webgl2: enabled
webgpu: enabled
Load (avg)	undefined
Memory (System)	31.73GB (14.96GB free)
Process Argv	
Screen Reader	no
VM	0%
Extensions (1)
Extension	Author (truncated)	Version
azdata-sanddance	msr	4.0.3

**Comment by m0nkeyc0de** [comment] 2024-06-19 09:35
Hello, I have exactly the same issue when I'm logging in with "Microsoft Azure AD - Universal with MFA support" with the Kusto Plugin.

Once the web browser writes everything is OK, the wheel continues to spin indefinitely in the login form.
![image](https://github.com/microsoft/azuredatastudio/assets/30374340/0a31eb6c-81fc-4571-a354-53160ef0a0c6)

**Comment by cssuh** [comment] 2024-07-10 21:36
duplicate of #25596

**Closed by cssuh** 2024-07-10 21:36 UTC
