### ISSUE TITLE
There are two objects in ConnectionStatusManager._connections for one connection to default

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#4771] opened 2019-03-29 19:44 UTC
Right click a inactive server in OE and select "New query", In onConnectionComplete, this._connectionStatusManager.updateDatabaseName(info); will add master uri to this._connections. When disconnect, only disconnect one. 

This causes issue for notebook attachTo will list the connection.

**Comment by Charles-Gagnon** [comment] 2019-03-29 22:15
getActiveConnectionProfiles is filtering out these additional connections : 

![image](https://user-images.githubusercontent.com/28519865/55265397-54be1b00-5235-11e9-9b09-4ed4d70ed74d.png)

I'm not seeing duplicate entries in the attach to dropdown for notebooks either :

![image](https://user-images.githubusercontent.com/28519865/55265431-833bf600-5235-11e9-90cb-27653ab1a7c9.png)

Could you explain further what the issue is here?

**Comment by Charles-Gagnon** [comment] 2019-03-29 22:20
And disconnecting does loop through all the connections and remove all ones with the same ID as well - I'm seeing both connections removed when I disconnect through right click -> disconnect.

How are you disconnecting from the server that you're seeing this issue?

**Comment by Charles-Gagnon** [comment] 2019-03-29 22:45
So one issue that looks like is happening is that you're creating a new connection when each cell is ran - but then these connections are never cleaned up when the notebook is closed. So you end up with a bunch of connections that look like this :

![image](https://user-images.githubusercontent.com/28519865/55266261-58ec3780-5239-11e9-9e98-0c3f5237327c.png)

The URIs that start with connection:// are from normal connections through OE or whatever and then also from the dropdown in Notebooks. 

But when you click the run button on a cell it calls connect in the requestExecute function 

```
let connectionUri = Utils.generateUri(this._currentConnection, 'notebook');
this._queryRunner = this._instantiationService.createInstance(QueryRunner, connectionUri);
this._connectionManagementService.connect(this._currentConnection, connectionUri).then((result) => {
```

But this connection is never stored in the _connectionsToDispose in notebookModel.ts and thus not cleaned up when the Notebook is closed - so when a new notebook is opened it'll populate with those connections.

**Comment by YurongHe** [comment] 2019-04-01 20:55
I did more investigation on this. I can't repro the issue stated at beginning on latest master.

But I see: when double click the OE server. There will be 4 connections.

![image](https://user-images.githubusercontent.com/43652751/55358903-639b0c80-5485-11e9-9acf-05987926fb74.png)

Close dashboard tab, only one dashboard connection is deleted. 
![image](https://user-images.githubusercontent.com/43652751/55359023-b674c400-5485-11e9-92b3-9b79cc194c6a.png)

While disconnect server from right click on OE server, the other two are deleted properly.

**Comment by kburtram** [comment] 2019-12-03 00:30
This doesn't appear to have an user facing impact so I'll close it now.

**Closed by kburtram** 2019-12-03 00:30 UTC
Labels: Area - Connection, Bug
