### ISSUE TITLE
Azure Data Studio the generated missing index is invalid.

### ISSUE THREAD

**Issue by alibaghernejad** [microsoft/azuredatastudio#24042] opened 2023-08-01 11:01 UTC
When using **SQL Execution Plan** for query performance tuning, One of the helpful features is the **missing index feature**. 

During the tuning of one of our stored procedures in Azure Data Studio, I noticed that one of the suggested indexes for the query is invalid. The same query using SSMS does generate a valid missing Index. By the way, here are the generated index, screencasts, and errors related to the issue.

`sql
/*
Missing Index Details from Azure Data Studio Invalid Missing Index suggestion.sql
The Query Processor estimates that implementing the following index could improve the query cost by 27.3501%.
*/

CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TagContentRelated] ([TagID],[IsDeleted])
INCLUDE ([TagID],[IsDeleted],[Priority])
GO
`
`Started executing query at Line 1
Msg 1909, Level 16, State 2, Line 8
Cannot use duplicate column names in index. Column name 'TagID' listed more than once.
Msg 1909, Level 16, State 2, Line 8
Cannot use duplicate column names in index. Column name 'IsDeleted' listed more than once.
Total execution time: 00:00:00.078`

- Azure Data Studio Version:
Version: 1.43.0
Commit: b790d700898b1095d83e62f0de14678a58222520
Date: 2023-04-10T23:08:07.209Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.38-1-MANJARO

- OS Version:
 Linux abmanjaro 6.1.38-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jul  5 23:49:30 UTC 2023 x86_64 GNU/Linux

Steps to Reproduce:

1. Open Azure Data Studio and enable  **Actual Plan**.
2. Calling the Sp.
3. The generated missing index by Azure Data Studio is invalid.

![Azure Data Studio Invalid Missing Index suggestion](https://github.com/microsoft/azuredatastudio/assets/10639835/63081522-8f70-4c78-8942-55a86d792561)

![Sql Server management Studio Missing Index suggestion](https://github.com/microsoft/azuredatastudio/assets/10639835/b5d59ed2-f6bb-41ab-b5ea-ae5d50751a8f)

Lets me know if more information is needed.

**Comment by erinstellato-ms** [comment] 2023-08-30 21:41
@alibaghernejad Thank you for logging this issue! FYI that I'm closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/20249. I am linking to this issue from the other so that your demo code and information is available if needed. Feel free to upvote that issue (upvoting and comments help us determine priority), thanks!

**Closed by erinstellato-ms** 2023-08-30 21:41 UTC
Labels: Bug, Area - Query Editor, Triage: Needed, Subarea - Execution Plan, Duplicate
