### ISSUE TITLE
Keeps asking to refresh credentials

### ISSUE THREAD

**Issue by magnusbratt** [microsoft/azuredatastudio#8903] opened 2020-01-16 19:38 UTC
Issue Type: <b>Bug</b>

1. Click on Connections icon in left side menu
2. Under Azure, click Sign in to Azure...
3. In the Linked Accounts popup, click Add an account
4. Click Copy & Open
5. Complete sign in. The Account is now listed correctly.
6. Click Close to close the Linked Accounts popup/window
7. In the connections pane, under Azure, click > to expand resources.

Actual result:
The Linked Accounts window opens, with the message "You need to refresh the credentials for this account".

I looked in the logs, and found this in 5-Deployments.log that might be relevant:

    > docker version --format "{{json .}}"
    > az --version
    > azdata -v
    > kubectl version -o json --client
    stderr: /bin/sh: 1: docker: not found
    stderr: 
    stderr: /bin/sh: 1: az: not found
    stderr: 
    stderr: /bin/sh: 1: azdata: not found
    stderr: 
    stderr: /bin/sh: 1: kubectl: not found
    stderr: 
    >>> docker version --format "{{json .}}"    … exited with code: 127
	>>> docker version --format "{{json .}}"   … errored out: Process exited with code 127	>>> Ignoring error in execution and continuing tool deployment    >>> az --version    … exited with code: 127
	>>> az --version   … errored out: Process exited with code 127	>>> Ignoring error in execution and continuing tool deployment    >>> azdata -v    … exited with code: 127
	>>> azdata -v   … errored out: Process exited with code 127	>>> Ignoring error in execution and continuing tool deployment    >>> kubectl version -o json --client    … exited with code: 127
	>>> kubectl version -o json --client   … errored out: Process exited with code 127	>>> Ignoring error in execution and continuing tool deployment

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:35:43.481Z)
OS version: Linux x64 4.19.60-06185-g54aa50936831

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 2207)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|4.84GB (0.80GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment] 2020-01-16 19:50
@magnusbratt The errors are probably unrelated - those are from the deployment dialog but it seems like you're having an issue with the Azure viewlet.

Could you repro the issue and then open the developer console (Help -> Toggle Developer Tools) and click on the **Console** tab, then paste any errors you see there? That will hopefully help track down what the issue is.

**Comment by magnusbratt** [comment] 2020-01-16 20:24
OK. This is from the Console. By the way, I am currently on a Chromebook, but get the same issue on my Windows machine.

![image](https://user-images.githubusercontent.com/6708638/72560026-706ade80-38a6-11ea-9728-759105e32ee2.png)

**Comment by magnusbratt** [comment] 2020-01-16 20:36
I tried with another account, and for this account I instead get the message "No Subscriptions Found", which might be correct, since that account does not have any active subscriptions. 

![image](https://user-images.githubusercontent.com/6708638/72560604-b2e0eb00-38a7-11ea-8fba-c41cc2c8790c.png)

**Comment by aaomidi** [comment] 2020-03-09 21:00
I presume a lot of these issues will be partially solved with MSAL v2.0. In the meantime, you can try deleting the files from %appdata%\azuredatastudio\Azure Accounts\ if you're on a windows system.

**Comment by aaomidi** [comment] 2020-04-02 18:46
This is probably fixed with the latest insiders build. If it's not please comment back and I'll reopen the issue.

**Closed by aaomidi** 2020-04-02 18:46 UTC
Labels: Area - Azure, Bug, Triage: Done

**Comment by magnusbratt** [comment] 2020-04-08 16:38
@aaomidi I just tried with the insiders build on a Mac and it still did not work. I replied in issue #9885.
