### ISSUE TITLE
Azure Data Studio

### ISSUE THREAD

**Issue by DaveNavarro** [microsoft/azuredatastudio#18774] opened 2022-03-18 16:34 UTC
There are times that I use the Filter feature in SQL Server Management Studio (SSMS) to find / show tables or stored procedures (what ever) that I need to work with.

Since Azure Data Studio doesn't have this feature, I have to use both apps. I do most of my work in Azure Data Studio (ADS) but have to find the tables / sprocs I need to edit in SSMS.

I'm requesting please, to have the SSMS filter feature added to ADS.

Thank you,

~ Dave

**Comment by Charles-Gagnon** [comment] 2022-03-18 16:52
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/15296

**Closed by Charles-Gagnon** 2022-03-18 16:52 UTC
