### ISSUE TITLE
Notebook cell output doesnt scroll or wrap and is just visually truncated

### ISSUE THREAD

**Issue by twright-msft** [Microsoft/azuredatastudio#4876] opened 2019-04-05 14:55 UTC
Issue Type: <b>Bug</b>

Run some cell that produces output in the cell that is too long to fit on the screen.  It wont wrap, nor does it have a scroll bar.  You have to copy/paste the text out of there into someplace else.

![image](https://user-images.githubusercontent.com/14988070/55636632-1d40f880-5778-11e9-9a4b-c472bc84ca88.png)

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_3162884|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
ssmskeymap|kev|1.1.0
sql-vnext|Mic|0.11.0
sqlservbdc-app-deploy|Mic|2.3.0

</details>

**Comment by chlafreniere** [comment] 2019-04-05 16:31
This is a dupe of #3779, which we're tracking to fix soon.

**Closed by chlafreniere** 2019-04-05 16:31 UTC
Labels: Area: Notebooks, Enhancement
