### ISSUE TITLE
Database names listed according to case

### ISSUE THREAD

**Issue by WallyEwi** [microsoft/azuredatastudio#22228] opened 2023-03-08 17:39 UTC
Issue Type: <b>Bug</b>

There is inconsistency with the listing of the databases.  In the Connection Details pop-out, the databases are ordered ignoring case, but in the drop-down list at the top of the editor window, databases beginning with an upper-case letter are listed first.  I'm used to case being ignored, which is what I would prefer, but either way would be nice so there is a consistency.  

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (2.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-select-top-n|jim|0.0.5
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
dacpac|Mic|1.12.0
import|Mic|1.5.4
profiler|Mic|0.12.2
schema-compare|Mic|1.18.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|0.21.0
sql-migration|Mic|1.4.0
whoisactive|Mic|0.1.4
extra-sql-script-as|pac|0.5.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by alanrenmsft** [comment] 2023-03-08 18:52
@WallyEwi this is a dupe of https://github.com/microsoft/azuredatastudio/issues/4105, the issue has been fixed and will be available in the next stable build. You can try the latest insider build to verify: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch

**Closed by alanrenmsft** 2023-03-08 18:52 UTC
Labels: Bug, Area - Query Editor, Duplicate

**Comment by WallyEwi** [comment] 2023-03-08 18:57
Thanks!  Sorry my search didn't turn up the previously posted issue.
