### ISSUE TITLE
Error: Specified tenant with ID 'undefined' not found. when connecting to Kusto

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#18507] opened 2022-02-20 21:29 UTC
![image](https://user-images.githubusercontent.com/14988070/154864929-8f27d299-77b2-46b2-83df-2347e66ef60a.png)
I dropped and added back my Azure AD authentication just to be sure.

I even get this error when trying to connect to the samples: https://help.kusto.windows.net

Version: 1.34.0 (user setup)
Commit: 83a4316cf89cbf961a0f09a72c861379cfd01fa9
Date: 2021-12-15T20:47:33.863Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

Kusto extension version: 0.5.4

**Comment by Charles-Gagnon** [comment] 2022-02-21 07:38
@qifahs @JustinMDotNet

**Comment by JustinMDotNet** [comment] 2022-03-01 23:02
This has been reported and triaged here: of https://github.com/microsoft/azuredatastudio/issues/17894

**Comment by kburtram** [comment] 2022-04-04 18:20
This appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/17894.  Please add any missing context to that issue if applicable.  Thanks!

**Closed by kburtram** 2022-04-04 18:20 UTC
Labels: Bug, Area - Connection, Triage: Done, Area - Kusto
