### ISSUE TITLE
Drag & drop for server grouping doesn't always work correctly

### ISSUE THREAD

**Issue by cpichuka** [microsoft/azuredatastudio#24397] opened 2023-09-13 14:17 UTC
Type: <b>Bug</b>

Steps to Reproduce:

1. Open ADS
2. Create a server group
3. Create multiple connections (say 2 or 3)
4. Drag the connection to server group
5. Drag 2nd or 3rd connection to the server group, it doesn't work always correctly.

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (12.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-fr|Mic|1.42.0
ads-language-pack-ja|Mic|1.42.0
ads-oracle-datamigration-extension|Mic|1.0.0-rc0087
azuredatastudio-dma-oracle|Mic|4.2.1
azuredatastudio-oracle|Mic|0.1.3
azuredatastudio-postgresql|Mic|0.2.7
dsct-db2|Mic|0.0.1
dsct-oracle-to-ms-sql|Mic|0.6.0
net-6-runtime|Mic|1.1.0
postgresql-migration|Mic|2.0.6
schema-compare|Mic|1.18.0
sql-database-projects|Mic|1.0.1
sql-migration|Mic|1.4.9
whoisactive|Mic|0.1.4

</details>

**Comment by cheenamalhotra** [comment] 2023-09-13 17:59
Duplicate of #24250 

Hi @cpichuka 
We've addressed this issue in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and will be part of next release.

**Closed by cheenamalhotra** 2023-09-13 17:59 UTC
Labels: Bug, Area - Object Explorer, Triage: Done
