### ISSUE TITLE
Cannot read property length of null when change tabs

### ISSUE THREAD

**Issue by fathermrsing** [microsoft/azuredatastudio#14019] opened 2021-01-22 07:32 UTC
Open my saved query in a tab (A)
Open my other saved query in a tab (B)
In the tab B execute any query which finishes unsuccessfully (I have a really long thing for data migration. It gets stuck on a previously-good INSERT INTO SELECT FROM query, the views which it's selecting from use complex joins and rownumbers, but all the views are defined in Tab A, so I have to fix them there)
Cancel the query so my macbook doesn't sound like a desktop (fans) (The query would run for thirty minutes at least, if I let it. I think it's an infinite loop).
Switch to tab A
Switch to tab B
Expected result: successful switch to tab B
Actual result: Tab B disconnects and closes, and an error message pops up.

**Comment by kburtram** [comment] 2021-08-23 19:10
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/8141.  Thanks for reporting this bug.  We'll investigate to try to determine what's happening here.

**Closed by kburtram** 2021-08-23 19:10 UTC
Labels: Bug, Area - Query Editor
