### ISSUE TITLE
[ADS]-[BDC]-Spark Job Submission from Command Pallet - Errors Cannot read property ‘label’ of undefined 

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#6588] opened 2019-08-05 12:46 UTC
Issue Type: <b>Bug</b>

Hi Team,
 
I am using the following insider build of ADS 
 
Version: 1.10.0-insider (user setup)
Commit: 2c12b95e176e94f4e55b2a66774abfaf837c2dbb
Date: 2019-07-30T18:50:20.139Z
VS Code 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
 
Name: mssql
Id: microsoft.mssql
Description: 
Version: 0.1.0
Publisher: Microsoft
 
From the command pallet if I try to submit a spark job its failing with the error “Cannot read property ‘label’ of undefined. Is this a known issue that is being addressed?

In the Log ( Extension Host) we notice the following failures
 
[2019-08-03 01:00:19.061] [exthost] [error] [Microsoft.mssql] provider FAILED
[2019-08-03 01:00:19.061] [exthost] [error] Error: DisposableStore is missing...
    at SuggestAdapter._convertCompletionItem (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:42814:23)
    at define.resolveCompletionItem.async_1.asPromise.then.resolvedItem (c:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:42799:29)
 
Developer tools shows these errors
 
Cannot read property 'label' of undefined
console.(anonymous function) @ C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:2280
 
Unhandled Promise rejection: Canceled ; Zone: <root> ; Task: Promise.then ; Value: Error: Canceled
    at Object.canceled (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:5669:23)
    at Delayer.cancel (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:12493:38)
    at ThrottledDelayer.cancel (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:12529:26)
    at OutputFileListener.unwatch (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:249476:34)
    at FileOutputChannelModel.onModelWillDispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:249537:30)
    at disposable.model.onWillDispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:249418:26)
    at Emitter.fire (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:10435:38)
    at TextModel.dispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:88815:33)
    at Proxy.destroyModel (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:114884:29)
    at ResourceEditorModel.dispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:175676:35)
    at modelPromise.then.model (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:305754:31)
    at ZoneDelegate.invoke (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:595:35) Canceled: Canceled
    at Object.canceled (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:5669:23)
    at Delayer.cancel (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:12493:38)
    at ThrottledDelayer.cancel (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:12529:26)
    at OutputFileListener.unwatch (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:249476:34)
    at FileOutputChannelModel.onModelWillDispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:249537:30)
    at disposable.model.onWillDispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:249418:26)
    at Emitter.fire (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:10435:38)
    at TextModel.dispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:88815:33)
    at Proxy.destroyModel (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:114884:29)
    at ResourceEditorModel.dispose (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:175676:35)
    at modelPromise.then.model (file:///C:/Users/pradm/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.main.js:305754:31)
    at ZoneDelegate.invoke (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:595:35)
console.(anonymous function) @ C:\Users\pradm\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules\zone.js\dist\zone-node.js:2280

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (f5184ba282c284ea089f83c8a5c83d0379167c57, 2019-08-05T07:52:19.234Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (12 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kevcunnane** [comment] 2019-08-05 17:32
This is a duplicate of #6576, closing as I've a fix in PR referencing that bug and it has some additional context.

**Closed by kevcunnane** 2019-08-05 17:32 UTC
