### ISSUE TITLE
Azure Flat File Import Service launch error 

### ISSUE THREAD

**Issue by PovilasID** [microsoft/azuredatastudio#13419] opened 2020-11-14 17:00 UTC
- Azure Data Studio Version:
1.24.0
Steps to Reproduce:

1. Install new instance of Azure Data studio
2. Install import plugin 
3. `Ctrl+I`
In the bottom right coroner shows up a notification:
![Screenshot 2020-11-14 183201](https://user-images.githubusercontent.com/396243/99152617-87878200-26ab-11eb-9dc9-ab5f908d33b5.png)

**Comment by aasimkhan30** [comment] 2020-12-02 23:04
@PovilasID this might be due to a download failure. Does restarting ADS and opening import wizard fixes this issue for you?

**Comment by aasimkhan30** [comment] 2021-03-02 22:07
Closing this issue as it cannot be reproduced on the latest version

**Closed** 2021-03-02 22:06 UTC
Labels: Area - SQL Import, Bug, Needs More Info, Triage: Done
