### ISSUE TITLE
ZH-TW

### ISSUE THREAD

**Issue by jcs2677** [Microsoft/azuredatastudio#3399] opened 2018-12-04 02:31 UTC
- Azure Data Studio Version:

Steps to Reproduce:

**Comment by kburtram** [comment] 2018-12-04 02:40
@jcs2677 could you please add additional content to this issue?  Is this a suggestion to support Traditional Chinese localization?

**Comment by kburtram** [comment] 2018-12-04 20:53
Closing since the issue is lacking necessary details.  Please reopen with additional context.

**Closed by kburtram** 2018-12-04 20:53 UTC
Labels: more info
