### ISSUE TITLE
Add Ability to Create Diagrams (ERD) From Existing Tables and Create or Update Schema From Diagram

### ISSUE THREAD

**Issue by bleepzter** [microsoft/azuredatastudio#9360] opened 2020-02-26 23:54 UTC
In SSMS you can add a new diagram and either:
1. Model the parts or the entire database by bringing in existing tables.
2. Create new tables and their relationships.

This feature is missing from Azure Data Studio which is the most useful feature in SSMS when designing a new database.

**Comment by kburtram** [comment] 2021-09-10 21:31
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/94.  Thanks for opening the suggestion!

**Closed by kburtram** 2021-09-10 21:31 UTC
Labels: Area - Object Explorer, Enhancement, Triage: Done
