### ISSUE TITLE
Connection blade pre-fills connection details with wrong tenant id when B2B guest tenant was used on saved connection

### ISSUE THREAD

**Issue by jikuja** [microsoft/azuredatastudio#21255] opened 2022-11-17 15:52 UTC
- Azure Data Studio Version: 1.14.0
- OS Version: OS X 10.15.7 / Windows 10

Steps to Reproduce:

1. Open a new notebook with SQL kernel
2. Click `attach to` dropdown menu and select `Change connection`
3. Open en entry that WAS using B2B guest tenant on `recent` or on `Browse` => `Saved` list
4. Connection details will be pre-filled
5. Azure AD tenant is reset back to account's home tenant
6. Without extra step to change Azure AD tenant into correct B2B guest tenant database connection will fail

Does this issue occur when all extensions are disabled?: Yes

Related tickets:
* https://github.com/microsoft/azuredatastudio/issues/21253
* https://github.com/microsoft/azuredatastudio/issues/21254

**Comment by cheenamalhotra** [comment] 2022-11-17 19:28
Hi @jikuja 

This is a known issue (https://github.com/microsoft/azuredatastudio/issues/20517) and has been recently fixed with https://github.com/microsoft/azuredatastudio/pull/21190, it's targeted for the December release. 

Could you please let us know if the latest Insiders build resolves the issue for you, as it contains the fix I linked above:
[Try out the latest insiders build from main branch](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch)

**Comment by jikuja** [comment] 2022-11-17 20:24
ty. Used wrong keywords with a search.

Tried insider build: 
Version: 1.41.0-insider
Commit: a37d6230f94943ee49dbe4109a40dd5d3d2a0d9c
Date: 2022-11-16T06:33:42.633Z (1 day ago)
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin x64 19.6.0

Results: 
Fix **not** fully working:

1. Open a new notebook with SQL kernel
2. Click attach to dropdown menu and select Change connection
3. Open en entry that WAS using B2B guest tenant on Browse => Saved list
4. Connection details will be pre-filled
5. Azure AD tenant is reset back to account's home tenant
6. If I click same saved connection on list again then the correct tenant is shown

or

1. Open a new notebook with SQL kernel
2. Click attach to dropdown menu and select Change connection
3. Open en entry that WAS using B2B guest tenant on recent list
4. Connection details will be pre-filled
5. Azure AD tenant is reset back to account's home tenant
6. If I click same recent connection on list again then the correct tenant is shown

**Comment by cheenamalhotra** [comment] 2022-11-17 21:11
Thanks for quick feedback!

I can see the behavior in `Browse > Azure`, which I would agree got missed out.
But `Browse > Recent` or `Recent list` are working fine for me, but I'll take a closer look as I fix the `Azure` tab.

I did notice it defaults to the first index when you click 'Change Connection' which is by design, since it doesn't populate previous connection at that time.

**Comment by cheenamalhotra** [comment] 2022-12-02 22:38
Hi @jikuja 

I will close the issue as resolved with #21289 and fix is now available for validation in latest insiders release.
Let us know if you experience this issue in future releases.

**Closed by cheenamalhotra** 2022-12-02 22:38 UTC
Labels: Area - Azure, Triage: Done
