### ISSUE TITLE
DW Dashboard tab never loads

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24870] opened 2023-11-02 21:39 UTC
Insiders/RC1

1. Install `Azure SQL Data Warehouse Insights` extension
2. Open server dashboard

The `SQL DW Dashboard` tab is in the loading state forever. No obvious errors in the console logs

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/da4e533f-8ed8-4efd-a9ed-354527c0332e)

**Comment by Charles-Gagnon** [comment] 2023-11-02 21:39
@aasimkhan30 @kisantia another thing to consider for ask mode

**Comment by kisantia** [comment] 2023-11-03 15:49
Approved - this fix that @aasimkhan30 looks low risk enough to take and since it was a regression from last release

**Comment by kisantia** [comment] 2023-11-04 00:47
Confirmed this is now fixed in the latest RC build

**Closed by kisantia** 2023-11-04 00:47 UTC
Labels: Bug, Area - Shell, Approved
