### ISSUE TITLE
Editing a saved connection causes it to jump to the bottom of its group in OE

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1468] opened 2018-05-23 00:32 UTC
- SQL Operations Studio Version: 5/22 daily build (6aac0b6)

Steps to Reproduce:
1. Save a connection
2. Open the connection dialog and select your saved connection from recent connections or saved connections
3. Edit something about the connection (e.g. open advanced properties and increment the connect timeout by 1)
4. Hit connect

Expected behavior: The connection is updated but stays where it is in OE
Actual behavior: The connection is updated but moves to the bottom of the server group in OE

Before (the relevant connection is second):
![Connection is shown in the middle of other connections in its group](https://user-images.githubusercontent.com/3758704/40397152-df3ef69a-5de5-11e8-8178-30efdb757f45.png)

After:
![Connection is shown at the bottom of the other connections in its group](https://user-images.githubusercontent.com/3758704/40397149-ddefe858-5de5-11e8-9f15-25c903d2bbee.png)

**Comment by kburtram** [comment] 2021-04-23 17:49
Closing older issues.  We are looking at improving sorting of connection in OE at the moment.  @caohai you may see if this is an easy fix while looking in this area.  Thanks!

**Closed by kburtram** 2021-04-23 17:49 UTC
Labels: Area - Data Explorer, Bug

**Comment by caohai** [comment] 2021-04-23 19:54
I followed the steps and cannot reproduce the issue in latest official build. The issue should have been fixed in previous version.
```
Version: 1.28.0
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
```
![ezgif-3-9e3e7d13c1d4](https://user-images.githubusercontent.com/21186993/115923261-d263ad80-a432-11eb-974c-57418d397a34.gif)
