### ISSUE TITLE
Visualization setting not remembered if the cell is executed after the chart is set

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#14179] opened 2021-02-05 21:14 UTC
- Azure Data Studio Version: 1.25.2

Steps to Reproduce:

- Run a query on Notebook
- Change it to Pie chart
- Rerun the query

The chart changes to table instead of Pie. Is this a known issue ?

**Comment by chlafreniere** [comment] 2021-02-08 22:47
This is a dupe of #185, so closing.. Let's use that issue to track (it already has Impact: Live site).

**Closed by chlafreniere** 2021-02-08 22:47 UTC
Labels: Area - Notebooks, Bug, Impact: Live site, Triage: Needed
