### ISSUE TITLE
"service component could not start" Source: SQL Server Import (Extension)

### ISSUE THREAD

**Issue by rmvp** [microsoft/azuredatastudio#7321] opened 2019-09-23 19:30 UTC
Issue Type: <b>Bug</b>

When I start Azure Data Studio I get notification staying that; 
"service component could not start"
Source: SQL Server Import (Extension)
Then, If I try to run the import wizard, I get the following;
command 'flatFileimport.start' not found 

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T17:09:00.875Z)
OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2942)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (4.00GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rmvp** [comment] 2019-09-23 19:37
![Screenshot from 2019-09-23 14-35-37](https://user-images.githubusercontent.com/30558303/65456731-95c37080-de0f-11e9-9879-596c79b889b0.png)

**Comment by chlafreniere** [comment] 2019-09-23 19:46
@rmvp can you ensure that you have the latest version of the import extension?

**Comment by rmvp** [comment] 2019-09-23 19:59
@chlafreniere 
Name: SQL Server Import
Id: microsoft.import
Description: SQL Server Import for Azure Data Studio supports importing CSV or JSON files into SQL Server.
Version: 0.10.0
Publisher: Microsoft
VS Marketplace Link: undefined?itemName=Microsoft.import

**Comment by Charles-Gagnon** [comment] 2019-09-23 20:21
I'm going to close this as a duplicate of #2716 since they seem to be the same. Please use that one for updating with further information!

**Closed by Charles-Gagnon** 2019-09-23 20:21 UTC
Labels: Area: SQL Import, Bug, Triage: Needed
