### ISSUE TITLE
Only Seeing Last Plan with Actual Plan Command

### ISSUE THREAD

**Issue by ambroselittle** [microsoft/azuredatastudio#2663] opened 2018-09-21 15:26 UTC
- SQL Operations Studio Version: Version 0.33.7-insider (0.33.7-insider)  
- macOS 10.13.6 (17G2307)

Also tried it on the current stable version. Actually, that's where I found it first..

Steps to Reproduce:

1. Create a query window with > 1 queries.
2. Use Run Current Query with Actual Plan command.

Actual:
Seems to cycle through the query plans in the Query Plan tab.
See: https://www.dropbox.com/s/jng6j59n7okxp0r/sqlops-actual-plan-bug.mov?dl=0

Expected:
Show them all, similar to Explain.

Maybe my expectations are just off?

**Comment by ambroselittle** [comment] 2018-11-19 20:56
I can confirm this is still an issue in Version 1.2.4 (1.2.4). 

This is more or less the only thing that keeps me having to run Parallels and SMS. Would love to see it fixed!

**Comment by kburtram** [comment] 2018-12-11 20:50
This is basically the same issue as https://github.com/Microsoft/azuredatastudio/issues/1995.  The problem is that showplan control we're using only renders one showplan XML document at a time.

If there are multiple statements within a batch then only a single XML showplan is returned for all the statements in the batch when getting the estimated plan.  If there are multiple batches then one XML showplan is returned per-batch with estimated.  With actual plans one XML document is returned per statement regardless of batches.

We have a couple different ideas how to resolve this limitation, but this isn't fixed in Dec release.

**Comment by mozart27** [comment] 2019-04-03 13:28
Is there any news on when this issue might be fixed?

**Comment by ambroselittle** [comment] 2019-04-10 20:15
@kburtram, I'm not trying to be snarky, but the estimated shows multiple plans, so isn't this just a matter of swapping in the same control/code used on estimated for displaying actual? If you point me in the right direction, I'll submit a PR.

**Comment by jsmith8858** [comment] 2019-04-13 14:50
Any updates here? I agree with the prior post -- the code that displays the estimated plan clearly can render multiple plans in a list, surely this should be fairly easy to leverage the same code/technique for the actual plans?

**Comment by ambroselittle** [comment] 2020-05-13 18:36
I have a whole horde of people at my company who'd jump to ADS if this one simple feature were fixed. Any update? Can I help/do you take PRs?

**Comment by kburtram** [comment] 2021-04-23 18:02
@ambroselittle sorry I missed your previous comment (just looking through older issues today).  If you're still interested in submitted a PR for this let me know and I can point you in the write direction.  I think the fix may be a little more complicated than just swapping the estimated and actual code paths.

**Comment by ambroselittle** [comment] 2021-04-26 17:05
@kburtram, yes. At least am willing to look at it.

**Comment by ambroselittle** [comment] 2021-05-12 15:46
@kburtram, can ye point me in the right direction?

**Comment by kburtram** [comment] 2021-05-12 15:54
@ambroselittle I'll put together some suggestions on how to fix this and reply back later today.  Sorry for the delay.

**Comment by aasimkhan30** [comment] 2022-04-18 18:20
This is fixed in the new execution plan feature

**Closed by aasimkhan30** 2022-04-18 18:20 UTC
Labels: Bug, Area - Query Plan (Deprecated)
