### ISSUE TITLE
Ignore dbo : dbo.ProcName vs Proc name are treated as difference in schema compare

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6189] opened 2019-06-27 18:16 UTC
Issue Type: <b>Bug</b>

The comparison is showing that there is a change in a view and a stored procedure.  The only difference between the two are, for example:

create procedure AddToLog
create procedure [dbo].[AddToLog]

These should not be considered different.

Is there an option that will consider these to be the same and not requiring a change?

Left database: SQL 2008 R2.  Right database: Azure SQL

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (19.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by glittle** [comment] 2019-06-27 19:41
This is for the Schema Compare extension.

**Comment by udeeshagautam** [comment] 2019-06-29 00:40
This repros for store proc differences in both ADS and SSDT - seems like DacFx treats them as different

**Comment by kisantia** [comment] 2020-11-05 00:55
It seems by design to me that these two are treated differently. If a user's default schema isn't dbo, then it won't be the same so that assumption can't be made. Does this make sense or am I missing something?

For example, if a user's default schema is "testSchema" then creating a stored proc without the schema specified will create it in "testSchema", not "dbo".  
![image](https://user-images.githubusercontent.com/31145923/98182986-0286b680-1ebc-11eb-95cc-6e462257e9b0.png)

**Comment by kisantia** [comment] 2021-01-28 18:44
closing as by design. As mentioned above, dbo isn't always a user's default schema, so the current behavior makes sense.

**Closed by kisantia** 2021-01-28 18:44 UTC
Labels: Area - Schema Compare, Bug, Triage: Done, Upstream
