### ISSUE TITLE
Script.Postdeploy files from Visual Studio project cause build error

### ISSUE THREAD

**Issue by klandymore** [microsoft/azuredatastudio#16930] opened 2021-08-30 00:51 UTC
Issue Type: <b>Bug</b>

- Azure Data Studio Version: 1.32.0
- OS Version: Mac OS 11.5.2
- SQL Database Projects extension 0.12.0

Steps to Reproduce:

1. Clone GIT repo with Visual Studio Solution containing SSDT project with Post Deploy script
2. Reference file in Script.PostDeploy.sql e.g. :r Dir1\Dir2\MyScript.sql
3. Right click SQL Project, select Build

Build output (some xx sub'd by me, note also the / and \ in paths)

`stdout: /Users/xx/source/xx/MySSDTProject/Script.PostDeployment1.sql(10,4,10,4): Build error SQL72001: The included file Subdir1\Seed\FilenameWithMergeStatement.sql (/Users/xx/source/xx/MySSDTProject/Subdir1\Seed\FilenamewithMergeStatement.sql) does not exist. [/Users/xx/source/xx/MySSDTProject/MySSDTProject.sqlproj]`

Extension version: 0.12.0
Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:09:20.282Z)
OS version: Darwin x64 20.6.0

**Comment by klandymore** [comment] 2021-08-30 01:04
Just wanted to add, the sqlproj file builds and publishes perfectly fine in Visual Studio 2019 on Windows. I did the conversion that Azure Data Studio wanted when initially opening the file, and it still works fine in Visual Studio 2019 on Windows.

**Comment by klandymore** [comment] 2021-08-30 15:32
if I update the direction of the slashes to / in :r lines in the Script.PostDeploy file, then the solution will build and publish as expected. How do we ensure this can be managed on both Windows and Mac.

**Comment by klandymore** [comment] 2021-08-30 22:18
Also, I'm not seeing publish execute successfully on either windows or mac for this particular project.

**Comment by kisantia** [comment] 2021-08-31 20:49
@klandymore to clarify, did you mean the build was not successful on windows or mac for the project using ADS only after changing to forward slashes? Was build still working when using VS after changing the direction of the slashes in the :r lines?

**Comment by LanceTrahan** [comment] 2022-08-07 03:50
> @klandymore to clarify, did you mean the build was not successful on windows or mac for the project using ADS only after changing to forward slashes? Was build still working when using VS after changing the direction of the slashes in the :r lines?

I'm having this issue as well. Trying to build from ADS or VSCode with the SQL Database Projects extension fails on Mac until I flip the slashes for the r: entries in the PostDeployment.sql file. Hope that clarifies.

Here are my versions for reference:
Azure Data Studio Version: 1.38.0
OS Version: Mac OS 10.14.6
SQL Database Projects extension 0.18.0

**Comment by SakshiS-harma** [comment] 2022-09-28 22:34
> Also, I'm not seeing publish execute successfully on either windows or mac for this particular project.

@klandymore, I am able to repro the original mentioned issue. But I am not seeing any problems with publish on windows or mac (for mac, I had the forward slashes in place).
Can you please confirm if you are still seeing the issue? I am working on a fix for the original mentioned issue.

**Comment by SakshiS-harma** [comment] 2022-10-19 22:44
The issue is fixed on the DacFx side. It will be brought into ADS when a new version of Microsoft.Build.Sql is released.

**Closed by SakshiS-harma** 2022-10-19 22:44 UTC
Labels: Bug, Upstream, Pri: 1, Area - SQL Project
