### ISSUE TITLE
Add "Find in Object Tree" to context menu in Editor

### ISSUE THREAD

**Issue by jimkilliansentinel** [microsoft/azuredatastudio#22273] opened 2023-03-09 18:16 UTC
**Is your feature request related to a problem? Please describe.**
Locating a table or other object referenced in the SQL code in order to work with it can be daunting due to the sheer number of objects in the tree.

**Describe the solution or feature you'd like**
There's currently a "Go to Definition (F12)" in the context menu (which, BTW, doesn't work for the function I just tried). For a table, this opens a new editor window with a CREATE script for the table. Helpful for seeing the layout, but doesn't help with seeing the data.

I would like for there to be a "Find in Object Tree" (or whatever the correct wording would be) that would select the correct object in the object tree/list so that I can easily script it, redesign it, edit the data, or whatever other options are available. Would be nice if it worked for any object type (table, SP, function, etc.). I assume that if you can locate the definition for the existing F12 functionality, finding it in the tree is doable.

**Describe alternatives you've considered**
Add an option to search/filter the object tree for the name of the object I want to find. The filter option is available in SSMS. This still requires a lot of scrolling to get to the tree branch for the object type you want when there are tons of objects.

**Additional context**
Add the new Goto option just above or below the F12 option:
![image](https://user-images.githubusercontent.com/85969574/224116454-9ef09fdb-7d5c-4762-b572-ff0c4221716e.png)

**Comment by alanrenmsft** [comment] 2023-03-10 17:57
dupe of #22063

**Closed by alanrenmsft** 2023-03-10 17:57 UTC
Labels: Area - Query Editor, Enhancement, Triage: Needed
