### ISSUE TITLE
Files containing @ displayed incorrectly and leading to error

### ISSUE THREAD

**Issue by aersamkull** [microsoft/azuredatastudio#20181] opened 2022-07-27 15:23 UTC
Issue Type: <b>Bug</b>

1. Create a SQL Project with Files containing @, eg using Visual Studio SSDT
2. Open in Azure Data Studio
3. File shows in Azure Data Studio with %40 instead of @ and opening it fails

Extension version: 0.17.2
Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aersamkull** [comment] 2022-07-27 15:24
I have such files because of Azure AD Logins

**Comment by aersamkull** [comment] 2022-07-27 15:31
It seems that the csproj actually contains %40 in the filename, maybe some kind of encoding

**Comment by kisantia** [comment] 2022-08-09 15:58
closing as duplicate of #17020. Workaround is https://github.com/microsoft/azuredatastudio/issues/17020#issuecomment-966738340

**Closed by kisantia** 2022-08-09 15:58 UTC
Labels: Bug, Triage: Needed, Area - SQL Project
