### ISSUE TITLE
Publish to Github & login fails "...Please upgrade VS Code..."

### ISSUE THREAD

**Issue by ALZDBA** [microsoft/azuredatastudio#20022] opened 2022-07-13 11:18 UTC
- Azure Data Studio Version:1.37.0 ( **vscode 1.59.0**)
- OS Version: Win10 20H2

Steps to Reproduce:

1. Publish to Github 
2.it routes to login via Edge to https://vscode-auth.github.com/ and gives the message

I have upgraded VSCode and rebooted my laptop, still I cannot publish to github

Does this issue occur when all extensions are disabled?: Yes/No

![2022-07-13 13_17_05-Window](https://user-images.githubusercontent.com/4035114/178721565-a2c424fe-0d41-4a00-9e14-a72c265ed309.jpg)

**Comment by ALZDBA** [comment] 2022-07-13 11:20
Strange thing is when I start VSCode, it shows following information: !!!

**Version: 1.69.1 (user setup)**
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:24.514Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Charles-Gagnon** [comment] 2022-07-13 15:40
Duplicate of https://github.com/microsoft/azuredatastudio/issues/19979

As a workaround you can try publishing the branch using the git CLI and authenticating through that, after which you should be able to push commits through ADS again.

**Closed by Charles-Gagnon** 2022-07-13 15:40 UTC

**Comment by ALZDBA** [comment] 2022-08-09 12:34
> * Azure Data Studio Version:1.37.0 ( **vscode 1.59.0**)
> 
>     * OS Version: Win10 20H2
> 
> 
> Steps to Reproduce:
> 
>     1. Publish to Github
>        2.it routes to login via Edge to https://vscode-auth.github.com/ and gives the message
> 
> 
> I have upgraded VSCode and rebooted my laptop, still I cannot publish to github
> 
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> ![2022-07-13 13_17_05-Window](https://user-images.githubusercontent.com/4035114/178721565-a2c424fe-0d41-4a00-9e14-a72c265ed309.jpg)

**The reason for my problems was, I wasn't presented a "personal account" to use during the login process. 
Hence devops got mixedup because or the login failed (password) or the login succeeded but the userid no longer matched ( in the background), resulting in failed login.**

I managed to correct this and now ads seems to remember the account to use.
