### ISSUE TITLE
Notebooks have too much white space between cells

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#10351] opened 2020-05-12 06:27 UTC
- Azure Data Studio Version:
Version: 1.17.1 (user setup)
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-30T00:16:35.943Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a new notebook
2. Create a text cell, a code cell and a text cell.
You will see a lot of white spaces

ADS has lots of whitespace
![image](https://user-images.githubusercontent.com/6405919/81645564-a47e8800-93de-11ea-8a92-4d96e1de005c.png)

Jupyter Notebook has less whitespace which makes it more readable:
![image](https://user-images.githubusercontent.com/6405919/81645699-e4de0600-93de-11ea-8dfb-1e5ff4bab6da.png)

**Comment by Charles-Gagnon** [comment] 2020-05-12 15:55
Likely duplicate of https://github.com/microsoft/azuredatastudio/issues/10191 - should be fixed in master/insiders.

**Closed by Charles-Gagnon** 2020-05-12 15:55 UTC
Labels: Impact: Live site

**Comment by MsSQLGirl** [comment] 2020-05-12 15:57
Confirmed. It is a duplicate of #10191.
