### ISSUE TITLE
Graphical output of geospatial data

### ISSUE THREAD

**Issue by SQLThomas** [microsoft/azuredatastudio#1492] opened 2018-05-25 13:27 UTC
Issue Type: Feature Request

Is it planned to implement the graphical output of geospatial data as an additional result tab, like SSMS has it built in?

**Comment by kburtram** [comment] 2019-07-17 23:14
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/267.  Thanks for reporting.

**Closed by kburtram** 2019-07-17 23:14 UTC
Labels: Enhancement
