### ISSUE TITLE
Loop on canceling connection dialog

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#7332] opened 2019-09-24 00:00 UTC
Issue Type: <b>Bug</b>

Repro:
- Connect to Azure using the Object Explorer.
- From one of the subscriptions, click on a SQL database to connect to.
- A connection dialog will popup asking for credentials.
- Try canceling this dialog without entering credentials, to do something else.

ADS gets stuck in a loop. The cancel button brings up a "Login failed to..." message. Dismissing this message, brings back to the connection dialog. I had to close ADS to get out of this loop.

Expected: Cancel should just cancel and let the user resume their work.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (46.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.5.0

</details>

**Comment by abist** [comment] 2019-09-24 17:52
@qifahs I'm going to go ahead and close this issue since it' a duplicate of https://github.com/microsoft/azuredatastudio/issues/7332 and being tracked there.

**Closed by abist** 2019-09-24 17:52 UTC
Labels: Area: Data Explorer, Bug, Triage: Done
