### ISSUE TITLE
Execution taking time

### ISSUE THREAD

**Issue by veeresh224** [microsoft/azuredatastudio#23238] opened 2023-05-29 14:45 UTC
Type: <b>Bug</b>

After clicked on Run, query is taking more time trigger the execution. 

Azure Data Studio version: azuredatastudio 1.44.0 (Universal) (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:52:43.653Z)
OS version: Darwin arm64 22.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment] 2023-05-30 15:38
dupe of #23145

**Closed by alanrenmsft** 2023-05-30 15:38 UTC
