### ISSUE TITLE
UI overlapping after second query

### ISSUE THREAD

**Issue by fsmythe** [microsoft/azuredatastudio#16854] opened 2021-08-23 10:38 UTC
![Screenshot 2021-08-23 113414](https://user-images.githubusercontent.com/1161466/130434087-ad76b970-1b41-444c-bc80-1ceabeb9f19a.png)
Issue Type: <b>Bug</b>

Results after second query are all mushed, UI overlaps. (pictured)

Repeatable, happens every time, any query it happens the problem persists.

One column is a large HTML field, which seems to be the base of the issue. Even after manually changing the width of each displayed field the HTML column (4th) still displays from the far left, overlapping other fields.

Have to close tab and re run query for it to be fixed, then after another query the problem happens again.

1920*1080 at 125% DPI

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment] 2021-09-03 21:00
@fsmythe is it possible for you to share the data to reproduce the issue with us? I did a quick try with long html string but couldn't reproduce the issue. thanks! please make sure to remove the sensitive information

**Comment by kburtram** [comment] 2021-09-22 21:38
Closing based on previous comment.  Please let us know if you can provide additional reproduction steps or diagnostic log information.  Thanks!

**Closed by kburtram** 2021-09-22 21:38 UTC
Labels: Bug, Area - Query Editor, Triage: Done
