### ISSUE TITLE
notebook find results color is not cleared after the text has been changed

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#11175] opened 2020-07-02 00:01 UTC
Steps to Reproduce:

1. open a notebook and add a code cell with the following text: 
`
test blah blah blah
`
2. open the find widget of notebook (cmd+F on macOS) and type in test
3. now the text 'test' should be highlighted
4. update the cell text and change 'test' to 'abc'

expected: nothing is highlighted
actual: 'a' is still highlighted
<img width="634" alt="Screen Shot 2020-07-01 at 4 59 08 PM" src="https://user-images.githubusercontent.com/13777222/86302042-63c01580-bbbc-11ea-9631-178cbb1cd16a.png">

**Comment by alanrenmsft** [comment] 2020-07-02 00:21
also, not sure how did it get into this state, multiple highlights + highlights visible even after closing the find widget, I can't repro this one though:
<img width="1246" alt="Screen Shot 2020-07-01 at 5 20 12 PM" src="https://user-images.githubusercontent.com/13777222/86302966-3e80d680-bbbf-11ea-9abf-1ec8282edc58.png">

**Comment by chlafreniere** [comment] 2020-07-06 16:05
We idenfieid a regression recently here and already fixed one issue. Will take a look. Thanks.

**Comment by chlafreniere** [comment] 2020-07-06 19:47
Dupe of #11120.

**Closed by chlafreniere** 2020-07-06 19:47 UTC
Labels: Area - Notebooks, Bug, Triage: Done
