### ISSUE TITLE
clear output for entire .ipynb file

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3948] opened 2019-02-06 23:35 UTC
- Azure Data Studio Version: 1.4.4-insider

Steps to Reproduce:

1. Open a notebook that has been run before
2. In order to clear the output for the whole file, you have to individually clear each cell
There should be a way to do this with one command or action or button or something

**Comment by chlafreniere** [comment] 2019-03-27 04:58
Dupe of #4705, which is out for PR 😃.

**Closed by chlafreniere** 2019-03-27 04:58 UTC
Labels: notebooks
