### ISSUE TITLE
A11y_AzureDataStudioAAE_Azure ADC(Preview)_Controller Configuration_Keyboard: Instructions are not provided for password edit field complexity requirement on tab navigation. 

### ISSUE THREAD

**Issue by sspatil123** [microsoft/azuredatastudio#15729] opened 2021-06-16 09:14 UTC
https://user-images.githubusercontent.com/85863999/127467399-60eed41d-ebdd-4321-9a99-15e5623f67fb.mp4

“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudio_AAE_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#Keyboard;#WCAG3.3.2;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio-AAE
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure arc and Azure data ClI
2. Connect to Azure Arc Controller
3. Tab till "Connection" and tab to see more button
4. Tab to "New Deployment" and Azure ADC(Preview) and then tab select button
5. Deployment Prerequisite page will open and tab on next "Select from existing Kubernetes cluster" will open
6. Tab till "Next" button and 'Controller configuration' will open
7. Tab till 'Password' item

### Actual:
When keyboard focus is on "password" edit field, user does not get information of password complexity requirement.

Similar issue is present following scenarios:
PostgreSQl Hyperscale server groups-Provide azure enabled PostgreSQl Hyperscale server groups
Azure Sql Managed Instance- Provide azure sql managed instance parameters

### Expected:
Before focus going to password edit field user should get requirement of password complexity.
### 
User Impact:
Keyboard users will not know information of password requirement to be filled in edit field.

**Comment by Charles-Gagnon** [comment] 2021-07-29 18:29
@sspatil123 I'm closing this as working as intended given that the standard behavior is for us not to display the actual password complexity requirements for these fields.

Instead when the user submits the form an error will pop up (and be read by the screen reader) informing them where they can go to learn about the password complexity requirements. 

Given that the behavior is the same for both screen reader and non-screen reader scenarios this doesn't seem to be an actual issue - unless there's some requirement that screen readers must display complexity information even if the normal input doesn't display it either.

**Closed by Charles-Gagnon** 2021-07-29 18:29 UTC
Labels: A11y_AzureDataStudio, Area - Azure Arc, Bug, Impact: Accessibility, Triage: Done

**Comment by Shivamd1** [comment] 2022-01-25 12:04
closing not repro

![image](https://user-images.githubusercontent.com/60880975/150973475-a9ae6201-54a0-468b-be57-03b492a8df66.png)

**Comment by Harika1702** [comment] 2023-02-06 10:39
GitHub Tags: #Closed;
