### ISSUE TITLE
AzureData Tools Database projects unable to open SQL files with @ in filename.

### ISSUE THREAD

**Issue by sgarwood** [microsoft/azuredatastudio#20974] opened 2022-10-25 21:45 UTC
- Azure Data Studio Version: 1.39.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Optional-  Clone https://github.com/sgarwood/dontAtMeADS.git repo and open `SQLProj` in Visual Studio SSDT. Click on `Create@User.sql`  in Solution Explorer. Observe the source code opens for the procedure.
2. Open new Azure Data Studio Window
3. Open Database Projects Panel.
4. Open Existing -> Remote git repository -> Enter `https://github.com/sgarwood/dontAtMeADS.git` as Git repository URL
5. Let ADS restart when prompted and select Yes to trust workspace.
6. `The targets, references, and system database references need to be updated to build the project 'dontAtMeSSDT'. If the project was created in SSDT, it will continue to work in both tools. Do you want to update the project?` When prompted select `Yes` 
7. Attempt to Open `Create%40User.sql` in Database projects
9. See error `Unable to open 'Create%40User.sql - disconnected': Unable to read file 'c:\Users\sgarwood\source\repos\azure-data-studio\dontAtMeADS\dontAtMeSSDT\Create%40User.sql' (Error: Unable to resolve nonexistent file 'c:\Users\sgarwood\source\repos\azure-data-studio\dontAtMeADS\dontAtMeSSDT\Create%40User.sql').`

Looks like the escaping of the @ character in the `.sqlproj` file is not being deescaped when convering back to  a file path on disk to open the file.

Does this issue occur when all extensions are disabled?: NA required extension is Database Project

Sorry all- got another bug for you- hopefully this one is easier to track down and stick a debugger on straight away. 
Thanks for all your efforts.

**Comment by sgarwood** [comment] 2022-10-25 21:48
@Benjin Hopefully a clear repro for one of the other issues I mentioned earlier today. Thanks once again

**Comment by sgarwood** [comment] 2022-10-25 21:57
Also seems to case issues when trying to perform a schema compare

1. Open new schema compare
1. Select a Database as Source
2. Select Above SQL project as Target
3. Select Compare
4. See the error `Schema Compare failed: Unexpected exception caught during population of target model: Could not find file 'c:\Users\sgarwood\source\repos\azure-data-studio\dontAtMeADS\dontAtMeSSDT\Create%40User.sql'.`

**Comment by kisantia** [comment] 2022-10-26 18:14
closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/17020. Workaround is https://github.com/microsoft/azuredatastudio/issues/17020#issuecomment-966738340

**Closed by kisantia** 2022-10-26 18:14 UTC
Labels: Area - SQL Project
