### ISSUE TITLE
Azure core extension: Filtering to find my SQL server instance

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#7912] opened 2019-10-22 22:37 UTC
Issue Type: <b>Feature Request</b>

I have a lot of subscriptions I have access to. My Azure core list is really long and it is hard to find the server/db I am looking for. I know the name of the server/db, I should be able to filter the list for it. A filter box on top of the list to type in the name would help a lot.

Azure Data Studio version: azuredatastudio 1.13.0 (05a53af085861999ed8dc99596cd55829387d490, 2019-10-22T07:41:49.347Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Charles-Gagnon** [comment] 2019-10-22 22:42
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/860

(That one specifically mentions OE, not Azure subscriptions, but I think it makes sense to just bundle the requests into a single issue since they're all essentially the same)

**Closed by Charles-Gagnon** 2019-10-22 22:42 UTC
Labels: Area - Data Explorer, Enhancement
