### ISSUE TITLE
Do not bring databases online when connecting to serverless Azure SQL

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#21475] opened 2022-12-22 22:46 UTC
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

Situation:
Using Azure Data Studio as a tool
We have got an Azure SQL server with 4 serverless databases. 1 of these databases is ONLINE, and 3 databases are OFFLINE.
Connection is made with ADS following settings:
- Server filled in
- Azure AD
- Account: myAccount
- Database: <default>
- Encrypt: TRUE
 
Result:
1. Connection established, 2 folders are listed below the server ("Databases" and "Security"). When looking in Azure Portal NONE of the 3 databases go online, That's good!
2. When collapsing folder "Databases" it is resuming database2, and then the listing of the databases fails.
3. database2 is now also online. Rightclick on "databases" and click refresh. Now database 3 is resuming and goes online. List of databases is still failing because database 4 is not yet ONLINE. When database4 is also online I finally see a list of all databases below the server (in Azure Data Studio).
4. This behaviour is not what we expect. With tool SSMS we can connect with the server and see all databases in the list WITHOUT going ONLINE.
 
Additional:
In SSMS this behaviour is different. There you can list all databases without being them online. Only when you collapse or doubleclick on a specific database, the database goes ONLINE. Which is exactly what we want as a behaviour.
However, we have developers who like to use ADS as well.
Hope the info is sufficient and understandable. If not, please let me know.

Copied from: https://feedback.azure.com/d365community/idea/21815a9c-6580-ed11-a81b-000d3adb7ffd

Does this issue occur when all extensions are disabled?: Yes

**Comment by erinstellato-ms** [comment] 2022-12-22 22:47
Also conversation about the same issue here: https://learn.microsoft.com/en-us/answers/questions/1121676/index.html

**Comment by MarkieMark73** [comment] 2022-12-23 08:50
Thanks Erin, really appreciated!

**Comment by cheenamalhotra** [comment] 2022-12-23 18:38
For reference, this is related to #5173

**Comment by Charles-Gagnon** [comment] 2022-12-23 19:39
It also seems like a duplicate of https://github.com/microsoft/azuredatastudio/issues/8557

And is also related to https://github.com/microsoft/azuredatastudio/issues/6450 - specifically the investigation that I did found what I believe to be the root problem with how we're using SMO to query

https://github.com/microsoft/azuredatastudio/issues/6450#issuecomment-1111578698

David and I got what should have been a fix for it out, but that caused a regression so had to be rolled back. It looks like the fix for that is still a work in progress too - @shueybubbles is that something you're still planning on doing?

**Comment by erinstellato-ms** [comment] 2022-12-23 20:01
@cheenamalhotra and @Charles-Gagnon thank you both for looking at this and doing some more digging.  Will definitely reconvene with @shueybubbles after break.

**Comment by Charles-Gagnon** [comment] 2022-12-23 20:17
Also will throw it out there that this isn't necessarily a issue we *need* to solve in SMO. SSMS gets by just fine because it uses a different way of querying the databases (SFC queries directly instead of the full SMO objects). So if we were to modify ADS to do the same then it wouldn't require any changes in SMO. 

That being said - having SMO not connect to every single database when the DB collection is iterated is probably something we should be doing anyways (only connecting when a property is specifically requested that requires it).

**Comment by shueybubbles** [comment] 2022-12-23 21:16
I already rolled back the rollback in ADO. I am going to put out a new v170 build soon to test with.

**Comment by cheenamalhotra** [comment] 2023-01-03 21:22
Posting latest update, I followed this with David and on validating with v170 we found issue continues to exist. 
On debugging, we found the root cause is related to SMO trying to fetch 'Status' (field) for all children in list, when STS tries to call `ClearAndInitialize()` for all list elements. This 'Status' field (because its present), ends up calling `SqlSmoObject.DoDatabaseSpecialCase` which trigger flow to query respective database element in the list.

As of SMO v170.8.0, the issue continues to exist.

**Closed** 2023-01-10 20:08 UTC
Labels: Bug, Area - Object Explorer, Pri: 2, Triage: Done, Size: L, External
