### ISSUE TITLE
changing to python3 kernel hangs on a non domain joined local user windows vm

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#11631] opened 2020-08-04 01:55 UTC
- Azure Data Studio Version:
Version: 1.21.0-insider (user setup)
Commit: f941f99
Date: 2020-08-03T05:36:14.244Z
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

- Steps to Reproduce:

1. Login into a windows hyper-v host machine. The bug was reproduced from SQLTOOLS-HEKA1
2. From Hyper-V manager right click on the hostname and click 'Quick Create'
![image](https://user-images.githubusercontent.com/41588310/89242273-fede4d80-d5b5-11ea-9f7e-1b4f235f90c8.png)
3. Select 'Windows 10 dev environment' and then click on 'Create Virtual Machine'
![image](https://user-images.githubusercontent.com/41588310/89242775-30a3e400-d5b7-11ea-803c-7498401d04eb.png). Click through the VM creation wizard with all default settings. 
4. Connect to the VM once it has been created.
5. Log into the VM as the default local windows user account (called 'user'). Kindly note that this vm is in a workgroup not joined to a domain.
6. Download the Windows User Installer insider's build msi from: https://azuredatastudio-update.azurewebsites.net/latest/win32-x64-user/insider
7. Run the downloaded msi and click through using default options of the installer. Except on 'Select Additional Tasks' page, check all of the following options:
![image](https://user-images.githubusercontent.com/41588310/89243100-0272d400-d5b8-11ea-858d-728ad2de495a.png)
8. As documented in https://github.com/microsoft/azuredatastudio/issues/11630, there is a popup error reported during installation. Click ok to dismiss the pop-up and everything proceeds to completion.
9. Create a new notebook when the ADS starts up.
![image](https://user-images.githubusercontent.com/41588310/89243704-7661ac00-d5b9-11ea-9200-9a05307e1c62.png)
10. In the new notebook that opens change Kernel from 'SQL' to 'Python3'. This pops open the following dialog:
![image](https://user-images.githubusercontent.com/41588310/89243763-a0b36980-d5b9-11ea-9565-49a04013e5ab.png)
Keep everything the default and click on install.
11. Notebooks output channel opens up at the bottom as python installation proceeds. It ends with the following entry:
```
... Starting Notebook server
    > "C:\Users\User\azuredatastudio-python\0.0.1\python.exe" "c:\Users\User\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --no-mathjax --notebook-dir "c:\Users\User" --port=9840 --NotebookApp.token=6c59df721fdfdd3e97fbdcb0c0f9e8f902f643083e24f838
```
**Actual:**
However, the kernel does not change to 'Python3' and remains stuck at 'Changing Kernels'. If one starts another new notebook and one changes the Kernel in that 2nd new notebook to 'Python3' even that does not finish and remains stuck in 'Changing Kernels' state.

**Expected:**
The kernel should change to Python3 successfully and one should be able to create and execute python cells.

**Comment by chlafreniere** [comment] 2020-08-04 17:34
Dupe of #11607.

**Closed by chlafreniere** 2020-08-04 17:34 UTC
Labels: Area - Notebooks, Bug, Triage: Needed
