### ISSUE TITLE
Unable to install Kubernetes extension for VS Code in ADS

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/azuredatastudio#4599] opened 2019-03-19 17:58 UTC
Issue Type: <b>Bug</b>

I tried to load the [Kubernetes extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools) into ADS and received the following error message.

Unable to install version '0.1.18' of extension 'ms-kubernetes-tools.vscode-kubernetes-tools-0.1.18' as it is not compatible with Azure Data Studio '1.5.1'.

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.11.0
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.5.2
sql-search|Red|0.3.1

</details>

**Comment by kburtram** [comment] 2019-03-19 18:17
@alanrenmsft do you think this is related to the Engine check changes we made in 1.5.1?  I can see the extension asks for VS Code 1.31, which is what ADS 1.5.1 is built on.

**Comment by MattIrv** [comment] 2019-03-19 18:20
@SQLvariant I took a look at this and it's failing to install because the current version of the Kubernetes extension depends on VS Code 1.31 and the official release of Azure Data Studio isn't up to date with that yet.

Our insiders build is up to date with 1.31 so if you install the insiders build ([links in our readme](https://github.com/Microsoft/azuredatastudio/blob/master/README.md)) I've verified that you can install the extension. 

If insiders builds are too unstable for you, it looks like [version 0.1.15 of the extension](https://github.com/Azure/vscode-kubernetes-tools/tree/0.1.15) is compatible but you would have to build it yourself since the VS Code marketplace only has the latest version.

**Comment by MattIrv** [comment] 2019-03-19 18:24
@kburtram @alanrenmsft the error message is coming from the VS Code engine version check that we reenabled for this release. Prior to Alan's changes it was commented out

**Comment by alanrenmsft** [comment] 2019-03-19 18:48
@SQLvariant, the error message itself is by design. as Matt pointed out, you can use the insider build of ADS, but if you really need the latest k8s extension in ADS stable release, you can update the engine requirement in extension's package.json to * and build a vsix package by yourself.

**Comment by alanrenmsft** [comment] 2019-03-20 18:41
closing the issue as we have provided instructions.

**Closed by alanrenmsft** 2019-03-20 18:41 UTC
Labels: bug, extensibility
