### ISSUE TITLE
Line break get lost when saving or retrieving data in edit table mode

### ISSUE THREAD

**Issue by StaniAlex** [microsoft/azuredatastudio#6205] opened 2019-06-28 13:53 UTC
- Azure Data Studio Version: 1.8.0

Steps to Reproduce:

Case 1: Saving Data
1. Right click on a table
2. Select 'Edit Data'
3. Copy Text from another location
-> Sample Text:
This is the frist line.
This is the 2nd line.
4. Sample text will be saved as: This is the frist line.This is the 2nd line.
And not like: This is the frist line.
This is the 2nd line.

Case 2: Retrieving Data
1. Right click on a table
2. Select 'Edit Data'
3. Text is saved like in the database:
This is the frist line.
This is the 2nd line.
4. Copying and pasting the content of the field results in: This is the frist line.This is the 2nd line.
instead of: This is the frist line.
This is the 2nd line.

**Comment by Charles-Gagnon** [comment] 2019-06-28 14:20
Thanks for the report @StaniAlex! I'm closing this as a duplicate of #1303 - please follow that for any updates on this issue.

**Closed by Charles-Gagnon** 2019-06-28 14:20 UTC
Labels: Bug
