### ISSUE TITLE
SQL Results Panel is rendering very slow

### ISSUE THREAD

**Issue by wendellestradairely** [microsoft/azuredatastudio#6628] opened 2019-08-07 01:13 UTC
Issue Type: <b>Bug</b>

Run a select statement to query a table with a few hundred or a few thousand records:

SELECT * FROM <table>

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.41.0
cms|Mic|0.3.0
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0
schema-compare|Mic|0.4.0
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by anthonydresser** [comment] 2019-08-07 18:07
Can you try to disable the user options `resultsGrid.autoSizeColumns` and see if that makes a noticeable difference for you

**Comment by whizkidwwe1217** [comment] 2019-08-07 20:45
It turned out to be an issue with Windows desktop with dual monitors. I just reconfigured the dual monitor and the issue was gone.

**Comment by wendellestradairely** [comment] 2019-08-07 23:44
I tried to disable `resultsGrid.autoSizeColumns` but it's still rendering very slow with just a thousand records. You can watch the attached recording below. _(I zipped the mp4 screen recording because github doesn't allow attaching videos)_.
[screen recording.zip](https://github.com/microsoft/azuredatastudio/files/3479254/screen.recording.zip)

**Comment by anthonydresser** [comment] 2019-08-08 00:24
How many columns are in your result set?

**Comment by wendellestradairely** [comment] 2019-08-08 01:17
I have like 68 of them. I guess that's making the results grid to render slow. But I also have another table with just 15 columns and 700 records in total and still takes time to render the results. Although it's just a couple of seconds delay and not really a big problem but I think its performance can still be improved.

**Comment by anthonydresser** [comment] 2019-08-08 19:06
We have known perf issues when it comes to large number of columns #4875 #5477 . We have some work streams on the back burner to increase the perf of the table overall.

**Comment by kburtram** [comment] 2021-08-18 00:12
Closing older issues.  This is a duplicate of several other active issues we're currently tracking for upcoming investigation.

**Closed by kburtram** 2021-08-18 00:12 UTC
Labels: Area - Performance, Area - Query Editor, Triage: Done
