### ISSUE TITLE
CMS can't register azure ad auth type

### ISSUE THREAD

**Issue by drdamour** [microsoft/azuredatastudio#10872] opened 2020-06-11 07:57 UTC
- Azure Data Studio Version:1.18.0

Steps to Reproduce:

1. add a centralized server
2. attempt to add a server registration
3. the authentication option only lists windows authentication and non of the AAD options

**Comment by cheenamalhotra** [comment] 2023-07-21 02:01
Duplicate of #17264

**Closed by cheenamalhotra** 2023-07-21 02:01 UTC
Labels: Enhancement, Triage: Done, Area - CMS

**Comment by drdamour** [comment] 2024-04-07 00:28
think this was a mistaken dupe...that other ticket is about adding a cms...this is about registering a new server within a cms
