### ISSUE TITLE
Table desginer

### ISSUE THREAD

**Issue by drsa353** [microsoft/azuredatastudio#22060] opened 2023-02-28 16:29 UTC
Issue Type: <b>Performance Issue</b>

The table desginer most of times opens very slow

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	 17836	azuredatastudio main
    0	    93	 10456	   extensionHost
    0	    75	 10984	     "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10456
    0	    26	 18416	     "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.4.1.5\MicrosoftSqlToolsCredentials.exe" --locale en --log-file c:\Users\drsa3\AppData\Roaming\azuredatastudio\logs\20230228T184005\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical --autoflush-log
    0	     6	 16788	       console-window-host (Windows internal process)
    0	   139	 20284	     "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.4.1.5\MicrosoftSqlToolsServiceLayer.exe" --locale en --log-file c:\Users\drsa3\AppData\Roaming\azuredatastudio\logs\20230228T184005\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical --autoflush-log
    0	     8	 20308	       console-window-host (Windows internal process)
    0	    28	 20472	     "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.4.1.5\SqlToolsResourceProviderService.exe" --locale en --log-file c:\Users\drsa3\AppData\Roaming\azuredatastudio\logs\20230228T184005\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical --autoflush-log
    0	     6	 18360	       console-window-host (Windows internal process)
    0	   124	 12580	   gpu-process
    0	    86	 14264	   issue-reporter
    0	    68	 18496	   shared-process
    0	    66	 10828	     ptyHost
    0	    67	 19156	     fileWatcher
    0	    37	 18532	   utility-network-service
    1	   188	 18652	   window (drsa353 - HMISDB - New Table - Azure Data Studio)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
dacpac|Mic|1.12.0
import|Mic|1.5.4
profiler|Mic|0.12.2
query-history|Mic|0.5.3

(3 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment] 2023-03-01 03:51
1. what is the target server?
2. what is the network work latency between your client and server?
3. if it is an Azure resource, what is the service tier and performance level of it?
4. how many tables and other objects are there in the database?
5. how long does it take for the designer to load? SSMS vs ADS.

**Comment by alanrenmsft** [comment] 2023-03-06 18:37
dupe of #22025

**Closed by alanrenmsft** 2023-03-06 18:37 UTC
Labels: Bug, Needs More Info, Triage: Done, Area - Designer, Subarea - Perf
