### ISSUE TITLE
Way to change App_Name()

### ISSUE THREAD

**Issue by lehne** [microsoft/azuredatastudio#9533] opened 2020-03-10 20:50 UTC
**Is your feature request related to a problem? Please describe.**
I am unable to run certain queries because they depend on the App_Name() function returning something particular. In SSMS, I can change the App Name in the advanced connection properties. I have found no way to change it in Azure Data Studio. It is always "azdata-Query"

**Describe the solution or feature you'd like**
Add a text field for connection to allow changing App_Name() or perhaps a setting in the json file that is documented.

**Describe alternatives you've considered**
I've not been able to find any documentation explaining how to change this.

**Additional context**
The App_Name() function is described here:
https://docs.microsoft.com/en-us/sql/t-sql/functions/app-name-transact-sql?view=sql-server-2017

**Comment by genpri** [comment] 2020-11-03 09:44
in our company we also have several queries depending on app_name() rendering ADS a non-option for us, which is sad because the tool otherwise would be perfect for our daily development routine.
waiting patiently for this enhancement.

**Comment by yooakim** [comment] 2021-11-25 16:12
Please ad us to the wish list, being able to specify "[Application Name](https://docs.microsoft.com/en-us/sql/t-sql/functions/app-name-transact-sql?view=sql-server-ver15)" on the connection settings in Azure Data Studio would be very useful for us.

It works fine with SSMS and other tools but in the dialog for connection in Azure Data Studio /Advanced properties... there is place for entering the application name.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/862546/143474199-2d3baa94-cc1f-4260-9d78-2489edb4a225.png">

**Comment by cheenamalhotra** [comment] 2022-12-16 21:05
Closing as duplicate of #3991

**Closed by cheenamalhotra** 2022-12-16 21:05 UTC
Labels: Area - Connection, Enhancement, Triage: Done
