### ISSUE TITLE
Quick search in the "Connections" panel

### ISSUE THREAD

**Issue by Tavriets** [microsoft/azuredatastudio#6963] opened 2019-08-26 23:46 UTC
Issue Type: <b>Feature Request</b>

That would be quite helpful if user could search/filter/highlight entries in the "Connections" window. For example, quickly find table, view or function in the tree by typing its name.

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Charles-Gagnon** [comment] 2020-08-19 21:35
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 - this has been added and will be available in the upcoming insiders build for early testing. Feedback is appreciated!

**Closed by Charles-Gagnon** 2020-08-19 21:35 UTC
Labels: Area - Connection, Enhancement, Triage: Done
