### ISSUE TITLE
Query: conversion overflow error for large number

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3865] opened 2019-01-31 00:11 UTC
Issue Type: <b>Bug</b>

Enter query `select 12345678912345678912345678912345678912`, run. End up with `Conversion overflows` error instead of showing the single cell output which shows in SSMS.

This is a bad error since it's client-side conversion (either in SqlToolsService or, worse, might be a .Net Core SqlClient issue since I remember this happening before). Needs debugging & investigation.

Azure Data Studio version: Azure Data Studio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:48:43.514Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.35.2
sql-vnext|Mic|0.9.1

</details>

**Comment by saurabh500** [comment] 2019-01-31 01:30
Duplicate of https://github.com/Microsoft/azuredatastudio/issues/275

**Comment by kburtram** [comment] 2019-02-25 21:40
Closing as duplicate of #275.

**Closed by kburtram** 2019-02-25 21:40 UTC
Labels: bug, query execution
